function result = gpenmpcEvaluateOrdinaryB2Rollout(decision, method, trajectory, phaseState, observation, context, gpModel, causalContextF17, config)
%GPENMPCEVALUATEORDINARYB2ROLLOUT Native eight-step B1/ordinary-B2 rollout.
%
% Ordinary B2 weights the GP mean by trust, axis agreement and responsibility
% in translational prediction. B1 and B2 share the total robust tube.
% GP variance supports confidence and validity checks.

arguments
    decision (1,:) double
    method (1,1) string
    trajectory (1,1) struct
    phaseState (1,1) struct
    observation (1,1) struct
    context (1,1) struct
    gpModel struct
    causalContextF17 (1,1) struct
    config (1,1) struct
end
validateIdentity(method, decision, context, config);
isB2 = method == config.method;
if isB2 && isempty(fieldnames(gpModel))
    error("gpenmpcEvaluateOrdinaryB2Rollout:Model", ...
        "Ordinary B2 requires the frozen native sparse GP model.");
end

dt = config.prediction_step_s;
phaseBlocks = decision(1:config.control_blocks);
outerCorrectionF = decision(config.control_blocks + (1:3)).';
controls = repelem(phaseBlocks, config.move_block_size);
p = column(observation.position_m, 3, "position_m");
v = column(observation.velocity_mps, 3, "velocity_mps");
phase = double(phaseState.progress_s);
rate = double(phaseState.progress_rate);
previousPhaseAcceleration = double(phaseState.previous_phase_acceleration_s_inv);
previousForce = column(observation.previous_desired_force_n, 3, "previous_desired_force_n");
previousOuterCorrectionI = column( ...
    observation.previous_outer_acceleration_correction_i_mps2, 3, ...
    "previous_outer_acceleration_correction_i_mps2");
wind3 = [column(observation.wind_estimate_xy_mps, 2, "wind_estimate_xy_mps"); 0.0];
payloadKg = double(observation.payload_kg);
predictedBodyRate = column(observation.body_rate_rad_s, 3, "body_rate_rad_s");
mass = context.base_mass_kg + payloadKg;
sigmaP = zeros(3, 1);
sigmaV = zeros(3, 1);
hardInvalid = false;
currentHardInvalid = false;
terminalExecutionPower = 0.0;
expectedTerminalPhase = min(trajectory.total_duration_s, ...
    phase + config.horizon_steps .* dt);
initialPhase = phase;
if isfield(causalContextF17, "values")
    predictedContext = double(causalContextF17.values(:));
else
    predictedContext = [1.0; 0.0; 0.0; 0.0];
end
contextValid = isfield(causalContextF17, "valid") ...
    && logical(causalContextF17.valid) && numel(predictedContext) == 4 ...
    && all(isfinite(predictedContext));
gpAgreementWeightF = ones(3, 1);
if isfield(causalContextF17, "runtime_gp_axis_weight_f")
    gpAgreementWeightF = double( ...
        causalContextF17.runtime_gp_axis_weight_f(:));
    if numel(gpAgreementWeightF) ~= 3 ...
            || any(~isfinite(gpAgreementWeightF)) ...
            || any(gpAgreementWeightF < 0.0) ...
            || any(gpAgreementWeightF > 1.0)
        error("gpenmpcEvaluateOrdinaryB2Rollout:GpAgreementWeight", ...
            "Runtime GP agreement weights must be finite and within [0,1].");
    end
end
coordinatedGpExecution = isB2 ...
    && isfield(config, "coordinated_gp_execution_feedforward_enabled") ...
    && logical(config.coordinated_gp_execution_feedforward_enabled);
coordinatedArchitectureEnabled = isfield(config, "coordinated_architecture_enabled") ...
    && logical(config.coordinated_architecture_enabled);
coordinatedGpMethodEnabled = coordinatedArchitectureEnabled && isB2;
physicalGpEnabled = coordinatedGpExecution;
if coordinatedArchitectureEnabled
    physicalGpEnabled = isB2 ...
        && logical(config.coordinated_physical_gp_application_enabled);
end
gpResponsibilityBlend = 1.0;
predictedFilteredMeanF = zeros(3, 1);
observerShadowI = optionalVector3(observation, ...
    "runtime_vertical_observer_shadow_i_mps2", zeros(3,1));
responsibilityGateEnabled = coordinatedGpExecution ...
    && isfield(config, "gp_responsibility_gate_enabled") ...
    && logical(config.gp_responsibility_gate_enabled);
if responsibilityGateEnabled
    gpResponsibilityBlend = optionalScalar(causalContextF17, ...
        "runtime_gp_responsibility_blend", 0.0);
    gpResponsibilityBlend = min(max(gpResponsibilityBlend, 0.0), 1.0);
    predictedFilteredMeanF = optionalVector3(causalContextF17, ...
        "runtime_gp_filtered_mean_f_mps2", zeros(3,1));
end

initialReference = gpenmpcPhaseReference(trajectory, phase, rate, ...
    previousPhaseAcceleration, 0.0);
initialReference.acceleration_mps2 = ...
    initialReference.acceleration_mps2 + previousOuterCorrectionI;
initialAir = initialReference.velocity_mps - wind3;
initialDrag = context.nominal_drag_n_per_mps2(:) .* initialAir .* abs(initialAir);
initialTrackingAcceleration = initialReference.acceleration_mps2 ...
    + context.position_gain_s2(:) .* (initialReference.position_m - p) ...
    + context.velocity_gain_s(:) .* (initialReference.velocity_mps - v);
initialForceWithoutRobust = mass .* (initialTrackingAcceleration ...
    + [0.0; 0.0; context.gravity_mps2]) + initialDrag;
predictedCommonRobustI = clipNorm( ...
    (previousForce - initialForceWithoutRobust) ./ mass, ...
    config.raw.common_inner_loop_predictor.combined_cap_mps2);
executionAligned = executionConsistentCostEnabled(config);
if executionAligned
    predictedRotation = gpenmpcQuaternionRotation( ...
        column(observation.quaternion_wxyz, 4, "quaternion_wxyz"));
    previousPredictedRotor = column( ...
        observation.previous_rotor_command_n, 6, "previous_rotor_command_n");
else
    predictedRotation = eye(3);
    previousPredictedRotor = zeros(6, 1);
end

stageRows = repmat(stageTemplate(config), config.horizon_steps, 1);
diagnosticRows = repmat(diagnosticTemplate(), config.horizon_steps, 1);
for index = 1:config.horizon_steps
    targetPhaseAcceleration = controls(index);
    transition = gpenmpcJerkBoundedReferenceTransition(trajectory, phase, rate, ...
        previousPhaseAcceleration, targetPhaseAcceleration, ...
        previousOuterCorrectionI, outerCorrectionF, dt, ...
        config.reference_transition_jerk_limit_mps3);
    reference = transition.reference;
    referenceAir = reference.velocity_mps - wind3;
    dragFeedforward = context.nominal_drag_n_per_mps2(:) ...
        .* referenceAir .* abs(referenceAir);
    trackingAcceleration = reference.acceleration_mps2 ...
        + context.position_gain_s2(:) .* (reference.position_m - p) ...
        + context.velocity_gain_s(:) .* (reference.velocity_mps - v);
    robustFrame = transition.reference_frame_i_from_f;
    curvature = transition.reference_curvature;
    slidingI = v - reference.velocity_mps ...
        + config.raw.common_inner_loop_predictor.lambda_position_s_inv(:) ...
        .* (p - reference.position_m);
    desiredForceForFeature = mass .* (trackingAcceleration ...
        + predictedCommonRobustI + [0.0; 0.0; context.gravity_mps2]) ...
        + dragFeedforward;

    meanI = zeros(3, 1);
    gpControlTargetI = zeros(3, 1);
    gpAuthority = 0.0;
    gpPredictionAuthorityF = zeros(3,1);
    gpPhysicalAuthorityF = zeros(3,1);
    responsibility = gpenmpcComputeGpResponsibility( ...
        0.0, double(config.gp_mean_scale), 0.0, zeros(3,1), ...
        zeros(3,1), false, double(config.minimum_soft_trust), 0.0);
    meanF = zeros(3, 1);
    filteredMeanF = zeros(3, 1);
    halfWidthF = zeros(3, 1);
    trust = 0.0;
    supportDistance = 0.0;
    latentMaximum = 0.0;
    sampleInvalid = false;
    gpFrame = robustFrame;
    featuresF17 = zeros(17, 1);
    if isB2
        sampleInvalid = ~contextValid;
        if ~sampleInvalid
            featuresF17 = gpenmpcBuildAeroF17Features( ...
                v, reference, robustFrame, wind3, payloadKg, ...
                desiredForceForFeature, curvature, ...
                predictedContext, context);
            prediction = gpenmpcSparseGpPredict(gpModel, featuresF17.');
            meanF = prediction.mean_mps2(1, :).';
            halfWidthF = prediction.calibrated_half_width_mps2(1, :).';
            trust = double(prediction.trust(1));
            supportDistance = double(prediction.support_distance(1));
            latentMaximum = max(prediction.latent_variance_standardized(1, :));
            sampleInvalid = logical(prediction.hard_invalid(1));
            if sampleInvalid
                trust = 0.0;
                meanF = zeros(3, 1);
            end
            filteredMeanF = meanF;
            if responsibilityGateEnabled
                meanFilterGain = 1.0 - exp(-dt ./ ...
                    double(config.responsibility_gp_mean_filter_time_constant_s));
                predictedFilteredMeanF = predictedFilteredMeanF ...
                    + meanFilterGain .* (meanF - predictedFilteredMeanF);
                filteredMeanF = predictedFilteredMeanF;
            end
            if coordinatedGpMethodEnabled
                responsibility = gpenmpcComputeGpResponsibility( ...
                    gpResponsibilityBlend, double(config.gp_mean_scale), ...
                    trust, gpAgreementWeightF, filteredMeanF, ...
                    ~sampleInvalid, double(config.minimum_soft_trust), ...
                    double(config.coordinated_exact_b1_tolerance));
                meanI = gpFrame * responsibility.weighted_mean_f_mps2;
                gpPredictionAuthorityF = responsibility.alpha_effective_f;
            else
                effectiveAgreementWeightF = gpAgreementWeightF ...
                    .* gpResponsibilityBlend;
                gpPredictionAuthorityF = min(max(config.gp_mean_scale .* trust ...
                    .* effectiveAgreementWeightF, 0.0), 1.0);
                meanI = gpFrame * (gpPredictionAuthorityF .* filteredMeanF);
            end
        end
        hardInvalid = hardInvalid || sampleInvalid;
        if index == 1
            currentHardInvalid = sampleInvalid;
        end
    end

    boundaryF = config.raw.common_inner_loop_predictor.boundary_layer_mps(:);
    totalRadiusF = config.common_robust_total_radius_f_mps2(:);
    if coordinatedArchitectureEnabled
        totalRadiusF = config.coordinated_b1_radius_f_mps2(:);
        composition = gpenmpcComposeResidualTarget( ...
            robustFrame.' * slidingI, boundaryF, totalRadiusF, ...
            config.coordinated_post_gp_radius_f_mps2(:), responsibility, ...
            gpFrame, robustFrame, observerShadowI, physicalGpEnabled);
        robustTargetI = composition.robust_i_mps2;
        gpControlTargetI = composition.gp_control_i_mps2;
        gpPhysicalAuthorityF = composition.alpha_physical_f;
        gpAuthority = mean(gpPhysicalAuthorityF);
        coordinatedTargetI = composition.raw_target_i_mps2;
        compensationTransition = gpenmpcAdvanceCompensationState( ...
            predictedCommonRobustI, coordinatedTargetI, dt, ...
            config.raw.common_inner_loop_predictor.filter_time_constant_s, ...
            config.raw.common_inner_loop_predictor.slew_limit_mps3, ...
            config.raw.common_inner_loop_predictor.combined_cap_mps2, 1.0);
        predictedCommonRobustI = compensationTransition.applied_i_mps2;
    else
        if coordinatedGpExecution
            gpAuthority = mean(gpPredictionAuthorityF);
            totalRadiusF = (1.0 - gpAuthority) .* totalRadiusF ...
                + gpAuthority .* config.post_gp_residual_radius_f_mps2(:);
            gpControlTargetI = -meanI;
        end
        robustTargetF = -totalRadiusF .* tanh( ...
            (robustFrame.' * slidingI) ./ boundaryF);
        robustTargetI = robustFrame * robustTargetF;
        filterGain = 1.0 - exp(-dt ...
            ./ config.raw.common_inner_loop_predictor.filter_time_constant_s);
        coordinatedTargetI = robustTargetI + gpControlTargetI;
        robustLowPass = predictedCommonRobustI ...
            + filterGain .* (coordinatedTargetI - predictedCommonRobustI);
        robustDelta = clipNorm(robustLowPass - predictedCommonRobustI, ...
            config.raw.common_inner_loop_predictor.slew_limit_mps3 .* dt);
        predictedCommonRobustI = clipNorm(predictedCommonRobustI + robustDelta, ...
            config.raw.common_inner_loop_predictor.combined_cap_mps2);
    end
    desiredForce = mass .* (trackingAcceleration + predictedCommonRobustI ...
        + [0.0; 0.0; context.gravity_mps2]) + dragFeedforward;
    % +meanI is the learned plant residual.  The negative control target is
    % already inside predictedCommonRobustI through coordinatedTargetI, so
    % prediction and execution share one sign convention and one cap.
    predictedAcceleration = trackingAcceleration + predictedCommonRobustI + meanI;
    uniformRotor = repmat(norm(desiredForce, 2) ./ 6.0, 1, 6);
    executionRotorVariation = 0.0;
    predictedAttitudeError = zeros(3, 1);
    predictedMoment = zeros(3, 1);
    predictedRotor = uniformRotor(:);
    if executionAligned
        [predictedRotor, predictedAttitudeError, predictedMoment] = ...
            predictedRotorCommand(desiredForce, predictedRotation, ...
                predictedBodyRate, context);
        executionRotorVariation = sum(abs( ...
            predictedRotor - previousPredictedRotor));
    end

    if isB2 && ~sampleInvalid
        predictedContext(1) = gpenmpcNormalizedTotalRotorCommand( ...
            uniformRotor, payloadKg);
        meanFForHistory = gpFrame.' * meanI;
        historyGain = 1.0 - exp(-dt ./ 0.50);
        predictedContext(2:4) = predictedContext(2:4) ...
            + historyGain .* (meanFForHistory - predictedContext(2:4));
    end

    accelerationUncertainty = zeros(3, 1); % ordinary B2 is not N1
    nextSigmaV = sqrt(sigmaV.^2 + (dt .* accelerationUncertainty).^2);
    nextSigmaP = sqrt(sigmaP.^2 + (dt .* sigmaV).^2 ...
        + (0.5 .* dt.^2 .* accelerationUncertainty).^2);
    nextP = p + dt .* v + 0.5 .* dt.^2 .* predictedAcceleration;
    nextV = v + dt .* predictedAcceleration;
    nextRate = rate + dt .* transition.phase_acceleration_s_inv;
    nextPhase = phase + dt .* rate ...
        + 0.5 .* dt.^2 .* transition.phase_acceleration_s_inv;
    nextPhase = min(nextPhase, trajectory.total_duration_s);

    airspeed = norm(v - wind3, 2);
    [publicPower, powerStatus] = phasePower(context, airspeed, payloadKg, v(3));
    nominalReferenceForce = mass .* (reference.acceleration_mps2 ...
        + [0.0; 0.0; context.gravity_mps2]) + dragFeedforward;
    powerRotor = uniformRotor;
    if executionAligned
        powerRotor = predictedRotor.';
    end
    executionPower = gpenmpcEnmpcStageControllerSensitivePower(publicPower, powerRotor, ...
        norm(nominalReferenceForce, 2), context.rotor_diameter_m);
    stageEnergy = dt .* executionPower;
    terminalExecutionPower = executionPower;

    positionError = reference.position_m - p;
    velocityError = reference.velocity_mps - v;
    forceVariation = desiredForce - previousForce;
    jerkNorm = norm(reference.jerk_mps3, 2);
    progressDeficit = max(0.0, expectedTerminalPhase - nextPhase);
    positionRadius = norm(nextSigmaP, 2);
    accelerationRadius = norm(accelerationUncertainty, 2);
    forceRadius = mass .* accelerationRadius;
    tilt = atan2(norm(desiredForce(1:2), 2), max(desiredForce(3), 1.0e-9));
    uniformRotorLoad = (norm(desiredForce, 2) + forceRadius) ./ 6.0;
    nextReferencePosition = gpenmpcEvaluateTrajectoryDerivative(trajectory, nextPhase, 0);
    nextReferenceVelocity = gpenmpcEvaluateTrajectoryDerivative(trajectory, nextPhase, 1) .* nextRate;
    predictedNextPositionError = norm(nextReferencePosition - nextP, 2);
    predictedNextVelocityError = norm(nextReferenceVelocity - nextV, 2);
    nominalAccelerationBudget = config.acceleration_screen_mps2 ...
        - config.common_inner_loop_acceleration_reserve_mps2 ...
        - config.additional_prediction_acceleration_reserve_mps2;
    nominalRotorLoad = norm(desiredForce, 2) ./ 6.0;
    corridor = min(config.corridor_half_width_m, ...
        optionalScalar(observation, "corridor_half_width_m", config.corridor_half_width_m));
    hardMargins = [ ...
        nextRate - config.phase_rate_min, ...
        config.phase_rate_max - nextRate, ...
        nextPhase, trajectory.total_duration_s - nextPhase, ...
        corridor - predictedNextPositionError, ...
        config.position_screen_m - predictedNextPositionError, ...
        config.velocity_screen_mps - predictedNextVelocityError, ...
        nominalAccelerationBudget - norm(predictedAcceleration, 2), ...
        config.jerk_screen_mps3 - jerkNorm, ...
        context.maximum_total_thrust_n - norm(desiredForce, 2), ...
        context.maximum_per_rotor_thrust_n - nominalRotorLoad, ...
        context.maximum_tilt_rad - tilt, ...
        context.airspeed_max_mps - airspeed, ...
        ternary(powerStatus ~= 2, 1.0, -1.0), ...
        config.outer_acceleration_correction_max_mps2 - norm(outerCorrectionF, 2)];
    riskMargins = [ ...
        (corridor - predictedNextPositionError - positionRadius) ./ max(corridor, 1.0e-9), ...
        (config.position_screen_m - predictedNextPositionError - positionRadius) ...
            ./ config.position_screen_m, ...
        (config.velocity_screen_mps - predictedNextVelocityError - norm(nextSigmaV, 2)) ...
            ./ config.velocity_screen_mps, ...
        (nominalAccelerationBudget - norm(predictedAcceleration, 2) - accelerationRadius) ...
            ./ nominalAccelerationBudget, ...
        (context.maximum_total_thrust_n - norm(desiredForce, 2) - forceRadius) ...
            ./ context.maximum_total_thrust_n, ...
        (context.maximum_per_rotor_thrust_n - uniformRotorLoad) ...
            ./ context.maximum_per_rotor_thrust_n];

    stageRows(index) = struct( ...
        "stage_energy_j", stageEnergy, ...
        "position_error_norm_m", norm(positionError, 2), ...
        "velocity_error_norm_mps", norm(velocityError, 2), ...
        "force_variation_norm_n", norm(forceVariation, 2), ...
        "execution_rotor_variation_n", executionRotorVariation, ...
        "reference_jerk_norm_mps3", jerkNorm, ...
        "phase_acceleration_s_inv", transition.phase_acceleration_s_inv, ...
        "phase_jerk_s_inv2", transition.phase_jerk_s_inv2, ...
        "progress_deficit_s", progressDeficit, ...
        "predicted_next_position_error_m", predictedNextPositionError, ...
        "predicted_next_velocity_error_mps", predictedNextVelocityError, ...
        "trust", trust, ...
        "hard_constraints", hardMargins, ...
        "risk_constraints_normalized", riskMargins);
    diagnosticRows(index) = struct( ...
        "horizon_index", index - 1, ...
        "progress_s", phase, ...
        "progress_rate", rate, ...
        "reference_position_m", reference.position_m.', ...
        "reference_velocity_mps", reference.velocity_mps.', ...
        "reference_acceleration_mps2", reference.acceleration_mps2.', ...
        "reference_jerk_mps3", reference.jerk_mps3.', ...
        "predicted_position_m", p.', ...
        "predicted_velocity_mps", v.', ...
        "predicted_acceleration_mps2", predictedAcceleration.', ...
        "predicted_common_robust_acceleration_i_mps2", predictedCommonRobustI.', ...
        "predicted_gp_plant_residual_i_mps2", meanI.', ...
        "predicted_gp_control_target_i_mps2", gpControlTargetI.', ...
        "predicted_gp_authority", gpAuthority, ...
        "predicted_gp_prediction_authority_f", gpPredictionAuthorityF.', ...
        "predicted_gp_physical_authority_f", gpPhysicalAuthorityF.', ...
        "predicted_residual_robust_target_i_mps2", robustTargetI.', ...
        "predicted_total_compensation_target_i_mps2", coordinatedTargetI.', ...
        "desired_force_n", desiredForce.', ...
        "predicted_rotor_command_n", predictedRotor.', ...
        "predicted_attitude_error_rad", predictedAttitudeError.', ...
        "predicted_moment_nm", predictedMoment.', ...
        "gp_mean_f_mps2", meanF.', ...
        "gp_filtered_mean_f_mps2", filteredMeanF.', ...
        "gp_mean_i_mps2", meanI.', ...
        "gp_agreement_weight_f", gpAgreementWeightF.', ...
        "gp_features_f17", featuresF17.', ...
        "gp_frame_i_from_f", gpFrame, ...
        "calibrated_half_width_f_mps2", halfWidthF.', ...
        "trust", trust, ...
        "hard_invalid", sampleInvalid, ...
        "support_distance", supportDistance, ...
        "latent_variance_max", latentMaximum, ...
        "stage_energy_j", stageEnergy, ...
        "power_domain_status", powerStatus, ...
        "outer_transition_fraction", transition.fraction);
    p = nextP;
    v = nextV;
    phase = nextPhase;
    rate = nextRate;
    sigmaP = nextSigmaP;
    sigmaV = nextSigmaV;
    previousForce = desiredForce;
    if executionAligned
        angularAcceleration = context.inertia_kg_m2 \ (predictedMoment ...
            - cross(predictedBodyRate, ...
                context.inertia_kg_m2 * predictedBodyRate));
        predictedBodyRate = predictedBodyRate + dt .* angularAcceleration;
        predictedRotation = predictedRotation * ...
            gpenmpcSo3Exp(dt .* predictedBodyRate);
        previousPredictedRotor = predictedRotor;
    end
    previousPhaseAcceleration = transition.phase_acceleration_s_inv;
    previousOuterCorrectionI = transition.outer_correction_i_mps2;
end

remainingDuration = max(0.0, trajectory.total_duration_s - phase) ...
    ./ max(rate, config.phase_rate_min);
terminalEnergyToGo = terminalExecutionPower .* remainingDuration;
result = gpenmpcBookkeepEnmpcRollout(stageRows, terminalEnergyToGo, ...
    hardInvalid, currentHardInvalid, config);
result.terminal_progress_s = phase;
result.initial_progress_s = initialPhase;
result.stage_rows = stageRows;
result.rows = diagnosticRows;
result.predicted_causal_context_terminal = predictedContext.';
result.method = method;
result.gp_mean_scale = config.gp_mean_scale;
result.gp_agreement_weight_f = gpAgreementWeightF.';
result.robust_tube_identity = config.robust_tube_identity;
result.n1_or_b2r1_active = false;
result.execution_consistent_cost_enabled = executionAligned;
result.coordinated_gp_execution_feedforward_enabled = coordinatedGpExecution;
result.coordinated_architecture_enabled = coordinatedArchitectureEnabled;
result.coordinated_physical_gp_application_enabled = physicalGpEnabled;
result.gp_responsibility_gate_enabled = responsibilityGateEnabled;
result.runtime_gp_responsibility_blend = gpResponsibilityBlend;
result.objective_progress_scale_s = config.progress_scale_s;
result.objective_execution_rotor_variation_scale_n = ...
    config.execution_rotor_variation_scale_n;
end


function [powerW, status] = phasePower(context, airspeed, payloadKg, verticalSpeed)
if verticalSpeed > 0.10
    powerW = context.phase_power_fcn("ASCEND", context.airspeed_min_mps, payloadKg);
    status = 3;
elseif verticalSpeed < -0.10
    powerW = context.phase_power_fcn("DESCEND", context.airspeed_min_mps, payloadKg);
    status = 3;
elseif airspeed < 0.20
    powerW = context.phase_power_fcn("HOVER", context.airspeed_min_mps, payloadKg);
    status = 3;
elseif airspeed < context.airspeed_min_mps
    hover = context.phase_power_fcn("HOVER", context.airspeed_min_mps, payloadKg);
    forward = context.phase_power_fcn("FORWARD", context.airspeed_min_mps, payloadKg);
    blend = min(max(airspeed ./ context.airspeed_min_mps, 0.0), 1.0);
    powerW = (1.0 - blend) .* hover + blend .* forward;
    status = 1;
elseif airspeed <= context.airspeed_max_mps + 1.0e-10
    powerW = context.phase_power_fcn("FORWARD", ...
        min(airspeed, context.airspeed_max_mps), payloadKg);
    status = 0;
else
    powerW = context.phase_power_fcn("FORWARD", context.airspeed_max_mps, payloadKg);
    status = 2;
end
powerW = double(powerW);
end


function clipped = clipNorm(vector, maximumNorm)
vector = double(vector(:));
vectorNorm = norm(vector, 2);
if vectorNorm > maximumNorm
    clipped = vector .* (maximumNorm ./ max(vectorNorm, 1.0e-15));
else
    clipped = vector;
end
end


function row = stageTemplate(config)
row = struct( ...
    "stage_energy_j", 0.0, ...
    "position_error_norm_m", 0.0, ...
    "velocity_error_norm_mps", 0.0, ...
    "force_variation_norm_n", 0.0, ...
    "execution_rotor_variation_n", 0.0, ...
    "reference_jerk_norm_mps3", 0.0, ...
    "phase_acceleration_s_inv", 0.0, ...
    "phase_jerk_s_inv2", 0.0, ...
    "progress_deficit_s", 0.0, ...
    "predicted_next_position_error_m", 0.0, ...
    "predicted_next_velocity_error_mps", 0.0, ...
    "trust", 0.0, ...
    "hard_constraints", ones(1, config.hard_constraints_per_step), ...
    "risk_constraints_normalized", ones(1, config.risk_constraints_per_step));
end


function row = diagnosticTemplate()
row = struct( ...
    "horizon_index", 0, ...
    "progress_s", 0.0, ...
    "progress_rate", 0.0, ...
    "reference_position_m", zeros(1, 3), ...
    "reference_velocity_mps", zeros(1, 3), ...
    "reference_acceleration_mps2", zeros(1, 3), ...
    "reference_jerk_mps3", zeros(1, 3), ...
    "predicted_position_m", zeros(1, 3), ...
    "predicted_velocity_mps", zeros(1, 3), ...
    "predicted_acceleration_mps2", zeros(1, 3), ...
    "predicted_common_robust_acceleration_i_mps2", zeros(1, 3), ...
    "predicted_gp_plant_residual_i_mps2", zeros(1, 3), ...
    "predicted_gp_control_target_i_mps2", zeros(1, 3), ...
    "predicted_gp_authority", 0.0, ...
    "predicted_gp_prediction_authority_f", zeros(1, 3), ...
    "predicted_gp_physical_authority_f", zeros(1, 3), ...
    "predicted_residual_robust_target_i_mps2", zeros(1, 3), ...
    "predicted_total_compensation_target_i_mps2", zeros(1, 3), ...
    "desired_force_n", zeros(1, 3), ...
    "predicted_rotor_command_n", zeros(1, 6), ...
    "predicted_attitude_error_rad", zeros(1, 3), ...
    "predicted_moment_nm", zeros(1, 3), ...
    "gp_mean_f_mps2", zeros(1, 3), ...
    "gp_filtered_mean_f_mps2", zeros(1, 3), ...
    "gp_mean_i_mps2", zeros(1, 3), ...
    "gp_agreement_weight_f", ones(1, 3), ...
    "gp_features_f17", zeros(1, 17), ...
    "gp_frame_i_from_f", eye(3), ...
    "calibrated_half_width_f_mps2", zeros(1, 3), ...
    "trust", 0.0, ...
    "hard_invalid", false, ...
    "support_distance", 0.0, ...
    "latent_variance_max", 0.0, ...
    "stage_energy_j", 0.0, ...
    "power_domain_status", 0, ...
    "outer_transition_fraction", 0.0);
end


function value = column(input, count, name)
value = double(input(:));
if numel(value) ~= count || any(~isfinite(value))
    error("gpenmpcEvaluateOrdinaryB2Rollout:Input", ...
        "%s must contain %d finite values.", name, count);
end
end


function value = optionalScalar(source, name, fallback)
if isfield(source, name)
    value = double(source.(name));
else
    value = double(fallback);
end
end


function value = optionalVector3(source, name, fallback)
if isfield(source, name)
    value = double(source.(name)(:));
else
    value = double(fallback(:));
end
if numel(value) ~= 3 || any(~isfinite(value))
    error("gpenmpcEvaluateOrdinaryB2Rollout:OptionalVector", ...
        "Optional field %s must contain three finite values.", name);
end
end


function enabled = executionConsistentCostEnabled(config)
enabled = isfield(config, "execution_consistent_cost_enabled") ...
    && logical(config.execution_consistent_cost_enabled);
end


function [rotor, attitudeError, momentNm] = predictedRotorCommand( ...
        desiredForceRaw, rotation, bodyRate, context)
[desiredForce, ~] = gpenmpcProjectForce(desiredForceRaw, ...
    context.maximum_total_thrust_n, context.maximum_tilt_rad);
desiredRotation = desiredRotationFromForce(desiredForce);
attitudeError = 0.5 .* gpenmpcVee( ...
    desiredRotation.' * rotation - rotation.' * desiredRotation);
gyroscopicMoment = cross(bodyRate, context.inertia_kg_m2 * bodyRate);
momentNm = -context.attitude_moment_gain_nm_per_rad .* attitudeError ...
    - context.body_rate_moment_gain_nm_s_per_rad .* bodyRate ...
    + gyroscopicMoment;
desiredThrust = max(dot(desiredForce, rotation(:, 3)), 0.0);
rawRotor = context.rotor_allocation_pseudoinverse ...
    * [desiredThrust; momentNm];
rotor = min(max(rawRotor, 0.0), context.maximum_per_rotor_thrust_n);
end


function rotation = desiredRotationFromForce(desiredForce)
b3 = desiredForce ./ max(norm(desiredForce), 1.0e-15);
b1Command = [1.0; 0.0; 0.0];
b2 = cross(b3, b1Command);
if norm(b2) < 1.0e-9
    b1Command = [0.0; 1.0; 0.0];
    b2 = cross(b3, b1Command);
end
b2 = b2 ./ max(norm(b2), 1.0e-15);
b1 = cross(b2, b3);
rotation = [b1, b2, b3];
end


function value = ternary(condition, trueValue, falseValue)
if condition
    value = trueValue;
else
    value = falseValue;
end
end


function validateIdentity(method, decision, context, config)
if method ~= config.method && method ~= config.b1_fallback_method
    error("gpenmpcEvaluateOrdinaryB2Rollout:Method", ...
        "Only B1 and ordinary B2 are supported.");
end
if numel(decision) ~= config.decision_dimension || any(~isfinite(decision))
    error("gpenmpcEvaluateOrdinaryB2Rollout:Decision", ...
        "Decision must be one finite 7D vector.");
end
requiredContext = ["base_mass_kg", "gravity_mps2", "position_gain_s2", ...
    "velocity_gain_s", "nominal_drag_n_per_mps2", "maximum_payload_kg", ...
    "maximum_total_thrust_n", "maximum_per_rotor_thrust_n", ...
    "maximum_tilt_rad", "rotor_diameter_m", "airspeed_min_mps", ...
    "airspeed_max_mps", "phase_power_fcn"];
for name = requiredContext
    if ~isfield(context, name)
        error("gpenmpcEvaluateOrdinaryB2Rollout:Context", ...
            "Prediction context is missing %s.", name);
    end
end
if executionConsistentCostEnabled(config)
    executionContext = ["rotor_allocation_pseudoinverse", "inertia_kg_m2", ...
        "attitude_moment_gain_nm_per_rad", ...
        "body_rate_moment_gain_nm_s_per_rad"];
    for name = executionContext
        if ~isfield(context, name)
            error("gpenmpcEvaluateOrdinaryB2Rollout:Context", ...
                "Execution-consistent context is missing %s.", name);
        end
    end
end
if abs(config.gp_mean_scale - 1.0) > 1.0e-12 ...
        || config.additional_prediction_acceleration_reserve_mps2 ~= 0.0 ...
        || config.n1_residual_tube_enabled || config.b2r1_enabled
    error("gpenmpcEvaluateOrdinaryB2Rollout:Identity", ...
        "The rollout left the ordinary-B2 method identity.");
end
end
