function config = gpenmpcApplyResponsibilityConfiguration(config)
%GPENMPCAPPLYRESPONSIBILITYCONFIGURATION Enable bounded GP responsibility.
%
% Configures a causal low-residual responsibility gate, a bumpless GP/B1
% crossfade, a causal GP-mean bandwidth limit and a common objective scale
% calibrated from prior traces.

arguments
    config (1,1) struct
end

config = gpenmpcApplyCoordinatedGpConfiguration(config);
required = ["gp_responsibility_gate_enabled", ...
    "responsibility_residual_floor_f_mps2", ...
    "responsibility_innovation_ewma_time_constant_s", ...
    "gp_responsibility_enter_ratio", ...
    "gp_responsibility_exit_ratio", ...
    "gp_responsibility_enter_dwell_s", ...
    "gp_responsibility_exit_dwell_s", ...
    "responsibility_cross_fade_duration_s", ...
    "responsibility_gp_mean_filter_time_constant_s", ...
    "responsibility_common_energy_scale_j"];
for name = required
    if ~isfield(config, name)
        error("gpenmpcApplyResponsibilityConfiguration:MissingField", ...
            "The responsibility configuration is missing %s.", name);
    end
end
config.gp_responsibility_gate_enabled = true;
config.energy_scale_j = double(config.responsibility_common_energy_scale_j);
config.gp_candidate_profile = ...
    "CAUSAL_RESPONSIBILITY__BUMPLESS_EXACT_B1__ALIGNED_ENERGY";
end
