if(NOT GPENMPC_HIL_SOURCE_DIR)
  get_filename_component(GPENMPC_HIL_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
endif()
set(GPENMPC_RFLY "${GPENMPC_HIL_SOURCE_DIR}/rfly_vendor_integration")
set(GPENMPC_RUNTIME "${GPENMPC_RFLY}/px4_runtime")
set(GPENMPC_INGRESS "${GPENMPC_HIL_SOURCE_DIR}/px4_full_inner/px4_ingress")
set(GPENMPC_GENERATED "${GPENMPC_HIL_SOURCE_DIR}/evidence/arm_controller/GPENMPC_Rfly_Canonical_Controller_ert_rtw")
set(GPENMPC_MAVLINK_OVERLAY "${GPENMPC_RFLY}/application_integration/overlay/src/modules/mavlink")
set(GPENMPC_DRIVER_OVERLAY "${GPENMPC_RFLY}/application_integration/overlay/drivers")
include("${CMAKE_CURRENT_LIST_DIR}/LateRuntimeSources.cmake")
