# Use a private writable XRCE source location for the PX4 ExternalProject target.
include(ExternalProject)
macro(ExternalProject_Add)
  if("${ARGV0}" STREQUAL "libmicroxrceddsclient_project")
    set(_gpenmpc_ep_arguments ${ARGV})
    list(FIND _gpenmpc_ep_arguments SOURCE_DIR _gpenmpc_ep_source_index)
    if(_gpenmpc_ep_source_index LESS 0)
      message(FATAL_ERROR "Expected exact existing XRCE SOURCE_DIR")
    endif()
    math(EXPR _gpenmpc_ep_source_index "${_gpenmpc_ep_source_index}+1")
    list(GET _gpenmpc_ep_arguments ${_gpenmpc_ep_source_index} _gpenmpc_ep_parent)
    if(NOT _gpenmpc_ep_parent STREQUAL "${PX4_SOURCE_DIR}/src/modules/uxrce_dds_client/Micro-XRCE-DDS-Client")
      message(FATAL_ERROR "Unexpected XRCE source identity")
    endif()
    set(_gpenmpc_ep_private "${EXTERNAL_MODULES_LOCATION}/../private_dependencies/Micro-XRCE-DDS-Client")
    if(NOT EXISTS "${_gpenmpc_ep_private}/CMakeLists.txt")
      message(FATAL_ERROR "Prepare audited local XRCE/CDR sources first")
    endif()
    list(REMOVE_AT _gpenmpc_ep_arguments ${_gpenmpc_ep_source_index})
    list(INSERT _gpenmpc_ep_arguments ${_gpenmpc_ep_source_index} "${_gpenmpc_ep_private}")
    _ExternalProject_Add(${_gpenmpc_ep_arguments})
  else()
    _ExternalProject_Add(${ARGV})
  endif()
endmacro()
