function [plantState, service] = gpenmpcApplyFixedC3ServiceTransition( ...
        plantState, payloadBeforeKg, payloadAfterKg, serviceDurationS, ...
        expectedGroundDurationS, serviceNodePositionM, profile)
%GPENMPCAPPLYFIXEDC3SERVICETRANSITION Apply the shared service-time model.
%
% Model descent, ground dwell and ascent, then initialize the next transit at
% node hover with the updated payload, service state and energy accounting.

serviceNodePositionM = double(serviceNodePositionM(:));
if numel(serviceNodePositionM) ~= 3 || any(~isfinite(serviceNodePositionM))
    error("gpenmpcApplyFixedC3ServiceTransition:ServiceNodePosition", ...
        "Service node position must contain three finite coordinates.");
end
serviceStartAltitudeM = serviceNodePositionM(3);
serviceTargetAltitudeM = ...
    double(profile.collision_envelope.planning_radius_m) + 0.02;
serviceDurationS = double(serviceDurationS);
if ~isscalar(serviceDurationS) || ~isfinite(serviceDurationS) ...
        || serviceDurationS < 0.0
    error("gpenmpcApplyFixedC3ServiceTransition:Duration", ...
        "Service duration must be one finite nonnegative scalar.");
end
expectedGroundDurationS = double(expectedGroundDurationS);
if ~isscalar(expectedGroundDurationS) ...
        || ~isfinite(expectedGroundDurationS) ...
        || expectedGroundDurationS < 0.0
    error("gpenmpcApplyFixedC3ServiceTransition:GroundDuration", ...
        "Expected ground dwell must be one finite nonnegative scalar.");
end
if serviceStartAltitudeM < serviceTargetAltitudeM - 1.0e-12
    error("gpenmpcApplyFixedC3ServiceTransition:ServiceAltitude", ...
        "Service start altitude is below the retained low service target.");
end
verticalDistanceM = max(0.0, ...
    serviceStartAltitudeM - serviceTargetAltitudeM);
verticalDurationS = verticalDistanceM ./ 1.0 + 1.0;
groundDurationS = serviceDurationS - 2.0 .* verticalDurationS;
if groundDurationS < -1.0e-9
    error("gpenmpcApplyFixedC3ServiceTransition:Duration", ...
        "Service duration %.9f s is shorter than the public vertical phases.", ...
        serviceDurationS);
end
groundDurationS = max(groundDurationS, 0.0);
if abs(groundDurationS - expectedGroundDurationS) > 1.0e-9
    error("gpenmpcApplyFixedC3ServiceTransition:GroundDurationMismatch", ...
        "Service duration and task-defined ground dwell disagree: " + ...
        "derived %.9f s, expected %.9f s.", ...
        groundDurationS, expectedGroundDurationS);
end
[descentPowerW, ~] = gpenmpcM600PhasePower( ...
    profile, payloadBeforeKg, 0.0, -1.0);
[ascentPowerW, ~] = gpenmpcM600PhasePower( ...
    profile, payloadAfterKg, 0.0, 1.0);
groundPowerW = double(profile.energy_model.ground_auxiliary_power_w);
descentEnergyJ = descentPowerW .* verticalDurationS;
groundEnergyJ = groundPowerW .* groundDurationS;
ascentEnergyJ = ascentPowerW .* verticalDurationS;

x = zeros(size(double(plantState(:))));
x(1:3) = serviceNodePositionM;
x(7) = 1.0;
x(14:19) = (double(profile.mass_properties.base_mass_kg) ...
    + double(payloadAfterKg)) .* 9.80665 ./ 6.0;
plantState = x;
service = struct( ...
    "duration_s", serviceDurationS, ...
    "service_start_altitude_m", serviceStartAltitudeM, ...
    "service_target_altitude_m", serviceTargetAltitudeM, ...
    "vertical_distance_each_m", verticalDistanceM, ...
    "vertical_duration_each_s", verticalDurationS, ...
    "ground_duration_s", groundDurationS, ...
    "payload_before_kg", double(payloadBeforeKg), ...
    "payload_after_kg", double(payloadAfterKg), ...
    "descent_energy_j", descentEnergyJ, ...
    "ground_energy_j", groundEnergyJ, ...
    "ascent_energy_j", ascentEnergyJ, ...
    "public_energy_j", descentEnergyJ + groundEnergyJ + ascentEnergyJ, ...
    "controller_sensitive_energy_j", ...
        descentEnergyJ + groundEnergyJ + ascentEnergyJ, ...
    "controller_specific_adjustment_j", 0.0);
end
