function [runtime,accepted,reason] = bindCanonicalRuntimeObservations( ...
        prepared,virtualActuator,wind,nowNs,maximumAgeNs)
% Bind observations with their source timestamps and generations.
% Initialize rotor command from measured lag, then use committed HIL93 commands.
runtime=struct();accepted=false;reason="INVALID_OBSERVED_RUNTIME";
if ~isstruct(prepared)||~isscalar(prepared)||~all(isfield(prepared, ...
        {'schema','virtual_actuator','outer','wind','task'})) ...
        ||~finiteScalar(nowNs)||nowNs<0 ...
        ||~finiteScalar(maximumAgeNs)||maximumAgeNs<=0
    return
end
if ~stamp(virtualActuator,'HOST_M600_VIRTUAL_ACTUATOR_INTERFACE')
    reason="INVALID_OR_STALE_ROTOR_OBSERVATION";return
end
if ~stamp(wind,'FROZEN_TASK_WIND_ESTIMATOR')
    reason="INVALID_OR_STALE_WIND_OBSERVATION";return
end
if ~all(isfield(virtualActuator,{'ordering','rotor_thrust_state_n', ...
        'thrust_effectiveness','state_source','plant_session_id'})) ...
        ||~textScalar(virtualActuator.ordering) ...
        ||string(virtualActuator.ordering)~="SOFTWARE_M600_ORDER" ...
        ||~textScalar(virtualActuator.state_source) ...
        ||string(virtualActuator.state_source)~="SAME_M600_ACCEPTED_STEP_ROTOR_LAG_STATE" ...
        ||~vector(virtualActuator.rotor_thrust_state_n,6) ...
        ||any(virtualActuator.rotor_thrust_state_n(:)<0) ...
        ||~vector(virtualActuator.thrust_effectiveness,6) ...
        ||any(virtualActuator.thrust_effectiveness(:)<=0) ...
        ||~integer(virtualActuator.plant_session_id)||virtualActuator.plant_session_id<1
    reason="INVALID_ROTOR_STATE_SEMANTICS";return
end
if ~isfield(wind,'estimate_xy_mps')||~vector(wind.estimate_xy_mps,2)
    reason="INVALID_WIND_VALUE";return
end
base=prepared.virtual_actuator;
if ~all(isfield(base,{'command_source','command_generation','rotor_command_n'}))
    reason="MISSING_PRIOR_COMMITTED_COMMAND_BINDING";return
end
if ~integer(base.command_generation)||~textScalar(base.command_source)
    reason="INVALID_PRIOR_COMMAND_GENERATION";return
end
if base.command_generation==0
    if string(base.command_source)~="CANONICAL_LEG_INITIAL_ROTOR_STATE"
        reason="INVALID_INITIAL_COMMAND_SOURCE";return
    end
    command=double(virtualActuator.rotor_thrust_state_n(:));
else
    hostFull=string(base.command_source)=="PREVIOUS_COMMITTED_FULL_KERNEL_HOST_COMMAND" ...
        &&isfield(prepared.outer,'desired_force_source') ...
        &&string(prepared.outer.desired_force_source)=="COMMITTED_CANONICAL_FULL_SE3_KERNEL_HOST_ONLY";
    boardFull=string(base.command_source)=="PREVIOUS_COMMITTED_FULL_KERNEL_BOARD_COMMAND" ...
        &&isfield(prepared.outer,'desired_force_source') ...
        &&string(prepared.outer.desired_force_source)=="COMMITTED_CANONICAL_FULL_SE3_KERNEL_BOARD_RFC1" ...
        &&isfield(prepared.outer,'board_commit_consumer');
    if boardFull
        receipt=prepared.outer.board_commit_consumer;
        boardFull=~receipt.failed&&receipt.commits>0 ...
            &&isfield(receipt.last_receipt,'source_generation') ...
            &&uint64(base.command_generation)==receipt.last_receipt.source_generation ...
            &&isequal(base.rotor_command_n,receipt.last_receipt.actual61(5:10));
    end
    if (string(base.command_source)~="PREVIOUS_COMMITTED_HIL_ACTUATOR_COMMAND" && ~hostFull && ~boardFull) ...
            ||~vector(base.rotor_command_n,6)||any(base.rotor_command_n(:)<0)
        reason="INVALID_COMMITTED_COMMAND_SOURCE";return
    end
    command=double(base.rotor_command_n(:));
end
runtime=prepared;
runtime.virtual_actuator=virtualActuator;
runtime.virtual_actuator.rotor_command_n=command;
runtime.virtual_actuator.command_source=base.command_source;
runtime.virtual_actuator.command_generation=base.command_generation;
runtime.wind=wind;
runtime.observed_input_stamps_preserved=true;
runtime.observation_binding=struct( ...
    'rotor_rx_ns',virtualActuator.rx_ns,'rotor_generation',virtualActuator.generation, ...
    'wind_rx_ns',wind.rx_ns,'wind_generation',wind.generation, ...
    'plant_session_id',virtualActuator.plant_session_id, ...
    'rotor_state_source',virtualActuator.state_source, ...
    'source_age_rewritten',false,'plant_truth_state_used',false);
accepted=true;reason="OBSERVED_INPUTS_BOUND_WITH_ORIGINAL_STAMPS";

    function yes=stamp(x,source)
        yes=isstruct(x)&&isscalar(x)&&all(isfield(x, ...
            {'source','rx_ns','generation','valid'})) ...
            &&(ischar(x.source)||(isstring(x.source)&&isscalar(x.source))) ...
            &&string(x.source)==string(source) ...
            &&islogical(x.valid)&&isscalar(x.valid)&&x.valid ...
            &&integer(x.generation)&&x.generation>=1 ...
            &&integer(x.rx_ns)&&x.rx_ns<=nowNs&&nowNs-x.rx_ns<=maximumAgeNs;
    end
end
function yes=finiteScalar(x)
yes=isnumeric(x)&&isreal(x)&&isscalar(x)&&isfinite(x);
end
function yes=integer(x)
yes=finiteScalar(x)&&x>=0&&x==fix(x)&&x<=flintmax;
end
function yes=vector(x,n)
yes=isnumeric(x)&&isreal(x)&&isvector(x)&&numel(x)==n&&all(isfinite(x(:)));
end
function yes=textScalar(x)
yes=(ischar(x)&&isrow(x))||(isstring(x)&&isscalar(x)&&~ismissing(x));
end
