function [response,stopRequested] = boardOuterHostService(action,payload,workRoot)
% Dispatch the persistent outer service through loopback wrappers.
arguments
    action (1,1) string
    payload (1,1) struct = struct()
    workRoot (1,1) string = ""
end
persistent service initialized
if isempty(initialized),initialized=false;end
stopRequested=false;
try
    switch upper(action)
        case "RESET"
            clear service
            initialized=false;
            response=baseResponse("RESET");
        case "INITIALIZE"
            assert(~initialized,'gpenmpcNative:BoardOuterAlreadyInitialized', ...
                'Reset the outer service before initialization.');
            assert(strlength(workRoot)>0 && isfolder(workRoot), ...
                'gpenmpcNative:BoardOuterServiceRoot','Valid work root required.');
            requireFields(payload,{'schema','method','expected','trajectory'});
            assert(string(payload.schema)== ...
                "GPENMPC_BOARD_OUTER_INITIALIZE_REQUEST_V1", ...
                'gpenmpcNative:BoardOuterInitializeSchema','Bad initialize schema.');
            assets=gpenmpcNative.loadCurrentAssets(workRoot);
            assert(string(payload.method)==string(assets.enmpc.method), ...
                'gpenmpcNative:BoardOuterMethod','Method identity mismatch.');
            service=gpenmpcNative.BoardOuterService( ...
                workRoot,payload.expected,payload.trajectory);
            initialized=true;
            response=baseResponse("INITIALIZED");
            response.schema="GPENMPC_BOARD_OUTER_INITIALIZE_RESPONSE_V1";
            response.method=string(assets.enmpc.method);
            response.configuration_payload_sha256= ...
                string(assets.configurationBinding.effective_configuration_payload_sha256);
            response.source_manifest_sha256=string(assets.binding.source_manifest_sha256);
            response.solver_deadline_s=assets.enmpc.solver_deadline_s;
        case "PREPARE"
            assert(initialized,'gpenmpcNative:BoardOuterNotInitialized', ...
                'Initialize service before preparation.');
            requireFields(payload,{'schema','now_ns','px4_sample','runtime'});
            assert(string(payload.schema)== ...
                "GPENMPC_BOARD_OUTER_PREPARE_REQUEST_V1", ...
                'gpenmpcNative:BoardOuterPrepareSchema','Bad prepare schema.');
            response=service.prepare(double(payload.now_ns), ...
                payload.px4_sample,payload.runtime);
            response.schema="GPENMPC_BOARD_OUTER_PREPARE_RESPONSE_V1";
        case "UPDATE"
            assert(initialized,'gpenmpcNative:BoardOuterNotInitialized', ...
                'Initialize service before update.');
            requireFields(payload,{'schema','generation','now_ns','px4_sample','runtime'});
            assert(string(payload.schema)== ...
                "GPENMPC_BOARD_OUTER_UPDATE_REQUEST_V1", ...
                'gpenmpcNative:BoardOuterUpdateSchema','Bad update schema.');
            generation=double(payload.generation);
            assert(isfinite(generation) && generation>=1 && generation==fix(generation), ...
                'gpenmpcNative:BoardOuterUpdateGeneration','Invalid generation.');
            response=service.update(uint64(generation),double(payload.now_ns), ...
                payload.px4_sample,payload.runtime);
        case "ASYNC_UPDATE_SUBMIT"
            assert(initialized,'gpenmpcNative:BoardOuterNotInitialized', ...
                'Initialize service before async update submit.');
            requireFields(payload,{'schema','generation','now_ns','px4_sample','runtime'});
            assert(string(payload.schema)== ...
                "GPENMPC_BOARD_OUTER_ASYNC_SUBMIT_REQUEST_V1", ...
                'gpenmpcNative:BoardOuterAsyncSubmitSchema', ...
                'Bad async submit schema.');
            generation=double(payload.generation);
            assert(isfinite(generation)&&generation>=1 ...
                && generation==fix(generation), ...
                'gpenmpcNative:BoardOuterAsyncSubmitGeneration', ...
                'Invalid async generation.');
            response=service.submitUpdate(uint64(generation), ...
                double(payload.now_ns),payload.px4_sample,payload.runtime);
        case "ASYNC_UPDATE_POLL"
            assert(initialized,'gpenmpcNative:BoardOuterNotInitialized', ...
                'Initialize service before async update poll.');
            requireFields(payload,{'schema','now_ns'});
            assert(string(payload.schema)== ...
                "GPENMPC_BOARD_OUTER_ASYNC_POLL_REQUEST_V1", ...
                'gpenmpcNative:BoardOuterAsyncPollSchema', ...
                'Bad async poll schema.');
            response=service.pollUpdate(double(payload.now_ns));
        case "EXPIRE"
            assert(initialized,'gpenmpcNative:BoardOuterNotInitialized', ...
                'Initialize service before expiry.');
            requireFields(payload,{'schema','generation','reason'});
            assert(string(payload.schema)== ...
                "GPENMPC_BOARD_OUTER_EXPIRE_REQUEST_V1", ...
                'gpenmpcNative:BoardOuterExpireSchema','Bad expiry schema.');
            response=service.expire(uint64(payload.generation),string(payload.reason));
        case "REFERENCE_STEP"
            assert(initialized,'gpenmpcNative:BoardOuterNotInitialized', ...
                'Initialize service before reference step.');
            requireFields(payload,{'schema','dt_s'});
            assert(string(payload.schema)== ...
                "GPENMPC_BOARD_REFERENCE_STEP_REQUEST_V1", ...
                'gpenmpcNative:BoardReferenceStepSchema','Bad reference schema.');
            reference=service.stepReference(double(payload.dt_s));
            response=baseResponse("REFERENCE");
            response.schema="GPENMPC_BOARD_REFERENCE_STEP_RESPONSE_V1";
            response.reference=reference;
        case "PHYSICAL_REFERENCE_STEP"
            assert(initialized,'gpenmpcNative:BoardOuterNotInitialized', ...
                'Initialize service before physical reference step.');
            requireFields(payload,{'schema','generation','now_ns', ...
                'px4_sample','runtime','dt_s'});
            assert(string(payload.schema)== ...
                "GPENMPC_BOARD_PHYSICAL_REFERENCE_REQUEST_V1", ...
                'gpenmpcNative:BoardPhysicalReferenceSchema', ...
                'Bad physical reference schema.');
            generation=double(payload.generation);
            assert(isfinite(generation)&&generation>=1 ...
                && generation==fix(generation), ...
                'gpenmpcNative:BoardPhysicalReferenceGeneration', ...
                'Invalid physical generation.');
            response=service.stepPhysicalReference(uint64(generation), ...
                double(payload.now_ns),payload.px4_sample,payload.runtime, ...
                double(payload.dt_s));
        case "GROUND_REFERENCE_STEP"
            assert(initialized,'gpenmpcNative:BoardOuterNotInitialized', ...
                'Initialize service before ground reference step.');
            requireFields(payload,{'schema','dt_s','ground_confirmed','board_armed'});
            assert(string(payload.schema)== ...
                "GPENMPC_BOARD_GROUND_REFERENCE_REQUEST_V1", ...
                'gpenmpcNative:BoardGroundReferenceSchema', ...
                'Bad ground reference schema.');
            response=service.stepGroundReference(double(payload.dt_s), ...
                logical(payload.ground_confirmed),logical(payload.board_armed));
        case "PHYSICAL_CONTROL_COMMIT"
            assert(initialized,'gpenmpcNative:BoardOuterNotInitialized', ...
                'Initialize service before physical control commit.');
            requireFields(payload,{'schema','generation','now_ns', ...
                'control_feedback'});
            assert(string(payload.schema)== ...
                "GPENMPC_BOARD_PHYSICAL_CONTROL_COMMIT_REQUEST_V1", ...
                'gpenmpcNative:BoardPhysicalCommitSchema', ...
                'Bad physical control commit schema.');
            generation=double(payload.generation);
            assert(isfinite(generation)&&generation>=1 ...
                && generation==fix(generation), ...
                'gpenmpcNative:BoardPhysicalCommitGeneration', ...
                'Invalid physical commit generation.');
            response=service.commitPhysicalControl(uint64(generation), ...
                double(payload.now_ns),payload.control_feedback);
        case "PHYSICAL_V7_CONTROL_COMMIT"
            assert(initialized,'gpenmpcNative:BoardOuterNotInitialized', ...
                'Initialize service before V7 physical control commit.');
            requireFields(payload,{'schema','generation','now_ns', ...
                'module_guard','actuator_output'});
            assert(string(payload.schema)== ...
                "GPENMPC_BOARD_V7_PHYSICAL_CONTROL_COMMIT_REQUEST_V1", ...
                'gpenmpcNative:BoardV7PhysicalCommitSchema', ...
                'Bad V7 physical control commit schema.');
            generation=double(payload.generation);
            assert(isfinite(generation)&&generation>=1 ...
                && generation==fix(generation), ...
                'gpenmpcNative:BoardV7PhysicalCommitGeneration', ...
                'Invalid V7 physical commit generation.');
            response=service.commitV7PhysicalControl(uint64(generation), ...
                double(payload.now_ns),payload.module_guard, ...
                payload.actuator_output);
        case "STATUS"
            assert(initialized,'gpenmpcNative:BoardOuterNotInitialized', ...
                'Initialize service before status.');
            response=service.status();
        case "STOP"
            if initialized
                finalStatus=service.status();
            else
                finalStatus=struct('initialized',false);
            end
            clear service
            initialized=false;
            response=baseResponse("STOPPED");
            response.final_status=finalStatus;
            stopRequested=true;
        otherwise
            error('gpenmpcNative:BoardOuterAction','Unknown action %s',action);
    end
catch exception
    response=baseResponse("FAIL_CLOSED");
    response.failure_code=string(exception.identifier)+":"+string(exception.message);
    response.fail_closed=true;
end
end

function response=baseResponse(status)
response=struct('status',string(status),'fail_closed',false, ...
    'hardware_actions',0,'com_open',0,'board_access',0, ...
    'parameter_writes',0,'mapping_writes',0,'arm_requests',0, ...
    'mode_requests',0,'task_rows',0,'physical_output_commands',0);
end

function requireFields(value,names)
assert(isstruct(value) && isscalar(value) && all(isfield(value,names)), ...
    'gpenmpcNative:BoardOuterRequestFields','Missing request field.');
end
