classdef BoardOuterService < handle
    % Own solver warm-start, generation ordering, continuity and board-reference state.
    properties (SetAccess=private)
        Failed = false
        FailureCode = ""
        LastGeneration = uint64(0)
        AcceptedSolverResults = uint64(0)
        ExpiredSolverResults = uint64(0)
        RejectedSnapshots = uint64(0)
        Prepared = false
        PreparationCalls = uint64(0)
        PreparationWallS = 0
        HardwareActions = 0
        AsyncSubmitted = uint64(0)
        AsyncAccepted = uint64(0)
        AsyncExpired = uint64(0)
        AsyncLateDiscarded = uint64(0)
        AsyncWarmupWallS = 0
        CurrentLegIndex = 1
        CurrentPayloadKg
        LegTransitionCount = uint64(0)
        OuterSuspended = false
        LifecycleSuspendCount = uint64(0)
        AsyncLifecycleDiscarded = uint64(0)
        FreshOuterForCurrentLeg = false
        PreparationInFlight = false
        PreparationExpired = false
        PreparationResultTiming = "NOT_STARTED"
    end
    properties (Access=private)
        WorkRoot
        Assets
        Expected
        Config
        Trajectory
        Adapter
        PhysicalRuntime
        WarmStart
        ConfigurationPayloadSha256
        LastInputGenerations = zeros(1,6)
        LastInputBoundary = struct()
        ReferenceMode = ""
        FixedAssets
        Worker
        AsyncInFlight = false
        AsyncCommitted = false
        AsyncGeneration = uint64(0)
        AsyncSubmittedNs = uint64(0)
        AsyncBoundary = struct()
        AsyncSnapshotTimestampNs = uint64(0)
        AsyncInputGenerations = zeros(1,6)
        AsyncEnabled = false
        AsyncRetiredForLifecycle = false
        PreparationBoundary = struct()
        PreparationSnapshotNs = uint64(0)
        PreparationSubmittedNs = uint64(0)
        PreparationLastEventNs = uint64(0)
        PreparationWorkerExpiryBaseline = 0
        PreparationNumericalState = struct()
    end
    methods
        function obj = BoardOuterService(workRoot,expected,trajectory)
            % A new execution session after ground service may start at a later mission leg.
            if isfield(expected,'initial_leg_index')
                v=expected.initial_leg_index;
                assert(isnumeric(v)&&isreal(v)&&isscalar(v)&&isfinite(v) ...
                    &&v>=1&&v==fix(v)&&v<=double(intmax('int32')), ...
                    'gpenmpcNative:CanonicalInitialLeg','Explicit positive global task leg required.');
                obj.CurrentLegIndex=double(v);
            end
            assert(isfield(expected,'canonical_package_root'), ...
                'gpenmpcNative:CanonicalPackageRequired', ...
                'The service must explicitly bind the canonical assets in this distribution.');
            assets = gpenmpcNative.loadCanonicalAssets( ...
                string(expected.canonical_package_root));
            obj.Assets = assets;
            assert(isfield(expected,'initial_payload_kg') ...
                &&isnumeric(expected.initial_payload_kg)&&isscalar(expected.initial_payload_kg) ...
                &&isfinite(expected.initial_payload_kg)&&expected.initial_payload_kg>=0, ...
                'gpenmpcNative:CanonicalInitialPayload','Explicit task initial payload required.');
            obj.CurrentPayloadKg=double(expected.initial_payload_kg);
            obj.WorkRoot = string(workRoot);
            obj.Expected = expected;
            obj.Config = assets.enmpc;
            obj.ConfigurationPayloadSha256 = ...
                string(assets.configurationBinding.effective_configuration_payload_sha256);
            obj.Trajectory = trajectory;
            obj.Adapter = gpenmpcNative.initializeBoardReferenceAdapter( ...
                obj.Config,trajectory,string(obj.Config.method));
            assert(isfield(expected,'task_identity_sha256'), ...
                'gpenmpcNative:BoardOuterTaskIdentity', ...
                'The frozen task identity is required.');
            obj.PhysicalRuntime = gpenmpcNative.CurrentPhysicalCausalRuntime( ...
                workRoot,expected,string(expected.task_identity_sha256),assets);
            obj.WarmStart = zeros(1,obj.Config.decision_dimension);
            obj.AsyncEnabled=isfield(expected,'async_outer_required') ...
                && islogical(expected.async_outer_required) ...
                && isscalar(expected.async_outer_required) ...
                && expected.async_outer_required;
            if obj.AsyncEnabled
                bindingPath=assets.binding_path;
                fixed=struct('source_root',assets.sourceRoot, ...
                    'config',assets.enmpc,'context',assets.prediction_context, ...
                    'gp_model',assets.gp_model, ...
                    'source_manifest_sha256', ...
                        string(assets.binding.source_manifest_sha256), ...
                    'source_binding_sha256',gpenmpcNative.fileSha256(bindingPath), ...
                    'configuration_payload_sha256', ...
                        string(assets.configurationBinding.effective_configuration_payload_sha256), ...
                    'gp_model_sha256',gpenmpcNative.fileSha256(assets.gpModelPath));
                obj.FixedAssets=parallel.pool.Constant(fixed);
                obj.Worker=gpenmpcNative.OuterMailboxWorker( ...
                    obj.FixedAssets,obj.Config.solver_deadline_s);
            end
        end

        function receipt = prepare(obj,nowNs,px4Sample,runtime)
            % Pre-formal JIT/content rehearsal. It consumes no generation,
            % commits no command, and cannot publish a board reference.
            assert(~obj.Failed && obj.LastGeneration==0 && ~obj.Prepared && ~obj.PreparationInFlight, ...
                'gpenmpcNative:BoardOuterPreparationState', ...
                'Preparation is permitted exactly once before generation 1.');
            obj.requireRuntimeTask(runtime);
            phase = struct('progress_s',obj.Adapter.phase_s, ...
                'progress_rate',obj.Adapter.phase_rate, ...
                'previous_phase_acceleration_s_inv', ...
                    obj.Adapter.previous_phase_acceleration_s_inv);
            [snapshot,accepted,reason,boundary] = ...
                gpenmpcNative.makeBoardOuterSnapshot(obj.WorkRoot, ...
                    px4Sample,obj.snapshotExpected(),nowNs,runtime,obj.Trajectory, ...
                    phase,obj.WarmStart,obj.Assets);
            if ~accepted
                obj.Failed=true;obj.FailureCode=string(reason);
                receipt=struct('status','FAIL_CLOSED','reason',string(reason), ...
                    'input_boundary',boundary,'generation_consumed',false, ...
                    'command_committed',false,'hardware_actions',0);
                return
            end
            started=tic;
            probe=gpenmpcNative.solveCurrentOuter(snapshot);
            obj.PreparationWallS=toc(started);
            obj.PreparationCalls=obj.PreparationCalls+uint64(1);
            assert(probe.used_current_supervisor ...
                && probe.snapshot_timestamp_ns==snapshot.snapshot_timestamp_ns, ...
                'gpenmpcNative:BoardOuterPreparationBinding', ...
                'Preparation result is not bound to the rehearsal snapshot.');
            obj.Prepared=true;
            obj.LastInputGenerations=obj.boundaryGenerations(boundary);
            obj.LastInputBoundary=boundary;
            if obj.AsyncEnabled
                warmTimer=tic;
                compact=obj.compactSnapshot(snapshot);
                assert(obj.Worker.submit(compact,0,double(nowNs)), ...
                    'gpenmpcNative:BoardOuterAsyncWarmSubmit', ...
                    'Unable to submit the pre-formal async warm-up.');
                ready=false;reason='PENDING';warmResult=struct();
                while ~ready && toc(warmTimer)<60.0
                    [ready,warmResult,reason]=obj.Worker.poll( ...
                        double(nowNs),0);
                    if reason=="WORKER_ERROR_NO_COMMAND",break,end
                    if ~ready,pause(0.002);end
                end
                obj.AsyncWarmupWallS=toc(warmTimer);
                assert(ready && reason=="FRESH_RESULT" ...
                    && logical(warmResult.dynamic_snapshot_only) ...
                    && logical(warmResult.immutable_worker_constant), ...
                    'gpenmpcNative:BoardOuterAsyncWarmup', ...
                    'Async solver warm-up failed before formal t0: %s',reason);
            end
            receipt=struct('status','PASS_HOST_PREPARATION', ...
                'wall_s',obj.PreparationWallS, ...
                'solver_deadline_s',obj.Config.solver_deadline_s, ...
                'generation_consumed',false,'command_committed',false, ...
                'publication_count',0,'input_boundary',boundary, ...
                'async_enabled',obj.AsyncEnabled, ...
                'async_warmup_wall_s',obj.AsyncWarmupWallS, ...
                'preparation_decision',probe.decision, ...
                'preparation_audit',probe.audit, ...
                'hardware_actions',0,'com_open',0,'board_access',0);
        end

        function receipt=beginPreparation(obj,nowNs,px4Sample,runtime)
            % The SAME persistent worker performs the only actual-snapshot
            % preparation probe. No main-thread duplicate solver call, wait,
            % generation-1 result, warm-start commit or observer update.
            assert(~obj.Failed&&~obj.Prepared&&~obj.PreparationInFlight ...
                &&obj.LastGeneration==0&&obj.PreparationCalls==0&&obj.AsyncEnabled, ...
                'gpenmpcNative:BoardOuterPreparationState','One async preparation before formal generation 1 required.');
            assert(isa(nowNs,'uint64')&&isscalar(nowNs)&&nowNs>0, ...
                'gpenmpcNative:BoardOuterPreparationTime','Original HOST event required.');
            obj.requireRuntimeTask(runtime);
            phase=struct('progress_s',obj.Adapter.phase_s,'progress_rate',obj.Adapter.phase_rate, ...
                'previous_phase_acceleration_s_inv',obj.Adapter.previous_phase_acceleration_s_inv);
            [snapshot,accepted,reason,boundary]=gpenmpcNative.makeBoardOuterSnapshot( ...
                obj.WorkRoot,px4Sample,obj.snapshotExpected(),nowNs,runtime,obj.Trajectory, ...
                phase,obj.WarmStart,obj.Assets);
            if ~accepted
                obj.Failed=true;obj.FailureCode=string(reason);
                receipt=struct('status','FAIL_CLOSED','reason',string(reason), ...
                    'input_boundary',boundary,'generation_consumed',false, ...
                    'command_committed',false,'hardware_actions',0);return
            end
            obj.PreparationWorkerExpiryBaseline=obj.Worker.Expired;
            obj.PreparationNumericalState=struct('warm_start',obj.WarmStart, ...
                'adapter',obj.Adapter,'physical',obj.PhysicalRuntime.status());
            assert(obj.Worker.submit(obj.compactSnapshot(snapshot),0,double(nowNs)), ...
                'gpenmpcNative:BoardOuterAsyncWarmSubmit','The sole worker must accept generation-0 preparation.');
            obj.PreparationCalls=obj.PreparationCalls+uint64(1);
            obj.PreparationInFlight=true;obj.PreparationBoundary=boundary;
            obj.PreparationSnapshotNs=uint64(snapshot.snapshot_timestamp_ns);
            obj.PreparationSubmittedNs=nowNs;obj.PreparationLastEventNs=nowNs;
            obj.PreparationResultTiming="PENDING";
            receipt=obj.preparationReceipt('PREPARATION_SUBMITTED','PENDING');
        end

        function receipt=pollPreparation(obj,nowNs)
            assert(~obj.Failed&&~obj.Prepared&&obj.PreparationInFlight, ...
                'gpenmpcNative:BoardOuterPreparationState','No current preparation request.');
            assert(isa(nowNs,'uint64')&&isscalar(nowNs)&&nowNs>=obj.PreparationLastEventNs, ...
                'gpenmpcNative:BoardOuterPreparationTime','Preparation HOST event regressed.');
            obj.PreparationLastEventNs=nowNs;
            [ready,probe,reason]=obj.Worker.poll(double(nowNs),0);
            obj.PreparationWallS=double(nowNs-obj.PreparationSubmittedNs)*1e-9;
            obj.AsyncWarmupWallS=obj.PreparationWallS;
            obj.PreparationExpired=obj.Worker.Expired>obj.PreparationWorkerExpiryBaseline;
            % Pass current time to the worker to preserve its .28 s expiry ledger.
            % The 60 s cold-preparation ceiling is separate from task deadlines.
            if obj.PreparationWallS>=60.0||string(reason)=="WORKER_ERROR_NO_COMMAND"
                obj.PreparationInFlight=false;obj.Failed=true;
                obj.FailureCode="PREPARATION__"+string(reason);
                if obj.PreparationWallS>=60.0,obj.FailureCode="PREPARATION_COLD_LIMIT_EXPIRED";end
                receipt=obj.preparationReceipt('FAIL_CLOSED',obj.FailureCode);return
            end
            late=string(reason)=="LATE_RESULT_DISCARDED";
            if ~ready&&~late
                assert(any(string(reason)==["PENDING","EXPIRED_STILL_BUSY_NO_REQUEUE"]), ...
                    'gpenmpcNative:BoardOuterPreparationWorker','Unexpected preparation disposition.');
                receipt=obj.preparationReceipt('PREPARATION_PENDING',reason);return
            end
            if late
                % Retain an expired gen-0 rehearsal result as diagnostics only.
                probe=obj.Worker.LastCompletedDiagnostic;
                obj.PreparationResultTiming="COLD_REHEARSAL_COMPLETED_EXPIRED";
            else
                obj.PreparationResultTiming="DIAGNOSTIC_WITHIN_SOLVER_DEADLINE";
            end
            assert(probe.used_current_supervisor ...
                &&uint64(probe.snapshot_timestamp_ns)==obj.PreparationSnapshotNs ...
                &&string(probe.configuration_payload_sha256)==obj.ConfigurationPayloadSha256 ...
                &&logical(probe.dynamic_snapshot_only)&&logical(probe.immutable_worker_constant), ...
                'gpenmpcNative:BoardOuterPreparationBinding','Actual same-input preparation result required.');
            assert(isequaln(obj.PreparationNumericalState,struct('warm_start',obj.WarmStart, ...
                'adapter',obj.Adapter,'physical',obj.PhysicalRuntime.status())), ...
                'gpenmpcNative:BoardOuterPreparationMutation','Preparation must not mutate numerical state.');
            obj.Prepared=true;obj.PreparationInFlight=false;
            obj.LastInputGenerations=obj.boundaryGenerations(obj.PreparationBoundary);
            obj.LastInputBoundary=obj.PreparationBoundary;
            receipt=obj.preparationReceipt('PASS_HOST_PREPARATION',reason);
            receipt.preparation_decision=probe.decision;receipt.preparation_audit=probe.audit;
            receipt.numerical_state_unchanged=true;
        end

        function response = update(obj,generation,nowNs,px4Sample,runtime)
            obj.requireActiveGeneration(generation);
            assert(~obj.AsyncInFlight,'gpenmpcNative:BoardOuterAsyncBusy', ...
                'A synchronous solve cannot compete with the in-flight worker.');
            obj.requireRuntimeTask(runtime);
            phase = struct('progress_s',obj.Adapter.phase_s, ...
                'progress_rate',obj.Adapter.phase_rate, ...
                'previous_phase_acceleration_s_inv', ...
                    obj.Adapter.previous_phase_acceleration_s_inv);
            [snapshot,accepted,reason,boundary] = ...
                gpenmpcNative.makeBoardOuterSnapshot(obj.WorkRoot, ...
                    px4Sample,obj.snapshotExpected(),nowNs,runtime,obj.Trajectory, ...
                    phase,obj.WarmStart,obj.Assets);
            if ~accepted
                obj.RejectedSnapshots = obj.RejectedSnapshots + uint64(1);
                response = obj.commitFailure(generation,reason,true,boundary,0.0);
                return
            end
            inputGenerations=obj.boundaryGenerations(boundary);
            [advanced,advanceReason]=gpenmpcNative.validateOuterObservationAdvance( ...
                obj.LastInputBoundary,boundary);
            if ~advanced
                obj.RejectedSnapshots=obj.RejectedSnapshots+uint64(1);
                boundary.status="REJECTED";
                boundary.reason=advanceReason;
                response=obj.commitFailure(generation, ...
                    advanceReason,true,boundary,0.0);
                return
            end
            obj.LastInputGenerations=inputGenerations;
            obj.LastInputBoundary=boundary;
            started = tic;
            result = gpenmpcNative.solveCurrentOuter(snapshot);
            wallS = toc(started);
            assert(result.snapshot_timestamp_ns == snapshot.snapshot_timestamp_ns ...
                && string(result.configuration_payload_sha256) == ...
                    string(snapshot.configuration_payload_sha256), ...
                'gpenmpcNative:BoardOuterResultBinding', ...
                'Current solver result is not bound to the submitted snapshot.');
            if wallS > obj.Config.solver_deadline_s
                obj.ExpiredSolverResults = obj.ExpiredSolverResults + uint64(1);
                response = obj.commitFailure(generation, ...
                    "SOLVER_WALL_DEADLINE_EXCEEDED",false,boundary,wallS);
                return
            end
            [obj.Adapter,event] = gpenmpcNative.commitBoardReferenceDecision( ...
                obj.Adapter,result.decision,result.audit,uint64(generation),obj.Config);
            obj.WarmStart = result.warm_start;
            obj.LastGeneration = uint64(generation);
            obj.AcceptedSolverResults = obj.AcceptedSolverResults + uint64(1);
            obj.FreshOuterForCurrentLeg=~obj.Adapter.hard_invalid_latched;
            if obj.Adapter.hard_invalid_latched
                obj.Failed = true;
                obj.FailureCode = "SOLVER_HARD_INVALID";
            end
            response = obj.responseStruct(generation,boundary,event, ...
                result.decision,result.audit,wallS,"FRESH_SOLVER_RESULT");
        end

        function response = submitUpdate(obj,generation,nowNs,px4Sample,runtime)
            % Submit one outer update asynchronously; permit one in-flight request
            % and account for rejected snapshots through continuity handling.
            assert(obj.AsyncEnabled && ~isempty(obj.Worker), ...
                'gpenmpcNative:BoardOuterAsyncNotEnabled', ...
                'The explicit async_outer_required identity is absent.');
            obj.requireActiveGeneration(generation);
            assert(~obj.AsyncInFlight, ...
                'gpenmpcNative:BoardOuterAsyncBusy', ...
                'Only one outer solver request may be in flight.');
            obj.requireRuntimeTask(runtime);
            phase = struct('progress_s',obj.Adapter.phase_s, ...
                'progress_rate',obj.Adapter.phase_rate, ...
                'previous_phase_acceleration_s_inv', ...
                    obj.Adapter.previous_phase_acceleration_s_inv);
            [snapshot,accepted,reason,boundary] = ...
                gpenmpcNative.makeBoardOuterSnapshot(obj.WorkRoot, ...
                    px4Sample,obj.snapshotExpected(),nowNs,runtime,obj.Trajectory, ...
                    phase,obj.WarmStart,obj.Assets);
            if ~accepted
                obj.RejectedSnapshots=obj.RejectedSnapshots+uint64(1);
                response=obj.commitFailure(generation,reason,true,boundary,0.0);
                response.async_disposition="REJECTED_BEFORE_SUBMIT";
                return
            end
            inputGenerations=obj.boundaryGenerations(boundary);
            [advanced,advanceReason]=gpenmpcNative.validateOuterObservationAdvance( ...
                obj.LastInputBoundary,boundary);
            if ~advanced
                obj.RejectedSnapshots=obj.RejectedSnapshots+uint64(1);
                boundary.status="REJECTED";
                boundary.reason=advanceReason;
                response=obj.commitFailure(generation, ...
                    advanceReason,true,boundary,0.0);
                response.async_disposition="REJECTED_BEFORE_SUBMIT";
                return
            end
            compact=obj.compactSnapshot(snapshot);
            submitted=obj.Worker.submit(compact,double(generation),double(nowNs));
            assert(submitted,'gpenmpcNative:BoardOuterAsyncSubmit', ...
                'The single-flight outer solver rejected an idle submit.');
            obj.AsyncInFlight=true;
            obj.AsyncCommitted=false;
            obj.AsyncRetiredForLifecycle=false;
            obj.AsyncGeneration=uint64(generation);
            obj.AsyncSubmittedNs=uint64(nowNs);
            obj.AsyncBoundary=boundary;
            obj.AsyncSnapshotTimestampNs=uint64(snapshot.snapshot_timestamp_ns);
            obj.AsyncInputGenerations=inputGenerations;
            obj.AsyncSubmitted=obj.AsyncSubmitted+uint64(1);
            response=struct('schema', ...
                'GPENMPC_BOARD_OUTER_ASYNC_SUBMIT_RESPONSE_V1', ...
                'status','SUBMITTED','generation',double(generation), ...
                'snapshot_timestamp_ns',double(snapshot.snapshot_timestamp_ns), ...
                'input_boundary',boundary,'hardware_actions',0, ...
                'com_open',0,'board_access',0);
        end

        function response = pollUpdate(obj,nowNs)
            % Poll the one in-flight solver without blocking. Deadline
            % expiry commits the existing safe-continuity fallback exactly
            % once; a later worker result is retained only as a discard fact.
            assert(isfinite(nowNs)&&nowNs>=0&&nowNs==fix(nowNs), ...
                'gpenmpcNative:BoardOuterAsyncPollTime','Invalid poll time.');
            if ~obj.AsyncInFlight
                response=struct('schema', ...
                    'GPENMPC_BOARD_OUTER_ASYNC_POLL_RESPONSE_V1', ...
                    'status','IDLE','hardware_actions',0, ...
                    'com_open',0,'board_access',0);
                return
            end
            if obj.AsyncRetiredForLifecycle
                % Drain the worker without applying results across LAND or leg transitions.
                [~,~,retiredReason]=obj.Worker.poll(double(nowNs),-1);
                terminal=any(string(retiredReason)==["STALE_GENERATION_DISCARDED", ...
                    "LATE_RESULT_DISCARDED","WORKER_ERROR_NO_COMMAND"]);
                if terminal
                    obj.AsyncInFlight=false;
                    obj.AsyncLifecycleDiscarded=obj.AsyncLifecycleDiscarded+uint64(1);
                    if string(retiredReason)=="WORKER_ERROR_NO_COMMAND"
                        obj.Failed=true;obj.FailureCode="RETIRED_OUTER_WORKER_ERROR";
                    end
                end
                response=struct('schema','GPENMPC_BOARD_OUTER_ASYNC_POLL_RESPONSE_V1', ...
                    'status','LIFECYCLE_RETIRED_RESULT_DRAIN','terminal',terminal, ...
                    'worker_reason',string(retiredReason),'generation',double(obj.AsyncGeneration), ...
                    'command_committed',false,'publication_allowed',false, ...
                    'hardware_actions',0,'com_open',0,'board_access',0);
                return
            end
            [ready,result,reason]=obj.Worker.poll( ...
                double(nowNs),double(obj.AsyncGeneration));
            elapsedS=max(0,(double(nowNs)-double(obj.AsyncSubmittedNs))*1e-9);
            if ready && ~obj.AsyncCommitted
                assert(uint64(result.snapshot_timestamp_ns)== ...
                    obj.AsyncSnapshotTimestampNs ...
                    && string(result.configuration_payload_sha256)== ...
                    obj.ConfigurationPayloadSha256 ...
                    && logical(result.dynamic_snapshot_only) ...
                    && logical(result.immutable_worker_constant), ...
                    'gpenmpcNative:BoardOuterAsyncBinding', ...
                    'Async solver result is not bound to the submitted identity.');
                [obj.Adapter,event]=gpenmpcNative.commitBoardReferenceDecision( ...
                    obj.Adapter,result.decision,result.audit, ...
                    obj.AsyncGeneration,obj.Config);
                obj.WarmStart=result.warm_start;
                obj.LastGeneration=obj.AsyncGeneration;
                obj.LastInputGenerations=obj.AsyncInputGenerations;
                obj.LastInputBoundary=obj.AsyncBoundary;
                obj.AcceptedSolverResults=obj.AcceptedSolverResults+uint64(1);
                obj.AsyncAccepted=obj.AsyncAccepted+uint64(1);
                obj.FreshOuterForCurrentLeg=~obj.Adapter.hard_invalid_latched;
                if obj.Adapter.hard_invalid_latched
                    obj.Failed=true;obj.FailureCode="SOLVER_HARD_INVALID";
                end
                response=obj.responseStruct(obj.AsyncGeneration, ...
                    obj.AsyncBoundary,event,result.decision,result.audit, ...
                    elapsedS,"FRESH_ASYNC_SOLVER_RESULT");
                response.schema= ...
                    "GPENMPC_BOARD_OUTER_ASYNC_POLL_RESPONSE_V1";
                response.status="FRESH_RESULT_COMMITTED";
                obj.AsyncCommitted=true;
                obj.AsyncInFlight=false;
                return
            end
            if obj.AsyncCommitted
                if reason=="WORKER_ERROR_NO_COMMAND"
                    % After deadline fallback consumes a generation, a later worker error
                    % must end the drain and clear the pending job.
                    obj.AsyncInFlight=false;
                    obj.Failed=true;obj.FailureCode="EXPIRED_OUTER_WORKER_ERROR";
                    obj.Adapter.hard_invalid_latched=true;
                    obj.Adapter.publication_allowed=false;
                    response=struct('schema', ...
                        'GPENMPC_BOARD_OUTER_ASYNC_POLL_RESPONSE_V1', ...
                        'status','FAIL_CLOSED_EXPIRED_WORKER_ERROR', ...
                        'generation',double(obj.AsyncGeneration), ...
                        'additional_command_committed',false, ...
                        'hardware_actions',0,'com_open',0,'board_access',0);
                elseif reason=="LATE_RESULT_DISCARDED" ...
                        || reason=="STALE_GENERATION_DISCARDED"
                    obj.AsyncLateDiscarded=obj.AsyncLateDiscarded+uint64(1);
                    obj.AsyncInFlight=false;
                    response=struct('schema', ...
                        'GPENMPC_BOARD_OUTER_ASYNC_POLL_RESPONSE_V1', ...
                        'status',string(reason),'generation', ...
                        double(obj.AsyncGeneration),'hardware_actions',0, ...
                        'com_open',0,'board_access',0);
                else
                    response=struct('schema', ...
                        'GPENMPC_BOARD_OUTER_ASYNC_POLL_RESPONSE_V1', ...
                        'status','EXPIRED_WORKER_DRAIN_PENDING', ...
                        'generation',double(obj.AsyncGeneration), ...
                        'hardware_actions',0,'com_open',0,'board_access',0);
                end
                return
            end
            if reason=="WORKER_ERROR_NO_COMMAND"
                response=obj.commitFailure(obj.AsyncGeneration, ...
                    "ASYNC_OUTER_WORKER_ERROR",true,obj.AsyncBoundary,elapsedS);
                response.schema= ...
                    "GPENMPC_BOARD_OUTER_ASYNC_POLL_RESPONSE_V1";
                response.status="FAIL_CLOSED_WORKER_ERROR";
                obj.AsyncCommitted=true;
                obj.AsyncInFlight=false;
                return
            end
            if elapsedS>obj.Config.solver_deadline_s
                obj.ExpiredSolverResults=obj.ExpiredSolverResults+uint64(1);
                obj.AsyncExpired=obj.AsyncExpired+uint64(1);
                response=obj.commitFailure(obj.AsyncGeneration, ...
                    "SOLVER_WALL_DEADLINE_EXCEEDED",false, ...
                    obj.AsyncBoundary,elapsedS);
                response.schema= ...
                    "GPENMPC_BOARD_OUTER_ASYNC_POLL_RESPONSE_V1";
                response.status="DEADLINE_FALLBACK_COMMITTED";
                obj.LastInputGenerations=obj.AsyncInputGenerations;
                obj.LastInputBoundary=obj.AsyncBoundary;
                obj.AsyncCommitted=true;
                return
            end
            response=struct('schema', ...
                'GPENMPC_BOARD_OUTER_ASYNC_POLL_RESPONSE_V1', ...
                'status','PENDING','generation',double(obj.AsyncGeneration), ...
                'elapsed_s',elapsedS,'hardware_actions',0, ...
                'com_open',0,'board_access',0);
        end

        function response = expire(obj,generation,reason)
            obj.requireActiveGeneration(generation);
            assert(~obj.AsyncInFlight,'gpenmpcNative:BoardOuterAsyncBusy', ...
                'The in-flight request is accounted only by pollUpdate.');
            obj.ExpiredSolverResults = obj.ExpiredSolverResults + uint64(1);
            boundary = struct('status',"NOT_SUBMITTED", ...
                'reason',string(reason),'hardware_actions',0);
            response = obj.commitFailure(generation,string(reason),false, ...
                boundary,obj.Config.solver_deadline_s);
        end

        function receipt = suspendOuterForLifecycle(obj,reason,nowNs)
            % Suspend after the last control sample and before LAND.
            % Drain an executing solver without reusing its result on the next leg.
            physical=obj.PhysicalRuntime.status();
            assert(~physical.sample_open, ...
                'gpenmpcNative:LifecycleOpenControlSample', ...
                'Close the last physical sample before lifecycle suspension.');
            assert(isscalar(nowNs)&&isfinite(nowNs)&&nowNs>=0 ...
                &&isscalar(string(reason)) ...
                &&any(string(reason)==["NATIVE_LAND","GROUND_SERVICE","SAFETY_EXIT"]), ...
                'gpenmpcNative:LifecycleSuspensionInput','Invalid lifecycle event.');
            wasSuspended=obj.OuterSuspended;
            obj.OuterSuspended=true;
            obj.Adapter.publication_allowed=false;
            if ~wasSuspended
                obj.LifecycleSuspendCount=obj.LifecycleSuspendCount+uint64(1);
            end
            if obj.AsyncInFlight
                obj.AsyncRetiredForLifecycle=true;
                % Keep submitted work accounted during landing without treating it as an accepted solve.
                obj.LastGeneration=max(obj.LastGeneration,obj.AsyncGeneration);
            end
            receipt=struct('status','OUTER_SUSPENDED_NO_PUBLICATION', ...
                'reason',string(reason),'now_ns',double(nowNs), ...
                'already_suspended',wasSuspended,'phase_s',obj.Adapter.phase_s, ...
                'inflight_retired',obj.AsyncInFlight,'last_generation',double(obj.LastGeneration), ...
                'command_committed',false,'hardware_actions',0);
        end

        function reference = stepReference(obj,dtS)
            assert(~obj.OuterSuspended,'gpenmpcNative:OuterLifecycleSuspended', ...
                'No reference progression during LAND/ground lifecycle.');
            assert(obj.ReferenceMode=="" ...
                || obj.ReferenceMode=="LEGACY_REFERENCE_ONLY", ...
                'gpenmpcNative:BoardReferenceModeConflict', ...
                'Legacy and current physical reference paths cannot be mixed.');
            obj.ReferenceMode="LEGACY_REFERENCE_ONLY";
            [obj.Adapter,reference] = gpenmpcNative.stepBoardReferenceAdapter( ...
                obj.Adapter,obj.Trajectory,dtS,obj.Config);
        end

        function receipt = beginLeg(obj,legIndex,trajectory,payloadKg, ...
                groundConfirmed,boardArmed,nowNs,px4Sample)
            % Reset per leg at the caller-controlled lifecycle boundary.
            % Failed sessions remain terminal.
            physical=obj.PhysicalRuntime.status();
            assert(~obj.Failed && ~obj.AsyncInFlight && ~physical.sample_open, ...
                'gpenmpcNative:BoardLegTransitionBusy', ...
                'Cannot reset failed, in-flight or uncommitted state.');
            assert(islogical(groundConfirmed)&&isscalar(groundConfirmed) ...
                &&groundConfirmed&&islogical(boardArmed)&&isscalar(boardArmed) ...
                &&~boardArmed&&isscalar(legIndex)&&isfinite(legIndex) ...
                &&legIndex==obj.CurrentLegIndex+1, ...
                'gpenmpcNative:BoardLegTransitionAuthority', ...
                'A sequential new leg requires confirmed ground and disarm.');
            % Validate/build locally before resetting any causal state.
            nextAdapter=gpenmpcNative.initializeBoardReferenceAdapter( ...
                obj.Config,trajectory,string(obj.Config.method));
            obj.PhysicalRuntime.prepareLegTransition(legIndex,payloadKg,nowNs,px4Sample);
            obj.Trajectory=trajectory;
            obj.Adapter=nextAdapter;
            obj.Adapter.last_committed_generation=obj.LastGeneration;
            obj.Adapter.publication_allowed=false;
            obj.WarmStart=zeros(1,obj.Config.decision_dimension);
            obj.CurrentLegIndex=double(legIndex);
            obj.CurrentPayloadKg=double(payloadKg);
            obj.FreshOuterForCurrentLeg=false;
            obj.OuterSuspended=false;
            obj.AsyncRetiredForLifecycle=false;
            obj.LegTransitionCount=obj.LegTransitionCount+uint64(1);
            receipt=struct('status','CANONICAL_NEW_LEG_RESET_NO_PUBLICATION', ...
                'leg_index',obj.CurrentLegIndex,'phase_s',0,'phase_rate',1, ...
                'warm_start_reset',true,'continuity_reset',true, ...
                'causal_history_reset',true,'outer_generation_preserved', ...
                double(obj.LastGeneration),'hardware_actions',0);
        end

        function response = stepGroundReference(obj,dtS,groundConfirmed,boardArmed)
            % Ground dwell belongs to delivery lifecycle, not flight phase.
            % No canonical outer/phase progress or command is consumed here.
            assert(obj.ReferenceMode=="CURRENT_A1_PHYSICAL", ...
                'gpenmpcNative:BoardGroundReferenceMode', ...
                'Ground lifecycle is available only on the physical path.');
            assert(islogical(groundConfirmed)&&isscalar(groundConfirmed) ...
                && groundConfirmed && islogical(boardArmed) ...
                && isscalar(boardArmed) && ~boardArmed, ...
                'gpenmpcNative:BoardGroundReferenceAuthority', ...
                'Ground clock advance requires confirmed ground and disarm.');
            assert(isscalar(dtS)&&isfinite(dtS)&&dtS>0, ...
                'gpenmpcNative:BoardGroundDt','Invalid dwell duration.');
            response=struct('schema', ...
                'GPENMPC_BOARD_GROUND_REFERENCE_RESPONSE_V1', ...
                'status','GROUND_DWELL_FLIGHT_CLOCK_PAUSED_NO_PUBLICATION', ...
                'phase_s',obj.Adapter.phase_s,'phase_rate',obj.Adapter.phase_rate, ...
                'dwell_step_s',double(dtS),'publication_allowed',false, ...
                'board_reference_publication_count',0, ...
                'hardware_actions',0,'com_open',0,'board_access',0);
        end

        function response = stepPhysicalReference(obj,generation,nowNs, ...
                px4Sample,runtime,dtS)
            assert(~obj.OuterSuspended,'gpenmpcNative:OuterLifecycleSuspended', ...
                'No control publication during LAND/ground lifecycle.');
            assert(~obj.Failed,'gpenmpcNative:BoardOuterFailed', ...
                'Board outer service is fail-closed: %s',obj.FailureCode);
            assert(obj.Prepared && obj.FreshOuterForCurrentLeg, ...
                'gpenmpcNative:BoardPhysicalReferenceNotAdmitted', ...
                'A fresh outer result is required before physical publication.');
            assert(obj.ReferenceMode=="" ...
                || obj.ReferenceMode=="CURRENT_A1_PHYSICAL", ...
                'gpenmpcNative:BoardReferenceModeConflict', ...
                'Legacy and current physical reference paths cannot be mixed.');
            obj.ReferenceMode="CURRENT_A1_PHYSICAL";
            % Read-only wall observations; NEVER supplied as control now/dt.
            profile=struct('scope','HOST_FUNCTION_OBSERVATION','clock_error','');
            profile=physicalProfileStamp(profile,'before_task_check_ns');
            obj.requireRuntimeTask(runtime);
            profile=physicalProfileStamp(profile,'before_adapter_ns');
            [obj.Adapter,baseReference] = ...
                gpenmpcNative.stepBoardReferenceAdapter( ...
                    obj.Adapter,obj.Trajectory,dtS,obj.Config);
            profile=physicalProfileStamp(profile,'after_adapter_ns');
            if ~baseReference.publication_allowed
                obj.Failed=true;
                obj.FailureCode="BASE_REFERENCE_PUBLICATION_SUPPRESSED";
                response=struct('schema', ...
                    'GPENMPC_BOARD_PHYSICAL_REFERENCE_RESPONSE_V1', ...
                    'accepted',false,'publication_allowed',false, ...
                    'reason',obj.FailureCode,'hardware_actions',0);
                return
            end
            profile=physicalProfileStamp(profile,'before_runtime_begin_ns');
            response=obj.PhysicalRuntime.beginSample( ...
                generation,nowNs,px4Sample,runtime, ...
                baseReference.reference_up,dtS);
            profile=physicalProfileStamp(profile,'after_runtime_begin_ns');
            response.schema= ...
                "GPENMPC_BOARD_PHYSICAL_REFERENCE_RESPONSE_V1";
            response.base_reference=baseReference;
            hostFullInner=isfield(response,'host_kernel_execution_allowed') ...
                &&isequal(response.host_kernel_execution_allowed,true) ...
                &&isfield(response,'board_publication_authority') ...
                &&isequal(response.board_publication_authority,false);
            boardPrepared=isfield(response,'board_commit_input_prepared') ...
                &&isequal(response.board_commit_input_prepared,true) ...
                &&isfield(response,'board_publication_authority')&&isequal(response.board_publication_authority,false);
            if ~response.accepted || (~response.publication_allowed && ~hostFullInner && ~boardPrepared)
                obj.Failed=true;
                obj.FailureCode="PHYSICAL_RUNTIME__"+string(response.reason);
                obj.Adapter.hard_invalid_latched=true;
                obj.Adapter.publication_allowed=false;
            end
            profile=physicalProfileStamp(profile,'after_response_ns');
            response.host_physical_profile=profile;
        end

        function response = commitPhysicalControl(obj,generation,nowNs,feedback)
            assert(obj.ReferenceMode=="CURRENT_A1_PHYSICAL", ...
                'gpenmpcNative:BoardPhysicalReferenceMode', ...
                'No current physical reference sample is open.');
            response=obj.PhysicalRuntime.commitControl( ...
                generation,nowNs,feedback);
            response.schema= ...
                "GPENMPC_BOARD_PHYSICAL_CONTROL_COMMIT_RESPONSE_V1";
            if ~response.accepted
                obj.Failed=true;
                if isfield(response,'reason')
                    obj.FailureCode="PHYSICAL_CONTROL_COMMIT__" ...
                        +string(response.reason);
                else
                    obj.FailureCode="PHYSICAL_CONTROL_COMMIT_REJECTED";
                end
                obj.Adapter.hard_invalid_latched=true;
                obj.Adapter.publication_allowed=false;
            end
        end

        function receipt=recordPhysicalBoardCommandSubmission(obj,generation,association,originalSubmitNs)
            assert(obj.ReferenceMode=="CURRENT_A1_PHYSICAL"&&~obj.Failed, ...
                'gpenmpcNative:BoardPhysicalReferenceMode','An original physical command must be open.');
            % Record the caller's transport event.
            receipt=obj.PhysicalRuntime.recordBoardCommandSubmission(generation,association,originalSubmitNs);
        end

        function response = commitV7PhysicalControl(obj,generation,nowNs, ...
                moduleGuard,actuatorOutput)
            assert(obj.ReferenceMode=="CURRENT_A1_PHYSICAL", ...
                'gpenmpcNative:BoardPhysicalReferenceMode', ...
                'No current physical reference sample is open.');
            response=obj.PhysicalRuntime.commitV7NominalControl( ...
                generation,nowNs,moduleGuard,actuatorOutput);
            response.schema= ...
                "GPENMPC_BOARD_V7_PHYSICAL_CONTROL_COMMIT_RESPONSE_V1";
            if ~response.accepted
                obj.Failed=true;
                if isfield(response,'reason')
                    obj.FailureCode="V7_PHYSICAL_CONTROL_COMMIT__" ...
                        +string(response.reason);
                else
                    obj.FailureCode="V7_PHYSICAL_CONTROL_COMMIT_REJECTED";
                end
                obj.Adapter.hard_invalid_latched=true;
                obj.Adapter.publication_allowed=false;
            end
        end

        function value = outerRuntime(obj,generation,nowNs,rotorCommandN, ...
                thrustEffectiveness,windEstimateXyMps,payloadKg)
            % Assemble the outer-solver input from causal runtime state and interface observations.
            assert(isfinite(generation)&&generation>=1 ...
                && generation==fix(generation) ...
                && isfinite(nowNs)&&nowNs>=0&&nowNs==fix(nowNs), ...
                'gpenmpcNative:BoardOuterRuntimeStamp','Invalid runtime stamp.');
            assert(isscalar(payloadKg)&&isfinite(payloadKg) ...
                &&payloadKg==obj.CurrentPayloadKg, ...
                'gpenmpcNative:CanonicalPayloadTransition', ...
                'Payload changes require the explicit ground-service leg transition.');
            rotor=double(rotorCommandN(:));
            effectiveness=double(thrustEffectiveness(:));
            wind=double(windEstimateXyMps(:));
            assert(numel(rotor)==6&&all(isfinite(rotor))&&all(rotor>=0) ...
                &&numel(effectiveness)==6&&all(isfinite(effectiveness)) ...
                &&all(effectiveness>0)&&numel(wind)==2&&all(isfinite(wind)) ...
                &&isfinite(payloadKg)&&payloadKg>=0, ...
                'gpenmpcNative:BoardOuterRuntimeValue','Invalid runtime value.');
            stamp=@(source)struct('source',source,'rx_ns',double(nowNs), ...
                'generation',double(generation),'valid',true);
            actuator=stamp('HOST_M600_VIRTUAL_ACTUATOR_INTERFACE');
            actuator.ordering='SOFTWARE_M600_ORDER';
            actuator.rotor_command_n=rotor;
            actuator.thrust_effectiveness=effectiveness;
            causal=obj.PhysicalRuntime.outerRuntimeState();
            if causal.desired_force_generation>0
                % After the first leg sample, use the previous controller command rather than lagged rotor state.
                actuator.rotor_command_n= ...
                    double(causal.previous_committed_rotor_command_n(:));
                actuator.command_source="PREVIOUS_COMMITTED_HIL_ACTUATOR_COMMAND";
                if causal.desired_force_source=="COMMITTED_CANONICAL_FULL_SE3_KERNEL_HOST_ONLY"
                    actuator.command_source="PREVIOUS_COMMITTED_FULL_KERNEL_HOST_COMMAND";
                elseif causal.desired_force_source=="COMMITTED_CANONICAL_FULL_SE3_KERNEL_BOARD_RFC1"
                    actuator.command_source="PREVIOUS_COMMITTED_FULL_KERNEL_BOARD_COMMAND";
                end
                actuator.command_generation=causal.desired_force_generation;
            else
                actuator.command_source="CANONICAL_LEG_INITIAL_ROTOR_STATE";
                actuator.command_generation=0;
            end
            if isempty(causal.previous_desired_force_projected_n)
                % Initialize the leg before its first control commit.
                causal.previous_desired_force_projected_n= ...
                    (double(obj.Assets.profile.mass_properties.base_mass_kg) ...
                    +double(payloadKg))*[0;0;9.80665];
                causal.desired_force_generation=0;
                causal.desired_force_source="CANONICAL_LEG_INITIAL_FORCE";
            end
            outer=stamp('HOST_CAUSAL_RUNTIME');
            names=fieldnames(causal);
            for k=1:numel(names),outer.(names{k})=causal.(names{k});end
            outer.previous_outer_acceleration_correction_i_mps2= ...
                double(obj.Adapter.previous_outer_correction_i_mps2(:));
            task=struct('source','FROZEN_GPENMPC_TASK_STATE', ...
                'payload_kg',double(payloadKg), ...
                'leg_index',obj.CurrentLegIndex, ...
                'corridor_half_width_m',double(obj.Config.corridor_half_width_m));
            windValue=stamp('FROZEN_TASK_WIND_ESTIMATOR');
            windValue.estimate_xy_mps=wind;
            value=struct('schema','GPENMPC_LIVE_OUTER_RUNTIME_V1', ...
                'task_identity_sha256',string(obj.Expected.task_identity_sha256), ...
                'plant_truth_used',false,'virtual_actuator',actuator, ...
                'outer',outer,'wind',windValue,'task',task);
        end

        function value = observedOuterRuntime(obj,generation,nowNs,virtualActuator,wind)
            % Live boundary: keep original external rx/generation. The
            % primitive outerRuntime API remains for isolated host fixtures
            % and the historical integrated-plant path, not sensor freshness.
            assert(~obj.Failed,'gpenmpcNative:BoardOuterFailed','Service is fail-closed.');
            fields={'rotor_thrust_state_n','thrust_effectiveness'};
            if ~isstruct(virtualActuator)||~all(isfield(virtualActuator,fields)) ...
                    ||~isstruct(wind)||~isfield(wind,'estimate_xy_mps')
                obj.Failed=true;obj.FailureCode="MISSING_OBSERVED_RUNTIME_INPUT";
                obj.Adapter.publication_allowed=false;
                error('gpenmpcNative:ObservedOuterRuntime','%s',obj.FailureCode);
            end
            prepared=obj.outerRuntime(generation,nowNs, ...
                virtualActuator.rotor_thrust_state_n,virtualActuator.thrust_effectiveness, ...
                wind.estimate_xy_mps,obj.CurrentPayloadKg);
            [value,ok,reason]=gpenmpcNative.bindCanonicalRuntimeObservations( ...
                prepared,virtualActuator,wind,nowNs,obj.Expected.maximum_runtime_age_ns);
            if ~ok
                obj.Failed=true;obj.FailureCode=reason;
                obj.Adapter.hard_invalid_latched=true;
                obj.Adapter.publication_allowed=false;
                error('gpenmpcNative:ObservedOuterRuntime','%s',reason);
            end
        end

        function value = status(obj)
            physicalStatus=obj.PhysicalRuntime.status();
            value = struct('schema','GPENMPC_BOARD_OUTER_SERVICE_STATUS_V1', ...
                'failed',obj.Failed,'failure_code',obj.FailureCode, ...
                'last_generation',double(obj.LastGeneration), ...
                'accepted_solver_results',double(obj.AcceptedSolverResults), ...
                'expired_solver_results',double(obj.ExpiredSolverResults), ...
                'rejected_snapshots',double(obj.RejectedSnapshots), ...
                'prepared',obj.Prepared, ...
                'preparation_calls',double(obj.PreparationCalls), ...
                'preparation_wall_s',obj.PreparationWallS, ...
                'preparation_in_flight',obj.PreparationInFlight, ...
                'preparation_expired',obj.PreparationExpired, ...
                'preparation_result_timing',obj.PreparationResultTiming, ...
                'publication_allowed',obj.Adapter.publication_allowed, ...
                'hard_invalid_latched',obj.Adapter.hard_invalid_latched, ...
                'reference_sample_count',double(obj.Adapter.reference_sample_count), ...
                'reference_mode',obj.ReferenceMode, ...
                'phase_s',obj.Adapter.phase_s, ...
                'phase_rate',obj.Adapter.phase_rate, ...
                'leg_index',obj.CurrentLegIndex, ...
                'leg_transition_count',double(obj.LegTransitionCount), ...
                'payload_kg',obj.CurrentPayloadKg, ...
                'fresh_outer_for_current_leg',obj.FreshOuterForCurrentLeg, ...
                'canonical_package_root',string(obj.Expected.canonical_package_root), ...
                'canonical_source_root',obj.Assets.sourceRoot, ...
                'outer_period_s',obj.Config.outer_period_s, ...
                'prediction_step_s',obj.Config.prediction_step_s, ...
                'prediction_horizon_s',obj.Config.prediction_horizon_s, ...
                'async_in_flight',obj.AsyncInFlight, ...
                'async_enabled',obj.AsyncEnabled, ...
                'async_warmup_wall_s',obj.AsyncWarmupWallS, ...
                'async_committed',obj.AsyncCommitted, ...
                'async_generation',double(obj.AsyncGeneration), ...
                'async_submitted',double(obj.AsyncSubmitted), ...
                'async_accepted',double(obj.AsyncAccepted), ...
                'async_expired',double(obj.AsyncExpired), ...
                'async_late_discarded',double(obj.AsyncLateDiscarded), ...
                'outer_suspended',obj.OuterSuspended, ...
                'lifecycle_suspend_count',double(obj.LifecycleSuspendCount), ...
                'async_lifecycle_discarded',double(obj.AsyncLifecycleDiscarded), ...
                'async_retired_for_lifecycle',obj.AsyncRetiredForLifecycle, ...
                'physical_runtime',physicalStatus, ...
                'last_input_generations',obj.LastInputGenerations, ...
                'configuration_payload_sha256', ...
                    obj.ConfigurationPayloadSha256, ...
                'hardware_actions',0,'com_open',0,'board_access',0);
        end

        function close(obj)
            if ~isempty(obj.Worker)
                obj.Worker.close();
            end
            if ~isempty(obj.FixedAssets)
                delete(obj.FixedAssets);
            end
            obj.Worker=[];obj.FixedAssets=[];
        end

        function delete(obj)
            obj.close();
        end
    end
    methods (Access=private)
        function r=preparationReceipt(obj,status,reason)
            r=struct('status',string(status),'reason',string(reason), ...
                'wall_s',obj.PreparationWallS,'async_warmup_wall_s',obj.AsyncWarmupWallS, ...
                'solver_deadline_s',obj.Config.solver_deadline_s,'cold_engineering_limit_s',60.0, ...
                'original_submit_ns',obj.PreparationSubmittedNs, ...
                'original_snapshot_ns',obj.PreparationSnapshotNs, ...
                'original_poll_ns',obj.PreparationLastEventNs, ...
                'input_boundary',obj.PreparationBoundary,'generation',uint64(0), ...
                'preparation_result_timing',obj.PreparationResultTiming, ...
                'worker_expired_count',obj.Worker.Expired, ...
                'worker_submitted_count',obj.Worker.Submitted, ...
                'preparation_expired',obj.PreparationExpired,'async_enabled',obj.AsyncEnabled, ...
                'generation_consumed',false,'command_committed',false,'publication_count',0, ...
                'result_fresh_for_control',false,'hardware_actions',0,'com_open',0,'board_access',0);
        end
        function requireRuntimeTask(obj,runtime)
            ok=isstruct(runtime)&&isscalar(runtime)&&isfield(runtime,'task') ...
                &&isstruct(runtime.task)&&isscalar(runtime.task) ...
                &&all(isfield(runtime.task,{'leg_index','payload_kg'})) ...
                &&isequal(double(runtime.task.leg_index),obj.CurrentLegIndex) ...
                &&isequal(double(runtime.task.payload_kg),obj.CurrentPayloadKg);
            if ~ok
                obj.Failed=true;obj.FailureCode="UNAUTHORIZED_LEG_OR_PAYLOAD_CHANGE";
                obj.Adapter.hard_invalid_latched=true;
                obj.Adapter.publication_allowed=false;
                error('gpenmpcNative:BoardRuntimeTaskBinding', ...
                    'Input leg/payload differs from the explicitly active leg.');
            end
        end

        function expected=snapshotExpected(obj)
            expected=obj.Expected;
            causal=obj.PhysicalRuntime.outerRuntimeState();
            expected.outer_snapshot_leg_index=obj.CurrentLegIndex;
            expected.last_committed_inner_generation= ...
                double(causal.desired_force_generation);
            expected.outer_snapshot_first_in_leg= ...
                causal.desired_force_generation==0;
        end

        function requireActiveGeneration(obj,generation)
            assert(~obj.OuterSuspended,'gpenmpcNative:OuterLifecycleSuspended', ...
                'No outer submit/commit during LAND/ground lifecycle.');
            assert(~obj.Failed,'gpenmpcNative:BoardOuterFailed', ...
                'Board outer service is fail-closed: %s',obj.FailureCode);
            assert(obj.Prepared,'gpenmpcNative:BoardOuterNotPrepared', ...
                'Run the zero-generation HOST preparation before update.');
            assert(isa(generation,'uint64') && isscalar(generation) ...
                && generation == obj.LastGeneration + uint64(1), ...
                'gpenmpcNative:BoardOuterGeneration', ...
                'Outer generations must be exact, monotone, and gap-free.');
        end

        function response = commitFailure(obj,generation,reason,hardInvalid,boundary,wallS)
            decision = struct('method',string(obj.Config.method), ...
                'success',false,'hard_invalid',logical(hardInvalid), ...
                'phase_acceleration_s_inv',0.0, ...
                'outer_acceleration_correction_f_mps2',zeros(3,1), ...
                'fallback_reason',string(reason),'elapsed_seconds',double(wallS), ...
                'gp_b1_fallback_active',false);
            audit = struct('current_hard_invalid',logical(hardInvalid), ...
                'coordinated_selected_method',string(obj.Config.method));
            [obj.Adapter,event] = gpenmpcNative.commitBoardReferenceDecision( ...
                obj.Adapter,decision,audit,uint64(generation),obj.Config);
            obj.LastGeneration = uint64(generation);
            if hardInvalid
                obj.Failed = true;
                obj.FailureCode = string(reason);
            end
            response = obj.responseStruct(generation,boundary,event, ...
                decision,audit,wallS,"FAILURE_CONTINUITY_COMMIT");
        end

        function response = responseStruct(obj,generation,boundary,event, ...
                decision,audit,wallS,disposition)
            selectedMethod = "";
            if isfield(audit,'coordinated_selected_method')
                selectedMethod = string(audit.coordinated_selected_method);
            end
            response = struct( ...
                'schema','GPENMPC_BOARD_OUTER_UPDATE_RESPONSE_V1', ...
                'generation',double(generation), ...
                'disposition',string(disposition), ...
                'decision_success',logical(decision.success), ...
                'hard_invalid',logical(decision.hard_invalid), ...
                'selected_method',selectedMethod, ...
                'phase_acceleration_s_inv', ...
                    obj.Adapter.target_phase_acceleration_s_inv, ...
                'outer_acceleration_correction_f_mps2', ...
                    obj.Adapter.target_outer_correction_f_mps2, ...
                'applied_command_source',string(event.applied_command_source), ...
                'publication_allowed',obj.Adapter.publication_allowed, ...
                'solver_wall_s',double(wallS), ...
                'solver_deadline_s',obj.Config.solver_deadline_s, ...
                'input_boundary',boundary, ...
                'solver_decision',decision,'solver_audit',audit, ...
                'continuity_event',event, ...
                'leg_index',obj.CurrentLegIndex, ...
                'configuration_payload_sha256',obj.ConfigurationPayloadSha256, ...
                'failed',obj.Failed,'failure_code',obj.FailureCode, ...
                'hardware_actions',0,'com_open',0,'board_access',0);
        end

        function compact=compactSnapshot(obj,snapshot)
            fixed=obj.FixedAssets.Value;
            compact=rmfield(snapshot,{'source_root','config','context','gp_model'});
            compact.work_root=obj.WorkRoot;
            compact.source_manifest_sha256=fixed.source_manifest_sha256;
            compact.source_binding_sha256=fixed.source_binding_sha256;
            compact.gp_model_sha256=fixed.gp_model_sha256;
        end


        function values=boundaryGenerations(~,boundary)
            values=[double(boundary.estimate_generations(:).'), ...
                double(boundary.virtual_actuator_generation), ...
                double(boundary.outer_runtime_generation), ...
                double(boundary.wind_generation)];
            assert(numel(values)==6 && all(isfinite(values)) ...
                && all(values>=1) && all(values==fix(values)), ...
                'gpenmpcNative:BoardOuterBoundaryGeneration', ...
                'Input boundary generations must be six positive integers.');
        end
    end
end
function profile=physicalProfileStamp(profile,name)
try,profile.(name)=gpenmpcNative.rflyOriginalHostMonotonicNs();
catch problem,profile.(name)=uint64(0);profile.clock_error=problem.identifier;end
end
