function [actual,estimate,selection]=canonicalSavedTaskWindAt(reference,globalTime,legIndex)
% Evaluate the saved task's two exogenous wind fields.
if isa(reference,'gpenmpcNative.RflyLocalTaskAsset')
    [actual,estimate,selection]=reference.windAt(globalTime,legIndex);return
end
time=double(reference.global_time_s(:));
assert(isnumeric(globalTime)&&isreal(globalTime)&&isscalar(globalTime)&&isfinite(globalTime) ...
    &&numel(time)>1&&all(isfinite(time))&&all(diff(time)>0) ...
    &&isequal(size(reference.actual_wind_xy_mps),[numel(time),2]) ...
    &&isequal(size(reference.wind_estimate_xy_mps),[numel(time),2]) ...
    &&all(isfinite(reference.actual_wind_xy_mps(:)))&&all(isfinite(reference.wind_estimate_xy_mps(:))), ...
    'gpenmpcNative:CanonicalTaskWind','Complete original finite task wind fields required.');
query=min(max(globalTime,time(1)),time(end));
actual=interp1(time,double(reference.actual_wind_xy_mps),query,"linear").';
estimate=interp1(time,double(reference.wind_estimate_xy_mps),query,"linear").';
row=find(time<=query,1,'last');
assert(reference.leg_index(row)==legIndex,'gpenmpcNative:CanonicalTaskWindLeg','Original task row differs from active leg.');
selection=struct('schema','RFLY_CANONICAL_LINEAR_TASK_WIND_V1','saved_task_time_s',globalTime, ...
    'evaluated_task_time_s',query,'left_source_row',row,'right_source_row',min(row+1,numel(time)), ...
    'leg_index',legIndex,'actual_wind_xy_mps',actual,'wind_estimate_xy_mps',estimate, ...
    'arithmetic_source','CANONICAL_WHOLE_TASK_EXOGENOUS_AT_LINEAR','online_wind_measurement',false);
end
