function [candidate,out] = canonicalLocalInnerPreControl( ...
        committed,input,previousPending,numerics,branchSpecialization)
% CANONICALLOCALINNERPRECONTROL Compute the fast-control numerical candidate.
% Inputs include x13, rotor thrust, reference p/v/a/j, payload, wind estimate,
% dt, source timestamp/generation, leg index and new_leg.
% Use canonical numerical parameters; GP inference remains separate.
% COMMITTED=[] initializes a new leg. Otherwise pass the state installed after
% the prior output commit and its pending prediction/velocity/nominal/frame metadata.
% Install CANDIDATE only after successful output commit.
% Returned source tags retain the caller's identity and timestamps.
arguments
    committed
    input (1,1) struct
    previousPending (1,1) struct
    numerics (1,1) struct
    branchSpecialization (1,1) logical = input.new_leg
end
% Generated first/ordinary entries specialize the explicit new-leg branch.
newLeg=coder.const(branchSpecialization);
assert(newLeg==input.new_leg,'gpenmpcNative:LocalPreControlSpecialization', ...
    'The generated branch must match the original explicit new-leg input.');
required={'x13','rotor_thrust_state_n','reference_up','payload_kg', ...
    'wind_estimate_xy_mps','dt_s','source_timestamp_ns', ...
    'source_generation','leg_index','new_leg'};
assert(gpenmpcNative.hasCanonicalFields(input,required) ...
    &&gpenmpcNative.hasCanonicalFields(numerics,{'robust','enmpc','calibration','profile', ...
        'attitudeContinuity','kernelParameters'}), ...
    'gpenmpcNative:LocalPreControlInput','Explicit original inputs/configuration required.');
% Accept measured intervals of 2--20 ms around the 100 Hz target.
assert(finiteVector(input.x13,13)&&finiteVector(input.rotor_thrust_state_n,6) ...
    &&finiteVector(input.wind_estimate_xy_mps,2) ...
    &&finiteScalar(input.payload_kg)&&input.payload_kg>=0 ...
    &&finiteScalar(input.dt_s)&&input.dt_s>=.002&&input.dt_s<=.0200001 ...
    &&isa(input.source_timestamp_ns,'uint64')&&isscalar(input.source_timestamp_ns) ...
    &&input.source_timestamp_ns>0 ...
    &&isa(input.source_generation,'uint64')&&isscalar(input.source_generation) ...
    &&input.source_generation>0 ...
    &&finiteScalar(input.leg_index)&&input.leg_index>=1 ...
    &&input.leg_index==fix(input.leg_index) ...
    &&islogical(input.new_leg)&&isscalar(input.new_leg), ...
    'gpenmpcNative:LocalPreControlInput','Malformed numerical/source inputs.');
r=input.reference_up;
assert(isstruct(r)&&isscalar(r)&&gpenmpcNative.hasCanonicalFields(r, ...
    {'position_m','velocity_mps','acceleration_mps2','jerk_mps3'}) ...
    &&finiteVector(r.position_m,3)&&finiteVector(r.velocity_mps,3) ...
    &&finiteVector(r.acceleration_mps2,3)&&finiteVector(r.jerk_mps3,3), ...
    'gpenmpcNative:LocalPreControlReference','Original finite p/v/a/j required.');
if isempty(committed)
    assert(input.new_leg,'gpenmpcNative:LocalPreControlInitialization', ...
        'Initial numerical state requires an explicit new leg.');
    committed=struct('robust_state',gpenmpcInitializeRobustSe3State(), ...
        'attitude_continuity_state',gpenmpcInitializeDesiredAttitudeContinuityState(), ...
        'residual_history_f_mps2',zeros(3,1),'gp_agreement_weight_f',zeros(3,1), ...
        'previous_rotor_command_n',[],'previous_desired_force_projected_up_n',[], ...
        'causal_valid',false,'last_sample_timestamp_ns',uint64(0), ...
        'source_generation',uint64(0),'leg_index',NaN);
end
assert(isstruct(committed)&&isscalar(committed)&&gpenmpcNative.hasCanonicalFields(committed, ...
    {'robust_state','attitude_continuity_state','residual_history_f_mps2', ...
    'gp_agreement_weight_f','previous_rotor_command_n', ...
    'previous_desired_force_projected_up_n','causal_valid', ...
    'last_sample_timestamp_ns','source_generation','leg_index'}), ...
    'gpenmpcNative:LocalPreControlState','Original committed numerical state required.');
assert(isequal(input.new_leg,isnan(committed.leg_index) ...
    ||input.leg_index~=committed.leg_index), ...
    'gpenmpcNative:LocalPreControlLeg','Do not reset continuity on the same leg.');
assert(input.source_timestamp_ns>committed.last_sample_timestamp_ns ...
    &&input.source_generation>committed.source_generation, ...
    'gpenmpcNative:LocalPreControlSource','Original source must advance; no +1 source rule is imposed.');
candidate=committed;
x13=double(input.x13(:));x19=[x13;double(input.rotor_thrust_state_n(:))];
dt=double(input.dt_s);stamp=input.source_timestamp_ns;
if newLeg
    candidate.residual_history_f_mps2=zeros(3,1);
    candidate.causal_valid=false;
    candidate.gp_agreement_weight_f=zeros(3,1);
    candidate.previous_rotor_command_n=double(input.rotor_thrust_state_n(:));
    candidate.previous_desired_force_projected_up_n= ...
        (double(numerics.profile.mass_properties.base_mass_kg)+input.payload_kg)*[0;0;9.80665];
    latest=emptyEvidence();
    candidate.robust_state=gpenmpcResetCausalVerticalDisturbanceObserver( ...
        candidate.robust_state,x13(4:6),double(stamp)*1.0e-9, ...
        input.leg_index,input.payload_kg);
else
    fields={'prediction','velocity_up_mps','nominal_acceleration_up_mps2', ...
        'frame_i_from_f','generation','timestamp_ns','leg_index'};
    assert(gpenmpcNative.hasCanonicalFields(previousPending,fields) ...
        &&isequal(previousPending.timestamp_ns,committed.last_sample_timestamp_ns) ...
        &&isequal(previousPending.generation,committed.source_generation) ...
        &&isequal(previousPending.leg_index,committed.leg_index), ...
        'gpenmpcNative:LocalPreControlPending','Previous committed interval must match the state.');
    assert(finiteVector(previousPending.velocity_up_mps,3) ...
        &&finiteVector(previousPending.nominal_acceleration_up_mps2,3) ...
        &&isequal(size(previousPending.frame_i_from_f),[3,3]) ...
        &&all(isfinite(previousPending.frame_i_from_f),'all') ...
        &&isstruct(previousPending.prediction) ...
        &&isequal(previousPending.prediction.prediction_sample_closed,false) ...
        &&isequal(previousPending.prediction.observed_innovation_available,false), ...
        'gpenmpcNative:LocalPreControlPending','An original unclosed prediction is required.');
    % Preserve subtraction before time-unit conversion.
    interval=(double(stamp)-double(committed.last_sample_timestamp_ns))*1.0e-9;
    assert(isfinite(interval)&&interval>1.0e-9&&interval<=.0200001 ...
        &&abs(interval-dt)<=5.0e-7, ...
        'gpenmpcNative:LocalPreControlInterval','Original causal interval differs from dt.');
    [candidate.residual_history_f_mps2,residualF,labelValid]= ...
        gpenmpcAdvanceCausalResidualHistory(candidate.residual_history_f_mps2, ...
        previousPending.velocity_up_mps,x13(4:6), ...
        previousPending.nominal_acceleration_up_mps2, ...
        previousPending.frame_i_from_f,interval,true,0.50);
    observedI=previousPending.frame_i_from_f*residualF;
    closed=gpenmpcCloseGpInnovationEvidence(previousPending.prediction, ...
        observedI,logical(labelValid)&&all(isfinite(observedI)),numerics.enmpc);
    [candidate.gp_agreement_weight_f,consistency]=gpenmpcUpdateGpAgreementWeight( ...
        candidate.gp_agreement_weight_f,closed,interval,numerics.enmpc);
    latest=attachConsistency(closed,consistency,numerics.enmpc);
    candidate.causal_valid=logical(labelValid) ...
        &&all(isfinite(candidate.residual_history_f_mps2));
end
[candidate.robust_state,vertical]=gpenmpcObserveCausalVerticalDisturbance( ...
    candidate.robust_state,x13(4:6),double(stamp)*1.0e-9, ...
    input.leg_index,input.payload_kg,numerics.robust);
executionEvidence=latest;
if ~logical(executionEvidence.available)
    executionEvidence.predicted_mean_f_mps2=zeros(1,3);
    executionEvidence.observed_innovation_f_mps2=zeros(1,3);
    executionEvidence.calibrated_half_width_f_mps2=ones(1,3);
end
physicalReference=struct('position_m',double(r.position_m(:)), ...
    'velocity_mps',double(r.velocity_mps(:)));
[augmentation,candidate.robust_state,physical]= ...
    gpenmpcCoordinatedGpRobustSe3Augmentation(x19,physicalReference, ...
        numerics.robust,candidate.robust_state,dt,executionEvidence, ...
        double(candidate.gp_agreement_weight_f(:)),numerics.enmpc);
assert(all(isfinite(augmentation))&&norm(augmentation)<= ...
    double(numerics.robust.combined_compensation_cap_mps2)+1.0e-12, ...
    'gpenmpcNative:LocalPreControlAugmentation','Original compensation bound failed.');
% Augment reference acceleration once.
raw=gpenmpcDesiredSe3Command(x19,r,input.payload_kg, ...
    input.wind_estimate_xy_mps,augmentation,numerics.calibration,numerics.profile);
[attitude,candidate.attitude_continuity_state]=gpenmpcUpdateDesiredAttitudeContinuity( ...
    candidate.attitude_continuity_state,raw.desired_rotation,dt,input.new_leg,numerics.attitudeContinuity);
assert(~attitude.time_discontinuity,'gpenmpcNative:LocalPreControlContinuity', ...
    'The original desired-attitude continuity rejected this interval.');
[w,u,d,valid]=gpenmpcNative.se3WrenchKernel(x19,r.position_m,r.velocity_mps, ...
    r.acceleration_mps2,input.payload_kg,input.wind_estimate_xy_mps,augmentation, ...
    true,attitude.desired_rotation,attitude.desired_angular_velocity_body_rad_s, ...
    attitude.desired_angular_acceleration_body_rad_s2,numerics.kernelParameters);
assert(valid&&all(isfinite([w;u;d])), ...
    'gpenmpcNative:LocalPreControlKernel','Canonical kernel rejected its candidate.');
candidate.last_sample_timestamp_ns=stamp;
candidate.source_generation=input.source_generation;
candidate.leg_index=input.leg_index;
control=struct('desired_force_projected_up_n',double(d(4:6)), ...
    'rotor_command_n',double(u),'rotor_saturated',logical(d(51)), ...
    'force_projection_norm_mismatch_n',double(d(49)), ...
    'desired_moment_nm',double(w(2:4)),'desired_thrust_n',double(w(1)));
out=struct('schema','CANONICAL_LOCAL_INNER_NUMERICAL_CANDIDATE_V1', ...
    'input',input,'x19',x19,'kernel_control_candidate',control, ...
    'source_timestamp_ns',stamp,'source_generation',input.source_generation, ...
    'closed_gp_evidence',latest,'vertical_observer',vertical, ...
    'physical_diagnostic',physical,'augmentation_up_mps2',augmentation, ...
    'attitude_command',attitude,'kernel_output61',[w;u;d], ...
    'candidate_only',true,'board_publication_authority',false, ...
    'current_gp_prediction_performed',false,'hardware_actions',0);
end

function value=attachConsistency(value,diagnostic,config)
value.consistency_ewma_f=double(diagnostic.next_weight_f(:).');
value.consistency_evidence_active=logical(diagnostic.valid_closed_evidence);
value.consistency_ewma_aggregate=double(diagnostic.aggregate_consistency_score);
value.normalized_innovation_error_f=double(diagnostic.normalized_innovation_error_f(:).');
value.innovation_consistency_score_f=double(diagnostic.instantaneous_consistency_score_f(:).');
value.consistency_enter_eligible=logical(diagnostic.enter_eligible);
value.consistency_exit_low=logical(diagnostic.exit_low);
value.eligible_for_b1_dwell=logical(diagnostic.enter_eligible)&&logical(value.available) ...
    &&logical(value.observed_innovation_available)&&~logical(value.hard_invalid) ...
    &&double(value.trust)>=double(config.minimum_soft_trust);
end
function value=emptyEvidence()
value=struct('available',false,'prediction_sample_closed',false, ...
    'observed_innovation_available',false,'hard_invalid',false,'trust',0.0, ...
    'predicted_mean_f_mps2',zeros(1,3),'gp_frame_i_from_f',eye(3), ...
    'observed_innovation_f_mps2',zeros(1,3),'calibrated_half_width_f_mps2',ones(1,3), ...
    'observed_innovation_consistent',false,'eligible_for_b1_dwell',false);
end
function yes=finiteVector(x,n)
yes=isnumeric(x)&&isreal(x)&&isvector(x)&&numel(x)==n&&all(isfinite(x(:)));
end
function yes=finiteScalar(x)
yes=isnumeric(x)&&isreal(x)&&isscalar(x)&&isfinite(x);
end
