function [result,accepted,reason]=canonicalRotorToActuatorMotors(rotorN,calibration,interface)
% Convert allocated rotor forces into PX4 motor units and ordering.
% Follow FunctionMotors(THR_MDL_FAC=0), output_limit_calc_single and PWMSim.
% The 1000..2000 uint16 representation introduces quantization.
result=struct('valid',false,'publication_allowed',false,'hardware_actions',0);
accepted=false;reason="INVALID_INTERFACE_CONTRACT";
fields={'schema','input_units','input_order','allocation_matrix', ...
    'per_rotor_upper_n','software_from_px4_one_based','hil_output_functions', ...
    'thr_mdl_fac','reversible_flags','output_reverse_mask', ...
    'pwm_sim_min','pwm_sim_max','output_limit_state'};
if ~isstruct(interface)||~isscalar(interface)||~all(isfield(interface,fields)) ...
        ||~isstruct(calibration)||~isscalar(calibration)||~isfield(calibration,'rotor_allocation')
    return
end
if ~sameText(interface.schema,"CANONICAL_M600_ROTOR_EXECUTION_INTERFACE_V1") ...
        ||~sameText(interface.input_units,"NEWTON") ...
        ||~sameText(interface.input_order,"CANONICAL_M600_ORDER")
    reason="UNITS_OR_ORDER_CONTRACT_REJECTED";return
end
r=calibration.rotor_allocation;
rf={'angles_deg','spin_sign','arm_radius_m','yaw_moment_arm_nominal_m','per_rotor_thrust_upper_n'};
if ~isstruct(r)||~isscalar(r)||~all(isfield(r,rf)) ...
        ||~finiteVector(r.angles_deg,6)||~finiteVector(r.spin_sign,6) ...
        ||~isequal(double(r.angles_deg(:)),[0;60;120;180;240;300]) ...
        ||~isequal(double(r.spin_sign(:)),[1;-1;1;-1;1;-1]) ...
        ||~finiteScalar(r.arm_radius_m)||r.arm_radius_m~=0.5665 ...
        ||~finiteScalar(r.yaw_moment_arm_nominal_m)||r.yaw_moment_arm_nominal_m~=0.025 ...
        ||~finiteScalar(r.per_rotor_thrust_upper_n)||r.per_rotor_thrust_upper_n~=32.145727009134916
    reason="NONCANONICAL_GEOMETRY_OR_LIMIT";return
end
angles=deg2rad(double(r.angles_deg(:)));upper=double(r.per_rotor_thrust_upper_n);
A=[ones(1,6);double(r.arm_radius_m).*sin(angles).'; ...
    -double(r.arm_radius_m).*cos(angles).'; ...
    double(r.yaw_moment_arm_nominal_m).*double(r.spin_sign(:)).'];
if ~isnumeric(interface.allocation_matrix)||~isreal(interface.allocation_matrix) ...
        ||~isequal(size(interface.allocation_matrix),[4,6]) ...
        ||any(~isfinite(interface.allocation_matrix),'all') ...
        ||max(abs(double(interface.allocation_matrix)-A),[],'all')>1e-14 ...
        ||~finiteScalar(interface.per_rotor_upper_n)||interface.per_rotor_upper_n~=upper ...
        ||~finiteVector(interface.software_from_px4_one_based,6) ...
        ||~isequal(double(interface.software_from_px4_one_based(:)),[5;1;4;6;2;3])
    reason="ALLOCATION_OR_PERMUTATION_IDENTITY_REJECTED";return
end
if ~finiteVector(interface.hil_output_functions,16) ...
        ||~isequal(double(interface.hil_output_functions(:)),[(101:106)';zeros(10,1)]) ...
        ||~finiteScalar(interface.thr_mdl_fac)||interface.thr_mdl_fac~=0 ...
        ||~finiteScalar(interface.reversible_flags)||interface.reversible_flags~=0 ...
        ||~finiteScalar(interface.output_reverse_mask)||interface.output_reverse_mask~=0 ...
        ||~finiteScalar(interface.pwm_sim_min)||interface.pwm_sim_min~=1000 ...
        ||~finiteScalar(interface.pwm_sim_max)||interface.pwm_sim_max~=2000 ...
        ||~sameText(interface.output_limit_state,"ON")
    reason="PX4_OUTPUT_PATH_NOT_THE_AUDITED_LINEAR_ON_STATE";return
end
if ~finiteVector(rotorN,6)||any(rotorN(:)<0)||any(rotorN(:)>upper)
    reason="ROTOR_INPUT_NOT_FINITE_PRECLIPPED_NEWTON";return
end
rotorN=double(rotorN(:));map=double(interface.software_from_px4_one_based(:));
normalizedSoftware=rotorN/upper;
normalizedPx4=zeros(6,1);normalizedPx4(map)=normalizedSoftware;
% ActuatorMotors is float32[12]; unused motors use topic-defined NaN stop.
controls=nan(12,1,'single');controls(1:6)=single(normalizedPx4);
functionValues=controls(1:6).*single(2)-single(1);
% math::interpolate: a=(2000-1000)/(1-(-1)); b=1000-a*(-1).
interpolated=single(500).*functionValues+single(1500);
interpolated(functionValues<=single(-1))=single(1000);
interpolated(functionValues>single(1))=single(2000);
% Values are nonnegative, so MATLAB round matches C lroundf ties-away.
pwm=uint16(round(interpolated));
wire=single((single(pwm)-single(1000))./single(1000));
decoded=double(wire(map))*upper;
result=struct('schema','CANONICAL_M600_ROTOR_EXECUTION_PREVIEW_V1', ...
    'valid',true,'publication_allowed',false,'hardware_actions',0, ...
    'controller_or_allocator_recomputed',false,'helper_clipping_performed',false, ...
    'input_rotor_newton',rotorN,'software_from_px4_one_based',map, ...
    'actuator_motors_control',controls,'reversible_flags',uint16(0), ...
    'expected_pwm_sim_u16_on',pwm,'expected_hil_controls_1_to_6_on',wire, ...
    'expected_linear_host_decoded_rotor_newton',decoded, ...
    'signed_quantization_error_newton',decoded-rotorN, ...
    'maximum_absolute_error_newton',max(abs(decoded-rotorN)), ...
    'ideal_half_step_error_bound_newton',upper/2000, ...
    'float32_arithmetic_guard_newton',upper*(4*double(eps(single(2000)))/1000+double(eps(single(1)))), ...
    'requested_allocated_wrench_txyz',A*rotorN, ...
    'expected_quantized_wrench_txyz',A*decoded, ...
    'exact_arbitrary_real_output_equivalence',false, ...
    'single_publisher_or_board_deployment_verified',false, ...
    'scope','HOST_ONLY_CONVERSION_AND_SOURCE_DERIVED_QUANTIZATION_PREVIEW');
accepted=true;reason="PASS_CONVERSION_WITH_DISCLOSED_PWM_QUANTIZATION";
end

function ok=finiteScalar(v)
ok=isnumeric(v)&&isreal(v)&&isscalar(v)&&isfinite(v);
end
function ok=finiteVector(v,n)
ok=isnumeric(v)&&isreal(v)&&isvector(v)&&numel(v)==n&&all(isfinite(v(:)));
end
function ok=sameText(v,t)
ok=(isstring(v)&&isscalar(v)||ischar(v)&&isrow(v))&&string(v)==t;
end
