function [next64,kernel61,scaffold70,request19,closed5,learning12] = canonicalLocalInnerFixedAbi( ...
        numerics,state64,stateTags2,input36,inputTags2,pending70,pendingTags2,newLeg)
%#codegen
% Fixed-shape adapter for precontrol and postcontrol numerics.
% newLeg is compile-time constant in the generated entries.
% Tags are uint64 [original_timestamp_ns; original_source_generation]; other values are double.
% The returned postcontrol state is a candidate until the owner commits it.
% Complete the GP prediction in scaffold70 before the next innovation closure.
% input36: x13(1:13), lag6(14:19), reference p/v/a/j(20:31),
% payload(32), wind2(33:34), dt(35), leg(36).
% state64: robust27, attitude20, residual3, agreement3, causal1,
% previous rotor6, previous projected force3, leg1.
% pending70: prediction54, velocity3, nominal3, frame9, leg1.
% request19: required1, features17, mean_scale1.
% closed5 holds current precontrol evidence for gpenmpcCoordinatedOuterStep:
% available, closed, innovation, hard_invalid and trust.
assert(isequal(size(state64),[64,1])&&isequal(size(stateTags2),[2,1]) ...
    &&isequal(size(input36),[36,1])&&isequal(size(inputTags2),[2,1]) ...
    &&isequal(size(pending70),[70,1])&&isequal(size(pendingTags2),[2,1]));
input=struct('x13',input36(1:13),'rotor_thrust_state_n',input36(14:19), ...
    'reference_up',struct('position_m',input36(20:22),'velocity_mps',input36(23:25), ...
        'acceleration_mps2',input36(26:28),'jerk_mps3',input36(29:31)), ...
    'payload_kg',input36(32),'wind_estimate_xy_mps',input36(33:34), ...
    'dt_s',input36(35),'leg_index',input36(36),'source_timestamp_ns',inputTags2(1), ...
    'source_generation',inputTags2(2),'new_leg',newLeg);
if newLeg
    % Same original fresh-owner initializer, typed before entering precontrol.
    % The two fixed zero buffers replace only empty placeholders: precontrol's
    % explicit new-leg branch overwrites both before any numerical read.
    initial=struct('robust_state',gpenmpcInitializeRobustSe3State(), ...
        'attitude_continuity_state',gpenmpcInitializeDesiredAttitudeContinuityState(), ...
        'residual_history_f_mps2',zeros(3,1),'gp_agreement_weight_f',zeros(3,1), ...
        'previous_rotor_command_n',zeros(6,1),'previous_desired_force_projected_up_n',zeros(3,1), ...
        'causal_valid',false,'last_sample_timestamp_ns',uint64(0), ...
        'source_generation',uint64(0),'leg_index',NaN);
    [candidate,out]=gpenmpcNative.canonicalLocalInnerPreControl(initial,input,struct(),numerics,true);
else
    state=unpackState(state64,stateTags2);
    pending=unpackPending(pending70,pendingTags2);
    [candidate,out]=gpenmpcNative.canonicalLocalInnerPreControl(state,input,pending,numerics,false);
end
[next,scaffold,query,~]=gpenmpcNative.canonicalLocalInnerPostControl(candidate,out,numerics,true);
next64=packState(next);kernel61=out.kernel_output61;
scaffold.prediction=query.pending;
scaffold70=packPending(scaffold);
request19=[double(query.prediction_required);query.features_f17(:);query.gp_mean_scale];
e=out.closed_gp_evidence;
closed5=[double(e.available);double(e.prediction_sample_closed); ...
    double(e.observed_innovation_available);double(e.hard_invalid);double(e.trust)];
% Export current closed-prediction and execution diagnostics.
d=out.physical_diagnostic;
learning12=[double(e.observed_innovation_f_mps2(:)); ...
    double(d.gp_prediction_axis_authority_f(:));double(d.gp_physical_axis_authority_f(:)); ...
    double(d.exact_b1_fallback);double(d.gp_responsibility_blend);double(d.gp_trust)];
end

function s=unpackState(v,t)
r=gpenmpcInitializeRobustSe3State();
r.filtered_compensation_i_mps2=v(1:3);r.authority_scale=v(4);r.last_tangent_xy=v(5:6);
r.vertical_disturbance_ewma_mps2=v(7);r.vertical_observer_previous_velocity_z_mps=v(8);
r.vertical_observer_previous_nominal_acceleration_z_mps2=v(9);
r.vertical_observer_previous_time_s=v(10);r.vertical_observer_previous_leg_index=v(11);
r.vertical_observer_previous_payload_kg=v(12);r.vertical_observer_observation_valid=logical(v(13));
r.vertical_observer_update_enabled=logical(v(14));r.vertical_observer_reset_count=v(15);
r.vertical_observer_antiwindup_hold_count=v(16);r.responsibility_innovation_ratio_ewma_f=v(17:19);
r.gp_responsibility_mode_active=logical(v(20));r.gp_responsibility_enter_elapsed_s=v(21);
r.gp_responsibility_exit_elapsed_s=v(22);r.gp_responsibility_blend=v(23);
r.responsibility_filtered_gp_mean_f_mps2=v(24:26);r.gp_responsibility_mode_transition_count=v(27);
a=gpenmpcInitializeDesiredAttitudeContinuityState();
a.initialized=logical(v(28));a.angular_velocity_valid=logical(v(29));a.angular_acceleration_valid=logical(v(30));
a.filtered_rotation=reshape(v(31:39),3,3);a.desired_angular_velocity_body_rad_s=v(40:42);
a.desired_angular_acceleration_body_rad_s2=v(43:45);a.update_count=v(46);a.reset_count=v(47);
s=struct('robust_state',r,'attitude_continuity_state',a,'residual_history_f_mps2',v(48:50), ...
    'gp_agreement_weight_f',v(51:53),'causal_valid',logical(v(54)), ...
    'previous_rotor_command_n',v(55:60),'previous_desired_force_projected_up_n',v(61:63), ...
    'leg_index',v(64),'last_sample_timestamp_ns',t(1),'source_generation',t(2));
end
function v=packState(s)
r=s.robust_state;a=s.attitude_continuity_state;
v=[r.filtered_compensation_i_mps2;r.authority_scale;r.last_tangent_xy; ...
    r.vertical_disturbance_ewma_mps2;r.vertical_observer_previous_velocity_z_mps; ...
    r.vertical_observer_previous_nominal_acceleration_z_mps2;r.vertical_observer_previous_time_s; ...
    r.vertical_observer_previous_leg_index;r.vertical_observer_previous_payload_kg; ...
    double(r.vertical_observer_observation_valid);double(r.vertical_observer_update_enabled); ...
    r.vertical_observer_reset_count;r.vertical_observer_antiwindup_hold_count; ...
    r.responsibility_innovation_ratio_ewma_f;double(r.gp_responsibility_mode_active); ...
    r.gp_responsibility_enter_elapsed_s;r.gp_responsibility_exit_elapsed_s;r.gp_responsibility_blend; ...
    r.responsibility_filtered_gp_mean_f_mps2;r.gp_responsibility_mode_transition_count; ...
    double(a.initialized);double(a.angular_velocity_valid);double(a.angular_acceleration_valid); ...
    a.filtered_rotation(:);a.desired_angular_velocity_body_rad_s; ...
    a.desired_angular_acceleration_body_rad_s2;a.update_count;a.reset_count; ...
    s.residual_history_f_mps2;s.gp_agreement_weight_f;double(s.causal_valid); ...
    s.previous_rotor_command_n;s.previous_desired_force_projected_up_n;s.leg_index];
end
function p=unpackPending(v,t)
e=struct('schema',"GPENMPC_CURRENT_SAMPLE_GP_PREDICTION_V1", ...
    'read_only',logical(v(1)),'available',logical(v(2)),'causal_valid',logical(v(3)), ...
    'gp_model_available',logical(v(4)),'hard_invalid',logical(v(5)),'trust',v(6), ...
    'minimum_soft_trust',v(7),'support_distance',v(8),'latent_variance_max',v(9), ...
    'features_f17',v(10:26).','gp_frame_i_from_f',reshape(v(27:35),3,3), ...
    'predicted_mean_f_mps2',v(36:38).','runtime_weighted_mean_f_mps2',v(39:41).', ...
    'calibrated_half_width_f_mps2',v(42:44).','prediction_sample_closed',logical(v(45)), ...
    'observed_innovation_available',logical(v(46)),'observed_innovation_f_mps2',v(47:49).', ...
    'innovation_error_f_mps2',v(50:52).','observed_innovation_consistent',logical(v(53)), ...
    'eligible_for_b1_dwell',logical(v(54)), ...
    'normalized_innovation_error_f',nan(1,3),'innovation_consistency_score_f',nan(1,3), ...
    'observed_innovation_consistent_f',false(1,3));
% The close function writes the scratch fields only when evidence is available.
p=struct('prediction',e,'velocity_up_mps',v(55:57),'nominal_acceleration_up_mps2',v(58:60), ...
    'frame_i_from_f',reshape(v(61:69),3,3),'leg_index',v(70),'timestamp_ns',t(1),'generation',t(2));
end
function v=packPending(p)
e=p.prediction;
v=[double(e.read_only);double(e.available);double(e.causal_valid);double(e.gp_model_available); ...
    double(e.hard_invalid);e.trust;e.minimum_soft_trust;e.support_distance;e.latent_variance_max; ...
    e.features_f17(:);e.gp_frame_i_from_f(:);e.predicted_mean_f_mps2(:);e.runtime_weighted_mean_f_mps2(:); ...
    e.calibrated_half_width_f_mps2(:);double(e.prediction_sample_closed);double(e.observed_innovation_available); ...
    e.observed_innovation_f_mps2(:);e.innovation_error_f_mps2(:);double(e.observed_innovation_consistent); ...
    double(e.eligible_for_b1_dwell);p.velocity_up_mps;p.nominal_acceleration_up_mps2;p.frame_i_from_f(:);p.leg_index];
end
