function [controls16,enableOut,result,reason] = canonicalRotorToHIL16CtrlsNorm( ...
    rotorN,enableIn,calibration,interface)
% Encode allocated rotor thrust as single[16] HIL16CtrlsNorm input.
% The DLL maps controls([5;1;4;6;2;3])*upper.
% Motor thrust uses [0,1] within the interface's [-1,1] domain.
% enableOut indicates input admissibility; rejected values return zero and false.
% Suppressing publication does not clear a downstream held value.
controls16=zeros(16,1,'single');enableOut=false;
result=struct('schema','CANONICAL_M600_HIL16CTRLSNORM_PREVIEW_V1', ...
    'valid',false,'publication_allowed',false,'hardware_actions',0, ...
    'controller_or_allocator_recomputed',false,'helper_clipping_performed',false, ...
    'pwm_quantization_performed',false,'exact_arbitrary_real_output_equivalence',false, ...
    'firmware_route_or_single_publisher_verified',false, ...
    'disabled_output_is_disarm_or_last_value_clear',false, ...
    'scope','HOST_NUMERICAL_ENCODING');
reason="INVALID_ENABLE_INPUT";
if ~islogical(enableIn)||~isscalar(enableIn),return;end
if ~enableIn,reason="DISABLED_ZERO_OUTPUT";return;end
reason="INVALID_INTERFACE_CONTRACT";
fields={'schema','input_units','input_order','allocation_matrix', ...
    'per_rotor_upper_n','software_from_hil_one_based','hil_signal_units', ...
    'official_block_name','official_output_topic','inactive_channel_value'};
if ~isstruct(interface)||~isscalar(interface)||~all(isfield(interface,fields)) ...
        ||~isstruct(calibration)||~isscalar(calibration)||~isfield(calibration,'rotor_allocation')
    return
end
if ~sameText(interface.schema,"CANONICAL_M600_HIL16CTRLSNORM_INTERFACE_V1") ...
        ||~sameText(interface.input_units,"NEWTON") ...
        ||~sameText(interface.input_order,"CANONICAL_M600_ORDER") ...
        ||~sameText(interface.hil_signal_units,"LINEAR_NORMALIZED_THRUST") ...
        ||~sameText(interface.official_block_name,"HIL16CtrlsNorm") ...
        ||~sameText(interface.official_output_topic,"actuator_outputs_rfly") ...
        ||~finiteScalar(interface.inactive_channel_value)||interface.inactive_channel_value~=0
    reason="UNITS_ORDER_OR_OFFICIAL_BLOCK_CONTRACT_REJECTED";return
end
r=calibration.rotor_allocation;
rf={'angles_deg','spin_sign','arm_radius_m','yaw_moment_arm_nominal_m','per_rotor_thrust_upper_n'};
if ~isstruct(r)||~isscalar(r)||~all(isfield(r,rf)) ...
        ||~finiteVector(r.angles_deg,6)||~finiteVector(r.spin_sign,6) ...
        ||~isequal(double(r.angles_deg(:)),[0;60;120;180;240;300]) ...
        ||~isequal(double(r.spin_sign(:)),[1;-1;1;-1;1;-1]) ...
        ||~finiteScalar(r.arm_radius_m)||r.arm_radius_m~=0.5665 ...
        ||~finiteScalar(r.yaw_moment_arm_nominal_m)||r.yaw_moment_arm_nominal_m~=0.025 ...
        ||~finiteScalar(r.per_rotor_thrust_upper_n)||r.per_rotor_thrust_upper_n~=32.145727009134916
    reason="NONCANONICAL_GEOMETRY_OR_LIMIT";return
end
upper=double(r.per_rotor_thrust_upper_n);angles=deg2rad(double(r.angles_deg(:)));
A=[ones(1,6);double(r.arm_radius_m).*sin(angles).'; ...
    -double(r.arm_radius_m).*cos(angles).'; ...
    double(r.yaw_moment_arm_nominal_m).*double(r.spin_sign(:)).'];
if ~isnumeric(interface.allocation_matrix)||~isreal(interface.allocation_matrix) ...
        ||~isequal(size(interface.allocation_matrix),[4,6]) ...
        ||any(~isfinite(interface.allocation_matrix),'all') ...
        ||max(abs(double(interface.allocation_matrix)-A),[],'all')>1e-14 ...
        ||~finiteScalar(interface.per_rotor_upper_n)||interface.per_rotor_upper_n~=upper ...
        ||~finiteVector(interface.software_from_hil_one_based,6) ...
        ||~isequal(double(interface.software_from_hil_one_based(:)),[5;1;4;6;2;3])
    reason="ALLOCATION_OR_CONSUMER_PERMUTATION_IDENTITY_REJECTED";return
end
% Reject in the ORIGINAL precision, before conversion to single. An invalid
% value just above upper or below zero must not become valid by rounding.
if ~(isa(rotorN,'double')||isa(rotorN,'single'))||~finiteVector(rotorN,6) ...
        ||any(double(rotorN(:))<0)||any(double(rotorN(:))>upper)
    reason="ROTOR_INPUT_NOT_FINITE_PRECLIPPED_NEWTON";return
end
rotorN=double(rotorN(:));map=double(interface.software_from_hil_one_based(:));
controls16(map)=single(rotorN/upper);
decoded=double(controls16(map))*upper;
result.valid=true;
result.input_rotor_newton=rotorN;
result.software_from_hil_one_based=map;
result.expected_linear_host_decoded_rotor_newton=decoded;
result.signed_float32_quantization_error_newton=decoded-rotorN;
result.maximum_absolute_error_newton=max(abs(decoded-rotorN));
% In [0,1], the largest float32 spacing BELOW 1 is 2^-24. Half is 2^-25.
% The extra guard bounds the double division and multiplication.
result.float32_half_step_bound_newton=upper*2^-25;
result.float64_arithmetic_guard_newton=2*eps(upper);
result.requested_allocated_wrench_txyz=A*rotorN;
result.expected_single_decoded_wrench_txyz=A*decoded;
enableOut=true;reason="PASS_HOST_ENCODING_WITH_DISCLOSED_FLOAT32_QUANTIZATION";
end

function ok=finiteScalar(v)
ok=isnumeric(v)&&isreal(v)&&isscalar(v)&&isfinite(v);
end
function ok=finiteVector(v,n)
ok=isnumeric(v)&&isreal(v)&&isvector(v)&&numel(v)==n&&all(isfinite(v(:)));
end
function ok=sameText(v,t)
ok=(isstring(v)&&isscalar(v)||ischar(v)&&isrow(v))&&string(v)==t;
end
