function [nextState,pendingScaffold,gpRequest,receipt] = ...
        canonicalLocalInnerPostControl(candidate,precontrol,numerics,gpModelAvailable)
% CANONICALLOCALINNERPOSTCONTROL Compute post-commit numerical updates.
% The owner installs the result only after successful output commit.
% Use the previous rotor command and current projected force for the GP request.
% pendingScaffold lacks a prediction until completeCanonical... returns.
arguments
    candidate (1,1) struct
    precontrol (1,1) struct
    numerics (1,1) struct
    gpModelAvailable (1,1) logical
end
stateFields={'robust_state','residual_history_f_mps2','gp_agreement_weight_f', ...
    'attitude_continuity_state','causal_valid','previous_rotor_command_n', ...
    'previous_desired_force_projected_up_n','last_sample_timestamp_ns', ...
    'source_generation','leg_index'};
assert(gpenmpcNative.hasCanonicalFields(candidate,stateFields)&&gpenmpcNative.hasCanonicalFields(precontrol, ...
    {'input','source_timestamp_ns','source_generation','kernel_control_candidate', ...
    'candidate_only','board_publication_authority'}) ...
    &&isequal(precontrol.candidate_only,true) ...
    &&isequal(precontrol.board_publication_authority,false), ...
    'gpenmpcNative:LocalPostControlInput','A pure canonical numerical candidate is required.');
i=precontrol.input;c=precontrol.kernel_control_candidate;
assert(gpenmpcNative.hasCanonicalFields(numerics,{'calibration','profile','prediction_context','enmpc'}) ...
    &&gpenmpcNative.hasCanonicalFields(i,{'x13','rotor_thrust_state_n','wind_estimate_xy_mps','payload_kg', ...
        'reference_up','source_timestamp_ns','source_generation','leg_index','dt_s'}), ...
    'gpenmpcNative:LocalPostControlInput','Original sample and exact numerical configuration required.');
assert(isequal(candidate.last_sample_timestamp_ns,i.source_timestamp_ns) ...
    &&isequal(precontrol.source_timestamp_ns,i.source_timestamp_ns) ...
    &&isequal(candidate.source_generation,i.source_generation) ...
    &&isequal(precontrol.source_generation,i.source_generation) ...
    &&isequal(candidate.leg_index,i.leg_index), ...
    'gpenmpcNative:LocalPostControlSource','Candidate and original observation must match.');
assert(gpenmpcNative.hasCanonicalFields(c,{'desired_force_projected_up_n','rotor_command_n', ...
    'rotor_saturated','force_projection_norm_mismatch_n'}) ...
    &&finiteVector(c.desired_force_projected_up_n,3) ...
    &&finiteVector(c.rotor_command_n,6)&&all(c.rotor_command_n>=0) ...
    &&islogical(c.rotor_saturated)&&isscalar(c.rotor_saturated) ...
    &&finiteScalar(c.force_projection_norm_mismatch_n) ...
    &&finiteScalar(i.dt_s)&&i.dt_s>0&&i.dt_s<=.0200001 ...
    &&finiteVector(i.x13,13)&&finiteVector(i.rotor_thrust_state_n,6), ...
    'gpenmpcNative:LocalPostControlNumerics','Original finite control/observed rotor values required.');
nextState=candidate;
nextState.robust_state=gpenmpcRobustSe3ObserveControl( ...
    candidate.robust_state,c,double(i.dt_s));
x19=[double(i.x13(:));double(i.rotor_thrust_state_n(:))];
nominal=gpenmpcKnownNominalAccelerationFromObservation(x19, ...
    i.wind_estimate_xy_mps,i.payload_kg,numerics.calibration,numerics.profile);
nextState.robust_state=gpenmpcCommitCausalVerticalDisturbanceObserver( ...
    nextState.robust_state,i.x13(4:6),nominal, ...
    double(i.source_timestamp_ns)*1.0e-9,i.leg_index,i.payload_kg);
gpRequest=gpenmpcNative.prepareCanonicalCurrentGpPrediction( ...
    i.x13(4:6),i.reference_up,i.wind_estimate_xy_mps,i.payload_kg, ...
    c.desired_force_projected_up_n,candidate.previous_rotor_command_n, ...
    candidate.residual_history_f_mps2,numerics.prediction_context, ...
    gpModelAvailable,logical(candidate.causal_valid),numerics.enmpc);
pendingScaffold=struct('velocity_up_mps',i.x13(4:6), ...
    'nominal_acceleration_up_mps2',nominal, ...
    'frame_i_from_f',double(gpRequest.pending.gp_frame_i_from_f), ...
    'generation',i.source_generation,'timestamp_ns',i.source_timestamp_ns, ...
    'leg_index',i.leg_index);
nextState.previous_rotor_command_n=c.rotor_command_n;
nextState.previous_desired_force_projected_up_n= ...
    double(c.desired_force_projected_up_n(:));
receipt=struct('schema','CANONICAL_LOCAL_POSTCONTROL_NUMERICAL_RESULT_V1', ...
    'original_source_generation',i.source_generation, ...
    'original_source_timestamp_ns',i.source_timestamp_ns, ...
    'previous_rotor_command_n_for_prediction',candidate.previous_rotor_command_n, ...
    'current_rotor_command_n',c.rotor_command_n, ...
    'nominal_acceleration_up_mps2',nominal,'gp_prediction_required',gpRequest.prediction_required, ...
    'gp_prediction_executed',false,'innovation_closed_early',false, ...
    'board_consumption_proven',false,'publication_count',0,'hardware_actions',0);
end
function yes=finiteScalar(x)
yes=isnumeric(x)&&isreal(x)&&isscalar(x)&&isfinite(x);
end
function yes=finiteVector(x,n)
yes=isnumeric(x)&&isreal(x)&&isvector(x)&&numel(x)==n&&all(isfinite(x(:)));
end
