function [association,accepted,reason]=correlateActuatorAfterReference( ...
        actuator,reference,clock,expected,nowNs)
% Correlate HIL93 by conservative timestamp ordering.
% HIL93 does not echo reference consumption; retain its packet generation
% and store association generation separately.
association=struct();accepted=false;reason="INVALID_ASSOCIATION_INPUT";
if ~record(actuator,{'uid','boot_generation','src_system','src_component', ...
        'message_id','generation','source_generation','time_usec','source_time_ns','rx_ns'}) ...
        ||~record(reference,{'host_send_begin_ns','host_send_return_ns', ...
        'send_returned','inner_generation','boot_generation'}) ...
        ||~record(clock,{'clock_valid','sync_locked','fixed_best_timesync'}) ...
        ||~record(expected,{'uid','boot_generation','system_id','component_id','maximum_runtime_age_ns'}) ...
        ||~integer(nowNs)
    return
end
if ~trueScalar(reference.send_returned)||~integer(reference.inner_generation) ...
        ||reference.inner_generation<1||~integer(reference.host_send_begin_ns) ...
        ||~integer(reference.host_send_return_ns) ...
        ||reference.host_send_begin_ns>reference.host_send_return_ns ...
        ||reference.host_send_return_ns>nowNs
    reason="REFERENCE_SEND_NOT_CONFIRMED";return
end
if ~textScalar(actuator.uid)||~textScalar(expected.uid) ...
        ||~integer(actuator.boot_generation)||~integer(expected.boot_generation) ...
        ||~integer(reference.boot_generation)||~integer(actuator.src_system) ...
        ||~integer(actuator.src_component)||~integer(expected.system_id) ...
        ||~integer(expected.component_id)||~integer(actuator.message_id) ...
        ||string(actuator.uid)~=string(expected.uid) ...
        ||actuator.boot_generation~=expected.boot_generation ...
        ||reference.boot_generation~=expected.boot_generation ...
        ||actuator.src_system~=expected.system_id||actuator.src_component~=expected.component_id ...
        ||actuator.message_id~=93
    reason="ACTUATOR_SOURCE_OR_BOOT_MISMATCH";return
end
if ~integer(actuator.generation)||actuator.generation<1 ...
        ||~integer(actuator.source_generation)||actuator.source_generation~=actuator.generation ...
        ||~integer(actuator.time_usec)||actuator.time_usec<1 ...
        ||~integer(actuator.source_time_ns)||actuator.source_time_ns~=double(actuator.time_usec)*1000 ...
        ||~integer(actuator.rx_ns)||actuator.rx_ns>nowNs ...
        ||~scalar(expected.maximum_runtime_age_ns)||expected.maximum_runtime_age_ns<=0 ...
        ||nowNs-actuator.rx_ns>expected.maximum_runtime_age_ns
    reason="ACTUATOR_TIMESTAMP_OR_ORIGINAL_GENERATION_INVALID";return
end
b=clock.fixed_best_timesync;
if ~trueScalar(clock.clock_valid)||~trueScalar(clock.sync_locked) ...
        ||~record(b,{'offset_lower_s','offset_upper_s'}) ...
        ||~scalar(b.offset_lower_s)||~scalar(b.offset_upper_s) ...
        ||b.offset_lower_s>b.offset_upper_s
    reason="SOURCE_CLOCK_MAPPING_NOT_VALID";return
end
sourceBounds=double(actuator.source_time_ns)+1e9*[b.offset_lower_s,b.offset_upper_s];
if sourceBounds(1)<=reference.host_send_return_ns
    reason="SOURCE_TIME_NOT_PROVEN_AFTER_REFERENCE_SEND";return
end
if sourceBounds(2)>double(actuator.rx_ns)
    reason="SOURCE_TIME_INTERVAL_NOT_BEFORE_RECEIVE";return
end
association=struct('schema','V7_ACTUATOR_TEMPORAL_ASSOCIATION_ONLY_V1', ...
    'inner_association_generation',double(reference.inner_generation), ...
    'actuator_source_generation',actuator.source_generation, ...
    'original_actuator',actuator,'reference_send',reference, ...
    'actuator_host_time_bounds_ns',sourceBounds, ...
    'temporal_order_proven',true,'reference_consumption_proven',false, ...
    'same_estimate_sample_proven',false,'raw_generation_rewritten',false, ...
    'claim','TEMPORALLY_LATER_ACTUATOR', ...
    'hardware_actions',0);
accepted=true;reason="TEMPORAL_ORDER_ONLY__NO_REFERENCE_ECHO";
end
function yes=record(x,names)
yes=isstruct(x)&&isscalar(x)&&all(isfield(x,names));
end
function yes=scalar(x)
yes=isnumeric(x)&&isreal(x)&&isscalar(x)&&isfinite(x);
end
function yes=integer(x)
yes=scalar(x)&&x>=0&&x==fix(x)&&x<=flintmax;
end
function yes=trueScalar(x)
yes=islogical(x)&&isscalar(x)&&x;
end
function yes=textScalar(x)
yes=(ischar(x)&&isrow(x))||(isstring(x)&&isscalar(x)&&~ismissing(x));
end
