classdef CurrentPhysicalCausalRuntime < handle
    % Maintain causal physical-compensation state through a two-phase transaction.
    % beginSample closes the preceding interval from a fresh estimate;
    % commitControl binds the controller output before the next estimate.
    properties (SetAccess=private)
        Failed = false
        FailureCode = ""
        LastGeneration = uint64(0)
        BeginCount = uint64(0)
        ControlCommitCount = uint64(0)
        LegResetCount = uint64(0)
        ClosedEvidenceCount = uint64(0)
        AvailableEvidenceCount = uint64(0)
        HardwareActions = 0
    end
    properties (Access=private)
        WorkRoot
        Expected
        Assets
        TaskIdentitySha256
        PhysicalAdapterState
        ResidualHistoryF = zeros(3,1)
        CausalValid = false
        AgreementF = zeros(3,1)
        LatestEvidence
        Pending = struct()
        HasPending = false
        OpenSample = struct()
        SampleOpen = false
        PreviousRotorCommandN = []
        PreviousDesiredForceProjectedN = []
        DesiredForceGeneration = uint64(0)
        DesiredForceSource = "CANONICAL_LEG_INITIAL_FORCE"
        CurrentLeg = NaN
        AuthorizedNextLeg = 1
        AuthorizedPayloadKg
        LastSampleTimestampNs = uint64(0)
        LastOdometryResetCounter = NaN
        LastEstimateGenerations = zeros(1,3)
        LastVirtualActuatorGeneration = 0
        LastWindGeneration = 0
        V7Binding
        FullInner = false
        BoardCommit = false
        BoardCommitConsumer = []
        AttitudeContinuityState
        FullInnerCommittedCount = uint64(0)
    end
    methods
        function obj = CurrentPhysicalCausalRuntime(workRoot,expected,taskSha,verifiedAssets)
            obj.WorkRoot = string(workRoot);
            obj.Expected = expected;
            if isfield(expected,'initial_leg_index')
                v=expected.initial_leg_index;
                assert(isnumeric(v)&&isreal(v)&&isscalar(v)&&isfinite(v) ...
                    &&v>=1&&v==fix(v)&&v<=double(intmax('int32')), ...
                    'gpenmpcNative:CanonicalInitialLeg','Explicit positive global task leg required.');
                obj.AuthorizedNextLeg=double(v);
            end
            if nargin < 4
                assert(isfield(expected,'canonical_package_root'), ...
                    'gpenmpcNative:CanonicalPackageRequired', ...
                    'The current execution requires the canonical E-drive package.');
                verifiedAssets = gpenmpcNative.loadCanonicalAssets( ...
                    string(expected.canonical_package_root));
            end
            obj.Assets = verifiedAssets;
            obj.AuthorizedPayloadKg=double(expected.initial_payload_kg);
            obj.TaskIdentitySha256 = upper(string(taskSha));
            assert(obj.isSha256(obj.TaskIdentitySha256), ...
                'gpenmpcNative:PhysicalCausalTaskIdentity', ...
                'A valid frozen task SHA-256 is required.');
            required = {'uid','system_id','component_id','boot_generation', ...
                'maximum_age_ns','maximum_runtime_age_ns'};
            assert(isstruct(expected) && isscalar(expected) ...
                && all(isfield(expected,required)) ...
                && obj.finiteScalar(expected.maximum_age_ns) ...
                && obj.finiteScalar(expected.maximum_runtime_age_ns) ...
                && expected.maximum_age_ns>0 ...
                && expected.maximum_runtime_age_ns>0, ...
                'gpenmpcNative:PhysicalCausalExpectedBoundary', ...
                'Explicit estimate and runtime boundaries are required.');
            obj.PhysicalAdapterState = ...
                gpenmpcNative.initializeCoordinatedPhysicalAdapter( ...
                    obj.Assets.enmpc,obj.TaskIdentitySha256);
            obj.V7Binding = gpenmpcNative.v7NominalControllerBinding();
            if isfield(expected,'inner_control_contract')
                contract=string(expected.inner_control_contract);
                assert(isscalar(contract)&&any(contract==[ ...
                    "LEGACY_V7_NOMINAL","CANONICAL_FULL_SE3"]), ...
                    'gpenmpcNative:InnerControlContract','Unknown inner control contract.');
                obj.FullInner=contract=="CANONICAL_FULL_SE3";
            end
            if obj.FullInner
                assert(isfield(expected,'full_inner_evidence_scope') ...
                    &&any(string(expected.full_inner_evidence_scope)==["HOST_ONLY_KERNEL_EXECUTION","BOARD_COMMIT_RFC1"]), ...
                    'gpenmpcNative:FullInnerDeploymentNotBound', ...
                    'Explicit HOST or registered-session RFC1 consumer contract required.');
                obj.BoardCommit=string(expected.full_inner_evidence_scope)=="BOARD_COMMIT_RFC1";
                if obj.BoardCommit
                    obj.BoardCommitConsumer=gpenmpcNative.RflyBoardCommitConsumer(expected,taskSha,obj.Assets);
                end
                assert(obj.Assets.attitudeContinuity.enabled ...
                    &&strcmpi(gpenmpcNative.fileSha256(which('gpenmpcNative.se3WrenchKernel')), ...
                    '52F714D65C4A3CD5879FFD4478F60379F68CD5F65A38F5971B91BBC01D0E4AB8'), ...
                    'gpenmpcNative:FullInnerKernelIdentity','Canonical continuity/kernel required.');
                obj.AttitudeContinuityState=gpenmpcInitializeDesiredAttitudeContinuityState();
            end
            obj.LatestEvidence = obj.emptyExecutionEvidence();
        end

        function output = beginSample(obj,generation,nowNs,px4Sample, ...
                runtime,baseReferenceUp,dtS)
            output = obj.rejected('UNPROCESSED');
            if obj.Failed
                output = obj.rejected('HARD_INVALID_ALREADY_LATCHED');
                return
            end
            if obj.SampleOpen
                output = obj.latchAndReject('PREVIOUS_SAMPLE_CONTROL_NOT_COMMITTED');
                return
            end
            generationOk=obj.finiteInteger(generation)&&uint64(generation)==obj.LastGeneration+uint64(1);
            if obj.BoardCommit
                generationOk=isa(generation,'uint64')&&isscalar(generation)&&generation>obj.LastGeneration ...
                    &&isfield(px4Sample,'position_generation')&&generation==uint64(px4Sample.position_generation);
            end
            if ~generationOk ...
                    || ~obj.finiteInteger(nowNs) ...
                    || ~obj.finiteScalar(dtS) || dtS<=0 || dtS>0.0100001
                output = obj.latchAndReject('GENERATION_TIMESTAMP_OR_DT_REJECTED');
                return
            end
            [x13,accepted,reason] = gpenmpcNative.px4EstimateState( ...
                px4Sample,obj.Expected,double(nowNs));
            if ~accepted
                output = obj.latchAndReject("PX4_ESTIMATE_REJECTED__"+string(reason));
                return
            end
            resetField='odometry_reset_counter';approvedSource="PX4_EKF2_MAVLINK_ODOMETRY_331";
            if obj.BoardCommit,resetField='reset_counter';approvedSource="PX4_PRIVATE_VEHICLE_ODOMETRY_RSP1";end
            atomicFields={'atomic_estimate','plant_truth_used','sample_timestamp_ns',resetField};
            if string(px4Sample.source)~=approvedSource ...
                    || ~all(isfield(px4Sample,atomicFields)) ...
                    || ~(islogical(px4Sample.atomic_estimate) ...
                        && isscalar(px4Sample.atomic_estimate) ...
                        && px4Sample.atomic_estimate) ...
                    || ~(islogical(px4Sample.plant_truth_used) ...
                        && isscalar(px4Sample.plant_truth_used) ...
                        && ~px4Sample.plant_truth_used) ...
                    || ~obj.finiteInteger(px4Sample.sample_timestamp_ns) ...
                    || px4Sample.sample_timestamp_ns<1 ...
                    || ~obj.finiteInteger(px4Sample.(resetField))
                output=obj.latchAndReject('ATOMIC_ODOMETRY_REQUIRED');
                return
            end
            sampleTimestampNs=uint64(px4Sample.sample_timestamp_ns);
            estimateGenerations = [double(px4Sample.position_generation), ...
                double(px4Sample.attitude_generation), ...
                double(px4Sample.rates_generation)];
            if any(estimateGenerations<=obj.LastEstimateGenerations) ...
                    || numel(unique(estimateGenerations))~=1
                output = obj.latchAndReject( ...
                    'NONADVANCING_OR_NONATOMIC_PX4_ESTIMATE_GENERATION');
                return
            end
            resetCounter=double(px4Sample.(resetField));
            if ~isnan(obj.LastOdometryResetCounter) ...
                    && resetCounter~=obj.LastOdometryResetCounter
                output=obj.latchAndReject('PX4_ODOMETRY_RESET_COUNTER_CHANGED');
                return
            end
            [runtimeOk,runtimeReason,context] = ...
                obj.validateRuntime(runtime,double(nowNs));
            if ~runtimeOk
                output = obj.latchAndReject(runtimeReason);
                return
            end
            if ~obj.validReference(baseReferenceUp)
                output = obj.latchAndReject('INVALID_BASE_REFERENCE');
                return
            end

            newLeg = isnan(obj.CurrentLeg) || context.leg_index~=obj.CurrentLeg;
            if newLeg
                if context.leg_index~=obj.AuthorizedNextLeg ...
                        ||context.payload_kg~=obj.AuthorizedPayloadKg
                    output=obj.latchAndReject('LEG_TRANSITION_NOT_PREPARED');
                    return
                end
                if ~isnan(obj.CurrentLeg) ...
                        && context.leg_index~=obj.CurrentLeg+1
                    output = obj.latchAndReject('NONSEQUENTIAL_LEG_IDENTITY');
                    return
                end
                obj.CurrentLeg = context.leg_index;
                obj.AuthorizedNextLeg=NaN;
                obj.ResidualHistoryF = zeros(3,1);
                obj.CausalValid = false;
                obj.AgreementF = zeros(3,1);
                obj.LatestEvidence = obj.emptyExecutionEvidence();
                obj.HasPending = false;
                obj.PreviousRotorCommandN = context.rotor_thrust_state_n;
                obj.PreviousDesiredForceProjectedN = ...
                    (double(obj.Assets.profile.mass_properties.base_mass_kg) ...
                    +context.payload_kg)*[0;0;9.80665];
                obj.DesiredForceGeneration = uint64(0);
                obj.DesiredForceSource = "CANONICAL_LEG_INITIAL_FORCE";
                obj.PhysicalAdapterState.robust_state = ...
                    gpenmpcResetCausalVerticalDisturbanceObserver( ...
                        obj.PhysicalAdapterState.robust_state,x13(4:6), ...
                        double(sampleTimestampNs)*1.0e-9,context.leg_index, ...
                        context.payload_kg);
                obj.LegResetCount = obj.LegResetCount+uint64(1);
            else
                if ~obj.HasPending || obj.LastSampleTimestampNs==0
                    output = obj.latchAndReject( ...
                        'MISSING_PREVIOUS_CAUSAL_CONTROL_COMMIT');
                    return
                end
                intervalS = (double(sampleTimestampNs) ...
                    -double(obj.LastSampleTimestampNs))*1.0e-9;
                if ~isfinite(intervalS) || intervalS<=1.0e-9 ...
                        || intervalS>0.0100001 ...
                        || abs(intervalS-double(dtS))>5.0e-7
                    output = obj.latchAndReject('CAUSAL_INTERVAL_REJECTED');
                    return
                end
                [obj.ResidualHistoryF,residualF,labelValid] = ...
                    gpenmpcAdvanceCausalResidualHistory( ...
                        obj.ResidualHistoryF,obj.Pending.velocity_up_mps, ...
                        x13(4:6),obj.Pending.nominal_acceleration_up_mps2, ...
                        obj.Pending.frame_i_from_f,intervalS,true,0.50);
                observedI = obj.Pending.frame_i_from_f*residualF;
                closed = gpenmpcCloseGpInnovationEvidence( ...
                    obj.Pending.prediction,observedI, ...
                    logical(labelValid)&&all(isfinite(observedI)), ...
                    obj.Assets.enmpc);
                [obj.AgreementF,consistency] = ...
                    gpenmpcUpdateGpAgreementWeight( ...
                        obj.AgreementF,closed,intervalS,obj.Assets.enmpc);
                obj.LatestEvidence = ...
                    obj.attachConsistency(closed,consistency);
                obj.CausalValid = logical(labelValid) ...
                    && all(isfinite(obj.ResidualHistoryF));
                obj.ClosedEvidenceCount = obj.ClosedEvidenceCount+uint64(1);
                obj.AvailableEvidenceCount = obj.AvailableEvidenceCount ...
                    + uint64(logical(obj.LatestEvidence.available));
            end

            [obj.PhysicalAdapterState.robust_state,observerDiagnostic] = ...
                gpenmpcObserveCausalVerticalDisturbance( ...
                    obj.PhysicalAdapterState.robust_state,x13(4:6), ...
                    double(sampleTimestampNs)*1.0e-9,context.leg_index, ...
                    context.payload_kg,obj.Assets.robust);
            executionEvidence = obj.executionEvidence(obj.LatestEvidence);
            physicalInput = struct( ...
                'schema',"GPENMPC_COORDINATED_PHYSICAL_INPUT_V1", ...
                'method_identity',"A1_COORDINATED_PHYSICAL", ...
                'configuration_payload_sha256', ...
                    obj.PhysicalAdapterState.configuration_payload_sha256, ...
                'task_identity_sha256',obj.TaskIdentitySha256, ...
                'estimate_source',"PX4_EKF2_MAVLINK_ODOMETRY_331", ...
                'plant_truth_used',false,'generation',double(generation), ...
                'sample_timestamp_ns',double(sampleTimestampNs), ...
                'host_receive_timestamp_ns',double(nowNs), ...
                'dt_s',double(dtS), ...
                'estimate_state_up',x13, ...
                'reference_up',struct( ...
                    'position_m',double(baseReferenceUp.position_m(:)), ...
                    'velocity_mps',double(baseReferenceUp.velocity_mps(:))), ...
                'gp_evidence',executionEvidence, ...
                'gp_agreement_weight_f',obj.AgreementF);
            if obj.BoardCommit
                physicalInput.estimate_source="PX4_PRIVATE_VEHICLE_ODOMETRY_RSP1";
                physicalInput.generation=double(obj.BeginCount+uint64(1));
                physicalInput.private_source_generation=uint64(generation);
                physicalInput.source_ticket=px4Sample.source_ticket;
                [obj.PhysicalAdapterState,physical]=gpenmpcNative.stepCoordinatedPhysicalAdapterBoard( ...
                    obj.PhysicalAdapterState,physicalInput,obj.Assets.robust,obj.Assets.enmpc);
            else
                [obj.PhysicalAdapterState,physical] = ...
                    gpenmpcNative.stepCoordinatedPhysicalAdapter( ...
                        obj.PhysicalAdapterState,physicalInput, ...
                        obj.Assets.robust,obj.Assets.enmpc);
            end
            transform = diag([1,1,-1]);
            composed = gpenmpcNative.composePhysicalCompensationReferenceNed( ...
                transform*double(baseReferenceUp.acceleration_mps2(:)), ...
                physical,obj.Assets.robust);
            if ~physical.accepted || ~composed.accepted
                output = obj.latchAndReject( ...
                    'PHYSICAL_COMPENSATION_OR_COMPOSITION_REJECTED');
                return
            end

            fullInnerCommand=struct();
            if obj.FullInner
                % Use the ORIGINAL reference and exactly one augmentation.
                % Feeding composed acceleration here would double-apply GP
                % and robust compensation, a different control law.
                try
                    extra={};
                    if obj.BoardCommit
                        extra={struct('source_generation',uint64(px4Sample.position_generation), ...
                            'source_ticket',px4Sample.source_ticket, ...
                            'execution_session_sha256',obj.Expected.rfly_board_commit.execution_session_sha256)};
                    end
                    [fullInnerCommand,nextAttitude]=gpenmpcNative.prepareCanonicalFullInnerCommand( ...
                        x13,baseReferenceUp,context.payload_kg,context.wind_estimate_xy_mps, ...
                        physical.compensation_up_mps2,obj.AttitudeContinuityState, ...
                        double(dtS),newLeg,obj.Assets,uint64(generation), ...
                        sampleTimestampNs,obj.TaskIdentitySha256,extra{:});
                    obj.AttitudeContinuityState=nextAttitude;
                catch ex
                    output=obj.latchAndReject("FULL_INNER_COMMAND__"+string(ex.identifier));
                    return
                end
            end

            obj.OpenSample = struct( ...
                'generation',uint64(generation), ...
                'timestamp_ns',sampleTimestampNs, ...
                'host_begin_ns',uint64(nowNs),'dt_s',double(dtS), ...
                'x13',x13,'reference_up',baseReferenceUp, ...
                'reference_ned',struct( ...
                    'position_ned_m',transform*double(baseReferenceUp.position_m(:)), ...
                    'velocity_ned_mps',transform*double(baseReferenceUp.velocity_mps(:)), ...
                    'acceleration_ned_mps2',composed.acceleration_ned_mps2), ...
                'wind_estimate_xy_mps',context.wind_estimate_xy_mps, ...
                'payload_kg',context.payload_kg, ...
                'leg_index',context.leg_index, ...
                'rotor_thrust_state_n',context.rotor_thrust_state_n);
            obj.OpenSample.full_inner_command=fullInnerCommand;
            if obj.BoardCommit,obj.OpenSample.private_source_sample=px4Sample;end
            obj.SampleOpen = true;
            obj.LastGeneration = uint64(generation);
            obj.LastSampleTimestampNs = sampleTimestampNs;
            obj.LastOdometryResetCounter = resetCounter;
            obj.LastEstimateGenerations = estimateGenerations;
            obj.LastVirtualActuatorGeneration = ...
                context.virtual_actuator_generation;
            obj.LastWindGeneration = context.wind_generation;
            obj.BeginCount = obj.BeginCount+uint64(1);
            output = struct( ...
                'schema',"GPENMPC_PHYSICAL_CAUSAL_REFERENCE_V1", ...
                'accepted',true,'publication_allowed',true, ...
                'reason',"FRESH_CAUSAL_SINGLE_PUBLISHER_REFERENCE", ...
                'generation',double(generation), ...
                'estimate_sample_timestamp_ns',double(sampleTimestampNs), ...
                'host_receive_timestamp_ns',double(nowNs), ...
                'reference_up',baseReferenceUp, ...
                'reference_ned',struct( ...
                    'position_ned_m',transform*double(baseReferenceUp.position_m(:)), ...
                    'velocity_ned_mps',transform*double(baseReferenceUp.velocity_mps(:)), ...
                    'acceleration_ned_mps2',composed.acceleration_ned_mps2, ...
                    'jerk_ned_mps3',transform*double(baseReferenceUp.jerk_mps3(:))), ...
                'physical_output',physical,'composition',composed, ...
                'closed_gp_evidence',obj.LatestEvidence, ...
                'gp_agreement_weight_f',obj.AgreementF, ...
                'causal_valid',obj.CausalValid, ...
                'residual_history_f_mps2',obj.ResidualHistoryF, ...
                'vertical_observer',observerDiagnostic, ...
                'compute_partition', ...
                    "HOST_A1_AUGMENTATION__BOARD_NOMINAL_POSITION_CONTROL", ...
                'board_control_mode', ...
                    "RA_CTRL_MODE_NOMINAL_SINGLE_PUBLISHER", ...
                'control_commit_required_before_next_sample',true, ...
                'plant_truth_used',false,'hardware_actions',0);
            if obj.FullInner
                output.full_inner_command=fullInnerCommand;
                output.publication_allowed=false;
                output.host_kernel_execution_allowed=true;
                output.compute_partition="HOST_CANONICAL_A1_AND_CONTINUITY__FULL_SE3_KERNEL_INPUT";
                output.board_control_mode="NOT_DEPLOYED_HOST_ONLY_FULL_KERNEL";
                output.reference_ned_publication_allowed=false;
                output.board_publication_authority=false;
                output.final_hil_admission=false;
                if obj.BoardCommit
                    output.host_kernel_execution_allowed=false;
                    output.board_commit_input_prepared=true;
                    output.board_control_mode="BOARD_COMMIT_RFC1_PENDING_REGISTERED_ROUTE";
                    output.live_registration_proven=false;
                end
            end
        end

        function receipt=recordBoardCommandSubmission(obj,generation,association,originalSubmitNs)
            assert(obj.BoardCommit&&obj.SampleOpen&&~obj.Failed ...
                &&isequal(generation,obj.OpenSample.generation) ...
                &&isa(originalSubmitNs,'uint64')&&originalSubmitNs>=obj.OpenSample.host_begin_ns, ...
                'gpenmpcNative:BoardCommitSubmission','Original open board command and submit event required.');
            try
                receipt=obj.BoardCommitConsumer.submitted(obj.OpenSample.full_inner_command, ...
                    obj.OpenSample.private_source_sample,association,originalSubmitNs);
            catch ex
                obj.latch("BOARD_COMMIT_SUBMIT__"+string(ex.identifier));rethrow(ex);
            end
        end

        function receipt = commitControl(obj,generation,nowNs,feedback)
            receipt = obj.commitRejected('UNPROCESSED');
            if obj.Failed
                receipt = obj.commitRejected('HARD_INVALID_ALREADY_LATCHED');
                return
            end
            if ~obj.SampleOpen || ~obj.finiteInteger(generation) ...
                    || uint64(generation)~=obj.OpenSample.generation ...
                    || ~obj.finiteInteger(nowNs)
                obj.latch('CONTROL_COMMIT_SEQUENCE_REJECTED');
                receipt = obj.commitRejected(obj.FailureCode);
                return
            end
            if obj.FullInner
                boardReceipt=struct();
                if obj.BoardCommit
                    [valid,reason,control,boardReceipt]=obj.BoardCommitConsumer.consume(feedback,nowNs);
                else
                    [valid,reason,control]=gpenmpcNative.validateCanonicalFullInnerFeedback( ...
                        feedback,obj.OpenSample.full_inner_command,obj.Assets, ...
                        double(nowNs),double(obj.OpenSample.host_begin_ns), ...
                        double(obj.Expected.maximum_runtime_age_ns));
                end
                if valid
                    control.previous_rotor_command_n_for_prediction= ...
                        double(obj.PreviousRotorCommandN(:));
                end
            else
                [valid,reason,control] = obj.validateControlFeedback( ...
                    feedback,double(nowNs),double(generation));
            end
            if ~valid
                obj.latch(reason);
                receipt = obj.commitRejected(obj.FailureCode);
                return
            end
            if ~obj.FullInner && (control.rotor_saturated ...
                    || control.force_projection_norm_mismatch_n>1.0e-6)
                obj.latch('OUTSIDE_VALIDATED_NO_PROJECTION_NO_SATURATION_DOMAIN');
                receipt = obj.commitRejected(obj.FailureCode);
                return
            end

            if obj.BoardCommit,controlDt=control.dt_s;else,controlDt=feedback.dt_s;end
            obj.PhysicalAdapterState.robust_state = ...
                gpenmpcRobustSe3ObserveControl( ...
                    obj.PhysicalAdapterState.robust_state,control, ...
                    double(controlDt));
            x19 = [obj.OpenSample.x13;obj.OpenSample.rotor_thrust_state_n];
            nominal = gpenmpcKnownNominalAccelerationFromObservation( ...
                x19,obj.OpenSample.wind_estimate_xy_mps, ...
                obj.OpenSample.payload_kg,obj.Assets.calibration, ...
                obj.Assets.profile);
            obj.PhysicalAdapterState.robust_state = ...
                gpenmpcCommitCausalVerticalDisturbanceObserver( ...
                    obj.PhysicalAdapterState.robust_state, ...
                    obj.OpenSample.x13(4:6),nominal, ...
                    double(obj.OpenSample.timestamp_ns)*1.0e-9, ...
                    obj.OpenSample.leg_index,obj.OpenSample.payload_kg);
            pending = gpenmpcPredictCurrentGpEvidence( ...
                obj.OpenSample.x13(4:6),obj.OpenSample.reference_up, ...
                obj.OpenSample.wind_estimate_xy_mps, ...
                obj.OpenSample.payload_kg,control.desired_force_projected_up_n, ...
                obj.PreviousRotorCommandN,obj.ResidualHistoryF, ...
                obj.Assets.prediction_context,obj.Assets.gp_model, ...
                logical(obj.CausalValid),obj.Assets.enmpc);
            obj.Pending = struct('prediction',pending, ...
                'velocity_up_mps',obj.OpenSample.x13(4:6), ...
                'nominal_acceleration_up_mps2',nominal, ...
                'frame_i_from_f',double(pending.gp_frame_i_from_f), ...
                'generation',obj.OpenSample.generation, ...
                'timestamp_ns',obj.OpenSample.timestamp_ns, ...
                'leg_index',obj.OpenSample.leg_index);
            obj.HasPending = true;
            obj.PreviousRotorCommandN = control.rotor_command_n;
            obj.PreviousDesiredForceProjectedN = ...
                double(control.desired_force_projected_up_n(:));
            obj.DesiredForceGeneration = obj.OpenSample.generation;
            obj.DesiredForceSource = "COMMITTED_NOMINAL_CONTROLLER_MIRROR";
            if obj.FullInner
                obj.DesiredForceSource="COMMITTED_CANONICAL_FULL_SE3_KERNEL_HOST_ONLY";
                if obj.BoardCommit,obj.DesiredForceSource="COMMITTED_CANONICAL_FULL_SE3_KERNEL_BOARD_RFC1";end
                obj.FullInnerCommittedCount=obj.FullInnerCommittedCount+uint64(1);
            end
            obj.SampleOpen = false;
            obj.OpenSample = struct();
            obj.ControlCommitCount = obj.ControlCommitCount+uint64(1);
            receipt = struct( ...
                'schema',"GPENMPC_PHYSICAL_CONTROL_COMMIT_V1", ...
                'status',"PASS_HOST_CAUSAL_CONTROL_COMMIT", ...
                'accepted',true,'generation',double(generation), ...
                'pending_gp_available',logical(pending.available), ...
                'causal_valid',obj.CausalValid, ...
                'nominal_acceleration_up_mps2',nominal, ...
                'previous_rotor_command_n_for_prediction', ...
                    double(control.previous_rotor_command_n_for_prediction(:)), ...
                'current_rotor_command_n',control.rotor_command_n, ...
                'plant_truth_used',false,'publication_count',0, ...
                'hardware_actions',0);
            receipt.full_inner_kernel=obj.FullInner;
            receipt.board_consumption_proven=false;
            if obj.BoardCommit
                receipt.board_commit_observation=boardReceipt;
                receipt.status="PASS_HOST_CAUSAL_UPDATE_FROM_BOARD_COMMIT_RFC1";
                receipt.simulator_consumption_proven=false;
            end
        end

        function receipt = commitV7NominalControl(obj,generation,nowNs, ...
                moduleGuard,actuator)
            % Construct the V7 feedback contract inside the causal runtime.
            % The caller supplies only the observed module guard and actual
            % MAVLink HIL_ACTUATOR_CONTROLS packet; it cannot substitute a
            % desired force or synthetic rotor command at this boundary.
            receipt = obj.commitRejected('UNPROCESSED_V7_CONTROL_FEEDBACK');
            if obj.FullInner
                obj.latch('V7_FEEDBACK_FORBIDDEN_FOR_FULL_INNER');
                receipt=obj.commitRejected(obj.FailureCode);
                return
            end
            if obj.Failed
                receipt=obj.commitRejected('HARD_INVALID_ALREADY_LATCHED');
                return
            end
            if ~obj.SampleOpen || ~obj.finiteInteger(generation) ...
                    || uint64(generation)~=obj.OpenSample.generation ...
                    || ~obj.finiteInteger(nowNs)
                obj.latch('V7_CONTROL_COMMIT_SEQUENCE_REJECTED');
                receipt=obj.commitRejected(obj.FailureCode);
                return
            end
            transform=diag([1,1,-1]);
            estimate=struct( ...
                'source',"PX4_EKF2_MAVLINK_ODOMETRY_331", ...
                'atomic_estimate',true,'plant_truth_used',false, ...
                'sample_timestamp_ns',double(obj.OpenSample.timestamp_ns), ...
                'position_ned_m',transform*double(obj.OpenSample.x13(1:3)), ...
                'velocity_ned_mps',transform*double(obj.OpenSample.x13(4:6)));
            estimatedWindNed=[double(obj.OpenSample.wind_estimate_xy_mps(:));0];
            totalMass=double(obj.Assets.profile.mass_properties.base_mass_kg) ...
                +double(obj.OpenSample.payload_kg);
            [mirror,mirrorAccepted,mirrorReason]= ...
                gpenmpcNative.v7NominalControllerMirror( ...
                    estimate,obj.OpenSample.reference_ned,estimatedWindNed, ...
                    totalMass,obj.OpenSample.dt_s,obj.V7Binding);
            if ~mirrorAccepted
                obj.latch("V7_NOMINAL_MIRROR__"+string(mirrorReason));
                receipt=obj.commitRejected(obj.FailureCode);
                return
            end
            adapterExpected=struct( ...
                'system_id',obj.Expected.system_id, ...
                'component_id',obj.Expected.component_id, ...
                'maximum_runtime_age_ns',obj.Expected.maximum_runtime_age_ns, ...
                'per_rotor_upper_n',obj.V7Binding.per_rotor_upper_n, ...
                'software_from_px4_one_based', ...
                    obj.V7Binding.software_from_px4_one_based);
            [feedback,feedbackAccepted,feedbackReason]= ...
                gpenmpcNative.adaptV7NominalControlFeedback( ...
                    mirror,moduleGuard,actuator,adapterExpected, ...
                    double(nowNs),double(generation));
            if ~feedbackAccepted
                obj.latch("V7_CONTROL_FEEDBACK_ADAPTER__"+string(feedbackReason));
                receipt=obj.commitRejected(obj.FailureCode);
                return
            end
            receipt=obj.commitControl(generation,nowNs,feedback);
            receipt.v7_feedback_adapter_status=string(feedbackReason);
            receipt.v7_mirror_source=string(mirror.source);
            receipt.v7_controller_source_sha256= ...
                string(mirror.controller_source_sha256);
            receipt.v7_desired_force_projected_up_n= ...
                double(mirror.desired_force_projected_up_n(:));
            receipt.v7_force_projection_norm_mismatch_n= ...
                double(mirror.force_projection_norm_mismatch_n);
            receipt.v7_commanded_acceleration_ned_mps2= ...
                double(mirror.commanded_acceleration_ned_mps2(:));
            receipt.actual_actuator_source=string(feedback.actuator_source);
            receipt.actual_actuator_message_id=feedback.actuator_message_id;
        end

        function prepareLegTransition(obj,legIndex,payloadKg,nowNs,px4Sample)
            % Called by the outer service only at confirmed ground/disarm.
            % Keep global sample generations and the robust observer state;
            % its canonical vertical reset occurs on the first fresh sample.
            assert(~obj.Failed && ~obj.SampleOpen ...
                &&obj.finiteInteger(legIndex)&&~isnan(obj.CurrentLeg) ...
                &&legIndex==obj.CurrentLeg+1 ...
                &&obj.finiteScalar(payloadKg)&&payloadKg>=0, ...
                'gpenmpcNative:PhysicalLegTransition', ...
                'Invalid pending-control, leg or payload transition.');
            [x13,accepted,reason]=gpenmpcNative.px4EstimateState( ...
                px4Sample,obj.Expected,double(nowNs));
            assert(accepted&&isfield(px4Sample,'sample_timestamp_ns'), ...
                'gpenmpcNative:PhysicalLegEstimate', ...
                'Fresh estimate required before new-leg outer solve: %s',reason);
            obj.PhysicalAdapterState.robust_state= ...
                gpenmpcResetCausalVerticalDisturbanceObserver( ...
                    obj.PhysicalAdapterState.robust_state,x13(4:6), ...
                    double(px4Sample.sample_timestamp_ns)*1e-9,legIndex,payloadKg);
            obj.AuthorizedNextLeg=double(legIndex);
            obj.AuthorizedPayloadKg=double(payloadKg);
            obj.ResidualHistoryF=zeros(3,1);
            obj.CausalValid=false;
            obj.AgreementF=zeros(3,1);
            obj.LatestEvidence=obj.emptyExecutionEvidence();
            obj.Pending=struct();
            obj.HasPending=false;
            obj.PreviousDesiredForceProjectedN= ...
                (double(obj.Assets.profile.mass_properties.base_mass_kg) ...
                +double(payloadKg))*[0;0;9.80665];
            obj.DesiredForceGeneration=uint64(0);
            obj.DesiredForceSource="CANONICAL_LEG_INITIAL_FORCE";
        end

        function value = status(obj)
            physical = obj.PhysicalAdapterState;
            value = struct( ...
                'schema',"GPENMPC_PHYSICAL_CAUSAL_RUNTIME_STATUS_V1", ...
                'failed',obj.Failed,'failure_code',obj.FailureCode, ...
                'last_generation',double(obj.LastGeneration), ...
                'sample_open',obj.SampleOpen,'has_pending_prediction',obj.HasPending, ...
                'current_leg',obj.CurrentLeg, ...
                'begin_count',double(obj.BeginCount), ...
                'control_commit_count',double(obj.ControlCommitCount), ...
                'desired_force_generation',double(obj.DesiredForceGeneration), ...
                'desired_force_source',obj.DesiredForceSource, ...
                'leg_reset_count',double(obj.LegResetCount), ...
                'closed_evidence_count',double(obj.ClosedEvidenceCount), ...
                'available_evidence_count',double(obj.AvailableEvidenceCount), ...
                'causal_valid',obj.CausalValid, ...
                'gp_agreement_weight_f',obj.AgreementF, ...
                'residual_history_f_mps2',obj.ResidualHistoryF, ...
                'physical_accepted_sample_count', ...
                    double(physical.accepted_sample_count), ...
                'physical_gp_active_count', ...
                    double(physical.physical_gp_active_count), ...
                'exact_b1_fallback_count', ...
                    double(physical.exact_b1_fallback_count), ...
                'compute_partition', ...
                    "HOST_A1_AUGMENTATION__BOARD_NOMINAL_POSITION_CONTROL", ...
                'second_position_control_publisher',false, ...
                'plant_truth_used',false,'hardware_actions',0, ...
                'com_open',0,'board_access',0,'parameter_writes',0, ...
                'mapping_writes',0,'arm_requests',0,'mode_requests',0, ...
                'task_rows',0,'physical_output_commands',0);
            value.full_inner_kernel=obj.FullInner;
            value.full_inner_commit_count=double(obj.FullInnerCommittedCount);
            value.final_hil_admission=false;
            if obj.FullInner
                value.compute_partition="HOST_CANONICAL_A1_AND_CONTINUITY__FULL_SE3_KERNEL_INPUT";
                value.full_inner_evidence_scope="HOST_ONLY_KERNEL_EXECUTION";
                if obj.BoardCommit
                    value.full_inner_evidence_scope="BOARD_COMMIT_RFC1";
                    value.board_commit_consumer=obj.BoardCommitConsumer.status();
                end
                value.attitude_continuity_state=obj.AttitudeContinuityState;
                value.robust_authority_scale=double(physical.robust_state.authority_scale);
            end
        end

        function value = outerRuntimeState(obj)
            % Expose only the causal, board-independent state needed by the
            % immutable 0.3 s outer solver snapshot.  This is deliberately a
            % value copy: no plant truth, transport handle, or output endpoint
            % can cross this boundary.
            robust=obj.PhysicalAdapterState.robust_state;
            vertical=0.0;
            blend=0.0;
            filtered=zeros(3,1);
            if isfield(robust,'vertical_disturbance_ewma_mps2')
                vertical=double(robust.vertical_disturbance_ewma_mps2);
            end
            if isfield(robust,'gp_responsibility_blend')
                blend=double(robust.gp_responsibility_blend);
            end
            if isfield(robust,'responsibility_filtered_gp_mean_f_mps2')
                filtered=double(robust.responsibility_filtered_gp_mean_f_mps2(:));
            end
            assert(isfinite(vertical) && isfinite(blend) ...
                && blend>=0 && blend<=1 && numel(filtered)==3 ...
                && all(isfinite(filtered)), ...
                'gpenmpcNative:PhysicalOuterRuntimeState', ...
                'Causal runtime contains invalid outer-snapshot state.');
            value=struct( ...
                'previous_desired_force_projected_n', ...
                    obj.PreviousDesiredForceProjectedN, ...
                'previous_committed_rotor_command_n',obj.PreviousRotorCommandN, ...
                'desired_force_generation',double(obj.DesiredForceGeneration), ...
                'desired_force_source',obj.DesiredForceSource, ...
                'previous_outer_acceleration_correction_i_mps2',zeros(3,1), ...
                'runtime_vertical_observer_shadow_i_mps2',[0;0;-vertical], ...
                'residual_history_f_mps2',double(obj.ResidualHistoryF(:)), ...
                'runtime_gp_axis_weight_f',double(obj.AgreementF(:)), ...
                'runtime_gp_responsibility_blend',blend, ...
                'runtime_gp_filtered_mean_f_mps2',filtered, ...
                'causal_valid',logical(obj.CausalValid), ...
                'gp_evidence',obj.executionEvidence(obj.LatestEvidence), ...
                'plant_truth_used',false,'hardware_actions',0);
            if obj.BoardCommit,value.board_commit_consumer=obj.BoardCommitConsumer.status();end
        end
    end

    methods (Access=private)
        function [ok,reason,context] = validateRuntime(obj,runtime,nowNs)
            ok=false; reason="MALFORMED_PHYSICAL_CAUSAL_RUNTIME"; context=struct();
            required={'schema','task_identity_sha256','plant_truth_used', ...
                'virtual_actuator','wind','task'};
            if ~isstruct(runtime) || ~isscalar(runtime) ...
                    || ~all(isfield(runtime,required)) ...
                    || string(runtime.schema) ...
                        ~= "GPENMPC_PHYSICAL_CAUSAL_RUNTIME_INPUT_V1" ...
                    || ~obj.isSha256(runtime.task_identity_sha256) ...
                    || ~strcmpi(string(runtime.task_identity_sha256), ...
                        obj.TaskIdentitySha256) ...
                    || ~(islogical(runtime.plant_truth_used) ...
                        && isscalar(runtime.plant_truth_used) ...
                        && ~runtime.plant_truth_used)
                reason="RUNTIME_IDENTITY_OR_TRUTH_ISOLATION_REJECTED"; return
            end
            actuator=runtime.virtual_actuator; wind=runtime.wind; task=runtime.task;
            if ~obj.validStamp(actuator, ...
                    "HOST_M600_VIRTUAL_ACTUATOR_INTERFACE",nowNs) ...
                    || ~obj.validStamp(wind,"FROZEN_TASK_WIND_ESTIMATOR",nowNs)
                reason="STALE_OR_INVALID_RUNTIME_SOURCE"; return
            end
            actuatorFields={'ordering','rotor_thrust_state_n'};
            windFields={'estimate_xy_mps'};
            taskFields={'source','payload_kg','leg_index'};
            if ~all(isfield(actuator,actuatorFields)) ...
                    || string(actuator.ordering)~="SOFTWARE_M600_ORDER" ...
                    || ~all(isfield(wind,windFields)) ...
                    || ~all(isfield(task,taskFields)) ...
                    || string(task.source)~="FROZEN_GPENMPC_TASK_STATE" ...
                    || ~obj.finiteVector(actuator.rotor_thrust_state_n,6) ...
                    || any(actuator.rotor_thrust_state_n(:)<0) ...
                    || any(actuator.rotor_thrust_state_n(:)> ...
                        obj.Assets.kernelParameters.rotorUpper+1.0e-12) ...
                    || ~obj.finiteVector(wind.estimate_xy_mps,2) ...
                    || ~obj.finiteScalar(task.payload_kg) || task.payload_kg<0 ...
                    || ~obj.finiteInteger(task.leg_index) || task.leg_index<1
                reason="NONFINITE_OR_OUT_OF_DOMAIN_RUNTIME_VALUE"; return
            end
            actuatorGeneration=double(actuator.generation);
            windGeneration=double(wind.generation);
            if actuatorGeneration<=obj.LastVirtualActuatorGeneration ...
                    || windGeneration<obj.LastWindGeneration
                reason="NONADVANCING_OR_REVERSED_RUNTIME_GENERATION"; return
            end
            context=struct( ...
                'rotor_thrust_state_n',double(actuator.rotor_thrust_state_n(:)), ...
                'wind_estimate_xy_mps',double(wind.estimate_xy_mps(:)), ...
                'payload_kg',double(task.payload_kg), ...
                'leg_index',double(task.leg_index), ...
                'virtual_actuator_generation',actuatorGeneration, ...
                'wind_generation',windGeneration);
            ok=true; reason="PASS";
        end

        function [ok,reason,value] = validateControlFeedback( ...
                obj,feedback,nowNs,generation)
            ok=false; reason="MALFORMED_CONTROL_FEEDBACK"; value=struct();
            required={'schema','source','valid','plant_truth_used','generation', ...
                'rx_ns','dt_s','desired_force_projected_up_n','rotor_command_n', ...
                'rotor_saturated','force_projection_norm_mismatch_n', ...
                'control_mode','failure_reason','active','state_valid', ...
                'reference_fresh','segment_fresh', ...
                'native_position_controller_disabled', ...
                'native_attitude_rate_allocator_enabled', ...
                'single_publisher_contract_pass','mirror_source', ...
                'mirror_sample_timestamp_ns','mirror_exact_nominal', ...
                'robust_acceleration_ned_mps2', ...
                'commanded_acceleration_ned_mps2', ...
                'controller_source_sha256','module_source_sha256', ...
                'module_guard_rx_ns','actuator_source','actuator_message_id', ...
                'actuator_generation','actuator_rx_ns','actuator_time_usec', ...
                'actuator_system_id','actuator_component_id', ...
                'software_from_px4_one_based','direct_actuator_authority', ...
                'hardware_actions'};
            trueFields={'active','state_valid','reference_fresh','segment_fresh', ...
                'native_position_controller_disabled', ...
                'native_attitude_rate_allocator_enabled', ...
                'single_publisher_contract_pass','mirror_exact_nominal'};
            trueFlags=false;
            if isstruct(feedback)&&isscalar(feedback)&&all(isfield(feedback,trueFields))
                trueFlags=all(cellfun(@(f)islogical(feedback.(f)) ...
                    && isscalar(feedback.(f))&&feedback.(f),trueFields));
            end
            if ~isstruct(feedback) || ~isscalar(feedback) ...
                    || ~all(isfield(feedback,required)) ...
                    || string(feedback.schema) ...
                        ~= "GPENMPC_V7_NOMINAL_CONTROL_FEEDBACK_V2" ...
                    || string(feedback.source) ...
                        ~= "PX4_V7_NOMINAL_MIRROR_PLUS_HIL_ACTUATOR_CONTROLS_93" ...
                    || ~(islogical(feedback.valid)&&isscalar(feedback.valid) ...
                        && feedback.valid) ...
                    || ~(islogical(feedback.plant_truth_used) ...
                        && isscalar(feedback.plant_truth_used) ...
                        && ~feedback.plant_truth_used) ...
                    || ~obj.finiteInteger(feedback.generation) ...
                    || double(feedback.generation)~=generation ...
                    || ~obj.finiteScalar(feedback.rx_ns) ...
                    || feedback.rx_ns<double(obj.OpenSample.host_begin_ns) ...
                    || feedback.rx_ns>nowNs ...
                    || nowNs-feedback.rx_ns>obj.Expected.maximum_runtime_age_ns ...
                    || ~obj.finiteScalar(feedback.dt_s) ...
                    || feedback.dt_s<=0 || feedback.dt_s>0.0100001 ...
                    || abs(double(feedback.dt_s)-obj.OpenSample.dt_s)>5.0e-7 ...
                    || ~obj.finiteVector(feedback.desired_force_projected_up_n,3) ...
                    || ~obj.finiteVector(feedback.rotor_command_n,6) ...
                    || any(feedback.rotor_command_n(:)<0) ...
                    || any(feedback.rotor_command_n(:)> ...
                        obj.Assets.kernelParameters.rotorUpper+1.0e-12) ...
                    || ~(islogical(feedback.rotor_saturated) ...
                        && isscalar(feedback.rotor_saturated)) ...
                    || ~obj.finiteScalar( ...
                        feedback.force_projection_norm_mismatch_n) ...
                    || feedback.force_projection_norm_mismatch_n<0 ...
                    || ~trueFlags ...
                    || double(feedback.control_mode)~=1 ...
                    || double(feedback.failure_reason)~=0 ...
                    || string(feedback.mirror_source) ...
                        ~= "HOST_EXACT_V7_NOMINAL_PREPROJECTION_MIRROR" ...
                    || ~obj.finiteInteger(feedback.mirror_sample_timestamp_ns) ...
                    || uint64(feedback.mirror_sample_timestamp_ns) ...
                        ~= uint64(obj.OpenSample.timestamp_ns) ...
                    || ~obj.finiteVector( ...
                        feedback.robust_acceleration_ned_mps2,3) ...
                    || any(abs(feedback.robust_acceleration_ned_mps2(:))>1e-12) ...
                    || ~obj.finiteVector( ...
                        feedback.commanded_acceleration_ned_mps2,3) ...
                    || ~strcmpi(string(feedback.controller_source_sha256), ...
                        "BE085D8302709AE1BD955522E7C9923AAFE90D4C764A9E07DBD7E549A9D51C44") ...
                    || ~strcmpi(string(feedback.module_source_sha256), ...
                        "BA6A0A02F207790149B8AB0DC25C0197B0C39A000F05F6808E236F832DF9718E") ...
                    || ~obj.finiteInteger(feedback.module_guard_rx_ns) ...
                    || feedback.module_guard_rx_ns>nowNs ...
                    || nowNs-feedback.module_guard_rx_ns ...
                        >obj.Expected.maximum_runtime_age_ns ...
                    || string(feedback.actuator_source) ...
                        ~= "PX4_MAVLINK_HIL_ACTUATOR_CONTROLS_93" ...
                    || double(feedback.actuator_message_id)~=93 ...
                    || ~obj.finiteInteger(feedback.actuator_generation) ...
                    || double(feedback.actuator_generation)~=generation ...
                    || ~obj.finiteInteger(feedback.actuator_rx_ns) ...
                    || double(feedback.actuator_rx_ns)~=double(feedback.rx_ns) ...
                    || ~obj.finiteInteger(feedback.actuator_time_usec) ...
                    || feedback.actuator_time_usec<1 ...
                    || double(feedback.actuator_system_id) ...
                        ~=double(obj.Expected.system_id) ...
                    || double(feedback.actuator_component_id) ...
                        ~=double(obj.Expected.component_id) ...
                    || ~isequal(double( ...
                        feedback.software_from_px4_one_based(:)),[5;1;4;6;2;3]) ...
                    || ~(islogical(feedback.direct_actuator_authority) ...
                        && isscalar(feedback.direct_actuator_authority) ...
                        && ~feedback.direct_actuator_authority) ...
                    || ~obj.finiteScalar(feedback.hardware_actions) ...
                    || double(feedback.hardware_actions)~=0
                return
            end
            value=struct( ...
                'desired_force_projected_up_n', ...
                    double(feedback.desired_force_projected_up_n(:)), ...
                'rotor_command_n',double(feedback.rotor_command_n(:)), ...
                'rotor_saturated',logical(feedback.rotor_saturated), ...
                'force_projection_norm_mismatch_n', ...
                    double(feedback.force_projection_norm_mismatch_n), ...
                'previous_rotor_command_n_for_prediction', ...
                    double(obj.PreviousRotorCommandN(:)));
            ok=true; reason="PASS";
        end

        function ok = validStamp(obj,value,source,nowNs)
            required={'source','rx_ns','generation','valid'};
            ok=isstruct(value)&&isscalar(value)&&all(isfield(value,required)) ...
                && string(value.source)==source ...
                && islogical(value.valid)&&isscalar(value.valid)&&value.valid ...
                && obj.finiteInteger(value.generation)&&value.generation>=1 ...
                && obj.finiteScalar(value.rx_ns)&&value.rx_ns>=0 ...
                && value.rx_ns<=nowNs ...
                && nowNs-value.rx_ns<=obj.Expected.maximum_runtime_age_ns;
        end

        function ok = validReference(obj,value)
            required={'position_m','velocity_mps','acceleration_mps2','jerk_mps3'};
            ok=isstruct(value)&&isscalar(value)&&all(isfield(value,required));
            if ~ok, return, end
            for k=1:numel(required)
                if ~obj.finiteVector(value.(required{k}),3), ok=false; return, end
            end
        end

        function value = attachConsistency(obj,evidence,diagnostic)
            value=evidence;
            value.consistency_ewma_f=double(diagnostic.next_weight_f(:).');
            value.consistency_evidence_active= ...
                logical(diagnostic.valid_closed_evidence);
            value.consistency_ewma_aggregate= ...
                double(diagnostic.aggregate_consistency_score);
            value.normalized_innovation_error_f= ...
                double(diagnostic.normalized_innovation_error_f(:).');
            value.innovation_consistency_score_f= ...
                double(diagnostic.instantaneous_consistency_score_f(:).');
            value.consistency_enter_eligible=logical(diagnostic.enter_eligible);
            value.consistency_exit_low=logical(diagnostic.exit_low);
            value.eligible_for_b1_dwell=logical(diagnostic.enter_eligible) ...
                && logical(value.available) ...
                && logical(value.observed_innovation_available) ...
                && ~logical(value.hard_invalid) ...
                && double(value.trust)>=double(obj.Assets.enmpc.minimum_soft_trust);
        end

        function value = executionEvidence(obj,evidence) %#ok<INUSL>
            value=evidence;
            if ~logical(value.available)
                value.predicted_mean_f_mps2=zeros(1,3);
                value.observed_innovation_f_mps2=zeros(1,3);
                value.calibrated_half_width_f_mps2=ones(1,3);
            end
        end

        function value = emptyExecutionEvidence(~)
            value=struct('available',false, ...
                'prediction_sample_closed',false, ...
                'observed_innovation_available',false,'hard_invalid',false, ...
                'trust',0.0,'predicted_mean_f_mps2',zeros(1,3), ...
                'gp_frame_i_from_f',eye(3), ...
                'observed_innovation_f_mps2',zeros(1,3), ...
                'calibrated_half_width_f_mps2',ones(1,3), ...
                'observed_innovation_consistent',false, ...
                'eligible_for_b1_dwell',false);
        end

        function output = latchAndReject(obj,reason)
            obj.latch(reason);
            output=obj.rejected(obj.FailureCode);
        end

        function latch(obj,reason)
            if obj.BoardCommit,obj.BoardCommitConsumer.revoke();end
            obj.Failed=true;
            obj.FailureCode=string(reason);
            obj.SampleOpen=false;
            obj.OpenSample=struct();
            obj.PhysicalAdapterState.hard_invalid_latched=true;
        end

        function output = rejected(obj,reason)
            output=struct( ...
                'schema',"GPENMPC_PHYSICAL_CAUSAL_REFERENCE_V1", ...
                'accepted',false,'publication_allowed',false, ...
                'reason',string(reason),'generation',double(obj.LastGeneration), ...
                'reference_up',struct(),'reference_ned',struct(), ...
                'physical_output',struct(),'composition',struct(), ...
                'closed_gp_evidence',struct(), ...
                'gp_agreement_weight_f',zeros(3,1), ...
                'causal_valid',false,'residual_history_f_mps2',zeros(3,1), ...
                'vertical_observer',struct(), ...
                'compute_partition',"NO_OUTPUT_FAIL_CLOSED", ...
                'board_control_mode',"NO_OUTPUT_FAIL_CLOSED", ...
                'control_commit_required_before_next_sample',false, ...
                'plant_truth_used',false,'hardware_actions',0);
        end

        function receipt = commitRejected(obj,reason)
            receipt=struct( ...
                'schema',"GPENMPC_PHYSICAL_CONTROL_COMMIT_V1", ...
                'status',"FAIL_CLOSED",'accepted',false, ...
                'reason',string(reason),'generation',double(obj.LastGeneration), ...
                'pending_gp_available',false,'causal_valid',false, ...
                'nominal_acceleration_up_mps2',nan(3,1), ...
                'previous_rotor_command_n_for_prediction',nan(6,1), ...
                'current_rotor_command_n',nan(6,1), ...
                'plant_truth_used',false,'publication_count',0, ...
                'hardware_actions',0);
        end

        function ok = finiteScalar(~,value)
            ok=isnumeric(value)&&isreal(value)&&isscalar(value)&&isfinite(value);
        end
        function ok = finiteInteger(obj,value)
            ok=obj.finiteScalar(value)&&value>=0&&value==fix(value) ...
                && value<=double(intmax('uint64'));
        end
        function ok = finiteVector(~,value,count)
            ok=isnumeric(value)&&isreal(value)&&isvector(value) ...
                && numel(value)==count&&all(isfinite(value(:)));
        end
        function ok = isSha256(~,value)
            text=char(upper(string(value)));
            ok=strlength(string(value))==64 ...
                && all(ismember(text,['0':'9','A':'F']));
        end
    end
end
