function [bytes,receipt]=encodeCanonicalFullInnerArguments(command,assets)
% Encode the MATLAB/generated-C ABI: IEEE binary64, big endian,
% column-major matrices, no padding, and all kernel parameters.
assert(string(command.schema)=="GPENMPC_CANONICAL_FULL_INNER_COMMAND_V1" ...
    &&any(string(command.evidence_scope)==["HOST_ONLY_KERNEL_EXECUTION","BOARD_COMMIT_RFC1"]) ...
    &&~command.board_publication_authority ...
    &&strcmpi(command.kernel_source_sha256, ...
        '52F714D65C4A3CD5879FFD4478F60379F68CD5F65A38F5971B91BBC01D0E4AB8') ...
    &&strcmpi(command.configuration_payload_sha256, ...
        assets.binding.effective_configuration_payload_sha256) ...
    &&string(command.coordinate_frame)=="CANONICAL_UP_FRAME_NOT_NED_FRD" ...
    &&command.augmentation_applications==1, ...
    'gpenmpcNative:KernelAbiIdentity','Exact explicitly scoped canonical command required.');
assert(isa(command.generation,'uint64')&&isscalar(command.generation) ...
    &&command.generation>0,'gpenmpcNative:KernelAbiGeneration','Exact uint64 generation required.');
a=command.attitude_command;r=command.reference_up;p=assets.kernelParameters;
assert(a.enabled,'gpenmpcNative:KernelAbiContinuity','Current canonical continuity is enabled.');
bytes=uint8('RAK1').';
realField(command.state_up,19);realField(r.position_m,3);
realField(r.velocity_mps,3);realField(r.acceleration_mps2,3);
realField(command.payload_kg,1);realField(command.wind_estimate_xy_mps,2);
realField(command.augmentation_up_mps2,3);bytes(end+1,1)=uint8(1);
realField(a.desired_rotation,9);realField(a.desired_angular_velocity_body_rad_s,3);
realField(a.desired_angular_acceleration_body_rad_s2,3);
names={'kp','kd','kr','kw','drag','inertia','pseudoinverse', ...
    'baseMass','totalThrust','rotorUpper','maxTilt'};
sizes=[3 3 3 3 3 9 24 1 1 1 1];
for k=1:numel(names),realField(p.(names{k}),sizes(k));end
% HOST keeps its original logical generation. BOARD_COMMIT explicitly binds
% these stateful calculations to the ACTUAL private source generation.
if string(command.evidence_scope)=="BOARD_COMMIT_RFC1"
    assert(isa(command.source_generation,'uint64')&&command.source_generation==command.generation ...
        &&isequal(command.augmentation_state_generation,command.source_generation) ...
        &&isequal(command.continuity_state_generation,command.source_generation), ...
        'gpenmpcNative:KernelAbiBoardGeneration','Original private source generation required.');
end
appendBE(command.generation);appendBE(command.generation);
assert(numel(bytes)==829,'gpenmpcNative:KernelAbiLength','Numerical ABI length drift.');
digest=java.security.MessageDigest.getInstance('SHA-256');
digest.update(typecast(bytes,'int8'));
hash=upper(reshape(dec2hex(typecast(digest.digest(),'uint8'),2).',1,[]));
receipt=struct('schema','GPENMPC_HOST_CANONICAL_KERNEL_ARGUMENT_ABI_V1', ...
    'byte_count',829,'binary64_count',101,'kernel_argument_sha256',hash, ...
    'generation',command.generation,'source_scope',command.evidence_scope, ...
    'live_wire_protocol',false,'board_access',0,'publication_authority',false);
    function realField(value,count)
        assert(isa(value,'double')&&isreal(value)&&numel(value)==count ...
            &&all(isfinite(value(:))), ...
            'gpenmpcNative:KernelAbiField','Finite exact-size binary64 field required.');
        appendBE(value(:));
    end
    function appendBE(value)
        [~,~,endian]=computer;
        if endian=='L',value=swapbytes(value);end
        bytes=[bytes;reshape(typecast(value(:),'uint8'),[],1)]; %#ok<AGROW>
    end
end
