function feedback=executeCanonicalFullInnerKernelHost(command,assets,rxNs)
% Execute the extracted full controller as a host numerical endpoint.
assert(string(command.evidence_scope)=="HOST_ONLY_KERNEL_EXECUTION" ...
    &&~command.board_publication_authority ...
    &&string(command.schema)=="GPENMPC_CANONICAL_FULL_INNER_COMMAND_V1", ...
    'gpenmpcNative:HostKernelScope','HOST-only command required.');
a=command.attitude_command;r=command.reference_up;
[w,u,d,valid]=gpenmpcNative.se3WrenchKernel(command.state_up, ...
    r.position_m,r.velocity_mps,r.acceleration_mps2,command.payload_kg, ...
    command.wind_estimate_xy_mps,command.augmentation_up_mps2,true, ...
    a.desired_rotation,a.desired_angular_velocity_body_rad_s, ...
    a.desired_angular_acceleration_body_rad_s2,assets.kernelParameters);
feedback=struct('schema','GPENMPC_CANONICAL_FULL_INNER_FEEDBACK_V1', ...
    'evidence_scope','HOST_ONLY_KERNEL_EXECUTION', ...
    'generation',command.generation, ...
    'estimate_sample_timestamp_ns',command.estimate_sample_timestamp_ns, ...
    'task_identity_sha256',command.task_identity_sha256, ...
    'configuration_payload_sha256',command.configuration_payload_sha256, ...
    'kernel_source_sha256',command.kernel_source_sha256, ...
    'rx_ns',double(rxNs),'dt_s',command.dt_s,'valid',logical(valid), ...
    'wrench_n_nm',w,'rotor_command_n',u,'diagnostic51',d, ...
    'board_consumption_proven',false,'plant_truth_used',false,'hardware_actions',0);
end
