classdef LiveHilPlantService < handle
    % LIVEHILPLANTSERVICE Own the 19-state M600 plant, delivery timeline
    % and asynchronous 0.3 s outer method. Consume board and actuator observations.
    properties (SetAccess=private)
        Initialized=false
        Prepared=false
        Admitted=false
        Failed=false
        FailureCode=""
        PhysicalGeneration=uint64(0)
        OuterGeneration=uint64(0)
        PlantStepCount=uint64(0)
        GroundStepCount=uint64(0)
        ReferencePublicationCount=uint64(0)
        ContactEntryCount=uint64(0)
        EnergyJ=0.0
        SimTimeS=0.0
        AirborneObserved=false
        GroundConfirmed=true
        GroundSupportDwellS=0.50
        HardwareActions=0
    end
    properties (Access=private)
        WorkRoot
        TaskPath
        TaskIdentitySha256
        Task
        Assets
        Expected
        Trajectory
        BoardService
        StateUp
        AccelerationUp=zeros(3,1)
        ContactParameters
        LastContact=struct()
        OpenContext=struct()
        SampleOpen=false
        TaskIndex=1
        TakeoffDurationS=20.0
        NextOuterDuePhaseS=0.0
        InitialPayloadKg=0.0
        PreviousContactActive=false
        GroundSupportRequiredS=0.50
        LastPowerW=0.0
        LastPlantDiagnostic=struct()
        LastOuterDisposition="NOT_STARTED"
        Closed=false
    end
    methods
        function obj=LiveHilPlantService(workRoot,taskPath,expected)
            obj.WorkRoot=string(workRoot);
            obj.TaskPath=string(taskPath);
            assert(isfolder(obj.WorkRoot)&&isfile(obj.TaskPath), ...
                'gpenmpcNative:LivePlantInputs','Work root or task is missing.');
            loaded=load(obj.TaskPath,'physicalTask');
            assert(isfield(loaded,'physicalTask') ...
                && string(loaded.physicalTask.schema)== ...
                    "GPENMPC_CURRENT_A1_PHYSICAL_CLOSED_LOOP_TASK_V3", ...
                'gpenmpcNative:LivePlantTask','Unexpected physical task.');
            obj.Task=loaded.physicalTask;
            obj.Assets=gpenmpcNative.loadCurrentAssets(obj.WorkRoot);
            obj.TaskIdentitySha256=gpenmpcNative.fileSha256(obj.TaskPath);
            assert(isstruct(expected)&&isscalar(expected) ...
                &&isfield(expected,'task_identity_sha256') ...
                &&strcmpi(string(expected.task_identity_sha256), ...
                    obj.TaskIdentitySha256), ...
                'gpenmpcNative:LivePlantTaskIdentity','Task SHA mismatch.');
            obj.Expected=expected;
            obj.Trajectory=buildLiveTrajectory(obj.Task,obj.TakeoffDurationS);
            obj.BoardService=gpenmpcNative.BoardOuterService( ...
                obj.WorkRoot,obj.Expected,obj.Trajectory);
            first=obj.Task.reference;
            firstPosition=double(first.position_m(1,:)).';
            obj.InitialPayloadKg=double(first.payload_kg(1));
            obj.StateUp=[firstPosition(1:2);0;zeros(3,1);1;zeros(6,1);zeros(6,1)];
            obj.ContactParameters=frozenContactParameters();
            trueMass=obj.trueMass(obj.InitialPayloadKg);
            obj.LastContact=gpenmpcNative.compliantContactState( ...
                obj.StateUp,trueMass,obj.ContactParameters);
            obj.LastPowerW=double(obj.Assets.profile.energy_model.ground_auxiliary_power_w);
            obj.Initialized=true;
        end

        function receipt=prepare(obj,nowNs,px4Sample)
            obj.requireUsable();
            assert(~obj.Prepared && ~obj.Admitted && obj.PhysicalGeneration==0, ...
                'gpenmpcNative:LivePlantPrepareState','Preparation is one-shot.');
            runtime=obj.outerRuntime(px4Sample,nowNs);
            receipt=obj.BoardService.prepare(double(nowNs),px4Sample,runtime);
            assert(string(receipt.status)=="PASS_HOST_PREPARATION", ...
                'gpenmpcNative:LivePlantPreparation','Outer preparation failed.');
            obj.Prepared=true;
            receipt.plant=obj.snapshot();
            receipt.initial_reference=obj.currentReference();
        end

        function receipt=admit(obj,nowNs,px4Sample)
            obj.requireUsable();
            assert(obj.Prepared && ~obj.Admitted, ...
                'gpenmpcNative:LivePlantAdmissionState','Invalid admission state.');
            obj.OuterGeneration=uint64(1);
            runtime=obj.outerRuntime(px4Sample,nowNs);
            response=obj.BoardService.update(obj.OuterGeneration, ...
                double(nowNs),px4Sample,runtime);
            assert(logical(response.decision_success), ...
                'gpenmpcNative:LivePlantInitialOuter', ...
                'Initial selected-method outer solve did not commit.');
            obj.Admitted=true;
            obj.NextOuterDuePhaseS=obj.Assets.enmpc.outer_period_s;
            obj.LastOuterDisposition="INITIAL_SYNCHRONOUS_RESULT";
            receipt=struct('schema','GPENMPC_LIVE_PLANT_ADMISSION_V1', ...
                'status','PASS_SELECTED_METHOD_ADMITTED', ...
                'outer_generation',double(obj.OuterGeneration), ...
                'outer_response',response,'plant',obj.snapshot(), ...
                'hardware_actions',0,'com_open',0,'board_access',0);
        end

        function response=beginSample(obj,nowNs,px4Sample)
            obj.requireAdmitted();
            assert(~obj.SampleOpen, ...
                'gpenmpcNative:LivePlantSampleOpen','Previous sample remains open.');
            obj.pollAndMaybeSubmit(nowNs,px4Sample);
            response=obj.openNextSample(nowNs,px4Sample);
        end

        function response=commitAdvanceAndBegin(obj,nowNs,px4Sample, ...
                moduleGuard,actuatorOutput)
            obj.requireAdmitted();
            assert(obj.SampleOpen, ...
                'gpenmpcNative:LivePlantNoOpenSample','No sample is open.');
            commit=obj.BoardService.commitV7PhysicalControl( ...
                obj.PhysicalGeneration,double(nowNs),moduleGuard,actuatorOutput);
            assert(logical(commit.accepted), ...
                'gpenmpcNative:LivePlantControlCommit', ...
                'Actual board control failed the causal commit boundary.');
            obj.integrate(double(commit.current_rotor_command_n(:)),obj.OpenContext);
            obj.SampleOpen=false;
            obj.OpenContext=struct();
            obj.pollAndMaybeSubmit(nowNs,px4Sample);
            phase=obj.phaseContext();
            if any(phase.phase_code==[11,21])
                response=struct('schema','GPENMPC_LIVE_PLANT_STEP_V1', ...
                    'status','NATIVE_LAND_REQUIRED__TASK_CLOCK_PAUSED', ...
                    'reference_publication_allowed',false, ...
                    'native_land_required',true, ...
                    'final_land',phase.phase_code==21, ...
                    'phase',phase,'commit',commit,'plant',obj.snapshot(), ...
                    'outer_disposition',obj.LastOuterDisposition, ...
                    'hardware_actions',0,'com_open',0,'board_access',0);
                return
            end
            next=obj.openNextSample(nowNs,px4Sample);
            next.commit=commit;
            next.plant=obj.snapshot();
            response=next;
        end

        function response=landingStep(obj,nowNs,actuatorOutput,boardArmed)
            % Continue the same source-native HIL plant under PX4 native LAND.
            % No task reference or selected-method state is advanced here.
            obj.requireAdmitted();
            assert(~obj.SampleOpen && islogical(boardArmed)&&isscalar(boardArmed), ...
                'gpenmpcNative:LivePlantLandingState','Invalid landing state.');
            controls=obj.validateActuator(actuatorOutput,nowNs);
            rotor=controls([5;1;4;6;2;3]).* ...
                gpenmpcNative.v7NominalControllerBinding().per_rotor_upper_n;
            context=obj.phaseContext();
            reference=obj.directReferenceAtPhase(context.live_phase_s);
            open=struct('reference_up',reference,'payload_kg',context.payload_kg, ...
                'actual_wind_xy_mps',context.actual_wind_xy_mps, ...
                'wind_estimate_xy_mps',context.wind_estimate_xy_mps, ...
                'phase_code',context.phase_code, ...
                'task_time_s',context.task_time_s,'board_armed',boardArmed);
            obj.integrate(rotor,open);
            response=struct('schema','GPENMPC_LIVE_PLANT_LAND_STEP_V1', ...
                'status','NATIVE_LAND_PLANT_ADVANCED', ...
                'reference_publication_allowed',false,'phase',context, ...
                'plant',obj.snapshot(),'hardware_actions',0, ...
                'com_open',0,'board_access',0);
        end

        function response=groundStep(obj,dtS,boardArmed)
            obj.requireAdmitted();
            assert(~obj.SampleOpen && obj.GroundConfirmed ...
                &&islogical(boardArmed)&&isscalar(boardArmed)&&~boardArmed, ...
                'gpenmpcNative:LivePlantGroundState', ...
                'Ground clock requires software contact and board disarm.');
            ground=obj.BoardService.stepGroundReference(double(dtS),true,false);
            obj.holdGround();
            obj.GroundStepCount=obj.GroundStepCount+uint64(1);
            phase=obj.phaseContext();
            complete=phase.live_phase_s>=obj.Trajectory.total_duration_s-1e-9;
            rearm=phase.phase_code==12 && ~complete;
            response=struct('schema','GPENMPC_LIVE_PLANT_GROUND_STEP_V1', ...
                'status',ternary(complete,'TASK_COMPLETE_ON_GROUND', ...
                    ternary(rearm,'REARM_REQUIRED','GROUND_DWELL_RUNNING')), ...
                'ground_reference',ground,'phase',phase, ...
                'task_complete',complete,'rearm_required',rearm, ...
                'reference_publication_allowed',false,'plant',obj.snapshot(), ...
                'hardware_actions',0,'com_open',0,'board_access',0);
        end

        function response=resumeAdmission(obj,nowNs,px4Sample)
            % Commit one fresh outer decision after a completed ground dwell.
            obj.requireAdmitted();
            assert(~obj.SampleOpen&&obj.GroundConfirmed, ...
                'gpenmpcNative:LivePlantResumeState','Resume requires ground state.');
            phase=obj.phaseContext();
            assert(phase.phase_code==12, ...
                'gpenmpcNative:LivePlantResumePhase','Resume is not at ascent phase.');
            obj.drainAsync(nowNs);
            obj.OuterGeneration=obj.OuterGeneration+uint64(1);
            runtime=obj.outerRuntime(px4Sample,nowNs);
            outer=obj.BoardService.update(obj.OuterGeneration,double(nowNs), ...
                px4Sample,runtime);
            assert(logical(outer.decision_success), ...
                'gpenmpcNative:LivePlantResumeOuter','Resume outer solve failed.');
            obj.NextOuterDuePhaseS=phase.live_phase_s+ ...
                obj.Assets.enmpc.outer_period_s;
            obj.LastOuterDisposition="GROUND_RESUME_SYNCHRONOUS_RESULT";
            response=struct('schema','GPENMPC_LIVE_PLANT_RESUME_V1', ...
                'status','PASS_REARM_REFERENCE_READY', ...
                'initial_reference',obj.currentReference(), ...
                'phase',phase,'outer_response',outer,'plant',obj.snapshot(), ...
                'hardware_actions',0,'com_open',0,'board_access',0);
        end

        function reference=currentReference(obj)
            status=obj.BoardService.status();
            reference=obj.directReferenceAtPhase(double(status.phase_s));
        end

        function value=snapshot(obj)
            qUp=double(obj.StateUp(7:10));qUp=qUp/max(norm(qUp),1e-15);
            qNed=qUp.*[1;-1;-1;1];
            omegaFrd=double(obj.StateUp(11:13)).*[-1;-1;1];
            accelerationNed=[obj.AccelerationUp(1); ...
                obj.AccelerationUp(2);-obj.AccelerationUp(3)];
            rotationNedFromBody=quaternionRotation(qNed);
            specificForceBody=rotationNedFromBody.'* ...
                (accelerationNed-[0;0;9.80665]);
            magneticBody=rotationNedFromBody.'*[0.215;0;0.427];
            altitudeMsl=488.0+double(obj.StateUp(3));
            pressurePa=101325.0*max(1.0-2.25577e-5*altitudeMsl,0.1)^5.25588;
            sensor=struct('specific_force_body_mps2',specificForceBody, ...
                'gyro_body_frd_rad_s',omegaFrd,'magnetic_body_gauss',magneticBody, ...
                'pressure_mbar',pressurePa/100.0, ...
                'pressure_alt_m',altitudeMsl,'altitude_msl_m',altitudeMsl, ...
                'source','SINGLE_MATLAB_M600_SOFTWARE_PLANT', ...
                'plant_instance_count',1);
            value=struct( ...
                'schema','GPENMPC_M600_SINGLE_SOFTWARE_PLANT_STATE_V1', ...
                'sim_time_s',obj.SimTimeS, ...
                'position_up_m',double(obj.StateUp(1:3)), ...
                'velocity_up_mps',double(obj.StateUp(4:6)), ...
                'quaternion_wxyz_body_to_up',qUp, ...
                'body_rate_up_rad_s',double(obj.StateUp(11:13)), ...
                'rotor_thrust_software_order_n',double(obj.StateUp(14:19)), ...
                'acceleration_up_mps2',double(obj.AccelerationUp), ...
                'position_ned_m',[obj.StateUp(1);obj.StateUp(2);-obj.StateUp(3)], ...
                'velocity_ned_mps',[obj.StateUp(4);obj.StateUp(5);-obj.StateUp(6)], ...
                'quaternion_wxyz_body_to_ned',qNed, ...
                'body_rate_frd_rad_s',omegaFrd, ...
                'acceleration_ned_mps2',accelerationNed, ...
                'sensor',sensor, ...
                'airborne_observed',obj.AirborneObserved, ...
                'ground_confirmed',obj.GroundConfirmed, ...
                'ground_support_dwell_s',obj.GroundSupportDwellS, ...
                'ground_support_required_s',obj.GroundSupportRequiredS, ...
                'contact_active',logical(obj.LastContact.contact_active), ...
                'contact_force_n',double(obj.LastContact.contact_force_n), ...
                'energy_model_j',obj.EnergyJ,'last_power_model_w',obj.LastPowerW, ...
                'plant_instance_count',1,'plant_truth_used_for_command',false, ...
                'hardware_actions',0);
        end

        function value=status(obj)
            board=obj.BoardService.status();
            value=struct('schema','GPENMPC_LIVE_PLANT_STATUS_V1', ...
                'initialized',obj.Initialized,'prepared',obj.Prepared, ...
                'admitted',obj.Admitted,'failed',obj.Failed, ...
                'failure_code',obj.FailureCode, ...
                'physical_generation',double(obj.PhysicalGeneration), ...
                'outer_generation',double(obj.OuterGeneration), ...
                'plant_steps',double(obj.PlantStepCount), ...
                'ground_steps',double(obj.GroundStepCount), ...
                'reference_publications',double(obj.ReferencePublicationCount), ...
                'contact_entries',double(obj.ContactEntryCount), ...
                'phase',obj.phaseContext(),'plant',obj.snapshot(), ...
                'outer_service',board,'hardware_actions',0, ...
                'com_open',0,'board_access',0);
        end

        function close(obj)
            if obj.Closed,return,end
            if ~isempty(obj.BoardService),obj.BoardService.close();end
            obj.Closed=true;
        end

        function delete(obj)
            obj.close();
        end
    end

    methods (Access=private)
        function response=openNextSample(obj,nowNs,px4Sample)
            phaseBefore=obj.phaseContext();
            obj.PhysicalGeneration=obj.PhysicalGeneration+uint64(1);
            runtime=obj.physicalRuntime(nowNs,phaseBefore);
            physical=obj.BoardService.stepPhysicalReference( ...
                obj.PhysicalGeneration,double(nowNs),px4Sample,runtime,0.01);
            assert(logical(physical.accepted)&&logical(physical.publication_allowed), ...
                'gpenmpcNative:LivePlantReference','Physical reference rejected.');
            obj.SampleOpen=true;
            obj.ReferencePublicationCount=obj.ReferencePublicationCount+uint64(1);
            obj.OpenContext=struct( ...
                'reference_up',physical.reference_up, ...
                'payload_kg',phaseBefore.payload_kg, ...
                'actual_wind_xy_mps',phaseBefore.actual_wind_xy_mps, ...
                'wind_estimate_xy_mps',phaseBefore.wind_estimate_xy_mps, ...
                'phase_code',phaseBefore.phase_code, ...
                'task_time_s',phaseBefore.task_time_s,'board_armed',true);
            response=struct('schema','GPENMPC_LIVE_PLANT_STEP_V1', ...
                'status','REFERENCE_READY_FOR_SINGLE_BOARD_PUBLISHER', ...
                'generation',double(obj.PhysicalGeneration), ...
                'reference_publication_allowed',true, ...
                'reference_ned',physical.reference_ned, ...
                'reference_up',physical.reference_up, ...
                'physical_reference',physical,'phase',phaseBefore, ...
                'plant',obj.snapshot(),'outer_disposition',obj.LastOuterDisposition, ...
                'native_land_required',false,'hardware_actions',0, ...
                'com_open',0,'board_access',0);
        end

        function pollAndMaybeSubmit(obj,nowNs,px4Sample)
            board=obj.BoardService.status();
            if logical(board.async_in_flight)
                poll=obj.BoardService.pollUpdate(double(nowNs));
                obj.LastOuterDisposition=string(poll.status);
                board=obj.BoardService.status();
            end
            phase=double(board.phase_s);
            if ~logical(board.async_in_flight) ...
                    &&phase+1e-12>=obj.NextOuterDuePhaseS
                obj.OuterGeneration=obj.OuterGeneration+uint64(1);
                runtime=obj.outerRuntime(px4Sample,nowNs);
                submit=obj.BoardService.submitUpdate(obj.OuterGeneration, ...
                    double(nowNs),px4Sample,runtime);
                obj.LastOuterDisposition=string(submit.status);
                obj.NextOuterDuePhaseS=obj.NextOuterDuePhaseS+ ...
                    obj.Assets.enmpc.outer_period_s;
            end
        end

        function drainAsync(obj,nowNs)
            started=tic;
            while logical(obj.BoardService.status().async_in_flight) ...
                    &&toc(started)<1.0
                poll=obj.BoardService.pollUpdate( ...
                    double(nowNs)+round(toc(started)*1e9));
                obj.LastOuterDisposition=string(poll.status);
                if contains(string(poll.status),'FAIL_CLOSED')
                    error('gpenmpcNative:LivePlantAsyncDrain','%s',poll.status);
                end
                pause(0.002);
            end
            assert(~logical(obj.BoardService.status().async_in_flight), ...
                'gpenmpcNative:LivePlantAsyncDrainTimeout', ...
                'Outer worker did not drain before ground resume.');
        end

        function runtime=outerRuntime(obj,px4Sample,nowNs)
            generation=max([double(px4Sample.position_generation), ...
                double(px4Sample.attitude_generation), ...
                double(px4Sample.rates_generation)]);
            phase=obj.phaseContext();
            effectiveness=double( ...
                obj.Task.mission_config.plant_mismatch.thrust_effectiveness_by_rotor(:));
            runtime=obj.BoardService.outerRuntime(generation,double(nowNs), ...
                obj.StateUp(14:19),effectiveness, ...
                phase.wind_estimate_xy_mps,phase.payload_kg);
        end

        function runtime=physicalRuntime(obj,nowNs,phase)
            generation=double(obj.PhysicalGeneration);
            stamp=@(source)struct('source',source,'rx_ns',double(nowNs), ...
                'generation',generation,'valid',true);
            actuator=stamp('HOST_M600_VIRTUAL_ACTUATOR_INTERFACE');
            actuator.ordering='SOFTWARE_M600_ORDER';
            actuator.rotor_thrust_state_n=double(obj.StateUp(14:19));
            wind=stamp('FROZEN_TASK_WIND_ESTIMATOR');
            wind.estimate_xy_mps=double(phase.wind_estimate_xy_mps(:));
            runtime=struct('schema', ...
                'GPENMPC_PHYSICAL_CAUSAL_RUNTIME_INPUT_V1', ...
                'task_identity_sha256',obj.TaskIdentitySha256, ...
                'plant_truth_used',false,'virtual_actuator',actuator, ...
                'wind',wind,'task',struct( ...
                    'source','FROZEN_GPENMPC_TASK_STATE', ...
                    'payload_kg',double(phase.payload_kg), ...
                    'leg_index',double(phase.leg_index)));
        end

        function phase=phaseContext(obj)
            board=obj.BoardService.status();
            livePhase=double(board.phase_s);
            taskTime=livePhase-obj.TakeoffDurationS;
            reference=obj.Task.reference;
            if taskTime<=0
                index=1;phaseCode=0;leg=double(reference.leg_index(1));
            else
                while obj.TaskIndex<numel(reference.global_time_s) ...
                        &&double(reference.global_time_s(obj.TaskIndex+1)) ...
                            <=taskTime+1e-12
                    obj.TaskIndex=obj.TaskIndex+1;
                end
                index=obj.TaskIndex;
                phaseCode=double(reference.phase_code(index));
                leg=double(reference.leg_index(index));
            end
            phase=struct('live_phase_s',livePhase, ...
                'task_time_s',max(0,taskTime),'task_index',index, ...
                'phase_code',phaseCode,'leg_index',leg, ...
                'payload_kg',double(reference.payload_kg(index)), ...
                'actual_wind_xy_mps',double(reference.actual_wind_xy_mps(index,:)).', ...
                'wind_estimate_xy_mps',double(reference.wind_estimate_xy_mps(index,:)).', ...
                'pretask_takeoff',taskTime<0, ...
                'formal_task_started',taskTime>=0);
        end

        function reference=directReferenceAtPhase(obj,livePhase)
            reference=gpenmpcPhaseReference(obj.Trajectory,double(livePhase),1,0,0);
        end

        function integrate(obj,rotorCommandN,context)
            dt=0.01;
            start=double(obj.StateUp(:));
            rotor=double(rotorCommandN(:));
            assert(numel(rotor)==6&&all(isfinite(rotor))&&all(rotor>=0), ...
                'gpenmpcNative:LivePlantRotor','Invalid virtual rotor command.');
            reference=context.reference_up;
            payload=double(context.payload_kg);
            actualWind=double(context.actual_wind_xy_mps(:));
            [k1,~]=obj.derivative(start,rotor,reference,payload,actualWind,obj.SimTimeS);
            mid=gpenmpcReferenceExtrapolation(reference,0.5*dt);
            [k2,~]=obj.derivative(start+0.5*dt*k1,rotor,mid,payload, ...
                actualWind,obj.SimTimeS+0.5*dt);
            [k3,~]=obj.derivative(start+0.5*dt*k2,rotor,mid,payload, ...
                actualWind,obj.SimTimeS+0.5*dt);
            next=gpenmpcReferenceExtrapolation(reference,dt);
            [k4,~]=obj.derivative(start+dt*k3,rotor,next,payload, ...
                actualWind,obj.SimTimeS+dt);
            state=start+dt*(k1+2*k2+2*k3+k4)/6;
            state(7:10)=state(7:10)/max(norm(state(7:10)),1e-15);
            state(14:19)=min(max(state(14:19),0), ...
                obj.Assets.kernelParameters.rotorUpper);
            [~,diagnostic]=obj.derivative(state,rotor,next,payload,actualWind, ...
                obj.SimTimeS+dt);
            contact=gpenmpcNative.compliantContactState( ...
                state,obj.trueMass(payload),obj.ContactParameters);
            if logical(contact.contact_overtravel_m>1e-12)
                error('gpenmpcNative:LivePlantContactOvertravel', ...
                    'Software landing gear exceeded the frozen stroke.');
            end
            if logical(contact.contact_active)&&~obj.PreviousContactActive
                obj.ContactEntryCount=obj.ContactEntryCount+uint64(1);
            end
            obj.PreviousContactActive=logical(contact.contact_active);
            obj.AirborneObserved=obj.AirborneObserved||state(3)>0.02;
            supportCandidate=logical(contact.contact_active) ...
                &&state(3)<=0.10&&abs(state(6))<=0.15;
            if supportCandidate
                obj.GroundSupportDwellS=obj.GroundSupportDwellS+dt;
            else
                obj.GroundSupportDwellS=0.0;
            end
            obj.GroundConfirmed=obj.GroundSupportDwellS+1e-12 ...
                >=obj.GroundSupportRequiredS;
            obj.StateUp=state;
            obj.AccelerationUp=double(diagnostic.actual_acceleration_mps2(:));
            obj.LastContact=contact;
            obj.LastPlantDiagnostic=diagnostic;
            [power,~]=gpenmpcM600ControllerSensitivePower( ...
                obj.Assets.profile,obj.Assets.calibration,payload,state,next, ...
                actualWind,double(context.wind_estimate_xy_mps(:)));
            obj.LastPowerW=double(power);
            obj.EnergyJ=obj.EnergyJ+dt*obj.LastPowerW;
            obj.SimTimeS=obj.SimTimeS+dt;
            obj.PlantStepCount=obj.PlantStepCount+uint64(1);
        end

        function [value,diagnostic]=derivative(obj,state,rotor,reference, ...
                payload,actualWind,timeS)
            [value,diagnostic]=gpenmpcM600SixDofPlantDerivative( ...
                state,rotor,reference,payload,actualWind,timeS, ...
                obj.Task.mission_config,obj.Assets.calibration,obj.Assets.profile);
            contact=gpenmpcNative.compliantContactState( ...
                state,double(diagnostic.true_mass_kg),obj.ContactParameters);
            value(6)=value(6)+double(contact.vertical_acceleration_up_mps2);
            diagnostic.actual_acceleration_mps2(3)= ...
                diagnostic.actual_acceleration_mps2(3) ...
                +double(contact.vertical_acceleration_up_mps2);
        end

        function controls=validateActuator(obj,actuator,nowNs)
            required={'mavpackettype','controls','src_system','src_component', ...
                'rx_ns','time_usec'};
            assert(isstruct(actuator)&&isscalar(actuator) ...
                &&all(isfield(actuator,required)) ...
                &&string(actuator.mavpackettype)=="HIL_ACTUATOR_CONTROLS" ...
                &&double(actuator.src_system)==double(obj.Expected.system_id) ...
                &&double(actuator.src_component)==double(obj.Expected.component_id) ...
                &&isfinite(actuator.rx_ns)&&actuator.rx_ns<=nowNs ...
                &&nowNs-actuator.rx_ns<=obj.Expected.maximum_runtime_age_ns, ...
                'gpenmpcNative:LivePlantLandingActuator', ...
                'Landing actuator observation is invalid or stale.');
            controls=double(actuator.controls(:));
            assert(numel(controls)==16&&all(isfinite(controls(1:6))) ...
                &&all(controls(1:6)>=0)&&all(controls(1:6)<=1), ...
                'gpenmpcNative:LivePlantLandingActuatorValue', ...
                'Landing actuator control is invalid.');
        end

        function holdGround(obj)
            obj.StateUp(3)=0;obj.StateUp(4:6)=0;obj.StateUp(11:13)=0;
            obj.StateUp(14:19)=0;obj.AccelerationUp=zeros(3,1);
            obj.GroundConfirmed=true;
            obj.GroundSupportDwellS=obj.GroundSupportRequiredS;
            obj.LastContact=gpenmpcNative.compliantContactState( ...
                obj.StateUp,obj.trueMass(obj.phaseContext().payload_kg), ...
                obj.ContactParameters);
            obj.LastPowerW=double(obj.Assets.profile.energy_model.ground_auxiliary_power_w);
            obj.EnergyJ=obj.EnergyJ+0.01*obj.LastPowerW;
            obj.SimTimeS=obj.SimTimeS+0.01;
        end

        function mass=trueMass(obj,payload)
            mass=double(obj.Assets.profile.mass_properties.base_mass_kg) ...
                +double(payload) ...
                +double(obj.Task.mission_config.plant_mismatch.mass_bias_kg);
        end

        function requireUsable(obj)
            assert(obj.Initialized&&~obj.Closed&&~obj.Failed, ...
                'gpenmpcNative:LivePlantUnavailable','Live plant service unavailable.');
        end

        function requireAdmitted(obj)
            obj.requireUsable();
            assert(obj.Prepared&&obj.Admitted, ...
                'gpenmpcNative:LivePlantNotAdmitted','Live plant is not admitted.');
        end
    end
end

function trajectory=buildLiveTrajectory(task,takeoffDurationS)
reference=task.reference;
dt=double(task.mission_config.simulation.sample_period_s);
prefixTime=(0:dt:takeoffDurationS-dt).';
n=numel(prefixTime);
tau=prefixTime/takeoffDurationS;
blend=10*tau.^3-15*tau.^4+6*tau.^5;
blendRate=(30*tau.^2-60*tau.^3+30*tau.^4)/takeoffDurationS;
blendAcceleration=(60*tau-180*tau.^2+120*tau.^3)/takeoffDurationS^2;
blendJerk=(60-360*tau+360*tau.^2)/takeoffDurationS^3;
start=double(reference.position_m(1,:));start(3)=0;
finish=double(reference.position_m(1,:));delta=finish-start;
position=repmat(start,n,1)+blend*delta;
velocity=blendRate*delta;
acceleration=blendAcceleration*delta;
jerk=blendJerk*delta;
time=[prefixTime;takeoffDurationS+double(reference.global_time_s(:))];
position=[position;double(reference.position_m)];
velocity=[velocity;double(reference.velocity_mps)];
acceleration=[acceleration;double(reference.acceleration_mps2)];
jerk=[jerk;double(reference.jerk_mps3)];
trajectory=gpenmpcSampledC3Trajectory(time,position,velocity,acceleration,jerk);
trajectory.time_s=time;
trajectory.position_m=position;
trajectory.live_takeoff_duration_s=takeoffDurationS;
trajectory.formal_task_duration_s=double(reference.global_time_s(end));
trajectory.source_is_parent_control_output=false;
end

function parameters=frozenContactParameters()
parameters=struct('static_deflection_m',0.035,'damping_ratio',0.90, ...
    'maximum_deflection_m',0.060, ...
    'smooth_force_fraction_of_weight',0.02, ...
    'bump_stop_stiffness_multiplier',10.0, ...
    'damping_engagement_depth_fraction_of_static_deflection',1.0, ...
    'provenance','V7_CONTINUOUS_CONTACT_ACCEPTED_MECHANISM');
end

function value=ternary(condition,yes,no)
if condition,value=yes;else,value=no;end
end

function rotation=quaternionRotation(q)
q=double(q(:));q=q/max(norm(q),1e-15);
w=q(1);x=q(2);y=q(3);z=q(4);
rotation=[1-2*(y*y+z*z),2*(x*y-z*w),2*(x*z+y*w); ...
    2*(x*y+z*w),1-2*(x*x+z*z),2*(y*z-x*w); ...
    2*(x*z-y*w),2*(y*z+x*w),1-2*(x*x+y*y)];
end
