classdef LiveBoardState < handle
    %LIVEBOARDSTATE Atomic PX4 estimate/actuator state for MATLAB HIL.

    properties (SetAccess=private)
        UID (1,1) string
        SystemID (1,1) double
        ComponentID (1,1) double
        BootGeneration (1,1) double
        Armed (1,1) logical = false
        ArmTransitions (1,1) uint64 = uint64(0)
        Mode (1,1) string = "UNKNOWN"
        LandedState (1,1) double = -1
        LastHeartbeatNs (1,1) double = 0
        OdometryGeneration (1,1) uint64 = uint64(100)
        ActuatorGeneration (1,1) uint64 = uint64(0)
        OdometryQueue (1,:) cell = cell(1,0)
        ActuatorQueue (1,:) cell = cell(1,0)
        CommandAcks (1,:) cell = cell(1,0)
        StatusText (1,:) cell = cell(1,0)
    end

    properties (Constant)
        MaximumStreamAgeNs = 100000000
        TaskOriginNedM = [-34.518;-75.710;0]
        MaximumQueue = 512
    end

    methods
        function obj=LiveBoardState(uid,systemId,componentId,bootGeneration)
            obj.UID=string(uid);obj.SystemID=double(systemId);
            obj.ComponentID=double(componentId);
            obj.BootGeneration=double(bootGeneration);
        end

        function accept(obj,message,rxNs,statusPoller)
            arguments
                obj
                message
                rxNs (1,1) double {mustBeFinite,mustBeNonnegative}
                statusPoller=[]
            end
            name=gpenmpcNative.MavlinkSerialLink.messageName(message);
            if name=="SERIAL_CONTROL"
                if double(message.SystemID)==obj.SystemID&&~isempty(statusPoller)
                    statusPoller.accept(message,rxNs);
                end
                return
            end
            if double(message.SystemID)~=obj.SystemID,return,end
            payload=message.Payload;
            switch name
                case "HEARTBEAT"
                    observed=bitand(uint8(payload.base_mode),uint8(128))~=0;
                    if observed&&~obj.Armed
                        obj.ArmTransitions=obj.ArmTransitions+uint64(1);
                    end
                    obj.Armed=observed;
                    obj.Mode=gpenmpcNative.MavlinkSerialLink.modeName( ...
                        payload.custom_mode);
                    obj.LastHeartbeatNs=rxNs;
                case "EXTENDED_SYS_STATE"
                    obj.LandedState=double(payload.landed_state);
                case "ODOMETRY"
                    q=double(payload.q(:));
                    localPosition=double([payload.x;payload.y;payload.z]);
                    position=localPosition+obj.TaskOriginNedM;
                    core=[position;double([payload.vx;payload.vy;payload.vz]); ...
                        q;double([payload.rollspeed;payload.pitchspeed;payload.yawspeed])];
                    if double(payload.frame_id)~=1 ...
                            ||double(payload.child_frame_id)~=1 ...
                            ||double(payload.estimator_type)~=8 ...
                            ||~all(isfinite(core))||abs(norm(q)-1)>1e-5
                        return
                    end
                    obj.OdometryGeneration=obj.OdometryGeneration+uint64(1);
                    sample=struct( ...
                        'source','PX4_EKF2_MAVLINK_ODOMETRY_331', ...
                        'atomic_estimate',true,'plant_truth_used',false, ...
                        'uid',obj.UID,'system_id',obj.SystemID, ...
                        'component_id',obj.ComponentID, ...
                        'boot_generation',obj.BootGeneration, ...
                        'sample_timestamp_ns',double(payload.time_usec)*1000, ...
                        'odometry_reset_counter',double(payload.reset_counter), ...
                        'odometry_frame_id',double(payload.frame_id), ...
                        'odometry_child_frame_id',double(payload.child_frame_id), ...
                        'odometry_estimator_type',double(payload.estimator_type), ...
                        'position_ned_m',position, ...
                        'velocity_ned_mps',double([payload.vx;payload.vy;payload.vz]), ...
                        'quaternion_wxyz_body_to_ned',q, ...
                        'omega_frd_rad_s',double([payload.rollspeed; ...
                            payload.pitchspeed;payload.yawspeed]), ...
                        'position_rx_ns',rxNs,'attitude_rx_ns',rxNs, ...
                        'rates_rx_ns',rxNs, ...
                        'position_generation',double(obj.OdometryGeneration), ...
                        'attitude_generation',double(obj.OdometryGeneration), ...
                        'rates_generation',double(obj.OdometryGeneration), ...
                        'position_valid',true,'attitude_valid',true, ...
                        'rates_valid',true);
                    obj.OdometryQueue{end+1}=sample;
                    obj.OdometryQueue=obj.trim(obj.OdometryQueue);
                case "HIL_ACTUATOR_CONTROLS"
                    controls=double(payload.controls(:));
                    if numel(controls)~=16||~all(isfinite(controls(1:6))),return,end
                    controls(~isfinite(controls))=0;
                    obj.ActuatorGeneration=obj.ActuatorGeneration+uint64(1);
                    observed=struct('mavpackettype','HIL_ACTUATOR_CONTROLS', ...
                        'time_usec',double(payload.time_usec), ...
                        'controls',controls,'src_system',double(message.SystemID), ...
                        'src_component',double(message.ComponentID),'rx_ns',rxNs, ...
                        'observation_generation',double(obj.ActuatorGeneration));
                    obj.ActuatorQueue{end+1}=observed;
                    obj.ActuatorQueue=obj.trim(obj.ActuatorQueue);
                case "COMMAND_ACK"
                    obj.CommandAcks{end+1}=struct('rx_ns',rxNs, ...
                        'command',double(payload.command), ...
                        'result',double(payload.result), ...
                        'progress',double(payload.progress), ...
                        'result_param2',double(payload.result_param2), ...
                        'target_system',double(payload.target_system), ...
                        'target_component',double(payload.target_component));
                case "STATUSTEXT"
                    obj.StatusText{end+1}=struct('rx_ns',rxNs, ...
                        'severity',double(payload.severity), ...
                        'text',gpenmpcNative.MavlinkSerialLink.cleanText(payload.text));
            end
        end

        function sample=newestOdometry(obj,nowNs)
            assert(~isempty(obj.OdometryQueue), ...
                'gpenmpcNative:LiveBoardOdometryAbsent','ODOMETRY was not observed.');
            sample=obj.OdometryQueue{end};
            assert(nowNs-sample.position_rx_ns<=obj.MaximumStreamAgeNs, ...
                'gpenmpcNative:LiveBoardOdometryStale','ODOMETRY is stale.');
        end

        function sample=odometryAfter(obj,previousTimestampNs,nowNs)
            while ~isempty(obj.OdometryQueue) ...
                    &&obj.OdometryQueue{1}.sample_timestamp_ns<=previousTimestampNs
                obj.OdometryQueue(1)=[];
            end
            assert(~isempty(obj.OdometryQueue), ...
                'gpenmpcNative:LiveBoardNextOdometryAbsent', ...
                'The next ODOMETRY sample was not observed.');
            sample=obj.OdometryQueue{1};obj.OdometryQueue(1)=[];
            dtNs=sample.sample_timestamp_ns-previousTimestampNs;
            assert(dtNs>0&&dtNs<=10000100&&abs(dtNs-10000000)<=500, ...
                'gpenmpcNative:LiveBoardOdometryInterval', ...
                'ODOMETRY interval is not the frozen 10 ms identity: %.0f ns.',dtNs);
            assert(nowNs-sample.position_rx_ns<=obj.MaximumStreamAgeNs, ...
                'gpenmpcNative:LiveBoardNextOdometryStale', ...
                'The next ODOMETRY sample is stale.');
        end

        function value=actuatorAfter(obj,previousGeneration,physicalGeneration,nowNs)
            while ~isempty(obj.ActuatorQueue) ...
                    &&obj.ActuatorQueue{1}.observation_generation<=previousGeneration
                obj.ActuatorQueue(1)=[];
            end
            assert(~isempty(obj.ActuatorQueue), ...
                'gpenmpcNative:LiveBoardNextActuatorAbsent', ...
                'The next virtual actuator output was not observed.');
            value=obj.ActuatorQueue{1};obj.ActuatorQueue(1)=[];
            assert(nowNs-value.rx_ns<=obj.MaximumStreamAgeNs, ...
                'gpenmpcNative:LiveBoardNextActuatorStale', ...
                'The next actuator output is stale.');
            value.generation=double(physicalGeneration);
        end

        function generation=latestActuatorGeneration(obj)
            if isempty(obj.ActuatorQueue)
                generation=double(obj.ActuatorGeneration);
            else
                generation=obj.ActuatorQueue{end}.observation_generation;
            end
        end

        function setInitialHeartbeat(obj,message,rxNs,landedState)
            obj.accept(message,rxNs,[]);
            obj.LandedState=double(landedState);
        end

        function status=snapshot(obj)
            status=struct('uid',obj.UID,'system_id',obj.SystemID, ...
                'component_id',obj.ComponentID,'boot_generation',obj.BootGeneration, ...
                'armed',obj.Armed,'arm_transitions',double(obj.ArmTransitions), ...
                'mode',obj.Mode,'landed_state',obj.LandedState, ...
                'last_heartbeat_ns',obj.LastHeartbeatNs, ...
                'odometry_generation',double(obj.OdometryGeneration), ...
                'actuator_generation',double(obj.ActuatorGeneration), ...
                'odometry_queue',numel(obj.OdometryQueue), ...
                'actuator_queue',numel(obj.ActuatorQueue));
        end
    end

    methods (Access=private)
        function value=trim(obj,value)
            if numel(value)>obj.MaximumQueue
                value=value(end-obj.MaximumQueue+1:end);
            end
        end
    end
end
