function bundle=loadRflyCanonicalDeliveryTask(taskPath,taskSha256)
% Load the five-leg task with the canonical sampled-jet evaluator.
% The live owner supplies causal phase and verified ground-service events.
arguments
    taskPath (1,1) string
    taskSha256 (1,1) string
end
distributionRoot=fileparts(fileparts(fileparts(fileparts(fileparts(mfilename('fullpath'))))));
canonical=fullfile(distributionRoot,'assets','canonical','method_source', ...
    'matlab','comparison','gpenmpcSampledC3Trajectory.m');
canonicalSha='8E1B1DBE5E224E7047252399C51E235DDCA8685B58185A85ACBE43370207FF1B';
assert(strcmpi(sha(taskPath),taskSha256),'gpenmpcNative:DeliveryTaskIdentity', ...
    'The saved physical-task bytes differ.');
assert(strcmpi(sha(canonical),canonicalSha),'gpenmpcNative:DeliveryTrajectoryImplementation', ...
    'Use the canonical whole-task sampled C3 jet implementation.');
addpath(fileparts(canonical),'-begin');
assert(strcmpi(which('gpenmpcSampledC3Trajectory'),canonical), ...
    'gpenmpcNative:DeliveryTrajectoryShadow','Another trajectory implementation shadows the canonical function.');
q=load(taskPath,'physicalTask','timeline');
assert(all(isfield(q,{'physicalTask','timeline'})), ...
    'gpenmpcNative:DeliveryTaskSchema','Both original task and service timeline are required.');
t=q.physicalTask;tl=q.timeline;r=t.reference;m=t.execution_method_binding;
assert(strcmp(m.architecture,'A1_COORDINATED_PHYSICAL') ...
    &&strcmpi(m.effective_configuration_payload_sha256, ...
        'A859433D0AA774013341444A4B9AE971A34F12B4FB89C0A004B2CB3E013FCEBA') ...
    &&strcmpi(m.gp_model_sha256, ...
        '4A09E9A3D4818B5555CD3439A6D2133026EEA0FDC2774A1FB17F9E05486E5BB2') ...
    &&t.parent_control_injection_prohibited&&t.parent_state_injection_prohibited, ...
    'gpenmpcNative:DeliveryMethod','The canonical physical delivery task is required.');
origin=double(tl.local_ground_origin_xyz_up_m(:));
assert(numel(origin)==3&&all(isfinite(origin))&&origin(3)==0, ...
    'gpenmpcNative:DeliveryFrame','The task-declared fixed ground origin is required, not a measured plant state.');
assert(isequal(unique(r.leg_index,'stable').',1:5)&&numel(t.plans(1).legs)==5 ...
    &&numel(tl.service_records)==4&&t.physical_service.delivery_count==4 ...
    &&t.physical_service.ground_dwell_s==8, ...
    'gpenmpcNative:DeliveryLegs','The same five flights and four ground services are required.');
assert(r.global_time_s(1)==0&&all(diff(r.global_time_s)>0) ...
    &&abs(r.global_time_s(end)-tl.task_end_s)<1e-9 ...
    &&abs(t.mission_config.simulation.sample_period_s-.01)<1e-12, ...
    'gpenmpcNative:DeliveryTime','The complete saved task and original sample period are required.');
legs=cell(5,1);records=cell(5,1);
for k=1:5
    ix=find(r.leg_index==k);local=double(r.local_time_s(ix));
    assert(all(diff(ix)==1)&&local(1)==0&&all(diff(local)>0) ...
        &&max(abs(local-(r.global_time_s(ix)-r.global_time_s(ix(1)))))<1e-10, ...
        'gpenmpcNative:DeliveryLegTime','Leg rows must remain contiguous and retain their exact time origin.');
    payload=double(t.plans(1).legs(k).payload_departure_kg);
    assert(all(r.payload_kg(ix)==payload), ...
        'gpenmpcNative:DeliveryPayload','No payload change is permitted inside one flight leg.');
    position=double(r.position_m(ix,:))-origin.';
    jets={position,double(r.velocity_mps(ix,:)),double(r.acceleration_mps2(ix,:)),double(r.jerk_mps3(ix,:))};
    trajectory=gpenmpcSampledC3Trajectory(local,jets{:});
    meta=struct('leg_index',k,'source_first_row',ix(1),'source_last_row',ix(end), ...
        'source_row_count',numel(ix),'saved_global_start_s',r.global_time_s(ix(1)), ...
        'saved_global_end_s',r.global_time_s(ix(end)), ...
        'trajectory_duration_s',trajectory.total_duration_s,'payload_kg',payload, ...
        'initial_position_up_m',position(1,:),'initial_velocity_mps',jets{2}(1,:), ...
        'initial_acceleration_mps2',jets{3}(1,:),'initial_jerk_mps3',jets{4}(1,:), ...
        'planned_descent_start_phase_s',NaN, ...
        'saved_leg_end_phase_s',trajectory.total_duration_s, ...
        'actual_native_land_handoff_owner','EXISTING_CAUSAL_DELIVERY_LIFECYCLE_NOT_SAVED_TIME_ALONE', ...
        'native_land_is_independent_of_trajectory_completion',true, ...
        'ground_rows_are_not_armed_control_evidence',true);
    if k<=4
        service=tl.service_records(k);
        meta.planned_descent_start_phase_s=double(service.retimed_window_start_s)-meta.saved_global_start_s;
        meta.saved_service_start_s=double(service.retimed_window_start_s);
        meta.saved_service_end_s=double(service.retimed_window_end_s);
        meta.ground_dwell_s=double(service.ground_dwell_s);
        assert(meta.planned_descent_start_phase_s>=0 ...
            &&meta.planned_descent_start_phase_s<=trajectory.total_duration_s ...
            &&meta.ground_dwell_s==8,'gpenmpcNative:DeliveryHandoff','Saved service boundary is outside its actual leg.');
    end
    legs{k}=struct('trajectory',trajectory,'source_indices',ix,'local_time_s',local, ...
        'position_up_m',position,'velocity_mps',jets{2},'acceleration_mps2',jets{3}, ...
        'jerk_mps3',jets{4},'phase_code',r.phase_code(ix),'meta',meta);
    records{k}=meta;
end
payloadChanges=find(diff(r.payload_kg)~=0)+1;
assert(numel(payloadChanges)==4&&all(r.phase_code(payloadChanges)==12), ...
    'gpenmpcNative:DeliveryGroundPayload','Saved unloading must occur only at the four post-ground ascent boundaries.');
receipt=struct('schema','RFLY_CANONICAL_DELIVERY_REFERENCE_BINDING_V1', ...
    'task_path',char(taskPath),'task_sha256',char(upper(taskSha256)), ...
    'canonical_trajectory_source',canonical,'canonical_trajectory_sha256',canonicalSha, ...
    'trajectory_semantics','SAME_CANONICAL_INDEPENDENT_LINEAR_INTERPOLATION_OF_SAVED_P_V_A_J', ...
    'derivative_arrays_refitted',false,'reference_resampled',false, ...
    'fixed_task_ground_origin_up_m',origin.','frame_change','CONSTANT_POSITION_TRANSLATION_ONLY__VELOCITY_ACCELERATION_JERK_UNCHANGED', ...
    'board_origin_source','MUST_BE_ORIGINAL_REGISTERED_BOARD_ESTIMATOR_ORIGIN_NOT_PLANT_TRUTH', ...
    'source_row_count',numel(r.global_time_s),'saved_task_duration_s',double(tl.task_end_s), ...
    'legs',{records},'physical_ground_services',4,'payload_change_rows',payloadChanges, ...
    'phase_clock_owner','EXISTING_CANONICAL_OUTER_ADAPTER__NOT_WALL_TIME_OR_PLANT_TRUTH', ...
    'service_clock_owner','EXISTING_DUAL_GROUND_STANDARD_DISARM_DWELL_PAYLOAD_ACK_LIFECYCLE', ...
    'new_session_per_ground_service_required',true,'initial_takeoff_lifecycle_binding_complete',false, ...
    'live_integration_proven',false,'hardware_actions',0,'solver_calls',0,'plant_instances',0);
bundle=struct('task',t,'timeline',tl,'legs',{legs},'receipt',receipt);
end
function value=sha(p)
f=fopen(p,'rb');assert(f>=0,'gpenmpcNative:DeliveryInputMissing','Missing input %s',p);
c=onCleanup(@()fclose(f));b=fread(f,Inf,'*uint8');clear c
d=java.security.MessageDigest.getInstance('SHA-256');d.update(typecast(b,'int8'));
value=upper(reshape(dec2hex(typecast(d.digest(),'uint8'),2).',1,[]));
end
