function [snapshot,receipt]=makeLocalCommittedOuterSnapshot(assets,trajectory,warmStart,source,committed,inputs,registered,nowNs,maxAgeNs,dynamicOnly)
% Map retained source, RLC and input records to an eNMPC observation.
% The owner verifies record provenance; this adapter checks consistency.
% Retain post-commit state and original source age.
if nargin<10,dynamicOnly=false;end
assert(islogical(dynamicOnly)&&isscalar(dynamicOnly));
assert(isa(nowNs,'uint64')&&isa(maxAgeNs,'uint64')&&maxAgeNs>0);
s=sourceObservation(source);
held=isstruct(inputs)&&isfield(inputs,'held_input_bytes');
inputSource=s;
if held
    assert(~isempty(committed),'gpenmpcNative:LocalOuterHeldBootstrap');
    inputSource=sourceObservation(inputs.original_input_source);
    if isfield(inputs,'held_input_decoded')
        % Compare all bytes with the successful same-IO send's decoded command.
        u=inputs.held_input_decoded;
        assert(isequal(u.original_bytes,inputs.held_input_bytes(:)), ...
            'gpenmpcNative:LocalOuterRetainedInput','Retained send parse differs from the original input.');
    else
        u=gpenmpcNative.RflyLocalTaskCodec.decode(inputs.held_input_bytes);
    end
    assert(inputSource.original_sample_us<=s.original_sample_us ...
        &&s.original_sample_us-inputSource.original_sample_us<=uint64(100000) ...
        &&inputSource.reset_counter==s.reset_counter,'gpenmpcNative:LocalOuterHeldInputAge');
elseif isstruct(inputs)
    u=gpenmpcNative.RflyLocalTaskCodec.originalNumericalObservation(inputs,source.message,source.original_host_receive_ns,registered);
else
    u=gpenmpcNative.RflyLocalTaskCodec.decode(inputs);
end
assert(isequal(s.identity,registered.identity)&&isequal(inputSource.identity,s.identity)&&isequal(u.source.identity,s.identity) ...
    &&u.source.source_generation==inputSource.source_generation&&u.source.sample_us==inputSource.original_sample_us ...
    &&isequal(u.original_sensor52,inputSource.original_sensor52)&&u.leg_index==registered.leg_index ...
    &&strcmpi(hex(u.execution_session_sha256),registered.execution_session_sha256) ...
    &&strcmpi(hex(u.task_sha256),registered.task_sha256) ...
    &&strcmpi(hex(u.configuration_sha256),assets.configurationBinding.effective_configuration_payload_sha256), ...
    'gpenmpcNative:LocalOuterInputBinding','Actual same-session source/task inputs required.');
assert(nowNs>=source.original_host_receive_ns&&nowNs-source.original_host_receive_ns<=maxAgeNs, ...
    'gpenmpcNative:LocalOuterSourceAge','Do not renew an old board source with a new HOST time.');
x=s.canonical_state13;first=isempty(committed);
if first
    % Use the WholeTask new-leg initializer.
    force=(assets.profile.mass_properties.base_mass_kg+u.payload.payload_kg).*[0;0;9.80665];
    command=u.rotor.original_observation.observed_thrust_n;
    outer=zeros(3,1);vertical=0;residual=zeros(3,1);agreement=zeros(3,1);blend=0;filtered=zeros(3,1);causalValid=false;
    phase=struct('progress_s',0,'progress_rate',1,'previous_phase_acceleration_s_inv',0);
    gp=struct('available',false,'prediction_sample_closed',false,'observed_innovation_available',false,'hard_invalid',false,'trust',0);
    commitGen=uint64(0);commitHash='';
else
    if isfield(committed,'decoded')&&~isempty(committed.decoded)
        c=committed.decoded;
        assert(isequal(c.original_bytes,committed.message(:)) ...
            &&isequal(c.original_host_receive_ns,committed.original_host_receive_ns), ...
            'gpenmpcNative:LocalOuterRetainedCommit','Retained same-IO parse lost its exact original bytes/time.');
    else
        c=gpenmpcNative.RflyLocalCommittedDecoder(committed.message,committed.original_host_receive_ns);
    end
    if held,assert(c.outer_generation==u.outer.generation,'gpenmpcNative:LocalOuterHeldCommand');end
    assert(isequal(c.identity,s.identity)&&c.source_generation==s.source_generation ...
        &&c.source_timestamp_ns==s.original_sample_us*uint64(1000)&&c.leg_index==u.leg_index ...
        &&strcmpi(hex(c.configuration_sha256),hex(u.configuration_sha256)) ...
        &&strcmpi(hex(c.reference_asset_sha256),registered.reference_asset_sha256) ...
        &&ismember(c.state_kind,uint8(2:4))&&nowNs>=committed.original_host_receive_ns ...
        &&nowNs-committed.original_host_receive_ns<=maxAgeNs, ...
        'gpenmpcNative:LocalOuterCommitBinding','Only a matching actual joint-installed C state may feed the outer solver.');
    v=c.state64;
    force=v(61:63);command=v(55:60);outer=c.reference6(4:6);
    vertical=v(7);residual=v(48:50);agreement=v(51:53);blend=v(23);filtered=v(24:26);
    assert(v(54)==0||v(54)==1);causalValid=logical(v(54));
    phase=struct('progress_s',c.installed_phase2(1),'progress_rate',c.installed_phase2(2), ...
        'previous_phase_acceleration_s_inv',c.reference6(3));
    gp=c.closed_gp_evidence;commitGen=c.source_generation;commitHash=hex(c.committed_state_sha256);
end
assert(all(isfinite([force;command;outer;vertical;residual;agreement;blend;filtered])) ...
    &&all(command>=0)&&all(agreement>=0&agreement<=1)&&blend>=0&&blend<=1 ...
    &&phase.progress_s>=0&&phase.progress_s<=trajectory.total_duration_s ...
    &&phase.progress_rate>=assets.enmpc.phase_rate_min&&phase.progress_rate<=assets.enmpc.phase_rate_max);
observation=struct('position_m',x(1:3),'velocity_mps',x(4:6),'quaternion_wxyz',x(7:10),'body_rate_rad_s',x(11:13), ...
    'previous_desired_force_n',force,'previous_rotor_command_n',command, ...
    'previous_outer_acceleration_correction_i_mps2',outer,'runtime_vertical_observer_shadow_i_mps2',[0;0;-vertical], ...
    'wind_estimate_xy_mps',u.wind.estimate_xy_mps,'payload_kg',u.payload.payload_kg, ...
    'corridor_half_width_m',assets.enmpc.corridor_half_width_m);
causal=struct('valid',causalValid,'values',[gpenmpcNormalizedTotalRotorCommand(command,u.payload.payload_kg);residual], ...
    'runtime_gp_axis_weight_f',agreement,'runtime_gp_responsibility_blend',blend,'runtime_gp_filtered_mean_f_mps2',filtered);
% Original worker uses double ns. Refuse lossy conversion instead of changing
% the underlying epoch or silently discarding original uint64 timestamps.
assert(source.original_host_receive_ns<=uint64(flintmax));
snapshot=struct('snapshot_timestamp_ns',double(source.original_host_receive_ns), ...
    'configuration_payload_sha256',assets.configurationBinding.effective_configuration_payload_sha256, ...
    'warm_start',double(warmStart),'phase',phase, ...
    'observation',observation,'causal',causal,'gp_evidence',gp, ...
    'estimate_source','ACTUAL_RLS1_MATCHED_LOCAL_C_COMMIT','task_identity_sha256',registered.task_sha256, ...
    'plant_truth_used',false,'hardware_actions',0);
if ~dynamicOnly
    snapshot.source_root=assets.sourceRoot;snapshot.config=assets.enmpc;
    snapshot.context=assets.prediction_context;snapshot.gp_model=assets.gp_model;snapshot.trajectory=trajectory;
end
receipt=struct('schema','LOCAL_COMMITTED_OUTER_OBSERVATION_V1','source_generation',s.source_generation, ...
    'source_timestamp_ns',s.original_sample_us*uint64(1000),'original_host_source_receive_ns',source.original_host_receive_ns, ...
    'committed_generation',commitGen,'committed_state_sha256',commitHash,'first_explicit_leg_initializer',first, ...
    'next_open_GP_used',false,'host_inner_or_plant_step',false,'no_retimestamp',true, ...
    'boundary','Actual post-commit source-aged HIL observation; not zero-delay software lockstep equivalence.');
receipt.slow_input_source_generation=inputSource.source_generation;
receipt.valid_held_slow_input=held;
end
function s=sourceObservation(source)
% Reuse the decoded value supplied by takeCanonical after digest and binding checks.
% Decode raw-only fixtures independently without replacing the fast-source cache.
if isfield(source,'decoded')&&~isempty(source.decoded)
    s=source.decoded;
    assert(isequal(s.original_bytes,source.message(:)) ...
        &&isequal(s.original_host_receive_ns,source.original_host_receive_ns), ...
        'gpenmpcNative:LocalOuterRetainedSource','Retained same-IO parse lost its exact original bytes/time.');
else
    s=gpenmpcNative.RflyLocalSnapshotDecoder(source.message,source.original_host_receive_ns);
end
end
function s=hex(b),s=upper(reshape(dec2hex(b,2).',1,[]));end
