function [snapshot,accepted,reason,receipt] = makeBoardOuterSnapshot( ...
        workRoot, px4Sample, expected, nowNs, runtime, trajectory, phase, warmStart, verifiedAssets)
% Build an outer-solver snapshot from causal board and interface observations.
% Preverified assets avoid per-sample file IO; otherwise load the canonical entry.
% The caller owns the first-snapshot latch and committed-inner counter.

snapshot = struct;
accepted = false;
reason = "MALFORMED_BOARD_OUTER_RUNTIME";
receipt = struct('status',"REJECTED",'reason',reason,'hardware_actions',0);

requiredExpected = {'maximum_runtime_age_ns','task_identity_sha256', ...
    'outer_snapshot_leg_index','outer_snapshot_first_in_leg', ...
    'last_committed_inner_generation'};
if ~isstruct(expected) || ~isscalar(expected) ...
        || ~all(isfield(expected,requiredExpected)) ...
        || ~finiteScalar(expected.maximum_runtime_age_ns) ...
        || expected.maximum_runtime_age_ns <= 0 ...
        || ~shaScalar(expected.task_identity_sha256) ...
    || ~nonnegativeInteger(expected.outer_snapshot_leg_index) ...
    || expected.outer_snapshot_leg_index < 1 ...
    || ~logicalScalar(expected.outer_snapshot_first_in_leg) ...
    || ~nonnegativeInteger(expected.last_committed_inner_generation)
    reason = "INVALID_EXPLICIT_RUNTIME_BOUNDARY";
    receipt.reason = reason;
    return
end

[x13,estimateAccepted,estimateReason] = ...
    gpenmpcNative.px4EstimateState(px4Sample,expected,nowNs);
if ~estimateAccepted
    reason = "PX4_ESTIMATE_REJECTED__" + string(estimateReason);
    receipt.reason = reason;
    return
end

requiredRuntime = {'schema','task_identity_sha256','plant_truth_used', ...
    'virtual_actuator','outer','wind','task'};
if ~isstruct(runtime) || ~isscalar(runtime) ...
        || ~all(isfield(runtime,requiredRuntime)) ...
        || string(runtime.schema) ~= "GPENMPC_LIVE_OUTER_RUNTIME_V1" ...
        || ~islogical(runtime.plant_truth_used) ...
        || ~isscalar(runtime.plant_truth_used) || runtime.plant_truth_used ...
        || ~shaScalar(runtime.task_identity_sha256) ...
        || ~strcmpi(string(runtime.task_identity_sha256), ...
            string(expected.task_identity_sha256))
    reason = "RUNTIME_IDENTITY_OR_TRUTH_ISOLATION_REJECTED";
    receipt.reason = reason;
    return
end

[okActuator,actuatorReason] = validateStamped(runtime.virtual_actuator, ...
    "HOST_M600_VIRTUAL_ACTUATOR_INTERFACE",nowNs, ...
    expected.maximum_runtime_age_ns);
[okOuter,outerReason] = validateStamped(runtime.outer, ...
    "HOST_CAUSAL_RUNTIME",nowNs,expected.maximum_runtime_age_ns);
[okWind,windReason] = validateStamped(runtime.wind, ...
    "FROZEN_TASK_WIND_ESTIMATOR",nowNs,expected.maximum_runtime_age_ns);
if ~(okActuator && okOuter && okWind)
    reason = "STALE_OR_INVALID_RUNTIME_SOURCE__" + ...
        actuatorReason + "__" + outerReason + "__" + windReason;
    receipt.reason = reason;
    return
end

actuator = runtime.virtual_actuator;
outer = runtime.outer;
wind = runtime.wind;
task = runtime.task;
requiredActuator = {'ordering','rotor_command_n','thrust_effectiveness'};
requiredOuter = {'previous_outer_acceleration_correction_i_mps2', ...
    'runtime_vertical_observer_shadow_i_mps2','residual_history_f_mps2', ...
    'runtime_gp_axis_weight_f','runtime_gp_responsibility_blend', ...
    'runtime_gp_filtered_mean_f_mps2','causal_valid','gp_evidence', ...
    'previous_desired_force_projected_n','desired_force_source', ...
    'desired_force_generation'};
requiredWind = {'estimate_xy_mps'};
requiredTask = {'source','payload_kg','corridor_half_width_m','leg_index'};
if ~all(isfield(actuator,requiredActuator)) ...
        || string(actuator.ordering) ~= "SOFTWARE_M600_ORDER" ...
        || ~all(isfield(outer,requiredOuter)) ...
        || ~all(isfield(wind,requiredWind)) ...
        || ~all(isfield(task,requiredTask)) ...
        || string(task.source) ~= "FROZEN_GPENMPC_TASK_STATE" ...
    || ~nonnegativeInteger(task.leg_index) || task.leg_index < 1 ...
    || task.leg_index ~= expected.outer_snapshot_leg_index
    reason = "RUNTIME_SCHEMA_OR_SOURCE_REJECTED";
    receipt.reason = reason;
    return
end

rotor = actuator.rotor_command_n;
effectiveness = actuator.thrust_effectiveness;
if ~finiteVector(rotor,6) || any(rotor(:) < 0) ...
        || ~finiteVector(effectiveness,6) || any(effectiveness(:) <= 0) ...
        || ~finiteVector(outer.previous_outer_acceleration_correction_i_mps2,3) ...
        || ~finiteVector(outer.runtime_vertical_observer_shadow_i_mps2,3) ...
        || ~finiteVector(outer.residual_history_f_mps2,3) ...
        || ~finiteVector(outer.runtime_gp_axis_weight_f,3) ...
        || any(outer.runtime_gp_axis_weight_f(:) < 0) ...
        || any(outer.runtime_gp_axis_weight_f(:) > 1) ...
        || ~finiteScalar(outer.runtime_gp_responsibility_blend) ...
        || outer.runtime_gp_responsibility_blend < 0 ...
        || outer.runtime_gp_responsibility_blend > 1 ...
        || ~finiteVector(outer.runtime_gp_filtered_mean_f_mps2,3) ...
        || ~(islogical(outer.causal_valid) && isscalar(outer.causal_valid)) ...
        || ~finiteVector(wind.estimate_xy_mps,2) ...
        || ~finiteScalar(task.payload_kg) || task.payload_kg < 0 ...
        || ~finiteScalar(task.corridor_half_width_m) ...
        || task.corridor_half_width_m <= 0
    reason = "NONFINITE_OR_OUT_OF_DOMAIN_RUNTIME_VALUE";
    receipt.reason = reason;
    return
end

evidence = outer.gp_evidence;
requiredEvidence = {'available','prediction_sample_closed', ...
    'observed_innovation_available','hard_invalid','trust'};
if ~isstruct(evidence) || ~isscalar(evidence) ...
        || ~all(isfield(evidence,requiredEvidence)) ...
        || ~logicalScalar(evidence.available) ...
        || ~logicalScalar(evidence.prediction_sample_closed) ...
        || ~logicalScalar(evidence.observed_innovation_available) ...
        || ~logicalScalar(evidence.hard_invalid) ...
        || ~finiteScalar(evidence.trust) || evidence.trust < 0 || evidence.trust > 1
    reason = "INVALID_GP_EVIDENCE_RUNTIME";
    receipt.reason = reason;
    return
end

if nargin < 9 || isempty(verifiedAssets)
    if ~textScalar(workRoot) ...
            || ~strcmpi(stripFinalSeparator(string(workRoot)), ...
                canonicalAssetRoot())
        reason = "NONCANONICAL_ASSET_ROOT_REJECTED";
        receipt.reason = reason;
        return
    end
    try
        assets = gpenmpcNative.loadCanonicalAssets(canonicalAssetRoot());
    catch exception
        reason = "CANONICAL_ASSET_LOAD_REJECTED";
        receipt.reason = reason;
        receipt.asset_load_error_identifier = string(exception.identifier);
        return
    end
else
    assets = verifiedAssets;
end
if ~validCanonicalAssets(assets)
    reason = "UNVERIFIED_OR_NONCANONICAL_ASSETS_REJECTED";
    receipt.reason = reason;
    return
end
cfg = assets.enmpc;
allocation = gpenmpcM600Allocation(assets.calibration);
if any(rotor(:) > allocation.per_rotor_upper_n + 1.0e-12)
    reason = "VIRTUAL_ROTOR_COMMAND_EXCEEDS_FROZEN_AUTHORITY";
    receipt.reason = reason;
    return
end
if ~validPhase(phase,cfg) || ~validTrajectory(trajectory) ...
        || ~isnumeric(warmStart) || ~isreal(warmStart) ...
        || ~isrow(warmStart) || numel(warmStart) ~= cfg.decision_dimension ...
        || any(~isfinite(warmStart))
    reason = "INVALID_PHASE_TRAJECTORY_OR_WARM_START";
    receipt.reason = reason;
    return
end

% Use the previous committed nominal force target in the software +Z-up frame.
[forceOk,forceReason,previousDesiredForce] = validateDesiredForce( ...
    outer,expected,task,phase,assets);
if ~forceOk
    reason = forceReason;
    receipt.reason = reason;
    return
end
causalValues = [gpenmpcNormalizedTotalRotorCommand( ...
    double(rotor(:)),double(task.payload_kg)); ...
    double(outer.residual_history_f_mps2(:))];

observation = struct( ...
    'position_m',x13(1:3), ...
    'velocity_mps',x13(4:6), ...
    'quaternion_wxyz',x13(7:10), ...
    'body_rate_rad_s',x13(11:13), ...
    'previous_desired_force_n',previousDesiredForce, ...
    'previous_rotor_command_n',double(rotor(:)), ...
    'previous_outer_acceleration_correction_i_mps2', ...
        double(outer.previous_outer_acceleration_correction_i_mps2(:)), ...
    'runtime_vertical_observer_shadow_i_mps2', ...
        double(outer.runtime_vertical_observer_shadow_i_mps2(:)), ...
    'wind_estimate_xy_mps',double(wind.estimate_xy_mps(:)), ...
    'payload_kg',double(task.payload_kg), ...
    'corridor_half_width_m',double(task.corridor_half_width_m));
causal = struct('valid',logical(outer.causal_valid), ...
    'values',causalValues, ...
    'runtime_gp_axis_weight_f',double(outer.runtime_gp_axis_weight_f(:)), ...
    'runtime_gp_responsibility_blend', ...
        double(outer.runtime_gp_responsibility_blend), ...
    'runtime_gp_filtered_mean_f_mps2', ...
        double(outer.runtime_gp_filtered_mean_f_mps2(:)));
snapshot = struct('source_root',assets.sourceRoot, ...
    'snapshot_timestamp_ns',double(nowNs), ...
    'configuration_payload_sha256', ...
        assets.configurationBinding.effective_configuration_payload_sha256, ...
    'config',cfg,'warm_start',double(warmStart), ...
    'trajectory',trajectory,'phase',phase,'observation',observation, ...
    'context',assets.prediction_context,'gp_model',assets.gp_model, ...
    'causal',causal,'gp_evidence',evidence, ...
    'estimate_source',string(px4Sample.source), ...
    'task_identity_sha256',upper(string(runtime.task_identity_sha256)), ...
    'plant_truth_used',false,'hardware_actions',0);
accepted = true;
reason = "FRESH_CAUSAL_BOARD_OUTER_SNAPSHOT";
receipt = struct('status',"PASS",'reason',reason, ...
    'estimate_source',string(px4Sample.source), ...
    'task_identity_sha256',upper(string(runtime.task_identity_sha256)), ...
    'estimate_generations',[double(px4Sample.position_generation), ...
        double(px4Sample.attitude_generation),double(px4Sample.rates_generation)], ...
    'estimate_rx_ns',[double(px4Sample.position_rx_ns), ...
        double(px4Sample.attitude_rx_ns),double(px4Sample.rates_rx_ns)], ...
    'virtual_actuator_generation',double(actuator.generation), ...
    'outer_runtime_generation',double(outer.generation), ...
    'wind_generation',double(wind.generation), ...
    'wind_observation',wind, ...
    'virtual_actuator_rx_ns',double(actuator.rx_ns), ...
    'wind_rx_ns',double(wind.rx_ns), ...
    'outer_runtime_rx_ns',double(outer.rx_ns), ...
    'previous_force_source',string(outer.desired_force_source), ...
    'previous_force_generation',double(outer.desired_force_generation), ...
    'first_outer_snapshot_in_leg',logical(expected.outer_snapshot_first_in_leg), ...
    'leg_index',double(task.leg_index), ...
    'assets_preverified',nargin >= 9 && ~isempty(verifiedAssets), ...
    'plant_truth_used',false,'hardware_actions',0);
end

function [ok,reason] = validateStamped(value,expectedSource,nowNs,maxAgeNs)
ok = false;
reason = "INVALID";
required = {'source','rx_ns','generation','valid'};
if ~isstruct(value) || ~isscalar(value) || ~all(isfield(value,required))
    return
end
if string(value.source) ~= expectedSource
    reason = "SOURCE";
    return
end
if ~(islogical(value.valid) && isscalar(value.valid) && value.valid)
    reason = "NOT_VALID";
    return
end
if ~finiteScalar(value.generation) || value.generation < 1 ...
        || value.generation ~= fix(value.generation)
    reason = "GENERATION";
    return
end
if ~finiteScalar(value.rx_ns) || value.rx_ns < 0 || value.rx_ns > nowNs ...
        || nowNs-value.rx_ns > maxAgeNs
    reason = "TIME";
    return
end
ok = true;
reason = "PASS";
end

function ok = validPhase(value,cfg)
required = {'progress_s','progress_rate','previous_phase_acceleration_s_inv'};
ok = isstruct(value) && isscalar(value) && all(isfield(value,required)) ...
    && finiteScalar(value.progress_s) && value.progress_s >= 0 ...
    && finiteScalar(value.progress_rate) ...
    && value.progress_rate >= cfg.phase_rate_min ...
    && value.progress_rate <= cfg.phase_rate_max ...
    && finiteScalar(value.previous_phase_acceleration_s_inv);
end

function ok = validTrajectory(value)
ok = isstruct(value) && isscalar(value) ...
    && isfield(value,'total_duration_s') ...
    && finiteScalar(value.total_duration_s) && value.total_duration_s > 0 ...
    && (isfield(value,'coefficients_ascending') ...
        || (isfield(value,'time_s') && isfield(value,'position_m')));
end

function [ok,reason,force] = validateDesiredForce(outer,expected,task,phase,assets)
ok=false; reason="INVALID_COMMITTED_DESIRED_FORCE"; force=[];
if ~finiteVector(outer.previous_desired_force_projected_n,3) ...
        || ~textScalar(outer.desired_force_source) ...
        || ~nonnegativeInteger(outer.desired_force_generation) ...
        || ~nonnegativeInteger(outer.generation) ...
        || outer.generation <= outer.desired_force_generation
    return
end
generation=double(outer.desired_force_generation);
lastCommitted=double(expected.last_committed_inner_generation);
if generation~=lastCommitted
    reason="DESIRED_FORCE_COMMIT_GENERATION_MISMATCH";
    return
end
force=double(outer.previous_desired_force_projected_n(:));
source=string(outer.desired_force_source);
if expected.outer_snapshot_first_in_leg
    % Independent service-owned first-in-leg boundary: no committed command,
    % zero task progress, initial phase rate and phase acceleration.
    nominalMass=double(assets.profile.mass_properties.base_mass_kg) ...
        +double(task.payload_kg);
    canonicalInitial=nominalMass.*[0;0;9.80665];
    if generation~=0 || source~="CANONICAL_LEG_INITIAL_FORCE" ...
            || phase.progress_s~=0 || phase.progress_rate~=1 ...
            || phase.previous_phase_acceleration_s_inv~=0 ...
            || ~isequal(force,canonicalInitial)
        reason="CANONICAL_LEG_INITIAL_FORCE_BOUNDARY_REJECTED";
        return
    end
else
    expectedSource="COMMITTED_NOMINAL_CONTROLLER_MIRROR";
    if isfield(expected,'inner_control_contract') ...
            &&isequal(string(expected.inner_control_contract),"CANONICAL_FULL_SE3")
        if ~isfield(expected,'full_inner_evidence_scope') ...
                ||~any(string(expected.full_inner_evidence_scope)==["HOST_ONLY_KERNEL_EXECUTION","BOARD_COMMIT_RFC1"])
            reason="FULL_INNER_SNAPSHOT_DEPLOYMENT_NOT_BOUND";return
        end
        expectedSource="COMMITTED_CANONICAL_FULL_SE3_KERNEL_HOST_ONLY";
        if string(expected.full_inner_evidence_scope)=="BOARD_COMMIT_RFC1"
            if ~isfield(outer,'board_commit_consumer')||outer.board_commit_consumer.failed ...
                ||outer.board_commit_consumer.commits<1 ...
                ||~isfield(outer.board_commit_consumer.last_receipt,'source_generation') ...
                ||uint64(generation)~=outer.board_commit_consumer.last_receipt.source_generation
                reason="BOARD_COMMIT_CAUSAL_RECEIPT_MISSING";return
            end
            expectedSource="COMMITTED_CANONICAL_FULL_SE3_KERNEL_BOARD_RFC1";
        end
    end
    if generation<1 || source~=expectedSource
        reason="COMMITTED_NOMINAL_DESIRED_FORCE_SOURCE_REJECTED";
        return
    end
end
ok=true;reason="BOUND_CANONICAL_PREVIOUS_DESIRED_FORCE";
end

function ok=validCanonicalAssets(a)
required={'sourceRoot','enmpc','profile','calibration', ...
    'configurationBinding','prediction_context','gp_model','binding','packageRoot'};
ok=isstruct(a)&&isscalar(a)&&all(isfield(a,required));
if ~ok,return;end
ok=textScalar(a.sourceRoot) ...
    && strcmpi(stripFinalSeparator(string(a.sourceRoot)), ...
        fullfile(canonicalAssetRoot(),'method_source','matlab')) ...
    && textScalar(a.packageRoot) ...
    && strcmpi(stripFinalSeparator(string(a.packageRoot)),canonicalAssetRoot()) ...
    && isstruct(a.binding)&&isscalar(a.binding) ...
    && all(isfield(a.binding,{'schema','source_manifest_sha256', ...
        'verified_source_entries','source_path_only_difference'})) ...
    && string(a.binding.schema)=="CANONICAL_E_PACKAGE_RUNTIME_SOURCE_BINDING_V1" ...
    && strcmpi(string(a.binding.source_manifest_sha256), ...
        "73B05811B5D1EC37892650F29FD0F479696D186FAE20939EF1492DE9DA5A7F5D") ...
    && isequal(double(a.binding.verified_source_entries),160) ...
    && logicalScalar(a.binding.source_path_only_difference) ...
    && a.binding.source_path_only_difference ...
    && isstruct(a.configurationBinding)&&isscalar(a.configurationBinding) ...
    && isfield(a.configurationBinding,'effective_configuration_payload_sha256') ...
    && strcmpi(string(a.configurationBinding.effective_configuration_payload_sha256), ...
        "A859433D0AA774013341444A4B9AE971A34F12B4FB89C0A004B2CB3E013FCEBA") ...
    && isstruct(a.profile)&&isfield(a.profile,'mass_properties') ...
    && isfield(a.profile.mass_properties,'base_mass_kg') ...
    && finiteScalar(a.profile.mass_properties.base_mass_kg) ...
    && a.profile.mass_properties.base_mass_kg>0 ...
    && strcmpi(string(which('gpenmpcM600Allocation')), ...
        fullfile(string(a.sourceRoot),'dynamics','gpenmpcM600Allocation.m')) ...
    && strcmpi(string(which('gpenmpcNormalizedTotalRotorCommand')), ...
        fullfile(string(a.sourceRoot),'data','gpenmpcNormalizedTotalRotorCommand.m'));
if ~ok,return;end
c=a.enmpc;
required={'outer_period_s','prediction_step_s','horizon_steps', ...
    'prediction_horizon_s','solver_deadline_s','coordinated_architecture_mode', ...
    'coordinated_physical_gp_application_enabled', ...
    'coordinated_gp_execution_feedforward_enabled', ...
    'gp_responsibility_gate_enabled','command_continuity_enabled'};
ok=isstruct(c)&&isscalar(c)&&all(isfield(c,required));
if ~ok,return;end
ok=isequal(double(c.outer_period_s),0.30) ...
    && isequal(double(c.prediction_step_s),0.20) ...
    && isequal(double(c.horizon_steps),8) ...
    && isequal(double(c.prediction_horizon_s),1.60) ...
    && isequal(double(c.solver_deadline_s),0.28) ...
    && string(c.coordinated_architecture_mode)=="A1_COORDINATED_PHYSICAL";
for field=required(7:end)
    value=c.(field{1});
    ok=ok && islogical(value)&&isscalar(value)&&value;
end
end

function value=canonicalAssetRoot()
distributionRoot=fileparts(fileparts(fileparts(fileparts(fileparts(mfilename('fullpath'))))));
value=fullfile(string(distributionRoot),'assets','canonical');
end

function value=stripFinalSeparator(value)
value=replace(string(value),"/","\");
while endsWith(value,"\")
    value=extractBefore(value,strlength(value));
end
end

function ok=nonnegativeInteger(value)
ok=finiteScalar(value)&&value>=0&&value==fix(value)&&value<=flintmax;
end

function ok=textScalar(value)
ok=(ischar(value)&&isrow(value)) ...
    ||(isstring(value)&&isscalar(value)&&~ismissing(value));
end

function ok = finiteScalar(value)
ok = isnumeric(value) && isreal(value) && isscalar(value) && isfinite(value);
end

function ok = finiteVector(value,count)
ok = isnumeric(value) && isreal(value) && isvector(value) ...
    && numel(value)==count && all(isfinite(value(:)));
end

function ok = logicalScalar(value)
ok = islogical(value) && isscalar(value);
end

function ok = shaScalar(value)
ok = (ischar(value) || (isstring(value) && isscalar(value))) ...
    && strlength(string(value))==64 ...
    && all(ismember(char(upper(string(value))),['0':'9','A':'F']));
end
