function [window,state]=prepareCanonicalReferenceWindow( ...
        leg,binding,firstRow,windowGeneration,referenceAssetSha256,lastAcceptedSequence)
% Copy nominal jets and analytic bindings into a 256-entry reference buffer.
% The caller refills explicitly and preserves lastAcceptedSequence.
arguments
    leg (1,1) struct
    binding (1,1) struct
    firstRow (1,1) double {mustBeInteger,mustBePositive}
    windowGeneration (1,1) uint64
    referenceAssetSha256 (32,1) uint8
    lastAcceptedSequence (1,1) uint64 = uint64(0)
end
assert(windowGeneration>0&&any(referenceAssetSha256), ...
    'gpenmpcNative:ReferenceWindowIdentity','Explicit asset/window identity required.');
required={'local_time_s','position_up_m','velocity_mps','acceleration_mps2', ...
    'jerk_mps3','trajectory','meta'};
assert(all(isfield(leg,required))&&isfield(leg.meta,'leg_index'), ...
    'gpenmpcNative:ReferenceWindowSource','Original loaded task leg is required.');
time=double(leg.local_time_s(:));n=numel(time);
assert(n>=2&&all(isfinite(time))&&all(diff(time)>0)&&time(1)==0 ...
    &&firstRow<n&&time(end)==leg.trajectory.total_duration_s, ...
    'gpenmpcNative:ReferenceWindowRows','Original increasing nominal rows required.');
count=min(256,n-firstRow+1);ix=firstRow:firstRow+count-1;
arrays={leg.position_up_m,leg.velocity_mps,leg.acceleration_mps2,leg.jerk_mps3};
window=struct('schema',uint32(1),'capacity',uint16(256), ...
    'reference_asset_sha256',referenceAssetSha256, ...
    'leg_index',uint32(leg.meta.leg_index),'window_generation',windowGeneration, ...
    'source_first_row',uint32(firstRow),'source_total_rows',uint32(n), ...
    'row_count',uint16(count),'time_s',nan(256,1),'nominal_jet',nan(256,3,4), ...
    'nominal_duration_s',time(end),'total_duration_s',time(end), ...
    'binding_mode',uint8(0),'prefix_duration_s',0.0, ...
    'prefix_coefficients',nan(3,8,4,2), ...
    'ground_jet',nan(3,4),'rest_jet',nan(3,4), ...
    'relaunch_duration_s',0.0,'relaunch_offset_ned_m',nan(3,1), ...
    'vertical_frame_offset_ned_m',0.0);
window.time_s(1:count)=time(ix);
for order=0:3
    a=double(arrays{order+1});
    assert(isequal(size(a),[n 3])&&all(isfinite(a),'all'), ...
        'gpenmpcNative:ReferenceWindowJets','Original finite four N-by-3 arrays required.');
    window.nominal_jet(1:count,:,order+1)=a(ix,:);
end
assert(isfield(binding,'schema')&&isfield(binding,'leg_index') ...
    &&binding.leg_index==leg.meta.leg_index, ...
    'gpenmpcNative:ReferenceWindowBinding','Binding must belong to this exact leg.');
if strcmp(binding.schema,'RFLY_INITIAL_TAKEOFF_REFERENCE_BINDING_V1')
    assert(leg.meta.leg_index==1&&binding.prefix_duration_phase_s==25 ...
        &&isequal(binding.durations_phase_s,[20 5]) ...
        &&binding.original_leg_duration_s==time(end), ...
        'gpenmpcNative:ReferenceWindowBinding','Use the existing 20/25-s first-leg binding.');
    first=zeros(3,4);for order=0:3,first(:,order+1)=double(arrays{order+1}(1,:).');end
    assert(isequal(first,binding.original_first_jet_columns_p_v_a_j), ...
        'gpenmpcNative:ReferenceWindowBinding','Binding first jet differs from source rows.');
    window.binding_mode=uint8(1);window.prefix_duration_s=25;
    window.total_duration_s=25+time(end);
    window.ground_jet=[double(binding.ground_position_up_m(:)),zeros(3,3)];
    window.rest_jet=[first(:,1),zeros(3,3)];
    for segment=1:2
        coefficients=double(binding.coefficients_ascending_seconds{segment});
        assert(isequal(size(coefficients),[3 8])&&all(isfinite(coefficients),'all'), ...
            'gpenmpcNative:ReferenceWindowCoefficients','Copy existing bound coefficients, never fit rows.');
        % Original gpenmpcPrepareTrajectoryDerivatives recurrence, copied once.
        % Unused polynomial columns are not evaluated (avoid changed dot sums).
        for order=0:3
            window.prefix_coefficients(:,1:8-order,order+1,segment)=coefficients;
            coefficients=coefficients(:,2:end).*(1:size(coefficients,2)-1);
        end
    end
elseif strcmp(binding.schema,'RFLY_RELAUNCH_REFERENCE_BINDING_V1')
    assert(leg.meta.leg_index>=2&&leg.meta.leg_index<=5 ...
        &&binding.removal_duration_phase_s==11&&binding.nominal_duration_s==time(end), ...
        'gpenmpcNative:ReferenceWindowBinding','Use the existing causal relaunch binding.');
    offset=double(binding.horizontal_offset_ned_m(:));z=double(binding.vertical_frame_offset_ned_m);
    assert(isequal(size(offset),[3 1])&&all(isfinite(offset))&&offset(3)==0 ...
        &&isscalar(z)&&isfinite(z),'gpenmpcNative:ReferenceWindowBinding','Finite original offsets required.');
    window.binding_mode=uint8(2);window.relaunch_duration_s=11;
    window.relaunch_offset_ned_m=offset;window.vertical_frame_offset_ned_m=z;
else
    error('gpenmpcNative:ReferenceWindowBinding','Only existing initial/relaunch bindings are supported.');
end
state=struct('reference_asset_sha256',referenceAssetSha256, ...
    'leg_index',window.leg_index,'window_generation',windowGeneration, ...
    'last_accepted_sequence',lastAcceptedSequence);
end
