function [command,next] = prepareCanonicalFullInnerCommand( ...
        x13,reference,payload,wind,augmentation,previous,dt,newLeg,assets, ...
        generation,estimateTimestampNs,taskSha,boardContext)
% Prepare inputs for the full algebraic SE(3) kernel.
assert(isnumeric(x13)&&numel(x13)==13&&all(isfinite(x13(:))) ...
    &&isnumeric(augmentation)&&numel(augmentation)==3&&all(isfinite(augmentation(:))) ...
    &&isscalar(dt)&&isfinite(dt)&&dt>0&&dt<=.0100001 ...
    &&islogical(newLeg)&&isscalar(newLeg)&&assets.attitudeContinuity.enabled, ...
    'gpenmpcNative:FullInnerInput','Invalid canonical full-inner input.');
x=[double(x13(:));zeros(6,1)]; % algebraic kernel reads only x(1:13)
raw=gpenmpcDesiredSe3Command(x,reference,payload,wind,augmentation, ...
    assets.calibration,assets.profile);
[attitude,next]=gpenmpcUpdateDesiredAttitudeContinuity( ...
    previous,raw.desired_rotation,double(dt),newLeg,assets.attitudeContinuity);
assert(~attitude.time_discontinuity,'gpenmpcNative:FullInnerTimeDiscontinuity', ...
    'Do not conceal a source time discontinuity by resetting the desired attitude.');
command=struct('schema','GPENMPC_CANONICAL_FULL_INNER_COMMAND_V1', ...
    'generation',uint64(generation),'estimate_sample_timestamp_ns',uint64(estimateTimestampNs), ...
    'task_identity_sha256',string(taskSha),'dt_s',double(dt), ...
    'state_up',x,'reference_up',reference,'payload_kg',double(payload), ...
    'wind_estimate_xy_mps',double(wind(:)), ...
    'augmentation_up_mps2',double(augmentation(:)), ...
    'attitude_command',attitude, ...
    'configuration_payload_sha256',string(assets.binding.effective_configuration_payload_sha256), ...
    'kernel_source_sha256','52F714D65C4A3CD5879FFD4478F60379F68CD5F65A38F5971B91BBC01D0E4AB8', ...
    'coordinate_frame','CANONICAL_UP_FRAME_NOT_NED_FRD', ...
    'augmentation_applications',1,'board_publication_authority',false, ...
    'evidence_scope','HOST_ONLY_KERNEL_EXECUTION','plant_truth_used',false);
if nargin>=13
    assert(isstruct(boardContext)&&isscalar(boardContext) ...
        &&isequal(uint64(generation),boardContext.source_generation) ...
        &&isa(boardContext.source_ticket,'uint8')&&numel(boardContext.source_ticket)==32 ...
        &&any(boardContext.source_ticket)&&strlength(string(boardContext.execution_session_sha256))==64, ...
        'gpenmpcNative:FullInnerBoardContext','Exact private source/session association required.');
    command.evidence_scope='BOARD_COMMIT_RFC1';
    command.source_generation=boardContext.source_generation;
    command.source_ticket=boardContext.source_ticket(:);
    command.execution_session_sha256=string(boardContext.execution_session_sha256);
    command.augmentation_state_generation=boardContext.source_generation;
    command.continuity_state_generation=boardContext.source_generation;
end
end
