function [next,jet,receipt]=queryCanonicalReferenceWindow(window,state,request)
% Query fixed-array reference jets by phase, asset, leg, window and monotone sequence.
% Rejected calls preserve state and return no valid jet.
% Reasons: 0 pass, 1 shape/content, 2 identity, 3 sequence, 4 query, 5 window.
% Future reference queries do not represent future state observations.
next=state;jet=nan(3,4);
receipt=struct('accepted',false,'reason',uint8(1), ...
    'query_progress_s',NaN,'effective_nominal_progress_s',NaN, ...
    'query_sequence',uint64(0),'source_first_row',uint32(0),'source_last_row',uint32(0), ...
    'analytic_prefix_used',false,'reference_resampled',false,'hardware_actions',uint32(0));
% Same required fields, scalar predicates so MATLAB Coder can resolve the
% fixed ABI. Coder does not support the equivalent isfield(s,cellstr) form.
if ~isstruct(window)||~isscalar(window) ...
        ||~isfield(window,'schema')||~isfield(window,'capacity') ...
        ||~isfield(window,'reference_asset_sha256')||~isfield(window,'leg_index') ...
        ||~isfield(window,'window_generation')||~isfield(window,'source_first_row') ...
        ||~isfield(window,'source_total_rows')||~isfield(window,'row_count') ...
        ||~isfield(window,'time_s')||~isfield(window,'nominal_jet') ...
        ||~isfield(window,'nominal_duration_s')||~isfield(window,'total_duration_s') ...
        ||~isfield(window,'binding_mode')||~isfield(window,'prefix_duration_s') ...
        ||~isfield(window,'prefix_coefficients')||~isfield(window,'ground_jet') ...
        ||~isfield(window,'rest_jet')||~isfield(window,'relaunch_duration_s') ...
        ||~isfield(window,'relaunch_offset_ned_m')||~isfield(window,'vertical_frame_offset_ned_m') ...
        ||~isstruct(state)||~isscalar(state) ...
        ||~isfield(state,'reference_asset_sha256')||~isfield(state,'leg_index') ...
        ||~isfield(state,'window_generation')||~isfield(state,'last_accepted_sequence') ...
        ||~isstruct(request)||~isscalar(request) ...
        ||~isfield(request,'reference_asset_sha256')||~isfield(request,'leg_index') ...
        ||~isfield(request,'window_generation')||~isfield(request,'query_sequence') ...
        ||~isfield(request,'progress_s'),return;end
if ~isequal(window.schema,uint32(1))||~isequal(window.capacity,uint16(256)) ...
        ||~isa(window.row_count,'uint16')||~isscalar(window.row_count) ...
        ||window.row_count<2||window.row_count>256 ...
        ||~isequal(size(window.time_s),[256 1])||~isequal(size(window.nominal_jet),[256 3 4]) ...
        ||~isa(window.time_s,'double')||~isa(window.nominal_jet,'double'),return;end
if ~isa(window.reference_asset_sha256,'uint8')||~isequal(size(window.reference_asset_sha256),[32 1]) ...
        ||~any(window.reference_asset_sha256)||~isa(window.leg_index,'uint32') ...
        ||~isscalar(window.leg_index)||window.leg_index<1||window.leg_index>5 ...
        ||~isa(window.window_generation,'uint64')||~isscalar(window.window_generation) ...
        ||window.window_generation==0||~isa(window.source_first_row,'uint32') ...
        ||~isscalar(window.source_first_row)||~isa(window.source_total_rows,'uint32') ...
        ||~isscalar(window.source_total_rows)||~isa(window.binding_mode,'uint8') ...
        ||~isscalar(window.binding_mode),return;end
if ~finiteDoubleScalar(window.nominal_duration_s)||~finiteDoubleScalar(window.total_duration_s) ...
        ||~finiteDoubleScalar(window.prefix_duration_s)||~finiteDoubleScalar(window.relaunch_duration_s),return;end
count=double(window.row_count);t=window.time_s(1:count);
if any(~isfinite(t))||any(diff(t)<=0)||any(~isfinite(window.nominal_jet(1:count,:,:)),'all') ...
        ||~isfinite(window.nominal_duration_s)||window.nominal_duration_s<=0 ...
        ||t(1)<0||t(end)>window.nominal_duration_s ...
        ||window.source_first_row<1 ...
        ||double(window.source_first_row)+count-1>double(window.source_total_rows),return;end
if ~isequal(request.reference_asset_sha256,window.reference_asset_sha256) ...
        ||~isequal(request.leg_index,window.leg_index) ...
        ||~isequal(request.window_generation,window.window_generation) ...
        ||~isequal(state.reference_asset_sha256,window.reference_asset_sha256) ...
        ||~isequal(state.leg_index,window.leg_index) ...
        ||~isequal(state.window_generation,window.window_generation)
    receipt.reason=uint8(2);return
end
if ~isa(request.query_sequence,'uint64')||~isscalar(request.query_sequence) ...
        ||~isa(state.last_accepted_sequence,'uint64')||~isscalar(state.last_accepted_sequence) ...
        ||request.query_sequence<=state.last_accepted_sequence
    receipt.reason=uint8(3);return
end
q=request.progress_s;
if ~isa(q,'double')||~isscalar(q)||~isreal(q)||~isfinite(q)
    receipt.reason=uint8(4);return
end
receipt.query_progress_s=q;receipt.query_sequence=request.query_sequence;
if window.binding_mode==1
    if window.prefix_duration_s~=25||window.total_duration_s~=25+window.nominal_duration_s ...
        ||~isequal(size(window.prefix_coefficients),[3 8 4 2]) ...
        ||~isequal(size(window.ground_jet),[3 4])||~isequal(size(window.rest_jet),[3 4]) ...
        ||any(~isfinite(window.ground_jet),'all')||any(~isfinite(window.rest_jet),'all'),return;end
    q=min(max(q,0),window.total_duration_s);
    if q<25
        receipt.analytic_prefix_used=true;
        if q==0
            jet=window.ground_jet;
        elseif q==20
            jet=window.rest_jet;
        else
            segment=1;local=q;if q>20,segment=2;local=q-20;end
            for order=0:3
                coefficients=window.prefix_coefficients(:,1:8-order,order+1,segment);
                if any(~isfinite(coefficients),'all'),jet=nan(3,4);return;end
                powers=local.^(0:size(coefficients,2)-1);
                jet(:,order+1)=coefficients*powers.';
            end
        end
        finish();return
    end
    nominalQ=q-25; % Preserve binary64 subtraction.
elseif window.binding_mode==2
    if window.relaunch_duration_s~=11||window.total_duration_s~=window.nominal_duration_s ...
        ||~isequal(size(window.relaunch_offset_ned_m),[3 1]) ...
        ||any(~isfinite(window.relaunch_offset_ned_m)) ...
        ||~isscalar(window.vertical_frame_offset_ned_m)||~isfinite(window.vertical_frame_offset_ned_m),return;end
    nominalQ=q;
else
    return
end
nominalQ=min(max(nominalQ,0),window.nominal_duration_s);
receipt.effective_nominal_progress_s=nominalQ;
if nominalQ<t(1)||nominalQ>t(end)
    receipt.reason=uint8(5);return
end
for order=0:3
    % Same four independent linear interpolations on ORIGINAL nominal rows.
    jet(:,order+1)=interp1(t,window.nominal_jet(1:count,:,order+1),nominalQ,"linear").';
end
receipt.source_first_row=window.source_first_row;
receipt.source_last_row=window.source_first_row+uint32(count-1);
if window.binding_mode==2
    duration=window.relaunch_duration_s;tau=min(max(q/duration,0),1);
    for order=0:3
        switch order
            case 0,coefficient=1-(35*tau.^4-84*tau.^5+70*tau.^6-20*tau.^7);
            case 1,coefficient=-(140*tau.^3-420*tau.^4+420*tau.^5-140*tau.^6)/duration;
            case 2,coefficient=-(420*tau.^2-1680*tau.^3+2100*tau.^4-840*tau.^5)/duration^2;
            otherwise,coefficient=-(840*tau-5040*tau.^2+8400*tau.^3-4200*tau.^4)/duration^3;
        end
        jet(:,order+1)=jet(:,order+1)+window.relaunch_offset_ned_m*coefficient;
        if order==0,jet(3,order+1)=jet(3,order+1)-window.vertical_frame_offset_ned_m;end
    end
end
finish();
    function finish()
        if any(~isfinite(jet),'all'),jet=nan(3,4);return;end
        next.last_accepted_sequence=request.query_sequence;
        receipt.accepted=true;receipt.reason=uint8(0);
    end
end
function valid=finiteDoubleScalar(value)
valid=isa(value,'double')&&isscalar(value)&&isreal(value)&&isfinite(value);
end
