function feedback=RflyCommittedFeedbackDecoder(message,originalHostReceiveNs)
% Decode RFC1 feedback bytes.
assert(isa(message,'uint8')&&numel(message)==1112, ...
    'gpenmpcNative:FeedbackLength','RFC1 is exactly1112 bytes.');message=message(:);
assert(isequal(message(1:4),uint8('RFC1').')&&ismember(message(5),uint8([1,2,3])), ...
    'gpenmpcNative:FeedbackSchema','RFC1 disposition must be explicit.');
assert(isa(originalHostReceiveNs,'uint64')&&isscalar(originalHostReceiveNs)&&originalHostReceiveNs>0, ...
    'gpenmpcNative:FeedbackHostClock','Original uint64 HOST receipt event required.');
md=java.security.MessageDigest.getInstance('SHA-256');md.update(typecast(message(1:1080),'int8'));
assert(isequal(reshape(typecast(md.digest(),'uint8'),[],1),message(1081:1112)), ...
    'gpenmpcNative:FeedbackDigest','RFC1 checksum mismatch.');
names={'Fresh','HistoricalExpired','Revoked'};offset=6;
feedback=struct('schema','GPENMPC_RFLY_COMMITTED_FEEDBACK_RFC1', ...
    'disposition',names{double(message(5))},'snapshot_ticket',read('uint8',32));
token=struct();token.identity=struct('uid',read('uint64',1),'boot_generation',read('uint64',1), ...
    'system',read('uint8',1),'component',read('uint8',1));token.publication_path=read('uint8',1);
fields={'transaction','output_generation','sample_generation','timestamp_sample_us','source_generation_delta', ...
    'state_publication_us','state_board_rx_us','control_tick_us','sample_delta_us','actual_tick_delta_us', ...
    'reference_generation','reference_timestamp_us','reference_board_rx_us','reference_valid_until_us', ...
    'outer_generation','outer_board_rx_us','outer_valid_until_us','outer_based_on_sample_generation','outer_based_on_timestamp_sample_us'};
for k=1:numel(fields),token.(fields{k})=read('uint64',1);end
for name={'outer_payload_sha256','full_input_sha256','kernel_argument_sha256','kernel_source_sha256'}
    token.(name{1})=sha();
end
feedback.token=token;
for name={'configuration_payload_sha256','approved_parameter_sha256','matlab_extraction_source_sha256', ...
        'generated_arm_source_sha256','wrapper_matlab_source_sha256'}
    feedback.(name{1})=sha();
end
feedback.actual61=read('double',61);feedback.published_control16=read('single',16);
for name={'kernel_completed_us','publication_us','commit_completed_us','original_valid_until_us'}
    feedback.(name{1})=read('uint64',1);
end
assert(offset==1081,'gpenmpcNative:FeedbackLayout','RFC1 layout drift.');
feedback.message_sha256=sha();feedback.original_host_receive_ns=originalHostReceiveNs;
assert(token.identity.uid>0&&token.identity.boot_generation>0&&token.identity.system>0&&token.identity.component>0 ...
    &&token.output_generation>0&&token.sample_generation>0&&token.publication_path==2 ...
    &&feedback.kernel_completed_us>0&&feedback.publication_us>=feedback.kernel_completed_us ...
    &&feedback.commit_completed_us>=feedback.publication_us&&feedback.original_valid_until_us>=feedback.commit_completed_us ...
    &&strcmp(feedback.generated_arm_source_sha256,token.kernel_source_sha256), ...
    'gpenmpcNative:FeedbackBinding','Invalid identity, original board times, or code binding.');
assert(all(isfinite(feedback.actual61))&&all(isfinite(feedback.published_control16)) ...
    &&all(abs(feedback.published_control16)<=1)&&ismember(feedback.actual61(61),[0,1]), ...
    'gpenmpcNative:FeedbackValues','Nonfinite/out-of-domain actual feedback.');
feedback.wrench_n_nm=feedback.actual61(1:4);feedback.rotor_command_n=feedback.actual61(5:10);
feedback.diagnostic51=feedback.actual61(11:61);
feedback.control=struct('desired_force_projected_up_n',feedback.actual61(14:16), ...
    'rotor_command_n',feedback.actual61(5:10),'rotor_saturated',logical(feedback.actual61(61)), ...
    'force_projection_norm_mismatch_n',feedback.actual61(59), ...
    'desired_moment_nm',feedback.actual61(2:4),'desired_thrust_n',feedback.actual61(1));
feedback.historical_only=message(5)~=1;
feedback.control_authority=false;feedback.board_consumption_proven=false;
feedback.transport_source_authenticated=false; % enclosing real link owner verifies origin
    function value=read(kind,count)
        switch kind,case 'uint8',width=1;case 'single',width=4;otherwise,width=8;end
        value=typecast(message(offset:offset+count*width-1),kind);offset=offset+count*width;
        [~,~,endian]=computer;if endian=='L'&&width>1,value=swapbytes(value);end;value=value(:);
    end
    function value=sha()
        bytes=read('uint8',32);value=upper(reshape(dec2hex(bytes,2).',1,[]));
    end
end
