classdef RflyLocalTaskCodec
    % Encode RLI1 through MAVLink TUNNEL.
    methods (Static)
        function u=originalNumericalObservation(bound,rls,originalReceiveNs,registered)
            % Provide bootstrap measurements before the first outer command exists,
            % using the same validation as encode.
            s=gpenmpcNative.RflyLocalSnapshotDecoder(rls,originalReceiveNs);key=sourceKey(s);e=registered;
            assert(strcmp(bound.schema,'RFLY_LOCAL_ORIGINAL_INPUT_BINDING_V1') ...
                &&bound.numerical_inputs_complete&&~bound.control_authority ...
                &&isequal(bound.source,key)&&isequal(bound.rotor.source,key) ...
                &&isequal(bound.payload.source,key)&&isequal(bound.wind.source,key) ...
                &&strcmp(bound.rotor.value_kind,'OriginalPlantLagState'), ...
                'gpenmpcNative:LocalTaskSource','Same private source and original lag observation required.');
            assert(isequal(s.identity,e.identity)&&bound.leg_index==e.leg_index ...
                &&isequal(hashBytes(bound.payload.task_sha256),hashBytes(e.task_sha256)) ...
                &&strcmpi(e.configuration_sha256,'A859433D0AA774013341444A4B9AE971A34F12B4FB89C0A004B2CB3E013FCEBA'), ...
                'gpenmpcNative:LocalTaskIdentity','Registered current method/task/leg required.');
            r=bound.rotor.original_observation;
            assert(r.original_board_ingress_us==s.original_receipt_us&&r.dll_generation>0&&r.dll_session>0 ...
                &&r.original_host_receive_ns>0&&isfinite(r.original_sim_time_s)&&r.original_sim_time_s>=0 ...
                &&all(isfinite(r.observed_thrust_n))&&all(r.observed_thrust_n>=0) ...
                &&bound.payload.original_schedule_generation>0&&isfinite(bound.payload.payload_kg)&&bound.payload.payload_kg>=0 ...
                &&bound.wind.original_estimate_generation>0&&all(isfinite(bound.wind.estimate_xy_mps)), ...
                'gpenmpcNative:LocalTaskIngress','Original numeric observation and source time required.');
            for h={r.original_observation_sha,bound.rotor.verified_association_receipt_sha256, ...
                    bound.payload.original_schedule_evidence_sha256,bound.wind.original_estimate_evidence_sha256}
                hashBytes(h{1});
            end
            u=struct('source',key,'original_sensor52',s.original_sensor52,'leg_index',bound.leg_index, ...
                'execution_session_sha256',hashBytes(e.execution_session_sha256),'task_sha256',hashBytes(e.task_sha256), ...
                'configuration_sha256',hashBytes(e.configuration_sha256),'reference_asset_sha256',hashBytes(e.reference_asset_sha256), ...
                'rotor',bound.rotor,'payload',bound.payload,'wind',bound.wind,'outer',[], ...
                'control_authority',false,'outer_command_fabricated',false);
        end
        function bytes=encode(bound,rls,originalReceiveNs,outer,registered)
            gpenmpcNative.RflyLocalTaskCodec.originalNumericalObservation(bound,rls,originalReceiveNs,registered);
            s=gpenmpcNative.RflyLocalSnapshotDecoder(rls,originalReceiveNs);
            key=sourceKey(s);e=registered;
            assert(strcmp(bound.schema,'RFLY_LOCAL_ORIGINAL_INPUT_BINDING_V1') ...
                &&bound.numerical_inputs_complete&&~bound.control_authority ...
                &&isequal(bound.source,key)&&isequal(bound.rotor.source,key) ...
                &&isequal(bound.payload.source,key)&&isequal(bound.wind.source,key) ...
                &&strcmp(bound.rotor.value_kind,'OriginalPlantLagState'), ...
                'gpenmpcNative:LocalTaskSource','Same private source and original lag observation required.');
            assert(isequal(s.identity,e.identity)&&bound.leg_index==e.leg_index ...
                &&isequal(hashBytes(bound.payload.task_sha256),hashBytes(e.task_sha256)) ...
                &&strcmpi(e.configuration_sha256,'A859433D0AA774013341444A4B9AE971A34F12B4FB89C0A004B2CB3E013FCEBA'), ...
                'gpenmpcNative:LocalTaskIdentity','Registered current method/task/leg required.');
            r=bound.rotor.original_observation;
            assert(r.original_board_ingress_us==s.original_receipt_us, ...
                'gpenmpcNative:LocalTaskIngress','Original source receive time cannot be renewed.');
            bytes=[uint8('RLI1').';hashBytes(e.execution_session_sha256);hashBytes(e.configuration_sha256); ...
                hashBytes(e.task_sha256);hashBytes(e.reference_asset_sha256);be(uint32(e.leg_index)); ...
                be(s.identity.uid);be(s.identity.boot_generation);uint8(s.identity.system);uint8(s.identity.component); ...
                be(key.sample_us);be(key.publication_us);be(key.original_receipt_us);be(key.source_generation); ...
                be(key.generation_delta);be(key.sample_delta_us);uint8(key.reset_counter);hashBytes(key.state_and_origin_sha256); ...
                s.original_sensor52;be(r.dll_generation);be(r.dll_session);be(r.original_host_receive_ns); ...
                be(double(r.original_sim_time_s));be(double(r.observed_thrust_n(:)));hashBytes(r.original_observation_sha); ...
                hashBytes(bound.rotor.verified_association_receipt_sha256); ...
                be(bound.payload.original_schedule_generation);hashBytes(bound.payload.original_schedule_evidence_sha256);be(double(bound.payload.payload_kg)); ...
                be(bound.wind.original_estimate_generation);hashBytes(bound.wind.original_estimate_evidence_sha256);be(double(bound.wind.estimate_xy_mps(:))); ...
                be(outer.generation);be(outer.source_generation);be(outer.original_sample_us); ...
                be(outer.original_host_source_receive_ns);be(outer.original_creation_ns);be(outer.original_expiry_ns);be(double(outer.target4(:)))];
            assert(numel(bytes)==615);bytes=[bytes;digest(bytes)];
            gpenmpcNative.RflyLocalTaskCodec.decode(bytes);
        end
        function m=decode(bytes)
            assert(isa(bytes,'uint8')&&numel(bytes)==647);bytes=bytes(:);
            [~,~,endian]=computer;littleEndian=endian=='L';
            assert(isequal(bytes(1:4),uint8('RLI1').')&&isequal(digest(bytes(1:615)),bytes(616:647)), ...
                'gpenmpcNative:LocalTaskDigest','RLI1 checksum mismatch.');
            % RLI1's existing fixed wire layout. Convert integer/double groups
            % once, retaining uint64 without a double round trip. No field,
            % checksum, source or time check is omitted by this batching.
            ui=(0:7).'+[137 145 155 163 171 179 187 195 288 296 304 432 480 536 544 552 560 568 576];
            di=(0:7).'+[312 320 328 336 344 352 360 472 520 528 584 592 600 608];
            u=typecast(reshape(bytes(ui),[],1),'uint64');
            d=typecast(reshape(bytes(di),[],1),'double');leg=typecast(bytes(133:136),'uint32');
            if littleEndian,u=swapbytes(u);d=swapbytes(d);leg=swapbytes(leg);end
            m=struct('schema','RLI1_ORIGINAL_INPUTS_NO_CONTROL_AUTHORITY');
            m.execution_session_sha256=bytes(5:36);m.configuration_sha256=bytes(37:68);
            m.task_sha256=bytes(69:100);m.reference_asset_sha256=bytes(101:132);m.leg_index=leg;
            key.identity=struct('uid',u(1),'boot_generation',u(2),'system',bytes(153),'component',bytes(154));
            key.sample_us=u(3);key.publication_us=u(4);key.original_receipt_us=u(5);
            key.source_generation=u(6);key.generation_delta=u(7);key.sample_delta_us=u(8);
            key.reset_counter=bytes(203);key.state_and_origin_sha256=bytes(204:235);m.source=key;
            m.original_sensor52=bytes(236:287);
            r.dll_generation=u(9);r.dll_session=u(10);r.original_host_receive_ns=u(11);
            r.original_sim_time_s=d(1);r.observed_thrust_n=d(2:7);r.original_observation_sha=bytes(368:399);
            r.original_board_ingress_us=key.original_receipt_us;
            m.rotor=struct('source',key,'value_kind','OriginalPlantLagState','original_observation',r, ...
                'verified_association_receipt_sha256',bytes(400:431));
            m.payload=struct('source',key,'task_sha256',m.task_sha256,'original_schedule_generation',u(12), ...
                'original_schedule_evidence_sha256',bytes(440:471),'payload_kg',d(8));
            m.wind=struct('source',key,'original_estimate_generation',u(13), ...
                'original_estimate_evidence_sha256',bytes(488:519),'estimate_xy_mps',d(9:10));
            m.outer=struct('generation',u(14),'source_generation',u(15),'original_sample_us',u(16), ...
                'original_host_source_receive_ns',u(17),'original_creation_ns',u(18), ...
                'original_expiry_ns',u(19),'target4',d(11:14));
            o=m.outer;
            hashes={m.execution_session_sha256,m.configuration_sha256,m.task_sha256,m.reference_asset_sha256,key.state_and_origin_sha256, ...
                r.original_observation_sha,m.rotor.verified_association_receipt_sha256,m.payload.original_schedule_evidence_sha256,m.wind.original_estimate_evidence_sha256};
            assert(all(cellfun(@(v)any(v~=0),hashes))&&m.leg_index>=1&&m.leg_index<=5 ...
                &&key.identity.uid>0&&key.identity.boot_generation>0&&key.identity.system>0&&key.identity.component>0 ...
                &&key.sample_us>0&&key.source_generation>0&&key.publication_us>=key.sample_us&&key.original_receipt_us>=key.publication_us ...
                &&r.dll_generation>0&&r.dll_session>0&&r.original_host_receive_ns>0&&isfinite(r.original_sim_time_s)&&r.original_sim_time_s>=0 ...
                &&all(isfinite(r.observed_thrust_n))&&all(r.observed_thrust_n>=0) ...
                &&m.payload.original_schedule_generation>0&&isfinite(m.payload.payload_kg)&&m.payload.payload_kg>=0 ...
                &&m.wind.original_estimate_generation>0&&all(isfinite(m.wind.estimate_xy_mps)) ...
                &&o.generation>0&&o.source_generation>0&&o.source_generation<=key.source_generation ...
                &&o.original_sample_us>0&&o.original_sample_us<=key.sample_us&&o.original_host_source_receive_ns>0 ...
                &&o.original_creation_ns>=o.original_host_source_receive_ns&&o.original_expiry_ns>=o.original_creation_ns&&all(isfinite(o.target4)), ...
                'gpenmpcNative:LocalTaskFields','Malformed original inputs/outer fields.');
            m.original_bytes=bytes;m.control_authority=false;m.original_timestamps_renewed=false;
        end
        function [p,m]=fragments(bytes,targetSystem,targetComponent)
            m=gpenmpcNative.RflyLocalTaskCodec.decode(bytes);p=cell(6,1);
            generationBytes=be(m.source.source_generation);
            for k=1:6
                n=min(119,647-(k-1)*119);payload=zeros(128,1,'uint8');
                payload(1)=uint8(208+k-1);payload(2:9)=generationBytes;
                payload(10:9+n)=bytes(119*(k-1)+1:119*(k-1)+n);
                p{k}=struct('payload_type',uint16(42002),'target_system',uint8(targetSystem),'target_component',uint8(targetComponent), ...
                    'payload_length',uint8(9+n),'payload',payload);
            end
        end
    end
end
function key=sourceKey(s)
key=struct('identity',s.identity,'sample_us',s.original_sample_us,'publication_us',s.original_publication_us, ...
    'original_receipt_us',s.original_receipt_us,'source_generation',s.source_generation,'generation_delta',s.generation_delta, ...
    'sample_delta_us',s.sample_delta_us,'reset_counter',s.reset_counter,'state_and_origin_sha256',s.state_and_origin_sha256);
end
function b=be(v)
assert(isa(v,'uint64')||isa(v,'uint32')||isa(v,'double'));[~,~,e]=computer;if e=='L',v=swapbytes(v);end
b=reshape(typecast(v(:),'uint8'),[],1);
end
function h=digest(b),m=java.security.MessageDigest.getInstance('SHA-256');m.update(typecast(b(:),'int8'));h=reshape(typecast(m.digest(),'uint8'),[],1);end
function h=hashBytes(x)
if isa(x,'uint8'),h=x(:);else,h=uint8(sscanf(char(x),'%2x'));end
assert(numel(h)==32&&any(h~=0));
end
