function sample=RflySnapshotSample(message,originalHostReceiveNs,expected)
% Map RSP1 bytes into solver input while retaining all 246 source bytes.
s=gpenmpcNative.RflySnapshotDecoder(message,originalHostReceiveNs);
assert(isstruct(expected)&&isscalar(expected)&&all(isfield(expected, ...
    {'uid','system_id','component_id','boot_generation','configuration_payload_sha256'})), ...
    'gpenmpcNative:SnapshotExpected','Explicit session/configuration is required.');
assert(isnumeric(expected.boot_generation)&&isscalar(expected.boot_generation) ...
    &&isfinite(expected.boot_generation)&&expected.boot_generation>0 ...
    &&expected.boot_generation==fix(expected.boot_generation), ...
    'gpenmpcNative:SnapshotExpectedSession','Positive exact session generation required.');
assert(string(s.observed_uid)==string(expected.uid) ...
    &&isequal(uint64(s.observed_boot_generation),uint64(expected.boot_generation)) ...
    &&double(s.source_system)==double(expected.system_id) ...
    &&double(s.source_component)==double(expected.component_id), ...
    'gpenmpcNative:SnapshotIdentity','Observed private identity does not match the registered session.');
sha=upper(reshape(dec2hex(s.configuration_sha256,2).',1,[]));
assert(strcmpi(sha,string(expected.configuration_payload_sha256)), ...
    'gpenmpcNative:SnapshotConfiguration','Private configuration differs.');
assert(s.pose_frame==1&&s.velocity_frame==1&&s.subscription_generation>0 ...
    &&any(s.ticket)&&all(isfinite(s.task_origin_ned_m)), ...
    'gpenmpcNative:SnapshotFrame','Original NED frames/ticket/generation required.');
assert(s.original_sample_hrt_us<=idivide(intmax('uint64'),uint64(1000)), ...
    'gpenmpcNative:SnapshotOverflow','Original HRT cannot be represented in nanoseconds.');
raw=double(s.raw13_float32);
sample=struct('source','PX4_PRIVATE_VEHICLE_ODOMETRY_RSP1', ...
    'atomic_estimate',true,'plant_truth_used',false, ...
    'uid',string(s.observed_uid),'system_id',double(s.source_system), ...
    'component_id',double(s.source_component), ...
    'boot_generation',s.observed_boot_generation, ...
    'sample_timestamp_ns',s.original_sample_hrt_us*uint64(1000), ...
    'position_ned_m',raw(1:3)-s.task_origin_ned_m, ...
    'velocity_ned_mps',raw(4:6),'quaternion_wxyz_body_to_ned',raw(7:10), ...
    'omega_frd_rad_s',raw(11:13), ...
    'position_rx_ns',originalHostReceiveNs,'attitude_rx_ns',originalHostReceiveNs, ...
    'rates_rx_ns',originalHostReceiveNs, ...
    'position_generation',s.subscription_generation, ...
    'attitude_generation',s.subscription_generation,'rates_generation',s.subscription_generation, ...
    'position_valid',true,'attitude_valid',true,'rates_valid',true, ...
    'source_ticket',s.ticket,'source_export_sha256',s.export_sha256, ...
    'source_export_bytes',message(:),'source_host_receive_ns',originalHostReceiveNs, ...
    'original_sample_hrt_us',s.original_sample_hrt_us, ...
    'original_publication_hrt_us',s.original_publication_hrt_us, ...
    'original_board_receipt_hrt_us',s.original_board_receipt_hrt_us, ...
    'actual_source_delta_us',s.actual_source_delta_us,'generation_delta',s.generation_delta, ...
    'raw13_float32',s.raw13_float32,'task_origin_ned_m',s.task_origin_ned_m, ...
    'pose_frame',s.pose_frame,'velocity_frame',s.velocity_frame, ...
    'reset_counter',s.reset_counter,'quality',s.quality, ...
    'configuration_payload_sha256',sha, ...
    'sample_clock_domain','BOARD_HRT','receipt_clock_domain','HOST_MONOTONIC', ...
    'live_time_domain_binding',false);
end
