classdef RflyLocalStreamLifecycle < handle
    % Request streams through the bound MAVLink owner.
    % Construction is read-only; the caller explicitly enables and disables streams.
    properties (SetAccess=private)
        Failed=false
        Failure=''
        EnableAttempts=uint64(0)
        DisableAttempts=uint64(0)
        EnableReceipt=[]
        DisableReceipts={}
        EnableSendReturned=false
        DisableSendReturned=false
        StreamObserved=false
        ObservationCounts=zeros(1,3,'uint64')
        LastObservation=[]
    end
    properties (Access=private)
        Io
        Registered
        Association
        Expected
        LastGeneration=zeros(1,3,'uint64')
        Busy=false
    end
    methods
        function obj=RflyLocalStreamLifecycle(io,registered,association)
            assert(isstruct(io)&&all(isfield(io,{'pollCanonical','evidence','sendCanonicalSession'})) ...
                &&all(cellfun(@(n)isa(io.(n),'function_handle'), ...
                    {'pollCanonical','evidence','sendCanonicalSession'})), ...
                'gpenmpcNative:LocalStreamIo','The existing IO callbacks are required.');
            assert(isstruct(registered)&&registered.local_full_inner ...
                &&isstruct(association)&&association.local_full_inner ...
                &&strcmp(association.registration_result,'Registered') ...
                &&strcmp(association.echo_confirmation_result,'Confirmed'), ...
                'gpenmpcNative:LocalStreamRegistration','A confirmed original local registration is required.');
            obj.Io=io;obj.Registered=registered;obj.Association=association;
            raw=obj.checkBinding(true);obj.Expected=raw.canonical_exchange_expected;
        end
        function receipt=enable(obj)
            try
                assert(~obj.Busy&&~obj.Failed&&obj.EnableAttempts==0&&obj.DisableAttempts==0, ...
                    'gpenmpcNative:LocalStreamEnableOnce','Enable is one explicit request, never an automatic retry.');
                obj.Busy=true;guard=onCleanup(@()obj.unlock()); %#ok<NASGU>
                raw=obj.checkBinding(true);
                receipt=obj.sendRequest(true,raw);
                obj.EnableSendReturned=true;
            catch ex,obj.fail(ex);rethrow(ex);end
        end
        function receipt=disable(obj)
            % Explicit cleanup remains available after a latched failure.
            % A successful repeat is read-only; a failed attempt may be
            % explicitly retried and both original attempt records survive.
            try
                assert(~obj.Busy,'gpenmpcNative:LocalStreamReentry','A stream request is already in progress.');
                if obj.DisableSendReturned,receipt=obj.DisableReceipts{end};return;end
                obj.Busy=true;guard=onCleanup(@()obj.unlock()); %#ok<NASGU>
                % pollCanonical calls the failed reassembler and can throw.
                % Cleanup instead checks the same retained identity/owner via
                % the existing evidence getter; the IO enforces its whitelist.
                raw=obj.checkBinding(false);
                receipt=obj.sendRequest(false,raw);
                obj.DisableSendReturned=true;
            catch ex,obj.fail(ex);rethrow(ex);end
        end
        function observation=observe(obj,item)
            try
                assert(~obj.Busy&&~obj.Failed&&obj.EnableSendReturned&&obj.DisableAttempts==0, ...
                    'gpenmpcNative:LocalStreamObservationState','Observe only between successful enable and any disable attempt.');
                obj.Busy=true;guard=onCleanup(@()obj.unlock()); %#ok<NASGU>
                raw=obj.checkBinding(true);e=obj.Expected;
                names={'schema','channel','message','origin','generation','original_host_receive_ns', ...
                    'completion_host_receive_ns','processing_ns','fragment_rx_ns', ...
                    'original_callback_indices','decoded_fragments','decoded'};
                assert(isstruct(item)&&isscalar(item)&&all(isfield(item,names)) ...
                    &&strcmp(item.schema,'LOCAL_RUNTIME_COMPLETED_ORIGINAL_TUNNEL') ...
                    &&isequal(item.origin.link_lifecycle_generation,e.link_lifecycle_generation) ...
                    &&strcmpi(item.origin.execution_session_sha256,e.execution_session_sha256), ...
                    'gpenmpcNative:LocalStreamOrigin','The original same-session completed item is required.');
                channel=find(["gp_request","snapshot","committed_state"]==string(item.channel));
                assert(isscalar(channel)&&isa(item.message,'uint8')&&iscolumn(item.message), ...
                    'gpenmpcNative:LocalStreamChannel','Unknown channel or malformed retained bytes.');
                first=item.original_host_receive_ns;last=item.completion_host_receive_ns;
                submitted=obj.EnableReceipt.transport_receipt.original_host_submit_ns;
                assert(isa(first,'uint64')&&isscalar(first)&&isa(last,'uint64')&&isscalar(last) ...
                    &&isa(item.processing_ns,'uint64')&&isscalar(item.processing_ns) ...
                    &&first>max(submitted)&&first>=e.confirmed_host_rx_ns&&last>=first ...
                    &&item.processing_ns>=last&&item.processing_ns<=gpenmpcNative.rflyOriginalHostMonotonicNs(), ...
                    'gpenmpcNative:LocalStreamOldObservation','Only original post-request observations; no retimestamping.');
                switch channel
                    case 1
                        decoded=gpenmpcNative.RflyLocalGpCodec.decodeRequest(item.message);
                        generation=decoded.output_generation;schema=8;bodyLength=310;
                    case 2
                        decoded=gpenmpcNative.RflyLocalSnapshotDecoder(item.message,first);
                        generation=decoded.source_generation;schema=10;bodyLength=382;
                    case 3
                        decoded=gpenmpcNative.RflyLocalCommittedDecoder(item.message,first);
                        assert(decoded.learning_audit_available,'gpenmpcNative:LocalStreamLearningEvidence','Original RLC2 learning evidence is required.');
                        generation=decoded.output_generation;schema=14;bodyLength=1494;
                end
                assert(isequal(decoded.identity,obj.Registered.identity)&&isequaln(item.decoded,decoded) ...
                    &&isa(item.generation,'uint64')&&isscalar(item.generation)&&item.generation==generation ...
                    &&generation>obj.LastGeneration(channel)&&numel(item.message)==bodyLength, ...
                    'gpenmpcNative:LocalStreamBodyIdentity','Body identity, original decoding and generation must match.');
                if channel~=2
                    assert(strcmpi(streamHex(decoded.configuration_sha256),obj.Registered.configuration_sha256), ...
                        'gpenmpcNative:LocalStreamConfiguration','The registered configuration must match.');
                end
                if channel==3
                    assert(decoded.leg_index==obj.Registered.leg_index, ...
                        'gpenmpcNative:LocalStreamLeg','The registered task leg must match.');
                    if isfield(obj.Registered,'reference_asset_sha256')
                        assert(strcmpi(streamHex(decoded.reference_asset_sha256),obj.Registered.reference_asset_sha256), ...
                            'gpenmpcNative:LocalStreamReference','The registered reference must match.');
                    end
                end
                count=ceil(bodyLength/119);indices=item.original_callback_indices;times=item.fragment_rx_ns;
                assert(iscell(item.decoded_fragments)&&numel(item.decoded_fragments)==count ...
                    &&isa(indices,'uint64')&&numel(indices)==count&&isa(times,'uint64')&&numel(times)==count ...
                    &&times(1)==first&&times(end)==last&&all(times(2:end)>=times(1:end-1)) ...
                    &&isfield(raw,'raw_mavlink')&&iscell(raw.raw_mavlink), ...
                    'gpenmpcNative:LocalStreamOriginalFragments','Complete original fragments and receive times are required.');
                prior=uint64(0);
                for k=1:count
                    index=indices(k);
                    assert(index>prior&&index<=uint64(numel(raw.raw_mavlink)), ...
                        'gpenmpcNative:LocalStreamOriginalIndex','Original callback indices must be ordered and present.');
                    row=raw.raw_mavlink{double(index)};m=item.decoded_fragments{k};
                    nativeSource=strcmp(row.decoded_source,'ORIGINAL_MAVLINKIO_TUNNEL_CALLBACK');
                    if isfield(raw,'transport_kind')&&strcmp(raw.transport_kind,'OFFICIAL_CODEC_SOLE_RAW_UDP')
                        nativeSource=strcmp(row.decoded_source,'RAW_OWNER_DATAGRAM_DEQUEUE_OFFICIAL_DECODER') ...
                            &&isfield(row,'raw_frame')&&isa(row.raw_frame,'uint8') ...
                            &&~isempty(row.raw_frame)&&isequal(row.raw_frame_available,true);
                    end
                    assert(strcmp(row.topic,'TUNNEL')&&nativeSource ...
                        &&isequal(row.original_host_receive_ns,times(k))&&isequaln(row.decoded_message,m) ...
                        &&double(m.MsgID)==385&&isequal(uint8(m.SystemID),e.source_system) ...
                        &&isequal(uint8(m.ComponentID),e.source_component), ...
                        'gpenmpcNative:LocalStreamOriginalCallback','The retained callback identity, time and message must match.');
                    p=m.Payload;n=min(119,bodyLength-(k-1)*119);b=p.payload(:);
                    assert(isequal(p.target_system,e.target_system)&&isequal(p.target_component,e.target_component) ...
                        &&double(p.payload_type)==42002&&isa(b,'uint8')&&numel(b)==128 ...
                        &&double(p.payload_length)==9+n&&b(1)==uint8(schema*16+k-1) ...
                        &&streamBe64(b(2:9))==generation&&all(b(10+n:end)==0) ...
                        &&isequal(b(10:9+n),item.message((k-1)*119+1:(k-1)*119+n)), ...
                        'gpenmpcNative:LocalStreamOriginalBody','Exact original TUNNEL fragments must carry this body.');
                    prior=index;
                end
                obj.LastGeneration(channel)=generation;obj.ObservationCounts(channel)=obj.ObservationCounts(channel)+uint64(1);
                obj.LastObservation=item;obj.StreamObserved=true;
                observation=struct('channel',char(item.channel),'generation',generation, ...
                    'original_host_receive_ns',first,'completion_host_receive_ns',last, ...
                    'original_callback_indices',indices,'same_existing_mavlinkio',raw.same_existing_mavlinkio, ...
                    'same_existing_transport_owner',true,'transport_kind',raw.transport_kind, ...
                    'original_stream_traffic_observed',true,'enable_command_acknowledged',false, ...
                    'caused_by_enable_proven',false,'release_proven',false,'freshness_renewed',false);
            catch ex,obj.fail(ex);rethrow(ex);end
        end
        function s=status(obj)
            s=struct('failed',obj.Failed,'failure',obj.Failure,'enable_attempts',obj.EnableAttempts, ...
                'disable_attempts',obj.DisableAttempts,'enable_send_returned',obj.EnableSendReturned, ...
                'disable_send_returned',obj.DisableSendReturned,'original_stream_traffic_observed',obj.StreamObserved, ...
                'observation_counts',obj.ObservationCounts,'enable_receipt',obj.EnableReceipt, ...
                'disable_receipts',{obj.DisableReceipts},'last_observation',obj.LastObservation, ...
                'enable_command_acknowledged',false,'stream_disabled_proven',false,'release_proven',false, ...
                'independent_release_evidence_required',true,'additional_connections',0, ...
                'module_start_stop_commands',0,'arm_mode_commands',0);
        end
    end
    methods (Access=private)
        function raw=checkBinding(obj,healthy)
            if healthy
                state=obj.Io.pollCanonical();
                assert(state.bound&&state.board_local_full_inner&&gpenmpcNative.sameSoleMavlinkOwner(state) ...
                    &&state.additional_connections==0&&isempty(state.failure),'gpenmpcNative:LocalStreamUnbound','A healthy bound local IO is required.');
            end
            raw=obj.Io.evidence();r=obj.Registered;a=obj.Association;
            assert(isfield(raw,'canonical_exchange_association')&&isequaln(raw.canonical_exchange_association,a) ...
                &&isfield(raw,'canonical_exchange_expected')&&~isempty(raw.canonical_exchange_expected), ...
                'gpenmpcNative:LocalStreamAssociation','The original IO association must remain unchanged.');
            e=raw.canonical_exchange_expected;i=r.identity;echo=a.echo;
            assert(e.local_full_inner&&e.uid==i.uid&&e.session_generation==i.boot_generation ...
                &&e.source_system==i.system&&e.source_component==i.component ...
                &&strcmpi(e.execution_session_sha256,r.execution_session_sha256) ...
                &&strcmpi(e.configuration_sha256,r.configuration_sha256)&&strcmpi(e.task_sha256,r.task_sha256) ...
                &&e.leg_index==r.leg_index&&e.confirmed_host_rx_ns==a.original_host_receive_ns ...
                &&strcmpi(a.execution_session_sha256,r.execution_session_sha256) ...
                &&echo.uid==i.uid&&echo.process_session_generation==i.boot_generation ...
                &&echo.system==i.system&&echo.component==i.component ...
                &&echo.link_lifecycle_generation==e.link_lifecycle_generation ...
                &&strcmpi(echo.configuration_payload_sha256,r.configuration_sha256), ...
                'gpenmpcNative:LocalStreamSession','The exact confirmed session fields must match.');
            p=a.confirm_receipt.parsed_fields;
            assert(p.leg==r.leg_index&&strcmpi(p.task_sha,r.task_sha256)&&p.state==3 ...
                &&p.start_requests==0&&p.stop_requests==0&&p.session_fault==0, ...
                'gpenmpcNative:LocalStreamRegistration','The retained confirmation must precede module start.');
            if ~isempty(obj.Expected)
                assert(isequaln(e,obj.Expected),'gpenmpcNative:LocalStreamSessionChanged','This stream owner cannot change sessions.');
            end
        end
        function attempt=sendRequest(obj,enabled,before)
            if enabled,obj.EnableAttempts=obj.EnableAttempts+uint64(1);number=obj.EnableAttempts;
            else,obj.DisableAttempts=obj.DisableAttempts+uint64(1);number=obj.DisableAttempts;end
            attempt=struct('enabled_requested',enabled,'attempt_number',number,'api_invoked',true, ...
                'api_returned',false,'transport_receipt',[],'current_transport_receipt_observed',false, ...
                'failure','','board_acknowledged',false,'release_proven',false);
            try
                receipt=obj.Io.sendCanonicalSession('stream_local',struct('enabled',enabled));
                attempt.api_returned=true;attempt.transport_receipt=receipt;
                raw=obj.Io.evidence();
                attempt.current_transport_receipt_observed=isequaln(raw.canonical_session_last_send,receipt);
                expected='mavlink stream -d /dev/ttyACM0 -s GPENMPC_LOCAL_WIRE -r 0';
                if enabled,expected='mavlink stream -d /dev/ttyACM0 -s GPENMPC_LOCAL_WIRE -r -1';end
                n=receipt.encoding.fragments;t=receipt.original_host_submit_ns;u=receipt.original_host_send_return_ns;
                assert(attempt.current_transport_receipt_observed&&strcmp(receipt.encoding.action,'stream_local') ...
                    &&strcmp(receipt.encoding.original_command,expected)&&n>=1&&n==fix(n) ...
                    &&receipt.messages_attempted==n&&receipt.messages_send_returned==n ...
                    &&~receipt.partial&&isempty(receipt.error)&&gpenmpcNative.sameSoleMavlinkOwner(receipt) ...
                    &&isa(t,'uint64')&&numel(t)==n&&isa(u,'uint64')&&numel(u)==n ...
                    &&all(t>obj.Expected.confirmed_host_rx_ns)&&all(u>=t) ...
                    &&all(t(2:end)>=u(1:end-1)),'gpenmpcNative:LocalStreamSendReceipt','The complete current same-link send receipt is required.');
                obj.storeAttempt(enabled,attempt);
            catch ex
                attempt.failure=ex.identifier;
                % Preserve the failed attempt's IO record, including any transmitted prefix.
                try
                    raw=obj.Io.evidence();candidate=raw.canonical_session_last_send;
                    if ~isequaln(candidate,before.canonical_session_last_send)
                        attempt.transport_receipt=candidate;attempt.current_transport_receipt_observed=true;
                    end
                catch
                    % Existing API failure remains the reason; absence of an
                    % available receipt is explicitly retained as unknown.
                end
                obj.storeAttempt(enabled,attempt);rethrow(ex)
            end
        end
        function storeAttempt(obj,enabled,attempt)
            if enabled,obj.EnableReceipt=attempt;else,obj.DisableReceipts{end+1}=attempt;end
        end
        function fail(obj,ex)
            obj.Failed=true;if isempty(obj.Failure),obj.Failure=ex.identifier;end
        end
        function unlock(obj),obj.Busy=false;end
    end
end
function v=streamBe64(b)
v=uint64(0);for k=1:numel(b),v=bitor(bitshift(v,8),uint64(b(k)));end
end
function h=streamHex(b),h=upper(reshape(dec2hex(b,2).',1,[]));end
