function s=RflyLocalCommittedDecoder(bytes,originalHostReceiveNs)
% Decode committed RLC1 or RLC2 state; pending open prediction is excluded.
assert(isa(bytes,'uint8')&&(numel(bytes)==1398||numel(bytes)==1494));bytes=bytes(:);
assert(isa(originalHostReceiveNs,'uint64')&&isscalar(originalHostReceiveNs)&&originalHostReceiveNs>0);
% Memoize decoded bytes; consumers independently validate source, age and sequence.
persistent lastBytes lastReceiveNs lastParsed
if isequal(bytes,lastBytes)&&isequal(originalHostReceiveNs,lastReceiveNs)
    s=lastParsed;return
end
learning=numel(bytes)==1494;magic='RLC1';if learning,magic='RLC2';end
assert(isequal(bytes(1:4),uint8(magic).'),'gpenmpcNative:LocalCommittedMagic','Size/version pair required.');
last=numel(bytes)-32;md=java.security.MessageDigest.getInstance('SHA-256');md.update(typecast(bytes(1:last),'int8'));
assert(isequal(reshape(typecast(md.digest(),'uint8'),[],1),bytes(last+1:end)), ...
    'gpenmpcNative:LocalCommittedDigest','RLC1 checksum mismatch.');
% Decode contiguous primitive blocks once to reduce receive-path overhead.
[~,~,endian]=computer;
headerIdentity=value(5:20,'uint64');headerCounters=value(23:94,'uint64');
numeric=value(99:1202,'double');
s=struct('schema','BOARD_LOCAL_RLC1_ORIGINAL_COMMITTED_OBSERVATION', ...
    'identity',struct('uid',headerIdentity(1),'boot_generation',headerIdentity(2), ...
        'system',bytes(21),'component',bytes(22)), ...
    'source_timestamp_ns',headerCounters(1),'source_generation',headerCounters(2), ...
    'output_generation',headerCounters(3),'original_publication_us',headerCounters(4), ...
    'joint_installs',headerCounters(5),'gp_fills',headerCounters(6), ...
    'window_generation',headerCounters(7),'query_sequence',headerCounters(8), ...
    'outer_generation',headerCounters(9),'leg_index',value(95:98,'uint32'), ...
    'state64',numeric(1:64),'closed5',numeric(65:69), ...
    'reference6',numeric(70:75),'installed_phase2',numeric(76:77), ...
    'kernel61',numeric(78:138),'published_control16',value(1203:1266,'single'), ...
    'state_kind',bytes(1267),'closed_available',bytes(1268),'numeric_installed',bytes(1269), ...
    'prediction_ready',bytes(1270),'committed_state_sha256',bytes(1271:1302), ...
    'configuration_sha256',bytes(1303:1334),'reference_asset_sha256',bytes(1335:1366), ...
    'original_bytes',bytes,'original_host_receive_ns',originalHostReceiveNs, ...
    'control_authority',false,'freshness_renewed',false,'next_open_prediction_included',false);
i=s.identity;c=s.closed5;
assert(i.uid>0&&i.boot_generation>0&&i.system>0&&i.component>0 ...
    &&s.source_timestamp_ns>0&&s.source_generation>0&&s.output_generation>0 ...
    &&s.original_publication_us>=idivide(s.source_timestamp_ns,uint64(1000)) ...
    &&s.joint_installs>0&&s.window_generation>0&&s.query_sequence>0&&s.outer_generation>0 ...
    &&s.leg_index>=1&&s.leg_index<=5&&s.state_kind>=2&&s.state_kind<=4 ...
    &&s.closed_available<=1&&s.numeric_installed==1&&s.prediction_ready<=1 ...
    &&all(isfinite(c))&&all(c(1:4)==0|c(1:4)==1)&&c(5)>=0&&c(5)<=1 ...
    &&double(s.closed_available)==c(1)&&all(isfinite(s.reference6)) ...
    &&all(isfinite(s.installed_phase2))&&all(isfinite(s.published_control16)), ...
    'gpenmpcNative:LocalCommittedFields','Inconsistent installed/closed/phase evidence.');
s.closed_gp_evidence=struct('available',logical(c(1)),'prediction_sample_closed',logical(c(2)), ...
    'observed_innovation_available',logical(c(3)),'hard_invalid',logical(c(4)),'trust',c(5));
s.learning_audit_available=learning;s.learning12=[];s.physical_gp_diagnostic=[];
if learning
    v=value(1367:1462,'double');s.learning12=v;
    % Unavailable innovation is retained as NaN, not invented as zero.
    % Authority/blend/trust outputs must always be finite and bounded.
    assert(all(isfinite(v(4:12)))&&all(v(4:9)>=0&v(4:9)<=1) ...
        &&(v(10)==0||v(10)==1)&&all(v(11:12)>=0&v(11:12)<=1), ...
        'gpenmpcNative:LocalCommittedLearning','Invalid physical-learning diagnostic.');
    % When evidence is unavailable, close() may leave Frenet innovation NaN.
    if c(1)==1&&c(3)==1,assert(all(isfinite(v(1:3))),'gpenmpcNative:LocalCommittedInnovation');end
    s.closed_gp_evidence.observed_innovation_f_mps2=v(1:3);
    s.physical_gp_diagnostic=struct('closed_innovation_f_mps2',v(1:3), ...
        'gp_prediction_axis_authority_f',v(4:6),'gp_physical_axis_authority_f',v(7:9), ...
        'exact_b1_fallback',logical(v(10)),'gp_responsibility_blend',v(11),'gp_trust',v(12));
end
% state64/kernel61 preserve original binary64 bits, including optional invalid
% observer fields; the numerical consumer must validate the fields it uses.
lastBytes=bytes;lastReceiveNs=originalHostReceiveNs;lastParsed=s;
    function v=value(indices,kind)
        v=typecast(bytes(indices),kind);if endian=='L',v=swapbytes(v);end
        v=v(:);
    end
end
