function [packets,receipt,message]=RflyContextEncoder(context,serializer,dialect)
% Encode RCT1 using the owner's original event times and source-ticket association.
fields={'reference_generation','outer_generation','reference_source_receipt_ns', ...
    'reference_creation_ns','reference_expiry_ns','outer_source_receipt_ns', ...
    'outer_creation_ns','outer_expiry_ns'};
for k=1:numel(fields)
    v=context.(fields{k});assert(isa(v,'uint64')&&isscalar(v)&&v>0, ...
        'gpenmpcNative:ContextInteger','Original exact positive uint64 required.');
end
for prefix={'reference','outer'}
    p=prefix{1};assert(context.([p '_creation_ns'])>=context.([p '_source_receipt_ns']) ...
        &&context.([p '_expiry_ns'])>=context.([p '_creation_ns']), ...
        'gpenmpcNative:ContextClock','Original HOST times are not ordered.');
end
for field={'configuration_sha256','reference_source_ticket','outer_source_ticket'}
    v=context.(field{1});assert(isa(v,'uint8')&&numel(v)==32&&any(v), ...
        'gpenmpcNative:ContextBytes','Exact nonzero 32 bytes required.');
end
assert(isa(context.reference_ned,'double')&&numel(context.reference_ned)==11&&all(isfinite(context.reference_ned(:))) ...
    &&isa(context.outer_payload,'double')&&numel(context.outer_payload)==4&&all(isfinite(context.outer_payload(:))), ...
    'gpenmpcNative:ContextPayload','11 reference and4 actual outer binary64 values required.');
message=[uint8('RCT1').';context.configuration_sha256(:); ...
    be(context.reference_generation);be(context.outer_generation); ...
    context.reference_source_ticket(:);context.outer_source_ticket(:); ...
    be(context.reference_source_receipt_ns);be(context.reference_creation_ns);be(context.reference_expiry_ns); ...
    be(context.outer_source_receipt_ns);be(context.outer_creation_ns);be(context.outer_expiry_ns); ...
    be(context.reference_ned);be(context.outer_payload)];
assert(numel(message)==284);
md=java.security.MessageDigest.getInstance('SHA-256');md.update(typecast(message,'int8'));
message=[message;reshape(typecast(md.digest(),'uint8'),[],1)];
packets=cell(3,1);wire=0;
for index=0:2
    part=[uint8(64+index);be(context.reference_generation);message(index*119+1:min(index*119+119,316))];
    msg=createmsg(dialect,'TUNNEL');
    assert(isa(context.target_system,'uint8')&&isscalar(context.target_system)&&context.target_system>0 ...
        &&isa(context.target_component,'uint8')&&isscalar(context.target_component)&&context.target_component>0, ...
        'gpenmpcNative:ContextTarget','Exact nonzero target required.');
    msg.Payload.target_system=context.target_system;msg.Payload.target_component=context.target_component;
    msg.Payload.payload_type=uint16(42002);msg.Payload.payload_length=uint8(numel(part));
    payload=zeros(size(msg.Payload.payload),'uint8');payload(1:numel(part))=part;msg.Payload.payload=payload;
    packets{index+1}=reshape(uint8(serializemsg(serializer,msg)),1,[]);wire=wire+numel(packets{index+1});
end
receipt=struct('schema','RFLY_RCT1_SCHEMA4','message_bytes',316,'fragments',3, ...
    'serialized_bytes',wire,'live_time_domain_binding',false,'board_access',0);
end
function bytes=be(v)
[~,~,endian]=computer;if endian=='L',v=swapbytes(v);end
bytes=reshape(typecast(v(:),'uint8'),[],1);
end
