classdef RflyBoardCommitConsumer < handle
    % Consume RFC1 outputs into host causal state.
    % The integration owner supplies verified registration and route associations.
    properties (SetAccess=private)
        Failed=false
        Failure=""
        Commits=uint64(0)
        LastOutputGeneration=uint64(0)
    end
    properties (Access=private)
        Expected
        Contract
        Assets
        TaskSha
        Pending=[]
        LastHost=uint64(0)
        LastSampleUs=uint64(0)
        LastSourceGeneration=uint64(0)
        LastBoardCommitUs=uint64(0)
        LastBoardTransaction=uint64(0)
        LastReceipt=struct()
    end
    methods
        function obj=RflyBoardCommitConsumer(expected,taskSha,assets)
            obj.Expected=expected;obj.Assets=assets;obj.TaskSha=upper(string(taskSha));
            assert(isfield(expected,'rfly_board_commit'),'gpenmpcNative:BoardCommitConfiguration','Explicit registered-session/route contract required.');
            c=expected.rfly_board_commit;
            fields={'execution_session_sha256','identity_semantics','link_lifecycle_generation', ...
                'board_registration_hrt_us','reference_max_age_us','outer_max_age_us', ...
                'generated_arm_source_sha256','wrapper_matlab_source_sha256'};
            assert(all(isfield(c,fields))&&string(c.identity_semantics)=="BoardRegisteredExecutionSessionGenerationV1" ...
                &&obj.sha(c.execution_session_sha256)&&obj.sha(taskSha) ...
                &&obj.integer(c.link_lifecycle_generation)&&obj.integer(c.board_registration_hrt_us) ...
                &&obj.integer(c.reference_max_age_us)&&obj.integer(c.outer_max_age_us) ...
                &&strcmpi(c.generated_arm_source_sha256,'A47F1C255BDAC1DAE712494BE8D9D66FC4F83138DBA9B0C2E3A31E114D4ABD0F') ...
                &&strcmpi(c.wrapper_matlab_source_sha256,'9117D3CDF8E924A253F4C444CDD467E4850D6F11CBF5744B26375B950E2A95B5'), ...
                'gpenmpcNative:BoardCommitConfiguration','Actual frozen code/session semantics required; no scope-only admission.');
            obj.Contract=c;
        end
        function receipt=submitted(obj,command,source,association,originalSubmitNs)
            % Called AFTER preparation with the original transport submission
            % event and original RCT1 context; no send occurs in this method.
            obj.time(originalSubmitNs);assert(isempty(obj.Pending),'gpenmpcNative:BoardCommitPending','Previous command still pending.');
            try
                assert(string(command.evidence_scope)=="BOARD_COMMIT_RFC1" ...
                    &&strcmpi(command.task_identity_sha256,obj.TaskSha));
                p=obj.reconstruct(source);o=obj.reconstruct(association.outer_source_sample);
                c=association.context;b=association.binding;
                assert(isequal(command.generation,uint64(p.position_generation)) ...
                    &&isequal(command.estimate_sample_timestamp_ns,p.sample_timestamp_ns) ...
                    &&isequal(command.source_ticket,p.source_ticket) ...
                    &&strcmpi(command.execution_session_sha256,obj.Contract.execution_session_sha256));
                assert(isequal(b.command_generation,command.generation) ...
                    &&isequal(b.snapshot_ticket(:),p.source_ticket) ...
                    &&isequal(b.reference_generation,c.reference_generation)&&isequal(b.outer_generation,c.outer_generation) ...
                    &&isequal(c.reference_source_ticket(:),p.source_ticket)&&isequal(c.outer_source_ticket(:),o.source_ticket));
                assert(c.reference_source_receipt_ns==p.source_host_receive_ns ...
                    &&c.outer_source_receipt_ns==o.source_host_receive_ns ...
                    &&originalSubmitNs>=c.reference_creation_ns&&originalSubmitNs>=c.outer_creation_ns ...
                    &&originalSubmitNs<=c.reference_expiry_ns&&originalSubmitNs<=c.outer_expiry_ns);
                assert(o.original_sample_hrt_us<=p.original_sample_hrt_us&&o.position_generation<=p.position_generation);
                expectedConfig=upper(reshape(dec2hex(c.configuration_sha256(:),2).',1,[]));
                assert(strcmpi(expectedConfig,obj.Assets.binding.effective_configuration_payload_sha256) ...
                    &&isequal(b.configuration_sha256(:),c.configuration_sha256(:)));
                ref=command.reference_up;C=diag([1,1,-1]);
                assert(isequal(c.reference_ned(1:9),[C*ref.position_m(:);C*ref.velocity_mps(:);C*ref.acceleration_mps2(:)]));
                [full,abi]=gpenmpcNative.encodeCanonicalFullInnerArguments(command,obj.Assets);
                [boardFull,mapping]=gpenmpcNative.rflyBoardReconstructedArguments(full,command,p);
                parameterSha=obj.hash([uint8('RAP1').';full(398:813)]);
                assert(originalSubmitNs>=p.source_host_receive_ns);
                obj.Pending=struct('command',command,'source',p,'outer_source',o,'context',c, ...
                    'binding',b,'original_submit_ns',originalSubmitNs,'host_argument_sha256',abi.kernel_argument_sha256, ...
                    'board_argument_sha256',obj.hash(boardFull),'parameter_sha256',parameterSha,'state_mapping',mapping);
            catch ex
                location="";if ~isempty(ex.stack),location="__LINE_"+string(ex.stack(1).line);end
                obj.fail("PENDING_ASSOCIATION__"+string(ex.identifier)+location);
            end
            receipt=struct('pending',true,'command_generation',command.generation, ...
                'source_generation',uint64(p.position_generation),'publication_authority',false, ...
                'live_registration_proven',false,'original_submit_ns',originalSubmitNs);
        end
        function [ok,reason,control,receipt]=consume(obj,envelope,nowNs)
            ok=false;reason="BOARD_COMMIT_REJECTED";control=struct();receipt=struct();
            try
                obj.time(nowNs);assert(~isempty(obj.Pending),'gpenmpcNative:BoardCommitNoPending','No pending original command.');
                assert(string(envelope.schema)=="GPENMPC_RFLY_BOARD_COMMIT_INGRESS_V1");
                f=gpenmpcNative.RflyCommittedFeedbackDecoder(envelope.message,envelope.original_host_receive_ns);
                p=obj.Pending;s=p.source;o=p.outer_source;c=p.context;t=f.token;
                assert(string(f.disposition)=="Fresh",'gpenmpcNative:BoardCommitHistorical','Historical or revoked receipt.');
                origin=envelope.origin;
                assert(isa(origin.link_lifecycle_generation,'uint64') ...
                    &&origin.link_lifecycle_generation==obj.Contract.link_lifecycle_generation ...
                    &&strcmpi(origin.execution_session_sha256,obj.Contract.execution_session_sha256) ...
                    &&isequal(origin.source_system,uint8(obj.Expected.system_id)) ...
                    &&isequal(origin.source_component,uint8(obj.Expected.component_id)), ...
                    'gpenmpcNative:BoardCommitOrigin','Different registered route/session origin.');
                assert(string(t.identity.uid)==string(obj.Expected.uid) ...
                    &&isequal(t.identity.boot_generation,uint64(obj.Expected.boot_generation)) ...
                    &&isequal(t.identity.system,uint8(obj.Expected.system_id)) ...
                    &&isequal(t.identity.component,uint8(obj.Expected.component_id)) ...
                    &&isequal(f.snapshot_ticket,s.source_ticket), ...
                    'gpenmpcNative:BoardCommitIdentity','Wrong original identity or ticket.');
                % Token.transaction is the BOARD binding's logical counter,
                % not transport command_generation (which RFC1 does not echo).
                assert(t.transaction>obj.LastBoardTransaction&&t.sample_generation==uint64(s.position_generation) ...
                    &&t.reference_generation==c.reference_generation&&t.outer_generation==c.outer_generation ...
                    &&t.output_generation>obj.LastOutputGeneration ...
                    &&t.timestamp_sample_us==s.original_sample_hrt_us ...
                    &&t.state_publication_us==s.original_publication_hrt_us&&t.state_board_rx_us==s.original_board_receipt_hrt_us ...
                    &&t.outer_based_on_sample_generation==uint64(o.position_generation) ...
                    &&t.outer_based_on_timestamp_sample_us==o.original_sample_hrt_us, ...
                    'gpenmpcNative:BoardCommitLineage','Original command/source/reference/outer mismatch or replay.');
                assert(strcmpi(f.configuration_payload_sha256,p.command.configuration_payload_sha256) ...
                    &&strcmpi(f.approved_parameter_sha256,p.parameter_sha256) ...
                    &&strcmpi(f.matlab_extraction_source_sha256,p.command.kernel_source_sha256) ...
                    &&strcmpi(f.generated_arm_source_sha256,obj.Contract.generated_arm_source_sha256) ...
                    &&strcmpi(f.wrapper_matlab_source_sha256,obj.Contract.wrapper_matlab_source_sha256) ...
                    &&strcmpi(t.kernel_argument_sha256,p.board_argument_sha256) ...
                    &&strcmpi(t.outer_payload_sha256,obj.hash(obj.be(c.outer_payload))), ...
                    'gpenmpcNative:BoardCommitCodeOrArguments','Different code/config/parameters/numeric arguments/outer payload.');
                referenceExpiry=obj.deadline(s,c,'reference',obj.Contract.reference_max_age_us);
                outerExpiry=obj.deadline(o,c,'outer',obj.Contract.outer_max_age_us);
                assert(t.reference_valid_until_us==referenceExpiry&&t.outer_valid_until_us==outerExpiry ...
                    &&t.reference_timestamp_us==t.reference_board_rx_us ...
                    &&t.reference_board_rx_us>=s.original_board_receipt_hrt_us&&t.outer_board_rx_us>=o.original_board_receipt_hrt_us ...
                    &&t.control_tick_us>=max(t.reference_board_rx_us,t.outer_board_rx_us) ...
                    &&t.control_tick_us>=obj.Contract.board_registration_hrt_us ...
                    &&f.kernel_completed_us>=t.control_tick_us&&f.commit_completed_us>obj.LastBoardCommitUs ...
                    &&f.original_valid_until_us<=min(referenceExpiry,outerExpiry), ...
                    'gpenmpcNative:BoardCommitHrt','Original board HRT lineage/deadline mismatch.');
                if obj.LastSourceGeneration>0
                    assert(t.sample_generation>obj.LastSourceGeneration&&t.timestamp_sample_us>obj.LastSampleUs ...
                        &&t.source_generation_delta==t.sample_generation-obj.LastSourceGeneration ...
                        &&t.sample_delta_us==t.timestamp_sample_us-obj.LastSampleUs, ...
                        'gpenmpcNative:BoardCommitSourceRegression','Original consumed source deltas mismatch.');
                end
                rx=f.original_host_receive_ns;age=uint64(obj.Expected.maximum_runtime_age_ns);
                assert(rx>=p.original_submit_ns&&rx<=nowNs&&nowNs-rx<=age ...
                    &&nowNs>=s.source_host_receive_ns&&nowNs-s.source_host_receive_ns<=age ...
                    &&nowNs<=min(c.reference_expiry_ns,c.outer_expiry_ns), ...
                    'gpenmpcNative:BoardCommitHostAge','Original HOST event expired/reversed; no HOST/HRT mapping.');
                rotor=f.actual61(5:10);upper=obj.Assets.kernelParameters.rotorUpper;
                assert(all(rotor>=0&rotor<=upper)&&f.actual61(59)>=0);
                predicted=zeros(16,1,'single');predicted([5;1;4;6;2;3])=single(rotor/upper);
                assert(isequal(typecast(predicted,'uint32'),typecast(f.published_control16,'uint32')), ...
                    'gpenmpcNative:BoardCommitPublishedBits','Actual published16 differs from actual allocated rotor encoding.');
                % All control values come directly from decoded actual61. No
                % gpenmpcRobustSe3Control/oracle is called on this path.
                control=f.control;control.dt_s=p.command.dt_s;
                obj.LastOutputGeneration=t.output_generation;obj.LastBoardCommitUs=f.commit_completed_us;
                obj.LastBoardTransaction=t.transaction;
                obj.LastSourceGeneration=t.sample_generation;obj.LastSampleUs=t.timestamp_sample_us;
                obj.Commits=obj.Commits+uint64(1);obj.Pending=[];
                receipt=struct('schema','BOARD_COMMIT_RFC1_CONSUMED_BY_HOST_CAUSAL_RUNTIME', ...
                    'source_generation',t.sample_generation,'command_generation',p.command.generation, ...
                    'board_transaction',t.transaction,'output_generation',t.output_generation, ...
                    'reference_generation',t.reference_generation,'outer_generation',t.outer_generation, ...
                    'snapshot_ticket',f.snapshot_ticket,'execution_session_sha256',obj.Contract.execution_session_sha256, ...
                    'original_host_receive_ns',rx,'original_valid_until_us',f.original_valid_until_us, ...
                    'kernel_completed_us',f.kernel_completed_us,'publication_us',f.publication_us,'commit_completed_us',f.commit_completed_us, ...
                    'actual61',f.actual61,'published_control16',f.published_control16, ...
                    'host_argument_sha256',p.host_argument_sha256,'board_argument_sha256',p.board_argument_sha256, ...
                    'actual_board_argument_sha256',t.kernel_argument_sha256,'state_mapping',p.state_mapping, ...
                    'board_commit_reported',true,'transport_source_authenticated',false, ...
                    'wire_command_generation_present',false, ...
                    'simulator_consumption_proven',false,'publication_authority',false,'HOST_HRT_mapping',false);
                obj.LastReceipt=receipt;ok=true;reason="PASS_BOARD_COMMIT_RFC1_ACTUAL_OUTPUT_CONSUMED";
            catch ex
                if ~obj.Failed,obj.Failed=true;obj.Failure="RFC1_CONSUMER__"+string(ex.identifier);end
                reason=obj.Failure;
            end
        end
        function revoke(obj)
            if ~obj.Failed,obj.Failed=true;obj.Failure="BOARD_COMMIT_CONSUMER_REVOKED";end
            obj.Pending=[];
        end
        function r=status(obj)
            r=struct('failed',obj.Failed,'failure',obj.Failure,'pending',~isempty(obj.Pending), ...
                'commits',obj.Commits,'last_receipt',obj.LastReceipt,'publication_authority',false);
        end
    end
    methods (Access=private)
        function p=reconstruct(obj,source)
            p=gpenmpcNative.RflySnapshotSample(source.source_export_bytes,source.source_host_receive_ns,obj.Expected);
            names=fieldnames(p);for k=1:numel(names),assert(isequaln(source.(names{k}),p.(names{k})));end
        end
        function time(obj,t)
            assert(~obj.Failed,'gpenmpcNative:BoardCommitFailed','%s',obj.Failure);
            if ~obj.integer(t)||t<obj.LastHost,obj.fail("HOST_EVENT_REVERSED");end
            obj.LastHost=t;
        end
        function fail(obj,why)
            if ~obj.Failed,obj.Failed=true;obj.Failure=why;end
            error('gpenmpcNative:BoardCommitFailClosed','%s',obj.Failure);
        end
    end
    methods (Static,Access=private)
        function yes=integer(v),yes=isa(v,'uint64')&&isscalar(v)&&v>0;end
        function yes=sha(v),yes=~isempty(regexp(char(string(v)),'^[A-Fa-f0-9]{64}$','once'));end
        function bytes=be(value)
            [~,~,endian]=computer;if endian=='L',value=swapbytes(value);end;bytes=reshape(typecast(value(:),'uint8'),[],1);
        end
        function h=hash(bytes)
            md=java.security.MessageDigest.getInstance('SHA-256');md.update(typecast(uint8(bytes(:)),'int8'));
            h=upper(reshape(dec2hex(typecast(md.digest(),'uint8'),2).',1,[]));
        end
        function expiry=deadline(source,context,prefix,limit)
            start=context.([prefix '_source_receipt_ns']);created=context.([prefix '_creation_ns']);finish=context.([prefix '_expiry_ns']);
            assert(isa(start,'uint64')&&isa(created,'uint64')&&isa(finish,'uint64')&&start>0&&created>=start&&finish>=created);
            elapsed=created-start;assert(idivide(elapsed,uint64(1000))<limit ...
                ||(idivide(elapsed,uint64(1000))==limit&&rem(elapsed,uint64(1000))==0));
            duration=min(idivide(finish-start,uint64(1000)),limit);
            assert(duration>0&&source.original_sample_hrt_us<=intmax('uint64')-duration);
            expiry=source.original_sample_hrt_us+duration;
        end
    end
end
