function snapshot=RflySnapshotDecoder(message,originalHostReceiveNs)
% Decode private RSP1 exports while preserving observed UID and boot identity.
assert(isa(message,'uint8')&&numel(message)==246&&isequal(message(1:4),uint8('RSP1').'), ...
    'gpenmpcNative:SnapshotWire','Exact RSP1 message required.');message=message(:);
assert(isa(originalHostReceiveNs,'uint64')&&isscalar(originalHostReceiveNs)&&originalHostReceiveNs>0, ...
    'gpenmpcNative:SnapshotClock','Original HOST reception event required.');
md=java.security.MessageDigest.getInstance('SHA-256');md.update(typecast(message(1:214),'int8'));
assert(isequal(reshape(typecast(md.digest(),'uint8'),[],1),message(215:246)), ...
    'gpenmpcNative:SnapshotDigest','RSP1 checksum failed.');
snapshot=struct('schema','BOARD_PRIVATE_RSP1_EXPORT','ticket',message(5:36), ...
    'observed_uid',value(37:44,'uint64'),'observed_boot_generation',value(45:52,'uint64'), ...
    'source_system',message(53),'source_component',message(54), ...
    'odometry_message_version',value(55:58,'uint32'),'subscription_generation',value(59:62,'uint32'), ...
    'original_sample_hrt_us',value(63:70,'uint64'),'original_publication_hrt_us',value(71:78,'uint64'), ...
    'original_board_receipt_hrt_us',value(79:86,'uint64'),'task_origin_ned_m',value(87:110,'double'), ...
    'raw13_float32',value(111:162,'single'),'pose_frame',message(163),'velocity_frame',message(164), ...
    'reset_counter',message(165),'quality',typecast(message(166),'int8'), ...
    'generation_delta',value(167:174,'uint64'),'actual_source_delta_us',value(175:182,'uint64'), ...
    'configuration_sha256',message(183:214),'export_sha256',message(215:246), ...
    'original_host_receive_ns',originalHostReceiveNs,'live_time_domain_binding',false);
assert(snapshot.original_sample_hrt_us>0&&snapshot.original_sample_hrt_us<=snapshot.original_publication_hrt_us ...
    &&snapshot.original_publication_hrt_us<=snapshot.original_board_receipt_hrt_us&&all(isfinite(snapshot.raw13_float32)), ...
    'gpenmpcNative:SnapshotSource','Invalid original source ordering/data.');
    function v=value(indices,kind)
        v=typecast(message(indices),kind);[~,~,endian]=computer;if endian=='L',v=swapbytes(v);end;v=v(:);
    end
end
