classdef RflyTaskWindProvider < handle
    % Sample the saved scenario's wind-estimate input causally from task phase.
    properties (SetAccess=private)
        Failed=false
        Failure=""
        TaskSha256
        RotorEffectiveness
        LastReceipt=[]
        LastCanonicalReceipt=[]
    end
    properties (Access=private)
        Reference
        Expected
        LastGeneration=uint64(0)
        LastSampleNs=uint64(0)
        LastReceiveNs=uint64(0)
        LastPollNs=uint64(0)
        LastTaskTime=-Inf
        LastBytes=uint8([])
        LastWind=[]
        CanonicalLast=[]
    end
    methods
        function obj=RflyTaskWindProvider(taskPath,taskSha256,expected)
            assert(isfile(taskPath)&&ischar(taskSha256)&&numel(taskSha256)==64 ...
                &&all(ismember(upper(taskSha256),'0123456789ABCDEF')), ...
                'gpenmpcNative:TaskWindIdentity','Exact task file identity is required.');
            f=fopen(taskPath,'rb');assert(f>=0);c=onCleanup(@()fclose(f));
            bytes=fread(f,Inf,'*uint8');clear c
            md=java.security.MessageDigest.getInstance('SHA-256');md.update(typecast(bytes,'int8'));
            sha=upper(reshape(dec2hex(typecast(md.digest(),'uint8'),2).',1,[]));
            assert(strcmpi(sha,taskSha256),'gpenmpcNative:TaskWindIdentity','Task bytes differ.');
            q=load(taskPath,'physicalTask');assert(isfield(q,'physicalTask'));
            t=q.physicalTask;m=t.execution_method_binding;
            assert(strcmp(m.architecture,'A1_COORDINATED_PHYSICAL') ...
                &&strcmpi(m.effective_configuration_payload_sha256, ...
                    'A859433D0AA774013341444A4B9AE971A34F12B4FB89C0A004B2CB3E013FCEBA') ...
                &&strcmpi(m.gp_model_sha256, ...
                    '4A09E9A3D4818B5555CD3439A6D2133026EEA0FDC2774A1FB17F9E05486E5BB2'), ...
                'gpenmpcNative:TaskWindMethod','Bound physical control configuration and GP model are required.');
            r=t.reference;times=r.global_time_s(:);
            assert(all(isfinite(times))&&times(1)==0&&all(diff(times)>0) ...
                &&isequal(size(r.wind_estimate_xy_mps),[numel(times),2]) ...
                &&all(isfinite(r.wind_estimate_xy_mps(:))) ...
                &&all(isfinite(r.payload_kg(:)))&&all(r.payload_kg(:)>=0), ...
                'gpenmpcNative:TaskWindShape','Complete ordered task estimator input is required.');
            assert(isa(expected.maximum_runtime_age_ns,'uint64')&&expected.maximum_runtime_age_ns>0);
            obj.Reference=r;obj.Expected=expected;obj.TaskSha256=sha;
            obj.RotorEffectiveness=double(t.mission_config.plant_mismatch.thrust_effectiveness_by_rotor(:));
            assert(numel(obj.RotorEffectiveness)==6&&all(isfinite(obj.RotorEffectiveness)) ...
                &&all(obj.RotorEffectiveness>0));
        end
        function [wind,receipt]=observeLocalCanonical(obj,taskTime,legIndex,sourceBytes,originalReceiveNs,nowNs)
            % Explicit new local/RLS1 entry. Legacy observe remains left-hold.
            % Both winds use the canonical whole-task linear exogenousAt;
            % only the estimator is returned as the controller's wind input.
            try
                assert(~obj.Failed,'gpenmpcNative:TaskWindFailed','Prior fault remains latched.');
                assert(isa(nowNs,'uint64')&&isscalar(nowNs)&&isa(originalReceiveNs,'uint64')&&isscalar(originalReceiveNs) ...
                    &&originalReceiveNs>0&&nowNs>=originalReceiveNs&&nowNs-originalReceiveNs<=obj.Expected.maximum_runtime_age_ns, ...
                    'gpenmpcNative:TaskWindClock','Original local source receive time is not renewed.');
                s=gpenmpcNative.RflyLocalSnapshotDecoder(sourceBytes,originalReceiveNs);e=obj.Expected;
                assert(string(s.identity.uid)==string(e.uid)&&s.identity.boot_generation==uint64(e.boot_generation) ...
                    &&double(s.identity.system)==double(e.system_id)&&double(s.identity.component)==double(e.component_id), ...
                    'gpenmpcNative:TaskWindIdentity','RLS1 belongs to a different configured execution session.');
                last=obj.CanonicalLast;
                if ~isempty(last)
                    assert(nowNs>=last.poll_ns,'gpenmpcNative:TaskWindClock','Actual processing clock reversed.');
                    if s.source_generation==last.generation
                        assert(isequal(sourceBytes(:),last.bytes)&&originalReceiveNs==last.rx_ns&&taskTime==last.task_time&&legIndex==last.leg, ...
                            'gpenmpcNative:TaskWindDuplicate','Same local source cannot change time, phase or bytes.');
                        obj.CanonicalLast.poll_ns=nowNs;wind=last.wind;receipt=obj.LastCanonicalReceipt;return
                    end
                    assert(s.source_generation>last.generation&&s.original_sample_us>last.sample_us&&originalReceiveNs>=last.rx_ns ...
                        &&taskTime>=last.task_time,'gpenmpcNative:TaskWindSourceOrder','Original local source/task phase reversed.');
                end
                [actual,estimate,selection]=gpenmpcNative.canonicalSavedTaskWindAt(obj.Reference,taskTime,legIndex);
                wind=struct('source','FROZEN_TASK_WIND_ESTIMATOR','rx_ns',originalReceiveNs,'generation',s.source_generation, ...
                    'valid',true,'estimate_xy_mps',estimate);
                receipt=struct('schema','RFLY_LOCAL_CANONICAL_LINEAR_TASK_WIND_V1','task_sha256',obj.TaskSha256, ...
                    'original_source',s,'original_receive_ns',originalReceiveNs,'selection',selection, ...
                    'actual_plant_wind_xy_mps',actual,'wind_estimate_xy_mps',estimate, ...
                    'source_packet_kind','RLS1_BOARD_LOCAL_ORIGINAL_OBSERVATION','controller_uses_actual_wind',false, ...
                    'online_measurement',false,'publication_authority',false,'timestamps_renewed',false);
                obj.CanonicalLast=struct('generation',s.source_generation,'sample_us',s.original_sample_us,'rx_ns',originalReceiveNs, ...
                    'poll_ns',nowNs,'task_time',taskTime,'leg',legIndex,'bytes',sourceBytes(:),'wind',wind);
                obj.LastCanonicalReceipt=receipt;
            catch problem
                if ~obj.Failed,obj.Failed=true;obj.Failure=string(problem.identifier);end
                rethrow(problem)
            end
        end
        function [wind,receipt]=observe(obj,taskTime,sourceBytes,originalReceiveNs,nowNs)
            try
                assert(~obj.Failed,'gpenmpcNative:TaskWindFailed','Prior fault remains latched.');
                assert(isa(nowNs,'uint64')&&isscalar(nowNs)&&nowNs>=obj.LastPollNs ...
                    &&isa(originalReceiveNs,'uint64')&&isscalar(originalReceiveNs) ...
                    &&originalReceiveNs>0&&originalReceiveNs<=nowNs ...
                    &&nowNs-originalReceiveNs<=obj.Expected.maximum_runtime_age_ns, ...
                    'gpenmpcNative:TaskWindClock','Original source receive time must remain fresh.');
                assert(isnumeric(taskTime)&&isreal(taskTime)&&isscalar(taskTime)&&isfinite(taskTime) ...
                    &&taskTime>=obj.LastTaskTime&&taskTime>=0&&taskTime<=obj.Reference.global_time_s(end), ...
                    'gpenmpcNative:TaskWindPhase','Caller task phase must be monotonic and within the saved task.');
                s=gpenmpcNative.RflySnapshotSample(sourceBytes,originalReceiveNs,obj.Expected);
                g=uint64(s.position_generation);obj.LastPollNs=nowNs;
                if g==obj.LastGeneration
                    assert(isequal(sourceBytes(:),obj.LastBytes)&&originalReceiveNs==obj.LastReceiveNs ...
                        &&taskTime==obj.LastTaskTime,'gpenmpcNative:TaskWindDuplicate', ...
                        'Same source cannot change bytes, receive time or task phase.');
                    wind=obj.LastWind;receipt=obj.LastReceipt;return
                end
                assert(g>obj.LastGeneration&&s.sample_timestamp_ns>obj.LastSampleNs ...
                    &&originalReceiveNs>=obj.LastReceiveNs,'gpenmpcNative:TaskWindSourceOrder', ...
                    'A new evaluation requires an advancing original private source.');
                % Use causal left-hold selection from the saved task.
                index=find(obj.Reference.global_time_s<=taskTime,1,'last');
                wind=struct('source','FROZEN_TASK_WIND_ESTIMATOR','rx_ns',originalReceiveNs, ...
                    'generation',g,'valid',true,'estimate_xy_mps', ...
                    double(obj.Reference.wind_estimate_xy_mps(index,:)).');
                receipt=struct('schema','RFLY_SAVED_TASK_WIND_INPUT_V1','task_sha256',obj.TaskSha256, ...
                    'task_time_s',taskTime,'selected_row',index, ...
                    'selected_row_time_s',obj.Reference.global_time_s(index), ...
                    'leg_index',obj.Reference.leg_index(index),'payload_kg',obj.Reference.payload_kg(index), ...
                    'source_generation',g,'original_sample_timestamp_ns',s.sample_timestamp_ns, ...
                    'original_receive_ns',originalReceiveNs,'wind_estimate_xy_mps',wind.estimate_xy_mps, ...
                    'source_clock_advanced',false,'online_wind_measurement',false, ...
                    'actual_plant_wind_used',false,'plant_truth_state_used',false, ...
                    'same_value_new_source_semantics','NEW_TASK_INPUT_EVALUATION_NOT_NEW_WIND_MEASUREMENT', ...
                    'publication_authority',false);
                obj.LastGeneration=g;obj.LastSampleNs=s.sample_timestamp_ns;obj.LastReceiveNs=originalReceiveNs;
                obj.LastTaskTime=taskTime;obj.LastBytes=sourceBytes(:);obj.LastWind=wind;obj.LastReceipt=receipt;
            catch problem
                if ~obj.Failed,obj.Failed=true;obj.Failure=string(problem.identifier);end
                rethrow(problem)
            end
        end
    end
end
