function [payload,receipt]=RflyOuterPayload(response)
% Serialize the four applied command values from responseStruct.
assert(isstruct(response)&&isscalar(response)&&isfield(response,'schema') ...
    &&any(string(response.schema)==["GPENMPC_BOARD_OUTER_UPDATE_RESPONSE_V1", ...
        "GPENMPC_BOARD_OUTER_ASYNC_POLL_RESPONSE_V1"]), ...
    'gpenmpcNative:ContextOuterSchema','Actual BoardOuterService response required.');
if string(response.schema)=="GPENMPC_BOARD_OUTER_ASYNC_POLL_RESPONSE_V1"
    assert(isfield(response,'status')&&any(string(response.status)== ...
        ["FRESH_RESULT_COMMITTED","DEADLINE_FALLBACK_COMMITTED"]), ...
        'gpenmpcNative:ContextOuterNotCommitted','An async pending/drained result is not a command.');
end
assert(isequal(response.publication_allowed,true)&&isequal(response.hard_invalid,false)&&isequal(response.failed,false), ...
    'gpenmpcNative:ContextOuterUnavailable','Suppressed/hard-invalid outer command cannot be serialized.');
% A canonical soft solver failure can legitimately select continuity; do not
% introduce a new decision_success gate or substitute a different controller.
assert(isa(response.phase_acceleration_s_inv,'double')&&isscalar(response.phase_acceleration_s_inv) ...
    &&isa(response.outer_acceleration_correction_f_mps2,'double')&&numel(response.outer_acceleration_correction_f_mps2)==3, ...
    'gpenmpcNative:ContextOuterType','Actual binary64 command fields required.');
payload=[response.phase_acceleration_s_inv;response.outer_acceleration_correction_f_mps2(:)];
assert(all(isfinite(payload)),'gpenmpcNative:ContextOuterFinite','Nonfinite outer command.');
receipt=struct('scope','ACTUAL_APPLIED_PHASE_ACCELERATION_AND_CORRECTION_F_ONLY', ...
    'applied_command_source',string(response.applied_command_source), ...
    'generation',response.generation,'complete_solver_audit_included',false,'clock_binding_provided',false);
end
