function view=rflyCanonicalDeliveryTimeView(bundle,coordinator,trajectory)
% Read the control-service phase to select scenario wind and reference rows.
arguments
    bundle (1,1) struct
    coordinator (1,1) struct
    trajectory (1,1) struct
end
assert(isfield(bundle,'legs')&&numel(bundle.legs)==5 ...
    &&isfield(coordinator,'service')&&isfield(coordinator,'state') ...
    &&isfield(coordinator,'failed')&&isequal(coordinator.failed,false), ...
    'gpenmpcNative:DeliveryClockOwner','A nonfailed original coordinator status is required.');
s=coordinator.service;
assert(all(isfield(s,{'leg_index','phase_s','payload_kg','outer_suspended'})) ...
    &&isnumeric(s.leg_index)&&isscalar(s.leg_index)&&isfinite(s.leg_index) ...
    &&s.leg_index==fix(s.leg_index)&&s.leg_index>=1&&s.leg_index<=5 ...
    &&isnumeric(s.phase_s)&&isreal(s.phase_s)&&isscalar(s.phase_s) ...
    &&isfinite(s.phase_s)&&s.phase_s>=0, ...
    'gpenmpcNative:DeliveryClockState','Original global leg and finite causal phase are required.');
state=string(coordinator.state);
assert(isscalar(state)&&any(state==["UNPREPARED","PREPARING","PREPARED_PAUSED", ...
    "FLIGHT","NATIVE_LAND","GROUND"]),'gpenmpcNative:DeliveryClockLifecycle', ...
    'Unknown lifecycle cannot select saved task inputs.');
paused=any(state==["NATIVE_LAND","GROUND"]);
assert(~paused||isequal(s.outer_suspended,true), ...
    'gpenmpcNative:DeliveryClockSuspension','LAND/ground must already suspend the actual control service.');
leg=bundle.legs{s.leg_index};meta=leg.meta;
assert(isequal(s.payload_kg,meta.payload_kg),'gpenmpcNative:DeliveryClockPayload', ...
    'Saved task selection cannot perform or pretend a payload change.');
assert(isfield(trajectory,'schema')&&isfield(trajectory,'total_duration_s'), ...
    'gpenmpcNative:DeliveryClockTrajectory','The actually bound shared trajectory is required.');
offset=0;
if s.leg_index==1
    assert(strcmp(trajectory.schema,'RFLY_CANONICAL_INITIAL_TAKEOFF_SHARED_REFERENCE_V1') ...
        &&isfield(trajectory,'canonical_task_phase_offset_s') ...
        &&trajectory.canonical_task_phase_offset_s==25 ...
        &&trajectory.preparation_prefix_duration_s==25, ...
        'gpenmpcNative:DeliveryClockInitialPrefix','First-leg phase includes the actual shared 25-s preparation reference.');
    offset=25;
else
    assert(strcmp(trajectory.schema,'RFLY_CAUSAL_RELAUNCH_MATCHED_SAMPLED_REFERENCE_V1'), ...
        'gpenmpcNative:DeliveryClockRelaunch','Subsequent flights use their captured shared relaunch reference.');
end
assert(trajectory.total_duration_s==offset+meta.trajectory_duration_s, ...
    'gpenmpcNative:DeliveryClockDuration','No task-duration extension is hidden in the time view.');
q=double(s.phase_s);
local=max(0,q-offset);overrun=max(0,local-meta.trajectory_duration_s);
local=min(local,meta.trajectory_duration_s);
% Retain exact stored terminal time: recomputing start+(end-start) can add
% a binary64 ulp. Interior remains direct addition, not sample snapping.
if local==meta.trajectory_duration_s
    globalTime=meta.saved_global_end_s;
else
    globalTime=meta.saved_global_start_s+local;
end
row=find(leg.local_time_s<=local,1,'last');
view=struct('schema','RFLY_CANONICAL_DELIVERY_TIME_VIEW_V1', ...
    'owner','ACTUAL_CANONICAL_CONTROL_SERVICE_PHASE__NO_SECOND_CLOCK', ...
    'global_leg_index',s.leg_index,'coordinator_state',char(state), ...
    'controller_phase_s',q,'initial_preparation_offset_s',offset, ...
    'inside_initial_preparation',s.leg_index==1&&q<offset, ...
    'saved_leg_phase_s',local,'saved_task_time_s',globalTime, ...
    'controller_phase_past_saved_end_s',overrun, ...
    'saved_phase_code',leg.phase_code(row),'saved_source_row',leg.source_indices(row), ...
    'payload_kg',s.payload_kg,'outer_already_suspended',paused, ...
    'saved_descent_phase_reached',isfinite(meta.planned_descent_start_phase_s) ...
        &&local>=meta.planned_descent_start_phase_s, ...
    'actual_land_authorized',false,'actual_ground_confirmed',false, ...
    'payload_write_authorized',false,'task_completion_proven',false, ...
    'source_clock_advanced',false,'wall_time_used',false,'plant_truth_used',false);
end
