function association=RflySessionAssociationDecoder(prepareFrames,confirmFrames,request,authorization,dialect)
% Decode CanonicalSessionEntry text from SERIAL_CONTROL.
% The owner supplies challenge, submit times and fixed identity/configuration expectations.
% Authorization is an operator record, separate from telemetry.
% Without confirmFrames, return NOT_CONFIRMED preparation data for digest confirmation.
for name={'original_prepare_submit_ns','uid'}
    exactU64(request.(name{1}));
end
assert(isa(request.original_host_challenge,'uint64')&&numel(request.original_host_challenge)==2 ...
    &&any(request.original_host_challenge),'gpenmpcNative:SessionChallenge','Original challenge required.');
for name={'system','component','host_system','host_component'}
    v=request.(name{1});assert(isa(v,'uint8')&&isscalar(v)&&v>0,'gpenmpcNative:SessionIdentity','Exact byte identity required.');
end
local=localRequest(request);preparedState=1;confirmedState=2;
config=shaText(request.configuration_payload_sha256);parameter='';
if local,preparedState=2;confirmedState=3;else,parameter=shaText(request.approved_parameter_sha256);end
[p,prepare]=receipt(prepareFrames,request,dialect);
assert(request.original_prepare_submit_ns<=prepare.first_original_host_receive_ns, ...
    'gpenmpcNative:SessionHostOrder','Prepare receipt predates its original command.');
assert(p.state==preparedState&&p.registered==1&&p.echo_confirmed==0&&p.declared_isolation==0 ...
    &&p.declaration_is_sensor_proof==0&&p.session_fault==0&&p.start_requests==0&&p.stop_requests==0, ...
    'gpenmpcNative:SessionState','Unconfirmed Registered receipt required.');
echo=checkedEcho(p,request,config,parameter);
if isempty(confirmFrames)
    association=struct('schema','GPENMPC_RFLY_PREPARED_SESSION_RECEIPT_V1', ...
        'registration_result','Registered','echo_confirmation_result','NOT_CONFIRMED', ...
        'echo',echo,'execution_session_sha256',p.session_sha,'approved_parameter_sha256',parameter, ...
        'local_full_inner',local,'parameter_identity_board_echoed',~local, ...
        'original_request',request,'prepare_receipt',prepare, ...
        'original_host_receive_ns',prepare.last_original_host_receive_ns, ...
        'physical_authorization',false,'publication_authority',false, ...
        'live_registration_proven',false,'transport_source_authenticated',false);
    return
end
exactU64(request.original_confirm_submit_ns);
assert(isstruct(authorization)&&isscalar(authorization) ...
    &&string(authorization.source)=="OperatorUsbIsolationDeclaration" ...
    &&isfield(authorization,'original_record')&&~isempty(authorization.original_record), ...
    'gpenmpcNative:SessionDeclaration','The physical setup declaration and its source record are required.');
recordSha=shaText(authorization.physical_setup_record_sha256);
confirmSessionSha=shaText(request.original_confirm_session_sha256);
confirmRecordSha=shaText(request.confirmed_physical_setup_record_sha256);
assert(strcmp(confirmRecordSha,recordSha),'gpenmpcNative:SessionDeclarationCommand', ...
    'The confirm command must match the physical setup record digest.');
[c,confirm]=receipt(confirmFrames,request,dialect);
assert(request.original_prepare_submit_ns<=prepare.first_original_host_receive_ns ...
    &&prepare.last_original_host_receive_ns<request.original_confirm_submit_ns ...
    &&request.original_confirm_submit_ns<=confirm.first_original_host_receive_ns, ...
    'gpenmpcNative:SessionHostOrder','Original prepare/confirm HOST events must be ordered.');
assert(p.state==preparedState&&p.registered==1&&p.echo_confirmed==0&&p.declared_isolation==0 ...
    &&c.state==confirmedState&&c.registered==1&&c.echo_confirmed==1&&c.declared_isolation==1 ...
    &&p.declaration_is_sensor_proof==0&&c.declaration_is_sensor_proof==0 ...
    &&p.session_fault==0&&c.session_fault==0 ...
    &&p.start_requests==0&&c.start_requests==0&&p.stop_requests==0&&c.stop_requests==0, ...
    'gpenmpcNative:SessionState','Registered then Confirmed receipts required before start/stop.');
immutable={'challenge','uid','system','component','registration_hrt_us','session_generation', ...
    'link_generation','semantics','config_sha','session_sha'};
if local,immutable=[immutable,{'task_sha','leg'}];else,immutable{end+1}='parameter_sha';end
for k=1:numel(immutable)
    assert(isequal(p.(immutable{k}),c.(immutable{k})), ...
        'gpenmpcNative:SessionEchoMismatch','Prepare/confirm changed original %s.',immutable{k});
end
assert(strcmp(confirmSessionSha,c.session_sha), ...
    'gpenmpcNative:SessionDigest','Exact original RSE1 digest and original confirm argument must match.');
association=struct('schema','GPENMPC_RFLY_REGISTERED_SESSION_ASSOCIATION_V1', ...
    'registration_result','Registered','echo_confirmation_result','Confirmed','echo',echo, ...
    'original_host_challenge',request.original_host_challenge(:), ...
    'original_host_receive_ns',confirm.last_original_host_receive_ns, ...
    'execution_session_sha256',c.session_sha,'approved_parameter_sha256',parameter, ...
    'local_full_inner',local,'parameter_identity_board_echoed',~local, ...
    'provenance','ORIGINAL_SERIAL_CONTROL_RFLY_SESSION_RECEIPT_PAIR', ...
    'original_request',request,'prepare_receipt',prepare,'confirm_receipt',confirm, ...
    'physical_declaration',authorization,'physical_setup_record_sha256',recordSha, ...
    'human_declaration_session_sha256',c.session_sha,'board_reported_human_declaration_bound',true, ...
    'declaration_is_sensor_proof',false,'physical_authorization',false,'publication_authority',false, ...
    'transport_source_authenticated',false,'live_registration_proven',false, ...
    'board_confirm_timestamp_present',false,'cross_boot_unique_identity_claim',false, ...
    'board_echoes_user_record_sha256',false,'original_confirm_command_record_bound',true, ...
    'legacy_boot_generation_semantics','BOARD_REGISTERED_PROCESS_EXECUTION_SESSION_GENERATION_NOT_BOOT_COUNTER');
end

function echo=checkedEcho(c,request,config,parameter)
assert(isequal(c.challenge,request.original_host_challenge(:))&&c.uid==request.uid ...
    &&c.system==request.system&&c.component==request.component&&c.semantics==1 ...
    &&strcmp(c.config_sha,config), ...
    'gpenmpcNative:SessionRequestedTuple','Receipt differs from original challenge/frozen identity/config.');
if localRequest(request)
    assert(strcmp(c.task_sha,shaText(request.task_sha256))&&c.leg==request.leg_index, ...
        'gpenmpcNative:SessionLocalTask','Actual local task/explicit leg mismatch.');
else
    assert(strcmp(c.parameter_sha,parameter),'gpenmpcNative:SessionRequestedTuple','Parameter identity mismatch.');
end
for name={'registration_hrt_us','session_generation','link_generation'},exactU64(c.(name{1}));end
echo=struct('identity_semantics','BoardRegisteredExecutionSessionGenerationV1', ...
    'host_challenge',c.challenge,'uid',c.uid,'system',uint8(c.system),'component',uint8(c.component), ...
    'board_registration_hrt_us',c.registration_hrt_us,'process_session_generation',c.session_generation, ...
    'link_lifecycle_generation',c.link_generation,'configuration_payload_sha256',c.config_sha);
bytes=[uint8('RSE1').';uint8(1);be(echo.host_challenge);be(echo.uid);echo.system;echo.component; ...
    be(echo.board_registration_hrt_us);be(echo.process_session_generation); ...
    be(echo.link_lifecycle_generation);uint8(sscanf(config,'%2x'))];
md=java.security.MessageDigest.getInstance('SHA-256');md.update(typecast(bytes,'int8'));
calculated=upper(reshape(dec2hex(typecast(md.digest(),'uint8'),2).',1,[]));
assert(strcmp(calculated,c.session_sha),'gpenmpcNative:SessionDigest','Exact original RSE1 digest mismatch.');
end

function [fields,out]=receipt(frames,request,dialect)
assert(isstruct(frames)&&~isempty(frames),'gpenmpcNative:SessionFrames','Original complete frame records required.');
parts=cell(numel(frames),1);times=zeros(numel(frames),1,'uint64');targets=zeros(numel(frames),2,'uint8');
rawAvailable=false(numel(frames),1);targetsKnown=false(numel(frames),1);
for k=1:numel(frames)
    times(k)=exactU64(frames(k).original_host_receive_ns);
    if isfield(frames,'raw_frame')&&~isempty(frames(k).raw_frame)
        assert(~isfield(frames,'decoded_message')||isempty(frames(k).decoded_message), ...
            'gpenmpcNative:SessionFrame','Ambiguous raw/decoded record.');
        raw=frames(k).raw_frame;
        assert(isa(raw,'uint8')&&isvector(raw)&&numel(raw)>=12, ...
            'gpenmpcNative:SessionFrame','One original complete MAVLink2 frame required.');
        raw=raw(:);n=double(raw(2));signed=bitand(raw(3),uint8(1))~=0;
        assert(raw(1)==253&&bitand(raw(3),uint8(254))==0&&numel(raw)==12+n+13*double(signed) ...
            &&raw(6)==request.system&&raw(7)==request.component ...
            &&isequal(raw(8:10),uint8([126;0;0]))&&n<=81, ...
            'gpenmpcNative:SessionFrame','Unexpected frame length/version/message/origin.');
        [message,status]=deserializemsg(dialect,raw.',OutputAllMessage=true);
        assert(numel(message)==1&&status==0&&message.MsgID==126, ...
            'gpenmpcNative:SessionFrameCrc','Official MAVLink decoder rejected original frame.');
        % v1.16 extensions are absent from the installed older MATLAB dialect.
        % Read ONLY after its CRC check, at official generated offsets 79/80.
        payload=zeros(81,1,'uint8');payload(1:n)=raw(11:10+n);
        targets(k,:)=payload(80:81).';targetsKnown(k)=true;rawAvailable(k)=true;
    else
        % Use the five fields exposed by Subscriber.parsePackets without reserialization.
        assert(isfield(frames,'decoded_message')&&isfield(frames,'decoded_source') ...
            &&string(frames(k).decoded_source)=="ORIGINAL_MAVLINKIO_SERIAL_CONTROL_CALLBACK" ...
            &&isfield(frames,'raw_frame_available')&&isequal(frames(k).raw_frame_available,false), ...
            'gpenmpcNative:SessionCallback','Original callback provenance required.');
        message=frames(k).decoded_message;
        assert(isstruct(message)&&isscalar(message)&&all(isfield(message,{'MsgID','SystemID','ComponentID','Seq','Payload'})) ...
            &&message.MsgID==126&&message.SystemID==request.system&&message.ComponentID==request.component ...
            &&isscalar(message.Seq)&&isnumeric(message.Seq)&&isfinite(message.Seq) ...
            &&message.Seq>=0&&message.Seq<=255&&fix(message.Seq)==message.Seq, ...
            'gpenmpcNative:SessionCallback','Original callback header tuple required.');
        if all(isfield(message.Payload,{'target_system','target_component'}))
            targets(k,:)=[message.Payload.target_system message.Payload.target_component];targetsKnown(k)=true;
        end
    end
    p=message.Payload;
    assert(p.device==10&&p.flags==1&&p.baudrate==0&&p.timeout==0&&p.count>=0&&p.count<=70 ...
        &&fix(p.count)==p.count&&isa(p.data,'uint8')&&numel(p.data)==70, ...
        'gpenmpcNative:SessionShell','Actual SERIAL_CONTROL shell reply required.');
    assert(~targetsKnown(k)||((targets(k,1)==0||targets(k,1)==request.host_system) ...
        &&(targets(k,2)==0||targets(k,2)==request.host_component)), ...
        'gpenmpcNative:SessionTarget','Shell reply targets a different original HOST.');
    parts{k}=reshape(uint8(p.data(1:double(p.count))),[],1);
    if k>1,assert(times(k)>=times(k-1),'gpenmpcNative:SessionFrameTime','Original HOST receive time reversed.');end
end
shell=vertcat(parts{:});text=char(shell.');
local=localRequest(request);label='RFLY_SESSION';if local,label='RFLY_LOCAL_SESSION';end
starts=regexp(text,['(?m)^' label ' ']);
lines=regexp(text,['(?m)^' label ' [^\r\n]*(?:\r?\n)'],'match');
assert(numel(starts)==1&&numel(lines)==1, ...
    'gpenmpcNative:SessionLine','Exactly one complete unambiguous RFLY_SESSION line required.');
line=regexprep(lines{1},'\r?\n$','');tokens=strsplit(line,' ');
names={'state','challenge','uid','system','component','registration_hrt_us','session_generation', ...
    'link_generation','semantics','config_sha','session_sha'};
if local,names=[names,{'task_sha','leg'}];else,names{end+1}='parameter_sha';end
names=[names,{'registered','echo_confirmed', ...
    'declared_isolation','declaration_is_sensor_proof','session_fault','start_requests','stop_requests'}];
assert(numel(tokens)==numel(names)+1,'gpenmpcNative:SessionFields','Missing or extra session fields.');
fields=struct();
for k=1:numel(names)
    token=regexp(tokens{k+1},'^([a-z_]+)=([0-9A-Fa-f]+)$','tokens','once');
    assert(~isempty(token)&&strcmp(token{1},names{k}),'gpenmpcNative:SessionFields','Unexpected, duplicated or malformed field.');
    name=names{k};value=token{2};
    if strcmp(name,'challenge')
        assert(numel(value)==32,'gpenmpcNative:SessionChallenge','Challenge must be exactly 32 hex characters.');
        fields.(name)=[parseInteger(value(1:16),16);parseInteger(value(17:32),16)];
    elseif endsWith(name,'_sha'),fields.(name)=value;
    else,fields.(name)=parseInteger(value,10);
    end
end
% Treat Empty or Retired unregistered receipts as failed preparation;
% retain the original diagnostic line.
if local&&ismember(fields.state,uint64([0 5]))&&fields.registered==0
    error('gpenmpcNative:SessionNotRegistered', ...
        'Board reported an unregistered local session (state=%u, registered=0, session_fault=%u). Original receipt:\n%s', ...
        fields.state,fields.session_fault,lines{1});
end
for k=1:numel(names)
    if endsWith(names{k},'_sha'),fields.(names{k})=shaText(fields.(names{k}));end
end
out=struct('original_frames',frames,'original_shell_bytes',shell,'original_session_line_bytes',uint8(lines{1}).', ...
    'parsed_fields',fields,'first_original_host_receive_ns',times(1),'last_original_host_receive_ns',times(end), ...
    'original_frame_receive_ns',times,'serial_control_target_extensions',targets, ...
    'serial_control_target_extensions_known',targetsKnown,'raw_frame_available',rawAvailable, ...
    'mavlink_crc_checked',all(rawAvailable),'original_mavlinkio_decoded_callback',~rawAvailable, ...
    'mavlink_signature_authenticated',false);
end
function v=exactU64(v)
assert(isa(v,'uint64')&&isscalar(v)&&v>0,'gpenmpcNative:SessionExactUint64','Original positive uint64 required.');
end
function value=localRequest(request)
value=false;
if isfield(request,'local_full_inner')
    assert(isequal(request.local_full_inner,true),'gpenmpcNative:SessionLocalEntry','Explicit local entry selection required.');
    assert(isfield(request,'leg_index')&&isa(request.leg_index,'uint8')&&isscalar(request.leg_index) ...
        &&ismember(request.leg_index,uint8(1:5))&&isfield(request,'task_sha256'), ...
        'gpenmpcNative:SessionLocalTask','Explicit task and leg required.');
    value=true;
end
end
function v=parseInteger(s,base)
assert(~isempty(s),'gpenmpcNative:SessionInteger','Empty integer.');v=uint64(0);b=uint64(base);
for c=s
    if c>='0'&&c<='9',d=uint64(c-'0');
    elseif c>='a'&&c<='f',d=uint64(c-'a'+10);
    elseif c>='A'&&c<='F',d=uint64(c-'A'+10);
    else,error('gpenmpcNative:SessionInteger','Invalid integer character.');end
    assert(d<b&&v<=idivide(intmax('uint64')-d,b,'floor'), ...
        'gpenmpcNative:SessionInteger','Integer malformed or uint64 overflow.');
    v=v*b+d;
end
end
function s=shaText(s)
assert((ischar(s)&&isrow(s))||(isstring(s)&&isscalar(s)),'gpenmpcNative:SessionSha','SHA text required.');
s=upper(char(s));assert(~isempty(regexp(s,'^[0-9A-F]{64}$','once'))&&any(s~='0'), ...
    'gpenmpcNative:SessionSha','Exact nonzero SHA256 required.');
end
function b=be(v)
[~,~,endian]=computer;if endian=='L',v=swapbytes(v);end;b=reshape(typecast(v(:),'uint8'),[],1);
end
