classdef RflyCanonicalEnvironmentService < handle
    % Send 28-double environment frames through the bound IO owner.
    % The caller services heartbeat separately at 100 ms.
    % Retain counters, latest outcome and first failure; IO stores the ENV_TX bytes.
    properties (SetAccess=private)
        Failed=false
        FailureCode=''
        Closed=false
    end
    properties (Access=private)
        Io
        Config
        Contract
        FrameGeneration=0
        SentCount=uint64(0)
        AttemptCount=uint64(0)
        WaitCount=uint64(0)
        LastSourceS=-Inf
        LastBoardLowerS=-Inf
        LastSnapshotS=-Inf
        PayloadGeneration=0
        PayloadKg=NaN
        ReleaseGeneration=0
        PayloadFirstFrame=0
        ClampCount=uint64(0)
        MaximumRawRegressionS=0
        LastAttempt=struct()
        LastOutcome=struct()
        FirstFailure=struct()
        CanonicalTask=[]
        CanonicalTaskCache=[]
        CanonicalTaskSha=''
        CanonicalConfigurationSha=''
        LastWindSelection=struct()
        ManualDisturbance=false
        GustRandom=[]
        Gust=zeros(2,1)
        GustEpochS=NaN
        GustLastS=NaN
    end
    methods
        function obj=RflyCanonicalEnvironmentService(io,cfg,canonicalTaskSource)
            assert(isstruct(io)&&isscalar(io)&&all(isfield(io,{'sendPlantEnvironment','now'})) ...
                &&isa(io.sendPlantEnvironment,'function_handle')&&isa(io.now,'function_handle'), ...
                'gpenmpcNative:EnvironmentIo','The existing IO environment sender and clock are required.');
            assert(isstruct(cfg)&&isscalar(cfg)&&all(isfield(cfg, ...
                {'target_system','target_component','heartbeat_max_age_s','landed_max_age_s','delivery_environment_contract'})), ...
                'gpenmpcNative:EnvironmentConfig','Existing target, receive-age bounds and environment contract required.');
            c=cfg.delivery_environment_contract;
            assert(all(isfield(c,{'expected_session_token','initial_payload_kg','payload_by_generation_kg','mass_by_generation_kg'})) ...
                &&numel(c.payload_by_generation_kg)==5&&numel(c.mass_by_generation_kg)==5 ...
                &&all(isfinite(c.payload_by_generation_kg))&&all(diff(c.payload_by_generation_kg)<0) ...
                &&c.initial_payload_kg==c.payload_by_generation_kg(1) ...
                &&isfinite(cfg.heartbeat_max_age_s)&&cfg.heartbeat_max_age_s>0 ...
                &&isfinite(cfg.landed_max_age_s)&&cfg.landed_max_age_s>0, ...
                'gpenmpcNative:EnvironmentConfig','The unchanged five-payload contract and positive original receive bounds are required.');
            obj.Io=io;obj.Config=cfg;obj.Contract=c;obj.PayloadKg=c.initial_payload_kg;
            obj.ManualDisturbance=isfield(cfg,'local_short') ...
                &&isfield(cfg.local_short,'component_initialization')&&cfg.local_short.component_initialization ...
                &&isfield(cfg.local_short,'service_cfg')&&isfield(cfg.local_short.service_cfg,'operator_reference');
            if obj.ManualDisturbance
                % Use an independent random stream for environmental gusts.
                obj.GustRandom=RandStream('mt19937ar','Seed',20260914);
            end
            if nargin>=3
                assert(isstruct(canonicalTaskSource)&&isscalar(canonicalTaskSource) ...
                    &&all(isfield(canonicalTaskSource,{'path','sha256'}))&&validSha(canonicalTaskSource.sha256) ...
                    &&strcmpi(taskFileSha(canonicalTaskSource.path),canonicalTaskSource.sha256), ...
                    'gpenmpcNative:EnvironmentCanonicalTask','Original task file identity is required.');
                q=load(canonicalTaskSource.path,'physicalTask');t=q.physicalTask;m=t.execution_method_binding;
                assert(strcmp(m.architecture,'A1_COORDINATED_PHYSICAL') ...
                    &&strcmpi(m.effective_configuration_payload_sha256,'A859433D0AA774013341444A4B9AE971A34F12B4FB89C0A004B2CB3E013FCEBA') ...
                    &&strcmpi(m.gp_model_sha256,'4A09E9A3D4818B5555CD3439A6D2133026EEA0FDC2774A1FB17F9E05486E5BB2'), ...
                    'gpenmpcNative:EnvironmentCanonicalTask','The passport method identity is required.');
                obj.CanonicalTask=t.reference;obj.CanonicalTaskSha=upper(char(canonicalTaskSource.sha256));
                obj.CanonicalConfigurationSha=m.effective_configuration_payload_sha256;
                bound=canonicalTaskSource;bound.configuration_sha256=obj.CanonicalConfigurationSha;
                if isfield(bound,'cached_asset')
                    assert(isa(bound.cached_asset,'gpenmpcNative.RflyLocalTaskAsset'));
                    obj.CanonicalTaskCache=bound.cached_asset;
                else
                    obj.CanonicalTaskCache=gpenmpcNative.RflyLocalTaskAsset(bound);
                end
                obj.CanonicalTaskCache.read(bound);
            end
        end
        function r=stepCanonical(obj,snapshot,timeView,referenceNed,intent,identityReceipt,expectedIdentity)
            assert(~isempty(obj.CanonicalTask),'gpenmpcNative:EnvironmentCanonicalTask', ...
                'Canonical entry requires the constructor-bound original task.');
            r=obj.step(snapshot,timeView,referenceNed,intent,identityReceipt,expectedIdentity);
        end
        function r=step(obj,snapshot,timeView,referenceNed,intent,identityReceipt,expectedIdentity)
            % Keep the control failure latched while servicing fresh environment frames
            % for native LAND. Recover safety service only from queue or board-age faults
            % after freshness validation.
            safetyOnly=isstruct(intent)&&all(isfield(intent,{'lifecycle_phase', ...
                'task_clock_paused','payload_update_requested','payload_kg', ...
                'payload_generation','release_generation'})) ...
                &&strcmp(intent.lifecycle_phase,'NATIVE_LAND') ...
                &&isequal(intent.task_clock_paused,true)&&isequal(intent.payload_update_requested,false) ...
                &&intent.payload_kg==obj.PayloadKg&&intent.payload_generation==obj.PayloadGeneration ...
                &&intent.release_generation==obj.ReleaseGeneration;
            safetyAfterReceiveFailure=safetyOnly&&any(strcmp(obj.FailureCode, ...
                {'gpenmpcNative:EnvironmentQueuedSnapshotExpired','gpenmpcNative:EnvironmentBoardEvidenceStale'}));
            assert(~obj.Closed&&(~obj.Failed||safetyAfterReceiveFailure),'gpenmpcNative:EnvironmentClosed', ...
                'Failed control cannot resume; only freshly revalidated native-LAND environment after HOST receive-age failure is allowed.');
            try
                assert(isstruct(snapshot)&&isscalar(snapshot)&&isfield(snapshot,'now_s') ...
                    &&finite(snapshot.now_s)&&snapshot.now_s>=obj.LastSnapshotS, ...
                    'gpenmpcNative:EnvironmentTime','Original IO snapshot time must not reverse.');
                obj.LastSnapshotS=snapshot.now_s;
                obj.identity(snapshot,identityReceipt,expectedIdentity);
                assert(isstruct(timeView)&&isscalar(timeView)&&strcmp(timeView.schema,'RFLY_CANONICAL_DELIVERY_TIME_VIEW_V1') ...
                    &&finite(timeView.saved_task_time_s)&&timeView.saved_task_time_s>=0 ...
                    &&isequal(timeView.wall_time_used,false)&&isequal(timeView.plant_truth_used,false), ...
                    'gpenmpcNative:EnvironmentTimeView','Use the canonical saved-task time view, not an old mission/wall clock.');
                obj.intent(intent,snapshot);
                plantWind=struct();
                if ~isempty(obj.CanonicalTask)
                    plantWind=obj.canonicalWind(timeView,referenceNed,intent,expectedIdentity);
                end
                r=obj.outcome('WAITING_FOR_ORIGINAL_MODEL_CLOCK');
                if ~isfield(snapshot,'model_ready')||~isequal(snapshot.model_ready,true) ...
                    ||~isfield(snapshot,'clock_valid')||~isequal(snapshot.clock_valid,true)
                    assert(obj.SentCount==0,'gpenmpcNative:EnvironmentModelClock','An active environment lost original model/clock validity.');
                    obj.WaitCount=obj.WaitCount+uint64(1);obj.LastOutcome=r;return
                end
                % A decoded board-controller stop is NOT a sensor/plant
                % failure. It may coexist with the native safety handoff;
                % clock/model/source validity below remain mandatory.
                stoppedController=safetyOnly&&isfield(snapshot,'fatal') ...
                    &&~isempty(regexp(snapshot.fatal,'^BOARD_LOCAL_CONTEXT_STOPPED:[1-9][0-9]*$','once'));
                assert(isfield(snapshot,'fatal')&&(isempty(snapshot.fatal)||stoppedController) ...
                    &&isfield(snapshot,'model_diagnostic')&&isfield(snapshot.model_diagnostic,'decoded') ...
                    &&isfield(snapshot.model_diagnostic.decoded,'sim_time_s'), ...
                    'gpenmpcNative:EnvironmentModelClock','Healthy original model diagnostic required.');
                simS=snapshot.model_diagnostic.decoded.sim_time_s;
                assert(finite(simS)&&simS>=0&&simS>=obj.LastSourceS, ...
                    'gpenmpcNative:EnvironmentSource','Original model time reversed or invalid.');
                nowS=obj.Io.now();
                assert(finite(nowS)&&nowS>=snapshot.now_s, ...
                    'gpenmpcNative:EnvironmentTime','Actual same-IO send-side time cannot precede the snapshot.');
                hb=originalFresh(nowS,snapshot.heartbeat_rx_s,obj.Config.heartbeat_max_age_s);
                ext=originalFresh(nowS,snapshot.extended_rx_s,obj.Config.landed_max_age_s);
                assert(hb&&ext,'gpenmpcNative:EnvironmentBoardEvidenceStale','Original board receive evidence is stale or future.');
                r.payload_ack=obj.ack(snapshot,intent);
                if simS==obj.LastSourceS
                    r.status='NO_NEW_MODEL_SOURCE_NO_SEND';obj.WaitCount=obj.WaitCount+uint64(1);obj.LastOutcome=r;return
                end
                if obj.ManualDisturbance
                    % Drive the manual-mode 1.2 s filtered Gaussian gust and slow variation
                    % from model time.
                    if isnan(obj.GustEpochS),obj.GustEpochS=simS;obj.GustLastS=simS;end
                    elapsed=simS-obj.GustEpochS;dt=simS-obj.GustLastS;
                    a=exp(-dt/1.2);
                    obj.Gust=a*obj.Gust+.45*sqrt(max(0,1-a*a))*randn(obj.GustRandom,2,1);
                    obj.GustLastS=simS;
                    gust=min(.9,max(-.9,obj.Gust));
                    periodic=.7*sin(2*pi*elapsed./[12;17]);
                    applied=plantWind.actual_wind_ned_xy_mps+(1-exp(-elapsed/3))*(periodic+gust);
                    plantWind.actual_wind_ned_xy_mps=applied;
                    obj.LastWindSelection.manual_disturbance=struct('profile','FILTERED_RANDOM_GUST_AND_SLOW_PERIODIC', ...
                        'model_time_s',simS,'seed',20260914,'filter_time_s',1.2, ...
                        'gust_stationary_std_mps',.45,'gust_clip_mps',.9,'periodic_amplitude_mps',.7, ...
                        'periods_s',[12 17],'actual_wind_xy_mps',applied);
                end
                % Enforce the 0.25 s environment age from its source timestamp.
                assert(nowS-snapshot.now_s<=.25,'gpenmpcNative:EnvironmentQueuedSnapshotExpired', ...
                    'Known HOST queue delay alone already exceeds the original 250-ms environment budget.');
                assert(obj.FrameGeneration<2^32-1,'gpenmpcNative:EnvironmentGeneration','Environment frame generation exhausted.');
                next=obj.FrameGeneration+1;
                v=gpenmpcTaskIo.makePlantEnvironmentFrameFromSnapshot(snapshot,referenceNed, ...
                    intent.payload_kg,intent.payload_generation,intent.release_generation,next, ...
                    timeView.saved_task_time_s,intent.task_clock_paused,string(intent.lifecycle_phase), ...
                    obj.Contract.expected_session_token,true,hb,ext,plantWind);
                originalBoardLower=v.board_min_rx_io_time_s;
                if originalBoardLower<obj.LastBoardLowerS
                    obj.ClampCount=obj.ClampCount+uint64(1);
                    obj.MaximumRawRegressionS=max(obj.MaximumRawRegressionS,obj.LastBoardLowerS-originalBoardLower);
                    v.board_min_rx_io_time_s=obj.LastBoardLowerS;
                end
                % Retain the greatest observed mapped lower bound.
                obj.LastAttempt=struct('frame',v,'send_attempted',true,'send_returned',false, ...
                    'original_snapshot_io_time_s',snapshot.now_s,'send_check_io_time_s',nowS, ...
                    'original_model_time_s',simS,'original_heartbeat_rx_s',snapshot.heartbeat_rx_s, ...
                    'original_extended_rx_s',snapshot.extended_rx_s,'raw_board_lower_bound_s',originalBoardLower, ...
                    'retained_board_lower_bound_s',v.board_min_rx_io_time_s, ...
                    'caller_verified_same_io_identity',identityReceipt,'identity_independently_verified_here',false, ...
                    'original_task_wind_selection',obj.LastWindSelection);
                obj.AttemptCount=obj.AttemptCount+uint64(1);
                sent=obj.Io.sendPlantEnvironment(v); % The ONLY sending API.
                obj.LastAttempt.send_returned=true;obj.LastAttempt.io_receipt=sent;
                assert(isstruct(sent)&&isscalar(sent)&&all(isfield(sent, ...
                    {'sent_s','generation','payload_generation','service_release_generation','bytes'})) ...
                    &&sent.generation==next&&sent.payload_generation==intent.payload_generation ...
                    &&sent.service_release_generation==intent.release_generation&&sent.bytes==232 ...
                    &&finite(sent.sent_s)&&sent.sent_s>=nowS, ...
                    'gpenmpcNative:EnvironmentSendReceipt','Actual existing-IO send receipt does not match the attempted frame.');
                if obj.SentCount==0||intent.payload_generation~=obj.PayloadGeneration,obj.PayloadFirstFrame=next;end
                obj.FrameGeneration=next;obj.SentCount=obj.SentCount+uint64(1);
                obj.LastSourceS=simS;obj.LastBoardLowerS=v.board_min_rx_io_time_s;
                obj.PayloadGeneration=intent.payload_generation;obj.PayloadKg=intent.payload_kg;
                obj.ReleaseGeneration=intent.release_generation;
                r=obj.outcome('ENVIRONMENT_SENT_NOT_MODEL_ACK');r.send=sent;r.frame=v;
                r.payload_ack=obj.ack(snapshot,intent);obj.LastOutcome=r;
            catch problem
                if ~obj.Failed
                    obj.Failed=true;obj.FailureCode=problem.identifier;
                    obj.FirstFailure=struct('identifier',problem.identifier,'message',problem.message, ...
                        'last_snapshot_io_time_s',obj.LastSnapshotS,'attempt_count',obj.AttemptCount);
                end
                rethrow(problem)
            end
        end
        function s=status(obj)
            s=struct('schema','RFLY_CANONICAL_ENVIRONMENT_SERVICE_STATUS_V1','failed',obj.Failed, ...
                'failure_code',obj.FailureCode,'closed',obj.Closed,'frame_generation',obj.FrameGeneration, ...
                'send_attempt_count',obj.AttemptCount,'send_return_count',obj.SentCount,'wait_count',obj.WaitCount, ...
                'last_original_model_time_s',obj.LastSourceS,'retained_board_lower_bound_s',obj.LastBoardLowerS, ...
                'board_lower_bound_clamp_count',obj.ClampCount,'maximum_raw_board_regression_s',obj.MaximumRawRegressionS, ...
                'last_attempt',obj.LastAttempt,'last_outcome',obj.LastOutcome,'first_failure',obj.FirstFailure, ...
                'canonical_actual_wind_required',~isempty(obj.CanonicalTask)&&~obj.ManualDisturbance,'canonical_task_sha256',obj.CanonicalTaskSha, ...
                'legacy_wind_mode_when_no_task','HISTORICAL_ESTIMATE_OR_ZERO_COMPATIBILITY_NOT_CANONICAL', ...
                'bounded_history_slots',1,'disk_writes',0,'native_control_messages',0,'heartbeat_messages',0, ...
                'heartbeat_owner','CALLER_EXISTING_REGISTERED_HOST_HEARTBEAT_SERVICE__100MS_ORIGINAL_RX_CONTRACT', ...
                'environment_active_age_s',.25,'model_reset_requested',false,'publication_authority',false);
        end
        function close(obj)
            % No socket, board/module, environment RESET or plant action.
            obj.Closed=true;
        end
    end
    methods (Access=private)
        function value=canonicalWind(obj,view,reference,intent,expected)
            assert(isfield(view,'global_leg_index')&&isfield(reference,'actual_wind_ned_xy_mps') ...
                &&isfield(reference,'environment_task_sha256')&&strcmpi(reference.environment_task_sha256,obj.CanonicalTaskSha) ...
                &&strcmpi(expected.configuration_payload_sha256,obj.CanonicalConfigurationSha), ...
                'gpenmpcNative:EnvironmentCanonicalWind','Explicit same-task actual wind and current configuration required.');
            % Reuse cached task arrays and linear interpolation while checking
            % source, phase, payload and supplied wind on each update.
            [actual,estimate,selection]=gpenmpcNative.canonicalSavedTaskWindAt(obj.CanonicalTaskCache,view.saved_task_time_s,view.global_leg_index);
            supplied=reference.actual_wind_ned_xy_mps;
            assert(isa(supplied,'double')&&isreal(supplied)&&isequal(size(supplied),[2,1])&&all(isfinite(supplied)) ...
                &&isequal(typecast(supplied(:),'uint64'),typecast(actual(:),'uint64')) ...
                &&intent.payload_kg==obj.CanonicalTask.payload_kg(selection.left_source_row), ...
                'gpenmpcNative:EnvironmentCanonicalWind','Actual plant wind differs from exact canonical task interpolation.');
            selection.task_sha256=obj.CanonicalTaskSha;selection.controller_wind_estimate_xy_mps=estimate;
            selection.plant_wind_not_controller_estimate=true;obj.LastWindSelection=selection;
            value=struct('schema','RFLY_EXPLICIT_CANONICAL_PLANT_WIND_V1','actual_wind_ned_xy_mps',actual);
        end
        function identity(obj,s,r,e)
            fields={'schema','verified','uid','system_id','component_id','boot_generation', ...
                'configuration_payload_sha256','execution_session_sha256', ...
                'original_observed_io_time_s','original_observed_host_ns','provenance'};
            assert(isstruct(r)&&isscalar(r)&&all(isfield(r,fields)) ...
                &&strcmp(r.schema,'RFLY_CALLER_VERIFIED_SAME_IO_IDENTITY_V1')&&isequal(r.verified,true) ...
                &&isa(r.uid,'uint64')&&isscalar(r.uid)&&r.uid>0 ...
                &&isa(r.boot_generation,'uint64')&&isscalar(r.boot_generation)&&r.boot_generation>0 ...
                &&isa(r.original_observed_host_ns,'uint64')&&isscalar(r.original_observed_host_ns)&&r.original_observed_host_ns>0 ...
                &&finite(r.original_observed_io_time_s)&&r.original_observed_io_time_s>=0 ...
                &&r.original_observed_io_time_s<=s.now_s&&strlength(string(r.provenance))>0, ...
                'gpenmpcNative:EnvironmentIdentityReceipt','Explicit original caller-verified same-IO identity receipt required.');
            assert(isstruct(e)&&isscalar(e)&&all(isfield(e,{'uid','system_id','component_id','boot_generation', ...
                'configuration_payload_sha256','rfly_board_commit'})) ...
                &&string(r.uid)==string(e.uid)&&r.system_id==obj.Config.target_system ...
                &&r.component_id==obj.Config.target_component&&r.system_id==e.system_id&&r.component_id==e.component_id ...
                &&isequal(r.boot_generation,uint64(e.boot_generation)) ...
                &&validSha(r.configuration_payload_sha256)&&validSha(r.execution_session_sha256) ...
                &&strcmpi(r.configuration_payload_sha256,e.configuration_payload_sha256) ...
                &&strcmpi(r.execution_session_sha256,e.rfly_board_commit.execution_session_sha256), ...
                'gpenmpcNative:EnvironmentIdentityMismatch','Caller receipt differs from the current expected session/configuration.');
            % Actual IO snapshots do expose AUTOPILOT_VERSION when received;
            % no UID/boot field is invented when that observation is absent.
            if isfield(s,'autopilot_version')&&~isempty(s.autopilot_version)&&isfield(s.autopilot_version,'uid')
                assert(isa(s.autopilot_version.uid,'uint64')&&isequal(s.autopilot_version.uid,r.uid), ...
                    'gpenmpcNative:EnvironmentObservedUid','Actual snapshot AUTOPILOT_VERSION UID disagrees.');
            end
        end
        function intent(obj,v,s)
            assert(isstruct(v)&&isscalar(v)&&all(isfield(v,{'payload_kg','payload_generation', ...
                'release_generation','task_clock_paused','lifecycle_phase','payload_update_requested'})) ...
                &&integer(v.payload_generation,0,4)&&integer(v.release_generation,0,4) ...
                &&islogical(v.task_clock_paused)&&isscalar(v.task_clock_paused) ...
                &&islogical(v.payload_update_requested)&&isscalar(v.payload_update_requested) ...
                &&v.payload_kg==obj.Contract.payload_by_generation_kg(v.payload_generation+1) ...
                &&v.payload_generation>=obj.PayloadGeneration&&v.payload_generation<=obj.PayloadGeneration+1 ...
                &&v.release_generation==v.payload_generation, ...
                'gpenmpcNative:EnvironmentPayloadIntent','Exact task payload/release generations and explicit lifecycle intent required.');
            if v.payload_generation~=obj.PayloadGeneration
                assert(v.payload_update_requested&&v.task_clock_paused&&s.armed==0&&s.landed_state==1, ...
                    'gpenmpcNative:EnvironmentUnloadIntent','An unload request needs existing paused, disarmed landed lifecycle evidence.');
                % The model's dwell, contact and accepted-step checks determine application;
                % an intent alone is not an ACK.
            end
        end
        function r=ack(obj,s,intent)
            r=struct('matched',false,'payload_update_ack_for_lifecycle',false, ...
                'actual_payload_kg',NaN,'applied_frame_generation',0,'applied_payload_generation',0, ...
                'source','EXISTING_SAME_IO_DELIVERY_DIAGNOSTIC_OBSERVER','observed_model_time_s',NaN, ...
                'send_return_is_not_ack',true,'payload_write_authorized',false);
            if ~isfield(s,'delivery_environment'),return;end
            d=s.delivery_environment;
            if ~isstruct(d)||~isfield(d,'present')||~d.present||~isfield(d,'mass_ack_valid')||~d.mass_ack_valid,return;end
            q=d.decoded.environment_extension;
            assert(q.session_token==obj.Contract.expected_session_token, ...
                'gpenmpcNative:EnvironmentAckSession','ACK belongs to another plant environment session.');
            if ~isempty(obj.CanonicalTask)
                assert(isfield(s,'model_diagnostic')&&isfield(s.model_diagnostic,'decoded') ...
                    &&isfield(s.model_diagnostic.decoded,'sim_time_s') ...
                    &&isequal(typecast(double(q.same_model_time_s),'uint64'), ...
                        typecast(double(s.model_diagnostic.decoded.sim_time_s),'uint64')), ...
                    'gpenmpcNative:EnvironmentAckModelTime','Canonical ACK must belong to the original model diagnostic time.');
            end
            if q.applied_payload_generation~=intent.payload_generation ...
                ||abs(q.actual_payload_kg-intent.payload_kg)>=1e-12,return;end
            r.matched=obj.SentCount>0&&intent.payload_generation==obj.PayloadGeneration ...
                &&intent.payload_kg==obj.PayloadKg&&q.applied_frame_generation>=obj.PayloadFirstFrame ...
                &&q.applied_frame_generation<=obj.FrameGeneration;
            r.payload_update_ack_for_lifecycle=r.matched&&intent.payload_update_requested;
            r.actual_payload_kg=q.actual_payload_kg;r.applied_frame_generation=q.applied_frame_generation;
            r.applied_payload_generation=q.applied_payload_generation;r.observed_model_time_s=q.same_model_time_s;
        end
        function r=outcome(obj,status)
            r=struct('schema','RFLY_CANONICAL_ENVIRONMENT_STEP_V1','status',status, ...
                'frame_generation',obj.FrameGeneration,'publication_authority',false, ...
                'model_ack_proven_by_send',false,'heartbeat_sent',false,'native_control_sent',false);
        end
    end
end
function yes=finite(x),yes=isnumeric(x)&&isreal(x)&&isscalar(x)&&isfinite(x);end
function yes=integer(x,a,b),yes=finite(x)&&x==fix(x)&&x>=a&&x<=b;end
function yes=originalFresh(now,rx,bound),yes=finite(rx)&&now>=rx&&now-rx<=bound;end
function yes=validSha(x),yes=(ischar(x)||isstring(x))&&~isempty(regexp(char(x),'^[0-9a-fA-F]{64}$','once'));end
function h=taskFileSha(path)
f=fopen(path,'rb');assert(f>=0);c=onCleanup(@()fclose(f));b=fread(f,Inf,'*uint8');clear c
m=java.security.MessageDigest.getInstance('SHA-256');m.update(typecast(b,'int8'));
h=upper(reshape(dec2hex(typecast(m.digest(),'uint8'),2).',1,[]));
end
