function result=solveCurrentOuter(snapshot)
% Solve one coordinated outer-control update from its bound snapshot.
cfg=snapshot.config;
assert(strcmp(cfg.coordinated_architecture_mode,'A1_COORDINATED_PHYSICAL'));
assert(cfg.coordinated_physical_gp_application_enabled ...
    && cfg.command_continuity_enabled ...
    && cfg.gp_responsibility_gate_enabled);
assert(cfg.outer_period_s==0.3 && cfg.prediction_step_s==0.2 ...
    && cfg.horizon_steps==8 && cfg.prediction_horizon_s==1.6 ...
    && cfg.solver_deadline_s==0.28);
assert(startsWith(lower(string(which('gpenmpcCoordinatedOuterStep'))), ...
    lower(string(snapshot.source_root)+filesep)));
[decision,warm,audit]=gpenmpcCoordinatedOuterStep(snapshot.warm_start, ...
    snapshot.trajectory,snapshot.phase,snapshot.observation, ...
    snapshot.context,snapshot.gp_model,snapshot.causal,snapshot.gp_evidence,cfg);
result=struct('decision',decision,'warm_start',warm,'audit',audit, ...
    'snapshot_timestamp_ns',snapshot.snapshot_timestamp_ns, ...
    'configuration_payload_sha256',snapshot.configuration_payload_sha256, ...
    'used_current_supervisor',true,'hardware_actions',0);
end
