function [state, output] = stepCoordinatedPhysicalAdapterBoard( ...
        state, sample, robustConfig, config)
% Map private snapshots to the coordinated adapter.
% Use generation for observer updates and retain board lineage in
% private_source_generation and ticket.

arguments
    state (1,1) struct
    sample (1,1) struct
    robustConfig (1,1) struct
    config (1,1) struct
end

if state.hard_invalid_latched
    output = rejected("HARD_INVALID_ALREADY_LATCHED",state);
    return
end

[valid,reason] = validateSample(state,sample);
if ~valid
    state.hard_invalid_latched = true;
    state.robust_state = gpenmpcInitializeRobustSe3State();
    output = rejected(reason,state);
    return
end

plantState = zeros(19,1);
plantState(1:13) = double(sample.estimate_state_up(:));
reference = struct( ...
    'position_m',double(sample.reference_up.position_m(:)), ...
    'velocity_mps',double(sample.reference_up.velocity_mps(:)));
[augmentationUp,nextRobust,diagnostic] = ...
    gpenmpcCoordinatedGpRobustSe3Augmentation( ...
        plantState,reference,robustConfig,state.robust_state, ...
        double(sample.dt_s),sample.gp_evidence, ...
        double(sample.gp_agreement_weight_f(:)),config);

assert(all(isfinite(augmentationUp)) ...
    && norm(augmentationUp) <= ...
        double(robustConfig.combined_compensation_cap_mps2) + 1.0e-12, ...
    'gpenmpcNative:PhysicalAdapterOutput','Invalid physical compensation.');

state.robust_state = nextRobust;
state.last_generation = uint64(sample.generation);
state.last_sample_timestamp_ns = uint64(sample.sample_timestamp_ns);
state.accepted_sample_count = state.accepted_sample_count + uint64(1);
if logical(diagnostic.exact_b1_fallback)
    state.exact_b1_fallback_count = state.exact_b1_fallback_count + uint64(1);
else
    state.physical_gp_active_count = state.physical_gp_active_count + uint64(1);
end

transform = diag([1,1,-1]);
output = struct( ...
    'schema',"GPENMPC_COORDINATED_PHYSICAL_OUTPUT_V1", ...
    'accepted',true, ...
    'publication_allowed',true, ...
    'reason',"FRESH_CAUSAL_COORDINATED_PHYSICAL_SAMPLE", ...
    'generation',double(state.last_generation), ...
    'source_generation',sample.private_source_generation, ...
    'source_ticket',sample.source_ticket, ...
    'sample_timestamp_ns',double(state.last_sample_timestamp_ns), ...
    'compensation_up_mps2',double(augmentationUp(:)), ...
    'compensation_ned_mps2',transform*double(augmentationUp(:)), ...
    'exact_b1_fallback',logical(diagnostic.exact_b1_fallback), ...
    'physical_gp_active',~logical(diagnostic.exact_b1_fallback), ...
    'diagnostic',diagnostic, ...
    'control_interface',"BOUNDED_ACCELERATION_COMPENSATION_ONLY", ...
    'direct_actuator_authority',false, ...
    'thrust_torque_publication_authority',false, ...
    'trajectory_publication_authority',false, ...
    'plant_truth_used',false, ...
    'hardware_actions',0);
end

function [valid,reason] = validateSample(state,sample)
valid = false;
reason = "MALFORMED_COORDINATED_PHYSICAL_SAMPLE";
required = {'schema','method_identity','configuration_payload_sha256', ...
    'task_identity_sha256','estimate_source','plant_truth_used', ...
    'generation','sample_timestamp_ns','dt_s','estimate_state_up', ...
    'reference_up','gp_evidence','gp_agreement_weight_f', ...
    'private_source_generation','source_ticket'};
if ~all(isfield(sample,required))
    return
end
if string(sample.schema) ~= "GPENMPC_COORDINATED_PHYSICAL_INPUT_V1" ...
        || string(sample.method_identity) ~= "A1_COORDINATED_PHYSICAL" ...
        || ~strcmpi(string(sample.configuration_payload_sha256), ...
            string(state.configuration_payload_sha256)) ...
        || ~strcmpi(string(sample.task_identity_sha256), ...
            string(state.task_identity_sha256))
    reason = "METHOD_CONFIGURATION_OR_TASK_IDENTITY_MISMATCH";
    return
end
approvedEstimateSources="PX4_PRIVATE_VEHICLE_ODOMETRY_RSP1";
if ~any(string(sample.estimate_source)==approvedEstimateSources) ...
        || ~(islogical(sample.plant_truth_used) ...
            && isscalar(sample.plant_truth_used) && ~sample.plant_truth_used)
    reason = "PLANT_TRUTH_OR_UNAPPROVED_ESTIMATE_SOURCE";
    return
end
if ~isa(sample.private_source_generation,'uint64') || ~isscalar(sample.private_source_generation) ...
        || sample.private_source_generation==0 || ~isa(sample.source_ticket,'uint8') ...
        || numel(sample.source_ticket)~=32 || ~any(sample.source_ticket)
    reason="INVALID_PRIVATE_SOURCE_LINEAGE";
    return
end
if ~finiteInteger(sample.generation) ...
        || uint64(sample.generation) ~= state.last_generation + uint64(1)
    reason = "NONMONOTONE_OR_GAPPED_GENERATION";
    return
end
if ~finiteInteger(sample.sample_timestamp_ns) ...
        || uint64(sample.sample_timestamp_ns) <= state.last_sample_timestamp_ns
    reason = "NONMONOTONE_SAMPLE_TIMESTAMP";
    return
end
if ~finiteScalar(sample.dt_s) || sample.dt_s < 0.002 || sample.dt_s > 0.04 ...
        || ~finiteVector(sample.estimate_state_up,13) ...
        || ~finiteVector(sample.gp_agreement_weight_f,3) ...
        || any(sample.gp_agreement_weight_f(:) < 0) ...
        || any(sample.gp_agreement_weight_f(:) > 1)
    reason = "NONFINITE_OR_OUT_OF_RANGE_EXECUTION_INPUT";
    return
end
if ~isstruct(sample.reference_up) || ~isscalar(sample.reference_up) ...
        || ~all(isfield(sample.reference_up,{'position_m','velocity_mps'})) ...
        || ~finiteVector(sample.reference_up.position_m,3) ...
        || ~finiteVector(sample.reference_up.velocity_mps,3)
    reason = "INVALID_REFERENCE";
    return
end
if ~validEvidence(sample.gp_evidence)
    reason = "MALFORMED_GP_EVIDENCE";
    return
end
valid = true;
reason = "PASS";
end

function ok = validEvidence(value)
required = {'available','prediction_sample_closed', ...
    'observed_innovation_available','hard_invalid','trust', ...
    'predicted_mean_f_mps2','gp_frame_i_from_f'};
ok = isstruct(value) && isscalar(value) && all(isfield(value,required));
if ~ok, return, end
logicalNames = {'available','prediction_sample_closed', ...
    'observed_innovation_available','hard_invalid'};
for k = 1:numel(logicalNames)
    candidate = value.(logicalNames{k});
    if ~(islogical(candidate) && isscalar(candidate))
        ok = false;
        return
    end
end
ok = finiteScalar(value.trust) && value.trust >= 0 && value.trust <= 1 ...
    && finiteVector(value.predicted_mean_f_mps2,3) ...
    && isnumeric(value.gp_frame_i_from_f) ...
    && isequal(size(value.gp_frame_i_from_f),[3,3]) ...
    && all(isfinite(value.gp_frame_i_from_f),'all');
if logical(value.observed_innovation_available)
    ok = ok && isfield(value,'observed_innovation_f_mps2') ...
        && isfield(value,'calibrated_half_width_f_mps2') ...
        && finiteVector(value.observed_innovation_f_mps2,3) ...
        && finiteVector(value.calibrated_half_width_f_mps2,3) ...
        && all(value.calibrated_half_width_f_mps2(:) > 0);
end
end

function output = rejected(reason,state)
output = struct( ...
    'schema',"GPENMPC_COORDINATED_PHYSICAL_OUTPUT_V1", ...
    'accepted',false,'publication_allowed',false,'reason',string(reason), ...
    'generation',double(state.last_generation), ...
    'sample_timestamp_ns',double(state.last_sample_timestamp_ns), ...
    'compensation_up_mps2',nan(3,1), ...
    'compensation_ned_mps2',nan(3,1), ...
    'exact_b1_fallback',false,'physical_gp_active',false, ...
    'diagnostic',struct, ...
    'control_interface',"NO_OUTPUT_FAIL_CLOSED", ...
    'direct_actuator_authority',false, ...
    'thrust_torque_publication_authority',false, ...
    'trajectory_publication_authority',false, ...
    'plant_truth_used',false,'hardware_actions',0);
end

function ok = finiteScalar(value)
ok = isnumeric(value) && isreal(value) && isscalar(value) && isfinite(value);
end

function ok = finiteInteger(value)
ok = finiteScalar(value) && value >= 0 && value == fix(value) ...
    && value <= double(intmax('uint64'));
end

function ok = finiteVector(value,count)
ok = isnumeric(value) && isreal(value) && isvector(value) ...
    && numel(value) == count && all(isfinite(value(:)));
end


