function [owner,counters]=validateRflyOriginalStreamingWindow(w,n)
% Validate completed MEX records acquired by the RDR consumer.
% SSS counters are individually atomic, not a coherent epoch snapshot.
b=w.ring_section;s=w.step_status;
assert(isa(b,'uint8')&&numel(b)==160&&isa(s,'uint8')&&numel(s)==144 ...
    &&isfield(w,'snapshot_coherent')&&isequal(w.snapshot_coherent,false) ...
    &&strcmp(w.original_read_clock_domain,'WINDOWS_QPC_INTEGER_FLOOR_NS_SAME_STOPWATCH'), ...
    'gpenmpcNative:StreamingShape','Original live header shape required.');
assert(isequal(readLE(b(1:20),'uint32'),uint32([hex2dec('31524452');1;86176;336;256])) ...
    &&isequal(readLE(s(1:16),'uint32'),uint32([hex2dec('31535353');1;144;10])), ...
    'gpenmpcNative:StreamingShape','Original RDR1 and SSS1 shape required.');
pid=readLE(b(21:24),'uint32');nonce=readLE(b(65:72),'uint64');consumer=readLE(b(73:76),'uint32');
assert(pid>0&&consumer>0&&pid~=consumer&&nonce>0&&pid==readLE(s(25:28),'uint32') ...
    &&nonce==readLE(s(17:24),'uint64')&&readLE(b(77:80),'uint32')==3 ...
    &&any(readLE(b(25:28),'uint32')==uint32([3;4])) ...
    &&any(readLE(s(29:32),'uint32')==uint32([3;4])), 'gpenmpcNative:StreamingOwner','Producer, consumer and nonce must agree.');
assert(readLE(b(57:64),'uint64')==0&&readLE(b(81:84),'uint32')==0 ...
    &&all(readLE(b(97:160),'uint64')==0)&&readLE(s(41:48),'uint64')==0 ...
    &&readLE(s(57:64),'uint64')==0,'gpenmpcNative:StreamingStickyFault','Original fault cannot be cleared by a new batch.');
counters=readLE(s(65:144),'uint64');
% Counter 8 includes invalid generation-zero terrain preparation.
% Reject faulted or conflicting observations separately.
assert(counters(1)==1&&counters(2)==0&&counters(3)>=1&&all(counters(9:10)==0), ...
    'gpenmpcNative:StreamingSnapshotFault','Original step snapshot fault.');
events=readLE(reshape(w.records(1:8,:),[],1),'uint64');
assert(numel(events)==n&&n>0&&events(1)>0&&all(events(2:end)==events(1:end-1)+uint64(1)) ...
    &&events(end)<=readLE(b(41:48),'uint64'),'gpenmpcNative:StreamingRecordOrder','Completed copy order is incomplete.');
% Validate per-step receipts without equating independently sampled counters.
% Retain startup observations; selected source bindings require observation_valid=1.
assert(all(w.records(330:331,:)==0,'all'), ...
    'gpenmpcNative:StreamingRecordFault','Model failure in an original record.');
owner=struct('producer_pid',pid,'consumer_pid',consumer,'peer_nonce',nonce, ...
    'first_window_event',events(1),'last_window_event',events(end), ...
    'observed_total_getters',readLE(b(49:56),'uint64'), ...
    'external_owner_quiescence_proven_here',false,'running_counters_equal_epoch',false);
end
function v=readLE(b,t),v=typecast(b(:),t);[~,~,e]=computer;if e=='B',v=swapbytes(v);end;v=v(:);end
