function [ok,reason,control] = validateCanonicalFullInnerFeedback( ...
        f,command,assets,nowNs,beginNs,maximumAgeNs)
% Validate full-kernel host execution results.
ok=false;reason="MALFORMED_CANONICAL_FULL_INNER_FEEDBACK";control=struct();
fields={'schema','evidence_scope','generation','estimate_sample_timestamp_ns', ...
    'task_identity_sha256','configuration_payload_sha256','kernel_source_sha256', ...
    'rx_ns','dt_s','valid','wrench_n_nm','rotor_command_n','diagnostic51', ...
    'board_consumption_proven','plant_truth_used','hardware_actions'};
if ~isstruct(f)||~isscalar(f)||~all(isfield(f,fields)),return,end
if string(f.schema)~="GPENMPC_CANONICAL_FULL_INNER_FEEDBACK_V1" ...
        ||string(f.evidence_scope)~="HOST_ONLY_KERNEL_EXECUTION" ...
        ||~isequal(f.board_consumption_proven,false)||~isequal(f.plant_truth_used,false) ...
        ||~isequal(f.hardware_actions,0)||~isequal(f.valid,true)
    reason="FULL_INNER_SCOPE_OR_VALIDITY_REJECTED";return
end
if ~isequal(f.generation,command.generation) ...
        ||~isequal(f.estimate_sample_timestamp_ns,command.estimate_sample_timestamp_ns) ...
        ||~strcmpi(string(f.task_identity_sha256),command.task_identity_sha256) ...
        ||~strcmpi(string(f.configuration_payload_sha256),command.configuration_payload_sha256) ...
        ||~strcmpi(string(f.kernel_source_sha256),command.kernel_source_sha256)
    reason="FULL_INNER_SAMPLE_OR_CODE_IDENTITY_MISMATCH";return
end
if ~scalar(f.rx_ns)||f.rx_ns<beginNs||f.rx_ns>nowNs||nowNs-f.rx_ns>maximumAgeNs ...
        ||~scalar(f.dt_s)||abs(f.dt_s-command.dt_s)>5e-7 ...
        ||~vector(f.wrench_n_nm,4)||~vector(f.rotor_command_n,6)||~vector(f.diagnostic51,51)
    reason="FULL_INNER_TIMESTAMP_OR_NUMERICS_REJECTED";return
end
% Independent canonical source oracle, not the generated kernel. This
% covers force projection and rotor clipping; the canonical fail-soft
% ObserveControl consumes those outcomes rather than changing the law to
% an artificial no-projection/no-saturation-only implementation.
try
    [rotor,d]=gpenmpcRobustSe3Control(command.state_up,command.reference_up, ...
        command.payload_kg,command.wind_estimate_xy_mps,command.augmentation_up_mps2, ...
        assets.calibration,assets.profile,command.attitude_command);
    truth=[d.desired_thrust_n;d.desired_moment_nm;rotor; ...
        d.desired_force_raw_n;d.desired_force_projected_n;d.desired_rotation(:); ...
        d.raw_desired_rotation(:);d.attitude_error; ...
        d.desired_angular_velocity_body_rad_s;d.desired_angular_acceleration_body_rad_s2; ...
        d.desired_angular_velocity_in_current_body_rad_s;d.body_rate_error_rad_s; ...
        d.geometric_feedforward_moment_nm;d.raw_rotor_command_n; ...
        d.force_projection_norm_mismatch_n;d.tilt_rad;double(d.rotor_saturated)];
catch
    reason="FULL_INNER_ORACLE_INPUT_REJECTED";return
end
actual=[double(f.wrench_n_nm(:));double(f.rotor_command_n(:));double(f.diagnostic51(:))];
if max(abs(actual-truth))>1e-10
    reason="FULL_INNER_CANONICAL_OUTPUT_MISMATCH";return
end
control=struct('desired_force_projected_up_n',double(d.desired_force_projected_n(:)), ...
    'rotor_command_n',double(rotor(:)),'rotor_saturated',logical(d.rotor_saturated), ...
    'force_projection_norm_mismatch_n',double(d.force_projection_norm_mismatch_n), ...
    'desired_moment_nm',double(d.desired_moment_nm(:)), ...
    'desired_thrust_n',double(d.desired_thrust_n));
ok=true;reason="PASS_HOST_ONLY_FULL_CANONICAL_KERNEL_RETURN";
end
function yes=scalar(x)
yes=isnumeric(x)&&isreal(x)&&isscalar(x)&&isfinite(x);
end
function yes=vector(x,n)
yes=isnumeric(x)&&isreal(x)&&isvector(x)&&numel(x)==n&&all(isfinite(x(:)));
end
