function [payloads,binding]=validateLocalGpReplyForSend(replyBytes,item,expected,maximumAgeNs,nowNs,retireExpired)
% Pure byte/source consistency only. Actual IO must also match each callback.
if nargin<6,retireExpired=false;end
assert(islogical(retireExpired)&&isscalar(retireExpired));
assert(isstruct(item)&&isscalar(item)&&string(item.channel)=="gp_request" ...
    &&numel(item.decoded_fragments)==3&&isa(item.fragment_rx_ns,'uint64')&&numel(item.fragment_rx_ns)==3);
assert(isa(maximumAgeNs,'uint64')&&isscalar(maximumAgeNs)&&maximumAgeNs>0 ...
    &&isa(nowNs,'uint64')&&isscalar(nowNs));
q=gpenmpcNative.RflyLocalGpCodec.decodeRequest(item.message);
r=gpenmpcNative.RflyLocalGpCodec.decodeReply(replyBytes);e=expected;
assert(isequal(q.identity,r.identity)&&q.source_timestamp_ns==r.source_timestamp_ns ...
    &&q.source_generation==r.source_generation&&q.output_generation==r.output_generation ...
    &&isequal(q.original_request_sha256,r.original_request_sha256)&&isequal(q.gp_model_sha256,r.gp_model_sha256) ...
    &&q.identity.uid==e.uid&&q.identity.boot_generation==e.session_generation ...
    &&q.identity.system==e.source_system&&q.identity.component==e.source_component, ...
    'gpenmpcNative:LocalGpSendBinding','Exact request, reply, source and registered session required.');
assert(isequal(item.origin.link_lifecycle_generation,e.link_lifecycle_generation) ...
    &&strcmpi(item.origin.execution_session_sha256,e.execution_session_sha256), ...
    'gpenmpcNative:LocalGpSendOrigin','Registered same-owner request origin required.');
joined=zeros(310,1,'uint8');
for k=1:3
    m=item.decoded_fragments{k};p=m.Payload;n=min(119,310-(k-1)*119);
    assert(m.MsgID==385&&m.SystemID==e.source_system&&m.ComponentID==e.source_component ...
        &&p.payload_type==42002&&p.target_system==e.target_system&&p.target_component==e.target_component ...
        &&isa(p.payload,'uint8')&&numel(p.payload)==128&&double(p.payload_length)==9+n ...
        &&p.payload(1)==uint8(128+k-1)&&be64(p.payload(2:9))==q.output_generation ...
        &&all(p.payload(10+n:end)==0),'gpenmpcNative:LocalGpSendFragments','Original RGP1 fragments required.');
    joined(119*(k-1)+1:119*(k-1)+n)=p.payload(10:9+n);
end
rx=item.fragment_rx_ns(:);
assert(isequal(joined,q.original_bytes)&&all(rx(2:end)>=rx(1:end-1))&&rx(1)>0 ...
    &&item.original_host_receive_ns==rx(1)&&item.completion_host_receive_ns==rx(end) ...
    &&maximumAgeNs<=intmax('uint64')-rx(1), ...
    'gpenmpcNative:LocalGpSendOriginalBytes','Original callback bytes/times inconsistent.');
expiry=rx(1)+maximumAgeNs;
assert(nowNs>=rx(end)&&(nowNs<=expiry||retireExpired), ...
    'gpenmpcNative:LocalGpSendExpired','No queued or processed timestamp renewal.');
payloads=gpenmpcNative.RflyLocalGpCodec.replyFragments(replyBytes,e.source_system,e.source_component);
binding=struct('original_request_sha256',q.original_request_sha256, ...
    'original_host_receive_ns',rx(1),'valid_until_host_ns',expiry, ...
    'maximum_transport_age_ns',maximumAgeNs,'control_publication_expiry_used',false, ...
    'original_callback_matched_here',false,'control_authority',false);
end
function v=be64(b)
v=uint64(0);for k=1:numel(b),v=bitor(bitshift(v,8),uint64(b(k)));end
end
