function [payloads,binding,m]=validateLocalTaskInputForSend(bytes,item,e,maximumAgeNs,nowNs)
% Consistency only. Actual IO separately matches these to its callback ledger.
assert(isstruct(item)&&isscalar(item)&&string(item.channel)=="snapshot" ...
    &&numel(item.decoded_fragments)==4&&isa(item.fragment_rx_ns,'uint64')&&numel(item.fragment_rx_ns)==4);
assert(isa(maximumAgeNs,'uint64')&&isscalar(maximumAgeNs)&&maximumAgeNs>0 ...
    &&isa(nowNs,'uint64')&&isscalar(nowNs));
s=gpenmpcNative.RflyLocalSnapshotDecoder(item.message,item.original_host_receive_ns);
[payloads,m]=gpenmpcNative.RflyLocalTaskCodec.fragments(bytes,e.source_system,e.source_component);k=m.source;
assert(isequal(s.identity,k.identity)&&k.identity.uid==e.uid&&k.identity.boot_generation==e.session_generation ...
    &&k.identity.system==e.source_system&&k.identity.component==e.source_component ...
    &&k.sample_us==s.original_sample_us&&k.publication_us==s.original_publication_us ...
    &&k.original_receipt_us==s.original_receipt_us&&k.source_generation==s.source_generation ...
    &&k.generation_delta==s.generation_delta&&k.sample_delta_us==s.sample_delta_us&&k.reset_counter==s.reset_counter ...
    &&isequal(k.state_and_origin_sha256,s.state_and_origin_sha256)&&isequal(m.original_sensor52,s.original_sensor52) ...
    &&strcmpi(hex(m.execution_session_sha256),e.execution_session_sha256)&&strcmpi(hex(m.configuration_sha256),e.configuration_sha256), ...
    'gpenmpcNative:LocalTaskSendBinding','Exact private source and registered session required.');
assert(isequal(item.origin.link_lifecycle_generation,e.link_lifecycle_generation) ...
    &&strcmpi(item.origin.execution_session_sha256,e.execution_session_sha256), ...
    'gpenmpcNative:LocalTaskSendOrigin','Same-owner callback origin required.');
joined=zeros(382,1,'uint8');
% All four existing RLS fragments carry the same generation. Compare its
% exact network bytes once converted, rather than query COMPUTER/typecast
% separately for every fragment during the original 50-ms input lifetime.
generation=s.source_generation;[~,~,endian]=computer;
if endian=='L',generation=swapbytes(generation);end
generationBytes=reshape(typecast(generation,'uint8'),[],1);
for j=1:4
    msg=item.decoded_fragments{j};p=msg.Payload;n=min(119,382-(j-1)*119);
    assert(msg.MsgID==385&&msg.SystemID==e.source_system&&msg.ComponentID==e.source_component ...
        &&p.payload_type==42002&&p.target_system==e.target_system&&p.target_component==e.target_component ...
        &&isa(p.payload,'uint8')&&numel(p.payload)==128&&double(p.payload_length)==9+n ...
        &&p.payload(1)==uint8(160+j-1)&&isequal(reshape(p.payload(2:9),[],1),generationBytes) ...
        &&all(p.payload(10+n:end)==0),'gpenmpcNative:LocalTaskSendFragments','Original RLS1 fragments required.');
    joined(119*(j-1)+1:119*(j-1)+n)=p.payload(10:9+n);
end
rx=item.fragment_rx_ns(:);
assert(isequal(joined,s.original_bytes)&&all(rx(2:end)>=rx(1:end-1))&&rx(1)>0 ...
    &&item.original_host_receive_ns==rx(1)&&item.completion_host_receive_ns==rx(end) ...
    &&maximumAgeNs<=intmax('uint64')-rx(1),'gpenmpcNative:LocalTaskSendOriginalBytes');
expiry=rx(1)+maximumAgeNs;
assert(nowNs>=rx(end)&&nowNs<=expiry&&nowNs<=m.outer.original_expiry_ns, ...
    'gpenmpcNative:LocalTaskSendExpired','Input and held outer lifetimes are original, not receive-time renewals.');
expiry=min(expiry,m.outer.original_expiry_ns);
binding=struct('original_source_generation',s.source_generation,'original_sample_us',s.original_sample_us, ...
    'original_host_receive_ns',rx(1),'valid_until_host_ns',expiry,'maximum_transport_age_ns',maximumAgeNs, ...
    'original_callback_matched_here',false,'control_authority',false);
end
function s=hex(b),s=upper(reshape(dec2hex(b,2).',1,[]));end
