function paths = setup_project()
%SETUP_PROJECT Add the MATLAB simulation code to the search path.

root = string(fileparts(mfilename("fullpath")));
paths = struct( ...
    "root", root, ...
    "core", fullfile(root, "matlab", "core"), ...
    "extensions", fullfile(root, "matlab", "extensions"), ...
    "tasks", fullfile(root, "data", "tasks"), ...
    "outputs", fullfile(root, "outputs"));
assert(isfolder(paths.core), "setup_project:MissingCode", ...
    "Missing MATLAB source folder: %s", paths.core);
assert(isfolder(paths.tasks), "setup_project:MissingTasks", ...
    "Missing task folder: %s", paths.tasks);

addpath(root, "-begin");
addpath(genpath(paths.core), "-begin");
if isfolder(paths.extensions)
    % Include the fixed-reference comparison controllers.
    addpath(genpath(paths.extensions), "-begin");
end
rehash path;

required = ["gpenmpcLoadNativeEnmpcComparisonAssets", ...
    "gpenmpcRunNativeEnmpcWholeTask", "gpenmpcRunFixedC3WholeTask", ...
    "gpenmpcApplyArchitectureConfiguration", ...
    "gpenmpcApplyCommandContinuityConfiguration", ...
    "gpenmpcSparseGpPredict", "gpenmpcRobustSe3Control"];
for name = required
    selected = string(which(name));
    assert(strlength(selected) > 0, "setup_project:MissingFunction", ...
        "Missing MATLAB function: %s", name);
    selected = string(char(java.io.File(char(selected)).getCanonicalPath()));
    sourceRoot = string(char(java.io.File(char(fullfile(root, "matlab"))).getCanonicalPath()));
    assert(startsWith(lower(selected), lower(sourceRoot) + filesep), ...
        "setup_project:SourcePath", ...
        "MATLAB selected a function outside this project: %s", selected);
end
end
