function observation=compareIndependentAttitude(estimateRpy,modelRpy,estimateTime,modelTime,maximumSkew)
%COMPAREINDEPENDENTATTITUDE Compare independently observed attitude streams.
% Both Euler streams must be independently measured FRD-to-NED radians.
% Time arrays must already share a separately verified source-clock domain.
% maximumSkew is the caller's source-time alignment bound. The returned
% attitude errors are diagnostic measurements.
assert(isnumeric(estimateRpy)&&isreal(estimateRpy)&&isnumeric(modelRpy)&&isreal(modelRpy)&& ...
    isequal(size(estimateRpy),size(modelRpy))&&size(estimateRpy,1)==3&&size(estimateRpy,2)>0&& ...
    all(isfinite(estimateRpy),'all')&&all(isfinite(modelRpy),'all'), ...
    'm600check:AttitudeObservationShape','Require finite real paired 3-by-N Euler streams.');
n=size(estimateRpy,2);estimateTime=reshape(estimateTime,1,[]);modelTime=reshape(modelTime,1,[]);
assert(numel(estimateTime)==n&&numel(modelTime)==n&&all(isfinite([estimateTime,modelTime]))&& ...
    all(diff(estimateTime)>=0)&&all(diff(modelTime)>=0), ...
    'm600check:AttitudeObservationTime','Times must be finite, ordered and paired.');
assert(isnumeric(maximumSkew)&&isreal(maximumSkew)&&isscalar(maximumSkew)&&isfinite(maximumSkew)&&maximumSkew>=0, ...
    'm600check:AttitudeObservationTime','Explicit nonnegative source alignment bound required.');
delta=atan2(sin(estimateRpy-modelRpy),cos(estimateRpy-modelRpy));angle=zeros(1,n);tilt=angle;
for k=1:n
    Re=matrixFromEuler(estimateRpy(:,k));Rm=matrixFromEuler(modelRpy(:,k));relative=Re*Rm.';
    angle(k)=atan2(norm([relative(3,2)-relative(2,3);relative(1,3)-relative(3,1);relative(2,1)-relative(1,2)])/2, ...
        (trace(relative)-1)/2);
    be=Re.'*[0;0;1];bm=Rm.'*[0;0;1];tilt(k)=atan2(norm(cross(be,bm)),dot(be,bm));
end
skew=abs(estimateTime-modelTime);
observation=struct('wrapped_euler_error_rad',delta,'attitude_geodesic_error_rad',angle, ...
    'tilt_error_rad',tilt,'source_skew_s',skew,'pair_within_caller_time_bound',skew<=maximumSkew, ...
    'maximum_source_skew_s',maximumSkew,'performance_threshold_defined',false, ...
    'flight_admission_decided',false);
end
function R=matrixFromEuler(v)
r=v(1);p=v(2);y=v(3);cr=cos(r);sr=sin(r);cp=cos(p);sp=sin(p);cy=cos(y);sy=sin(y);
R=[cy*cp,cy*sp*sr-sy*cr,cy*sp*cr+sy*sr; ...
   sy*cp,sy*sp*sr+cy*cr,sy*sp*cr-cy*sr;-sp,cp*sr,cp*cr];
end
