function memory = initialStepMemory()
%#codegen
%INITIALSTEPMEMORY Same ground/contact observer initial values as live service.
memory = struct('previous_contact_active',false, ...
    'contact_entry_count',uint64(0),'airborne_observed',false, ...
    'ground_support_dwell_s',0.50,'ground_confirmed',true, ...
    'plant_step_count',uint64(0),'failed',false);
end
