function p = packParameters(calibration, profile, mission)
%PACKPARAMETERS Construct fixed-field parameters from the MATLAB model inputs.
% Contact constants come from frozenContactParameters in
% LiveHilPlantService/compliantContactState and represent modeled contact.

r = calibration.rotor_allocation;
p.calibration.rotor_allocation = struct( ...
    'angles_deg',column(r.angles_deg,6), ...
    'spin_sign',column(r.spin_sign,6), ...
    'arm_radius_m',scalar(r.arm_radius_m), ...
    'yaw_moment_arm_nominal_m',scalar(r.yaw_moment_arm_nominal_m), ...
    'per_rotor_thrust_upper_n',scalar(r.per_rotor_thrust_upper_n), ...
    'actuator_time_constant_nominal_s',scalar(r.actuator_time_constant_nominal_s));
p.calibration.mass_inertia.inertia_nominal_kg_m2 = ...
    column(calibration.mass_inertia.inertia_nominal_kg_m2,3);
p.calibration.aerodynamics.frame_drag_nominal_n_per_mps2 = ...
    column(calibration.aerodynamics.frame_drag_nominal_n_per_mps2,3);
p.calibration.development_limits.tilt_deg = ...
    scalar(calibration.development_limits.tilt_deg);
p.profile.mass_properties.base_mass_kg = ...
    scalar(profile.mass_properties.base_mass_kg);

m = mission.plant_mismatch;
crossDrag = double(m.cross_drag_matrix_n_per_mps2);
assert(isequal(size(crossDrag),[3,3]) && all(isfinite(crossDrag(:))));
amplitude = double(m.external_acceleration_amplitude_mps2);
% The oracle permits either scalar or three-axis column amplitude. Expand a
% scalar explicitly so the generated parameter type is always 3-by-1.
assert(isscalar(amplitude) || isequal(size(amplitude),[3,1]));
if isscalar(amplitude)
    amplitude = repmat(amplitude,3,1);
end
p.mission.plant_mismatch = struct( ...
    'mass_bias_kg',scalar(m.mass_bias_kg), ...
    'drag_scale_xyz',column(m.drag_scale_xyz,3), ...
    'cross_drag_matrix_n_per_mps2',crossDrag, ...
    'thrust_effectiveness_by_rotor',column(m.thrust_effectiveness_by_rotor,6), ...
    'external_acceleration_frequencies_hz',column(m.external_acceleration_frequencies_hz,3), ...
    'external_acceleration_phases_rad',column(m.external_acceleration_phases_rad,3), ...
    'external_acceleration_amplitude_mps2',column(amplitude,3), ...
    'acceleration_bias_inertial_mps2',column(m.acceleration_bias_inertial_mps2,3));

s = mission.structured_residual;
assert(isscalar(s.enabled));
p.mission.structured_residual = struct( ...
    'enabled',logical(s.enabled), ...
    'drag_payload_coupling_n_per_mps2_xyz',column(s.drag_payload_coupling_n_per_mps2_xyz,3), ...
    'drag_tilt_gain',scalar(s.drag_tilt_gain), ...
    'turn_sideforce_n_per_mps2',scalar(s.turn_sideforce_n_per_mps2), ...
    'turn_centripetal_gain',scalar(s.turn_centripetal_gain), ...
    'thrust_efficiency_base_loss',scalar(s.thrust_efficiency_base_loss), ...
    'thrust_efficiency_payload_gain',scalar(s.thrust_efficiency_payload_gain), ...
    'thrust_efficiency_command_gain',scalar(s.thrust_efficiency_command_gain), ...
    'thrust_efficiency_vertical_demand_gain',scalar(s.thrust_efficiency_vertical_demand_gain));

p.contact = struct('static_deflection_m',0.035, ...
    'damping_ratio',0.90,'maximum_deflection_m',0.060, ...
    'smooth_force_fraction_of_weight',0.02, ...
    'bump_stop_stiffness_multiplier',10.0, ...
    'damping_engagement_depth_fraction_of_static_deflection',1.0);
% Lock model identity. Payload affects mass,
% NOT this inertia; effective rotor command is linear thrust, NOT RPM.
assert(isequal(p.calibration.mass_inertia.inertia_nominal_kg_m2,[1.6;1.6;3.0]));
assert(isequal(p.calibration.rotor_allocation.angles_deg,[0;60;120;180;240;300]));
assert(isequal(p.calibration.rotor_allocation.spin_sign,[1;-1;1;-1;1;-1]));
assert(p.calibration.rotor_allocation.actuator_time_constant_nominal_s==0.12);
assert(p.calibration.rotor_allocation.per_rotor_thrust_upper_n==32.145727009134916);
assert(p.profile.mass_properties.base_mass_kg==9.5);
end

function value = column(value,count)
value = double(value(:));
assert(numel(value)==count && all(isfinite(value)));
end

function value = scalar(value)
value = double(value);
assert(isscalar(value) && isfinite(value));
end
