function counters = gpenmpcObserveSupervisorEvent(counters, event)
%GPENMPCOBSERVESUPERVISOREVENT Append one complete outer-FSM event.

arguments
    counters (1,1) struct
    event (1,1) struct
end
if ~isfield(counters, "supervisor_events")
    counters.supervisor_events = cell(0, 1);
    counters.supervisor_transition_count = 0;
    counters.supervisor_failure_hold_count = 0;
    counters.supervisor_fixed_reference_count = 0;
    counters.supervisor_b1_direct_request_count = 0;
    counters.supervisor_b2_probe_request_count = 0;
    counters.supervisor_reentry_count = 0;
end
counters.supervisor_events{end+1,1} = event;
counters.supervisor_transition_count = counters.supervisor_transition_count ...
    + double(logical(event.transitioned));
counters.supervisor_failure_hold_count = counters.supervisor_failure_hold_count ...
    + double(string(event.applied_source) == "LAST_FEASIBLE_ONE_TICK_HOLD");
counters.supervisor_fixed_reference_count = counters.supervisor_fixed_reference_count ...
    + double(logical(event.fixed_reference_applied));
counters.supervisor_b1_direct_request_count = ...
    counters.supervisor_b1_direct_request_count ...
    + double(contains(string(event.request_reason), "B1") ...
    || contains(string(event.request_reason), "STALE"));
counters.supervisor_b2_probe_request_count = ...
    counters.supervisor_b2_probe_request_count ...
    + double(startsWith(string(event.request_reason), ...
        "B2_REENTRY_PROBE"));
counters.supervisor_reentry_count = counters.supervisor_reentry_count ...
    + double(string(event.transition_reason) ...
    == "B2_REENTRY_PERSISTENCE_SATISFIED");
end
