function [derivative, diagnostic] = ...
        gpenmpcM600CascadedPidClosedLoopDerivative( ...
        plantState, reference, payloadKg, actualWindXyMps, ...
        windEstimateXyMps, globalTimeS, mission, calibration, profile, ...
        configuration, state, dt)
%GPENMPCM600CASCADEDPIDCLOSEDLOOPDERIVATIVE PID and shared M600 plant.

[rotorCommandN, control] = gpenmpcCascadedPidControl(plantState, ...
    reference, payloadKg, windEstimateXyMps, calibration, profile, ...
    configuration, state, dt);
[derivative, plant] = gpenmpcM600SixDofPlantDerivative(plantState, ...
    rotorCommandN, reference, payloadKg, actualWindXyMps, globalTimeS, ...
    mission, calibration, profile);
nominalAcceleration = gpenmpcKnownNominalAccelerationFromObservation( ...
    plantState, windEstimateXyMps, payloadKg, calibration, profile);

diagnostic = control;
diagnostic.actual_acceleration_mps2 = plant.actual_acceleration_mps2;
diagnostic.nominal_acceleration_mps2 = nominalAcceleration;
diagnostic.residual_acceleration_mps2 = ...
    plant.actual_acceleration_mps2 - nominalAcceleration;
diagnostic.actual_airspeed_mps = plant.actual_airspeed_mps;
diagnostic.actual_air_velocity_mps = plant.actual_air_velocity_mps;
diagnostic.true_drag_n = plant.true_drag_n;
diagnostic.true_wrench = plant.true_wrench;
diagnostic.structured_acceleration_mps2 = ...
    plant.structured_acceleration_mps2;
diagnostic.fast_acceleration_mps2 = plant.fast_acceleration_mps2;
diagnostic.true_mass_kg = plant.true_mass_kg;
end
