function extrapolated = gpenmpcReferenceExtrapolation(reference, horizonS)
%GPENMPCREFERENCEEXTRAPOLATION Constant-jerk causal reference extrapolation.

h = double(horizonS);
extrapolated = struct;
extrapolated.position_m = double(reference.position_m(:)) ...
    + h .* double(reference.velocity_mps(:)) ...
    + 0.5 .* h.^2 .* double(reference.acceleration_mps2(:)) ...
    + h.^3 ./ 6.0 .* double(reference.jerk_mps3(:));
extrapolated.velocity_mps = double(reference.velocity_mps(:)) ...
    + h .* double(reference.acceleration_mps2(:)) ...
    + 0.5 .* h.^2 .* double(reference.jerk_mps3(:));
extrapolated.acceleration_mps2 = double(reference.acceleration_mps2(:)) ...
    + h .* double(reference.jerk_mps3(:));
extrapolated.jerk_mps3 = double(reference.jerk_mps3(:));
end
