function transition = gpenmpcAdvanceCompensationState( ...
        previousCompensationI, rawTargetI, dt, filterTimeConstantS, ...
        slewLimitMps3, combinedCapMps2, authorityScale)
%GPENMPCADVANCECOMPENSATIONSTATE Shared filter, slew and cap transition.

arguments
    previousCompensationI (3,1) double
    rawTargetI (3,1) double
    dt (1,1) double {mustBePositive}
    filterTimeConstantS (1,1) double {mustBePositive}
    slewLimitMps3 (1,1) double {mustBeNonnegative}
    combinedCapMps2 (1,1) double {mustBeNonnegative}
    authorityScale (1,1) double {mustBeNonnegative}
end

targetI = gpenmpcClipNorm(rawTargetI, combinedCapMps2) .* authorityScale;
filterGain = 1.0 - exp(-dt ./ filterTimeConstantS);
lowPassI = previousCompensationI ...
    + filterGain .* (targetI - previousCompensationI);
deltaI = gpenmpcClipNorm(lowPassI - previousCompensationI, ...
    slewLimitMps3 .* dt);
appliedI = gpenmpcClipNorm(previousCompensationI + deltaI, ...
    combinedCapMps2);

transition = struct( ...
    "raw_target_i_mps2", rawTargetI, ...
    "target_i_mps2", targetI, ...
    "filter_gain", filterGain, ...
    "low_pass_i_mps2", lowPassI, ...
    "delta_i_mps2", deltaI, ...
    "applied_i_mps2", appliedI);
end
