function state = gpenmpcInitializeDesiredAttitudeContinuityState()
%GPENMPCINITIALIZEDESIREDATTITUDECONTINUITYSTATE Reset causal memory.

state = struct( ...
    "initialized", false, ...
    "angular_velocity_valid", false, ...
    "angular_acceleration_valid", false, ...
    "filtered_rotation", eye(3), ...
    "desired_angular_velocity_body_rad_s", zeros(3,1), ...
    "desired_angular_acceleration_body_rad_s2", zeros(3,1), ...
    "update_count", 0, ...
    "reset_count", 0);
end
