function [plantState, service] = gpenmpcApplyFixedC3ServiceTransition( ...
        plantState, payloadBeforeKg, payloadAfterKg, serviceDurationS, ...
        serviceNodePositionM, profile)
%GPENMPCAPPLYFIXEDC3SERVICETRANSITION Apply the public service-time contract.
%
% Account for descent, ground dwell and ascent, then initialize the next
% transit at node hover with the updated payload and energy state.

verticalDistanceM = 6.0 ...
    - (double(profile.collision_envelope.planning_radius_m) + 0.02);
verticalDurationS = verticalDistanceM ./ 1.0 + 1.0;
groundDurationS = double(serviceDurationS) - 2.0 .* verticalDurationS;
if groundDurationS < -1.0e-9
    error("gpenmpcApplyFixedC3ServiceTransition:Duration", ...
        "Service duration %.9f s is shorter than the public vertical phases.", ...
        serviceDurationS);
end
groundDurationS = max(groundDurationS, 0.0);
[descentPowerW, ~] = gpenmpcM600PhasePower( ...
    profile, payloadBeforeKg, 0.0, -1.0);
[ascentPowerW, ~] = gpenmpcM600PhasePower( ...
    profile, payloadAfterKg, 0.0, 1.0);
groundPowerW = double(profile.energy_model.ground_auxiliary_power_w);
descentEnergyJ = descentPowerW .* verticalDurationS;
groundEnergyJ = groundPowerW .* groundDurationS;
ascentEnergyJ = ascentPowerW .* verticalDurationS;

x = zeros(size(double(plantState(:))));
x(1:3) = double(serviceNodePositionM(:));
x(7) = 1.0;
x(14:19) = (double(profile.mass_properties.base_mass_kg) ...
    + double(payloadAfterKg)) .* 9.80665 ./ 6.0;
plantState = x;
service = struct( ...
    "duration_s", double(serviceDurationS), ...
    "vertical_duration_each_s", verticalDurationS, ...
    "ground_duration_s", groundDurationS, ...
    "payload_before_kg", double(payloadBeforeKg), ...
    "payload_after_kg", double(payloadAfterKg), ...
    "descent_energy_j", descentEnergyJ, ...
    "ground_energy_j", groundEnergyJ, ...
    "ascent_energy_j", ascentEnergyJ, ...
    "public_energy_j", descentEnergyJ + groundEnergyJ + ascentEnergyJ, ...
    "controller_sensitive_energy_j", ...
        descentEnergyJ + groundEnergyJ + ascentEnergyJ, ...
    "controller_specific_adjustment_j", 0.0);
end
