function task = gpenmpcLoadNativeComparisonUnit(unit, dataRoot)
%GPENMPCLOADNATIVECOMPARISONUNIT Load one method-independent MATLAB task unit.
%
% Return the fixed C3 R0 reference and exogenous task inputs. Retain recorded
% R0 state, commands and energy under parent_reference for comparison.

arguments
    unit (1,1) struct
    dataRoot (1,1) string
end
originalPath = path;
cleanup = onCleanup(@() path(originalPath));
addpath(dataRoot);
trace = gpenmpcReadNpz(unit.r0_trace_path);
ledger = jsondecode(fileread(unit.r0_ledger_path));
result = jsondecode(fileread(unit.r0_result_path));

required = ["global_time_s", "local_time_s", "leg_index", "phase_code", ...
    "reference_position_m", "reference_velocity_mps", ...
    "reference_acceleration_mps2", "reference_jerk_mps3", ...
    "payload_kg", "actual_wind_xy_mps", "wind_estimate_xy_mps", ...
    "slow_wind_measurement_bias_xy_mps", "position_m", "velocity_mps", ...
    "quaternion_wxyz", "body_rate_rad_s", "per_rotor_thrust_n", ...
    "rotor_command_n", "controller_sensitive_power_w"];
for name = required
    if ~isfield(trace, name)
        error("gpenmpcLoadNativeComparisonUnit:MissingTraceField", ...
            "R0 trace lacks required field %s.", name);
    end
end

count = numel(trace.global_time_s);
assertRows(trace.reference_position_m, count, "reference_position_m");
assertRows(trace.reference_velocity_mps, count, "reference_velocity_mps");
assertRows(trace.reference_acceleration_mps2, count, "reference_acceleration_mps2");
assertRows(trace.reference_jerk_mps3, count, "reference_jerk_mps3");
assertRows(trace.position_m, count, "position_m");
assertRows(trace.velocity_mps, count, "velocity_mps");
if any(~isfinite(double(trace.global_time_s(:)))) || ...
        any(diff(double(trace.global_time_s(:))) < -1.0e-12)
    error("gpenmpcLoadNativeComparisonUnit:Time", ...
        "R0 trace time must be finite and monotone.");
end

task = struct;
task.schema = "GPENMPC_MATLAB_NATIVE_COMPARISON_TASK_UNIT_V1";
task.mission_id = unit.mission_id;
task.planner_id = unit.planner_id;
task.city = unit.city;
task.mission_payload_sha256 = unit.mission_payload_sha256;
task.plan_payload_sha256 = unit.plan_payload_sha256;
task.reference_trace_sha256 = unit.reference_trace_sha256;
task.route_candidate_ids = unit.route_candidate_ids;
task.visit_order = unit.visit_order;
task.mission_config = ledger.mission_config;
task.plans = ledger.plans;
task.reference = struct( ...
    global_time_s=double(trace.global_time_s(:)), ...
    local_time_s=double(trace.local_time_s(:)), ...
    leg_index=double(trace.leg_index(:)), ...
    phase_code=double(trace.phase_code(:)), ...
    position_m=double(trace.reference_position_m), ...
    velocity_mps=double(trace.reference_velocity_mps), ...
    acceleration_mps2=double(trace.reference_acceleration_mps2), ...
    jerk_mps3=double(trace.reference_jerk_mps3), ...
    payload_kg=double(trace.payload_kg(:)), ...
    actual_wind_xy_mps=double(trace.actual_wind_xy_mps), ...
    wind_estimate_xy_mps=double(trace.wind_estimate_xy_mps), ...
    slow_wind_bias_xy_mps=double(trace.slow_wind_measurement_bias_xy_mps));
task.initial_state = struct( ...
    position_m=double(trace.position_m(1,:)).', ...
    velocity_mps=double(trace.velocity_mps(1,:)).', ...
    quaternion_wxyz=double(trace.quaternion_wxyz(1,:)).', ...
    body_rate_rad_s=double(trace.body_rate_rad_s(1,:)).', ...
    per_rotor_thrust_n=double(trace.per_rotor_thrust_n(1,:)).');
task.parent_reference = struct( ...
    status=string(result.status), ...
    task_complete=logical(result.task_complete_under_final_definition), ...
    mission_time_s=double(result.mission_time_s), ...
    mission_energy_j=double(result.mission_controller_sensitive_energy_j), ...
    position_m=double(trace.position_m), ...
    velocity_mps=double(trace.velocity_mps), ...
    quaternion_wxyz=double(trace.quaternion_wxyz), ...
    body_rate_rad_s=double(trace.body_rate_rad_s), ...
    per_rotor_thrust_n=double(trace.per_rotor_thrust_n), ...
    rotor_command_n=double(trace.rotor_command_n), ...
    controller_sensitive_power_w=double(trace.controller_sensitive_power_w(:)));
task.parent_control_injection_prohibited = true;
end


function assertRows(value, expected, label)
if size(value, 1) ~= expected
    error("gpenmpcLoadNativeComparisonUnit:RowCount", ...
        "%s has %d rows; expected %d.", label, size(value,1), expected);
end
end
