function task = gpenmpcLoadIndependentDevelopmentTask(caseRoot, dataRoot)
%GPENMPCLOADINDEPENDENTDEVELOPMENTTASK Load one fixed prior development task.
%
% Load the sampled C3 reference and exogenous winds from the B0 trace.
% Retain recorded state, control and energy under parent_reference. Event
% tasks reconstruct the executed leg roster from plan and route identities.

arguments
    caseRoot (1,1) string
    dataRoot (1,1) string
end

originalPath = path;
cleanup = onCleanup(@() path(originalPath)); %#ok<NASGU>
addpath(dataRoot);
tracePath = uniqueFile(caseRoot, "METHOD_TRACE_*.npz");
ledgerPath = uniqueFile(caseRoot, "METHOD_CASE_LEDGER_*.json");
resultPath = uniqueFile(caseRoot, "METHOD_CASE_RESULT_*.json");
trace = gpenmpcReadNpz(tracePath);
ledger = jsondecode(fileread(ledgerPath));
result = jsondecode(fileread(resultPath));

required = ["global_time_s", "local_time_s", "leg_index", ...
    "phase_code", "plan_version", "from_roster_index", ...
    "to_roster_index", "reference_position_m", ...
    "reference_velocity_mps", "reference_acceleration_mps2", ...
    "reference_jerk_mps3", "payload_kg", "actual_wind_xy_mps", ...
    "wind_estimate_xy_mps", "slow_wind_measurement_bias_xy_mps", ...
    "position_m", "velocity_mps", "quaternion_wxyz", ...
    "body_rate_rad_s", "per_rotor_thrust_n", "rotor_command_n", ...
    "controller_sensitive_power_w"];
for name = required
    if ~isfield(trace, name)
        error("gpenmpcLoadIndependentDevelopmentTask:MissingTraceField", ...
            "B0 trace lacks required field %s.", name);
    end
end

count = numel(trace.global_time_s);
assertRows(trace.reference_position_m, count, "reference_position_m");
assertRows(trace.reference_velocity_mps, count, "reference_velocity_mps");
assertRows(trace.reference_acceleration_mps2, count, ...
    "reference_acceleration_mps2");
assertRows(trace.reference_jerk_mps3, count, "reference_jerk_mps3");
assertRows(trace.actual_wind_xy_mps, count, "actual_wind_xy_mps");
assertRows(trace.wind_estimate_xy_mps, count, "wind_estimate_xy_mps");
if any(~isfinite(double(trace.global_time_s(:)))) || ...
        any(diff(double(trace.global_time_s(:))) < -1.0e-12)
    error("gpenmpcLoadIndependentDevelopmentTask:Time", ...
        "Reference time must be finite and monotone.");
end

legIds = unique(double(trace.leg_index(:)), "stable");
routeIds = string(result.actual_route_candidate_ids(:));
if numel(routeIds) ~= numel(legIds)
    error("gpenmpcLoadIndependentDevelopmentTask:RouteCount", ...
        "Executed route count differs from sampled leg count.");
end
actualLegs = repmat(ledger.plans(1).legs(1), numel(legIds), 1);
actualPlanVersions = zeros(numel(legIds), 1);
for legCursor = 1:numel(legIds)
    index = find(double(trace.leg_index(:)) == legIds(legCursor), 1, "first");
    planVersion = double(trace.plan_version(index));
    fromNode = double(trace.from_roster_index(index));
    toNode = double(trace.to_roster_index(index));
    planIndex = find(arrayfun(@(value) ...
        double(value.plan_version) == planVersion, ledger.plans));
    if numel(planIndex) ~= 1
        error("gpenmpcLoadIndependentDevelopmentTask:PlanVersion", ...
            "Expected one plan version %.0f.", planVersion);
    end
    legs = ledger.plans(planIndex).legs;
    match = arrayfun(@(value) ...
        double(value.from_roster_index) == fromNode && ...
        double(value.to_roster_index) == toNode && ...
        string(value.route_candidate_id) == routeIds(legCursor), legs);
    if nnz(match) ~= 1
        error("gpenmpcLoadIndependentDevelopmentTask:ExecutedLeg", ...
            "Cannot bind leg %.0f to plan %.0f and route %s.", ...
            legIds(legCursor), planVersion, routeIds(legCursor));
    end
    actualLegs(legCursor) = legs(find(match, 1, "first"));
    actualPlanVersions(legCursor) = planVersion;
end

mission = ledger.mission_config;
task = struct;
task.schema = "GPENMPC_INDEPENDENT_DEVELOPMENT_TASK_V1";
task.mission_id = string(mission.mission_id);
task.planner_id = "METHOD_BLIND_PARENT_ENERGY_PLAN";
task.city = "INDEPENDENT_DEVELOPMENT_MAP";
task.mission_payload_sha256 = string(mission.mission_payload_sha256);
task.plan_payload_sha256 = string(ledger.plans(1).plan_payload_sha256);
task.reference_trace_sha256 = gpenmpcSha256File(tracePath);
task.route_candidate_ids = routeIds;
task.visit_order = double(result.actual_visit_order(:));
task.actual_plan_versions = actualPlanVersions;
task.mission_config = mission;
task.plans = struct("plan_version", 0, "legs", actualLegs);
task.reference = struct( ...
    global_time_s=double(trace.global_time_s(:)), ...
    local_time_s=double(trace.local_time_s(:)), ...
    leg_index=double(trace.leg_index(:)), ...
    phase_code=double(trace.phase_code(:)), ...
    position_m=double(trace.reference_position_m), ...
    velocity_mps=double(trace.reference_velocity_mps), ...
    acceleration_mps2=double(trace.reference_acceleration_mps2), ...
    jerk_mps3=double(trace.reference_jerk_mps3), ...
    payload_kg=double(trace.payload_kg(:)), ...
    actual_wind_xy_mps=double(trace.actual_wind_xy_mps), ...
    wind_estimate_xy_mps=double(trace.wind_estimate_xy_mps), ...
    slow_wind_bias_xy_mps=double(trace.slow_wind_measurement_bias_xy_mps));
task.initial_state = struct( ...
    position_m=double(trace.position_m(1,:)).', ...
    velocity_mps=double(trace.velocity_mps(1,:)).', ...
    quaternion_wxyz=double(trace.quaternion_wxyz(1,:)).', ...
    body_rate_rad_s=double(trace.body_rate_rad_s(1,:)).', ...
    per_rotor_thrust_n=double(trace.per_rotor_thrust_n(1,:)).');
task.parent_reference = struct( ...
    status=string(result.status), ...
    task_complete=logical(result.task_complete_under_final_definition), ...
    mission_time_s=double(result.mission_time_s), ...
    mission_energy_j=double(result.mission_controller_sensitive_energy_j), ...
    position_m=double(trace.position_m), ...
    velocity_mps=double(trace.velocity_mps), ...
    quaternion_wxyz=double(trace.quaternion_wxyz), ...
    body_rate_rad_s=double(trace.body_rate_rad_s), ...
    per_rotor_thrust_n=double(trace.per_rotor_thrust_n), ...
    rotor_command_n=double(trace.rotor_command_n), ...
    controller_sensitive_power_w=double(trace.controller_sensitive_power_w(:)));
task.provenance = struct( ...
    source_case_root=caseRoot, ...
    source_trace_path=tracePath, ...
    source_trace_sha256=task.reference_trace_sha256, ...
    source_ledger_path=ledgerPath, ...
    source_ledger_sha256=gpenmpcSha256File(ledgerPath), ...
    source_result_path=resultPath, ...
    source_result_sha256=gpenmpcSha256File(resultPath));
task.parent_control_injection_prohibited = true;
end


function path = uniqueFile(root, pattern)
listing = dir(fullfile(root, pattern));
if numel(listing) ~= 1
    error("gpenmpcLoadIndependentDevelopmentTask:FileCount", ...
        "Expected one %s below %s, found %d.", pattern, root, numel(listing));
end
path = string(fullfile(listing(1).folder, listing(1).name));
end


function assertRows(value, expected, label)
if size(value, 1) ~= expected
    error("gpenmpcLoadIndependentDevelopmentTask:RowCount", ...
        "%s has %d rows; expected %d.", label, size(value,1), expected);
end
end
