function [loss, gradients] = gpenmpcCollapsedSparseVfeLossAndGradients(...
        parameters, xStandardized, yStandardized, inducingStandardized)
%GPENMPCCOLLAPSEDSPARSEVFELOSSANDGRADIENTS Exact VFE with custom adjoints.
%
% Cholesky operations are evaluated in double precision. Exact matrix
% adjoints are then treated as constants in a vector-Jacobian product
% through the ARD RBF kernel. MATLAB dlgradient therefore computes all
% hyperparameter gradients while preserving the collapsed VFE objective.

inducingCount = size(inducingStandardized, 1);
identity = eye(inducingCount);
lengthScale = exp(parameters.logLengthScale);
signalStd = exp(parameters.logSignalStd);
noiseStd = exp(parameters.logNoiseStd);
kernelMm = gpenmpcArdRbfKernel(inducingStandardized, ...
    inducingStandardized, lengthScale, signalStd) + 1.0e-6 .* identity;
kernelMn = gpenmpcArdRbfKernel(inducingStandardized, xStandardized, ...
    lengthScale, signalStd);

[lossValue, gradientKmm, gradientKmn, gradientSignalDiagonal, ...
    gradientLogNoise] = gpenmpcCollapsedSparseVfeObjectiveAdjoints(...
    xStandardized, yStandardized, inducingStandardized, ...
    double(extractdata(lengthScale)), double(extractdata(signalStd)), ...
    double(extractdata(noiseStd)));

surrogate = sum(kernelMm .* gradientKmm, "all") ...
    + sum(kernelMn .* gradientKmn, "all") ...
    + signalStd.^2 .* gradientSignalDiagonal ...
    + sum(parameters.logNoiseStd .* gradientLogNoise, "all");
[gradientLength, gradientSignal, gradientNoise] = dlgradient(surrogate, ...
    parameters.logLengthScale, parameters.logSignalStd, ...
    parameters.logNoiseStd);
gradients = struct;
gradients.logLengthScale = gradientLength;
gradients.logSignalStd = gradientSignal;
gradients.logNoiseStd = gradientNoise;
loss = dlarray(lossValue);
end
