function s=RflyLocalSnapshotDecoderReference(bytes,originalHostReceiveNs)
% Decode the board-local RLS1 snapshot format.
assert(isa(bytes,'uint8')&&numel(bytes)==382);bytes=bytes(:);
assert(isa(originalHostReceiveNs,'uint64')&&isscalar(originalHostReceiveNs)&&originalHostReceiveNs>0);
assert(isequal(bytes(1:4),uint8('RLS1').'),'gpenmpcNative:LocalSnapshotMagic','RLS1 required.');
md=java.security.MessageDigest.getInstance('SHA-256');md.update(typecast(bytes(1:350),'int8'));
assert(isequal(reshape(typecast(md.digest(),'uint8'),[],1),bytes(351:382)), ...
    'gpenmpcNative:LocalSnapshotDigest','RLS1 checksum mismatch.');
s=struct('schema','BOARD_LOCAL_RLS1_ORIGINAL_OBSERVATION', ...
    'identity',struct('uid',value(5:12,'uint64'),'boot_generation',value(13:20,'uint64'), ...
        'system',bytes(21),'component',bytes(22)), ...
    'original_sample_us',value(23:30,'uint64'),'original_publication_us',value(31:38,'uint64'), ...
    'original_receipt_us',value(39:46,'uint64'),'source_generation',value(47:54,'uint64'), ...
    'generation_delta',value(55:62,'uint64'),'sample_delta_us',value(63:70,'uint64'), ...
    'reset_counter',bytes(71),'state_and_origin_sha256',bytes(72:103), ...
    'odometry_instance',value(104:107,'uint32'),'task_origin_ned_m',value(108:131,'double'), ...
    'canonical_state13',value(132:235,'double'), ...
    'endpoint_receiver_hrt_us',value(236:243,'uint64'),'endpoint_wire_time_us',value(244:251,'uint64'), ...
    'endpoint_event_ordinal',value(252:259,'uint64'),'fields_updated',value(260:263,'uint32'), ...
    'receiver_instance',value(264:267,'int32'),'receiver_channel',value(268:271,'int32'), ...
    'hil_system',bytes(272),'hil_component',bytes(273),'hil_mavlink_sequence',bytes(274), ...
    'hil_payload_length',bytes(275),'hil_sensor_id',bytes(276),'original_sensor52',bytes(277:328), ...
    'gyro_instance',value(329:332,'int32'),'accel_instance',value(333:336,'int32'), ...
    'gyro_device_id',value(337:340,'uint32'),'accel_device_id',value(341:344,'uint32'), ...
    'original_endpoint_subscription_generation',value(345:348,'uint32'), ...
    'gyro_update_called',bytes(349),'accel_update_called',bytes(350), ...
    'original_bytes',bytes,'original_host_receive_ns',originalHostReceiveNs, ...
    'full_ekf_history_proven_here',false,'dll_association_proven_here',false, ...
    'control_authority',false,'time_mapping_established',false);
i=s.identity;
assert(i.uid>0&&i.boot_generation>0&&i.system>0&&i.component>0 ...
    &&s.original_sample_us>0&&s.source_generation>0 ...
    &&s.original_publication_us>=s.original_sample_us&&s.original_receipt_us>=s.original_publication_us ...
    &&any(s.state_and_origin_sha256~=0)&&s.odometry_instance<4 ...
    &&s.endpoint_receiver_hrt_us==s.original_sample_us&&s.endpoint_event_ordinal>0 ...
    &&s.receiver_instance>=0&&s.receiver_channel>=0&&s.hil_payload_length>0&&s.hil_payload_length<=65 ...
    &&bitand(s.fields_updated,uint32(56))==56&&s.gyro_update_called==1&&s.accel_update_called<=1 ...
    &&s.original_endpoint_subscription_generation>0 ...
    &&s.gyro_instance>=-1&&s.gyro_instance<4&&s.accel_instance>=-1&&s.accel_instance<4 ...
    &&all(isfinite(s.task_origin_ned_m))&&all(isfinite(s.canonical_state13)), ...
    'gpenmpcNative:LocalSnapshotFields','Inconsistent actual source/endpoint fields.');
    function v=value(indices,kind)
        v=typecast(bytes(indices),kind);[~,~,endian]=computer;if endian=='L',v=swapbytes(v);end
        v=v(:);
    end
end


