function result = runArchitectureConsistencyTests()
%RUNARCHITECTURECONSISTENCYTESTS Executable causal architecture tests.

tests = { ...
    @testAxiswiseResponsibility, ...
    @testInvalidAndZeroMeanRequireExactB1, ...
    @testA1UsesAxiswiseObserverAndRadius, ...
    @testA2PhysicalTargetIsExactB1, ...
    @testA2RuntimeAugmentationIsExactB1DuringActiveGate, ...
    @testSharedTransitionRespectsSlewAndCap, ...
    @testArchitectureConfigurationSeparatesPhysicalAuthority, ...
    @testNoFutureFieldsExistInSharedComposition};
names = [ ...
    "AXISWISE_EFFECTIVE_RESPONSIBILITY", ...
    "INVALID_OR_ZERO_EFFECT_EXACT_B1", ...
    "A1_AXISWISE_OBSERVER_AND_RADIUS", ...
    "A2_PHYSICAL_TARGET_EXACT_B1", ...
    "A2_ACTIVE_GATE_RUNTIME_EXACT_B1", ...
    "SHARED_TRANSITION_SLEW_AND_CAP", ...
    "A1_A2_PHYSICAL_AUTHORITY_SEPARATION", ...
    "SHARED_COMPOSITION_CAUSAL_NO_FUTURE"];
for index = 1:numel(tests)
    tests{index}();
end
result = struct( ...
    "schema", "GPENMPC_ARCHITECTURE_CONSISTENCY_TEST_RESULT_V1", ...
    "status", "PASS", ...
    "test_count", numel(tests), ...
    "passed_count", numel(tests), ...
    "tests", names, ...
    "whole_task_cases", 0, ...
    "formal_cases", 0);
disp(jsonencode(result));
end


function testAxiswiseResponsibility()
r = gpenmpcComputeGpResponsibility( ...
    0.8, 1.0, 0.5, [1.0;0.5;0.0], [0.2;-0.3;0.4], ...
    true, 0.25, 1.0e-12);
assert(max(abs(r.alpha_effective_f - [0.4;0.2;0.0])) <= 1.0e-12);
assert(max(abs(r.weighted_mean_f_mps2 - [0.08;-0.06;0.0])) <= 1.0e-12);
assert(~r.exact_b1_required);
end


function testInvalidAndZeroMeanRequireExactB1()
invalid = gpenmpcComputeGpResponsibility( ...
    1.0, 1.0, 0.9, ones(3,1), ones(3,1), false, 0.25, 1.0e-12);
zeroMean = gpenmpcComputeGpResponsibility( ...
    1.0, 1.0, 0.9, ones(3,1), zeros(3,1), true, 0.25, 1.0e-12);
assert(invalid.exact_b1_required && all(invalid.alpha_effective_f == 0.0));
assert(zeroMean.exact_b1_required && all(zeroMean.alpha_effective_f == 0.0));
end


function testA1UsesAxiswiseObserverAndRadius()
r = gpenmpcComputeGpResponsibility( ...
    0.8, 1.0, 0.5, [1.0;0.5;0.0], [0.2;-0.3;0.4], ...
    true, 0.25, 1.0e-12);
rhoB1 = [0.22;0.18;0.49];
rhoPost = [0.10;0.09;0.21];
observer = [0.06;-0.04;-0.20];
c = gpenmpcComposeResidualTarget( ...
    [0.1;-0.2;0.3], [0.2;0.2;0.2], rhoB1, rhoPost, r, ...
    eye(3), eye(3), observer, true);
expectedRho = (1.0-r.alpha_effective_f).*rhoB1 ...
    + r.alpha_effective_f.*rhoPost;
assert(max(abs(c.rho_applied_f_mps2 - expectedRho)) <= 1.0e-12);
assert(max(abs(c.observer_i_mps2 ...
    - (1.0-r.alpha_effective_f).*observer)) <= 1.0e-12);
assert(max(abs(c.gp_control_i_mps2 + r.weighted_mean_f_mps2)) <= 1.0e-12);
end


function testA2PhysicalTargetIsExactB1()
r = gpenmpcComputeGpResponsibility( ...
    1.0, 1.0, 0.9, ones(3,1), [0.2;-0.3;0.4], ...
    true, 0.25, 1.0e-12);
sliding = [0.1;-0.2;0.3];
boundary = [0.2;0.2;0.2];
rhoB1 = [0.22;0.18;0.49];
observer = [0.0;0.0;-0.20];
c = gpenmpcComposeResidualTarget( ...
    sliding, boundary, rhoB1, [0.10;0.09;0.21], r, ...
    eye(3), eye(3), observer, false);
expected = -rhoB1.*tanh(sliding./boundary) + observer;
assert(max(abs(c.raw_target_i_mps2 - expected)) <= 1.0e-12);
assert(all(c.alpha_physical_f == 0.0));
assert(all(c.gp_control_i_mps2 == 0.0));
end


function testA2RuntimeAugmentationIsExactB1DuringActiveGate()
[x, reference, robust, config, b1State] = fixture();
config.coordinated_physical_gp_application_enabled = false;
a2State = b1State;
sample = evidence([0.20;-0.12;0.24], [0.15;0.12;0.30]);
entered = false;
for index = 1:100
    [expected, b1State] = gpenmpcRobustSe3Augmentation( ...
        x, reference, robust, b1State, 0.01);
    [actual, a2State, diagnostic] = ...
        gpenmpcCoordinatedGpRobustSe3Augmentation( ...
        x, reference, robust, a2State, 0.01, sample, ones(3,1), config);
    assert(max(abs(actual-expected)) <= 1.0e-12);
    assert(max(abs(a2State.filtered_compensation_i_mps2 ...
        - b1State.filtered_compensation_i_mps2)) <= 1.0e-12);
    if diagnostic.gp_responsibility_blend > 0.0
        entered = true;
        assert(diagnostic.gp_authority == 0.0);
        assert(all(diagnostic.gp_physical_axis_authority_f == 0.0));
    end
end
assert(entered);
end


function testSharedTransitionRespectsSlewAndCap()
t = gpenmpcAdvanceCompensationState( ...
    [0.10;0;0], [3;4;0], 0.01, 0.20, 3.0, 0.75, 1.0);
assert(norm(t.delta_i_mps2) <= 0.03 + 1.0e-12);
assert(norm(t.applied_i_mps2) <= 0.75 + 1.0e-12);
end


function testArchitectureConfigurationSeparatesPhysicalAuthority()
[~, ~, robust, base] = fixture();
a1 = gpenmpcApplyArchitectureConfiguration( ...
    base, robust, "A1_COORDINATED_PHYSICAL");
a2 = gpenmpcApplyArchitectureConfiguration( ...
    base, robust, "A2_PREDICTION_ONLY");
assert(a1.coordinated_physical_gp_application_enabled);
assert(~a2.coordinated_physical_gp_application_enabled);
assert(max(abs(a1.coordinated_b1_radius_f_mps2 ...
    - a2.coordinated_b1_radius_f_mps2)) <= 1.0e-12);
end


function testNoFutureFieldsExistInSharedComposition()
r = gpenmpcComputeGpResponsibility( ...
    0.5, 1.0, 0.8, ones(3,1), [0.1;0.1;0.1], ...
    true, 0.25, 1.0e-12);
c = gpenmpcComposeResidualTarget( ...
    zeros(3,1), ones(3,1), ones(3,1), 0.5*ones(3,1), ...
    r, eye(3), eye(3), zeros(3,1), true);
end


function [x, reference, robust, config, state] = fixture()
x = zeros(19,1);
x(1:3) = [0.12;-0.08;0.04];
x(4:6) = [2.1;0.4;-0.1];
x(7) = 1.0;
reference = struct("position_m", zeros(3,1), ...
    "velocity_mps", [2.0;0.5;0.0]);
robust = struct( ...
    "lambda_position_s_inv", [0.7;0.7;0.8], ...
    "robust_radius_f_mps2", [0.125;0.103;0.396], ...
    "residual_tail_margin_f_mps2", [0.072;0.060;0.072], ...
    "projection_margin_f_mps2", [0.02;0.02;0.02], ...
    "robust_boundary_layer_mps", [0.2;0.2;0.2], ...
    "combined_compensation_cap_mps2", 0.75, ...
    "gp_compensation_cap_mps2", 0.4, ...
    "compensation_slew_limit_mps3", 3.0, ...
    "trust_filter_time_constant_s", 0.2);
config = struct( ...
    "minimum_soft_trust", 0.25, ...
    "gp_mean_scale", 1.0, ...
    "post_gp_residual_radius_f_mps2", [0.096;0.099;0.215], ...
    "common_robust_total_radius_f_mps2", [0.125;0.103;0.396], ...
    "coordinated_gp_execution_feedforward_enabled", false, ...
    "coordinated_gp_objective_scaling_enabled", false, ...
    "coordinated_gp_progress_scale_s", 2.5, ...
    "coordinated_gp_execution_rotor_variation_scale_n", 16.3385037412, ...
    "coordinated_gp_alpha_zero_tolerance", 1.0e-12, ...
    "gp_responsibility_gate_enabled", true, ...
    "responsibility_residual_floor_f_mps2", [0.032;0.029;0.037], ...
    "responsibility_innovation_ewma_time_constant_s", 0.30, ...
    "gp_responsibility_enter_ratio", 1.25, ...
    "gp_responsibility_exit_ratio", 0.75, ...
    "gp_responsibility_enter_dwell_s", 0.30, ...
    "gp_responsibility_exit_dwell_s", 0.60, ...
    "responsibility_cross_fade_duration_s", 0.20, ...
    "responsibility_gp_mean_filter_time_constant_s", 0.12, ...
    "responsibility_common_energy_scale_j", 500.0, ...
    "candidate_commit_hysteresis_fraction", 0.005);
state = gpenmpcInitializeRobustSe3State();
end


function value = evidence(meanF, observedF)
value = struct( ...
    "available", true, ...
    "prediction_sample_closed", true, ...
    "observed_innovation_available", true, ...
    "hard_invalid", false, ...
    "trust", 0.9, ...
    "predicted_mean_f_mps2", meanF(:).', ...
    "observed_innovation_f_mps2", observedF(:).', ...
    "calibrated_half_width_f_mps2", [0.05,0.05,0.10], ...
    "gp_frame_i_from_f", eye(3));
end
