function result = runCoordinatedGpExecutionTests()
%RUNCOORDINATEDGPEXECUTIONTESTS Test coordinated GP prediction and execution.

tests = { ...
    @testHardInvalidAndZeroAuthorityAreExactB1, ...
    @testThreeAxisSignFrameUnitsAndSingleAuthority, ...
    @testObserverIsNotAppliedWithActiveGp, ...
    @testZeroResidualIsExactB1, ...
    @testFallbackAndReentryRespectCommonSlew, ...
    @testFrozenObjectiveScalingAndExecutionCost, ...
    @testPredictorPlantAndControlSignsMatch, ...
    @testRunnerContainsOneCoordinatedExecutionCall, ...
    @testComponentLoggingSchemaIsComplete};
names = [ ...
    "HARD_INVALID_AND_ALPHA_ZERO_EXACT_B1", ...
    "THREE_AXIS_SIGN_FRAME_UNITS_AND_SINGLE_AUTHORITY", ...
    "VERTICAL_OBSERVER_NOT_APPLIED_WITH_ACTIVE_GP", ...
    "ZERO_RESIDUAL_EXACT_B1", ...
    "FALLBACK_REENTRY_COMMON_SLEW_CONTINUITY", ...
    "TRACE_DERIVED_OBJECTIVE_SCALING_FROZEN", ...
    "PREDICTOR_PLANT_AND_CONTROL_SIGNS_MATCH", ...
    "RUNNER_SINGLE_COORDINATED_GP_EXECUTION_CALL", ...
    "SEPARATE_GP_ROBUST_OBSERVER_TOTAL_LOGGING"];
for index = 1:numel(tests)
    tests{index}();
end
result = struct( ...
    "schema", "GPENMPC_COORDINATED_GP_PRE_WHOLE_TASK_TEST_RESULT_V1", ...
    "status", "PASS", ...
    "test_count", numel(tests), ...
    "passed_count", numel(tests), ...
    "tests", names);
disp(jsonencode(result));
end


function testHardInvalidAndZeroAuthorityAreExactB1()
[x, reference, robust, config, state] = fixture();
invalid = evidence([0.08;-0.04;0.12], eye(3), 0.8, true);
[expected, expectedState] = gpenmpcRobustSe3Augmentation( ...
    x, reference, robust, state, 0.01);
[actual, actualState, diagnostic] = ...
    gpenmpcCoordinatedGpRobustSe3Augmentation( ...
    x, reference, robust, state, 0.01, invalid, ones(3,1), config);
assert(isequal(actual, expected));
assert(isequaln(actualState, expectedState));
assert(diagnostic.exact_b1_fallback);

valid = evidence([0.08;-0.04;0.12], eye(3), 0.8, false);
[actual, actualState] = gpenmpcCoordinatedGpRobustSe3Augmentation( ...
    x, reference, robust, state, 0.01, valid, zeros(3,1), config);
assert(isequal(actual, expected));
assert(isequaln(actualState, expectedState));
end


function testThreeAxisSignFrameUnitsAndSingleAuthority()
[x, reference, robust, config, state] = fixture();
theta = pi ./ 5.0;
frame = [cos(theta), -sin(theta), 0; sin(theta), cos(theta), 0; 0, 0, 1];
meanF = [0.12;-0.07;0.09];
trust = 0.8;
agreement = [1.0;0.75;0.5];
valid = evidence(meanF, frame, trust, false);
[augmentation, ~, diagnostic] = gpenmpcCoordinatedGpRobustSe3Augmentation( ...
    x, reference, robust, state, 0.01, valid, agreement, config);
expectedF = -(trust .* agreement .* meanF);
expectedI = frame * expectedF;
assert(max(abs(diagnostic.gp_execution_feedforward_i_mps2 - expectedI)) <= 1.0e-12);
assert(max(abs(frame.' * diagnostic.gp_execution_feedforward_i_mps2 ...
    - expectedF)) <= 1.0e-12);
assert(all(sign(frame.' * diagnostic.gp_execution_feedforward_i_mps2) ...
    == -sign(meanF)));
assert(norm(augmentation) <= robust.combined_compensation_cap_mps2 + 1.0e-12);
assert(norm(diagnostic.gp_execution_feedforward_i_mps2) ...
    <= robust.gp_compensation_cap_mps2 + 1.0e-12);
end


function testObserverIsNotAppliedWithActiveGp()
[x, reference, robust, config, state] = fixture();
state.vertical_disturbance_ewma_mps2 = 0.24;
valid = evidence([0.08;-0.04;0.12], eye(3), 0.9, false);
[~, stateAfter, diagnostic] = gpenmpcCoordinatedGpRobustSe3Augmentation( ...
    x, reference, robust, state, 0.01, valid, ones(3,1), config);
assert(isequal(diagnostic.vertical_observer_compensation_i_mps2, zeros(3,1)));
assert(stateAfter.vertical_disturbance_ewma_mps2 == 0.24);
assert(~diagnostic.exact_b1_fallback);
end


function testZeroResidualIsExactB1()
[x, reference, robust, config, state] = fixture();
zero = evidence(zeros(3,1), eye(3), 0.9, false);
[expected, expectedState] = gpenmpcRobustSe3Augmentation( ...
    x, reference, robust, state, 0.01);
[actual, actualState, diagnostic] = ...
    gpenmpcCoordinatedGpRobustSe3Augmentation( ...
    x, reference, robust, state, 0.01, zero, ones(3,1), config);
assert(isequal(actual, expected));
assert(isequaln(actualState, expectedState));
assert(diagnostic.exact_b1_fallback);
assert(isequal(diagnostic.gp_execution_feedforward_i_mps2, zeros(3,1)));
end


function testFallbackAndReentryRespectCommonSlew()
[x, reference, robust, config, state] = fixture();
state.vertical_disturbance_ewma_mps2 = 0.2;
invalid = evidence([0.12;0.06;-0.08], eye(3), 0.9, true);
valid = evidence([0.12;0.06;-0.08], eye(3), 0.9, false);
previous = state.filtered_compensation_i_mps2;
[b1, state] = gpenmpcCoordinatedGpRobustSe3Augmentation( ...
    x, reference, robust, state, 0.01, invalid, ones(3,1), config);
assert(norm(b1 - previous) <= robust.compensation_slew_limit_mps3 .* 0.01 + 1e-12);
[active, state] = gpenmpcCoordinatedGpRobustSe3Augmentation( ...
    x, reference, robust, state, 0.01, valid, ones(3,1), config);
assert(norm(active - b1) <= robust.compensation_slew_limit_mps3 .* 0.01 + 1e-12);
[fallback, ~] = gpenmpcCoordinatedGpRobustSe3Augmentation( ...
    x, reference, robust, state, 0.01, invalid, ones(3,1), config);
assert(norm(fallback - active) <= robust.compensation_slew_limit_mps3 .* 0.01 + 1e-12);
end


function testFrozenObjectiveScalingAndExecutionCost()
root = fileparts(fileparts(mfilename("fullpath")));
runtimePath = fullfile(root, "matlab", "simulink", "assets", ...
    "enmpc_runtime_configuration.json");
config = gpenmpcLoadOrdinaryB2Config(runtimePath, 0.30);
assert(~config.coordinated_gp_execution_feedforward_enabled);
config = gpenmpcApplyCoordinatedGpConfiguration(config);
assert(config.coordinated_gp_execution_feedforward_enabled);
assert(config.coordinated_gp_objective_scaling_enabled);
assert(config.execution_consistent_cost_enabled);
assert(abs(config.progress_scale_s - 2.5) <= 1.0e-12);
assert(abs(config.execution_rotor_variation_scale_n - 16.3385037412) <= 1.0e-10);
assert(~config.prediction_effective_commit_enabled);
end


function testRunnerContainsOneCoordinatedExecutionCall()
root = fileparts(fileparts(mfilename("fullpath")));
runnerPath = fullfile(root, "matlab", "comparison", ...
    "gpenmpcRunNativeEnmpcWholeTask.m");
text = fileread(runnerPath);
needle = "gpenmpcCoordinatedGpRobustSe3Augmentation";
assert(numel(strfind(text, needle)) == 1); %#ok<STREMP>
end


function testComponentLoggingSchemaIsComplete()
root = fileparts(fileparts(mfilename("fullpath")));
runnerPath = fullfile(root, "matlab", "comparison", ...
    "gpenmpcRunNativeEnmpcWholeTask.m");
text = fileread(runnerPath);
assert(contains(text, "gp_execution_feedforward_i_mps2"));
assert(contains(text, "residual_robust_compensation_i_mps2"));
assert(contains(text, "vertical_observer_compensation_i_mps2"));
assert(contains(text, "total_compensation_i_mps2"));
end


function testPredictorPlantAndControlSignsMatch()
root = fileparts(fileparts(mfilename("fullpath")));
fixture = jsondecode(fileread(fullfile(root, "tests", "fixtures", ...
    "ordinary_b2_rollout_python_reference.json")));
stored = load(fullfile(root, "matlab", "native_training", ...
    "raw", "MATLAB_NATIVE_SPARSE_GP_MODEL.mat"), "nativeModel");
config = gpenmpcLoadOrdinaryB2Config(string(fixture.runtime_config_path));
config = gpenmpcApplyCoordinatedGpConfiguration(config);
trajectory = struct( ...
    "total_duration_s", double(fixture.trajectory.total_duration_s), ...
    "coefficients_ascending", double(fixture.trajectory.coefficients_ascending));
context = fixture.context;
context.phase_power_fcn = @fixedPower;
calibration = jsondecode(fileread(fullfile(root, "matlab", "simulink", ...
    "assets", "M600_DYN_CALIBRATION.json")));
allocation = gpenmpcM600Allocation(calibration);
context.rotor_allocation_pseudoinverse = allocation.pseudoinverse;
context.inertia_kg_m2 = allocation.inertia_kg_m2;
context.attitude_moment_gain_nm_per_rad = ...
    double(calibration.controller.attitude_moment_gain_nm_per_rad(:));
context.body_rate_moment_gain_nm_s_per_rad = ...
    double(calibration.controller.body_rate_moment_gain_nm_s_per_rad(:));
observation = fixture.observation;
observation.previous_rotor_command_n = repmat( ...
    norm(observation.previous_desired_force_n) ./ 6.0, 6, 1);
result = gpenmpcEvaluateOrdinaryB2Rollout( ...
    double(fixture.decision(:).'), config.method, trajectory, ...
    fixture.phase_state, observation, context, stored.nativeModel, ...
    fixture.causal_context_f17, config);
plant = vertcat(result.rows.predicted_gp_plant_residual_i_mps2);
control = vertcat(result.rows.predicted_gp_control_target_i_mps2);
assert(max(abs(plant + control), [], "all") <= 1.0e-12);
assert(all(isfinite(vertcat(result.rows.predicted_rotor_command_n)), "all"));
assert(result.control_activity_cost_signal == ...
    "PREDICTED_SIX_ROTOR_TOTAL_VARIATION");
end


function value = fixedPower(phase, airspeed, payload)
phaseDelta = 15.0 .* double(string(phase) == "ASCEND") ...
    + 8.0 .* double(string(phase) == "DESCEND");
value = 1050.0 + 9.0 .* airspeed.^2 + 20.0 .* payload + phaseDelta;
end


function [x, reference, robust, config, state] = fixture()
x = zeros(19,1);
x(1:3) = [0.12;-0.08;0.04];
x(4:6) = [2.1;0.4;-0.1];
x(7) = 1.0;
reference = struct( ...
    "position_m", zeros(3,1), ...
    "velocity_mps", [2.0;0.5;0.0]);
robust = struct( ...
    "lambda_position_s_inv", [0.7;0.7;0.8], ...
    "robust_radius_f_mps2", [0.125;0.103;0.396], ...
    "residual_tail_margin_f_mps2", [0.072;0.060;0.072], ...
    "projection_margin_f_mps2", [0.02;0.02;0.02], ...
    "robust_boundary_layer_mps", [0.2;0.2;0.2], ...
    "combined_compensation_cap_mps2", 0.75, ...
    "gp_compensation_cap_mps2", 0.4, ...
    "compensation_slew_limit_mps3", 3.0, ...
    "trust_filter_time_constant_s", 0.2);
config = struct( ...
    "minimum_soft_trust", 0.25, ...
    "gp_mean_scale", 1.0, ...
    "post_gp_residual_radius_f_mps2", [0.096;0.099;0.215], ...
    "coordinated_gp_alpha_zero_tolerance", 1.0e-12);
state = gpenmpcInitializeRobustSe3State();
end


function value = evidence(meanF, frame, trust, hardInvalid)
value = struct( ...
    "available", true, ...
    "prediction_sample_closed", true, ...
    "observed_innovation_available", true, ...
    "hard_invalid", logical(hardInvalid), ...
    "trust", double(trust), ...
    "predicted_mean_f_mps2", double(meanF(:).'), ...
    "gp_frame_i_from_f", double(frame));
end
