function result = runCommandContinuityTests()
%RUNCOMMANDCONTINUITYTESTS Targeted causal and fairness regression.

tests = { ...
    @testSelectorUsesSeparateFrozenTolerances, ...
    @testObjectiveHysteresisSuppressesSmallSwitch, ...
    @testObjectiveHysteresisAllowsMaterialSwitch, ...
    @testPrimaryRiskImprovementDoesNotNeedEconomicHysteresis, ...
    @testOneFailureMayHoldExactlyOnce, ...
    @testFreshSuccessRearmsExactlyOneHold, ...
    @testHardInvalidNeverUsesStaleHold, ...
    @testExactB1FallbackIsExplicit, ...
    @testB1AndB2ShareTheSameContinuityRule, ...
    @testIdentityMismatchFailsClosed, ...
    @testAuthorityViolationFailsClosed, ...
    @testNoFutureFieldsExist};
names = [ ...
    "SEPARATE_RISK_AND_TRACKING_TOLERANCES", ...
    "OBJECTIVE_HYSTERESIS_SUPPRESSES_SUBTHRESHOLD_SWITCH", ...
    "OBJECTIVE_HYSTERESIS_ALLOWS_MATERIAL_SWITCH", ...
    "PRIMARY_RISK_IMPROVEMENT_RETAINS_PRIORITY", ...
    "ONE_FAILURE_ONE_PERIOD_HOLD_ONLY", ...
    "FRESH_SUCCESS_REARMS_ONE_HOLD", ...
    "HARD_INVALID_NEVER_HOLDS_STALE_COMMAND", ...
    "EXACT_B1_FALLBACK_EXPLICIT_SOURCE", ...
    "B1_B2_SAME_CONTINUITY_RULE", ...
    "METHOD_IDENTITY_MISMATCH_FAILS_CLOSED", ...
    "AUTHORITY_VIOLATION_FAILS_CLOSED", ...
    "NO_FUTURE_FIELDS"];
for index = 1:numel(tests)
    tests{index}();
end
result = struct( ...
    "schema", "GPENMPC_COMMAND_CONTINUITY_TEST_RESULT_V1", ...
    "status", "PASS", ...
    "test_count", numel(tests), ...
    "passed_count", numel(tests), ...
    "tests", names, ...
    "whole_task_cases", 0, ...
    "formal_cases", 0);
disp(jsonencode(result));
end


function testSelectorUsesSeparateFrozenTolerances()
config = selectorConfig();
s = gpenmpcSelectEnmpcCandidate([zeros(1,7); ones(1,7).*0.01], ...
    [evaluation(100.0, 0.20, 0.10); ...
     evaluation(99.4, 0.20-0.5e-6, 0.10)], config);
assert(abs(s.risk_equivalence_tolerance-1e-6) <= 1e-15);
assert(abs(s.tracking_equivalence_tolerance-1e-4) <= 1e-15);
assert(s.primary_equivalent);
end


function testObjectiveHysteresisSuppressesSmallSwitch()
config = selectorConfig();
s = gpenmpcSelectEnmpcCandidate([zeros(1,7); ones(1,7).*0.01], ...
    [evaluation(100.0, 0.20, 0.10); ...
     evaluation(99.6, 0.20-0.5e-6, 0.10)], config);
assert(s.raw_selected_index == 2);
assert(s.index == 1 && s.profile_switch_suppressed);
end


function testObjectiveHysteresisAllowsMaterialSwitch()
config = selectorConfig();
s = gpenmpcSelectEnmpcCandidate([zeros(1,7); ones(1,7).*0.01], ...
    [evaluation(100.0, 0.20, 0.10); ...
     evaluation(99.4, 0.20-0.5e-6, 0.10)], config);
assert(s.raw_selected_index == 2 && s.index == 2);
assert(~s.profile_switch_suppressed);
end


function testPrimaryRiskImprovementDoesNotNeedEconomicHysteresis()
config = selectorConfig();
s = gpenmpcSelectEnmpcCandidate([zeros(1,7); ones(1,7).*0.01], ...
    [evaluation(100.0, 0.20, 0.10); ...
     evaluation(101.0, 0.20-2.0e-6, 0.10)], config);
assert(s.index == 2 && s.primary_improvement);
end


function testOneFailureMayHoldExactlyOnce()
config = continuityConfig();
state = gpenmpcInitializeCommandContinuity(config);
[state, first] = apply(state, successDecision(config.method), struct, ...
    config.method, config);
[state, held] = apply(state, failedDecision(config.method, false), struct, ...
    config.method, config);
[~, neutral] = apply(state, failedDecision(config.method, false), struct, ...
    config.method, config);
assert(first.source == "NEW_FEASIBLE_CANDIDATE");
assert(held.source == "ONE_PERIOD_LAST_FEASIBLE_HOLD");
assert(neutral.source == "SAFE_NEUTRAL_COMMAND");
assert(abs(held.phase_acceleration_s_inv-0.02) <= 1e-12);
end


function testFreshSuccessRearmsExactlyOneHold()
config = continuityConfig();
state = gpenmpcInitializeCommandContinuity(config);
[state, ~] = apply(state, successDecision(config.method), struct, ...
    config.method, config);
[state, ~] = apply(state, failedDecision(config.method, false), struct, ...
    config.method, config);
[state, ~] = apply(state, failedDecision(config.method, false), struct, ...
    config.method, config);
[state, ~] = apply(state, successDecision(config.method), struct, ...
    config.method, config);
[~, held] = apply(state, failedDecision(config.method, false), struct, ...
    config.method, config);
assert(held.source == "ONE_PERIOD_LAST_FEASIBLE_HOLD");
end


function testHardInvalidNeverUsesStaleHold()
config = continuityConfig();
state = gpenmpcInitializeCommandContinuity(config);
[state, ~] = apply(state, successDecision(config.method), struct, ...
    config.method, config);
[~, applied] = apply(state, failedDecision(config.method, true), ...
    struct("current_hard_invalid", true), config.method, config);
assert(applied.source == "HARD_INVALID_TERMINATION");
assert(all(applied.outer_acceleration_correction_f_mps2 == 0.0));
end


function testExactB1FallbackIsExplicit()
config = continuityConfig();
state = gpenmpcInitializeCommandContinuity(config);
decision = successDecision(config.b1_fallback_method);
audit = struct("coordinated_selected_method", config.b1_fallback_method);
[~, applied] = apply(state, decision, audit, config.method, config);
assert(applied.source == "EXACT_B1_FALLBACK");
end


function testB1AndB2ShareTheSameContinuityRule()
config = continuityConfig();
b1 = gpenmpcInitializeCommandContinuity(config);
b2 = gpenmpcInitializeCommandContinuity(config);
[b1, ~] = apply(b1, successDecision(config.b1_fallback_method), ...
    struct, config.b1_fallback_method, config);
[b2, ~] = apply(b2, successDecision(config.method), ...
    struct, config.method, config);
[~, a] = apply(b1, failedDecision(config.b1_fallback_method, false), ...
    struct, config.b1_fallback_method, config);
[~, b] = apply(b2, failedDecision(config.method, false), ...
    struct, config.method, config);
assert(a.source == b.source);
assert(a.source == "ONE_PERIOD_LAST_FEASIBLE_HOLD");
end


function testIdentityMismatchFailsClosed()
config = continuityConfig();
state = gpenmpcInitializeCommandContinuity(config);
threw = false;
try
    apply(state, successDecision("UNKNOWN_METHOD"), struct, ...
        config.method, config);
catch problem
    threw = contains(problem.identifier, "DecisionIdentity");
end
assert(threw);
end


function testAuthorityViolationFailsClosed()
config = continuityConfig();
state = gpenmpcInitializeCommandContinuity(config);
decision = successDecision(config.method);
decision.outer_acceleration_correction_f_mps2 = [0.2,0,0];
threw = false;
try
    apply(state, decision, struct, config.method, config);
catch problem
    threw = contains(problem.identifier, "CorrectionAuthority");
end
assert(threw);
end


function testNoFutureFieldsExist()
config = continuityConfig();
state = gpenmpcInitializeCommandContinuity(config);
[~, ~, event] = gpenmpcApplyCommandContinuity( ...
    state, successDecision(config.method), struct, config.method, config);
names = lower(string(fieldnames(event)));
assert(~any(contains(names, "future")));
end


function [state, applied] = apply(state, decision, audit, requested, config)
[state, applied] = gpenmpcApplyCommandContinuity( ...
    state, decision, audit, requested, config);
end


function config = continuityConfig()
config = selectorConfig();
config.method = "B2_ENMPC_GP_MEAN_TOTAL_TUBE";
config.b1_fallback_method = "B1_ENMPC_TOTAL_ROBUST_TUBE_NO_GP";
config.phase_acceleration_max_s_inv = 0.08;
config.outer_acceleration_correction_max_mps2 = 0.1;
config = gpenmpcApplyCommandContinuityConfiguration(config);
end


function config = selectorConfig()
config = struct( ...
    "decision_dimension", 7, ...
    "control_blocks", 4, ...
    "feasibility_tolerance", 1e-12, ...
    "candidate_primary_equivalence_tolerance", 1e-12, ...
    "candidate_commit_hysteresis_fraction", 0.005, ...
    "coordinated_risk_equivalence_tolerance", 1e-6, ...
    "coordinated_tracking_equivalence_tolerance", 1e-4, ...
    "coordinated_objective_relative_switch_improvement", 0.005, ...
    "prediction_effective_commit_enabled", false, ...
    "phase_acceleration_max_s_inv", 0.08, ...
    "outer_acceleration_correction_max_mps2", 0.1);
end


function item = evaluation(objective, risk, tracking)
item = struct( ...
    "objective", objective, ...
    "constraints", ones(4,1), ...
    "hard_invalid", false, ...
    "risk_violation", risk, ...
    "tracking_zone_violation", tracking);
end


function decision = successDecision(method)
decision = struct( ...
    "method", string(method), ...
    "success", true, ...
    "hard_invalid", false, ...
    "fallback_active", false, ...
    "gp_b1_fallback_active", false, ...
    "fallback_reason", "", ...
    "elapsed_seconds", 0.01, ...
    "phase_acceleration_s_inv", 0.02, ...
    "outer_acceleration_correction_f_mps2", [0.01,0.02,0.01]);
end


function decision = failedDecision(method, hardInvalid)
decision = successDecision(method);
decision.success = false;
decision.hard_invalid = hardInvalid;
decision.fallback_active = true;
decision.fallback_reason = "NO_FEASIBLE_SHOOTING_PROFILE";
decision.phase_acceleration_s_inv = 0.0;
decision.outer_acceleration_correction_f_mps2 = zeros(1,3);
end
