function result = runCausalVerticalObserverTests()
%RUNCAUSALVERTICALOBSERVERTESTS Test causal vertical-observer updates and resets.

tests = { ...
    @testReferenceAccelerationCannotLeakIntoResidualHistory, ...
    @testOfflineOnlineCausalHistoryParity, ...
    @testVerticalObserverConvergenceAndSharedAuthority, ...
    @testVerticalObserverAntiwindupAndContextReset};
names = [ ...
    "REFERENCE_ACCELERATION_NOT_USED_AS_NOMINAL_MODEL", ...
    "OFFLINE_ONLINE_CAUSAL_HISTORY_PARITY_1E12", ...
    "VERTICAL_OBSERVER_CONVERGES_WITHOUT_EXTRA_AUTHORITY", ...
    "VERTICAL_OBSERVER_ANTIWINDUP_AND_CONTEXT_RESET"];
for index = 1:numel(tests)
    tests{index}();
end
result = struct( ...
    "schema", "GPENMPC_CAUSAL_VERTICAL_OBSERVER_FOCUSED_TEST_V1", ...
    "status", "PASS", ...
    "test_count", numel(tests), ...
    "passed_count", numel(tests), ...
    "tests", names);
disp(jsonencode(result));
end


function testReferenceAccelerationCannotLeakIntoResidualHistory()
history = zeros(3,1);
referenceAcceleration = [0;0;0.1]; %#ok<NASGU>
[next, residual, valid] = gpenmpcAdvanceCausalResidualHistory( ...
    history, zeros(3,1), zeros(3,1), zeros(3,1), eye(3), ...
    0.01, true, 0.50);
assert(valid);
assert(max(abs(residual)) <= 1.0e-15);
assert(max(abs(next)) <= 1.0e-15);
end


function testOfflineOnlineCausalHistoryParity()
count = 9;
dt = 0.01;
time = (0:count-1).' .* dt;
nominal = repmat([0.03, -0.02, 0.04], count, 1);
residual = repmat([0.08, 0.05, -0.06], count, 1);
velocity = zeros(count, 3);
for index = 1:count-1
    velocity(index+1,:) = velocity(index,:) ...
        + dt .* (nominal(index,:) + residual(index,:));
end
trace = struct( ...
    "global_time_s", time, ...
    "velocity_mps", velocity, ...
    "nominal_acceleration_mps2", nominal, ...
    "leg_index", ones(count,1), ...
    "plan_version", ones(count,1), ...
    "from_roster_index", ones(count,1), ...
    "to_roster_index", 2 .* ones(count,1), ...
    "reference_velocity_mps", repmat([1,0,0], count, 1), ...
    "estimated_air_velocity_i_mps", velocity, ...
    "reference_acceleration_mps2", repmat([0,0,0.1], count, 1), ...
    "payload_kg", ones(count,1), ...
    "tilt_rad", zeros(count,1), ...
    "rotor_command_n", 18 .* ones(count,6), ...
    "phase_code", ones(count,1));
offline = gpenmpcExtractCausalAeroF17(trace);

online = zeros(count,3);
state = zeros(3,1);
for index = 1:count
    online(index,:) = state.';
    nextIndex = min(index + 1, count);
    [state, ~, ~] = gpenmpcAdvanceCausalResidualHistory( ...
        state, velocity(index,:).', velocity(nextIndex,:).', ...
        nominal(index,:).', eye(3), dt, index < count, 0.50);
end
assert(max(abs(offline.features(:,15:17) - online), [], "all") <= 1.0e-12);
end


function testVerticalObserverConvergenceAndSharedAuthority()
config = robustConfig();
state = gpenmpcInitializeRobustSe3State();
state = gpenmpcResetCausalVerticalDisturbanceObserver( ...
    state, zeros(3,1), 0.0, 1.0, 1.2);
state = gpenmpcCommitCausalVerticalDisturbanceObserver( ...
    state, zeros(3,1), zeros(3,1), 0.0, 1.0, 1.2);
dt = 0.01;
disturbance = 0.20;
for index = 1:500
    time = index .* dt;
    velocity = [0;0;disturbance .* time];
    [state, ~] = gpenmpcObserveCausalVerticalDisturbance( ...
        state, velocity, time, 1.0, 1.2, config);
    state = gpenmpcCommitCausalVerticalDisturbanceObserver( ...
        state, velocity, zeros(3,1), time, 1.0, 1.2);
end
assert(abs(state.vertical_disturbance_ewma_mps2 - disturbance) <= 2.0e-5);

x = zeros(19,1); x(7) = 1.0;
reference = struct("position_m", zeros(3,1), "velocity_mps", zeros(3,1));
state.filtered_compensation_i_mps2 = zeros(3,1);
previous = state.filtered_compensation_i_mps2;
for index = 1:100
    [augmentation, state, diagnostic] = gpenmpcRobustSe3Augmentation( ...
        x, reference, config, state, dt);
    assert(norm(augmentation) <= config.combined_compensation_cap_mps2 + 1.0e-12);
    assert(norm(augmentation - previous) ...
        <= config.compensation_slew_limit_mps3 .* dt + 1.0e-12);
    previous = augmentation;
end
assert(diagnostic.vertical_observer_compensation_i_mps2(3) < -0.19);
assert(norm(diagnostic.raw_target_i_mps2) ...
    <= config.combined_compensation_cap_mps2 + 1.0e-12);

% Identical shared inner-loop states give bit-exact B1 and hard-invalid-B2
% outputs because the GP branch is absent from this common function.
stateB1 = state;
stateB2HardInvalid = state;
[b1, stateB1] = gpenmpcRobustSe3Augmentation( ...
    x, reference, config, stateB1, dt);
[b2Hard, stateB2HardInvalid] = gpenmpcRobustSe3Augmentation( ...
    x, reference, config, stateB2HardInvalid, dt);
assert(isequal(b1, b2Hard));
assert(isequal(stateB1, stateB2HardInvalid));
end


function testVerticalObserverAntiwindupAndContextReset()
config = robustConfig();
state = gpenmpcInitializeRobustSe3State();
state = gpenmpcResetCausalVerticalDisturbanceObserver( ...
    state, zeros(3,1), 0.0, 1.0, 1.2);
state.vertical_disturbance_ewma_mps2 = 0.15;
state = gpenmpcCommitCausalVerticalDisturbanceObserver( ...
    state, zeros(3,1), zeros(3,1), 0.0, 1.0, 1.2);
control = struct("rotor_saturated", true, ...
    "force_projection_norm_mismatch_n", 0.0);
state = gpenmpcRobustSe3ObserveControl(state, control, 0.01);
[state, diagnostic] = gpenmpcObserveCausalVerticalDisturbance( ...
    state, [0;0;0.02], 0.01, 1.0, 1.2, config);
assert(~diagnostic.updated);
assert(abs(state.vertical_disturbance_ewma_mps2 - 0.15) <= 1.0e-15);
assert(state.vertical_observer_antiwindup_hold_count == 1);

state = gpenmpcCommitCausalVerticalDisturbanceObserver( ...
    state, [0;0;0.02], zeros(3,1), 0.01, 1.0, 1.2);
[state, diagnostic] = gpenmpcObserveCausalVerticalDisturbance( ...
    state, [0;0;0.02], 0.02, 1.0, 0.7, config);
assert(diagnostic.reset);
assert(state.vertical_disturbance_ewma_mps2 == 0.0);
assert(state.vertical_observer_reset_count >= 2);
end


function config = robustConfig()
config = struct( ...
    "lambda_position_s_inv", [0.7;0.7;0.8], ...
    "robust_radius_f_mps2", [0.125;0.103;0.396], ...
    "residual_tail_margin_f_mps2", [0.072;0.060;0.072], ...
    "projection_margin_f_mps2", [0.02;0.02;0.02], ...
    "robust_boundary_layer_mps", [0.2;0.2;0.2], ...
    "combined_compensation_cap_mps2", 0.75, ...
    "compensation_slew_limit_mps3", 3.0, ...
    "trust_filter_time_constant_s", 0.2);
end
