function receipt = runDisturbedDevelopmentFocusedSmoke( ...
        projectRoot, outputRoot, sourceRoot)
%RUNDISTURBEDDEVELOPMENTFOCUSEDSMOKE Test B1/B2 interfaces on a 400-sample disturbed task.

arguments
    projectRoot (1,1) string
    outputRoot (1,1) string = ""
    sourceRoot (1,1) string = ...
        gpenmpcExternalPath("independent_development_cases")
end
if strlength(outputRoot) == 0
    outputRoot = fullfile(projectRoot, "reports");
end
addpath(genpath(fullfile(projectRoot, "matlab")));
caseRoot = fullfile(sourceRoot, "ENMPC_DV_001", ...
    "B0_FIXED_TIMING_ROBUST_SE3");
task = gpenmpcLoadIndependentDevelopmentTask(caseRoot, ...
    fullfile(projectRoot, "matlab", "data"));
assert(task.mission_id == "ENMPC_DV_001");
assert(task.parent_control_injection_prohibited);
sourceTraceSha = task.reference_trace_sha256;
if isfield(task, "parent_reference")
    task = rmfield(task, "parent_reference");
end
assets = gpenmpcLoadNativeEnmpcComparisonAssets(projectRoot, 0.30);
methods = [assets.enmpc.b1_fallback_method, assets.enmpc.method];
assert(isequal(methods, ["B1_ENMPC_TOTAL_ROBUST_TUBE_NO_GP", ...
    "B2_ENMPC_GP_MEAN_TOTAL_TUBE"]));

rows = repmat(struct("method_id", "", "sample_count", 0, ...
    "solver_update_count", 0, "solver_success_count", 0, ...
    "solver_deadline_miss_count", 0, "solver_fallback_count", 0, ...
    "gp_adopted_count", 0, "gp_downweighted_count", 0, ...
    "gp_hard_invalid_count", 0, "gp_b1_fallback_count", 0, ...
    "supervisor_transition_count", 0, ...
    "supervisor_failure_hold_count", 0, ...
    "supervisor_fixed_reference_count", 0, ...
    "supervisor_b1_direct_request_count", 0, ...
    "supervisor_b2_probe_request_count", 0, ...
    "supervisor_reentry_count", 0, ...
    "finite_trace", false, "attitude_continuity_enabled", false, ...
    "focused_smoke", false), 2, 1);
for index = 1:2
    [trace, result] = gpenmpcRunNativeEnmpcWholeTask( ...
        task, methods(index), assets, MaximumInnerSamples=400, ...
        FocusedSmoke=true, AttitudeContinuityEnabled=true, ...
        AttitudeContinuityTimeConstantS=0.08, ...
        AttitudeContinuityMaximumAngularVelocityRadS=1.5, ...
        AttitudeContinuityMaximumAngularAccelerationRadS2=8.0, ...
        AttitudeContinuityMaximumContinuousDtS=0.05);
    assert(result.focused_smoke && ~result.full_task_mode);
    assert(result.sample_count == 400 && result.stopped_by_maximum_inner_samples);
    assert(all(logical(trace.attitude_continuity_enabled)));
    assert(allFinite(trace));
    if index == 1
        assert(result.solver.gp_adopted_count == 0 ...
            && result.solver.gp_downweighted_count == 0 ...
            && result.solver.gp_hard_invalid_count == 0 ...
            && result.solver.gp_b1_fallback_count == 0);
    end
    rows(index) = struct("method_id", methods(index), ...
        "sample_count", result.sample_count, ...
        "solver_update_count", result.solver.update_count, ...
        "solver_success_count", result.solver.success_count, ...
        "solver_deadline_miss_count", result.solver.deadline_miss_count, ...
        "solver_fallback_count", result.solver.fallback_count, ...
        "gp_adopted_count", result.solver.gp_adopted_count, ...
        "gp_downweighted_count", result.solver.gp_downweighted_count, ...
        "gp_hard_invalid_count", result.solver.gp_hard_invalid_count, ...
        "gp_b1_fallback_count", result.solver.gp_b1_fallback_count, ...
        "supervisor_transition_count", getNumeric(result.solver, ...
            "supervisor_transition_count"), ...
        "supervisor_failure_hold_count", getNumeric(result.solver, ...
            "supervisor_failure_hold_count"), ...
        "supervisor_fixed_reference_count", getNumeric(result.solver, ...
            "supervisor_fixed_reference_count"), ...
        "supervisor_b1_direct_request_count", getNumeric(result.solver, ...
            "supervisor_b1_direct_request_count"), ...
        "supervisor_b2_probe_request_count", getNumeric(result.solver, ...
            "supervisor_b2_probe_request_count"), ...
        "supervisor_reentry_count", getNumeric(result.solver, ...
            "supervisor_reentry_count"), ...
        "finite_trace", true, ...
        "attitude_continuity_enabled", ...
            all(logical(trace.attitude_continuity_enabled)), ...
        "focused_smoke", true);
end

receipt = struct;
receipt.schema = "GPENMPC_DISTURBED_DEVELOPMENT_FOCUSED_SMOKE_V1";
receipt.status = "PASS_DV001_B1_B2_400_SAMPLE_FOCUSED_SMOKE";
receipt.mission_id = "ENMPC_DV_001";
receipt.source_trace_sha256 = sourceTraceSha;
receipt.outer_period_s = 0.30;
receipt.solver_deadline_s = 0.28;
receipt.prediction_step_s = 0.20;
receipt.horizon_steps = 8;
receipt.prediction_horizon_s = 1.60;
receipt.rows = rows;
resultReceipt = gpenmpcWriteContentAddressedJson(outputRoot, ...
    "DISTURBED_DEVELOPMENT_FOCUSED_SMOKE", receipt);
receipt.receipt_path = resultReceipt.path;
receipt.receipt_sha256 = resultReceipt.sha256;
fprintf("DISTURBED_FOCUSED_SMOKE_PASS samples=400 methods=2\n");
end


function pass = allFinite(trace)
pass = true;
names = fieldnames(trace);
for index = 1:numel(names)
    value = trace.(names{index});
    if isnumeric(value) && any(~isfinite(double(value)), "all")
        pass = false;
        return
    end
end
end


function value = getNumeric(source, field)
if isfield(source, field)
    value = double(source.(field));
else
    value = 0.0;
end
end
