function receipt = runDesiredAttitudeContinuityTests(projectRoot)
%RUNDESIREDATTITUDECONTINUITYTESTS Test SO(3) attitude-command continuity.

arguments
    projectRoot (1,1) string
end
% Append project dynamics helpers after the implementation under test.
addpath(fullfile(projectRoot, "matlab", "dynamics"), "-end");
assetRoot = fullfile(projectRoot, "matlab", "simulink", "assets");
calibration = jsondecode(fileread(fullfile(assetRoot, ...
    "M600_DYN_CALIBRATION.json")));
profile = jsondecode(fileread(fullfile(assetRoot, ...
    "M600_PLATFORM_PROFILE.json")));

names = strings(0,1);
passed = false(0,1);
details = struct;

profiles = gpenmpcAttitudeContinuityProfiles();
record("finite_predevelopment_profile_set_is_closed", ...
    numel(profiles) == 3 ...
    && isequal([profiles.time_constant_s], [0.04, 0.08, 0.12]) ...
    && all([profiles.maximum_angular_velocity_rad_s] == 1.5) ...
    && all([profiles.maximum_angular_acceleration_rad_s2] == 8.0));

payloadKg = 1.7;
mass = double(profile.mass_properties.base_mass_kg) + payloadKg;
hover = mass .* 9.80665 ./ 6.0;
quaternion = [0.9979; 0.031; -0.047; 0.018];
quaternion = quaternion ./ norm(quaternion);
plantState = [[1.2;-0.7;14.3]; [0.8;-0.4;0.2]; quaternion; ...
    [0.06;-0.03;0.04]; repmat(hover,6,1)];
reference = struct("position_m", [1.4;-0.5;14.5], ...
    "velocity_mps", [0.7;-0.2;0.1], ...
    "acceleration_mps2", [0.22;-0.15;0.08], ...
    "jerk_mps3", zeros(3,1));
augmentation = [0.03;-0.04;0.02];
wind = [1.1;-0.6];
[actualRotor, actualDiagnostic] = gpenmpcRobustSe3Control( ...
    plantState, reference, payloadKg, wind, augmentation, calibration, profile);
[legacyRotor, legacyDiagnostic] = legacyController( ...
    plantState, reference, payloadKg, wind, augmentation, calibration, profile);
legacyFields = ["desired_force_raw_n", "desired_force_projected_n", ...
    "desired_rotation", "attitude_error", "desired_moment_nm", ...
    "desired_thrust_n", "raw_rotor_command_n", "rotor_command_n"];
exact = isequal(actualRotor, legacyRotor);
for name = legacyFields
    exact = exact && isequal(actualDiagnostic.(name), legacyDiagnostic.(name));
end
record("default_controller_is_exact_parent_equivalent", exact);

disabledState = gpenmpcInitializeDesiredAttitudeContinuityState();
disabledConfig = baseConfig(false);
[disabledCommand, disabledNext] = gpenmpcUpdateDesiredAttitudeContinuity( ...
    disabledState, rotationY(0.3), 0.01, false, disabledConfig);
record("disabled_layer_is_state_transparent", ...
    ~disabledCommand.enabled && isequal(disabledNext, disabledState) ...
    && isequal(disabledCommand.desired_rotation, rotationY(0.3)));

config = baseConfig(true);
state = gpenmpcInitializeDesiredAttitudeContinuityState();
orthonormal = true;
for index = 1:500
    time = (index - 1) .* 0.01;
    raw = rotationZ(0.19 .* sin(0.8 .* time)) ...
        * rotationY(0.24 .* cos(1.3 .* time));
    [command, state] = gpenmpcUpdateDesiredAttitudeContinuity( ...
        state, raw, 0.01, index == 1, config);
    rotation = command.desired_rotation;
    orthonormal = orthonormal ...
        && norm(rotation.' * rotation - eye(3), "fro") < 2.0e-12 ...
        && abs(det(rotation) - 1.0) < 2.0e-12 ...
        && all(isfinite(rotation), "all");
end
record("filtered_rotation_is_finite_and_on_so3", orthonormal);

boundedConfig = config;
  boundedConfig.maximum_angular_velocity_rad_s = 0.40;
  boundedConfig.maximum_angular_acceleration_rad_s2 = 1.20;
  boundedConfig.maximum_angular_jerk_rad_s3 = 4.0;
state = gpenmpcInitializeDesiredAttitudeContinuityState();
omegaBound = true;
  alphaBound = true;
  alphaSlewBound = true;
  previousAlpha = zeros(3,1);
  previousRotation = eye(3);
for index = 1:80
    raw = rotationY((-1).^index .* 0.45);
    [command, state] = gpenmpcUpdateDesiredAttitudeContinuity( ...
        state, raw, 0.01, index == 1, boundedConfig);
    omegaBound = omegaBound ...
        && norm(command.desired_angular_velocity_body_rad_s) <= 0.40 + 1e-12;
      alphaBound = alphaBound ...
          && norm(command.desired_angular_acceleration_body_rad_s2) <= 1.20 + 1e-12;
      if command.angular_acceleration_valid
          transportedPreviousAlpha = command.desired_rotation.' ...
              * previousRotation * previousAlpha;
          alphaSlewBound = alphaSlewBound ...
              && norm(command.desired_angular_acceleration_body_rad_s2 ...
              - transportedPreviousAlpha) <= 4.0 .* 0.01 + 1e-12;
      end
      previousAlpha = command.desired_angular_acceleration_body_rad_s2;
      previousRotation = command.desired_rotation;
  end
  record("desired_rate_acceleration_and_angular_jerk_are_bounded", ...
      omegaBound && alphaBound && alphaSlewBound);

state = gpenmpcInitializeDesiredAttitudeContinuityState();
[~, state] = gpenmpcUpdateDesiredAttitudeContinuity( ...
    state, rotationY(0.0), 0.01, true, config);
[~, state] = gpenmpcUpdateDesiredAttitudeContinuity( ...
    state, rotationY(0.1), 0.01, false, config);
[legReset, state] = gpenmpcUpdateDesiredAttitudeContinuity( ...
    state, rotationZ(0.7), 0.01, true, config);
[timeReset, ~] = gpenmpcUpdateDesiredAttitudeContinuity( ...
    state, rotationZ(-0.4), 0.20, false, config);
record("leg_service_and_time_discontinuity_reset_causally", ...
    legReset.reset_active && ~legReset.angular_velocity_valid ...
    && norm(legReset.desired_angular_velocity_body_rad_s) < 1e-14 ...
    && timeReset.reset_active && timeReset.time_discontinuity ...
    && norm(timeReset.desired_angular_acceleration_body_rad_s2) < 1e-14);

prefixStateA = gpenmpcInitializeDesiredAttitudeContinuityState();
prefixStateB = gpenmpcInitializeDesiredAttitudeContinuityState();
prefixEqual = true;
prefix = [0.0, 0.01, 0.025, 0.018];
for index = 1:numel(prefix)
    [outA, prefixStateA] = gpenmpcUpdateDesiredAttitudeContinuity( ...
        prefixStateA, rotationY(prefix(index)), 0.01, index == 1, config);
    [outB, prefixStateB] = gpenmpcUpdateDesiredAttitudeContinuity( ...
        prefixStateB, rotationY(prefix(index)), 0.01, index == 1, config);
    prefixEqual = prefixEqual && isequal(outA, outB);
end
[~, prefixStateA] = gpenmpcUpdateDesiredAttitudeContinuity( ...
    prefixStateA, rotationY(0.4), 0.01, false, config); %#ok<NASGU>
[~, prefixStateB] = gpenmpcUpdateDesiredAttitudeContinuity( ...
    prefixStateB, rotationY(-0.3), 0.01, false, config); %#ok<NASGU>
record("future_suffix_cannot_change_past_filtered_prefix", prefixEqual);

frequencyHz = 0.29;
dt = 0.01;
time = (0:dt:79.99).';
rawAngle = 0.16 .* sin(2.0 .* pi .* frequencyHz .* time);
filteredAngle = zeros(size(rawAngle));
responseConfig = config;
responseConfig.time_constant_s = 0.40;
responseConfig.maximum_angular_velocity_rad_s = 20.0;
responseConfig.maximum_angular_acceleration_rad_s2 = 200.0;
state = gpenmpcInitializeDesiredAttitudeContinuityState();
for index = 1:numel(time)
    [command, state] = gpenmpcUpdateDesiredAttitudeContinuity( ...
        state, rotationY(rawAngle(index)), dt, index == 1, responseConfig);
    filteredVector = gpenmpcSo3LogVee(command.desired_rotation);
    filteredAngle(index) = filteredVector(2);
end
steady = time >= 20.0;
rawAmplitude = harmonicAmplitude(time(steady), rawAngle(steady), frequencyHz);
filteredAmplitude = harmonicAmplitude( ...
    time(steady), filteredAngle(steady), frequencyHz);
details.known_frequency_hz = frequencyHz;
details.raw_rotation_amplitude_rad = rawAmplitude;
details.filtered_rotation_amplitude_rad = filteredAmplitude;
details.response_ratio = filteredAmplitude ./ rawAmplitude;
record("rotation_filter_reduces_known_command_frequency_response", ...
    details.response_ratio < 0.86 && details.response_ratio > 0.70);

enabledConfig = config;
state = gpenmpcInitializeDesiredAttitudeContinuityState();
[~, state] = gpenmpcUpdateDesiredAttitudeContinuity( ...
    state, actualDiagnostic.desired_rotation, 0.01, true, enabledConfig);
[attitudeCommand, ~] = gpenmpcUpdateDesiredAttitudeContinuity( ...
    state, rotationY(0.04) * actualDiagnostic.desired_rotation, ...
    0.01, false, enabledConfig);
[rotor, diagnostic] = gpenmpcRobustSe3Control(plantState, reference, ...
    payloadKg, wind, augmentation, calibration, profile, attitudeCommand);
record("enabled_geometric_feedforward_interface_is_finite", ...
    all(isfinite(rotor)) && diagnostic.attitude_continuity_enabled ...
    && all(isfinite(diagnostic.geometric_feedforward_moment_nm)));

receipt = struct( ...
    "schema", "GPENMPC_DESIRED_ATTITUDE_CONTINUITY_TEST_RECEIPT_V1", ...
    "tests", names, "passed", passed, "details", details, ...
    "passed_count", nnz(passed), "planned_count", numel(passed), ...
    "all_pass", all(passed));
if ~receipt.all_pass
    error("runDesiredAttitudeContinuityTests:Failure", ...
        "Attitude continuity tests failed: %s", ...
        strjoin(cellstr(names(~passed)), ", "));
end

    function record(name, condition)
        names(end+1,1) = string(name); %#ok<AGROW>
        passed(end+1,1) = logical(condition); %#ok<AGROW>
    end
end

function config = baseConfig(enabled)
config = struct( ...
    "enabled", logical(enabled), ...
    "time_constant_s", 0.08, ...
      "maximum_angular_velocity_rad_s", 1.5, ...
      "maximum_angular_acceleration_rad_s2", 8.0, ...
      "maximum_angular_jerk_rad_s3", 50.0, ...
      "maximum_continuous_dt_s", 0.05);
end

function amplitude = harmonicAmplitude(time, signal, frequency)
phase = exp(-1i .* 2.0 .* pi .* frequency .* double(time(:)));
amplitude = 2.0 .* abs(sum(double(signal(:)) .* phase)) ./ numel(time);
end

function rotation = rotationY(angle)
rotation = [cos(angle), 0, sin(angle); 0, 1, 0; ...
    -sin(angle), 0, cos(angle)];
end

function rotation = rotationZ(angle)
rotation = [cos(angle), -sin(angle), 0; sin(angle), cos(angle), 0; ...
    0, 0, 1];
end

function [rotorCommandN, diagnostic] = legacyController( ...
        plantState, reference, payloadKg, windEstimateXyMps, ...
        augmentationIMps2, calibration, profile)
gravity = 9.80665;
x = double(plantState(:));
allocation = gpenmpcM600Allocation(calibration);
controller = calibration.controller;
kp = double(controller.position_gain_s2(:));
kd = double(controller.velocity_gain_s(:));
kr = double(controller.attitude_moment_gain_nm_per_rad(:));
kw = double(controller.body_rate_moment_gain_nm_s_per_rad(:));
p = x(1:3); v = x(4:6);
rotation = gpenmpcQuaternionRotation(x(7:10));
omega = x(11:13);
nominalMassKg = double(profile.mass_properties.base_mass_kg) + double(payloadKg);
referenceAir = double(reference.velocity_mps(:)) ...
    - [double(windEstimateXyMps(:)); 0];
dragFeedforward = allocation.nominal_drag_n_per_mps2 ...
    .* referenceAir .* abs(referenceAir);
desiredForceRaw = nominalMassKg .* (double(reference.acceleration_mps2(:)) ...
    + kp .* (double(reference.position_m(:)) - p) ...
    + kd .* (double(reference.velocity_mps(:)) - v) ...
    + [0; 0; gravity] + double(augmentationIMps2(:))) ...
    + dragFeedforward;
[desiredForce, projectionMismatch] = gpenmpcProjectForce( ...
    desiredForceRaw, allocation.total_thrust_upper_n, ...
    allocation.maximum_tilt_rad);
b3 = desiredForce ./ max(norm(desiredForce), 1e-15);
b1Command = [1; 0; 0]; b2 = cross(b3, b1Command);
if norm(b2) < 1e-9
    b1Command = [0; 1; 0]; b2 = cross(b3, b1Command);
end
b2 = b2 ./ max(norm(b2), 1e-15); b1 = cross(b2, b3);
desiredRotation = [b1, b2, b3];
attitudeError = 0.5 .* gpenmpcVee( ...
    desiredRotation.' * rotation - rotation.' * desiredRotation);
momentNm = -kr .* attitudeError - kw .* omega ...
    + cross(omega, allocation.inertia_kg_m2 * omega);
desiredThrustN = max(dot(desiredForce, rotation(:, 3)), 0.0);
rawCommandN = allocation.pseudoinverse * [desiredThrustN; momentNm];
rotorCommandN = min(max(rawCommandN, 0.0), allocation.per_rotor_upper_n);
diagnostic = struct( ...
    "desired_force_raw_n", desiredForceRaw, ...
    "desired_force_projected_n", desiredForce, ...
    "desired_rotation", desiredRotation, ...
    "attitude_error", attitudeError, ...
    "desired_moment_nm", momentNm, ...
    "desired_thrust_n", desiredThrustN, ...
    "raw_rotor_command_n", rawCommandN, ...
    "rotor_command_n", rotorCommandN, ...
    "force_projection_norm_mismatch_n", projectionMismatch);
end
