function result = runExecutionAlignmentTests(projectRoot, implementationRoot, outputPath)
%RUNEXECUTIONALIGNMENTTESTS Test prediction and execution alignment.

arguments
    projectRoot (1,1) string
    implementationRoot (1,1) string
    outputPath (1,1) string = ""
end

originalPath = path;
cleanup = onCleanup(@() path(originalPath));
addpath(genpath(fullfile(projectRoot, "matlab")), "-end");
addpath(genpath(implementationRoot), "-begin");
rehash path;

fixturePath = fullfile(implementationRoot, "tests", "fixtures", ...
    "ordinary_b2_rollout_python_reference.json");
fixture = jsondecode(fileread(fixturePath));
modelPath = fullfile(implementationRoot, "matlab", ...
    "native_training", "raw", ...
    "MATLAB_NATIVE_SPARSE_GP_MODEL.mat");
stored = load(modelPath, "nativeModel");
config = gpenmpcLoadOrdinaryB2Config(string(fixture.runtime_config_path));
assert(~config.continuous_axis_weight_supervision_enabled);
assert(~config.execution_consistent_cost_enabled);

trajectory = struct( ...
    "total_duration_s", double(fixture.trajectory.total_duration_s), ...
    "coefficients_ascending", double(fixture.trajectory.coefficients_ascending));
phaseState = fixture.phase_state;
observation = fixture.observation;
context = fixture.context;
context.phase_power_fcn = @fixedPower;
causal = fixture.causal_context_f17;
decision = double(fixture.decision(:).');

legacyB1 = gpenmpcEvaluateOrdinaryB2Rollout(decision, ...
    config.b1_fallback_method, trajectory, phaseState, observation, ...
    context, struct, struct("valid", false, "values", zeros(4,1)), config);
legacyB2 = gpenmpcEvaluateOrdinaryB2Rollout(decision, config.method, ...
    trajectory, phaseState, observation, context, stored.nativeModel, ...
    causal, config);
legacyB1Error = comparisonError(legacyB1, fixture.python_b1);
legacyB2Error = comparisonError(legacyB2, fixture.python_b2);
assert(legacyB1Error <= 3.0e-9);
assert(legacyB2Error <= 3.0e-9);

calibrationPath = fullfile(implementationRoot, "matlab", "simulink", ...
    "assets", "M600_DYN_CALIBRATION.json");
calibration = jsondecode(fileread(calibrationPath));
allocation = gpenmpcM600Allocation(calibration);
context.rotor_allocation_pseudoinverse = allocation.pseudoinverse;
context.inertia_kg_m2 = allocation.inertia_kg_m2;
context.attitude_moment_gain_nm_per_rad = ...
    double(calibration.controller.attitude_moment_gain_nm_per_rad(:));
context.body_rate_moment_gain_nm_s_per_rad = ...
    double(calibration.controller.body_rate_moment_gain_nm_s_per_rad(:));
observation.previous_rotor_command_n = ...
    repmat(norm(observation.previous_desired_force_n) ./ 6.0, 6, 1);

executionConfig = config;
executionConfig.execution_consistent_cost_enabled = true;
executionResult = gpenmpcEvaluateOrdinaryB2Rollout(decision, ...
    executionConfig.method, trajectory, phaseState, observation, context, ...
    stored.nativeModel, causal, executionConfig);
assert(executionResult.control_activity_cost_signal == ...
    "PREDICTED_SIX_ROTOR_TOTAL_VARIATION");
assert(all(isfinite(executionResult.objective_vector)));
assert(all(arrayfun(@(x) all(isfinite(x.predicted_rotor_command_n)), ...
    executionResult.rows)));

continuousConfig = config;
continuousConfig.continuous_axis_weight_supervision_enabled = true;
state = gpenmpcInitializeOuterSupervisor(continuousConfig);
lowEvidence = struct( ...
    "available", true, ...
    "causal_valid", true, ...
    "observed_innovation_available", true, ...
    "gp_model_available", true, ...
    "hard_invalid", false, ...
    "trust", 0.30, ...
    "consistency_ewma_aggregate", 0.05);
request = gpenmpcOuterSupervisorRequest( ...
    state, true, continuousConfig, lowEvidence);
assert(request.requested_method == continuousConfig.method);
assert(request.request_reason == "CONTINUOUS_AXIS_WEIGHTED_B2");
staleRequest = gpenmpcOuterSupervisorRequest( ...
    state, false, continuousConfig, lowEvidence);
assert(staleRequest.requested_method == continuousConfig.b1_fallback_method);

result = struct( ...
    "schema", "GPENMPC_EXECUTION_ALIGNMENT_TEST_RESULT_V1", ...
    "status", "PASS", ...
    "test_count", 10, ...
    "passed_count", 10, ...
    "legacy_b1_max_error", legacyB1Error, ...
    "legacy_b2_max_error", legacyB2Error, ...
    "execution_cost_signal", executionResult.control_activity_cost_signal, ...
    "continuous_supervisor_soft_gate_removed", true, ...
    "causal_invalid_exact_b1_request", true, ...
    "whole_task_cases", 0, ...
    "formal_cases", 0);
if strlength(outputPath) > 0
    parent = fileparts(outputPath);
    if ~isfolder(parent), mkdir(parent); end
    writelines(jsonencode(result, PrettyPrint=true), outputPath, Encoding="UTF-8");
end
fprintf("%s\n", jsonencode(result));

    function powerW = fixedPower(phase, airspeed, payload)
        phaseDelta = 15.0 .* double(string(phase) == "ASCEND") ...
            + 8.0 .* double(string(phase) == "DESCEND");
        powerW = 1050.0 + 9.0 .* airspeed.^2 + 20.0 .* payload + phaseDelta;
    end
end


function maximum = comparisonError(actual, expected)
values = [ ...
    abs(actual.objective - expected.objective), ...
    max(abs(actual.constraints(:) - double(expected.constraints(:)))), ...
    max(abs(actual.risk_constraints_normalized(:) ...
        - double(expected.risk_constraints_normalized(:)))), ...
    abs(actual.risk_violation - expected.risk_violation), ...
    abs(actual.tracking_zone_violation - expected.tracking_zone_violation), ...
    abs(actual.predicted_energy_j - expected.predicted_energy_j), ...
    abs(actual.terminal_energy_to_go_j - expected.terminal_energy_to_go_j), ...
    abs(actual.terminal_progress_s - expected.terminal_progress_s), ...
    abs(actual.mean_trust - expected.mean_trust)];
rowFields = ["reference_position_m", "reference_velocity_mps", ...
    "reference_acceleration_mps2", "reference_jerk_mps3", ...
    "predicted_position_m", "predicted_velocity_mps", ...
    "predicted_acceleration_mps2", ...
    "predicted_common_robust_acceleration_i_mps2", "desired_force_n", ...
    "gp_mean_i_mps2", "calibrated_half_width_f_mps2", "trust", ...
    "support_distance", "latent_variance_max", "stage_energy_j", ...
    "outer_transition_fraction"];
for field = rowFields
    values(end + 1) = rowMaximum(actual.rows, expected.rows, field); %#ok<AGROW>
end
maximum = max(values);
end


function maximum = rowMaximum(actualRows, expectedRows, fieldName)
maximum = 0.0;
for index = 1:numel(actualRows)
    actual = double(actualRows(index).(fieldName));
    expected = double(expectedRows(index).(fieldName));
    maximum = max(maximum, max(abs(actual(:) - expected(:))));
end
end
