function result = runGpPredictionResponsibilityTests(projectRoot)
%RUNGPPREDICTIONRESPONSIBILITYTESTS Structural GP responsibility tests.

arguments
    projectRoot (1,1) string
end
addpath(genpath(fullfile(projectRoot, "matlab")));

tests = { ...
    @testGpDoesNotCreateASecondPhysicalCandidate, ...
    @testInnovationMismatchUsesContinuousWeightNotDiscreteFallback, ...
    @testConsistentInnovationKeepsB2Active, ...
    @testMissingEvidenceFailsClosed, ...
    @testReentryProbeRequiresClosedEvidence, ...
    @testClosedEvidenceUsesFrozenSampleFrame, ...
    @testNominalInnovationWithholdsFalseGpAxis, ...
    @testMatchedInnovationCausallyEarnsGpAxis, ...
    @testActiveB2PreservesSolverEvaluatedTarget, ...
    @testSharedRotorCommandFeatureDefinition};
names = [ ...
    "GP_MEAN_REMAINS_PREDICTIVE_WITHOUT_DIRECT_CANCELLATION_CANDIDATE", ...
    "INNOVATION_MISMATCH_USES_CONTINUOUS_WEIGHT_NOT_DISCRETE_FALLBACK", ...
    "ACTIVE_CONSISTENT_INNOVATION_RETAINS_B2", ...
    "MISSING_ACTIVE_EVIDENCE_FAILS_CLOSED", ...
    "REENTRY_PROBE_REQUIRES_CLOSED_EVIDENCE", ...
    "CLOSED_EVIDENCE_USES_ITS_FROZEN_SAMPLE_FRAME", ...
    "NOMINAL_INNOVATION_WITHHOLDS_FALSE_GP_AXIS", ...
    "MATCHED_INNOVATION_CAUSALLY_EARNS_GP_AXIS", ...
    "ACTIVE_B2_PRESERVES_SOLVER_EVALUATED_TARGET", ...
    "TRAINING_ONLINE_ROLLOUT_ROTOR_FEATURE_DEFINITION_SHARED"];
for index = 1:numel(tests)
    tests{index}();
end
result = struct( ...
    "schema", "GPENMPC_GP_PREDICTION_RESPONSIBILITY_TEST_V1", ...
    "status", "PASS", ...
    "test_count", numel(tests), ...
    "passed_count", numel(tests), ...
    "tests", names);
fprintf("%s\n", jsonencode(result));
end

function testGpDoesNotCreateASecondPhysicalCandidate()
config = coreConfig();
warm = [0.01, -0.02, 0.03, -0.04, 0.02, -0.03, 0.04];
means = repmat([0.20, -0.10, 0.05], 8, 1);
b2 = gpenmpcBuildEnmpcCandidateLibrary(config.method, warm, means, config);
b1 = gpenmpcBuildEnmpcCandidateLibrary( ...
    config.b1_fallback_method, warm, zeros(0, 3), config);
assert(isequal(b2.values, b1.values));
assert(isequal(b2.labels, b1.labels));
assert(~b2.gp_candidate_inserted);
assert(b2.gp_mean_remains_in_rollout);
assert(b2.gp_prediction_only);
end

function testInnovationMismatchUsesContinuousWeightNotDiscreteFallback()
config = supervisorConfig();
state = gpenmpcInitializeOuterSupervisor(config);
shadow = eligibleShadow();
shadow.observed_innovation_consistent = false;
request = gpenmpcOuterSupervisorRequest(state, true, config, shadow);
assert(request.requested_method == config.method);
evidence = closedEvidence([0.0;0.0;0.0], [0.1;0.1;0.1]);
evidence.observed_innovation_consistent = false;
[weight, ~] = gpenmpcUpdateGpAgreementWeight( ...
    ones(3,1), evidence, 0.01, config);
assert(weight(1) < 1.0);
assert(all(weight < 1.0));
assert(all(weight > 0.0));
end

function testConsistentInnovationKeepsB2Active()
config = supervisorConfig();
state = gpenmpcInitializeOuterSupervisor(config);
request = gpenmpcOuterSupervisorRequest( ...
    state, true, config, eligibleShadow());
assert(request.requested_method == config.method);
assert(request.request_reason == "B2_ACTIVE");
end

function testMissingEvidenceFailsClosed()
config = supervisorConfig();
state = gpenmpcInitializeOuterSupervisor(config);
request = gpenmpcOuterSupervisorRequest(state, true, config, struct);
assert(request.requested_method == config.b1_fallback_method);
assert(request.request_reason == ...
    "B2_ACTIVE_GP_EVIDENCE_UNAVAILABLE_DIRECT_B1");
end

function testReentryProbeRequiresClosedEvidence()
config = supervisorConfig();
state = gpenmpcInitializeOuterSupervisor(config);
state.mode = "B2_REENTRY_PROBE";
request = gpenmpcOuterSupervisorRequest(state, true, config, struct);
assert(request.requested_method == config.b1_fallback_method);
request = gpenmpcOuterSupervisorRequest( ...
    state, true, config, eligibleShadow());
assert(request.requested_method == config.method);
assert(request.request_reason == "B2_REENTRY_PROBE_WITH_CLOSED_GP_EVIDENCE");
end

function testClosedEvidenceUsesFrozenSampleFrame()
config = supervisorConfig();
frame = [0,-1,0;1,0,0;0,0,1];
meanF = [0.20,-0.10,0.05];
pending = eligibleShadow();
pending.gp_frame_i_from_f = frame;
pending.predicted_mean_f_mps2 = meanF;
pending.calibrated_half_width_f_mps2 = [0.01,0.01,0.01];
observedI = frame * meanF.';
closed = gpenmpcCloseGpInnovationEvidence( ...
    pending, observedI, true, config);
assert(max(abs(closed.observed_innovation_f_mps2 - meanF)) <= 1.0e-12);
assert(closed.observed_innovation_consistent);
assert(closed.eligible_for_b1_dwell);
end

function testNominalInnovationWithholdsFalseGpAxis()
config = supervisorConfig();
evidence = closedEvidence([0.0;0.0;0.0], [0.1;0.0;0.0]);
[weight, diagnostic] = gpenmpcUpdateGpAgreementWeight( ...
    zeros(3,1), evidence, 0.01, config);
assert(weight(1) > 0.0);
assert(weight(1) < weight(2));
assert(abs(weight(2) - weight(3)) <= 1.0e-15);
end

function testMatchedInnovationCausallyEarnsGpAxis()
config = supervisorConfig();
evidence = closedEvidence([0.1;0.0;0.0], [0.1;0.0;0.0]);
[weight, diagnostic] = gpenmpcUpdateGpAgreementWeight( ...
    zeros(3,1), evidence, 0.01, config);
expected = 1.0 - exp(-0.01 ./ 0.50);
assert(abs(weight(1) - expected) <= 1.0e-15);
assert(all(abs(weight(2:3) - expected) <= 1.0e-15));
assert(diagnostic.valid_closed_evidence);
end

function testActiveB2PreservesSolverEvaluatedTarget()
config = supervisorConfig();
state = gpenmpcInitializeOuterSupervisor(config);
request = gpenmpcOuterSupervisorRequest( ...
    state, true, config, eligibleShadow());
decision = decisionRecord(config.method, 0.08, [0.10;0;0]);
[~, applied] = gpenmpcOuterSupervisorStep( ...
    state, request, decision, struct, config, 1.0);
assert(abs(applied.phase_acceleration_s_inv - 0.08) <= 1.0e-12);
assert(norm(applied.outer_acceleration_correction_f_mps2 - [0.10;0;0]) ...
    <= 1.0e-12);
assert(applied.source == "B2_ACTIVE_DECISION");
end

function testSharedRotorCommandFeatureDefinition()
command = [10;11;12;13;14;15];
payload = 1.25;
expected = sum(command) ./ ((9.5 + payload) .* 9.80665);
actual = gpenmpcNormalizedTotalRotorCommand(command, payload);
assert(abs(actual - expected) <= 1.0e-15);
assert(gpenmpcNormalizedTotalRotorCommand(zeros(6,1), payload) == 0.0);
assert(gpenmpcNormalizedTotalRotorCommand(1e6 .* ones(6,1), payload) == 2.0);
end

function config = coreConfig()
config = supervisorConfig();
config.decision_dimension = 7;
config.control_blocks = 4;
config.horizon_steps = 8;
config.maximum_primary_candidates = 9;
config.shooting_constant_levels_s_inv = [0.04, 0.08];
    config.gp_candidate_profile = ...
        "GP_MEAN_PREDICTION_ONLY__SHARED_PHYSICAL_CANDIDATE_LIBRARY";
config.robust_tube_identity = "COMMON_TOTAL_ROBUST_TUBE";
end

function config = supervisorConfig()
config = struct( ...
    "method", "B2_ENMPC_GP_MEAN_TOTAL_TUBE", ...
    "b1_fallback_method", "B1_ENMPC_TOTAL_ROBUST_TUBE_NO_GP", ...
    "minimum_soft_trust", 0.25, ...
    "phase_acceleration_max_s_inv", 0.08, ...
    "outer_acceleration_correction_max_mps2", 0.10, ...
    "recovery_minimum_dwell_outer_ticks", 2, ...
    "reentry_success_persistence_outer_ticks", 2, ...
    "innovation_consistency_time_constant_s", 0.50, ...
    "innovation_consistency_enter_threshold", 0.50, ...
    "innovation_consistency_exit_threshold", 0.25, ...
    "innovation_consistency_exit_dwell_outer_ticks", 2, ...
    "outer_period_s", 0.30, ...
    "raw", struct("bumpless_recovery", struct( ...
        "target_recovery_rate", 1.0)));
end

function shadow = eligibleShadow()
shadow = struct( ...
    "available", true, ...
    "causal_valid", true, ...
    "observed_innovation_available", true, ...
    "gp_model_available", true, ...
    "hard_invalid", false, ...
    "trust", 0.8, ...
    "consistency_ewma_f", [0.8,0.8,0.8], ...
    "consistency_ewma_aggregate", 0.8, ...
    "observed_innovation_consistent", true);
end

function evidence = closedEvidence(observedF, predictedF)
evidence = eligibleShadow();
evidence.prediction_sample_closed = true;
evidence.observed_innovation_f_mps2 = observedF(:).';
evidence.predicted_mean_f_mps2 = predictedF(:).';
evidence.calibrated_half_width_f_mps2 = 0.1 .* ones(1,3);
end

function decision = decisionRecord(method, phase, correction)
decision = struct( ...
    "method", method, ...
    "success", true, ...
    "hard_invalid", false, ...
    "gp_b1_fallback_active", false, ...
    "fallback_reason", "", ...
    "phase_acceleration_s_inv", phase, ...
    "outer_acceleration_correction_f_mps2", correction, ...
    "mean_trust", 0.8, ...
    "elapsed_seconds", 0.01, ...
    "minimum_constraint_margin", 0.1);
end
