function result = runNativeSparseGpTrainingParity(nativeModelPath, ...
        nativeDataPath, parentModelPath, parentTrainingDataPath, ...
        parentInferenceParityPath, outputPath)
%RUNNATIVESPARSEGPtrainingPARITY Compare sparse-GP parameters and predictions.
%
% Compare candidate and reference model parameters, calibration predictions
% and a 96-sample online-prediction fixture.

arguments
    nativeModelPath (1,1) string
    nativeDataPath (1,1) string
    parentModelPath (1,1) string
    parentTrainingDataPath (1,1) string
    parentInferenceParityPath (1,1) string
    outputPath (1,1) string
end

paths = [nativeModelPath, nativeDataPath, parentModelPath, ...
    parentTrainingDataPath, parentInferenceParityPath];
for index = 1:numel(paths)
    if ~isfile(paths(index))
        error("runNativeSparseGpTrainingParity:Input", ...
            "Required read-only input is missing: %s", paths(index));
    end
end
if isfile(outputPath)
    error("runNativeSparseGpTrainingParity:AppendOnly", ...
        "Refusing to overwrite %s", outputPath);
end

candidate = load(nativeModelPath, "nativeModel", "result");
nativeData = load(nativeDataPath, "X_calibration");
parent = load(parentModelPath, "nativeModel", "result");
parentData = load(parentTrainingDataPath, ...
    "python_mean_calibration", "python_raw_std_calibration", ...
    "python_calibrated_half_width_calibration", ...
    "python_support_distance_calibration");
frozen = load(parentInferenceParityPath);

candidateCalibration = gpenmpcSparseGpPredict(...
    candidate.nativeModel, nativeData.X_calibration);
candidateOnline = gpenmpcSparseGpPredict(...
    candidate.nativeModel, frozen.parity_inputs);

parentInferenceModel = parent.nativeModel;
inferenceFields = [
    "kernel_name", "calibration_score_quantile", ...
    "distance_soft_q95", "distance_hard_q995", ...
    "latent_soft_q95", "latent_hard_q995"
];
for index = 1:numel(inferenceFields)
    parentInferenceModel.(inferenceFields(index)) = frozen.(inferenceFields(index));
end
parentOnline = gpenmpcSparseGpPredict(parentInferenceModel, frozen.parity_inputs);

modelErrors = struct;
modelErrors.input_mean = maxAbs(candidate.nativeModel.input_mean, parent.nativeModel.input_mean);
modelErrors.input_scale = maxAbs(candidate.nativeModel.input_scale, parent.nativeModel.input_scale);
modelErrors.output_mean = maxAbs(candidate.nativeModel.output_mean, parent.nativeModel.output_mean);
modelErrors.output_scale = maxAbs(candidate.nativeModel.output_scale, parent.nativeModel.output_scale);
modelErrors.inducing_standardized = maxAbs(candidate.nativeModel.inducing_standardized, ...
    parent.nativeModel.inducing_standardized);
modelErrors.lengthscale = maxAbs(candidate.nativeModel.lengthscale, parent.nativeModel.lengthscale);
modelErrors.signal_std = maxAbs(candidate.nativeModel.signal_std, parent.nativeModel.signal_std);
modelErrors.noise_std_standardized = maxAbs(...
    candidate.nativeModel.noise_std_standardized, ...
    parent.nativeModel.noise_std_standardized);
modelErrors.calibration_score_quantile = maxAbs(...
    candidate.nativeModel.calibration_score_quantile, ...
    parent.result.calibration_score_quantile);
modelErrors.ood_thresholds_vs_frozen_parent = max([
    abs(candidate.nativeModel.distance_soft_q95 - frozen.distance_soft_q95), ...
    abs(candidate.nativeModel.distance_hard_q995 - frozen.distance_hard_q995), ...
    abs(candidate.nativeModel.latent_soft_q95 - frozen.latent_soft_q95), ...
    abs(candidate.nativeModel.latent_hard_q995 - frozen.latent_hard_q995)
]);
modelErrors.kmm_cholesky = maxAbs(candidate.nativeModel.kmm_cholesky, ...
    parent.nativeModel.kmm_cholesky);
modelErrors.posterior_mean_white = maxAbs(...
    candidate.nativeModel.posterior_mean_white, ...
    parent.nativeModel.posterior_mean_white);
modelErrors.posterior_cov_white_axis1 = maxAbs(...
    candidate.nativeModel.posterior_cov_white_axis1, ...
    parent.nativeModel.posterior_cov_white_axis1);
modelErrors.posterior_cov_white_axis2 = maxAbs(...
    candidate.nativeModel.posterior_cov_white_axis2, ...
    parent.nativeModel.posterior_cov_white_axis2);
modelErrors.posterior_cov_white_axis3 = maxAbs(...
    candidate.nativeModel.posterior_cov_white_axis3, ...
    parent.nativeModel.posterior_cov_white_axis3);
modelErrors.selected_loss_per_sample_axis = abs(...
    candidate.result.selected_loss_per_sample_axis ...
    - parent.result.selected_loss_per_sample_axis);

calibrationErrors = struct;
calibrationErrors.mean_absolute_mps2 = maxAbs(...
    candidateCalibration.mean_mps2, parentData.python_mean_calibration);
calibrationErrors.raw_std_absolute_mps2 = maxAbs(...
    candidateCalibration.raw_std_mps2, parentData.python_raw_std_calibration);
calibrationErrors.half_width_absolute_mps2 = maxAbs(...
    candidateCalibration.calibrated_half_width_mps2, ...
    parentData.python_calibrated_half_width_calibration);
calibrationErrors.support_distance_absolute = maxAbs(...
    candidateCalibration.support_distance, ...
    parentData.python_support_distance_calibration(:));

onlineErrors = predictionErrors(candidateOnline, frozen);
parentOnlineErrors = predictionErrors(parentOnline, frozen);

tolerances = struct;
tolerances.normalization_absolute = 1.0e-12;
tolerances.inducing_absolute = 1.0e-10;
tolerances.hyperparameter_and_threshold_absolute = 1.0e-8;
tolerances.posterior_factor_absolute = 1.0e-7;
tolerances.prediction_absolute = 1.0e-9;
tolerances.latent_variance_absolute = 1.0e-8;
tolerances.selected_loss_absolute = 1.0e-9;

normalizationMaximum = max([
    modelErrors.input_mean, modelErrors.input_scale, ...
    modelErrors.output_mean, modelErrors.output_scale
]);
hyperparameterMaximum = max([
    modelErrors.lengthscale, modelErrors.signal_std, ...
    modelErrors.noise_std_standardized, ...
    modelErrors.calibration_score_quantile, ...
    modelErrors.ood_thresholds_vs_frozen_parent
]);
posteriorFactorMaximum = max([
    modelErrors.kmm_cholesky, modelErrors.posterior_mean_white, ...
    modelErrors.posterior_cov_white_axis1, ...
    modelErrors.posterior_cov_white_axis2, ...
    modelErrors.posterior_cov_white_axis3
]);

checks = struct;
checks.method_identity = candidate.result.training_rows == 4680 ...
    && candidate.result.calibration_rows == 2340 ...
    && candidate.result.input_dimension == 17 ...
    && candidate.result.output_dimension == 3 ...
    && candidate.result.inducing_count == 256 ...
    && candidate.result.optimization_steps == 48 ...
    && candidate.result.restarts == 2 ...
    && strcmp(candidate.result.objective, "COLLAPSED_VARIATIONAL_FREE_ENERGY") ...
    && strcmp(candidate.result.optimizer, "MATLAB_AUTOMATIC_DIFFERENTIATION_WITH_ADAM") ...
    && candidate.result.fitrgp_substituted == false;
checks.two_complete_restarts = all(...
    [candidate.result.restart_records.steps_completed] == 48) ...
    && all([candidate.result.restart_records.finite]);
checks.native_inputs_only = ...
    candidate.result.inducing_standardized_python_consumed == false ...
    && candidate.result.predecessor_model_or_predictions_consumed_during_training == false ...
    && candidate.result.python_or_pytorch_runtime_used == false ...
    && strcmp(candidate.result.inducing_variable, "inducing_standardized_matlab");
checks.normalization = normalizationMaximum <= tolerances.normalization_absolute;
checks.inducing = modelErrors.inducing_standardized <= tolerances.inducing_absolute;
checks.hyperparameters_and_thresholds = hyperparameterMaximum ...
    <= tolerances.hyperparameter_and_threshold_absolute;
checks.posterior_factors = posteriorFactorMaximum ...
    <= tolerances.posterior_factor_absolute;
checks.selected_loss = modelErrors.selected_loss_per_sample_axis ...
    <= tolerances.selected_loss_absolute;
checks.calibration_predictions = max(structfun(@double, calibrationErrors)) ...
    <= tolerances.prediction_absolute;
checks.online_predictions = onlineErrors.mean_absolute_mps2 <= tolerances.prediction_absolute ...
    && onlineErrors.raw_std_absolute_mps2 <= tolerances.prediction_absolute ...
    && onlineErrors.half_width_absolute_mps2 <= tolerances.prediction_absolute ...
    && onlineErrors.variance_absolute_mps4 <= tolerances.latent_variance_absolute ...
    && onlineErrors.support_distance_absolute <= tolerances.prediction_absolute ...
    && onlineErrors.trust_absolute <= tolerances.prediction_absolute ...
    && onlineErrors.control_contribution_absolute_mps2 <= tolerances.prediction_absolute ...
    && onlineErrors.hard_invalid_mismatch == 0;

result = struct;
result.schema = "GPENMPC_MATLAB_NATIVE_GP_PARENT_PARITY_RESULT_V1";
if all(structfun(@logical, checks))
    result.status = "PASS_NATIVE_TRAINING_AND_PARENT_PREDICTION_PARITY";
else
    result.status = "FAIL_NATIVE_TRAINING_OR_PARENT_PREDICTION_PARITY";
end
result.model_errors = modelErrors;
result.model_error_maxima = struct(...
    normalization=normalizationMaximum, ...
    hyperparameters_and_thresholds=hyperparameterMaximum, ...
    posterior_factors=posteriorFactorMaximum);
result.calibration_prediction_errors = calibrationErrors;
result.online_prediction_errors = onlineErrors;
result.parent_native_online_prediction_errors = parentOnlineErrors;
result.tolerances = tolerances;
result.checks = checks;
result.sample_count = size(frozen.parity_inputs, 1);
result.calibration_rows = size(nativeData.X_calibration, 1);
result.parent_root_mutated = false;
result.python_or_pytorch_runtime_used = false;
result.simulation_cases_run = 0;

folder = fileparts(outputPath);
if ~isfolder(folder)
    mkdir(folder);
end
fileId = fopen(outputPath, "w", "n", "UTF-8");
if fileId < 0
    error("runNativeSparseGpTrainingParity:Output", ...
        "Cannot create %s", outputPath);
end
cleanup = onCleanup(@() fclose(fileId));
fwrite(fileId, jsonencode(result, PrettyPrint=true), "char");
clear cleanup

if result.status ~= "PASS_NATIVE_TRAINING_AND_PARENT_PREDICTION_PARITY"
    error("runNativeSparseGpTrainingParity:Mismatch", ...
        "Native GP training or parent prediction parity failed.");
end
fprintf("NATIVE_GP_PARENT_PARITY_PASS mean=%.3g variance=%.3g model=%.3g\n", ...
    onlineErrors.mean_absolute_mps2, onlineErrors.variance_absolute_mps4, ...
    posteriorFactorMaximum);
end


function errors = predictionErrors(prediction, frozen)
errors = struct;
errors.mean_absolute_mps2 = maxAbs(...
    prediction.mean_mps2, frozen.python_mean_mps2);
errors.raw_std_absolute_mps2 = maxAbs(...
    prediction.raw_std_mps2, frozen.python_raw_std_mps2);
errors.half_width_absolute_mps2 = maxAbs(...
    prediction.calibrated_half_width_mps2, ...
    frozen.python_calibrated_half_width_mps2);
errors.variance_absolute_mps4 = maxAbs(...
    prediction.latent_variance_standardized, ...
    frozen.python_latent_variance_standardized);
errors.support_distance_absolute = maxAbs(...
    prediction.support_distance, frozen.python_support_distance(:));
errors.trust_absolute = maxAbs(prediction.trust, frozen.python_trust(:));
errors.control_contribution_absolute_mps2 = maxAbs(...
    prediction.applied_mean_f_mps2, frozen.python_applied_mean_f_mps2);
errors.hard_invalid_mismatch = nnz(...
    prediction.hard_invalid ~= logical(frozen.python_hard_invalid(:)));
end


function value = maxAbs(left, right)
if ~isequal(size(left), size(right))
    error("runNativeSparseGpTrainingParity:Shape", ...
        "Cannot compare arrays with different shapes.");
end
value = max(abs(double(left) - double(right)), [], "all");
end
