function result = runResponsibilityAlignmentTests()
%RUNRESPONSIBILITYALIGNMENTTESTS Test causal GP responsibility and bumpless transitions.

tests = { ...
    @testLowResidualStaysExactB1, ...
    @testHighResidualEntersAfterDwell, ...
    @testHysteresisPreventsChatter, ...
    @testCrossFadeIsComplementaryAndBounded, ...
    @testHardInvalidImmediatelyReturnsB1, ...
    @testGpMeanFilterIsCausalAndBandwidthLimited, ...
    @testConfigurationAndEnergyScaleAreFrozen, ...
    @testPredictorRespectsRuntimeResponsibility, ...
    @testObjectiveAuditFieldsAreImplemented, ...
    @testClosedResponsibilityRoutesCompleteOuterLayerToB1};
names = [ ...
    "LOW_RESIDUAL_EXACT_B1", ...
    "HIGH_RESIDUAL_DWELL_ENTRY", ...
    "HYSTERESIS_NO_CHATTER", ...
    "COMPLEMENTARY_BUMPLESS_CROSS_FADE", ...
    "HARD_INVALID_IMMEDIATE_B1", ...
    "CAUSAL_GP_BANDWIDTH_LIMIT", ...
    "FROZEN_RESPONSIBILITY_AND_ENERGY_SCALE", ...
    "PREDICTOR_RUNTIME_RESPONSIBILITY", ...
    "OBJECTIVE_AND_RANK_AUDIT_SCHEMA", ...
    "CLOSED_RESPONSIBILITY_EXACT_B1_OUTER_ROUTE"];
for index = 1:numel(tests)
    tests{index}();
end
result = struct( ...
    "schema", "GPENMPC_RESPONSIBILITY_ALIGNMENT_TEST_RESULT_V1", ...
    "status", "PASS", ...
    "test_count", numel(tests), ...
    "passed_count", numel(tests), ...
    "tests", names);
disp(jsonencode(result));
end


function testLowResidualStaysExactB1()
[x, reference, robust, config, candidateState] = fixture();
baselineState = candidateState;
sample = evidence([0.08;-0.04;0.12], [0.001;0.001;0.001], false);
for index = 1:200
    [expected, baselineState] = gpenmpcRobustSe3Augmentation( ...
        x, reference, robust, baselineState, 0.01);
    [actual, candidateState, diagnostic] = ...
        gpenmpcCoordinatedGpRobustSe3Augmentation( ...
        x, reference, robust, candidateState, 0.01, sample, ones(3,1), config);
    assert(max(abs(actual - expected)) <= 1.0e-12);
    assert(diagnostic.gp_responsibility_blend == 0.0);
    assert(diagnostic.gp_authority == 0.0);
end
assert(~candidateState.gp_responsibility_mode_active);
end


function testHighResidualEntersAfterDwell()
[x, reference, robust, config, state] = fixture();
state.vertical_disturbance_ewma_mps2 = 0.20;
sample = evidence([0.12;-0.07;0.20], [0.10;0.08;0.25], false);
for index = 1:80
    [~, state, diagnostic] = gpenmpcCoordinatedGpRobustSe3Augmentation( ...
        x, reference, robust, state, 0.01, sample, ones(3,1), config);
end
assert(state.gp_responsibility_mode_active);
assert(abs(state.gp_responsibility_blend - 1.0) <= 1.0e-12);
assert(diagnostic.gp_authority > 0.0);
assert(isequal(diagnostic.vertical_observer_compensation_i_mps2, zeros(3,1)));
assert(abs(diagnostic.vertical_observer_shadow_i_mps2(3) + 0.20) <= 1.0e-12);
end


function testHysteresisPreventsChatter()
[x, reference, robust, config, state] = fixture();
high = evidence([0.12;-0.07;0.20], [0.10;0.08;0.25], false);
for index = 1:80
    [~, state] = gpenmpcCoordinatedGpRobustSe3Augmentation( ...
        x, reference, robust, state, 0.01, high, ones(3,1), config);
end
transitionCount = state.gp_responsibility_mode_transition_count;
middleInnovation = config.responsibility_residual_floor_f_mps2(:) .* 0.95;
middle = evidence([0.12;-0.07;0.20], middleInnovation, false);
for index = 1:120
    [~, state] = gpenmpcCoordinatedGpRobustSe3Augmentation( ...
        x, reference, robust, state, 0.01, middle, ones(3,1), config);
end
assert(state.gp_responsibility_mode_active);
assert(state.gp_responsibility_mode_transition_count == transitionCount);
end


function testCrossFadeIsComplementaryAndBounded()
[x, reference, robust, config, state] = fixture();
state.vertical_disturbance_ewma_mps2 = 0.20;
high = evidence([0.12;-0.07;0.20], [0.10;0.08;0.25], false);
previous = state.filtered_compensation_i_mps2;
foundTransition = false;
for index = 1:60
    [actual, state, diagnostic] = gpenmpcCoordinatedGpRobustSe3Augmentation( ...
        x, reference, robust, state, 0.01, high, ones(3,1), config);
    assert(norm(actual - previous) ...
        <= robust.compensation_slew_limit_mps3 .* 0.01 + 1.0e-12);
    previous = actual;
    blend = diagnostic.gp_responsibility_blend;
    if blend > 0.0 && blend < 1.0
        foundTransition = true;
        expectedObserver = (1.0 - blend) ...
            .* diagnostic.vertical_observer_shadow_i_mps2;
        assert(max(abs(diagnostic.vertical_observer_compensation_i_mps2 ...
            - expectedObserver)) <= 1.0e-12);
    end
end
assert(foundTransition);
end


function testHardInvalidImmediatelyReturnsB1()
[x, reference, robust, config, state] = fixture();
high = evidence([0.12;-0.07;0.20], [0.10;0.08;0.25], false);
for index = 1:80
    [~, state] = gpenmpcCoordinatedGpRobustSe3Augmentation( ...
        x, reference, robust, state, 0.01, high, ones(3,1), config);
end
invalid = high;
invalid.hard_invalid = true;
expectedState = state;
[expected, expectedState] = gpenmpcRobustSe3Augmentation( ...
    x, reference, robust, expectedState, 0.01);
[actual, actualState, diagnostic] = ...
    gpenmpcCoordinatedGpRobustSe3Augmentation( ...
    x, reference, robust, state, 0.01, invalid, ones(3,1), config);
assert(max(abs(actual - expected)) <= 1.0e-12);
assert(max(abs(actualState.filtered_compensation_i_mps2 ...
    - expectedState.filtered_compensation_i_mps2)) <= 1.0e-12);
assert(diagnostic.exact_b1_fallback);
assert(actualState.gp_responsibility_blend == 0.0);
end


function testGpMeanFilterIsCausalAndBandwidthLimited()
[x, reference, robust, config, state] = fixture();
high = evidence([0.30;-0.20;0.25], [0.10;0.08;0.25], false);
entered = false;
for index = 1:100
    [~, state, diagnostic] = gpenmpcCoordinatedGpRobustSe3Augmentation( ...
        x, reference, robust, state, 0.01, high, ones(3,1), config);
    if diagnostic.gp_responsibility_blend > 0.0
        entered = true;
        break
    end
end
assert(entered);
assert(norm(diagnostic.gp_filtered_control_target_i_mps2) ...
    < norm(diagnostic.gp_raw_control_target_i_mps2));
end


function testConfigurationAndEnergyScaleAreFrozen()
root = fileparts(fileparts(mfilename("fullpath")));
runtime = fullfile(root, "matlab", "simulink", "assets", ...
    "enmpc_runtime_configuration.json");
config = gpenmpcLoadOrdinaryB2Config(runtime, 0.30);
config = gpenmpcApplyResponsibilityConfiguration(config);
assert(config.gp_responsibility_gate_enabled);
assert(abs(config.energy_scale_j - 500.0) <= 1.0e-12);
assert(abs(config.responsibility_gp_mean_filter_time_constant_s - 0.12) <= 1.0e-12);
assert(max(abs(config.responsibility_residual_floor_f_mps2 ...
    - [0.03219254730192427, 0.029209190368417185, ...
    0.037378411972285294])) <= 1.0e-12);
end


function testPredictorRespectsRuntimeResponsibility()
root = fileparts(fileparts(mfilename("fullpath")));
fixtureData = jsondecode(fileread(fullfile(root, "tests", "fixtures", ...
    "ordinary_b2_rollout_python_reference.json")));
stored = load(fullfile(root, "matlab", "native_training", ...
    "raw", "MATLAB_NATIVE_SPARSE_GP_MODEL.mat"), "nativeModel");
config = gpenmpcLoadOrdinaryB2Config(string(fixtureData.runtime_config_path));
config = gpenmpcApplyResponsibilityConfiguration(config);
trajectory = struct( ...
    "total_duration_s", double(fixtureData.trajectory.total_duration_s), ...
    "coefficients_ascending", ...
        double(fixtureData.trajectory.coefficients_ascending));
context = fixtureData.context;
context.phase_power_fcn = @fixedPower;
calibration = jsondecode(fileread(fullfile(root, "matlab", "simulink", ...
    "assets", "M600_DYN_CALIBRATION.json")));
allocation = gpenmpcM600Allocation(calibration);
context.rotor_allocation_pseudoinverse = allocation.pseudoinverse;
context.inertia_kg_m2 = allocation.inertia_kg_m2;
context.attitude_moment_gain_nm_per_rad = ...
    double(calibration.controller.attitude_moment_gain_nm_per_rad(:));
context.body_rate_moment_gain_nm_s_per_rad = ...
    double(calibration.controller.body_rate_moment_gain_nm_s_per_rad(:));
observation = fixtureData.observation;
observation.previous_rotor_command_n = repmat( ...
    norm(observation.previous_desired_force_n) ./ 6.0, 6, 1);
causal = fixtureData.causal_context_f17;
causal.runtime_gp_responsibility_blend = 0.0;
causal.runtime_gp_filtered_mean_f_mps2 = zeros(3,1);
rollout = gpenmpcEvaluateOrdinaryB2Rollout( ...
    double(fixtureData.decision(:).'), config.method, trajectory, ...
    fixtureData.phase_state, observation, context, stored.nativeModel, ...
    causal, config);
plant = vertcat(rollout.rows.predicted_gp_plant_residual_i_mps2);
control = vertcat(rollout.rows.predicted_gp_control_target_i_mps2);
assert(max(abs(plant), [], "all") <= 1.0e-12);
assert(max(abs(control), [], "all") <= 1.0e-12);
end


function testObjectiveAuditFieldsAreImplemented()
root = fileparts(fileparts(mfilename("fullpath")));
solver = fileread(fullfile(root, "matlab", "enmpc", ...
    "gpenmpcSolveOrdinaryB2FiniteShooting.m"));
runner = fileread(fullfile(root, "matlab", "comparison", ...
    "gpenmpcRunNativeEnmpcWholeTask.m"));
assert(contains(solver, "candidate_objective_vector"));
assert(contains(solver, "energy_term_changed_selected_candidate"));
assert(contains(runner, "selected_objective_vector"));
assert(contains(runner, "candidate_predicted_energy_spread_j"));
end


function testClosedResponsibilityRoutesCompleteOuterLayerToB1()
root = fileparts(fileparts(mfilename("fullpath")));
runner = fileread(fullfile(root, "matlab", "comparison", ...
    "gpenmpcRunNativeEnmpcWholeTask.m"));
assert(contains(runner, "RESPONSIBILITY_GATE_EXACT_B1"));
assert(contains(runner, "responsibilityBlend <= 1.0e-12"));
branchStart = strfind(runner, "if responsibilityGateEnabled");
b1Call = strfind(runner, "gpenmpcNativeB1OuterStep");
assert(~isempty(branchStart));
assert(any(b1Call > branchStart(1)));
end


function [x, reference, robust, config, state] = fixture()
x = zeros(19,1);
x(1:3) = [0.12;-0.08;0.04];
x(4:6) = [2.1;0.4;-0.1];
x(7) = 1.0;
reference = struct("position_m", zeros(3,1), ...
    "velocity_mps", [2.0;0.5;0.0]);
robust = struct( ...
    "lambda_position_s_inv", [0.7;0.7;0.8], ...
    "robust_radius_f_mps2", [0.125;0.103;0.396], ...
    "residual_tail_margin_f_mps2", [0.072;0.060;0.072], ...
    "projection_margin_f_mps2", [0.02;0.02;0.02], ...
    "robust_boundary_layer_mps", [0.2;0.2;0.2], ...
    "combined_compensation_cap_mps2", 0.75, ...
    "gp_compensation_cap_mps2", 0.4, ...
    "compensation_slew_limit_mps3", 3.0, ...
    "trust_filter_time_constant_s", 0.2);
config = struct( ...
    "minimum_soft_trust", 0.25, ...
    "gp_mean_scale", 1.0, ...
    "post_gp_residual_radius_f_mps2", [0.096;0.099;0.215], ...
    "coordinated_gp_alpha_zero_tolerance", 1.0e-12, ...
    "gp_responsibility_gate_enabled", true, ...
    "responsibility_residual_floor_f_mps2", ...
        [0.03219254730192427, 0.029209190368417185, ...
        0.037378411972285294], ...
    "responsibility_innovation_ewma_time_constant_s", 0.30, ...
    "gp_responsibility_enter_ratio", 1.25, ...
    "gp_responsibility_exit_ratio", 0.75, ...
    "gp_responsibility_enter_dwell_s", 0.30, ...
    "gp_responsibility_exit_dwell_s", 0.60, ...
    "responsibility_cross_fade_duration_s", 0.20, ...
    "responsibility_gp_mean_filter_time_constant_s", 0.12);
state = gpenmpcInitializeRobustSe3State();
end


function value = evidence(meanF, observedF, hardInvalid)
value = struct( ...
    "available", true, ...
    "prediction_sample_closed", true, ...
    "observed_innovation_available", true, ...
    "hard_invalid", logical(hardInvalid), ...
    "trust", 0.9, ...
    "predicted_mean_f_mps2", double(meanF(:).'), ...
    "observed_innovation_f_mps2", double(observedF(:).'), ...
    "calibrated_half_width_f_mps2", [0.05,0.05,0.10], ...
    "gp_frame_i_from_f", eye(3));
end


function value = fixedPower(phase, airspeed, payload)
phaseDelta = 15.0 .* double(string(phase) == "ASCEND") ...
    + 8.0 .* double(string(phase) == "DESCEND");
value = 1050.0 + 9.0 .* airspeed.^2 + 20.0 .* payload + phaseDelta;
end
