function result = runSupervisorContinuityTests(projectRoot, outputPath)
%RUNSUPERVISORCONTINUITYTESTS Test causal supervisor continuity and hysteresis.

arguments
    projectRoot (1,1) string
    outputPath (1,1) string = ""
end
addpath(genpath(fullfile(projectRoot, "matlab")));
config = localConfig();

% A one-axis transient exceedance reduces only the corresponding filtered
% weight and cannot reset all three axes instantaneously.
evidence = baseEvidence();
evidence.observed_innovation_f_mps2 = [0.21, 0.10, -0.10];
evidence.predicted_mean_f_mps2 = [0.10, 0.10, -0.10];
evidence.calibrated_half_width_f_mps2 = [0.10, 0.10, 0.10];
[weight, diagnostic] = gpenmpcUpdateGpAgreementWeight( ...
    0.8 .* ones(3,1), evidence, 0.01, config);
assert(weight(1) < weight(2));
assert(weight(2) > 0.8);
assert(all(weight > 0.0));

% Actual dt, rather than an assumed sample rate, sets the EWMA update.
[weightA, ~] = gpenmpcUpdateGpAgreementWeight( ...
    zeros(3,1), matchedEvidence(), 0.01, config);
[weightB, ~] = gpenmpcUpdateGpAgreementWeight( ...
    zeros(3,1), matchedEvidence(), 0.02, config);
assert(all(weightB > weightA));

% Hysteresis: an aggregate score above the exit threshold remains B2 even
% though it is below the stricter re-entry threshold.
state = gpenmpcInitializeOuterSupervisor(config);
mid = shadowWithScore(0.35);
request = gpenmpcOuterSupervisorRequest(state, true, config, mid);
assert(request.requested_method == config.method);

% Two persistent low-score outer updates cause a future B1 request, while a
% single low update does not.
low = shadowWithScore(0.10);
request = gpenmpcOuterSupervisorRequest(state, true, config, low);
[state, ~] = gpenmpcOuterSupervisorStep(state, request, ...
    goodDecision(config.method), struct("shadow_gp", low), config, 1.0);
assert(state.mode == "B2_ACTIVE");
request = gpenmpcOuterSupervisorRequest(state, true, config, low);
[state, ~, event] = gpenmpcOuterSupervisorStep(state, request, ...
    goodDecision(config.method), struct("shadow_gp", low), config, 1.0);
assert(state.mode == "B1_ONLY");
assert(event.transition_reason == "B2_CONSISTENCY_EXIT_DWELL_COMPLETE");

% Inactive diagnostic NaNs are valid placeholders; an active NaN is not.
trace = struct;
trace.position_m = zeros(2,3);
trace.gp_evidence_available = [false; true];
trace.gp_observed_innovation_available = [false; true];
trace.gp_consistency_evidence_active = [false; true];
trace.gp_predicted_mean_f_mps2 = [nan(1,3); zeros(1,3)];
trace.gp_calibrated_half_width_f_mps2 = [nan(1,3); ones(1,3)];
trace.gp_support_distance = [nan; 0.1];
trace.gp_latent_variance_max = [nan; 0.1];
trace.gp_observed_innovation_f_mps2 = [nan(1,3); zeros(1,3)];
trace.gp_innovation_error_f_mps2 = [nan(1,3); zeros(1,3)];
trace.gp_normalized_innovation_error_f = [nan(1,3); zeros(1,3)];
trace.gp_consistency_score_instant_f = [nan(1,3); ones(1,3)];
assert(gpenmpcAllFiniteActiveTrace(trace));
trace.gp_predicted_mean_f_mps2(2,1) = NaN;
assert(~gpenmpcAllFiniteActiveTrace(trace));

% A sub-threshold economic improvement cannot displace an otherwise
% equivalent feasible warm candidate; a primary risk improvement can.
config.decision_dimension = 2;
config.feasibility_tolerance = 1.0e-7;
config.candidate_commit_hysteresis_fraction = 0.005;
config.candidate_primary_equivalence_tolerance = 1.0e-12;
candidates = [0, 0; 0.1, 0];
evaluations = [selectionEvaluation(100.0, 0.0, 0.0); ...
    selectionEvaluation(99.6, 0.0, 0.0)];
selection = gpenmpcSelectEnmpcCandidate(candidates, evaluations, config);
assert(selection.index == 1);
assert(selection.raw_selected_index == 2);
assert(selection.profile_switch_suppressed);
evaluations(2) = selectionEvaluation(100.0, -0.1, 0.0);
selection = gpenmpcSelectEnmpcCandidate(candidates, evaluations, config);
assert(selection.index == 2);
assert(~selection.profile_switch_suppressed);

result = struct( ...
    "schema", "GPENMPC_SUPERVISOR_CONTINUITY_TEST_V1", ...
    "status", "PASS", ...
    "test_count", 7, ...
    "passed_count", 7);
if strlength(outputPath) > 0
    parent = fileparts(outputPath);
    if ~isfolder(parent), mkdir(parent); end
    writelines(jsonencode(result, PrettyPrint=true), outputPath, ...
        Encoding="UTF-8");
end
fprintf("%s\n", jsonencode(result));
end


function value = selectionEvaluation(objective, risk, tracking)
value = struct("objective", objective, "constraints", ones(2,1), ...
    "hard_invalid", false, "risk_violation", risk, ...
    "tracking_zone_violation", tracking);
end


function config = localConfig()
config = struct( ...
    "method", "B2_ENMPC_GP_MEAN_TOTAL_TUBE", ...
    "b1_fallback_method", "B1_ENMPC_TOTAL_ROBUST_TUBE_NO_GP", ...
    "minimum_soft_trust", 0.25, ...
    "phase_acceleration_max_s_inv", 0.08, ...
    "outer_acceleration_correction_max_mps2", 0.10, ...
    "recovery_minimum_dwell_outer_ticks", 2, ...
    "reentry_success_persistence_outer_ticks", 2, ...
    "innovation_consistency_time_constant_s", 0.50, ...
    "innovation_consistency_enter_threshold", 0.50, ...
    "innovation_consistency_exit_threshold", 0.25, ...
    "innovation_consistency_exit_dwell_outer_ticks", 2, ...
    "outer_period_s", 0.30, ...
    "reference_transition_jerk_limit_mps3", 2.0, ...
    "raw", struct("bumpless_recovery", struct( ...
        "target_recovery_rate", 1.0)));
end


function evidence = baseEvidence()
evidence = struct( ...
    "available", true, ...
    "prediction_sample_closed", true, ...
    "observed_innovation_available", true, ...
    "hard_invalid", false, ...
    "trust", 0.8, ...
    "observed_innovation_consistent", true);
end


function evidence = matchedEvidence()
evidence = baseEvidence();
evidence.observed_innovation_f_mps2 = [0.10, 0.0, -0.10];
evidence.predicted_mean_f_mps2 = [0.10, 0.0, -0.10];
evidence.calibrated_half_width_f_mps2 = 0.10 .* ones(1,3);
end


function shadow = shadowWithScore(score)
shadow = struct( ...
    "available", true, ...
    "causal_valid", true, ...
    "observed_innovation_available", true, ...
    "gp_model_available", true, ...
    "hard_invalid", false, ...
    "trust", 0.8, ...
    "observed_innovation_consistent", score >= 0.5, ...
    "consistency_ewma_f", score .* ones(1,3), ...
    "consistency_ewma_aggregate", score);
end


function decision = goodDecision(method)
decision = struct( ...
    "method", method, ...
    "success", true, ...
    "hard_invalid", false, ...
    "gp_b1_fallback_active", false, ...
    "fallback_reason", "", ...
    "phase_acceleration_s_inv", 0.0, ...
    "outer_acceleration_correction_f_mps2", zeros(1,3), ...
    "mean_trust", 0.8, ...
    "elapsed_seconds", 0.01, ...
    "minimum_constraint_margin", 0.1);
end
