function result = runShadowReentryTestSuite(stagingRoot, authorityRoot)
%RUNSHADOWREENTRYTESTSUITE Run the shadow-prediction and re-entry unit tests.
arguments
    stagingRoot (1,1) string
    authorityRoot (1,1) string
end
originalPath = path;
cleanup = onCleanup(@() path(originalPath));
addpath(genpath(authorityRoot), "-end");
addpath(fullfile(stagingRoot, "tests"), "-begin");
addpath(fullfile(stagingRoot, "matlab", "enmpc"), "-begin");
addpath(fullfile(stagingRoot, "matlab", "comparison"), "-begin");
outer = runOuterSupervisorTests(stagingRoot, ...
    fullfile(stagingRoot, "reports", ...
    "OUTER_SUPERVISOR_TEST_RESULT.json"));
focused = runShadowReentryFocusedTests(stagingRoot, authorityRoot, ...
    fullfile(stagingRoot, "reports", ...
    "SHADOW_REENTRY_FOCUSED_TEST_RESULT.json"));
assert(outer.status == "PASS" && focused.status == "PASS");
result = struct( ...
    "status", "PASS", ...
    "outer_supervisor", outer, ...
    "shadow_reentry", focused);
writelines(jsonencode(result, PrettyPrint=true), ...
    fullfile(stagingRoot, "reports", ...
    "SHADOW_REENTRY_TEST_SUITE_RESULT.json"), Encoding="UTF-8");
fprintf("SHADOW_REENTRY_ALL_FOCUSED_PASS\n");
end
