function [contract,validation]=buildTerrainDiagnosticRuntimeContract()
% Bind the diagnostic model to its reference observation and offline checks.
% Creates/installs nothing and grants neither a live result nor flight access.
here=string(fileparts(mfilename('fullpath')));mc=fileparts(fileparts(here));b=fileparts(mc);
e=fullfile(b,'evidence');k=fullfile(b,'matlab_validation','+m600check');
obs=string(gpenmpc_external_path('sensor_aligned_observation_fixture'));
items={ ...
 'old_dll_build',fullfile(gpenmpc_external_path('flat_terrain_model_dll'),'DLL_BUILD_RESULT.json'); ...
 'new_dll_build',fullfile(gpenmpc_external_path('diagnostic_terrain_model_dll'),'DLL_BUILD_RESULT.json'); ...
 'model_preparation',fullfile(gpenmpc_external_path('diagnostic_terrain_model'),'MODEL_PREPARATION_RESULT.json'); ...
 'source_replay',fullfile(gpenmpc_external_path('host_terrain_model_source_replay'),'RESULT.json'); ...
 'extension_probe',fullfile(gpenmpc_external_path('host_terrain_diagnostic_dll_probe'),'RESULT.json'); ...
 'legacy_probe',fullfile(gpenmpc_external_path('host_terrain_dll_legacy_probe'),'PROBE_RESULT.json'); ...
 'old_model',fullfile(gpenmpc_external_path('flat_terrain_model'),'GPENMPC_M600_Canonical.slx'); ...
 'new_model',fullfile(gpenmpc_external_path('diagnostic_terrain_model'),'GPENMPC_M600_Canonical.slx'); ...
 'old_parameters',fullfile(gpenmpc_external_path('flat_terrain_model'),'M600_CORE_PARAMETERS.mat'); ...
 'new_parameters',fullfile(gpenmpc_external_path('diagnostic_terrain_model'),'M600_CORE_PARAMETERS.mat'); ...
 'old_dll',fullfile(gpenmpc_external_path('flat_terrain_model_dll'),'compiled','GPENMPC_M600_Canonical.dll'); ...
 'new_dll',fullfile(gpenmpc_external_path('diagnostic_terrain_model_dll'),'compiled','GPENMPC_M600_Canonical.dll'); ...
 'core_source',fullfile(k,'copterSimFlatTerrainCore.m'); ...
 'sensor_encoder',fullfile(here,'encodeHilSensorLevelFrame.m'); ...
 'terrain_encoder',fullfile(k,'encodeCopterSimTerrainDiagnostics.m'); ...
 'terrain_state',fullfile(k,'initialCopterSimTerrainDiagnosticState.m'); ...
 'terrain_decoder',fullfile(k,'decodeCopterSimTerrainDiagnostics.m'); ...
 'legacy_decoder',fullfile(k,'decodeCopterSimDiagnostics.m'); ...
 'old_observation_plan',fullfile(obs,'CONSUMED_INPUTS','CONSUMED_PLAN.json'); ...
 'old_observation_outer',fullfile(obs,'OUTER_RESULT.json'); ...
 'old_observation_result',fullfile(obs,'INITIALIZATION_MATLAB','RESULT.json'); ...
 'replayed_model',fullfile(gpenmpc_external_path('host_terrain_model_source_replay'),'derived_sim','GPENMPC_M600_Canonical.slx'); ...
 'replayed_parameters',fullfile(gpenmpc_external_path('host_terrain_model_source_replay'),'derived_sim','M600_CORE_PARAMETERS.mat')};
refs=repmat(struct('label','','path','','bytes',0,'sha256',''),0,1);
for j=1:size(items,1)
 r=fileRef(items{j,2});refs(end+1)=struct('label',items{j,1},'path',r.path,'bytes',r.bytes,'sha256',r.sha256); %#ok<AGROW>
end
contract=struct('schema','M600_TERRAIN_DIAGNOSTIC_RUNTIME_CONTRACT_V1', ...
 'scope','HOST_EQUIVALENT_DIAGNOSTIC_ONLY_DERIVATION__NO_NEW_LIVE_CREDIT', ...
 'require_terrain_diagnostic_extension',true,'requires_fresh_runtime_preflight_and_observation',true, ...
 'old_observation',struct('execution_id','SENSOR_ALIGNED_REFERENCE_OBSERVATION','root',obs, ...
    'duration_s',45,'dll_sha256','80C95FA673EC462EB3108016A0F53FE4A7A50A7FD9F016DFB57EE9345A09EAE4', ...
    'scope','REFERENCE_MODEL_OBSERVATION'), ...
 'changes',struct('dynamics','UNCHANGED','parameters','BYTE_IDENTICAL', ...
    'sensor_pack_and_level_inverse','UNCHANGED','diagnostic_prefix7','BYTE_IDENTICAL', ...
    'terrain_guard','UNCHANGED_FAIL_CLOSED','only_new_data','FIRST_TERRAIN_FAULT_OBSERVATION_TAIL'), ...
 'layout',struct('packet_bytes',264,'payload_doubles',32,'legacy_prefix',1:7, ...
    'capture_valid',8,'first_reason',9,'locked_height',10,'first_terrain15',11:25, ...
    'extension_tag_index',26,'extension_tag_value',1,'reserved_zero',27:32), ...
 'claims',struct('host_equivalence',true,'new_live_verified',false,'old_live_credit_applies_to_new_runtime',false, ...
    'flight_admission',false,'terrain_source_cause_identified',false,'control_performance_PASS',false, ...
    'runtime_installed',false), ...
 'authority',struct('COM_open',0,'UDP_open',0,'board_actions',0,'parameter_writes',0, ...
    'firmware_writes',0,'arm_requests',0,'mode_requests',0,'outputs',0), ...
 'bindings',refs);
validation=m600check.validateTerrainDiagnosticRuntimeContract(contract);
end
function r=fileRef(file)
d=dir(file);assert(isscalar(d)&&~d.isdir,'m600check:TerrainContractMissing','%s',file);
r=struct('path',char(file),'bytes',d.bytes,'sha256',m600check.fileSha256(file));
end
