function [messages,receipt]=decodeCanonicalExchangePackets(packets,dialect,expected)
% Pure validation before the EXISTING mavlinkio owner submits MsgID/Payload.
% Input serialization sequence is evidence only; sendudpmsg generates the
% final link sequence.
assert(iscell(packets)&&isvector(packets)&&~isempty(packets)&&numel(packets)<=7, ...
    'm600check:CanonicalPacketCount','One bounded context/numeric group is required.');
messages=cell(size(packets));total=0;sequences=zeros(numel(packets),1,'uint8');
for k=1:numel(packets)
    bytes=packets{k};
    assert(isa(bytes,'uint8')&&isvector(bytes)&&numel(bytes)>=12&&bytes(1)==253 ...
        &&bytes(3)==0&&bytes(4)==0&&numel(bytes)==double(bytes(2))+12, ...
        'm600check:CanonicalPacketFrame','Exactly one complete unsigned MAVLink2 frame is required.');
    message=deserializemsg(dialect,bytes);
    assert(isscalar(message)&&double(message.MsgID)==385, ...
        'm600check:CanonicalPacketDecode','Official decoder must accept exactly one CRC-valid TUNNEL.');
    p=message.Payload;
    assert(isequal(uint8(message.SystemID),expected.target_system) ...
        &&isequal(uint8(message.ComponentID),expected.target_component) ...
        &&isequal(p.target_system,expected.source_system)&&isequal(p.target_component,expected.source_component) ...
        &&isequal(p.payload_type,uint16(42002))&&isa(p.payload,'uint8')&&numel(p.payload)==128, ...
        'm600check:CanonicalPacketEndpoints','Input frame must name the same registered endpoints.');
    version=double(bitshift(p.payload(1),-4));index=double(bitand(p.payload(1),uint8(15)));
    assert(ismember(version,[2,4]),'m600check:CanonicalPacketSchema','Only existing numeric/context ingress schemas are sent here.');
    if version==2,length=381;count=4;else,length=316;count=3;end
    assert(index<count&&double(p.payload_length)==9+min(119,length-index*119) ...
        &&any(p.payload(2:9))&&all(p.payload(double(p.payload_length)+1:end)==0), ...
        'm600check:CanonicalPacketFragment','Fragment shape required.');
    messages{k}=message;total=total+numel(bytes);sequences(k)=message.Seq;
end
receipt=struct('input_serialized_bytes',total,'input_sequences',sequences, ...
    'official_decoder_crc_accepted',true,'input_frames_are_final_wire',false, ...
    'source_payload_unchanged',true,'connections_opened',0,'control_authority',false);
end
