function r=evaluateUtcDrift(beforeS,utcS,afterS,utcPair,boundS)
% Both endpoint measurement intervals bound the clock-offset change.
v=[beforeS,utcS,afterS,utcPair.utc_zero_s,utcPair.uncertainty_s,boundS];
assert(isnumeric(v)&&isreal(v)&&numel(v)==6&&all(isfinite(v))&& ...
    afterS>=beforeS&&utcPair.uncertainty_s>=0&&boundS>0, ...
    'm600check:UtcDriftInput','Invalid clock drift measurement.');
observed=(utcS-utcPair.utc_zero_s)-(beforeS+afterS)/2;
currentUncertainty=(afterS-beforeS)/2+4*eps(abs(utcS));
combined=utcPair.uncertainty_s+currentUncertainty;
r=struct('observed_drift_s',observed,'current_sample_uncertainty_s',currentUncertainty, ...
    'initial_pair_uncertainty_s',utcPair.uncertainty_s,'combined_uncertainty_s',combined, ...
    'absolute_drift_upper_bound_s',abs(observed)+combined,'bound_s',boundS, ...
    'passed',abs(observed)+combined<=boundS);
end
