function r = sampleUtcMonotonicPair(monotonicNow, utcNow, sampleCount, driftBoundS)
%SAMPLEUTCMONOTONICPAIR Bounded, measured clock calibration; no I/O endpoints.
% Fixed prospective sample count. Preserve EVERY bracket, including first-call
% datetime/JIT overhead; select the narrowest measured acquisition interval.
assert(isa(monotonicNow,'function_handle')&&isa(utcNow,'function_handle'), ...
    'm600check:ClockSamplerFunction','Two clock functions are required.');
assert(isnumeric(sampleCount)&&isscalar(sampleCount)&&isfinite(sampleCount)&& ...
    sampleCount==fix(sampleCount)&&sampleCount>=1&&sampleCount<=32, ...
    'm600check:ClockSamplerCount','Bounded integer sample count required.');
assert(isnumeric(driftBoundS)&&isscalar(driftBoundS)&&isfinite(driftBoundS)&&driftBoundS>0, ...
    'm600check:ClockSamplerDriftBound','Existing positive UTC drift bound required.');
rows=repmat(struct('before_s',0,'utc_s',0,'after_s',0,'offset_lower_s',0, ...
    'offset_upper_s',0,'bracket_s',0),sampleCount,1);
lastAfter=-Inf;
for k=1:sampleCount
    before=monotonicNow();wall=utcNow();after=monotonicNow();
    assert(all(cellfun(@(v)isnumeric(v)&&isreal(v)&&isscalar(v)&&isfinite(v), ...
        {before,wall,after})),'m600check:ClockSamplerNonfinite','Invalid clock observation.');
    assert(before>=lastAfter&&after>=before,'m600check:ClockSamplerMonotonicReversal', ...
        'Monotonic clock must not go backwards.');
    rows(k)=struct('before_s',before,'utc_s',wall,'after_s',after, ...
        'offset_lower_s',wall-after,'offset_upper_s',wall-before,'bracket_s',after-before);
    lastAfter=after;
end
[~,selected]=min([rows.bracket_s]);q=rows(selected);
% Floating-point UTC subtraction has sub-microsecond roundoff at today's epoch.
% Include it in uncertainty.
roundoff=4*eps(max(abs([rows.utc_s])));
separation=max(0,max([rows.offset_lower_s])-min([rows.offset_upper_s]));
assert(separation<=driftBoundS+roundoff,'m600check:ClockSamplerUtcDiscontinuity', ...
    'Clock brackets disagree beyond the unchanged UTC drift bound.');
r=struct('utc_zero_s',q.utc_s-(q.before_s+q.after_s)/2, ...
    'uncertainty_s',q.bracket_s/2+roundoff,'selected_sample',selected, ...
    'sample_count',sampleCount,'samples',rows,'roundoff_allowance_s',roundoff, ...
    'interval_separation_s',separation,'utc_drift_bound_s',driftBoundS, ...
    'selection_rule','FIXED_COUNT_NARROWEST_MEASURED_CLOCK_BRACKET__ALL_SAMPLES_RETAINED');
end
