function report=validateTerrainDiagnosticRuntimeContract(contract,consumer)
% File-only verification. Optional consumer binds actual copies and required
% decoder flag; even a valid consumer is NOT a new live/flight acceptance.
if nargin<2,consumer=[];end
report=struct('passed',false,'status','REJECT_TERRAIN_DIAGNOSTIC_RUNTIME_CONTRACT', ...
 'failure','','checks',{{}},'references_verified',0,'consumer_verified',false, ...
 'old_live_scope','REFERENCE_MODEL_OBSERVATION','new_live_credit',false,'flight_admission',false, ...
 'requires_fresh_runtime_preflight_and_observation',true,'COM_open',0,'UDP_open',0,'board_actions',0);
try
 fields={'schema','scope','require_terrain_diagnostic_extension','requires_fresh_runtime_preflight_and_observation', ...
    'old_observation','changes','layout','claims','authority','bindings'};
 must(isstruct(contract)&&isscalar(contract)&&sameFields(contract,fields),'CONTRACT_FIELDS');
 must(strcmp(contract.schema,'M600_TERRAIN_DIAGNOSTIC_RUNTIME_CONTRACT_V1')&& ...
    strcmp(contract.scope,'HOST_EQUIVALENT_DIAGNOSTIC_ONLY_DERIVATION__NO_NEW_LIVE_CREDIT'),'CONTRACT_SCOPE');
 must(logicalTrue(contract.require_terrain_diagnostic_extension),'REQUIRED_EXTENSION_FLAG');
 must(logicalTrue(contract.requires_fresh_runtime_preflight_and_observation),'FRESH_RUNTIME_REQUIRED');
 claims=struct('host_equivalence',true,'new_live_verified',false,'old_live_credit_applies_to_new_runtime',false, ...
    'flight_admission',false,'terrain_source_cause_identified',false,'control_performance_PASS',false,'runtime_installed',false);
 must(same(contract.claims,claims),'NO_NEW_LIVE_OR_HARDWARE_CLAIM');
 authority=struct('COM_open',0,'UDP_open',0,'board_actions',0,'parameter_writes',0, ...
    'firmware_writes',0,'arm_requests',0,'mode_requests',0,'outputs',0);
 must(same(contract.authority,authority),'HOST_ONLY_AUTHORITY');
 changes=struct('dynamics','UNCHANGED','parameters','BYTE_IDENTICAL','sensor_pack_and_level_inverse','UNCHANGED', ...
    'diagnostic_prefix7','BYTE_IDENTICAL','terrain_guard','UNCHANGED_FAIL_CLOSED','only_new_data','FIRST_TERRAIN_FAULT_OBSERVATION_TAIL');
 must(same(contract.changes,changes),'DIAGNOSTIC_ONLY_CHANGE_SURFACE');
 layout=struct('packet_bytes',264,'payload_doubles',32,'legacy_prefix',1:7,'capture_valid',8, ...
    'first_reason',9,'locked_height',10,'first_terrain15',11:25,'extension_tag_index',26, ...
    'extension_tag_value',1,'reserved_zero',27:32);
 must(same(contract.layout,layout),'PREFIX_AND_EXTENSION_LAYOUT');
 oldObs=struct('execution_id','SENSOR_ALIGNED_REFERENCE_OBSERVATION', ...
    'root',string(gpenmpc_external_path('sensor_aligned_observation_fixture')), ...
    'duration_s',45,'dll_sha256','80C95FA673EC462EB3108016A0F53FE4A7A50A7FD9F016DFB57EE9345A09EAE4', ...
    'scope','REFERENCE_MODEL_OBSERVATION');
 must(same(contract.old_observation,oldObs),'OLD_OBSERVATION_SCOPE');
 anchors=anchorTable();refs=contract.bindings(:);labels={refs.label};
 must(numel(unique(labels))==numel(labels)&&isequal(sort(labels(:)),sort(anchors(:,1))),'BINDING_SET');
 for j=1:size(anchors,1)
    r=ref(anchors{j,1});must(sameFields(r,{'label','path','bytes','sha256'}),'BINDING_FIELDS');
    must(r.bytes==anchors{j,2}&&strcmp(r.sha256,anchors{j,3}),['PINNED_IDENTITY_' anchors{j,1}]);
    verifyFile(r);
 end
 oldModel=ref('old_model');newModel=ref('new_model');newParameters=ref('new_parameters');
 oldDll=ref('old_dll');newDll=ref('new_dll');
 if ~isempty(consumer)
    must(isstruct(consumer)&&isscalar(consumer)&& ...
      sameFields(consumer,{'model_dll','source_model','core_parameters','require_terrain_diagnostic_extension'}),'CONSUMER_FIELDS');
    must(logicalTrue(consumer.require_terrain_diagnostic_extension),'CONSUMER_REQUIRED_EXTENSION_FLAG');
    names={'model_dll','source_model','core_parameters'};roles={'new_dll','new_model','new_parameters'};
    for j=1:3
        r=consumer.(names{j});expected=ref(roles{j});must(sameFields(r,{'path','bytes','sha256'}),'CONSUMER_FILE_FIELDS');
        must(r.bytes==expected.bytes&&strcmp(r.sha256,expected.sha256),['CONSUMER_IDENTITY_' names{j}]);verifyFile(r);
    end
    report.consumer_verified=true;
 end
 prep=readRef('model_preparation');replay=readRef('source_replay');probe=readRef('extension_probe');legacy=readRef('legacy_probe');
 oldBuild=readRef('old_dll_build');newBuild=readRef('new_dll_build');
 must(prep.passed&&prep.model_updated&&prep.noncore_charts_unchanged&&prep.block_inventory_unchanged&& ...
    prep.sensor_inverse_path_preserved&&prep.single_terrain_input_snapshot&&prep.parent_files_unchanged, ...
    'ACTUAL_MODEL_UPDATE_AND_INVARIANTS');
 must(strcmp(prep.parent_model_sha256,oldModel.sha256)&& ...
    strcmp(prep.model_sha256,newModel.sha256)&&strcmp(prep.parameters_sha256,newParameters.sha256), ...
    'MODEL_AND_PARAMETER_CHAIN');
 % Reconstruct the recorded source by reversing the three exact chart edits.
 text=prep.chart_after;delta=prep.exact_changes;must(numel(delta)==3,'THREE_MINIMAL_CHART_EDITS');
 for j=numel(delta):-1:1
    must(numel(strfind(text,delta(j).replacement))==1,'UNAMBIGUOUS_CHART_PATCH');
    text=strrep(text,delta(j).replacement,delta(j).old);
 end
 must(strcmp(text,prep.chart_before),'EXACT_PARENT_CHART_RECOVERABLE');
 must(replay.passed&&strcmp(replay.status,'PASS_HOST_ACTUAL_MODEL_AND_CHART_DIAGNOSTIC_REPLAY__DLL_PROBE_PENDING')&& ...
    replay.checks_total==322&&replay.checks_passed==322&&numel(replay.checks)==322&&all([replay.checks.passed]), ...
    'ACTUAL_SOURCE_322');
 must(replay.normal_full_model_simulation&&replay.finite_fault_full_model_simulation&& ...
    replay.normal_model_samples==301&&replay.fault_model_rows==6&&replay.codec_checks_total==111&& ...
    numel(replay.source_cases)==49&&all([replay.source_cases.passed])&&replay.original_inputs_unchanged, ...
    'ACTUAL_MODEL_FAULT_RESET_SENSOR_REPLAY');
 must(strcmp(replay.parent_model_sha256,oldModel.sha256)&&strcmp(replay.derived_model_sha256,newModel.sha256)&& ...
    strcmp(replay.parameter_sha256,newParameters.sha256),'SOURCE_REPLAY_IDENTITY_CHAIN');
 must(replay.COM_open==0&&replay.UDP_open==0&&replay.board_actions==0&&~replay.HIL_performance_claim&& ...
    ~replay.closed_loop_controller_used&&~replay.terrain_source_cause_identified,'SOURCE_REPLAY_HOST_CLAIM');
 must(strcmp(oldBuild.dll_sha256,oldDll.sha256)&&strcmp(oldBuild.source_model_sha256,oldModel.sha256)&& ...
    strcmp(newBuild.dll_sha256,newDll.sha256)&&strcmp(newBuild.source_model_sha256,newModel.sha256)&& ...
    strcmp(oldBuild.abi_parent_cpp_sha256,newBuild.abi_parent_cpp_sha256), 'DLL_BUILD_MODEL_AND_ABI_CHAIN');
 must(probe.passed&&strcmp(probe.status,'PASS_GENERATED_DLL_TERRAIN_EXTENSION_AND_PARENT_OUTPUT_EQUIVALENCE__HOST_ONLY')&& ...
    probe.compile_returncode==0&&probe.probe_returncode==0&&probe.rows==5940&&probe.cases==50&& ...
    probe.checks_total==12&&probe.checks_passed==12&&numel(probe.checks)==12&&all([probe.checks.passed]), ...
    'ACTUAL_DLL_50_5940');
 must(strcmp(probe.old_dll_sha256,oldDll.sha256)&&strcmp(probe.new_dll_sha256,newDll.sha256)&& ...
    strcmp(probe.diagnostic_prefix_requirement,'FIRST_SEVEN_DOUBLES_BYTE_EXACT')&& ...
    all(probe.paired_max_abs_difference_vehicle_sensor_GPS==0)&&all(probe.bitwise_equal_rows_vehicle_sensor_GPS==5940), ...
    'DLL_PREFIX_AND_ALL_PHYSICS_SENSOR_GPS_UNCHANGED');
 must(numel(probe.first_faults)==47&&sum([probe.first_faults.first_reason]==2)==46&& ...
    sum([probe.first_faults.first_reason]==3)==1,'DLL_ACTUAL_FIRST_FAULT_DENOMINATOR');
 for j=1:numel(probe.first_faults)
    a=probe.first_faults(j);must(isequal(string(a.input_float64_hex(:)),string(a.captured_float64_hex(:)))&& ...
       numel(a.input_float64_hex)==15,'ALL15_FAULT_BITS_PRESERVED');
 end
 for j=1:numel(probe.evidence),verifyFile(probe.evidence(j));end
 must(probe.COM_open==0&&probe.UDP_open==0&&probe.board_actions==0&&~probe.CopterSim_started&& ...
    ~probe.controller_closed_loop&&~probe.HIL_performance_claim&&~probe.terrain_source_cause_identified, ...
    'DLL_PROBE_HOST_ONLY_CLAIM');
 must(strcmp(legacy.status,'PASS_DLL_ABI_AND_DIAGNOSTIC_FAULT_LATCH_ONLY')&&legacy.rows==18000&&legacy.cases==6&& ...
    strcmp(legacy.dll_sha256,newDll.sha256)&&legacy.hardware_actions==0&&legacy.COM_open==0&& ...
    ~legacy.CopterSim_executed&&~legacy.controller_closed_loop,'ACTUAL_LEGACY_18000_STEPS');
 verifyFile(struct('path',legacy.trace,'bytes',5851850,'sha256',legacy.trace_sha256));
 % Verify the reference observation and recorded safety conditions,
 % including the bound reference model identity.
 here=string(fileparts(mfilename('fullpath')));b=fileparts(fileparts(fileparts(here)));
 oldPath=path;guard=onCleanup(@()path(oldPath)); %#ok<NASGU>
 addpath(fullfile(b,'tools'),'-begin');context=make_sensor_aligned_hover_preparation();
 oldCheck=m600check.verifySensorAlignedHoverPreparation(context,context.calibration_contract);
 must(oldCheck.passed,'REFERENCE_OBSERVATION_VERIFIER');
 must(strcmp(context.runtime_binding.model_dll_sha256,oldDll.sha256)&& ...
    context.observation.elapsed_s==45,'REFERENCE_OBSERVATION_MODEL_IDENTITY');
 oldPlan=readRef('old_observation_plan');oldRef=oldPlan.references(strcmp({oldPlan.references.label},'model_dll'));
 must(isscalar(oldRef)&&strcmp(oldRef.sha256,oldDll.sha256),'OLD_CONSUMED_PLAN_NOT_REWRITTEN');
 report.old_observation_rows=oldCheck.observation.full_window_rows;
 report.passed=true;report.status='PASS_HOST_DIAGNOSTIC_DERIVATION_CONTRACT__NO_NEW_LIVE_CREDIT';
catch problem
 report.consumer_verified=false;
 report.failure=[problem.identifier ': ' problem.message];
end
    function must(ok,reason)
        if ~isscalar(ok)||~logical(ok),error('m600check:TerrainRuntimeContract','%s',reason);end
        report.checks{end+1}=reason;
    end
    function r=ref(label)
        index=find(strcmp(labels,label));must(numel(index)==1,['MISSING_' label]);r=refs(index);
    end
    function data=readRef(label),r=ref(label);data=m600check.normalizeTerrainFixtureMetadata(jsondecode(fileread(r.path)));end
    function verifyFile(r)
        d=dir(r.path);must(isscalar(d)&&~d.isdir,'MISSING_FILE');
        must(d.bytes==r.bytes&&strcmp(m600check.fileSha256(r.path),r.sha256),'FILE_BYTES_OR_SHA_MISMATCH');
        report.references_verified=report.references_verified+1;
    end
end
function okay=sameFields(x,names),okay=isstruct(x)&&isscalar(x)&&isequal(sort(fieldnames(x)),sort(names(:)));end
function yes=logicalTrue(value),yes=islogical(value)&&isscalar(value)&&value;end
function yes=same(a,b),yes=typedEqual(normalize(a),normalize(b));end
function yes=typedEqual(a,b)
% MATLAB isequal/isequaln regard logical true and double 1 as equal, even in
% nested structs. Check the class at EVERY leaf, not only the root struct.
yes=strcmp(class(a),class(b))&&isequal(size(a),size(b));if ~yes,return;end
if isstruct(a)
 names=fieldnames(a);yes=isequal(names,fieldnames(b));if ~yes,return;end
 for j=1:numel(a)
    for k=1:numel(names)
        if ~typedEqual(a(j).(names{k}),b(j).(names{k})),yes=false;return;end
    end
 end
elseif iscell(a)
 for j=1:numel(a),if ~typedEqual(a{j},b{j}),yes=false;return;end,end
else
 yes=isequaln(a,b);
end
end
function x=normalize(x)
if isstruct(x)
 x=orderfields(x);x=x(:);names=fieldnames(x);
 for j=1:numel(x),for k=1:numel(names),x(j).(names{k})=normalize(x(j).(names{k}));end,end
elseif iscell(x),x=x(:);for j=1:numel(x),x{j}=normalize(x{j});end
elseif isstring(x)
 if isscalar(x),x=char(x);else,x=cellstr(x(:));end
elseif isnumeric(x)&&isvector(x),x=x(:);
end
end
function a=anchorTable()
a={ ...
 'old_dll_build',1001,'2E597460C7091A5CBB35215D09BCBAD71F28AF9A711BD23F0CC8F19CFF27C9E9'; ...
 'new_dll_build',1019,'246579340896482453536E5F644F25690CAE9BD5B3DA719D0CD2E7BF61EDAFB5'; ...
 'model_preparation',6970,'9EC908E95AA8668F5E04AE3DD6F43365D6E8CB9859399964FFD924C8136AFB3F'; ...
 'source_replay',72753,'1343D24DA9F61B8EDF97EB19F3CD7A31B06270B091B225A4647BFE8CA823B903'; ...
 'extension_probe',55004,'C1E008B506AC4A54E48C4BDA767C05ADB1CCAB99692A9D6B2D0E47A07FF128BC'; ...
 'legacy_probe',680,'B5D020482F929D3697CE6CB9624DEE965926888B0251970EB7FA03FB596A6196'; ...
 'old_model',240314,'5B5874C28A2D6E005F29F88F8B95B475005FB62BFE2B41AF03A783425ECFA505'; ...
 'new_model',240670,'8A51BDA54AB552953AEC2D6ABF53634FEAB40DA4F2489A3EB09E56146254F03C'; ...
 'old_parameters',1373,'969D347CE041715CAED49BE0B7897486E34FA4E0B22EB82E50E9752B8F4F19E4'; ...
 'new_parameters',1373,'969D347CE041715CAED49BE0B7897486E34FA4E0B22EB82E50E9752B8F4F19E4'; ...
 'old_dll',152064,'80C95FA673EC462EB3108016A0F53FE4A7A50A7FD9F016DFB57EE9345A09EAE4'; ...
 'new_dll',152576,'458D2CCBFB50EC47E23E0F76AA9CDC851D14622A78B88205710060EC2BA3657D'; ...
 'core_source',4216,'99F24AFCA87539A1CCD34CE79CAA0E2425BEAF0868CDB07608E4600240F2CBFB'; ...
 'sensor_encoder',1251,'8F6769EAF1C131E7F917C892CAE814AD6C245FF2BC5AEAA619BAC52883E5ABBB'; ...
 'terrain_encoder',2008,'C3FE21E0A004CEECDFA4889511293E3908111931E708C2D03063E1941FF13B81'; ...
 'terrain_state',264,'B8AE37087C93F785B58F685BE372B918EC341852A0685B4B6AC9DFE3E7938B8D'; ...
 'terrain_decoder',3737,'C1EE72EE293BEE4928765C11F65A4B189A35F2E625E588B5469B64DCF5EDC777'; ...
 'legacy_decoder',3219,'558B0F8FBE198AA066A734B66129776F5B248E9C14598FC1EC6BF2DC5C19BD6C'; ...
 'old_observation_plan',41615,'9FC9ED781194E6CC255946B6D03788EA62709424243DDA160138CC2468A00D2D'; ...
 'old_observation_outer',201924,'FB6E9A4ECEC74526BBE1EBEDB01B197E7864A2EBDDD4528616D802EE7B03E887'; ...
 'old_observation_result',15415,'7AA47527DDECA06DC68DEF03F14E8D7BA5AFCCAC004CFFD962AC344040C6FB59'; ...
 'replayed_model',240670,'8A51BDA54AB552953AEC2D6ABF53634FEAB40DA4F2489A3EB09E56146254F03C'; ...
 'replayed_parameters',1373,'969D347CE041715CAED49BE0B7897486E34FA4E0B22EB82E50E9752B8F4F19E4'};
end
