function report=validateTemporaryAllocatorGeometry(contract)
% Validate allocator geometry and its source bindings.
report=struct('passed',false,'failure','','errors',{{}},'entries',[], ...
    'unchanged_guard_entries',[],'bindings',struct(),'data_validation',[], ...
    'hardware_actions',0,'flight_admission',false);
try
    assert(isstruct(contract)&&isscalar(contract)&&strcmp(contract.schema,'TEMPORARY_M600_NATIVE_ALLOCATOR_GEOMETRY_V1'), ...
        'm600check:GeometryContractSchema','Wrong temporary geometry schema.');
    assert(isequal(double(contract.maximum_apply_passes),1)&& ...
        strcmp(contract.restore_policy,'IDEMPOTENT_PER_OWNER_AFTER_DISARM_ZERO_OUTPUTS')&& ...
        ~isfield(contract,'maximum_restore_passes'), ...
        'm600check:GeometryRestorePolicy','One apply; independent safe-owner restoration must not be count-blocked.');
    for key={'gains_changes','failure_detector_changes','physical_mapping_changes','model_changes'}
        x=contract.(key{1});assert(isscalar(x)&&(islogical(x)||isnumeric(x))&&isfinite(x)&&x==0, ...
            'm600check:GeometryScope','No gains/FD/physical mapping/model change is permitted.');
    end
    [auditText,report.bindings.geometry_audit]=binding(contract.bindings.geometry_audit,true);
    [nativeText,report.bindings.native79]=binding(contract.bindings.native79,true);
    [~,report.bindings.canonical_source]=binding(contract.bindings.canonical_source,false);
    math=jsondecode(auditText);native79=jsondecode(nativeText);
    assert(strcmp(math.schema,'HOST_NATIVE_ROTOR_GEOMETRY_TEST_V1')&&logicalTrue(math.passed)&& ...
        math.case_count>0&&math.case_count==math.cases_passed&&numel(math.cases)==math.case_count&& ...
        all(arrayfun(@(c)logicalTrue(c.passed),math.cases))&& ...
        isequal(double(math.COM_UDP_board_model_actions),0)&&logicalZero(math.flight_admission), ...
        'm600check:GeometryMathSuite','All addressed static geometry cases must pass.');
    a=math.audit;
    assert(strcmpi(a.receipt_sha256,contract.bindings.native79.sha256)&& ...
        samePath(a.receipt_path,contract.bindings.native79.path)&& ...
        strcmpi(a.source_sha256,contract.bindings.canonical_source.sha256)&& ...
        samePath(a.source_path,contract.bindings.canonical_source.path)&&logicalTrue(a.receipt_is_actual_file), ...
        'm600check:GeometrySourceBinding','Math proof source/native79 bindings do not match exact files.');
    v=m600check.validateTemporaryAllocatorGeometryEntries(contract.entries,a,native79,contract.unchanged_guard_entries);
    report.data_validation=v;
    assert(v.passed,'m600check:GeometryDataRejected','%s',v.failure);
    report.entries=v.entries;report.unchanged_guard_entries=v.unchanged_guard_entries;report.passed=true;
catch p
    report.failure=[p.identifier ': ' p.message];report.errors={struct('identifier',p.identifier,'message',p.message)};
end
end
function [text,r]=binding(b,readText)
assert(isstruct(b)&&isscalar(b)&&all(isfield(b,{'path','bytes','sha256'}))&& ...
    isscalar(b.bytes)&&isfinite(b.bytes)&&b.bytes>0&&b.bytes==fix(b.bytes)&& ...
    ~isempty(regexp(char(b.sha256),'^[0-9A-Fa-f]{64}$','once')), ...
    'm600check:GeometryFileBinding','Exact path/bytes/SHA required.');
path=char(b.path);f=dir(path);assert(isfile(path)&&numel(f)==1&&f.bytes==b.bytes, ...
    'm600check:GeometryFileBytes','Missing or byte-size mismatch: %s',path);
fid=fopen(path,'rb');assert(fid>=0);c=onCleanup(@()fclose(fid)); %#ok<NASGU>
raw=fread(fid,Inf,'*uint8');md=java.security.MessageDigest.getInstance('SHA-256');md.update(raw);
h=upper(reshape(dec2hex(typecast(md.digest(),'uint8'),2).',1,[]));
assert(strcmpi(h,b.sha256),'m600check:GeometryFileHash','SHA mismatch: %s',path);
r=struct('path',path,'bytes',numel(raw),'sha256',h,'passed',true);text='';
if readText,text=native2unicode(raw.','UTF-8');end
end
function yes=samePath(a,b),yes=strcmpi(strrep(char(a),'/','\'),strrep(char(b),'/','\'));end
function yes=logicalTrue(x),yes=(islogical(x)||isnumeric(x))&&isscalar(x)&&isreal(x)&&isfinite(x)&&x==1;end
function yes=logicalZero(x),yes=(islogical(x)||isnumeric(x))&&isscalar(x)&&isreal(x)&&isfinite(x)&&x==0;end
