function profiles = gpenmpcAttitudeContinuityProfiles()
%GPENMPCATTITUDECONTINUITYPROFILES Three SO(3) rotation-filter profiles.
%
% Only the SO(3) rotation-filter time constant varies. The 1.5 rad/s value is
% the configured angular-rate bound, and the acceleration bound
% governs command continuity. These profiles define the finite comparison set.

ids = ["SO3_CONTINUITY_FAST"; "SO3_CONTINUITY_BALANCED"; ...
    "SO3_CONTINUITY_SMOOTH"];
tau = [0.04; 0.08; 0.12];
template = struct( ...
    "profile_id", "", ...
    "enabled", true, ...
    "time_constant_s", 0.0, ...
    "maximum_angular_velocity_rad_s", 1.5, ...
    "maximum_angular_acceleration_rad_s2", 8.0, ...
    "maximum_angular_jerk_rad_s3", 50.0, ...
    "maximum_continuous_dt_s", 0.05);
profiles = repmat(template, numel(ids), 1);
for index = 1:numel(ids)
    profiles(index) = struct( ...
        "profile_id", ids(index), ...
        "enabled", true, ...
        "time_constant_s", tau(index), ...
        "maximum_angular_velocity_rad_s", 1.5, ...
        "maximum_angular_acceleration_rad_s2", 8.0, ...
        "maximum_angular_jerk_rad_s3", 50.0, ...
        "maximum_continuous_dt_s", 0.05);
end
end
