function modelPath = buildGPENMPCNativeSixDofClosedLoop(outputRoot)
%BUILDGPENMPCNATIVESIXDOFCLOSEDLOOP Build an executable native Simulink loop.
%
% Assemble the reference, sparse-GP eNMPC and six-degree-of-freedom software
% plant into a host-side Simulink model.

arguments
    outputRoot (1,1) string
end
if ~isfolder(outputRoot)
    mkdir(outputRoot);
end
modelName = "GPENMPC_Native_GP_ENMPC_6DoF_ClosedLoop";
modelPath = fullfile(outputRoot, modelName + ".slx");
if isfile(modelPath)
    error("buildGPENMPCNativeSixDofClosedLoop:AppendOnly", ...
        "Refusing to overwrite %s", modelPath);
end
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
load_system("simulink");
new_system(modelName);
set_param(modelName, "SolverType", "Fixed-step", "Solver", "FixedStepDiscrete", ...
    "FixedStep", "0.01", "StopTime", "4.0", "SimulationMode", "normal", ...
    "SaveOutput", "on", "OutputSaveName", "yout", ...
    "SaveFormat", "Dataset", "ShowPortDataTypes", "on");

add_block("simulink/User-Defined Functions/Level-2 MATLAB S-Function", ...
    modelName + "/C3 reference and environment", ...
    "FunctionName", "gpenmpcNativeReferenceSfun", ...
    "Position", [35 120 230 185]);
add_block("simulink/User-Defined Functions/Level-2 MATLAB S-Function", ...
    modelName + "/Sparse GP ordinary B2 eNMPC", ...
    "FunctionName", "gpenmpcNativeOuterLoopSfun", ...
    "Position", [365 60 630 190]);
add_block("simulink/User-Defined Functions/Level-2 MATLAB S-Function", ...
    modelName + "/Robust SE3 six rotor 6DoF plant", ...
    "FunctionName", "gpenmpcNativeInnerPlantSfun", ...
    "Position", [760 70 1045 225]);
add_block("simulink/Discrete/Unit Delay", modelName + "/Previous applied force", ...
    "SampleTime", "0.01", "InitialCondition", "[0;0;100]", ...
    "Position", [1110 260 1170 300]);
initialState = zeros(19, 1);
initialState(3) = 1.5;
initialState(7) = 1.0;
add_block("simulink/Discrete/Unit Delay", modelName + "/Measured state one tick", ...
    "SampleTime", "0.01", "InitialCondition", mat2str(initialState, 17), ...
    "Position", [1080 15 1170 50]);

add_line(modelName, "C3 reference and environment/1", ...
    "Sparse GP ordinary B2 eNMPC/2", "autorouting", "on");
add_line(modelName, "C3 reference and environment/2", ...
    "Sparse GP ordinary B2 eNMPC/3", "autorouting", "on");
add_line(modelName, "Robust SE3 six rotor 6DoF plant/1", ...
    "Measured state one tick/1", "autorouting", "on");
add_line(modelName, "Measured state one tick/1", ...
    "Sparse GP ordinary B2 eNMPC/1", "autorouting", "on");
add_line(modelName, "Previous applied force/1", ...
    "Sparse GP ordinary B2 eNMPC/4", "autorouting", "on");
add_line(modelName, "Sparse GP ordinary B2 eNMPC/1", ...
    "Robust SE3 six rotor 6DoF plant/1", "autorouting", "on");
add_line(modelName, "C3 reference and environment/2", ...
    "Robust SE3 six rotor 6DoF plant/2", "autorouting", "on");
add_line(modelName, "Robust SE3 six rotor 6DoF plant/3", ...
    "Previous applied force/1", "autorouting", "on");

signals = { ...
    "fixed_reference", "C3 reference and environment/1"; ...
    "environment", "C3 reference and environment/2"; ...
    "selected_reference", "Sparse GP ordinary B2 eNMPC/1"; ...
    "gp_diagnostics", "Sparse GP ordinary B2 eNMPC/2"; ...
    "enmpc_decision", "Sparse GP ordinary B2 eNMPC/3"; ...
    "solver_status", "Sparse GP ordinary B2 eNMPC/4"; ...
    "state", "Robust SE3 six rotor 6DoF plant/1"; ...
    "robust_se3_diagnostics", "Robust SE3 six rotor 6DoF plant/2"; ...
    "desired_force", "Robust SE3 six rotor 6DoF plant/3"; ...
    "desired_wrench", "Robust SE3 six rotor 6DoF plant/4"; ...
    "rotor_commands", "Robust SE3 six rotor 6DoF plant/5"; ...
    "modeled_power", "Robust SE3 six rotor 6DoF plant/6"; ...
    "plant_acceleration", "Robust SE3 six rotor 6DoF plant/7"};
for index = 1:size(signals, 1)
    y = 40 + 38 .* (index - 1);
    add_block("simulink/Sinks/Out1", modelName + "/" + signals{index, 1}, ...
        "Position", [1260 y 1290 y + 20], "Port", string(index));
    line = add_line(modelName, signals{index, 2}, signals{index, 1} + "/1", ...
        "autorouting", "on");
    set_param(line, "Name", signals{index, 1});
end

note = Simulink.Annotation(modelName, sprintf([ ...
    'Executable host-only loop: analytic C3 reference -> native sparse GP and finite-shooting eNMPC -> ' ...
    'robust SE(3) -> M600 six-rotor allocation -> 19-state 6DoF plant.\n' ...
    'Normal-mode sample time 0.01 s; outer ordinary-B2 update 0.30 s.']));
note.Position = [340 360 1030 425];
set_param(modelName, "ZoomFactor", "FitSystem");
save_system(modelName, modelPath);
close_system(modelName, 0);
end
