function [selectedReference, prediction, decision, nextWarmStart, audit] = ...
        gpenmpcNativeHarnessOuterStep(state, fixedReference, environment, ...
        previousForce, warmStart, residualHistoryF, lastTangentXY, phaseRate, assets)
%GPENMPCNATIVEHARNESSOUTERSTEP Execute native GP inference and finite shooting.
%
% Supply a deterministic, physically dimensioned short-horizon rollout to
% the native finite-shooting solver through the Simulink signal interface.

[features, frameIFromF] = gpenmpcBuildOnlineF17(state, fixedReference, ...
    environment, residualHistoryF, lastTangentXY);
prediction = gpenmpcSparseGpPredict(assets.gp_model, features);
gpMeansF = repmat(prediction.applied_mean_f_mps2, ...
    assets.enmpc.horizon_steps, 1);
gpMeansI = (frameIFromF * gpMeansF.').';

b2 = @(candidate) evaluateCandidate(candidate, true, state, fixedReference, ...
    environment, previousForce, phaseRate, gpMeansI, prediction, assets);
b1 = @(candidate) evaluateCandidate(candidate, false, state, fixedReference, ...
    environment, previousForce, phaseRate, zeros(size(gpMeansI)), prediction, assets);
[decision, nextWarmStart, audit] = gpenmpcSolveOrdinaryB2FiniteShooting( ...
    warmStart, gpMeansI, b2, b1, assets.enmpc);

selectedReference = double(fixedReference(:));
if decision.success && ~decision.fallback_active
    nextRate = min(max(phaseRate + assets.outer_period_s .* ...
        decision.phase_acceleration_s_inv, assets.enmpc.phase_rate_min), ...
        assets.enmpc.phase_rate_max);
    correctionI = frameIFromF * ...
        double(decision.outer_acceleration_correction_f_mps2(:));
    selectedReference(4:6) = nextRate .* selectedReference(4:6);
    selectedReference(7:9) = nextRate.^2 .* selectedReference(7:9) + correctionI;
    selectedReference(10:12) = nextRate.^3 .* selectedReference(10:12);
end
end

function result = evaluateCandidate(candidate, useGp, state0, reference0, ...
        environment, previousForce, phaseRate0, gpMeansI, prediction, assets)
cfg = assets.enmpc;
dt = cfg.prediction_step_s;
position = double(state0(1:3));
velocity = double(state0(4:6));
phaseRate = phaseRate0;
previousAcceleration = double(reference0(7:9));
previousPhaseAcceleration = 0.0;
previousForce = double(previousForce(:));
payload = double(environment(5));
mass = double(assets.profile.mass_properties.base_mass_kg) + payload;
gravity = 9.80665;
upper = double(assets.calibration.rotor_allocation.per_rotor_thrust_upper_n);
tiltLimit = deg2rad(double(assets.calibration.development_limits.tilt_deg));
stageRows = cell(cfg.horizon_steps, 1);

for index = 1:cfg.horizon_steps
    blockIndex = ceil(index ./ cfg.move_block_size);
    phaseAcceleration = candidate(blockIndex);
    phaseRate = min(max(phaseRate + dt .* phaseAcceleration, ...
        cfg.phase_rate_min), cfg.phase_rate_max);
    horizon = index .* dt;
    referencePosition = reference0(1:3) + horizon .* reference0(4:6) ...
        + 0.5 .* horizon.^2 .* reference0(7:9) ...
        + horizon.^3 ./ 6.0 .* reference0(10:12);
    referenceVelocity = phaseRate .* (reference0(4:6) ...
        + horizon .* reference0(7:9) + 0.5 .* horizon.^2 .* reference0(10:12));
    referenceAcceleration = phaseRate.^2 .* ...
        (reference0(7:9) + horizon .* reference0(10:12));
    correction = candidate(cfg.control_blocks + 1:end).';
    [~, frameIFromF] = gpenmpcBuildOnlineF17(state0, reference0, ...
        environment, zeros(3, 1), [1; 0]);
    correctionI = frameIFromF * correction;
    learned = zeros(3, 1);
    trust = 0.0;
    hardInvalid = false;
    if useGp
        learned = gpMeansI(index, :).';
        trust = double(prediction.trust);
        hardInvalid = logical(prediction.hard_invalid);
    end
    commandedAcceleration = referenceAcceleration + correctionI;
    predictedAcceleration = commandedAcceleration + learned;
    velocity = velocity + dt .* predictedAcceleration;
    position = position + dt .* velocity;
    positionError = norm(position - referencePosition);
    velocityError = norm(velocity - referenceVelocity);
    force = mass .* (commandedAcceleration + [0; 0; gravity]);
    forceVariation = norm(force - previousForce);
    referenceJerk = norm((commandedAcceleration - previousAcceleration) ./ dt);
    phaseJerk = (phaseAcceleration - previousPhaseAcceleration) ./ dt;
    airspeed = norm(velocity - [environment(1:2); 0]);
    tilt = atan2(norm(force(1:2)), max(force(3), 1.0e-9));
    totalThrust = norm(force);
    rotorCommand = totalThrust ./ 6.0;
    powerW = 1050.0 + 4.0 .* airspeed.^2 + 0.035 .* totalThrust.^1.5;
    stageEnergy = max(powerW .* dt, 0.0);

    hard = [ ...
        phaseRate - cfg.phase_rate_min, cfg.phase_rate_max - phaseRate, ...
        cfg.phase_acceleration_max_s_inv - abs(phaseAcceleration), ...
        cfg.outer_acceleration_correction_max_mps2 - norm(correction), ...
        cfg.position_screen_m - positionError, ...
        cfg.velocity_screen_mps - velocityError, ...
        cfg.acceleration_screen_mps2 - norm(predictedAcceleration), ...
        cfg.jerk_screen_mps3 - referenceJerk, ...
        cfg.corridor_half_width_m - min(positionError, cfg.corridor_half_width_m), ...
        6.0 .* upper - totalThrust, rotorCommand, upper - rotorCommand, ...
        tiltLimit - tilt, 25.0 - airspeed, 1.0];
    halfWidth = double(prediction.calibrated_half_width_mps2(:));
    if ~useGp
        halfWidth = zeros(3, 1);
    end
    risk = [ones(1, 3) - (halfWidth ./ max(cfg.common_robust_total_radius_f_mps2(:), 1e-9)).', ...
        trust, 1.0 - double(hardInvalid), 1.0];
    stageRows{index} = struct( ...
        "stage_energy_j", stageEnergy, ...
        "position_error_norm_m", positionError, ...
        "velocity_error_norm_mps", velocityError, ...
        "force_variation_norm_n", forceVariation, ...
        "reference_jerk_norm_mps3", referenceJerk, ...
        "phase_acceleration_s_inv", phaseAcceleration, ...
        "phase_jerk_s_inv2", phaseJerk, ...
        "progress_deficit_s", max(0.0, 1.0 - phaseRate) .* horizon, ...
        "predicted_next_position_error_m", positionError, ...
        "predicted_next_velocity_error_mps", velocityError, ...
        "trust", trust, ...
        "hard_constraints", hard, ...
        "risk_constraints_normalized", risk);
    previousAcceleration = commandedAcceleration;
    previousPhaseAcceleration = phaseAcceleration;
    previousForce = force;
end
stageRows = vertcat(stageRows{:});
terminalEnergyToGo = max(0.0, 20.0 .* norm(reference0(1:3) - position));
result = gpenmpcBookkeepEnmpcRollout(stageRows, terminalEnergyToGo, ...
    useGp && logical(prediction.hard_invalid), ...
    useGp && logical(prediction.hard_invalid), cfg);
end
