#pragma once
// Generated by actual passport-bound MATLAB loader; HOST-only export, not board readback.
#include "../CanonicalRflyExecutor.hpp"
namespace gpenmpc_rfly_px4 {
inline gpenmpc_consumption::KernelParameters canonical_application_parameters() noexcept {
gpenmpc_consumption::KernelParameters p{};
p.kp[0] = 0.42250000000000004;
p.kp[1] = 0.42250000000000004;
p.kp[2] = 0.5625;
p.kd[0] = 1.1700000000000002;
p.kd[1] = 1.1700000000000002;
p.kd[2] = 1.3500000000000001;
p.kr[0] = 12.543999999999999;
p.kr[1] = 12.543999999999999;
p.kr[2] = 12.0;
p.kw[0] = 7.6159999999999997;
p.kw[1] = 7.6159999999999997;
p.kw[2] = 10.199999999999999;
p.drag[0] = 0.063490552932321503;
p.drag[1] = 0.063490552932321503;
p.drag[2] = 0.063490552932321503;
p.inertia[0] = 1.6000000000000001;
p.inertia[1] = 0.0;
p.inertia[2] = 0.0;
p.inertia[3] = 0.0;
p.inertia[4] = 1.6000000000000001;
p.inertia[5] = 0.0;
p.inertia[6] = 0.0;
p.inertia[7] = 0.0;
p.inertia[8] = 3.0;
p.pseudoinverse[0] = 0.16666666666666666;
p.pseudoinverse[1] = 0.16666666666666663;
p.pseudoinverse[2] = 0.16666666666666663;
p.pseudoinverse[3] = 0.16666666666666666;
p.pseudoinverse[4] = 0.16666666666666669;
p.pseudoinverse[5] = 0.16666666666666669;
p.pseudoinverse[6] = -1.1590111841446e-16;
p.pseudoinverse[7] = 0.5095765835742504;
p.pseudoinverse[8] = 0.50957658357425051;
p.pseudoinverse[9] = 9.1863786201094567e-17;
p.pseudoinverse[10] = -0.50957658357425051;
p.pseudoinverse[11] = -0.50957658357425051;
p.pseudoinverse[12] = -0.58840835539864655;
p.pseudoinverse[13] = -0.29420417769932322;
p.pseudoinverse[14] = 0.29420417769932317;
p.pseudoinverse[15] = 0.58840835539864655;
p.pseudoinverse[16] = 0.29420417769932344;
p.pseudoinverse[17] = -0.29420417769932333;
p.pseudoinverse[18] = 6.666666666666667;
p.pseudoinverse[19] = -6.6666666666666661;
p.pseudoinverse[20] = 6.6666666666666661;
p.pseudoinverse[21] = -6.666666666666667;
p.pseudoinverse[22] = 6.6666666666666661;
p.pseudoinverse[23] = -6.6666666666666661;
p.baseMass = 9.5;
p.totalThrust = 192.8743620548095;
p.rotorUpper = 32.145727009134916;
p.maxTilt = 0.43633231299858238;
return p; }
constexpr gpenmpc_rfly_execution::Digest kCanonicalApplicationParameterSha{0xCBF017C7,0x34B59715,0xB563A61B,0xCB64D8B1,0x42A74000,0x7C8D610B,0xB6D4BE54,0x808356A8};
} // namespace gpenmpc_rfly_px4
