function [trace, result] = gpenmpcRunFixedC3WholeTask( ...
        task, methodId, assets, options)
%GPENMPCRUNFIXEDC3WHOLETASK Native fixed-C3 whole-task M600 closed loop.
%
% N0, R0 and GR0 share the C3 reference, plant, geometric controller,
% allocation, limits, exogenous wind estimate and service model. N0 uses
% nominal geometric tracking, R0 adds robust augmentation, and GR0 combines
% the causal GP mean with trust-conditioned robust responsibility.

arguments
    task (1,1) struct
    methodId (1,1) string
    assets (1,1) struct
    options.force_hard_invalid (1,1) logical = false
    options.maximum_samples (1,1) double = Inf
end
contract = gpenmpcFixedC3MethodContract(methodId);
if contract.external_reference_provider_required
    error("gpenmpcRunFixedC3WholeTask:ExternalReferenceProviderRequired", ...
        "%s requires the separately implemented eNMPC reference provider.", ...
        methodId);
end

reference = task.reference;
availableCount = numel(reference.global_time_s);
sampleCount = min(availableCount, floor(options.maximum_samples));
if sampleCount < 2
    error("gpenmpcRunFixedC3WholeTask:SampleCount", ...
        "At least two fixed-C3 samples are required.");
end
dtNominal = 0.01;
x = [double(task.initial_state.position_m(:)); ...
    double(task.initial_state.velocity_mps(:)); ...
    double(task.initial_state.quaternion_wxyz(:)); ...
    double(task.initial_state.body_rate_rad_s(:)); ...
    double(task.initial_state.per_rotor_thrust_n(:))];
methodState = gpenmpcInitializeFixedC3MethodState(x);
if contract.use_pid
    if ~isfield(assets,"pid_configuration")
        error("gpenmpcRunFixedC3WholeTask:PidConfiguration", ...
            "Cascaded PID requires assets.pid_configuration.");
    end
    pidConfiguration = assets.pid_configuration;
    methodState.pid = gpenmpcInitializeCascadedPidState();
else
    pidConfiguration = struct;
end

trace = allocateTrace(sampleCount);
serviceRecords = repmat(struct( ...
    "after_leg_index", 0, "start_time_s", 0.0, "end_time_s", 0.0, ...
    "duration_s", 0.0, "service_start_altitude_m", 0.0, ...
    "service_target_altitude_m", 0.0, ...
    "vertical_distance_each_m", 0.0, ...
    "vertical_duration_each_s", 0.0, ...
    "ground_duration_s", 0.0, "payload_before_kg", 0.0, ...
    "payload_after_kg", 0.0, "descent_energy_j", 0.0, ...
    "ground_energy_j", 0.0, "ascent_energy_j", 0.0, ...
    "public_energy_j", 0.0, "controller_sensitive_energy_j", 0.0, ...
    "controller_specific_adjustment_j", 0.0), 0, 1);
publicEnergyJ = 0.0;
controllerEnergyJ = 0.0;
previousPublicPowerW = NaN;
previousControllerPowerW = NaN;
previousPowerTimeS = NaN;

for index = 1:sampleCount
    globalTimeS = double(reference.global_time_s(index));
    legIndex = double(reference.leg_index(index));
    payloadKg = double(reference.payload_kg(index));
    ref = sampleReference(reference, index);
    windActual = double(reference.actual_wind_xy_mps(index, :)).';
    windEstimate = double(reference.wind_estimate_xy_mps(index, :)).';
    methodState = gpenmpcObserveFixedC3CausalHistory( ...
        methodState, x, globalTimeS, legIndex);

    if contract.use_pid
        augmentation = zeros(3,1);
        velocityXY = double(ref.velocity_mps(1:2));
        if norm(velocityXY) > 1.0e-9
            tangent = velocityXY ./ norm(velocityXY);
        else
            tangent = methodState.robust.last_tangent_xy;
        end
        frame = [tangent(1), -tangent(2), 0; ...
            tangent(2), tangent(1), 0; 0, 0, 1];
        augmentationDiagnostic = zeroAugmentationDiagnostic(frame);
        if ~isfinite(methodState.pid.last_leg_index) ...
                || methodState.pid.last_leg_index ~= legIndex
            methodState.pid = gpenmpcResetCascadedPidState( ...
                methodState.pid,legIndex);
        end
    elseif methodId == "G0_AERO_GP_ONLY_SE3"
        [augmentation, methodState, augmentationDiagnostic] = ...
            gpenmpcGpOnlySe3Augmentation(x, ref, windEstimate, ...
            payloadKg, assets.robust, assets.gp_model, methodState, ...
            dtNominal, options.force_hard_invalid);
    elseif contract.use_gp
        [augmentation, methodState, augmentationDiagnostic] = ...
            gpenmpcGpRobustSe3Augmentation(x, ref, windEstimate, ...
            payloadKg, assets.robust, assets.gp_model, methodState, ...
            dtNominal, options.force_hard_invalid);
    elseif contract.use_robust
        [augmentation, methodState.robust, robustDiagnostic] = ...
            gpenmpcRobustSe3Augmentation(x, ref, assets.robust, ...
            methodState.robust, dtNominal);
        tangent = methodState.robust.last_tangent_xy;
        frame = [tangent(1), -tangent(2), 0; ...
            tangent(2), tangent(1), 0; 0, 0, 1];
        robustF = -robustDiagnostic.radius_f_mps2 ...
            .* tanh(robustDiagnostic.sliding_f_mps ...
            ./ double(assets.robust.robust_boundary_layer_mps(:)));
        augmentationDiagnostic = struct( ...
            "frame_i_from_f", frame, ...
            "support_distance", 0.0, ...
            "latent_variance_max", 0.0, ...
            "ood_score", 0.0, ...
            "hard_invalid", false, ...
            "fallback_active", false, ...
            "inference_seconds", 0.0, ...
            "trust_weight", 0.0, ...
            "gp_mean_f_mps2", zeros(3,1), ...
            "gp_std_f_mps2", zeros(3,1), ...
            "robust_acceleration_f_mps2", robustF, ...
            "applied_robust_radius_f_mps2", ...
                robustDiagnostic.radius_f_mps2, ...
            "rho_m2_total_f_mps2", robustDiagnostic.radius_f_mps2, ...
            "rho_m3_residual_f_mps2", robustDiagnostic.radius_f_mps2, ...
            "target_i_mps2", robustDiagnostic.target_i_mps2);
    else
        augmentation = zeros(3, 1);
        velocityXY = double(ref.velocity_mps(1:2));
        if norm(velocityXY) > 1.0e-9
            tangent = velocityXY ./ norm(velocityXY);
        else
            tangent = methodState.robust.last_tangent_xy;
        end
        frame = [tangent(1), -tangent(2), 0; ...
            tangent(2), tangent(1), 0; 0, 0, 1];
        augmentationDiagnostic = struct( ...
            "frame_i_from_f", frame, ...
            "support_distance", 0.0, ...
            "latent_variance_max", 0.0, ...
            "ood_score", 0.0, ...
            "hard_invalid", false, ...
            "fallback_active", false, ...
            "inference_seconds", 0.0, ...
            "trust_weight", 0.0, ...
            "gp_mean_f_mps2", zeros(3,1), ...
            "gp_std_f_mps2", zeros(3,1), ...
            "robust_acceleration_f_mps2", zeros(3,1), ...
            "applied_robust_radius_f_mps2", zeros(3,1), ...
            "rho_m2_total_f_mps2", zeros(3,1), ...
            "rho_m3_residual_f_mps2", zeros(3,1), ...
            "target_i_mps2", zeros(3,1));
    end
    [~, diagnostic] = evaluateClosedLoopDerivative(contract,x,ref, ...
        payloadKg,windActual,windEstimate,globalTimeS,augmentation, ...
        task.mission_config,assets.calibration,assets.profile, ...
        pidConfiguration,methodState,dtNominal);
    if contract.use_robust
        methodState.robust = gpenmpcRobustSe3ObserveControl( ...
            methodState.robust, diagnostic, dtNominal);
    end
    if contract.use_pid
        methodState.pid = gpenmpcUpdateCascadedPidState(methodState.pid, ...
            diagnostic,pidConfiguration,dtNominal,legIndex);
    end
    methodState = gpenmpcCommitFixedC3CausalHistory(methodState, x, ...
        diagnostic.nominal_acceleration_mps2, diagnostic.rotor_command_n, ...
        augmentationDiagnostic.frame_i_from_f, globalTimeS, legIndex, payloadKg);

    [controllerPowerW, powerDiagnostic] = ...
        gpenmpcM600ControllerSensitivePower(assets.profile, ...
        assets.calibration, payloadKg, x, ref, windActual, windEstimate);
    publicPowerW = double(powerDiagnostic.public_power_w);
    if isfinite(previousPowerTimeS)
        step = globalTimeS - previousPowerTimeS;
        if step > 1.0e-9 && step <= 0.0100001
            publicEnergyJ = publicEnergyJ + 0.5 .* step ...
                .* (previousPublicPowerW + publicPowerW);
            controllerEnergyJ = controllerEnergyJ + 0.5 .* step ...
                .* (previousControllerPowerW + controllerPowerW);
        end
    end
    trace = storeSample(trace, index, reference, x, diagnostic, ...
        augmentation, augmentationDiagnostic, publicPowerW, ...
        controllerPowerW, powerDiagnostic, publicEnergyJ, ...
        controllerEnergyJ);
    previousPublicPowerW = publicPowerW;
    previousControllerPowerW = controllerPowerW;
    previousPowerTimeS = globalTimeS;

    if index == sampleCount
        break
    end
    nextLeg = double(reference.leg_index(index + 1));
    if nextLeg == legIndex
        nextRef = sampleReference(reference, index + 1);
        step = double(reference.global_time_s(index + 1)) - globalTimeS;
        if step <= 1.0e-9 || step > 0.0100001
            error("gpenmpcRunFixedC3WholeTask:TimeStep", ...
                "Unexpected within-leg step %.12f s.", step);
        end
        midRef = midpointReference(ref, nextRef);
        nextWind = double(reference.actual_wind_xy_mps(index + 1, :)).';
        midWind = 0.5 .* (windActual + nextWind);
        k1 = evaluateClosedLoopDerivative(contract,x,ref,payloadKg, ...
            windActual,windEstimate,globalTimeS,augmentation, ...
            task.mission_config,assets.calibration,assets.profile, ...
            pidConfiguration,methodState,step);
        k2 = evaluateClosedLoopDerivative(contract,x+0.5.*step.*k1, ...
            midRef,payloadKg,midWind,windEstimate,globalTimeS+0.5.*step, ...
            augmentation,task.mission_config,assets.calibration, ...
            assets.profile,pidConfiguration,methodState,step);
        k3 = evaluateClosedLoopDerivative(contract,x+0.5.*step.*k2, ...
            midRef,payloadKg,midWind,windEstimate,globalTimeS+0.5.*step, ...
            augmentation,task.mission_config,assets.calibration, ...
            assets.profile,pidConfiguration,methodState,step);
        k4 = evaluateClosedLoopDerivative(contract,x+step.*k3, ...
            nextRef,payloadKg,nextWind,windEstimate,globalTimeS+step, ...
            augmentation,task.mission_config,assets.calibration, ...
            assets.profile,pidConfiguration,methodState,step);
        x = x + step .* (k1 + 2.0 .* k2 + 2.0 .* k3 + k4) ./ 6.0;
        x(7:10) = x(7:10) ./ max(norm(x(7:10)), 1.0e-15);
    else
        nextGlobalTimeS = double(reference.global_time_s(index + 1));
        serviceDurationS = nextGlobalTimeS - globalTimeS;
        payloadAfterKg = double(reference.payload_kg(index + 1));
        expectedGroundDurationS = expectedGroundServiceDuration( ...
            task, legIndex);
        [x, service] = gpenmpcApplyFixedC3ServiceTransition(x, payloadKg, ...
            payloadAfterKg, serviceDurationS, expectedGroundDurationS, ...
            double(reference.position_m(index + 1, :)).', assets.profile);
        service.after_leg_index = legIndex;
        service.start_time_s = globalTimeS;
        service.end_time_s = nextGlobalTimeS;
        serviceRecords(end + 1, 1) = service; %#ok<AGROW>
        publicEnergyJ = publicEnergyJ + service.public_energy_j;
        controllerEnergyJ = controllerEnergyJ ...
            + service.controller_sensitive_energy_j;
        methodState.previous_observation_valid = false;
        if contract.use_pid
            methodState.pid = gpenmpcResetCascadedPidState( ...
                methodState.pid,nextLeg);
        end
        previousPublicPowerW = NaN;
        previousControllerPowerW = NaN;
        previousPowerTimeS = NaN;
    end
end

trace.service_records = serviceRecords;
result = gpenmpcComputeFixedC3WholeTaskMetrics(trace, task, contract, ...
    methodState, sampleCount == availableCount);
end


function duration = expectedGroundServiceDuration(task, legIndex)
if ~isfield(task, "plans") || isempty(task.plans) ...
        || legIndex < 1 || legIndex > numel(task.plans(1).legs)
    error("gpenmpcRunFixedC3WholeTask:ServicePlan", ...
        "Reference service transition lacks a matching plan leg.");
end
service = task.plans(1).legs(legIndex).service;
if ~isfield(service, "ground_service_duration_s")
    error("gpenmpcRunFixedC3WholeTask:ServicePlan", ...
        "Matching plan leg lacks a task-defined ground dwell.");
end
duration = double(service.ground_service_duration_s);
end


function [derivative,diagnostic] = evaluateClosedLoopDerivative( ...
        contract,x,ref,payloadKg,windActual,windEstimate,globalTimeS, ...
        augmentation,mission,calibration,profile,pidConfiguration, ...
        methodState,dt)
if contract.use_pid
    [derivative,diagnostic] = ...
        gpenmpcM600CascadedPidClosedLoopDerivative(x,ref,payloadKg, ...
        windActual,windEstimate,globalTimeS,mission,calibration,profile, ...
        pidConfiguration,methodState.pid,dt);
else
    [derivative,diagnostic] = gpenmpcM600ClosedLoopDerivative(x,ref, ...
        payloadKg,windActual,windEstimate,globalTimeS,augmentation, ...
        mission,calibration,profile);
end
end


function diagnostic = zeroAugmentationDiagnostic(frame)
diagnostic = struct( ...
    "frame_i_from_f",frame,"support_distance",0.0, ...
    "latent_variance_max",0.0,"ood_score",0.0, ...
    "hard_invalid",false,"fallback_active",false, ...
    "inference_seconds",0.0,"trust_weight",0.0, ...
    "gp_mean_f_mps2",zeros(3,1),"gp_std_f_mps2",zeros(3,1), ...
    "robust_acceleration_f_mps2",zeros(3,1), ...
    "applied_robust_radius_f_mps2",zeros(3,1), ...
    "rho_m2_total_f_mps2",zeros(3,1), ...
    "rho_m3_residual_f_mps2",zeros(3,1), ...
    "target_i_mps2",zeros(3,1));
end


function trace = allocateTrace(count)
trace = struct;
vectors = ["global_time_s", "local_time_s", "leg_index", "phase_code", ...
    "payload_kg", "public_power_w", "controller_sensitive_power_w", ...
    "cumulative_public_energy_j", ...
    "cumulative_controller_sensitive_energy_j", "tilt_rad", ...
    "rotor_saturated", "force_projection_mismatch_n", "trust_weight", ...
    "ood_score", "hard_invalid", "fallback_active", ...
    "inference_seconds", "power_domain_status"];
for name = vectors
    trace.(name) = zeros(count, 1);
end
three = ["reference_position_m", "reference_velocity_mps", ...
    "reference_acceleration_mps2", "reference_jerk_mps3", ...
    "position_m", "velocity_mps", "body_rate_rad_s", ...
    "attitude_error_rad", "desired_force_projected_n", ...
    "actual_acceleration_mps2", "nominal_acceleration_mps2", ...
    "residual_acceleration_i_mps2", "augmentation_acceleration_i_mps2", ...
    "gp_mean_f_mps2", "gp_std_f_mps2", ...
    "robust_acceleration_f_mps2", "applied_robust_radius_f_mps2", ...
    "rho_m2_total_f_mps2", "rho_m3_residual_f_mps2"];
for name = three
    trace.(name) = zeros(count, 3);
end
trace.actual_wind_xy_mps = zeros(count, 2);
trace.wind_estimate_xy_mps = zeros(count, 2);
trace.quaternion_wxyz = zeros(count, 4);
trace.per_rotor_thrust_n = zeros(count, 6);
trace.rotor_command_n = zeros(count, 6);
end


function trace = storeSample(trace, index, reference, x, diagnostic, ...
        augmentation, aug, publicPowerW, controllerPowerW, power, ...
        publicEnergyJ, controllerEnergyJ)
trace.global_time_s(index) = reference.global_time_s(index);
trace.local_time_s(index) = reference.local_time_s(index);
trace.leg_index(index) = reference.leg_index(index);
trace.phase_code(index) = reference.phase_code(index);
trace.payload_kg(index) = reference.payload_kg(index);
trace.reference_position_m(index,:) = reference.position_m(index,:);
trace.reference_velocity_mps(index,:) = reference.velocity_mps(index,:);
trace.reference_acceleration_mps2(index,:) = reference.acceleration_mps2(index,:);
trace.reference_jerk_mps3(index,:) = reference.jerk_mps3(index,:);
trace.actual_wind_xy_mps(index,:) = reference.actual_wind_xy_mps(index,:);
trace.wind_estimate_xy_mps(index,:) = reference.wind_estimate_xy_mps(index,:);
trace.position_m(index,:) = x(1:3).';
trace.velocity_mps(index,:) = x(4:6).';
trace.quaternion_wxyz(index,:) = (x(7:10) ./ max(norm(x(7:10)),1e-15)).';
trace.body_rate_rad_s(index,:) = x(11:13).';
trace.per_rotor_thrust_n(index,:) = x(14:19).';
trace.rotor_command_n(index,:) = diagnostic.rotor_command_n.';
trace.attitude_error_rad(index,:) = diagnostic.attitude_error.';
trace.desired_force_projected_n(index,:) = diagnostic.desired_force_projected_n.';
trace.actual_acceleration_mps2(index,:) = diagnostic.actual_acceleration_mps2.';
trace.nominal_acceleration_mps2(index,:) = diagnostic.nominal_acceleration_mps2.';
trace.residual_acceleration_i_mps2(index,:) = diagnostic.residual_acceleration_mps2.';
trace.augmentation_acceleration_i_mps2(index,:) = augmentation.';
trace.gp_mean_f_mps2(index,:) = aug.gp_mean_f_mps2.';
trace.gp_std_f_mps2(index,:) = aug.gp_std_f_mps2.';
trace.robust_acceleration_f_mps2(index,:) = aug.robust_acceleration_f_mps2.';
trace.applied_robust_radius_f_mps2(index,:) = ...
    aug.applied_robust_radius_f_mps2.';
trace.rho_m2_total_f_mps2(index,:) = aug.rho_m2_total_f_mps2.';
trace.rho_m3_residual_f_mps2(index,:) = aug.rho_m3_residual_f_mps2.';
trace.public_power_w(index) = publicPowerW;
trace.controller_sensitive_power_w(index) = controllerPowerW;
trace.cumulative_public_energy_j(index) = publicEnergyJ;
trace.cumulative_controller_sensitive_energy_j(index) = controllerEnergyJ;
trace.tilt_rad(index) = diagnostic.tilt_rad;
trace.rotor_saturated(index) = diagnostic.rotor_saturated;
trace.force_projection_mismatch_n(index) = ...
    diagnostic.force_projection_norm_mismatch_n;
trace.trust_weight(index) = aug.trust_weight;
trace.ood_score(index) = aug.ood_score;
trace.hard_invalid(index) = aug.hard_invalid;
trace.fallback_active(index) = aug.fallback_active;
trace.inference_seconds(index) = aug.inference_seconds;
trace.power_domain_status(index) = double(power.power_domain_status_code);
end


function ref = sampleReference(reference, index)
ref = struct( ...
    "position_m", double(reference.position_m(index, :)).', ...
    "velocity_mps", double(reference.velocity_mps(index, :)).', ...
    "acceleration_mps2", double(reference.acceleration_mps2(index, :)).', ...
    "jerk_mps3", double(reference.jerk_mps3(index, :)).');
end


function ref = midpointReference(left, right)
ref = struct( ...
    "position_m", 0.5 .* (left.position_m + right.position_m), ...
    "velocity_mps", 0.5 .* (left.velocity_mps + right.velocity_mps), ...
    "acceleration_mps2", 0.5 .* (left.acceleration_mps2 + right.acceleration_mps2), ...
    "jerk_mps3", 0.5 .* (left.jerk_mps3 + right.jerk_mps3));
end
