function result = gpenmpcEvaluateOrdinaryB2RolloutLegacyBaseline(decision, method, trajectory, phaseState, observation, context, gpModel, causalContextF17, config)
%GPENMPCEVALUATEORDINARYB2ROLLOUTLEGACYBASELINE Read-only authority baseline.
%
% Ordinary B2 uses the full GP mean (scale one) in translational prediction
% and the same total robust tube as B1. GP variance is used only to compute
% support, trust and hard-invalid status. No N1 tightening and no B2R1 mean
% attenuation or extra acceleration reserve are present.

arguments
    decision (1,:) double
    method (1,1) string
    trajectory (1,1) struct
    phaseState (1,1) struct
    observation (1,1) struct
    context (1,1) struct
    gpModel struct
    causalContextF17 (1,1) struct
    config (1,1) struct
end
validateIdentity(method, decision, context, config);
isB2 = method == config.method;
if isB2 && isempty(fieldnames(gpModel))
    error("gpenmpcEvaluateOrdinaryB2Rollout:Model", ...
        "Ordinary B2 requires the frozen native sparse GP model.");
end

dt = config.prediction_step_s;
phaseBlocks = decision(1:config.control_blocks);
outerCorrectionF = decision(config.control_blocks + (1:3)).';
controls = repelem(phaseBlocks, config.move_block_size);
p = column(observation.position_m, 3, "position_m");
v = column(observation.velocity_mps, 3, "velocity_mps");
phase = double(phaseState.progress_s);
rate = double(phaseState.progress_rate);
previousPhaseAcceleration = double(phaseState.previous_phase_acceleration_s_inv);
previousForce = column(observation.previous_desired_force_n, 3, "previous_desired_force_n");
previousOuterCorrectionI = column( ...
    observation.previous_outer_acceleration_correction_i_mps2, 3, ...
    "previous_outer_acceleration_correction_i_mps2");
wind3 = [column(observation.wind_estimate_xy_mps, 2, "wind_estimate_xy_mps"); 0.0];
payloadKg = double(observation.payload_kg);
column(observation.body_rate_rad_s, 3, "body_rate_rad_s");
mass = context.base_mass_kg + payloadKg;
sigmaP = zeros(3, 1);
sigmaV = zeros(3, 1);
hardInvalid = false;
currentHardInvalid = false;
terminalExecutionPower = 0.0;
expectedTerminalPhase = min(trajectory.total_duration_s, ...
    phase + config.horizon_steps .* dt);
initialPhase = phase;
if isfield(causalContextF17, "values")
    predictedContext = double(causalContextF17.values(:));
else
    predictedContext = [1.0; 0.0; 0.0; 0.0];
end
contextValid = isfield(causalContextF17, "valid") ...
    && logical(causalContextF17.valid) && numel(predictedContext) == 4 ...
    && all(isfinite(predictedContext));

initialReference = gpenmpcPhaseReference(trajectory, phase, rate, ...
    previousPhaseAcceleration, 0.0);
initialReference.acceleration_mps2 = ...
    initialReference.acceleration_mps2 + previousOuterCorrectionI;
initialAir = initialReference.velocity_mps - wind3;
initialDrag = context.nominal_drag_n_per_mps2(:) .* initialAir .* abs(initialAir);
initialTrackingAcceleration = initialReference.acceleration_mps2 ...
    + context.position_gain_s2(:) .* (initialReference.position_m - p) ...
    + context.velocity_gain_s(:) .* (initialReference.velocity_mps - v);
initialForceWithoutRobust = mass .* (initialTrackingAcceleration ...
    + [0.0; 0.0; context.gravity_mps2]) + initialDrag;
predictedCommonRobustI = clipNorm( ...
    (previousForce - initialForceWithoutRobust) ./ mass, ...
    config.raw.common_inner_loop_predictor.combined_cap_mps2);

stageRows = repmat(stageTemplate(config), config.horizon_steps, 1);
diagnosticRows = repmat(diagnosticTemplate(), config.horizon_steps, 1);
for index = 1:config.horizon_steps
    targetPhaseAcceleration = controls(index);
    transition = gpenmpcJerkBoundedReferenceTransition(trajectory, phase, rate, ...
        previousPhaseAcceleration, targetPhaseAcceleration, ...
        previousOuterCorrectionI, outerCorrectionF, dt, ...
        config.reference_transition_jerk_limit_mps3);
    reference = transition.reference;
    referenceAir = reference.velocity_mps - wind3;
    dragFeedforward = context.nominal_drag_n_per_mps2(:) ...
        .* referenceAir .* abs(referenceAir);
    trackingAcceleration = reference.acceleration_mps2 ...
        + context.position_gain_s2(:) .* (reference.position_m - p) ...
        + context.velocity_gain_s(:) .* (reference.velocity_mps - v);
    robustFrame = transition.reference_frame_i_from_f;
    curvature = transition.reference_curvature;
    slidingI = v - reference.velocity_mps ...
        + config.raw.common_inner_loop_predictor.lambda_position_s_inv(:) ...
        .* (p - reference.position_m);
    desiredForceForFeature = mass .* (trackingAcceleration ...
        + predictedCommonRobustI + [0.0; 0.0; context.gravity_mps2]) ...
        + dragFeedforward;

    meanI = zeros(3, 1);
    meanF = zeros(3, 1);
    halfWidthF = zeros(3, 1);
    trust = 0.0;
    supportDistance = 0.0;
    latentMaximum = 0.0;
    sampleInvalid = false;
    gpFrame = robustFrame;
    if isB2
        sampleInvalid = ~contextValid;
        if ~sampleInvalid
            features = buildAeroF17(v, reference, robustFrame, wind3, payloadKg, ...
                desiredForceForFeature, curvature, ...
                predictedContext, context);
            prediction = gpenmpcSparseGpPredict(gpModel, features.');
            meanF = prediction.mean_mps2(1, :).';
            halfWidthF = prediction.calibrated_half_width_mps2(1, :).';
            trust = double(prediction.trust(1));
            supportDistance = double(prediction.support_distance(1));
            latentMaximum = max(prediction.latent_variance_standardized(1, :));
            sampleInvalid = logical(prediction.hard_invalid(1));
            if sampleInvalid
                trust = 0.0;
                meanF = zeros(3, 1);
            end
            meanI = gpFrame * (config.gp_mean_scale .* trust .* meanF);
        end
        hardInvalid = hardInvalid || sampleInvalid;
        if index == 1
            currentHardInvalid = sampleInvalid;
        end
    end

    totalRadiusF = config.common_robust_total_radius_f_mps2(:);
    robustTargetF = -totalRadiusF .* tanh( ...
        (robustFrame.' * slidingI) ...
        ./ config.raw.common_inner_loop_predictor.boundary_layer_mps(:));
    robustTargetI = robustFrame * robustTargetF;
    filterGain = 1.0 - exp(-dt ...
        ./ config.raw.common_inner_loop_predictor.filter_time_constant_s);
    robustLowPass = predictedCommonRobustI ...
        + filterGain .* (robustTargetI - predictedCommonRobustI);
    robustDelta = clipNorm(robustLowPass - predictedCommonRobustI, ...
        config.raw.common_inner_loop_predictor.slew_limit_mps3 .* dt);
    predictedCommonRobustI = clipNorm(predictedCommonRobustI + robustDelta, ...
        config.raw.common_inner_loop_predictor.combined_cap_mps2);
    desiredForce = mass .* (trackingAcceleration + predictedCommonRobustI ...
        + [0.0; 0.0; context.gravity_mps2]) + dragFeedforward;
    predictedAcceleration = trackingAcceleration + predictedCommonRobustI + meanI;

    if isB2 && ~sampleInvalid
        normalizedThrust = norm(desiredForce, 2) ...
            ./ max(mass .* context.gravity_mps2, 1.0e-12);
        predictedContext(1) = min(max(normalizedThrust, 0.0), 2.0);
        meanFForHistory = gpFrame.' * meanI;
        historyGain = 1.0 - exp(-dt ./ 0.50);
        predictedContext(2:4) = predictedContext(2:4) ...
            + historyGain .* (meanFForHistory - predictedContext(2:4));
    end

    accelerationUncertainty = zeros(3, 1); % ordinary B2 is not N1
    nextSigmaV = sqrt(sigmaV.^2 + (dt .* accelerationUncertainty).^2);
    nextSigmaP = sqrt(sigmaP.^2 + (dt .* sigmaV).^2 ...
        + (0.5 .* dt.^2 .* accelerationUncertainty).^2);
    nextP = p + dt .* v + 0.5 .* dt.^2 .* predictedAcceleration;
    nextV = v + dt .* predictedAcceleration;
    nextRate = rate + dt .* transition.phase_acceleration_s_inv;
    nextPhase = phase + dt .* rate ...
        + 0.5 .* dt.^2 .* transition.phase_acceleration_s_inv;
    nextPhase = min(nextPhase, trajectory.total_duration_s);

    airspeed = norm(v - wind3, 2);
    [publicPower, powerStatus] = phasePower(context, airspeed, payloadKg, v(3));
    uniformRotor = repmat(norm(desiredForce, 2) ./ 6.0, 1, 6);
    nominalReferenceForce = mass .* (reference.acceleration_mps2 ...
        + [0.0; 0.0; context.gravity_mps2]) + dragFeedforward;
    executionPower = gpenmpcEnmpcStageControllerSensitivePower(publicPower, uniformRotor, ...
        norm(nominalReferenceForce, 2), context.rotor_diameter_m);
    stageEnergy = dt .* executionPower;
    terminalExecutionPower = executionPower;

    positionError = reference.position_m - p;
    velocityError = reference.velocity_mps - v;
    forceVariation = desiredForce - previousForce;
    jerkNorm = norm(reference.jerk_mps3, 2);
    progressDeficit = max(0.0, expectedTerminalPhase - nextPhase);
    positionRadius = norm(nextSigmaP, 2);
    accelerationRadius = norm(accelerationUncertainty, 2);
    forceRadius = mass .* accelerationRadius;
    tilt = atan2(norm(desiredForce(1:2), 2), max(desiredForce(3), 1.0e-9));
    uniformRotorLoad = (norm(desiredForce, 2) + forceRadius) ./ 6.0;
    nextReferencePosition = gpenmpcEvaluateTrajectoryDerivative(trajectory, nextPhase, 0);
    nextReferenceVelocity = gpenmpcEvaluateTrajectoryDerivative(trajectory, nextPhase, 1) .* nextRate;
    predictedNextPositionError = norm(nextReferencePosition - nextP, 2);
    predictedNextVelocityError = norm(nextReferenceVelocity - nextV, 2);
    nominalAccelerationBudget = config.acceleration_screen_mps2 ...
        - config.common_inner_loop_acceleration_reserve_mps2 ...
        - config.additional_prediction_acceleration_reserve_mps2;
    nominalRotorLoad = norm(desiredForce, 2) ./ 6.0;
    corridor = min(config.corridor_half_width_m, ...
        optionalScalar(observation, "corridor_half_width_m", config.corridor_half_width_m));
    hardMargins = [ ...
        nextRate - config.phase_rate_min, ...
        config.phase_rate_max - nextRate, ...
        nextPhase, trajectory.total_duration_s - nextPhase, ...
        corridor - predictedNextPositionError, ...
        config.position_screen_m - predictedNextPositionError, ...
        config.velocity_screen_mps - predictedNextVelocityError, ...
        nominalAccelerationBudget - norm(predictedAcceleration, 2), ...
        config.jerk_screen_mps3 - jerkNorm, ...
        context.maximum_total_thrust_n - norm(desiredForce, 2), ...
        context.maximum_per_rotor_thrust_n - nominalRotorLoad, ...
        context.maximum_tilt_rad - tilt, ...
        context.airspeed_max_mps - airspeed, ...
        ternary(powerStatus ~= 2, 1.0, -1.0), ...
        config.outer_acceleration_correction_max_mps2 - norm(outerCorrectionF, 2)];
    riskMargins = [ ...
        (corridor - predictedNextPositionError - positionRadius) ./ max(corridor, 1.0e-9), ...
        (config.position_screen_m - predictedNextPositionError - positionRadius) ...
            ./ config.position_screen_m, ...
        (config.velocity_screen_mps - predictedNextVelocityError - norm(nextSigmaV, 2)) ...
            ./ config.velocity_screen_mps, ...
        (nominalAccelerationBudget - norm(predictedAcceleration, 2) - accelerationRadius) ...
            ./ nominalAccelerationBudget, ...
        (context.maximum_total_thrust_n - norm(desiredForce, 2) - forceRadius) ...
            ./ context.maximum_total_thrust_n, ...
        (context.maximum_per_rotor_thrust_n - uniformRotorLoad) ...
            ./ context.maximum_per_rotor_thrust_n];

    stageRows(index) = struct( ...
        "stage_energy_j", stageEnergy, ...
        "position_error_norm_m", norm(positionError, 2), ...
        "velocity_error_norm_mps", norm(velocityError, 2), ...
        "force_variation_norm_n", norm(forceVariation, 2), ...
        "reference_jerk_norm_mps3", jerkNorm, ...
        "phase_acceleration_s_inv", transition.phase_acceleration_s_inv, ...
        "phase_jerk_s_inv2", transition.phase_jerk_s_inv2, ...
        "progress_deficit_s", progressDeficit, ...
        "predicted_next_position_error_m", predictedNextPositionError, ...
        "predicted_next_velocity_error_mps", predictedNextVelocityError, ...
        "trust", trust, ...
        "hard_constraints", hardMargins, ...
        "risk_constraints_normalized", riskMargins);
    diagnosticRows(index) = struct( ...
        "horizon_index", index - 1, ...
        "progress_s", phase, ...
        "progress_rate", rate, ...
        "reference_position_m", reference.position_m.', ...
        "reference_velocity_mps", reference.velocity_mps.', ...
        "reference_acceleration_mps2", reference.acceleration_mps2.', ...
        "reference_jerk_mps3", reference.jerk_mps3.', ...
        "predicted_position_m", p.', ...
        "predicted_velocity_mps", v.', ...
        "predicted_acceleration_mps2", predictedAcceleration.', ...
        "predicted_common_robust_acceleration_i_mps2", predictedCommonRobustI.', ...
        "desired_force_n", desiredForce.', ...
        "gp_mean_f_mps2", meanF.', ...
        "gp_mean_i_mps2", meanI.', ...
        "calibrated_half_width_f_mps2", halfWidthF.', ...
        "trust", trust, ...
        "hard_invalid", sampleInvalid, ...
        "support_distance", supportDistance, ...
        "latent_variance_max", latentMaximum, ...
        "stage_energy_j", stageEnergy, ...
        "power_domain_status", powerStatus, ...
        "outer_transition_fraction", transition.fraction);
    p = nextP;
    v = nextV;
    phase = nextPhase;
    rate = nextRate;
    sigmaP = nextSigmaP;
    sigmaV = nextSigmaV;
    previousForce = desiredForce;
    previousPhaseAcceleration = transition.phase_acceleration_s_inv;
    previousOuterCorrectionI = transition.outer_correction_i_mps2;
end

remainingDuration = max(0.0, trajectory.total_duration_s - phase) ...
    ./ max(rate, config.phase_rate_min);
terminalEnergyToGo = terminalExecutionPower .* remainingDuration;
result = gpenmpcBookkeepEnmpcRollout(stageRows, terminalEnergyToGo, ...
    hardInvalid, currentHardInvalid, config);
result.terminal_progress_s = phase;
result.initial_progress_s = initialPhase;
result.stage_rows = stageRows;
result.rows = diagnosticRows;
result.predicted_causal_context_terminal = predictedContext.';
result.method = method;
result.gp_mean_scale = config.gp_mean_scale;
result.robust_tube_identity = config.robust_tube_identity;
result.n1_or_b2r1_active = false;
end


function features = buildAeroF17(velocityI, reference, frameIFromF, wind3, payloadKg, desiredForce, curvature, history, context)
airF = frameIFromF.' * (velocityI - wind3);
referenceAccelerationF = frameIFromF.' * reference.acceleration_mps2;
verticalForce = max(desiredForce(3), 1.0e-9);
tilt = atan2(norm(desiredForce(1:2), 2), verticalForce);
payloadFraction = payloadKg ./ context.maximum_payload_kg;
speed = norm(airF, 2);
tiltFactor = 1.0 + 0.35 .* sin(tilt).^2;
dragT = payloadFraction .* tiltFactor .* airF(1) .* abs(airF(1));
dragN = payloadFraction .* tiltFactor .* airF(2) .* abs(airF(2));
turn = curvature .* airF(1) .* abs(airF(1)) ...
    + airF(2) .* abs(airF(1));
previousCommand = history(1);
verticalDemand = max(0.0, 1.0 + referenceAccelerationF(3) ./ context.gravity_mps2);
thrustLoad = previousCommand .* (1.0 + payloadFraction) .* verticalDemand;
features = [payloadFraction; airF; speed; dragT; dragN; turn; ...
    referenceAccelerationF; tilt; previousCommand; thrustLoad; history(2:4)];
if numel(features) ~= 17 || any(~isfinite(features))
    error("gpenmpcEvaluateOrdinaryB2Rollout:Features", ...
        "AERO_PHYSICS_F17 must contain 17 finite causal features.");
end
end


function [powerW, status] = phasePower(context, airspeed, payloadKg, verticalSpeed)
if verticalSpeed > 0.10
    powerW = context.phase_power_fcn("ASCEND", context.airspeed_min_mps, payloadKg);
    status = 3;
elseif verticalSpeed < -0.10
    powerW = context.phase_power_fcn("DESCEND", context.airspeed_min_mps, payloadKg);
    status = 3;
elseif airspeed < 0.20
    powerW = context.phase_power_fcn("HOVER", context.airspeed_min_mps, payloadKg);
    status = 3;
elseif airspeed < context.airspeed_min_mps
    hover = context.phase_power_fcn("HOVER", context.airspeed_min_mps, payloadKg);
    forward = context.phase_power_fcn("FORWARD", context.airspeed_min_mps, payloadKg);
    blend = min(max(airspeed ./ context.airspeed_min_mps, 0.0), 1.0);
    powerW = (1.0 - blend) .* hover + blend .* forward;
    status = 1;
elseif airspeed <= context.airspeed_max_mps + 1.0e-10
    powerW = context.phase_power_fcn("FORWARD", ...
        min(airspeed, context.airspeed_max_mps), payloadKg);
    status = 0;
else
    powerW = context.phase_power_fcn("FORWARD", context.airspeed_max_mps, payloadKg);
    status = 2;
end
powerW = double(powerW);
end


function clipped = clipNorm(vector, maximumNorm)
vector = double(vector(:));
vectorNorm = norm(vector, 2);
if vectorNorm > maximumNorm
    clipped = vector .* (maximumNorm ./ max(vectorNorm, 1.0e-15));
else
    clipped = vector;
end
end


function row = stageTemplate(config)
row = struct( ...
    "stage_energy_j", 0.0, ...
    "position_error_norm_m", 0.0, ...
    "velocity_error_norm_mps", 0.0, ...
    "force_variation_norm_n", 0.0, ...
    "reference_jerk_norm_mps3", 0.0, ...
    "phase_acceleration_s_inv", 0.0, ...
    "phase_jerk_s_inv2", 0.0, ...
    "progress_deficit_s", 0.0, ...
    "predicted_next_position_error_m", 0.0, ...
    "predicted_next_velocity_error_mps", 0.0, ...
    "trust", 0.0, ...
    "hard_constraints", ones(1, config.hard_constraints_per_step), ...
    "risk_constraints_normalized", ones(1, config.risk_constraints_per_step));
end


function row = diagnosticTemplate()
row = struct( ...
    "horizon_index", 0, ...
    "progress_s", 0.0, ...
    "progress_rate", 0.0, ...
    "reference_position_m", zeros(1, 3), ...
    "reference_velocity_mps", zeros(1, 3), ...
    "reference_acceleration_mps2", zeros(1, 3), ...
    "reference_jerk_mps3", zeros(1, 3), ...
    "predicted_position_m", zeros(1, 3), ...
    "predicted_velocity_mps", zeros(1, 3), ...
    "predicted_acceleration_mps2", zeros(1, 3), ...
    "predicted_common_robust_acceleration_i_mps2", zeros(1, 3), ...
    "desired_force_n", zeros(1, 3), ...
    "gp_mean_f_mps2", zeros(1, 3), ...
    "gp_mean_i_mps2", zeros(1, 3), ...
    "calibrated_half_width_f_mps2", zeros(1, 3), ...
    "trust", 0.0, ...
    "hard_invalid", false, ...
    "support_distance", 0.0, ...
    "latent_variance_max", 0.0, ...
    "stage_energy_j", 0.0, ...
    "power_domain_status", 0, ...
    "outer_transition_fraction", 0.0);
end


function value = column(input, count, name)
value = double(input(:));
if numel(value) ~= count || any(~isfinite(value))
    error("gpenmpcEvaluateOrdinaryB2Rollout:Input", ...
        "%s must contain %d finite values.", name, count);
end
end


function value = optionalScalar(source, name, fallback)
if isfield(source, name)
    value = double(source.(name));
else
    value = double(fallback);
end
end


function value = ternary(condition, trueValue, falseValue)
if condition
    value = trueValue;
else
    value = falseValue;
end
end


function validateIdentity(method, decision, context, config)
if method ~= config.method && method ~= config.b1_fallback_method
    error("gpenmpcEvaluateOrdinaryB2Rollout:Method", ...
        "Only B1 and ordinary B2 are supported.");
end
if numel(decision) ~= config.decision_dimension || any(~isfinite(decision))
    error("gpenmpcEvaluateOrdinaryB2Rollout:Decision", ...
        "Decision must be one finite 7D vector.");
end
requiredContext = ["base_mass_kg", "gravity_mps2", "position_gain_s2", ...
    "velocity_gain_s", "nominal_drag_n_per_mps2", "maximum_payload_kg", ...
    "maximum_total_thrust_n", "maximum_per_rotor_thrust_n", ...
    "maximum_tilt_rad", "rotor_diameter_m", "airspeed_min_mps", ...
    "airspeed_max_mps", "phase_power_fcn"];
for name = requiredContext
    if ~isfield(context, name)
        error("gpenmpcEvaluateOrdinaryB2Rollout:Context", ...
            "Prediction context is missing %s.", name);
    end
end
if abs(config.gp_mean_scale - 1.0) > 1.0e-12 ...
        || config.additional_prediction_acceleration_reserve_mps2 ~= 0.0 ...
        || config.n1_residual_tube_enabled || config.b2r1_enabled
    error("gpenmpcEvaluateOrdinaryB2Rollout:Identity", ...
        "The rollout left the ordinary-B2 method identity.");
end
end
