/****************************************************************************
 *
 *   Copyright (C) 2013-2022 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file /tmp/gpenmpc_fmuv6c_20260924/px4/msg/GPENMPCShadowSuggestion.msg */


#pragma once


#include <uORB/uORB.h>


#ifndef __cplusplus

#endif


#ifdef __cplusplus
struct __EXPORT g_p_e_n_m_p_c_shadow_suggestion_s {
#else
struct g_p_e_n_m_p_c_shadow_suggestion_s {
#endif
	uint64_t timestamp;
	uint32_t sequence;
	uint32_t source_hash[8];
	uint32_t profile_hash[8];
	float predicted_position_risk_m;
	float predicted_acceleration_risk_mps2;
	float predicted_jerk_risk_mps3;
	float recoverability_margin;
	float proposed_progress_rate;
	float proposed_position_ned_m[3];
	float proposed_velocity_ned_mps[3];
	float proposed_acceleration_ned_mps2[3];
	float proposed_yaw_rad;
	float proposed_yaw_rate_rad_s;
	bool proposed;
	bool shadow_authorized;
	bool shadow_rejected;
	bool shadow_locked;
	bool shadow_released;
	uint8_t _padding0[7]; // required for logger


#ifdef __cplusplus

#endif
};

#ifdef __cplusplus
namespace px4 {
	namespace msg {
		using GPENMPCShadowSuggestion = g_p_e_n_m_p_c_shadow_suggestion_s;
	} // namespace msg
} // namespace px4
#endif

/* register this as object request broker structure */
ORB_DECLARE(gpenmpc_shadow_suggestion);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const g_p_e_n_m_p_c_shadow_suggestion_s& message);
#endif
