/****************************************************************************
 *
 *   Copyright (C) 2013-2022 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file /tmp/gpenmpc_fmuv6c_20260924/px4/msg/GPENMPCGroundObservabilityStatus.msg */


#pragma once


#include <uORB/uORB.h>


#ifndef __cplusplus
#define G_P_E_N_M_P_C_GROUND_OBSERVABILITY_STATUS_STATE_UNCALIBRATED 0
#define G_P_E_N_M_P_C_GROUND_OBSERVABILITY_STATUS_STATE_CALIBRATING 1
#define G_P_E_N_M_P_C_GROUND_OBSERVABILITY_STATUS_STATE_VALID 2
#define G_P_E_N_M_P_C_GROUND_OBSERVABILITY_STATUS_STATE_DEGRADED 3
#define G_P_E_N_M_P_C_GROUND_OBSERVABILITY_STATUS_STATE_HARD_FAULT 4
#define G_P_E_N_M_P_C_GROUND_OBSERVABILITY_STATUS_REASON_NONE 0
#define G_P_E_N_M_P_C_GROUND_OBSERVABILITY_STATUS_REASON_BASELINE_INCOMPLETE 1
#define G_P_E_N_M_P_C_GROUND_OBSERVABILITY_STATUS_REASON_UNSAFE_BASELINE_STATE 2
#define G_P_E_N_M_P_C_GROUND_OBSERVABILITY_STATUS_REASON_NONFINITE_SAMPLE 3
#define G_P_E_N_M_P_C_GROUND_OBSERVABILITY_STATUS_REASON_TIMESTAMP_DUPLICATE 4
#define G_P_E_N_M_P_C_GROUND_OBSERVABILITY_STATUS_REASON_TIMESTAMP_REGRESSION 5
#define G_P_E_N_M_P_C_GROUND_OBSERVABILITY_STATUS_REASON_TIMESTAMP_FUTURE 6
#define G_P_E_N_M_P_C_GROUND_OBSERVABILITY_STATUS_REASON_SAMPLE_STALE 7
#define G_P_E_N_M_P_C_GROUND_OBSERVABILITY_STATUS_REASON_RESET_AFTER_BASELINE 8
#define G_P_E_N_M_P_C_GROUND_OBSERVABILITY_STATUS_REASON_STREAM_DISAGREEMENT 9
#define G_P_E_N_M_P_C_GROUND_OBSERVABILITY_STATUS_REASON_INVALID_VERTICAL_STATE 10

#endif


#ifdef __cplusplus
struct __EXPORT g_p_e_n_m_p_c_ground_observability_status_s {
#else
struct g_p_e_n_m_p_c_ground_observability_status_s {
#endif
	uint64_t timestamp;
	uint64_t baro_timestamp_sample;
	uint64_t gps_timestamp_sample;
	uint32_t baro_baseline_samples;
	uint32_t gps_baseline_samples;
	uint32_t vertical_reset_counter;
	float baro_altitude_m;
	float gps_altitude_m;
	float baro_baseline_m;
	float gps_baseline_m;
	float baro_relative_height_m;
	float gps_relative_height_m;
	float gps_vertical_velocity_d_mps;
	float vertical_velocity_d_mps;
	float vertical_velocity_lower_d_mps;
	float vertical_velocity_upper_d_mps;
	float height_center_m;
	float height_lower_m;
	float height_upper_m;
	float baro_age_s;
	float gps_age_s;
	float baro_height_bound_m;
	float gps_height_bound_m;
	float gps_advertised_epv_m;
	float gps_vertical_velocity_bound_mps;
	float local_position_d_m;
	float local_velocity_d_mps;
	float reference_position_offset_target_m;
	float reference_position_offset_applied_m;
	float reference_position_offset_rate_mps;
	float reference_velocity_offset_target_mps;
	float reference_velocity_offset_applied_mps;
	float reference_velocity_offset_rate_mps2;
	uint8_t state;
	uint8_t reason;
	bool usable;
	bool baseline_locked;
	bool safe_baseline_state;
	bool baro_fresh;
	bool gps_fresh;
	bool interval_consistent;
	bool velocity_usable;
	bool precise_hil_sensor_contract;
	bool plant_truth_used;
	bool reference_alignment_active;
	bool reference_alignment_hard_fault;
	uint8_t _padding0[3]; // required for logger


#ifdef __cplusplus
	static constexpr uint8_t STATE_UNCALIBRATED = 0;
	static constexpr uint8_t STATE_CALIBRATING = 1;
	static constexpr uint8_t STATE_VALID = 2;
	static constexpr uint8_t STATE_DEGRADED = 3;
	static constexpr uint8_t STATE_HARD_FAULT = 4;
	static constexpr uint8_t REASON_NONE = 0;
	static constexpr uint8_t REASON_BASELINE_INCOMPLETE = 1;
	static constexpr uint8_t REASON_UNSAFE_BASELINE_STATE = 2;
	static constexpr uint8_t REASON_NONFINITE_SAMPLE = 3;
	static constexpr uint8_t REASON_TIMESTAMP_DUPLICATE = 4;
	static constexpr uint8_t REASON_TIMESTAMP_REGRESSION = 5;
	static constexpr uint8_t REASON_TIMESTAMP_FUTURE = 6;
	static constexpr uint8_t REASON_SAMPLE_STALE = 7;
	static constexpr uint8_t REASON_RESET_AFTER_BASELINE = 8;
	static constexpr uint8_t REASON_STREAM_DISAGREEMENT = 9;
	static constexpr uint8_t REASON_INVALID_VERTICAL_STATE = 10;

#endif
};

#ifdef __cplusplus
namespace px4 {
	namespace msg {
		using GPENMPCGroundObservabilityStatus = g_p_e_n_m_p_c_ground_observability_status_s;
	} // namespace msg
} // namespace px4
#endif

/* register this as object request broker structure */
ORB_DECLARE(gpenmpc_ground_observability_status);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const g_p_e_n_m_p_c_ground_observability_status_s& message);
#endif
