/****************************************************************************
 *
 *   Copyright (C) 2013-2022 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file /tmp/gpenmpc_fmuv6c_20260924/px4/msg/GPENMPCHteArbitrationStatus.msg */


#pragma once


#include <uORB/uORB.h>


#ifndef __cplusplus
#define G_P_E_N_M_P_C_HTE_ARBITRATION_STATUS_FAULT_NONE 0
#define G_P_E_N_M_P_C_HTE_ARBITRATION_STATUS_FAULT_GENERATION_DUPLICATE 1
#define G_P_E_N_M_P_C_HTE_ARBITRATION_STATUS_FAULT_GENERATION_REGRESSION 2
#define G_P_E_N_M_P_C_HTE_ARBITRATION_STATUS_FAULT_PUBLICATION_TIMESTAMP_REGRESSION 3
#define G_P_E_N_M_P_C_HTE_ARBITRATION_STATUS_FAULT_PUBLICATION_TIMESTAMP_FUTURE 4
#define G_P_E_N_M_P_C_HTE_ARBITRATION_STATUS_FAULT_SAMPLE_TIMESTAMP_REGRESSION 5
#define G_P_E_N_M_P_C_HTE_ARBITRATION_STATUS_FAULT_RESET_EPOCH_INCONSISTENT 6
#define G_P_E_N_M_P_C_HTE_ARBITRATION_STATUS_FAULT_VALID_SAMPLE_NONFINITE 7
#define G_P_E_N_M_P_C_HTE_ARBITRATION_STATUS_FAULT_COVARIANCE_NOT_PSD 8
#define G_P_E_N_M_P_C_HTE_ARBITRATION_STATUS_FAULT_SAME_SAMPLE_VALUE_CONFLICT 9
#define G_P_E_N_M_P_C_HTE_ARBITRATION_STATUS_FAULT_INVALID_ONLY_DT_TOO_SMALL 10
#define G_P_E_N_M_P_C_HTE_ARBITRATION_STATUS_FAULT_MALFORMED_INVALID 11
#define G_P_E_N_M_P_C_HTE_ARBITRATION_STATUS_FAULT_GROUP_TIMEOUT 12
#define G_P_E_N_M_P_C_HTE_ARBITRATION_STATUS_FAULT_SOURCE_FAILURE_IDENTITY 13
#define G_P_E_N_M_P_C_HTE_ARBITRATION_STATUS_FAULT_GENERATION_GAP 14

#endif


#ifdef __cplusplus
struct __EXPORT g_p_e_n_m_p_c_hte_arbitration_status_s {
#else
struct g_p_e_n_m_p_c_hte_arbitration_status_s {
#endif
	uint64_t timestamp;
	uint64_t pending_group_timestamp;
	uint64_t last_resolved_timestamp;
	uint64_t last_valid_sample_timestamp;
	uint64_t last_verified_publication_timestamp;
	uint64_t last_verified_sample_timestamp;
	uint64_t last_bounded_dropout_timestamp;
	uint64_t last_bounded_dropout_hold_age_us;
	uint64_t last_forwarded_local_position_timestamp;
	uint64_t last_forwarded_local_position_timestamp_sample;
	uint64_t hold_ts;
	uint64_t hold_sample_ts;
	uint64_t hold_age_us;
	uint32_t last_generation;
	uint32_t same_timestamp_valid_winners;
	uint32_t publications;
	uint32_t generation_gaps;
	uint32_t groups;
	uint32_t valid_winner_groups;
	uint32_t valid_then_dt_small;
	uint32_t dt_small_then_valid;
	uint32_t multiple_valid_groups;
	uint32_t equivalent_valid_duplicates;
	uint32_t same_time_valid_advances;
	uint32_t coalesced_soft_transients;
	uint32_t invalid_only_groups;
	uint32_t bounded_invalid_only_forwarded;
	uint32_t rep_snap;
	uint32_t accepted_dropouts;
	uint32_t reset_epoch_changes;
	uint32_t hard_fault_count;
	float hold_hte;
	uint8_t fault;
	bool group_pending;
	bool hard_fault;
	uint8_t _padding0[1]; // required for logger


#ifdef __cplusplus
	static constexpr uint8_t FAULT_NONE = 0;
	static constexpr uint8_t FAULT_GENERATION_DUPLICATE = 1;
	static constexpr uint8_t FAULT_GENERATION_REGRESSION = 2;
	static constexpr uint8_t FAULT_PUBLICATION_TIMESTAMP_REGRESSION = 3;
	static constexpr uint8_t FAULT_PUBLICATION_TIMESTAMP_FUTURE = 4;
	static constexpr uint8_t FAULT_SAMPLE_TIMESTAMP_REGRESSION = 5;
	static constexpr uint8_t FAULT_RESET_EPOCH_INCONSISTENT = 6;
	static constexpr uint8_t FAULT_VALID_SAMPLE_NONFINITE = 7;
	static constexpr uint8_t FAULT_COVARIANCE_NOT_PSD = 8;
	static constexpr uint8_t FAULT_SAME_SAMPLE_VALUE_CONFLICT = 9;
	static constexpr uint8_t FAULT_INVALID_ONLY_DT_TOO_SMALL = 10;
	static constexpr uint8_t FAULT_MALFORMED_INVALID = 11;
	static constexpr uint8_t FAULT_GROUP_TIMEOUT = 12;
	static constexpr uint8_t FAULT_SOURCE_FAILURE_IDENTITY = 13;
	static constexpr uint8_t FAULT_GENERATION_GAP = 14;

#endif
};

#ifdef __cplusplus
namespace px4 {
	namespace msg {
		using GPENMPCHteArbitrationStatus = g_p_e_n_m_p_c_hte_arbitration_status_s;
	} // namespace msg
} // namespace px4
#endif

/* register this as object request broker structure */
ORB_DECLARE(gpenmpc_hte_arbitration_status);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const g_p_e_n_m_p_c_hte_arbitration_status_s& message);
#endif
