/****************************************************************************
 *
 *   Copyright (C) 2013-2022 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file /tmp/gpenmpc_fmuv6c_20260924/px4/msg/GPENMPCPayloadTransitionAck.msg */


#pragma once


#include <uORB/uORB.h>


#ifndef __cplusplus
#define G_P_E_N_M_P_C_PAYLOAD_TRANSITION_ACK_FAULT_NONE 0
#define G_P_E_N_M_P_C_PAYLOAD_TRANSITION_ACK_FAULT_UPSTREAM 1
#define G_P_E_N_M_P_C_PAYLOAD_TRANSITION_ACK_FAULT_STATUS_TIMESTAMP_DUPLICATE 2
#define G_P_E_N_M_P_C_PAYLOAD_TRANSITION_ACK_FAULT_STATUS_TIMESTAMP_REGRESSION 3
#define G_P_E_N_M_P_C_PAYLOAD_TRANSITION_ACK_FAULT_STATUS_STALE 4
#define G_P_E_N_M_P_C_PAYLOAD_TRANSITION_ACK_FAULT_CONTRACT_IDENTITY 5
#define G_P_E_N_M_P_C_PAYLOAD_TRANSITION_ACK_FAULT_SERVICE_COUNT 6
#define G_P_E_N_M_P_C_PAYLOAD_TRANSITION_ACK_FAULT_SERVICE_SEQUENCE 7
#define G_P_E_N_M_P_C_PAYLOAD_TRANSITION_ACK_FAULT_SERVICE_TIMESTAMP 8
#define G_P_E_N_M_P_C_PAYLOAD_TRANSITION_ACK_FAULT_TARGET_INVALID 9
#define G_P_E_N_M_P_C_PAYLOAD_TRANSITION_ACK_FAULT_CONTROL_INACTIVE 10

#endif


#ifdef __cplusplus
struct __EXPORT g_p_e_n_m_p_c_payload_transition_ack_s {
#else
struct g_p_e_n_m_p_c_payload_transition_ack_s {
#endif
	uint64_t timestamp;
	uint64_t source_status_timestamp;
	uint64_t last_application_timestamp;
	uint64_t service_timestamp;
	uint64_t latest_hte_timestamp;
	uint32_t application_count;
	uint32_t service_count;
	uint32_t service_sequence;
	uint32_t hte_update_suppression_count;
	uint32_t same_timestamp_zoh_reuse_count;
	float applied_hover_thrust;
	float latest_native_hte;
	uint8_t fault;
	bool application_valid;
	bool new_application;
	bool transition_enabled;
	bool host_feedforward_disabled;
	bool hte_target_hold_active;
	uint8_t _padding0[6]; // required for logger


#ifdef __cplusplus
	static constexpr uint8_t FAULT_NONE = 0;
	static constexpr uint8_t FAULT_UPSTREAM = 1;
	static constexpr uint8_t FAULT_STATUS_TIMESTAMP_DUPLICATE = 2;
	static constexpr uint8_t FAULT_STATUS_TIMESTAMP_REGRESSION = 3;
	static constexpr uint8_t FAULT_STATUS_STALE = 4;
	static constexpr uint8_t FAULT_CONTRACT_IDENTITY = 5;
	static constexpr uint8_t FAULT_SERVICE_COUNT = 6;
	static constexpr uint8_t FAULT_SERVICE_SEQUENCE = 7;
	static constexpr uint8_t FAULT_SERVICE_TIMESTAMP = 8;
	static constexpr uint8_t FAULT_TARGET_INVALID = 9;
	static constexpr uint8_t FAULT_CONTROL_INACTIVE = 10;

#endif
};

#ifdef __cplusplus
namespace px4 {
	namespace msg {
		using GPENMPCPayloadTransitionAck = g_p_e_n_m_p_c_payload_transition_ack_s;
	} // namespace msg
} // namespace px4
#endif

/* register this as object request broker structure */
ORB_DECLARE(gpenmpc_payload_transition_ack);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const g_p_e_n_m_p_c_payload_transition_ack_s& message);
#endif
