/****************************************************************************
 *
 *   Copyright (C) 2013-2022 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file /tmp/gpenmpc_fmuv6c_20260924/px4/msg/GPENMPCTouchdownGovernorStatus.msg */


#pragma once


#include <uORB/uORB.h>


#ifndef __cplusplus
#define G_P_E_N_M_P_C_TOUCHDOWN_GOVERNOR_STATUS_STATE_INACTIVE 0
#define G_P_E_N_M_P_C_TOUCHDOWN_GOVERNOR_STATUS_STATE_ACTIVE 1
#define G_P_E_N_M_P_C_TOUCHDOWN_GOVERNOR_STATUS_STATE_FALLBACK 2
#define G_P_E_N_M_P_C_TOUCHDOWN_GOVERNOR_STATUS_STATE_INFEASIBLE 3
#define G_P_E_N_M_P_C_TOUCHDOWN_GOVERNOR_STATUS_STATE_SETTLING 4
#define G_P_E_N_M_P_C_TOUCHDOWN_GOVERNOR_STATUS_STATE_SUPPORT_RELEASE 5

#endif


#ifdef __cplusplus
struct __EXPORT g_p_e_n_m_p_c_touchdown_governor_status_s {
#else
struct g_p_e_n_m_p_c_touchdown_governor_status_s {
#endif
	uint64_t timestamp;
	uint64_t frame_status_timestamp;
	float robust_h_m;
	float robust_v_d_mps;
	float robust_touch_limit_mps;
	float predicted_touch_speed_mps;
	float unconstrained_v_mps;
	float constrained_v_target_mps;
	float constrained_v_applied_mps;
	float local_v_sp_mps;
	float local_z_sp_m;
	float command_accel_mps2;
	float command_jerk_mps3;
	float hover_thrust_estimate;
	float hover_thrust_target;
	float hover_thrust_variance;
	float trim_mismatch_accel_mps2;
	float settling_blend;
	float settling_accel_target_mps2;
	float settling_accel_applied_mps2;
	float support_dwell_s;
	float support_dwell_required_s;
	float recovery_clear_dwell_s;
	float recovery_episode_s;
	float ground_plane_settling_s;
	float frame_velocity_residual_mps;
	float frame_velocity_cancellation_target_mps2;
	float pre_touch_velocity_tracking_residual_mps;
	float pre_touch_frame_cancellation_co_ramp_target_mps2;
	float constraint_horizon_command_tracking_residual_mps;
	float post_ground_settling_peak_target_mps2;
	float horizon_s;
	uint8_t state;
	bool eligible;
	bool active;
	bool feasible;
	bool fallback;
	bool plant_truth_used;
	bool support_candidate;
	bool support_release_active;
	bool recovery_latched;
	bool recovery_completed;
	bool recovery_clear_candidate;
	bool recovery_timed_out;
	bool ground_plane_arrival_latched;
	bool frame_velocity_cancellation_active;
	bool pre_touch_velocity_tracking_closure_active;
	bool pre_touch_frame_cancellation_co_ramp_active;
	bool constraint_horizon_command_tracking_closure_active;
	bool post_ground_settling_peak_hold_active;
	uint8_t _padding0[6]; // required for logger


#ifdef __cplusplus
	static constexpr uint8_t STATE_INACTIVE = 0;
	static constexpr uint8_t STATE_ACTIVE = 1;
	static constexpr uint8_t STATE_FALLBACK = 2;
	static constexpr uint8_t STATE_INFEASIBLE = 3;
	static constexpr uint8_t STATE_SETTLING = 4;
	static constexpr uint8_t STATE_SUPPORT_RELEASE = 5;

#endif
};

#ifdef __cplusplus
namespace px4 {
	namespace msg {
		using GPENMPCTouchdownGovernorStatus = g_p_e_n_m_p_c_touchdown_governor_status_s;
	} // namespace msg
} // namespace px4
#endif

/* register this as object request broker structure */
ORB_DECLARE(gpenmpc_touchdown_governor_status);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const g_p_e_n_m_p_c_touchdown_governor_status_s& message);
#endif
