/****************************************************************************
 *
 *   Copyright (C) 2013-2022 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file /tmp/gpenmpc_fmuv6c_20260924/px4/msg/GPENMPCGroundFrameStatus.msg */


#pragma once


#include <uORB/uORB.h>


#ifndef __cplusplus
#define G_P_E_N_M_P_C_GROUND_FRAME_STATUS_STATE_UNINITIALIZED 0
#define G_P_E_N_M_P_C_GROUND_FRAME_STATUS_STATE_VALID 1
#define G_P_E_N_M_P_C_GROUND_FRAME_STATUS_STATE_DEGRADED 2
#define G_P_E_N_M_P_C_GROUND_FRAME_STATUS_STATE_HARD_FAULT 3
#define G_P_E_N_M_P_C_GROUND_FRAME_STATUS_REASON_NONE 0
#define G_P_E_N_M_P_C_GROUND_FRAME_STATUS_REASON_BASELINE_INCOMPLETE 1
#define G_P_E_N_M_P_C_GROUND_FRAME_STATUS_REASON_INPUT_NONFINITE 2
#define G_P_E_N_M_P_C_GROUND_FRAME_STATUS_REASON_TIMESTAMP_REGRESSION 3
#define G_P_E_N_M_P_C_GROUND_FRAME_STATUS_REASON_TIMESTAMP_FUTURE 4
#define G_P_E_N_M_P_C_GROUND_FRAME_STATUS_REASON_SAMPLE_STALE 5
#define G_P_E_N_M_P_C_GROUND_FRAME_STATUS_REASON_RESET_DELTA_INVALID 6
#define G_P_E_N_M_P_C_GROUND_FRAME_STATUS_REASON_COVARIANCE_INVALID 7
#define G_P_E_N_M_P_C_GROUND_FRAME_STATUS_REASON_UNCERTAINTY_EXCEEDED 8
#define G_P_E_N_M_P_C_GROUND_FRAME_STATUS_REASON_INNOVATION_REJECTED 9
#define G_P_E_N_M_P_C_GROUND_FRAME_STATUS_REASON_BIAS_IDENTITY_OUT_OF_BOUNDS 10
#define G_P_E_N_M_P_C_GROUND_FRAME_STATUS_PREARM_REASON_NONE 0
#define G_P_E_N_M_P_C_GROUND_FRAME_STATUS_PREARM_REASON_NOT_DISARMED_SAFE_BASELINE 1
#define G_P_E_N_M_P_C_GROUND_FRAME_STATUS_PREARM_REASON_BASELINE_UNAVAILABLE 2
#define G_P_E_N_M_P_C_GROUND_FRAME_STATUS_PREARM_REASON_SOURCE_IDENTITY_INVALID 3
#define G_P_E_N_M_P_C_GROUND_FRAME_STATUS_PREARM_REASON_INPUT_NONFINITE 4
#define G_P_E_N_M_P_C_GROUND_FRAME_STATUS_PREARM_REASON_COVARIANCE_ENVELOPE_NONPOSITIVE 5
#define G_P_E_N_M_P_C_GROUND_FRAME_STATUS_PREARM_REASON_POSITION_INCONSISTENT 6
#define G_P_E_N_M_P_C_GROUND_FRAME_STATUS_PREARM_REASON_VELOCITY_INCONSISTENT 7
#define G_P_E_N_M_P_C_GROUND_FRAME_STATUS_PREARM_REASON_ALIGNMENT_NOT_CONVERGED 8
#define G_P_E_N_M_P_C_GROUND_FRAME_STATUS_PREARM_REASON_RESET_DURING_DWELL 9
#define G_P_E_N_M_P_C_GROUND_FRAME_STATUS_PREARM_REASON_TIMESTAMP_INVALID 10
#define G_P_E_N_M_P_C_GROUND_FRAME_STATUS_PREARM_REASON_DWELL_INCOMPLETE 11

#endif


#ifdef __cplusplus
struct __EXPORT g_p_e_n_m_p_c_ground_frame_status_s {
#else
struct g_p_e_n_m_p_c_ground_frame_status_s {
#endif
	uint64_t timestamp;
	uint64_t local_ts;
	uint64_t ground_h_ts;
	uint64_t ground_v_ts;
	uint64_t prearm_dwell_started;
	uint32_t reset_events;
	uint32_t accepted_updates;
	uint32_t rejected_updates;
	uint32_t prearm_dwell_reset_count;
	uint32_t prearm_frame_reset_events;
	uint32_t prearm_vertical_reset_counter;
	float h_ground_m;
	float v_ground_d_mps;
	float b_z_m;
	float b_v_mps;
	float h_3sigma_m;
	float v_3sigma_mps;
	float b_z_3sigma_m;
	float b_v_3sigma_mps;
	float z_aligned_m;
	float vz_aligned_mps;
	float innovation_nsigma;
	float local_age_s;
	float ground_h_age_s;
	float ground_v_age_s;
	float b_z_target_m;
	float b_z_applied_m;
	float b_z_rate_mps;
	float b_v_target_mps;
	float b_v_applied_mps;
	float b_v_rate_mps2;
	float prearm_dwell_s;
	float prearm_z_residual_m;
	float prearm_vz_residual_mps;
	float prearm_z_envelope_m;
	float prearm_vz_envelope_mps;
	float prearm_z_ratio;
	float prearm_vz_ratio;
	float prearm_alignment_z_residual_m;
	float prearm_alignment_vz_residual_mps;
	uint8_t state;
	uint8_t reason;
	bool initialized;
	bool valid;
	bool fresh;
	bool hard_fault;
	bool hybrid_transition;
	bool innovation_rejected;
	bool bias_hold_near_ground;
	bool local_z_accepted;
	bool local_vz_accepted;
	bool ground_h_accepted;
	bool ground_v_accepted;
	bool alignment_active;
	bool alignment_uncertainty_ok;
	bool alignment_hard_fault;
	bool plant_truth_used;
	uint8_t prearm_reason;
	bool prearm_predicate;
	bool prearm_ready;
	bool prearm_baseline_ok;
	bool prearm_source_identity_ok;
	bool prearm_covariance_ok;
	bool prearm_position_ok;
	bool prearm_velocity_ok;
	bool prearm_alignment_ok;
	bool prearm_reset_ok;
	uint8_t _padding0[1]; // required for logger


#ifdef __cplusplus
	static constexpr uint8_t STATE_UNINITIALIZED = 0;
	static constexpr uint8_t STATE_VALID = 1;
	static constexpr uint8_t STATE_DEGRADED = 2;
	static constexpr uint8_t STATE_HARD_FAULT = 3;
	static constexpr uint8_t REASON_NONE = 0;
	static constexpr uint8_t REASON_BASELINE_INCOMPLETE = 1;
	static constexpr uint8_t REASON_INPUT_NONFINITE = 2;
	static constexpr uint8_t REASON_TIMESTAMP_REGRESSION = 3;
	static constexpr uint8_t REASON_TIMESTAMP_FUTURE = 4;
	static constexpr uint8_t REASON_SAMPLE_STALE = 5;
	static constexpr uint8_t REASON_RESET_DELTA_INVALID = 6;
	static constexpr uint8_t REASON_COVARIANCE_INVALID = 7;
	static constexpr uint8_t REASON_UNCERTAINTY_EXCEEDED = 8;
	static constexpr uint8_t REASON_INNOVATION_REJECTED = 9;
	static constexpr uint8_t REASON_BIAS_IDENTITY_OUT_OF_BOUNDS = 10;
	static constexpr uint8_t PREARM_REASON_NONE = 0;
	static constexpr uint8_t PREARM_REASON_NOT_DISARMED_SAFE_BASELINE = 1;
	static constexpr uint8_t PREARM_REASON_BASELINE_UNAVAILABLE = 2;
	static constexpr uint8_t PREARM_REASON_SOURCE_IDENTITY_INVALID = 3;
	static constexpr uint8_t PREARM_REASON_INPUT_NONFINITE = 4;
	static constexpr uint8_t PREARM_REASON_COVARIANCE_ENVELOPE_NONPOSITIVE = 5;
	static constexpr uint8_t PREARM_REASON_POSITION_INCONSISTENT = 6;
	static constexpr uint8_t PREARM_REASON_VELOCITY_INCONSISTENT = 7;
	static constexpr uint8_t PREARM_REASON_ALIGNMENT_NOT_CONVERGED = 8;
	static constexpr uint8_t PREARM_REASON_RESET_DURING_DWELL = 9;
	static constexpr uint8_t PREARM_REASON_TIMESTAMP_INVALID = 10;
	static constexpr uint8_t PREARM_REASON_DWELL_INCOMPLETE = 11;

#endif
};

#ifdef __cplusplus
namespace px4 {
	namespace msg {
		using GPENMPCGroundFrameStatus = g_p_e_n_m_p_c_ground_frame_status_s;
	} // namespace msg
} // namespace px4
#endif

/* register this as object request broker structure */
ORB_DECLARE(gpenmpc_ground_frame_status);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const g_p_e_n_m_p_c_ground_frame_status_s& message);
#endif
