/****************************************************************************
 *
 *   Copyright (C) 2013-2022 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file /tmp/gpenmpc_fmuv6c_20260924/px4/msg/GPENMPCLandingShapingStatus.msg */


#pragma once


#include <uORB/uORB.h>


#ifndef __cplusplus
#define G_P_E_N_M_P_C_LANDING_SHAPING_STATUS_DISTANCE_SOURCE_INVALID 0
#define G_P_E_N_M_P_C_LANDING_SHAPING_STATUS_DISTANCE_SOURCE_RANGE 1
#define G_P_E_N_M_P_C_LANDING_SHAPING_STATUS_DISTANCE_SOURCE_HOME_RELATIVE 2
#define G_P_E_N_M_P_C_LANDING_SHAPING_STATUS_DISTANCE_SOURCE_LOCAL_Z 3
#define G_P_E_N_M_P_C_LANDING_SHAPING_STATUS_DISTANCE_SOURCE_GPENMPC_SET_MEMBERSHIP 4
#define G_P_E_N_M_P_C_LANDING_SHAPING_STATUS_DISTANCE_SOURCE_GPENMPC_TIME_ALIGNED_GROUND_FRAME 5

#endif


#ifdef __cplusplus
struct __EXPORT g_p_e_n_m_p_c_landing_shaping_status_s {
#else
struct g_p_e_n_m_p_c_landing_shaping_status_s {
#endif
	uint64_t timestamp;
	uint64_t payload_status_timestamp;
	uint64_t payload_service_timestamp;
	uint32_t service_count;
	uint32_t service_sequence;
	uint32_t direct_application_ack_count;
	float distance_to_ground_m;
	float distance_to_bottom_m;
	float land_alt3_m;
	float land_speed_unshaped_mps;
	float land_crawl_speed_mps;
	float selected_vertical_speed_mps;
	float touchdown_authority_entry_distance_m;
	float touchdown_authority_full_distance_m;
	float touchdown_authority_max_acceleration_d_mps2;
	float touchdown_authority_blend;
	float touchdown_authority_acceleration_d_mps2;
	float touchdown_authority_desired_acceleration_d_mps2;
	float touchdown_authority_rise_rate_mps3;
	float touchdown_authority_fall_rate_mps3;
	float touchdown_settling_blend;
	float touchdown_hover_thrust_estimate;
	float touchdown_hover_thrust_target;
	float touchdown_trim_mismatch_acceleration_d_mps2;
	float ground_observer_height_center_m;
	float ground_observer_height_lower_m;
	float ground_observer_height_upper_m;
	float ground_observer_baro_bound_m;
	float ground_observer_gps_bound_m;
	uint8_t distance_source;
	uint8_t payload_fault;
	bool payload_status_fresh;
	bool gpenmpc_contract_valid;
	bool transition_active;
	bool recovery_requested;
	bool range_distance_available;
	bool estimated_ground_crawl_eligible;
	bool crawl_active;
	bool touchdown_authority_active;
	bool ground_observer_status_fresh;
	bool ground_observer_usable;
	bool ground_observer_precise_hil_contract;
	bool ground_observer_plant_truth_used;
	uint8_t ground_observer_state;
	uint8_t ground_observer_reason;


#ifdef __cplusplus
	static constexpr uint8_t DISTANCE_SOURCE_INVALID = 0;
	static constexpr uint8_t DISTANCE_SOURCE_RANGE = 1;
	static constexpr uint8_t DISTANCE_SOURCE_HOME_RELATIVE = 2;
	static constexpr uint8_t DISTANCE_SOURCE_LOCAL_Z = 3;
	static constexpr uint8_t DISTANCE_SOURCE_GPENMPC_SET_MEMBERSHIP = 4;
	static constexpr uint8_t DISTANCE_SOURCE_GPENMPC_TIME_ALIGNED_GROUND_FRAME = 5;

#endif
};

#ifdef __cplusplus
namespace px4 {
	namespace msg {
		using GPENMPCLandingShapingStatus = g_p_e_n_m_p_c_landing_shaping_status_s;
	} // namespace msg
} // namespace px4
#endif

/* register this as object request broker structure */
ORB_DECLARE(gpenmpc_landing_shaping_status);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const g_p_e_n_m_p_c_landing_shaping_status_s& message);
#endif
