/****************************************************************************
 *
 *   Copyright (C) 2013-2022 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file /tmp/gpenmpc_fmuv6c_20260924/px4/msg/GPENMPCExecStatus.msg */


#pragma once


#include <uORB/uORB.h>


#ifndef __cplusplus
#define G_P_E_N_M_P_C_EXEC_STATUS_FAIL_NONE 0
#define G_P_E_N_M_P_C_EXEC_STATUS_FAIL_STALE 1
#define G_P_E_N_M_P_C_EXEC_STATUS_FAIL_NONFINITE 2
#define G_P_E_N_M_P_C_EXEC_STATUS_FAIL_SCHEMA 3
#define G_P_E_N_M_P_C_EXEC_STATUS_FAIL_HASH 4
#define G_P_E_N_M_P_C_EXEC_STATUS_FAIL_SEQUENCE 5
#define G_P_E_N_M_P_C_EXEC_STATUS_FAIL_TIMESTAMP 6
#define G_P_E_N_M_P_C_EXEC_STATUS_FAIL_STATE 7
#define G_P_E_N_M_P_C_EXEC_STATUS_FAIL_BATTERY 8
#define G_P_E_N_M_P_C_EXEC_STATUS_FAIL_CODEGEN 9
#define G_P_E_N_M_P_C_EXEC_STATUS_FAIL_OVERRUN 10
#define G_P_E_N_M_P_C_EXEC_STATUS_FAIL_C_AUTHORITY 11
#define G_P_E_N_M_P_C_EXEC_STATUS_FAIL_HTE_TIMESTAMP 12
#define G_P_E_N_M_P_C_EXEC_STATUS_FAIL_HTE_INVALID 13
#define G_P_E_N_M_P_C_EXEC_STATUS_FAIL_HTE_STALE 14
#define G_P_E_N_M_P_C_EXEC_STATUS_FAIL_SERVICE_IDENTITY 15
#define G_P_E_N_M_P_C_EXEC_STATUS_FAIL_HTE_COMPENSATION 16
#define G_P_E_N_M_P_C_EXEC_STATUS_FAIL_HTE_AVAILABILITY_TIMEOUT 17
#define G_P_E_N_M_P_C_EXEC_STATUS_FAIL_GROUND_OBSERVER_IDENTITY 18
#define G_P_E_N_M_P_C_EXEC_STATUS_FAIL_TAKEOFF_PHASE_ALIGNMENT 19

#endif


#ifdef __cplusplus
struct __EXPORT g_p_e_n_m_p_c_exec_status_s {
#else
struct g_p_e_n_m_p_c_exec_status_s {
#endif
	uint64_t timestamp;
	uint64_t generated_c_call_count;
	uint64_t active_publish_count;
	uint64_t rejected_input_count;
	uint64_t shadow_sample_count;
	uint64_t shadow_invalid_count;
	uint64_t same_timestamp_schedule_reuse_count;
	uint32_t sequence;
	uint32_t failure_reason;
	uint32_t source_hash[8];
	uint32_t firmware_contract_hash[8];
	uint32_t profile_hash[8];
	uint32_t component_hash[8];
	float progress;
	float progress_rate;
	float execution_time_us;
	float maximum_execution_time_us;
	float rotor_reserve;
	float active_position_ned_m[3];
	float active_velocity_ned_mps[3];
	float active_acceleration_ned_mps2[3];
	float active_jerk_ned_mps3[3];
	float active_yaw_rad;
	float active_yaw_rate_rad_s;
	float predicted_rotor_thrust_n[6];
	float shadow_predicted_position_risk_m;
	float shadow_recoverability_margin;
	float shadow_proposed_progress_rate;
	bool writer_active;
	bool active_reference_published;
	bool input_valid;
	bool fail_closed;
	bool shadow_valid;
	bool shadow_proposed;
	bool shadow_authorized;
	bool shadow_rejected;
	bool shadow_locked;
	bool shadow_released;
	uint8_t _padding0[6]; // required for logger


#ifdef __cplusplus
	static constexpr uint32_t FAIL_NONE = 0;
	static constexpr uint32_t FAIL_STALE = 1;
	static constexpr uint32_t FAIL_NONFINITE = 2;
	static constexpr uint32_t FAIL_SCHEMA = 3;
	static constexpr uint32_t FAIL_HASH = 4;
	static constexpr uint32_t FAIL_SEQUENCE = 5;
	static constexpr uint32_t FAIL_TIMESTAMP = 6;
	static constexpr uint32_t FAIL_STATE = 7;
	static constexpr uint32_t FAIL_BATTERY = 8;
	static constexpr uint32_t FAIL_CODEGEN = 9;
	static constexpr uint32_t FAIL_OVERRUN = 10;
	static constexpr uint32_t FAIL_C_AUTHORITY = 11;
	static constexpr uint32_t FAIL_HTE_TIMESTAMP = 12;
	static constexpr uint32_t FAIL_HTE_INVALID = 13;
	static constexpr uint32_t FAIL_HTE_STALE = 14;
	static constexpr uint32_t FAIL_SERVICE_IDENTITY = 15;
	static constexpr uint32_t FAIL_HTE_COMPENSATION = 16;
	static constexpr uint32_t FAIL_HTE_AVAILABILITY_TIMEOUT = 17;
	static constexpr uint32_t FAIL_GROUND_OBSERVER_IDENTITY = 18;
	static constexpr uint32_t FAIL_TAKEOFF_PHASE_ALIGNMENT = 19;

#endif
};

#ifdef __cplusplus
namespace px4 {
	namespace msg {
		using GPENMPCExecStatus = g_p_e_n_m_p_c_exec_status_s;
	} // namespace msg
} // namespace px4
#endif

/* register this as object request broker structure */
ORB_DECLARE(gpenmpc_exec_status);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const g_p_e_n_m_p_c_exec_status_s& message);
#endif
