/****************************************************************************
 *
 *   Copyright (C) 2013-2022 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file /tmp/gpenmpc_fmuv6c_20260924/px4/msg/GPENMPCTakeoffPhaseStatus.msg */


#pragma once


#include <uORB/uORB.h>


#ifndef __cplusplus
#define G_P_E_N_M_P_C_TAKEOFF_PHASE_STATUS_STATE_DISARMED 0
#define G_P_E_N_M_P_C_TAKEOFF_PHASE_STATUS_STATE_AWAIT_EVIDENCE 1
#define G_P_E_N_M_P_C_TAKEOFF_PHASE_STATUS_STATE_SCHEDULED 2
#define G_P_E_N_M_P_C_TAKEOFF_PHASE_STATUS_STATE_TASK_ACTIVE 3
#define G_P_E_N_M_P_C_TAKEOFF_PHASE_STATUS_STATE_HARD_FAULT 4
#define G_P_E_N_M_P_C_TAKEOFF_PHASE_STATUS_REASON_NONE 0
#define G_P_E_N_M_P_C_TAKEOFF_PHASE_STATUS_REASON_AWAIT_ARMED_OFFBOARD 1
#define G_P_E_N_M_P_C_TAKEOFF_PHASE_STATUS_REASON_TAKEOFF_STATUS_MISSING_OR_STALE 2
#define G_P_E_N_M_P_C_TAKEOFF_PHASE_STATUS_REASON_STOCK_TAKEOFF_NOT_RAMPUP 3
#define G_P_E_N_M_P_C_TAKEOFF_PHASE_STATUS_REASON_LAND_DETECTOR_NOT_AIRBORNE 4
#define G_P_E_N_M_P_C_TAKEOFF_PHASE_STATUS_REASON_GROUND_FRAME_UNAVAILABLE 5
#define G_P_E_N_M_P_C_TAKEOFF_PHASE_STATUS_REASON_HEIGHT_EVIDENCE_INSUFFICIENT 6
#define G_P_E_N_M_P_C_TAKEOFF_PHASE_STATUS_REASON_VELOCITY_EVIDENCE_INSUFFICIENT 7
#define G_P_E_N_M_P_C_TAKEOFF_PHASE_STATUS_REASON_EVIDENCE_TIMEOUT 8
#define G_P_E_N_M_P_C_TAKEOFF_PHASE_STATUS_REASON_TIMESTAMP_REGRESSION 9
#define G_P_E_N_M_P_C_TAKEOFF_PHASE_STATUS_REASON_GROUND_FRAME_HARD_FAULT 10
#define G_P_E_N_M_P_C_TAKEOFF_PHASE_STATUS_REASON_FLIGHT_ENVELOPE_LOST 11
#define G_P_E_N_M_P_C_TAKEOFF_PHASE_STATUS_REASON_TIMESTAMP_FUTURE 12
#define G_P_E_N_M_P_C_TAKEOFF_PHASE_STATUS_REASON_RESET_IDENTITY_REGRESSION 13

#endif


#ifdef __cplusplus
struct __EXPORT g_p_e_n_m_p_c_takeoff_phase_status_s {
#else
struct g_p_e_n_m_p_c_takeoff_phase_status_s {
#endif
	uint64_t timestamp;
	uint64_t takeoff_status_timestamp;
	uint64_t evidence_timestamp;
	uint64_t phase_start_timestamp;
	uint32_t ground_frame_reset_event_count;
	float conservative_height_lower_m;
	float conservative_velocity_upper_d_mps;
	float intent_gain;
	float intent_velocity_d_mps;
	float intent_acceleration_d_mps2;
	float intent_jerk_d_mps3;
	uint8_t state;
	uint8_t reason;
	uint8_t stock_takeoff_state;
	bool liftoff_evidence;
	bool phase_scheduled;
	bool task_progress_enabled;
	bool intent_active;
	uint8_t _padding0[5]; // required for logger


#ifdef __cplusplus
	static constexpr uint8_t STATE_DISARMED = 0;
	static constexpr uint8_t STATE_AWAIT_EVIDENCE = 1;
	static constexpr uint8_t STATE_SCHEDULED = 2;
	static constexpr uint8_t STATE_TASK_ACTIVE = 3;
	static constexpr uint8_t STATE_HARD_FAULT = 4;
	static constexpr uint8_t REASON_NONE = 0;
	static constexpr uint8_t REASON_AWAIT_ARMED_OFFBOARD = 1;
	static constexpr uint8_t REASON_TAKEOFF_STATUS_MISSING_OR_STALE = 2;
	static constexpr uint8_t REASON_STOCK_TAKEOFF_NOT_RAMPUP = 3;
	static constexpr uint8_t REASON_LAND_DETECTOR_NOT_AIRBORNE = 4;
	static constexpr uint8_t REASON_GROUND_FRAME_UNAVAILABLE = 5;
	static constexpr uint8_t REASON_HEIGHT_EVIDENCE_INSUFFICIENT = 6;
	static constexpr uint8_t REASON_VELOCITY_EVIDENCE_INSUFFICIENT = 7;
	static constexpr uint8_t REASON_EVIDENCE_TIMEOUT = 8;
	static constexpr uint8_t REASON_TIMESTAMP_REGRESSION = 9;
	static constexpr uint8_t REASON_GROUND_FRAME_HARD_FAULT = 10;
	static constexpr uint8_t REASON_FLIGHT_ENVELOPE_LOST = 11;
	static constexpr uint8_t REASON_TIMESTAMP_FUTURE = 12;
	static constexpr uint8_t REASON_RESET_IDENTITY_REGRESSION = 13;

#endif
};

#ifdef __cplusplus
namespace px4 {
	namespace msg {
		using GPENMPCTakeoffPhaseStatus = g_p_e_n_m_p_c_takeoff_phase_status_s;
	} // namespace msg
} // namespace px4
#endif

/* register this as object request broker structure */
ORB_DECLARE(gpenmpc_takeoff_phase_status);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const g_p_e_n_m_p_c_takeoff_phase_status_s& message);
#endif
