/****************************************************************************
 *
 *   Copyright (C) 2013-2022 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file /tmp/gpenmpc_fmuv6c_20260924/px4/msg/GPENMPCPayloadTransitionStatus.msg */


#pragma once


#include <uORB/uORB.h>


#ifndef __cplusplus
#define GPENMPC_PAYLOAD_TRANSITION_STATUS_FAULT_NONE 0
#define GPENMPC_PAYLOAD_TRANSITION_STATUS_FAULT_HTE_TIMESTAMP_DUPLICATE 1
#define GPENMPC_PAYLOAD_TRANSITION_STATUS_FAULT_HTE_TIMESTAMP_REGRESSION 2
#define GPENMPC_PAYLOAD_TRANSITION_STATUS_FAULT_HTE_INVALID 3
#define GPENMPC_PAYLOAD_TRANSITION_STATUS_FAULT_HTE_STALE 4
#define GPENMPC_PAYLOAD_TRANSITION_STATUS_FAULT_SERVICE_IDENTITY 5
#define GPENMPC_PAYLOAD_TRANSITION_STATUS_FAULT_SERVICE_SEQUENCE 6
#define GPENMPC_PAYLOAD_TRANSITION_STATUS_FAULT_COMPENSATION_NONFINITE 7
#define GPENMPC_PAYLOAD_TRANSITION_STATUS_FAULT_COMPENSATION_SATURATION 8
#define GPENMPC_PAYLOAD_TRANSITION_STATUS_FAULT_CONVERGENCE_TIMEOUT 9
#define GPENMPC_PAYLOAD_TRANSITION_STATUS_FAULT_TIME_REGRESSION 10
#define GPENMPC_PAYLOAD_TRANSITION_STATUS_FAULT_APPLICATION_ACK_TIMESTAMP 11
#define GPENMPC_PAYLOAD_TRANSITION_STATUS_FAULT_APPLICATION_ACK_IDENTITY 12
#define GPENMPC_PAYLOAD_TRANSITION_STATUS_FAULT_APPLICATION_ACK_FAULT 13
#define GPENMPC_PAYLOAD_TRANSITION_STATUS_FAULT_HTE_MISMATCH_GROWTH 14
#define GPENMPC_PAYLOAD_TRANSITION_STATUS_AVAILABILITY_AVAILABLE 0
#define GPENMPC_PAYLOAD_TRANSITION_STATUS_AVAILABILITY_DEGRADED 1
#define GPENMPC_PAYLOAD_TRANSITION_STATUS_AVAILABILITY_REACQUIRE 2
#define GPENMPC_PAYLOAD_TRANSITION_STATUS_AVAILABILITY_RECOVERY 3
#define GPENMPC_PAYLOAD_TRANSITION_STATUS_ELIGIBILITY_OK 0
#define GPENMPC_PAYLOAD_TRANSITION_STATUS_ELIGIBILITY_NOT_ARMED 1
#define GPENMPC_PAYLOAD_TRANSITION_STATUS_ELIGIBILITY_NOT_IN_AIR 2
#define GPENMPC_PAYLOAD_TRANSITION_STATUS_ELIGIBILITY_DT_TOO_SMALL 3
#define GPENMPC_PAYLOAD_TRANSITION_STATUS_ELIGIBILITY_DT_TOO_LARGE 4
#define GPENMPC_PAYLOAD_TRANSITION_STATUS_ELIGIBILITY_ACCEL_NONFINITE 5

#endif


#ifdef __cplusplus
struct __EXPORT gpenmpc_payload_transition_status_s {
#else
struct gpenmpc_payload_transition_status_s {
#endif
	uint64_t timestamp;
	uint64_t ht;
	uint64_t hs;
	uint64_t ha;
	uint64_t svt;
	uint64_t aat;
	uint64_t ads;
	uint64_t rs;
	uint64_t lrv;
	uint64_t hlf;
	uint64_t hcl;
	uint32_t hn;
	uint32_t hi;
	uint32_t tu;
	uint32_t tc;
	uint32_t tx;
	uint32_t ad;
	uint32_t ar;
	uint32_t ato;
	uint32_t owr;
	uint32_t irr;
	uint32_t ezr;
	uint32_t sfg;
	uint32_t rpt;
	uint32_t rvs;
	uint32_t hsf;
	uint32_t hcf;
	uint32_t sc;
	uint32_t sq;
	float edt;
	uint32_t dac;
	float hte;
	float hvv;
	float hp;
	float htg;
	float mr;
	float dad;
	float aad;
	float acr;
	float hma;
	uint8_t fault;
	uint8_t av;
	uint8_t er;
	uint8_t hlr;
	bool hv;
	bool ea;
	bool earmed;
	bool eia;
	bool eld;
	bool eso;
	bool ta;
	bool cd;
	bool rr;
	bool te;
	bool hfd;
	bool afa;
	bool daa;
	uint8_t _padding0[3]; // required for logger


#ifdef __cplusplus
	static constexpr uint8_t FAULT_NONE = 0;
	static constexpr uint8_t FAULT_HTE_TIMESTAMP_DUPLICATE = 1;
	static constexpr uint8_t FAULT_HTE_TIMESTAMP_REGRESSION = 2;
	static constexpr uint8_t FAULT_HTE_INVALID = 3;
	static constexpr uint8_t FAULT_HTE_STALE = 4;
	static constexpr uint8_t FAULT_SERVICE_IDENTITY = 5;
	static constexpr uint8_t FAULT_SERVICE_SEQUENCE = 6;
	static constexpr uint8_t FAULT_COMPENSATION_NONFINITE = 7;
	static constexpr uint8_t FAULT_COMPENSATION_SATURATION = 8;
	static constexpr uint8_t FAULT_CONVERGENCE_TIMEOUT = 9;
	static constexpr uint8_t FAULT_TIME_REGRESSION = 10;
	static constexpr uint8_t FAULT_APPLICATION_ACK_TIMESTAMP = 11;
	static constexpr uint8_t FAULT_APPLICATION_ACK_IDENTITY = 12;
	static constexpr uint8_t FAULT_APPLICATION_ACK_FAULT = 13;
	static constexpr uint8_t FAULT_HTE_MISMATCH_GROWTH = 14;
	static constexpr uint8_t AVAILABILITY_AVAILABLE = 0;
	static constexpr uint8_t AVAILABILITY_DEGRADED = 1;
	static constexpr uint8_t AVAILABILITY_REACQUIRE = 2;
	static constexpr uint8_t AVAILABILITY_RECOVERY = 3;
	static constexpr uint8_t ELIGIBILITY_OK = 0;
	static constexpr uint8_t ELIGIBILITY_NOT_ARMED = 1;
	static constexpr uint8_t ELIGIBILITY_NOT_IN_AIR = 2;
	static constexpr uint8_t ELIGIBILITY_DT_TOO_SMALL = 3;
	static constexpr uint8_t ELIGIBILITY_DT_TOO_LARGE = 4;
	static constexpr uint8_t ELIGIBILITY_ACCEL_NONFINITE = 5;

#endif
};

#ifdef __cplusplus
namespace px4 {
	namespace msg {
		using GPENMPCPayloadTransitionStatus = gpenmpc_payload_transition_status_s;
	} // namespace msg
} // namespace px4
#endif

/* register this as object request broker structure */
ORB_DECLARE(gpenmpc_payload_transition_status);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const gpenmpc_payload_transition_status_s& message);
#endif
