/****************************************************************************
 *
 *   Copyright (C) 2013-2022 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file /tmp/gpenmpc_fmuv6c_20260924/px4/msg/GPENMPCVerticalControlStatus.msg */


#pragma once


#include <uORB/uORB.h>


#ifndef __cplusplus
#define GPENMPC_VERTICAL_CONTROL_STATUS_PHASE_DISABLED 0
#define GPENMPC_VERTICAL_CONTROL_STATUS_PHASE_PREP_OR_HOLD 1
#define GPENMPC_VERTICAL_CONTROL_STATUS_PHASE_ROUTE_MOTION 2
#define GPENMPC_VERTICAL_CONTROL_STATUS_PHASE_SERVICE_GUARD 3
#define GPENMPC_VERTICAL_CONTROL_STATUS_PHASE_HTE_UNAVAILABLE 4
#define GPENMPC_VERTICAL_CONTROL_STATUS_PHASE_NATIVE_LAND 5
#define GPENMPC_VERTICAL_CONTROL_STATUS_PHASE_ROUTE_MOTION_BOUNDED_HTE_HOLD 6

#endif


#ifdef __cplusplus
struct __EXPORT gpenmpc_vertical_control_status_s {
#else
struct gpenmpc_vertical_control_status_s {
#endif
	uint64_t timestamp;
	uint64_t sample_timestamp;
	uint64_t route_status_timestamp;
	uint64_t service_timestamp;
	float horizontal_reference_speed;
	float nominal_integral_gain;
	float effective_integral_gain;
	float target_integral_gain;
	float integral_gain_slew_rate;
	float initial_hold_integral_recenter_rate_mps3;
	float initial_hold_integral_recenter_target_d;
	float position_setpoint_d;
	float position_d;
	float position_term_d;
	float velocity_feedforward_d;
	float velocity_setpoint_d;
	float velocity_d;
	float velocity_error_d;
	float acceleration_feedforward_d;
	float acceleration_p_d;
	float acceleration_i_d;
	float acceleration_d_d;
	float acceleration_setpoint_d;
	float thrust_setpoint_d;
	float hover_thrust;
	float native_hte;
	float terminal_estimated_distance_to_ground_m;
	float terminal_integral_floor_target_d;
	float terminal_integral_floor_slew_rate_mps3;
	uint8_t phase;
	uint8_t hte_availability_state;
	bool route_status_fresh;
	bool route_reference_valid;
	bool route_motion_active;
	bool local_position_ready;
	bool native_airborne;
	bool service_guard_active;
	bool native_land_active;
	bool integrator_update_allowed;
	bool vertical_anti_windup;
	bool vertical_integral_updated;
	bool initial_hold_integral_recenter_active;
	bool prep_recenter;
	bool tko_active;
	bool hte_fresh;
	bool route_motion_seen;
	bool hte_bounded_hold_authority;
	bool payload_application_valid;
	bool payload_target_hold_active;
	bool payload_fault_free;
	bool landing_status_fresh;
	bool terminal_integral_authority_active;
	bool terminal_integral_floor_slew_active;
	bool terminal_negative_integral_update_blocked;
	uint8_t _padding0[3]; // required for logger


#ifdef __cplusplus
	static constexpr uint8_t PHASE_DISABLED = 0;
	static constexpr uint8_t PHASE_PREP_OR_HOLD = 1;
	static constexpr uint8_t PHASE_ROUTE_MOTION = 2;
	static constexpr uint8_t PHASE_SERVICE_GUARD = 3;
	static constexpr uint8_t PHASE_HTE_UNAVAILABLE = 4;
	static constexpr uint8_t PHASE_NATIVE_LAND = 5;
	static constexpr uint8_t PHASE_ROUTE_MOTION_BOUNDED_HTE_HOLD = 6;

#endif
};

#ifdef __cplusplus
namespace px4 {
	namespace msg {
		using GPENMPCVerticalControlStatus = gpenmpc_vertical_control_status_s;
	} // namespace msg
} // namespace px4
#endif

/* register this as object request broker structure */
ORB_DECLARE(gpenmpc_vertical_control_status);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const gpenmpc_vertical_control_status_s& message);
#endif
