/****************************************************************************
 *
 *   Copyright (C) 2013-2022 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file /tmp/gpenmpc_fmuv6c_20260924/px4/msg/GPENMPCExecTestStatus.msg */


#pragma once


#include <uORB/uORB.h>


#ifndef __cplusplus
#define GPENMPC_EXEC_TEST_STATUS_MODE_NORMAL 0
#define GPENMPC_EXEC_TEST_STATUS_MODE_SHADOW_EXTREME 1
#define GPENMPC_EXEC_TEST_STATUS_MODE_SHADOW_BAD_HASH 2
#define GPENMPC_EXEC_TEST_STATUS_MODE_SHADOW_NONFINITE 3
#define GPENMPC_EXEC_TEST_STATUS_MODE_SHADOW_SILENT 4
#define GPENMPC_EXEC_TEST_STATUS_MODE_WRONG_SCHEMA 10
#define GPENMPC_EXEC_TEST_STATUS_MODE_WRONG_DIMENSION 11
#define GPENMPC_EXEC_TEST_STATUS_MODE_WRONG_HASH 12
#define GPENMPC_EXEC_TEST_STATUS_MODE_NONFINITE 13
#define GPENMPC_EXEC_TEST_STATUS_MODE_SEQUENCE_ROLLBACK 14
#define GPENMPC_EXEC_TEST_STATUS_MODE_TIMESTAMP_JUMP 15
#define GPENMPC_EXEC_TEST_STATUS_MODE_STALE 16

#endif


#ifdef __cplusplus
struct __EXPORT gpenmpc_exec_test_status_s {
#else
struct gpenmpc_exec_test_status_s {
#endif
	uint64_t timestamp;
	uint64_t segment_publish_count;
	uint64_t shadow_publish_count;
	uint64_t observed_exec_status_count;
	uint64_t observed_active_count;
	uint64_t shadow_exact_count;
	uint64_t shadow_mismatch_count;
	uint64_t active_setpoint_mismatch_count;
	uint64_t expected_fail_count;
	uint64_t unexpected_result_count;
	uint64_t generated_c_call_count;
	uint32_t mode;
	uint32_t observed_exec_failure_reason;
	float active_position_ned_m[3];
	float active_velocity_ned_mps[3];
	float active_acceleration_ned_mps2[3];
	float active_yaw_rad;
	bool writer_lease_held;
	bool active_reference_published;
	bool exec_fail_closed;
	bool expected_result_observed;
	bool active_matches_constant_c;
	bool test_pass;
	uint8_t _padding0[2]; // required for logger


#ifdef __cplusplus
	static constexpr uint32_t MODE_NORMAL = 0;
	static constexpr uint32_t MODE_SHADOW_EXTREME = 1;
	static constexpr uint32_t MODE_SHADOW_BAD_HASH = 2;
	static constexpr uint32_t MODE_SHADOW_NONFINITE = 3;
	static constexpr uint32_t MODE_SHADOW_SILENT = 4;
	static constexpr uint32_t MODE_WRONG_SCHEMA = 10;
	static constexpr uint32_t MODE_WRONG_DIMENSION = 11;
	static constexpr uint32_t MODE_WRONG_HASH = 12;
	static constexpr uint32_t MODE_NONFINITE = 13;
	static constexpr uint32_t MODE_SEQUENCE_ROLLBACK = 14;
	static constexpr uint32_t MODE_TIMESTAMP_JUMP = 15;
	static constexpr uint32_t MODE_STALE = 16;

#endif
};

#ifdef __cplusplus
namespace px4 {
	namespace msg {
		using GPENMPCExecTestStatus = gpenmpc_exec_test_status_s;
	} // namespace msg
} // namespace px4
#endif

/* register this as object request broker structure */
ORB_DECLARE(gpenmpc_exec_test_status);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const gpenmpc_exec_test_status_s& message);
#endif
