/****************************************************************************
 *
 *   Copyright (C) 2013-2022 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file /tmp/gpenmpc_fmuv6c_20260924/px4/msg/GPENMPCSe3ControlStatus.msg */


#pragma once


#include <uORB/uORB.h>


#ifndef __cplusplus
#define GPENMPC_SE3_CONTROL_STATUS_MODE_PX4_NATIVE 0
#define GPENMPC_SE3_CONTROL_STATUS_MODE_N0_NOMINAL 1
#define GPENMPC_SE3_CONTROL_STATUS_MODE_R0_ROBUST 2
#define GPENMPC_SE3_CONTROL_STATUS_FAIL_NONE 0
#define GPENMPC_SE3_CONTROL_STATUS_FAIL_DISABLED 1
#define GPENMPC_SE3_CONTROL_STATUS_FAIL_PARAMETER 2
#define GPENMPC_SE3_CONTROL_STATUS_FAIL_NOT_ARMED 3
#define GPENMPC_SE3_CONTROL_STATUS_FAIL_NOT_OFFBOARD 4
#define GPENMPC_SE3_CONTROL_STATUS_FAIL_MUTUAL_EXCLUSION 5
#define GPENMPC_SE3_CONTROL_STATUS_FAIL_REFERENCE_STALE 6
#define GPENMPC_SE3_CONTROL_STATUS_FAIL_SEGMENT_STALE 7
#define GPENMPC_SE3_CONTROL_STATUS_FAIL_STATE_INVALID 8
#define GPENMPC_SE3_CONTROL_STATUS_FAIL_OUTPUT_INVALID 9

#endif


#ifdef __cplusplus
struct __EXPORT gpenmpc_se3_control_status_s {
#else
struct gpenmpc_se3_control_status_s {
#endif
	uint64_t timestamp;
	uint64_t sample_timestamp;
	uint64_t reference_timestamp;
	uint64_t segment_timestamp;
	uint64_t input_sample_count;
	uint64_t output_publish_count;
	uint64_t rejected_sample_count;
	uint64_t reset_count;
	float dt_s;
	float reference_age_s;
	float segment_age_s;
	float hover_thrust;
	float total_mass_kg;
	float yaw_setpoint_rad;
	float position_ned_m[3];
	float velocity_ned_mps[3];
	float reference_position_ned_m[3];
	float reference_velocity_ned_mps[3];
	float reference_acceleration_ned_mps2[3];
	float nominal_feedback_acceleration_ned_mps2[3];
	float drag_feedforward_acceleration_ned_mps2[3];
	float robust_acceleration_ned_mps2[3];
	float commanded_acceleration_ned_mps2[3];
	float normalized_thrust_ned[3];
	uint8_t control_mode;
	uint8_t failure_reason;
	bool active;
	bool reference_fresh;
	bool segment_fresh;
	bool state_valid;
	bool hover_thrust_fresh;
	bool native_position_controller_disabled;
	bool native_attitude_rate_allocator_enabled;
	bool single_publisher_contract_pass;
	uint8_t _padding0[6]; // required for logger


#ifdef __cplusplus
	static constexpr uint8_t MODE_PX4_NATIVE = 0;
	static constexpr uint8_t MODE_N0_NOMINAL = 1;
	static constexpr uint8_t MODE_R0_ROBUST = 2;
	static constexpr uint8_t FAIL_NONE = 0;
	static constexpr uint8_t FAIL_DISABLED = 1;
	static constexpr uint8_t FAIL_PARAMETER = 2;
	static constexpr uint8_t FAIL_NOT_ARMED = 3;
	static constexpr uint8_t FAIL_NOT_OFFBOARD = 4;
	static constexpr uint8_t FAIL_MUTUAL_EXCLUSION = 5;
	static constexpr uint8_t FAIL_REFERENCE_STALE = 6;
	static constexpr uint8_t FAIL_SEGMENT_STALE = 7;
	static constexpr uint8_t FAIL_STATE_INVALID = 8;
	static constexpr uint8_t FAIL_OUTPUT_INVALID = 9;

#endif
};

#ifdef __cplusplus
namespace px4 {
	namespace msg {
		using GPENMPCSe3ControlStatus = gpenmpc_se3_control_status_s;
	} // namespace msg
} // namespace px4
#endif

/* register this as object request broker structure */
ORB_DECLARE(gpenmpc_se3_control_status);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const gpenmpc_se3_control_status_s& message);
#endif
