/****************************************************************************
 *
 *   Copyright (C) 2021-2022 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/


#pragma once

#include <stddef.h>

#include <uORB/uORB.h>

static constexpr size_t ORB_TOPICS_COUNT{312};
static constexpr size_t orb_topics_count() { return ORB_TOPICS_COUNT; }

/*
 * Returns array of topics metadata
 */
extern const struct orb_metadata *const *orb_get_topics() __EXPORT;

enum class ORB_ID : orb_id_size_t {
	ackermann_velocity_setpoint = 0,
	action_request = 1,
	actuator_armed = 2,
	actuator_armed_rfly = 3,
	actuator_controls_status_0 = 4,
	actuator_controls_status_1 = 5,
	actuator_motors = 6,
	actuator_outputs = 7,
	actuator_outputs_debug = 8,
	actuator_outputs_rfly = 9,
	actuator_outputs_sim = 10,
	actuator_servos = 11,
	actuator_servos_trim = 12,
	actuator_test = 13,
	adc_report = 14,
	airspeed = 15,
	airspeed_validated = 16,
	airspeed_wind = 17,
	arming_check_reply = 18,
	arming_check_request = 19,
	autotune_attitude_control_status = 20,
	aux_global_position = 21,
	battery_status = 22,
	button_event = 23,
	camera_capture = 24,
	camera_status = 25,
	camera_trigger = 26,
	can_interface_status = 27,
	cellular_status = 28,
	collision_constraints = 29,
	config_control_setpoints = 30,
	config_overrides = 31,
	config_overrides_request = 32,
	control_allocator_status = 33,
	cpuload = 34,
	dataman_request = 35,
	dataman_response = 36,
	debug_array = 37,
	debug_key_value = 38,
	debug_value = 39,
	debug_vect = 40,
	differential_pressure = 41,
	differential_velocity_setpoint = 42,
	distance_sensor = 43,
	distance_sensor_mode_change_request = 44,
	ekf2_timestamps = 45,
	esc_report = 46,
	esc_serial_passthru = 47,
	esc_status = 48,
	estimator_aid_src_airspeed = 49,
	estimator_aid_src_aux_global_position = 50,
	estimator_aid_src_aux_vel = 51,
	estimator_aid_src_baro_hgt = 52,
	estimator_aid_src_drag = 53,
	estimator_aid_src_ev_hgt = 54,
	estimator_aid_src_ev_pos = 55,
	estimator_aid_src_ev_vel = 56,
	estimator_aid_src_ev_yaw = 57,
	estimator_aid_src_fake_hgt = 58,
	estimator_aid_src_fake_pos = 59,
	estimator_aid_src_gnss_hgt = 60,
	estimator_aid_src_gnss_pos = 61,
	estimator_aid_src_gnss_vel = 62,
	estimator_aid_src_gnss_yaw = 63,
	estimator_aid_src_gravity = 64,
	estimator_aid_src_mag = 65,
	estimator_aid_src_optical_flow = 66,
	estimator_aid_src_rng_hgt = 67,
	estimator_aid_src_sideslip = 68,
	estimator_attitude = 69,
	estimator_baro_bias = 70,
	estimator_bias3d = 71,
	estimator_ev_pos_bias = 72,
	estimator_event_flags = 73,
	estimator_global_position = 74,
	estimator_gnss_hgt_bias = 75,
	estimator_gps_status = 76,
	estimator_innovation_test_ratios = 77,
	estimator_innovation_variances = 78,
	estimator_innovations = 79,
	estimator_local_position = 80,
	estimator_odometry = 81,
	estimator_optical_flow_vel = 82,
	estimator_selector_status = 83,
	estimator_sensor_bias = 84,
	estimator_states = 85,
	estimator_status = 86,
	estimator_status_flags = 87,
	estimator_wind = 88,
	event = 89,
	external_ins_attitude = 90,
	external_ins_global_position = 91,
	external_ins_local_position = 92,
	failsafe_flags = 93,
	failure_detector_status = 94,
	figure_eight_status = 95,
	flaps_setpoint = 96,
	flight_phase_estimation = 97,
	follow_target = 98,
	follow_target_estimator = 99,
	follow_target_status = 100,
	fuel_tank_status = 101,
	fw_virtual_attitude_setpoint = 102,
	generator_status = 103,
	geofence_result = 104,
	geofence_status = 105,
	gimbal_controls = 106,
	gimbal_device_attitude_status = 107,
	gimbal_device_information = 108,
	gimbal_device_set_attitude = 109,
	gimbal_manager_information = 110,
	gimbal_manager_set_attitude = 111,
	gimbal_manager_set_manual_control = 112,
	gimbal_manager_status = 113,
	gimbal_v1_command = 114,
	goto_setpoint = 115,
	gpenmpc_exec_status = 116,
	gpenmpc_exec_test_status = 117,
	gpenmpc_full_inner_ingress = 118,
	gpenmpc_ground_frame_status = 119,
	gpenmpc_ground_observability_status = 120,
	gpenmpc_hte_arbitration_status = 121,
	gpenmpc_hte_publication = 122,
	gpenmpc_landing_shaping_status = 123,
	gpenmpc_original_hil_receipt = 124,
	gpenmpc_payload_transition_ack = 125,
	gpenmpc_payload_transition_status = 126,
	gpenmpc_se3_control_status = 127,
	gpenmpc_shadow_suggestion = 128,
	gpenmpc_takeoff_phase_status = 129,
	gpenmpc_touchdown_governor_status = 130,
	gpenmpc_trajectory_segment = 131,
	gpenmpc_vertical_control_status = 132,
	gpenmpc_vertical_state_coupling_status = 133,
	gpio_config = 134,
	gpio_in = 135,
	gpio_out = 136,
	gpio_request = 137,
	gps_dump = 138,
	gps_inject_data = 139,
	gripper = 140,
	health_report = 141,
	heater_status = 142,
	home_position = 143,
	hover_thrust_estimate = 144,
	input_rc = 145,
	internal_combustion_engine_control = 146,
	internal_combustion_engine_status = 147,
	iridiumsbd_status = 148,
	irlock_report = 149,
	landing_gear = 150,
	landing_gear_wheel = 151,
	landing_target_innovations = 152,
	landing_target_pose = 153,
	launch_detection_status = 154,
	led_control = 155,
	log_message = 156,
	logger_status = 157,
	mag_worker_data = 158,
	magnetometer_bias_estimate = 159,
	manual_control_input = 160,
	manual_control_setpoint = 161,
	manual_control_switches = 162,
	mavlink_log = 163,
	mavlink_tunnel = 164,
	mc_virtual_attitude_setpoint = 165,
	message_format_request = 166,
	message_format_response = 167,
	mission = 168,
	mission_result = 169,
	mode_completed = 170,
	mount_orientation = 171,
	navigator_mission_item = 172,
	navigator_status = 173,
	npfg_status = 174,
	obstacle_distance = 175,
	obstacle_distance_fused = 176,
	offboard_control_mode = 177,
	onboard_computer_status = 178,
	open_drone_id_arm_status = 179,
	open_drone_id_operator_id = 180,
	open_drone_id_self_id = 181,
	open_drone_id_system = 182,
	orb_multitest = 183,
	orb_test = 184,
	orb_test_large = 185,
	orb_test_medium = 186,
	orb_test_medium_multi = 187,
	orb_test_medium_queue = 188,
	orb_test_medium_queue_poll = 189,
	orb_test_medium_wrap_around = 190,
	orbit_status = 191,
	parameter_primary_set_value_request = 192,
	parameter_primary_set_value_response = 193,
	parameter_remote_set_value_request = 194,
	parameter_remote_set_value_response = 195,
	parameter_reset_request = 196,
	parameter_set_used_request = 197,
	parameter_set_value_request = 198,
	parameter_set_value_response = 199,
	parameter_update = 200,
	ping = 201,
	position_controller_landing_status = 202,
	position_controller_status = 203,
	position_setpoint = 204,
	position_setpoint_triplet = 205,
	power_button_state = 206,
	power_monitor = 207,
	pps_capture = 208,
	pure_pursuit_status = 209,
	pwm_input = 210,
	px4io_status = 211,
	qshell_req = 212,
	qshell_retval = 213,
	radio_status = 214,
	rate_ctrl_status = 215,
	rc_channels = 216,
	rc_parameter_map = 217,
	register_ext_component_reply = 218,
	register_ext_component_request = 219,
	rover_attitude_setpoint = 220,
	rover_attitude_status = 221,
	rover_position_setpoint = 222,
	rover_rate_setpoint = 223,
	rover_rate_status = 224,
	rover_steering_setpoint = 225,
	rover_throttle_setpoint = 226,
	rover_velocity_status = 227,
	rpm = 228,
	rtl_status = 229,
	rtl_time_estimate = 230,
	safety_button = 231,
	satellite_info = 232,
	sensor_accel = 233,
	sensor_accel_fifo = 234,
	sensor_airflow = 235,
	sensor_baro = 236,
	sensor_combined = 237,
	sensor_correction = 238,
	sensor_gnss_relative = 239,
	sensor_gps = 240,
	sensor_gyro = 241,
	sensor_gyro_fft = 242,
	sensor_gyro_fifo = 243,
	sensor_hygrometer = 244,
	sensor_mag = 245,
	sensor_optical_flow = 246,
	sensor_preflight_mag = 247,
	sensor_selection = 248,
	sensor_uwb = 249,
	sensors_status_baro = 250,
	sensors_status_imu = 251,
	sensors_status_mag = 252,
	spoilers_setpoint = 253,
	system_power = 254,
	takeoff_status = 255,
	task_stack_info = 256,
	tecs_status = 257,
	telemetry_status = 258,
	tiltrotor_extra_controls = 259,
	timesync_status = 260,
	trajectory_setpoint = 261,
	trajectory_setpoint6dof = 262,
	transponder_report = 263,
	tune_control = 264,
	uavcan_parameter_request = 265,
	uavcan_parameter_value = 266,
	ulog_stream = 267,
	ulog_stream_ack = 268,
	unregister_ext_component = 269,
	vehicle_acceleration = 270,
	vehicle_air_data = 271,
	vehicle_angular_acceleration_setpoint = 272,
	vehicle_angular_velocity = 273,
	vehicle_angular_velocity_groundtruth = 274,
	vehicle_attitude = 275,
	vehicle_attitude_groundtruth = 276,
	vehicle_attitude_setpoint = 277,
	vehicle_command = 278,
	vehicle_command_ack = 279,
	vehicle_command_mode_executor = 280,
	vehicle_constraints = 281,
	vehicle_control_mode = 282,
	vehicle_global_position = 283,
	vehicle_global_position_groundtruth = 284,
	vehicle_gps_position = 285,
	vehicle_imu = 286,
	vehicle_imu_status = 287,
	vehicle_land_detected = 288,
	vehicle_local_position = 289,
	vehicle_local_position_groundtruth = 290,
	vehicle_local_position_setpoint = 291,
	vehicle_magnetometer = 292,
	vehicle_mocap_odometry = 293,
	vehicle_odometry = 294,
	vehicle_optical_flow = 295,
	vehicle_optical_flow_vel = 296,
	vehicle_rates_setpoint = 297,
	vehicle_roi = 298,
	vehicle_status = 299,
	vehicle_thrust_setpoint = 300,
	vehicle_thrust_setpoint_virtual_fw = 301,
	vehicle_thrust_setpoint_virtual_mc = 302,
	vehicle_torque_setpoint = 303,
	vehicle_torque_setpoint_virtual_fw = 304,
	vehicle_torque_setpoint_virtual_mc = 305,
	vehicle_visual_odometry = 306,
	velocity_limits = 307,
	vtol_vehicle_status = 308,
	wheel_encoders = 309,
	wind = 310,
	yaw_estimator_status = 311,

	INVALID
};

const struct orb_metadata *get_orb_meta(ORB_ID id);
