function [sample,audit,next]=decodeAtomicOdometry(message,rxNs,nowNs,generation,expected,origin,clock,previous)
% Pure ODOMETRY(331) adapter; never assembles separate LP/attitude packets.
% PX4 explicitly publishes diagonal variances only, leaving other entries
% NaN. Preserve that documented unknown information; never fill it with zero.
% Unknown/negative required variances and undeclared patterns are rejected.
% The original reset_counter is retained. A reset is a hard-invalid input to
% current A1, not permission to infer/reset the estimator or its world origin.
if nargin<8,previous=struct();end
sample=[];next=previous;
audit=struct('accepted',false,'reason','MALFORMED_INPUT','raw_payload',[], ...
    'source','PX4_EKF2_MAVLINK_ODOMETRY_331','plant_truth_used',false,'hardware_actions',0);
try
    demand(isscalar(message)&&all(isfield(message,{'MsgID','Payload','SystemID','ComponentID'}))&& ...
        double(message.MsgID)==331,'NOT_ATOMIC_ODOMETRY_331');
    p=message.Payload;audit.raw_payload=p;
    demand(all(isfield(expected,{'uid','system_id','component_id','boot_generation', ...
        'maximum_age_ns','maximum_clock_uncertainty_ns'})),'EXPECTED_BOUNDARY_MISSING');
    demand((isstring(expected.uid)&&isscalar(expected.uid))||(ischar(expected.uid)&&isrow(expected.uid)), ...
        'UID_MUST_BE_EXACT_TEXT_NOT_DOUBLE');
    demand(string(expected.uid)==string(gpenmpc_device_identity('uid'))&& ...
        double(message.SystemID)==expected.system_id&&double(message.ComponentID)==expected.component_id, ...
        'STREAM_OR_UID_IDENTITY_MISMATCH');
    demand(validInteger(rxNs)&&validInteger(nowNs)&&rxNs<=nowNs&& ...
        validPositive(expected.maximum_age_ns)&&nowNs-rxNs<=expected.maximum_age_ns, ...
        'STALE_OR_FUTURE_RECEIVE_TIME');
    demand(validInteger(generation)&&generation>=1&&validInteger(expected.boot_generation), ...
        'GENERATION_OR_BOOT_INVALID');
    demand(isstruct(origin)&&isscalar(origin)&&isequal(origin.verified,true)&& ...
        string(origin.schema)=="CANONICAL_TASK_GROUND_ORIGIN_V1"&&validVector(origin.origin_ned_m,3), ...
        'CANONICAL_ORIGIN_NOT_BOUND');
    required={'time_usec','frame_id','child_frame_id','estimator_type','reset_counter', ...
        'x','y','z','vx','vy','vz','q','rollspeed','pitchspeed','yawspeed', ...
        'pose_covariance','velocity_covariance'};
    demand(all(isfield(p,required)),'ODOMETRY_FIELD_MISSING');
    demand(isa(p.time_usec,'uint64')&&isscalar(p.time_usec)&&p.time_usec>0&& ...
        p.time_usec<=uint64(floor(flintmax/1000)),'SOURCE_TIMESTAMP_TYPE_OR_EXACTNESS');
    demand(double(p.frame_id)==1&&double(p.child_frame_id)==1&&double(p.estimator_type)==8, ...
        'FRAME_OR_ESTIMATOR_IDENTITY_MISMATCH');
    demand(isa(p.reset_counter,'uint8')&&isscalar(p.reset_counter),'RESET_COUNTER_TYPE_INVALID');
    core=double([p.x;p.y;p.z;p.vx;p.vy;p.vz;p.q(:);p.rollspeed;p.pitchspeed;p.yawspeed]);
    demand(numel(core)==13&&all(isfinite(core))&&abs(norm(double(p.q(:)))-1)<=1e-6, ...
        'NONFINITE_OR_NONUNIT_ESTIMATE');
    [pose,validPose,poseInfo]=covariance(p.pose_covariance,[1,7,12,16,19,21]);
    [velocity,validVelocity,velocityInfo]=covariance(p.velocity_covariance,[1,7,12]);
    audit.pose_covariance_valid=validPose;audit.velocity_covariance_valid=validVelocity;
    audit.pose_covariance_information=poseInfo;audit.velocity_covariance_information=velocityInfo;
    demand(validPose&&validVelocity,'UNKNOWN_NONFINITE_OR_INVALID_COVARIANCE');
    if isfield(p,'quality')
        quality=double(p.quality);audit.optional_quality=quality;
        demand(isscalar(quality)&&isfinite(quality)&&quality==fix(quality)&&quality>=0&&quality<=100, ...
            'ODOMETRY_QUALITY_FAILED_OR_INVALID');
    end
    demand(all(isfield(clock,{'valid','board_to_host_offset_ns','uncertainty_ns'}))&& ...
        isequal(clock.valid,true)&&isfinite(clock.board_to_host_offset_ns)&& ...
        isscalar(clock.board_to_host_offset_ns)&&validInteger(clock.uncertainty_ns)&& ...
        validPositive(expected.maximum_clock_uncertainty_ns)&& ...
        clock.uncertainty_ns<=expected.maximum_clock_uncertainty_ns,'SOURCE_CLOCK_UNVERIFIED');
    sourceNs=double(p.time_usec*uint64(1000));mapped=sourceNs+clock.board_to_host_offset_ns;
    audit.source_age_upper_ns=nowNs-(mapped-clock.uncertainty_ns);
    demand(mapped-clock.uncertainty_ns<=rxNs&& ...
        audit.source_age_upper_ns<=expected.maximum_age_ns,'STALE_OR_FUTURE_SOURCE_TIME');
    if ~isempty(fieldnames(previous))
        demand(all(isfield(previous,{'last_time_usec','last_generation','reset_counter','boot_generation'})), ...
            'PREVIOUS_STATE_MALFORMED');
        demand(previous.boot_generation==expected.boot_generation,'BOOT_GENERATION_CHANGED');
        demand(p.time_usec>previous.last_time_usec&&generation==previous.last_generation+1, ...
            'NONADVANCING_TIMESTAMP_OR_GENERATION');
        demand(p.reset_counter==previous.reset_counter,'PX4_ODOMETRY_RESET_COUNTER_CHANGED');
    end
    position=double([p.x;p.y;p.z])+double(origin.origin_ned_m(:));
    sample=struct('source','PX4_EKF2_MAVLINK_ODOMETRY_331','atomic_estimate',true, ...
        'plant_truth_used',false,'uid',string(expected.uid),'system_id',expected.system_id, ...
        'component_id',expected.component_id,'boot_generation',expected.boot_generation, ...
        'sample_timestamp_ns',sourceNs,'odometry_reset_counter',double(p.reset_counter), ...
        'odometry_reset_counter_raw',p.reset_counter,'odometry_frame_id',double(p.frame_id), ...
        'odometry_child_frame_id',double(p.child_frame_id),'odometry_estimator_type',double(p.estimator_type), ...
        'position_ned_m',position,'velocity_ned_mps',double([p.vx;p.vy;p.vz]), ...
        'quaternion_wxyz_body_to_ned',double(p.q(:)), ...
        'omega_frd_rad_s',double([p.rollspeed;p.pitchspeed;p.yawspeed]), ...
        'position_rx_ns',double(rxNs),'attitude_rx_ns',double(rxNs),'rates_rx_ns',double(rxNs), ...
        'position_generation',double(generation),'attitude_generation',double(generation), ...
        'rates_generation',double(generation),'position_valid',true,'attitude_valid',true,'rates_valid',true, ...
        'pose_covariance_upper',p.pose_covariance,'velocity_covariance_upper',p.velocity_covariance, ...
        'pose_covariance_matrix',pose,'velocity_covariance_matrix',velocity, ...
        'pose_covariance_information',poseInfo,'velocity_covariance_information',velocityInfo, ...
        'task_sha256',origin.task_sha256,'mapped_source_host_ns',mapped, ...
        'source_clock_uncertainty_ns',clock.uncertainty_ns);
    next=struct('last_time_usec',p.time_usec,'last_generation',generation, ...
        'reset_counter',p.reset_counter,'boot_generation',expected.boot_generation);
    audit.accepted=true;audit.reason='FRESH_ATOMIC_ODOMETRY__EXPLICIT_TASK_ORIGIN';
catch problem
    sample=[];next=previous;audit.reason=problem.message;audit.error_identifier=problem.identifier;
end
end
function demand(yes,reason)
if ~isscalar(yes)||~yes,error('gpenmpcTaskIo:AtomicBoundary','%s',reason);end
end
function yes=validInteger(v)
yes=isnumeric(v)&&isreal(v)&&isscalar(v)&&isfinite(v)&&v>=0&&v==fix(v)&&v<=flintmax;
end
function yes=validPositive(v)
yes=isnumeric(v)&&isreal(v)&&isscalar(v)&&isfinite(v)&&v>0;
end
function yes=validVector(v,n)
yes=isnumeric(v)&&isreal(v)&&isvector(v)&&numel(v)==n&&all(isfinite(v(:)));
end
function [matrix,valid,information]=covariance(upper,publishedDiagonal)
matrix=nan(6);valid=false;
information=struct('pattern','INVALID','complete_matrix_known',false, ...
    'PSD_verified',false,'required_variances_finite_nonnegative',false, ...
    'unknown_entries_preserved',0,'unknown_entries_filled',0);
if ~isnumeric(upper)||~isreal(upper)||~isvector(upper)||numel(upper)~=21||any(isinf(upper)),return;end
upper=double(upper(:));k=0;
for i=1:6
    for j=i:6,k=k+1;matrix(i,j)=double(upper(k));matrix(j,i)=double(upper(k));end
end
information.unknown_entries_preserved=nnz(isnan(upper));
if all(isfinite(upper))
    % Only representation roundoff, no performance uncertainty threshold.
    tolerance=128*6*eps(max(1,norm(matrix,2)));
    valid=all(diag(matrix)>=0)&&min(eig(matrix))>=-tolerance;
    information.pattern='FULL_FINITE_COVARIANCE';information.complete_matrix_known=true;
    information.PSD_verified=valid;information.required_variances_finite_nonnegative=all(diag(matrix)>=0);
else
    unknown=setdiff(1:21,publishedDiagonal);
    valid=all(isfinite(upper(publishedDiagonal)))&&all(upper(publishedDiagonal)>=0)&&all(isnan(upper(unknown)));
    information.pattern='PX4_V116_PUBLISHED_DIAGONAL_VARIANCES_ONLY';
    information.required_variances_finite_nonnegative=all(isfinite(upper(publishedDiagonal)))&&all(upper(publishedDiagonal)>=0);
end
end
