function [packet,audit]=encodeA1Reference(reference,origin,target,timeBootMs,yawNedRad)
% Pure typed P/V/A/yaw encoder. No socket/serial/arm/mapping authority.
% A1 acceleration is already composed by the authoritative physical runtime;
% do not add compensation again. MAVLink msg84 has no jerk field.
assert(isstruct(reference)&&isscalar(reference)&& ...
    all(isfield(reference,{'accepted','publication_allowed','plant_truth_used', ...
    'generation','reference_ned','board_control_mode'}))&& ...
    isequal(reference.accepted,true)&&isequal(reference.publication_allowed,true)&& ...
    isequal(reference.plant_truth_used,false)&& ...
    string(reference.board_control_mode)=="RA_CTRL_MODE_NOMINAL_SINGLE_PUBLISHER", ...
    'gpenmpcTaskIo:ReferenceAuthority','Not an accepted causal A1 single-publisher reference.');
assert(isstruct(origin)&&isscalar(origin)&&isfield(origin,'verified')&&isequal(origin.verified,true)&& ...
    string(origin.schema)=="CANONICAL_TASK_GROUND_ORIGIN_V1", ...
    'gpenmpcTaskIo:OriginNotBound','Canonical task origin is required.');
for n={'system_id','component_id'}
    v=target.(n{1});assert(isnumeric(v)&&isscalar(v)&&isfinite(v)&&v==fix(v)&&v>=1&&v<=255, ...
        'gpenmpcTaskIo:Target','Exact MAVLink target is required.');
end
assert(isa(timeBootMs,'uint32')&&isscalar(timeBootMs), ...
    'gpenmpcTaskIo:ReferenceClock','Supply measured/mapped board boot milliseconds as uint32.');
assert(isnumeric(yawNedRad)&&isreal(yawNedRad)&&isscalar(yawNedRad)&&isfinite(yawNedRad), ...
    'gpenmpcTaskIo:Yaw','Explicit finite NED yaw is required; no implicit frame conversion.');
r=reference.reference_ned;
required={'position_ned_m','velocity_ned_mps','acceleration_ned_mps2','jerk_ned_mps3'};
assert(all(isfield(r,required)),'gpenmpcTaskIo:ReferenceSchema','P/V/A and source jerk fields are required.');
for k=1:numel(required),assert(valid3(r.(required{k})),'gpenmpcTaskIo:ReferenceNonfinite','Bad %s.',required{k});end
assert(valid3(origin.origin_ned_m),'gpenmpcTaskIo:OriginNotBound','Origin must be a finite three-vector.');
assert(isnumeric(reference.generation)&&isscalar(reference.generation)&&isfinite(reference.generation)&& ...
    reference.generation>=1&&reference.generation==fix(reference.generation), ...
    'gpenmpcTaskIo:ReferenceGeneration','Invalid reference generation.');
p=double(r.position_ned_m(:))-double(origin.origin_ned_m(:));
v=double(r.velocity_ned_mps(:));a=double(r.acceleration_ned_mps2(:));
values=single([p;v;a;double(yawNedRad)]);
assert(all(isfinite(values)),'gpenmpcTaskIo:ReferenceFloatOverflow','Reference cannot be represented in MAVLink float32.');
payload=struct('time_boot_ms',timeBootMs,'x',values(1),'y',values(2),'z',values(3), ...
    'vx',values(4),'vy',values(5),'vz',values(6),'afx',values(7),'afy',values(8),'afz',values(9), ...
    'yaw',values(10),'yaw_rate',single(0),'type_mask',uint16(2048), ...
    'target_system',uint8(target.system_id),'target_component',uint8(target.component_id), ...
    'coordinate_frame',uint8(1));
packet=struct('MsgID',uint32(84),'message_name','SET_POSITION_TARGET_LOCAL_NED','Payload',payload);
audit=struct('schema','A1_TYPED_REFERENCE_ENCODING_V1','generation',reference.generation, ...
    'task_sha256',origin.task_sha256,'reference_task_world_ned',r, ...
    'board_local_position_ned_m',p,'yaw_ned_rad',double(yawNedRad), ...
    'source_jerk_ned_mps3',double(r.jerk_ned_mps3(:)), ...
    'jerk_transmitted',false,'jerk_semantics', ...
    'HOST_BASE_REFERENCE_JERK_BEFORE_GP_ACCELERATION_COMPOSITION', ...
    'acceleration_already_composed_by_source',true,'compensation_reapplied',false, ...
    'float32_quantization_max_abs',max(abs(double(values)-[p;v;a;double(yawNedRad)])), ...
    'coordinate_translation_fitted_online',false,'truth_used',false,'hardware_actions',0);
end
function yes=valid3(v)
yes=isnumeric(v)&&isreal(v)&&isvector(v)&&numel(v)==3&&all(isfinite(v(:)));
end
