function [origin,task,receipt]=loadCanonicalTaskOrigin(receiptPath)
% Read-only task binding. Never derives a ground plane from observed truth.
receipt=jsondecode(fileread(receiptPath));
assert(string(receipt.schema)=="GPENMPC_EXACT_CAMBRIDGE_REFERENCE_PACKAGE_V1"&& ...
    string(receipt.mission_id)=="MU_CAMBRIDGE_MA_02"&& ...
    string(receipt.internal_method_id)=="A1_COORDINATED_PHYSICAL", ...
    'gpenmpcTaskIo:TaskIdentity','Not the canonical Cambridge A1 reference package.');
assert(receipt.audit.checks_total==receipt.audit.checks_passed&& ...
    all([receipt.audit.checks.pass]),'gpenmpcTaskIo:TaskAudit','Task binding did not pass.');
verifyFile(receipt.task);
files=receipt.source_files;
index=find(endsWith(string({files.path}),'CAMBRIDGE_REPRESENTATIVE_PHYSICAL_MISSION_V1.json'));
assert(isscalar(index),'gpenmpcTaskIo:MissionIdentity','Exact mission contract is ambiguous.');
verifyFile(files(index));cfg=jsondecode(fileread(files(index).path));
assert(strcmpi(files(index).sha256, ...
    'E4B20DE53ACC4AA442ACD8262AE5639AEE1644505E12362C62520AE9F6CB6013'), ...
    'gpenmpcTaskIo:MissionIdentity','Unexpected source mission contract.');
loaded=load(receipt.task.path,'physicalTask');task=loaded.physicalTask;
assert(string(task.schema)=="GPENMPC_CAMBRIDGE_PHYSICAL_CLOSED_LOOP_TASK_V1"&& ...
    string(task.mission_id)==string(cfg.mission_id)&& ...
    string(task.planner_id)==string(cfg.planner_id)&& ...
    isequal(double(task.visit_order(:)),double(cfg.visit_order(:)))&& ...
    strcmpi(task.mission_payload_sha256,cfg.mission_payload_sha256)&& ...
    strcmpi(task.plan_payload_sha256,cfg.plan_payload_sha256)&& ...
    strcmpi(task.reference_trace_sha256,cfg.source_trace.sha256), ...
    'gpenmpcTaskIo:TaskSourceMismatch','Loaded task and immutable mission do not agree.');
first=double(task.reference.position_m(1,:)).';last=double(task.reference.position_m(end,:)).';
ground=double(cfg.physical_service_profile.contact_plane_up_m);
assert(numel(first)==3&&all(isfinite([first;last;ground]))&& ...
    isequal(first(1:2),last(1:2))&& ...
    task.physical_service.delivery_count==4&&task.physical_service.ground_dwell_s==8&& ...
    cfg.physical_service_profile.payload_change_only_after_dual_ground_and_disarmed, ...
    'gpenmpcTaskIo:TaskOrigin','Depot return or physical-delivery definition differs.');
origin=struct('schema','CANONICAL_TASK_GROUND_ORIGIN_V1','verified',true, ...
    'task_receipt_path',char(receiptPath),'task_sha256',upper(string(receipt.task.sha256)), ...
    'mission_contract_sha256',upper(string(files(index).sha256)), ...
    'mission_id',string(task.mission_id),'planner_id',string(task.planner_id), ...
    'origin_up_m',[first(1:2);ground], ...
    'origin_ned_m',[first(1:2);-ground], ...
    'initial_flight_reference_up_m',first,'final_flight_reference_up_m',last, ...
    'reference_duration_s',double(task.reference.global_time_s(end)), ...
    'final_native_landing_required',true, ...
    'definition','TASK_DEPOT_XY_AND_EXPLICIT_MISSION_CONTACT_PLANE__NOT_INITIAL_TRUTH', ...
    'board_local_to_task_world','p_task_ned = p_board_local_ned + origin_ned_m', ...
    'task_world_to_board_local','p_board_local_ned = p_task_ned - origin_ned_m', ...
    'live_origin_alignment_verified',false,'hardware_actions',0);
end
function verifyFile(row)
info=dir(row.path);
assert(isscalar(info)&&~info.isdir&&info.bytes==row.bytes&& ...
    strcmpi(m600check.fileSha256(row.path),row.sha256), ...
    'gpenmpcTaskIo:SourceHashMismatch','Task source path/bytes/SHA differs: %s',row.path);
end
