function summary=analyze_native_hover_prewrite(outputDir)
% Reconstruct results from the retained MAT file.
arguments,outputDir (1,1) string,end
% Write derived analysis separately from the retained run.
if ~isfolder(outputDir),mkdir(outputDir);end
build=fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(build,'m600_coptersim','matlab_validation'));
runRoot=gpenmpc_external_path('native_hover_prewrite_recording');
input=fullfile(runRoot,'INNER_MATLAB','RAW_MATLAB_HIL.mat');x=load(input,'result');r=x.result;e=r.transport_evidence;
idx=find(strcmp({r.events.kind},'EXCEPTION'),1);cut=r.events(idx).time_s;
offset=(e.fixed_best_timesync.offset_lower_s+e.fixed_best_timesync.offset_upper_s)/2;
uncertainty=e.fixed_best_timesync.rtt_s/2+e.utc_pair_uncertainty_s+.0005;
rows=struct('raw_index',{},'topic',{},'rx_s',{},'source_s',{},'mapped_source_s',{}, ...
    'source_age_at_failure_s',{},'rx_age_at_failure_s',{},'flags',{},'payload',{});
for k=1:numel(e.raw_mavlink)
    a=e.raw_mavlink{k};if a.rx_s>cut,continue;end
    if ~ismember(a.topic,{'ATTITUDE','LOCAL_POSITION_NED','ESTIMATOR_STATUS','HEARTBEAT','EXTENDED_SYS_STATE','PARAM_VALUE'}),continue;end
    p=a.message.Payload;source=NaN;flags=NaN;
    if isfield(p,'time_boot_ms'),source=double(p.time_boot_ms)/1000;end
    if strcmp(a.topic,'ESTIMATOR_STATUS'),source=double(p.time_usec)/1e6;flags=double(p.flags);end
    rows(end+1)=struct('raw_index',k,'topic',a.topic,'rx_s',a.rx_s,'source_s',source, ...
        'mapped_source_s',source+offset,'source_age_at_failure_s',cut-source-offset, ...
        'rx_age_at_failure_s',cut-a.rx_s,'flags',flags,'payload',p); %#ok<AGROW>
end
s=struct('now_s',cut,'clock_valid',isempty(e.non_model_fatal)&&~e.clock_origin_changed, ...
    'clock_uncertainty_s',uncertainty);
topics={'ATTITUDE','LOCAL_POSITION_NED','ESTIMATOR_STATUS'};names={'attitude_observation','estimate','estimator_status_observation'};
streams=struct();
for q=1:3
    rr=rows(strcmp({rows.topic},topics{q}));t=[rr.source_s];rx=[rr.rx_s];
    progress=[true,diff(t)>0];last=rr(find(progress,1,'last'));cur=rr(end);
    o=struct('payload',cur.payload,'raw_source_time_s',last.source_s,'mapped_source_time_s',last.mapped_source_s, ...
        'rx_s',last.rx_s,'latest_rx_s',cur.rx_s,'source_progress_rx_s',last.rx_s, ...
        'source_generation_count',nnz(progress),'source_advance_count',nnz(progress)-1, ...
        'duplicate_count',nnz(diff(t)==0),'source_reversal_latched',any(diff(t)<0),'source_invalid_latched',any(~isfinite(t)));
    if q==2,p=last.payload;o.position_ned_m=double([p.x,p.y,p.z]);o.velocity_ned_mps=double([p.vx,p.vy,p.vz]);end
    s.(names{q})=o;
    streams.(topics{q})=struct('count',numel(rr),'last',cur,'maximum_rx_gap_s',max(diff(rx)), ...
        'source_reversals',nnz(diff(t)<0),'duplicates',nnz(diff(t)==0), ...
        'source_advances',nnz(diff(t)>0),'essential_payload_at_failure',cur.payload);
end
reconstructed=m600check.evaluateNativeHoverTelemetry(s,r.config);
for name={'HEARTBEAT','EXTENDED_SYS_STATE'}
    rr=rows(strcmp({rows.topic},name{1}));streams.(name{1})=struct('count',numel(rr),'last',rr(end));
end
params=rows(strcmp({rows.topic},'PARAM_VALUE'));
paramTimeline=struct('raw_index',{},'rx_s',{},'name',{},'mav_type',{},'raw_bits',{});
for k=1:numel(params)
    p=params(k).payload;
    paramTimeline(end+1)=struct('raw_index',params(k).raw_index,'rx_s',params(k).rx_s, ...
        'name',strtrim(strrep(char(p.param_id),char(0),'')),'mav_type',double(p.param_type), ...
        'raw_bits',upper(dec2hex(typecast(single(p.param_value),'uint32'),8))); %#ok<AGROW>
end
truthRows=struct('index',{},'rx_s',{},'source_s',{},'mapped_s',{},'rx_lag_s',{},'bytes',{});
diagRows=struct('index',{},'rx_s',{},'source_s',{},'failure',{},'ground',{});
for k=1:numel(e.raw_truth_datagrams)
    a=e.raw_truth_datagrams{k};if a.rx_s>cut,continue;end
    b=uint8(a.bytes);
    if numel(b)==264
        d=typecast(b(9:end),'double');diagRows(end+1)=struct('index',k,'rx_s',a.rx_s,'source_s',d(3),'failure',d(1),'ground',d(5)); %#ok<AGROW>
    elseif numel(b)==168
        d=typecast(b(113:end),'double');mapped=d(1)+e.coptersim_start_utc_s-e.utc_zero_s;
        truthRows(end+1)=struct('index',k,'rx_s',a.rx_s,'source_s',d(1),'mapped_s',mapped, ...
            'rx_lag_s',a.rx_s-mapped,'bytes',numel(b)); %#ok<AGROW>
    end
end
timeRows=struct('index',{},'rx_s',{},'start_ms',{},'current_ms',{},'counter',{},'rx_lag_s',{});
for k=1:numel(e.raw_clock_datagrams)
    a=e.raw_clock_datagrams{k};if a.rx_s>cut,continue;end
    d=typecast(uint8(a.bytes(9:32)),'int64');
    timeRows(end+1)=struct('index',k,'rx_s',a.rx_s,'start_ms',double(d(1)),'current_ms',double(d(2)), ...
        'counter',double(d(3)),'rx_lag_s',e.utc_zero_s+a.rx_s-double(d(2))/1000); %#ok<AGROW>
end
% The failed snapshot was not retained. Report the interval from the last
% model decode to the exception as the possible now_s range.
bracket=[diagRows(end).rx_s,cut];timeline=struct('now_s',{},'passed',{},'failure',{},'report',{});
for t=unique([bracket,linspace(bracket(1),bracket(2),5)])
    probe=s;probe.now_s=t;v=m600check.evaluateNativeHoverTelemetry(probe,r.config);
    timeline(end+1)=struct('now_s',t,'passed',v.passed,'failure',v.failure,'report',v); %#ok<AGROW>
end
clockAtom=struct('selected_counter',timeRows(end).counter,'dequeue_rx_s',timeRows(end).rx_s, ...
    'packet_current_utc_ms',timeRows(end).current_ms, ...
    'packet_current_mapped_host_s',timeRows(end).current_ms/1000-e.utc_zero_s, ...
    'adapter_time_heartbeat_lag_s',timeRows(end).rx_lag_s, ...
    'configured_max_lag_s',r.config.clock_max_time_heartbeat_lag_s, ...
    'lag_check_passed',timeRows(end).rx_lag_s<=r.config.clock_max_time_heartbeat_lag_s, ...
    'last_dequeue_to_exception_s',cut-timeRows(end).rx_s, ...
    'time_heartbeat_rx_max_age_s',r.config.clock_max_time_heartbeat_age_s, ...
    'previous_drain_rx_s',timeRows(1).rx_s,'dequeue_gap_s',timeRows(2).rx_s-timeRows(1).rx_s, ...
    'historical_batch_count',numel(timeRows)-1, ...
    'timestamp_semantics','rx_s = nowS() after MATLAB read/dequeue; no kernel/network arrival timestamp recorded', ...
    'first_sufficient_ready_failure','timeHeartbeatLag > configured .25 makes mappingValid false independently of current ATT/LP/EST', ...
    'not_uniquely_identified','No SO_TIMESTAMP/OS arrival timing; cannot separate producer/network/OS residence from MATLAB unpolled queue per packet.', ...
    'code_proven_mechanism','waitParameter polls MAVLink parameters and pause only; time/truth udpport drain occurs only in snapshot after 75 reads.', ...
    'one_hz_distinction','Frozen lag compares currentUTC with dequeue time and remains fixed until the next packet; snapshot calls do not recompute packet age.', ...
    'next_minimal_candidate','Drain the owned time/truth sockets inside waitParameter, retain the 0.25 s limit, and capture the first failed snapshot with its clock packet.');
sWithActualClock=s;sWithActualClock.clock_valid=false;
actualClockReconstruction=m600check.evaluateNativeHoverTelemetry(sWithActualClock,r.config);
summary=struct('classification','HOST_RAW_RECONSTRUCTION', ...
    'input',input,'input_sha256',sha(input),'exception',r.events(idx), ...
    'config_bounds',struct('state_max_age_s',r.config.state_max_age_s,'heartbeat_max_age_s',r.config.heartbeat_max_age_s, ...
    'maximum_truth_lag_s',r.config.maximum_truth_lag_s,'clock_max_uncertainty_s',r.config.clock_max_uncertainty_s), ...
    'best_timesync',e.fixed_best_timesync,'clock_uncertainty_s',uncertainty, ...
    'first_fatal',e.first_fatal,'non_model_fatal',e.non_model_fatal,'clock_origin_changed',e.clock_origin_changed, ...
    'streams',streams,'reconstructed_streams_assuming_clock_valid',reconstructed, ...
    'sufficient_clock_failure',clockAtom,'reconstructed_with_observed_clock_rejection',actualClockReconstruction, ...
    'failed_snapshot_not_retained',true,'snapshot_lower_upper_bracket_s',bracket,'snapshot_bracket_probes',timeline, ...
    'parameters',paramTimeline,'parameter_response_count_before_failure',numel(paramTimeline), ...
    'last_truth',truthRows(end),'last_diagnostic',diagRows(end),'time_rows',timeRows, ...
    'truth_count_before_exception',numel(truthRows),'diagnostic_count_before_exception',numel(diagRows), ...
    'max_historical_truth_dequeue_lag_s',max([truthRows.rx_lag_s]), ...
    'last_truth_age_at_exception_s',cut-truthRows(end).mapped_s, ...
    'last_truth_rx_age_at_exception_s',cut-truthRows(end).rx_s, ...
    'first_model_failure',r.first_model_failure,'actual_counts',r.counts,'fresh_final_safe_state',r.fresh_final_safe_state, ...
    'hardware_actions',0,'COM_UDP_open',0,'limitations','The exact failed snapshot and intra-snapshot callback order are unavailable; exception-time reconstruction has limited resolution.');
compact=rmfield(rows,'payload');writetable(struct2table(compact),fullfile(outputDir,'MAV_BEFORE_FAILURE.csv'));
writetable(struct2table(truthRows),fullfile(outputDir,'TRUTH_DEQUEUE_TIMELINE.csv'));
writetable(struct2table(diagRows),fullfile(outputDir,'DIAGNOSTIC_DEQUEUE_TIMELINE.csv'));
fid=fopen(fullfile(outputDir,'PREWRITE_RAW_RECONSTRUCTION.json'),'w');assert(fid>=0);c=onCleanup(@()fclose(fid)); %#ok<NASGU>
fwrite(fid,jsonencode(summary,PrettyPrint=true),'char');
disp(jsonencode(struct('exception',cut,'clock_atom',clockAtom,'bracket',bracket, ...
    'last_truth',truthRows(end),'last_diag',diagRows(end),'last_parameter',paramTimeline(end)),PrettyPrint=true));
end
function h=sha(path)
fid=fopen(path,'rb');assert(fid>=0);c=onCleanup(@()fclose(fid)); %#ok<NASGU>
md=java.security.MessageDigest.getInstance('SHA-256');md.update(fread(fid,Inf,'*uint8'));
h=upper(reshape(dec2hex(typecast(md.digest(),'uint8'),2).',1,[]));
end
