function receipt=build_live_task_package(outputRoot)
% BUILD_LIVE_TASK_PACKAGE Package the selected delivery task and planning assets.
arguments
    outputRoot (1,1) string
end
assert(~isfolder(outputRoot)&&~isfile(outputRoot), ...
    'gpenmpcNative:LiveTaskFreshRoot','Fresh output root required.');

work=string(gpenmpc_external_path('native_visual_host_runtime'));
projectRoot=string(gpenmpc_external_path('gp_tracking_method_project'));
parent=string(fileparts(fileparts(work)));
addpath(fullfile(parent,'matlab'));
addpath(fullfile(work,'src'),'-begin');
rehash path;
assets=gpenmpcNative.loadCurrentAssets(work);

sourcePath=gpenmpc_external_path('live_task_source_contract');
source=jsondecode(fileread(sourcePath));
dataRoot=fullfile(projectRoot,'matlab','data');
base=fullfile(string(source.source_roots.p2_task_source_root), ...
    string(source.source_roots.p2_source_case_base_relative));
task=gpenmpcLoadIndependentDevelopmentTask( ...
    fullfile(gpenmpc_external_path('fixed_timing_robust_reference'),'B0_FIXED_TIMING_ROBUST_SE3'),dataRoot);
deliveryPath=fullfile(work,'config', ...
    'CURRENT_PHYSICAL_DELIVERY_LIFECYCLE_V1.json');
delivery=jsondecode(fileread(deliveryPath));
physicalTask=gpenmpcNative.buildCurrentPhysicalClosedLoopTaskV20(task,delivery);

reference=physicalTask.reference;
assert(abs(double(physicalTask.mission_config.simulation.sample_period_s)-0.01) ...
    <=1e-12,'gpenmpcNative:LiveTaskDt','Unexpected plant/reference dt.');
assert(numel(unique(reference.leg_index,'stable'))==5 ...
    && nnz(reference.phase_code==11)>0 ...
    && nnz(reference.phase_code==21)>0, ...
    'gpenmpcNative:LiveTaskLifecycle','Delivery lifecycle is incomplete.');
assert(nnz(diff(reference.payload_kg)~=0)==4, ...
    'gpenmpcNative:LiveTaskPayload','Expected four grounded unloads.');

mkdir(outputRoot);
matPath=fullfile(outputRoot,'CURRENT_PHYSICAL_TASK.mat');
save(matPath,'physicalTask','-v7.3');
taskSha=gpenmpcNative.fileSha256(matPath);
phaseCodes=unique(double(reference.phase_code(:))).';
firstPosition=double(reference.position_m(1,:));
receipt=struct( ...
    'schema','GPENMPC_LIVE_TASK_PACKAGE_V1', ...
    'status','PASS_HOST_ONLY_TASK_PACKAGE', ...
    'run_id','GPENMPC_LIVE_DELIVERY', ...
    'public_method_name', ...
        'GP Enhanced Energy Aware eNMPC with Robust SE(3) Tracking Control', ...
    'internal_method_id','A1_COORDINATED_PHYSICAL', ...
    'mission_id','MU_CAMBRIDGE_MA_02', ...
    'planner_id','P_ENERGY_WIND_PAYLOAD', ...
    'task_mat_path',matPath, ...
    'task_mat_bytes',dir(matPath).bytes, ...
    'task_identity_sha256',taskSha, ...
    'source_contract_path',sourcePath, ...
    'source_contract_sha256',gpenmpcNative.fileSha256(sourcePath), ...
    'delivery_contract_path',deliveryPath, ...
    'delivery_contract_sha256',gpenmpcNative.fileSha256(deliveryPath), ...
    'source_manifest_sha256',string(assets.binding.source_manifest_sha256), ...
    'configuration_payload_sha256', ...
        string(assets.configurationBinding.effective_configuration_payload_sha256), ...
    'gp_model_sha256',gpenmpcNative.fileSha256(assets.gpModelPath), ...
    'sample_period_s',0.01, ...
    'sample_count',numel(reference.global_time_s), ...
    'formal_task_duration_s',double(reference.global_time_s(end)), ...
    'initial_task_position_up_m',firstPosition, ...
    'initial_ground_position_up_m',[firstPosition(1:2),0.0], ...
    'initial_takeoff_required',true, ...
    'initial_takeoff_duration_s',20.0, ...
    'phase_codes',phaseCodes, ...
    'delivery_ground_contact_count_required',4, ...
    'final_ground_contact_count_required',1, ...
    'grounded_payload_updates_required',4, ...
    'arm_transitions_required',5, ...
    'ground_delivery_semantics', ...
        'LAND_ON_SOFTWARE_GROUND__STANDARD_DISARM__GROUNDED_UNLOAD__REARM', ...
    'software_plant_instances',1, ...
    'plant_truth_used_for_command',false, ...
    'hardware_actions',0,'com_open',0,'board_access',0, ...
    'parameter_writes',0,'mapping_writes',0,'arm_requests',0, ...
    'mode_requests',0,'physical_output_count',0, ...
    'claim','Saved task package.');
writeJson(fullfile(outputRoot,'LIVE_TASK_PACKAGE.json'),receipt);
disp(jsonencode(receipt,PrettyPrint=true));
end

function writeJson(path,value)
file=fopen(path,'w','n','UTF-8');
assert(file>=0,'gpenmpcNative:LiveTaskWrite','Cannot create %s',path);
cleanup=onCleanup(@()fclose(file)); %#ok<NASGU>
fprintf(file,'%s\n',jsonencode(value,PrettyPrint=true));
end
