function receipt = build_canonical_cambridge_task_package(outputRoot)
% Package the Cambridge reference without the delivery-variant flare profile.
arguments
    outputRoot (1,1) string
end
assert(~isfolder(outputRoot) && ~isfile(outputRoot), ...
    'gpenmpcTask:FreshOutput','Refusing to overwrite an existing output.');
projectRoot = string(gpenmpc_external_path('delivery_method_project'));
workRoot = string(gpenmpc_external_path('native_visual_host_runtime'));
oldPath = path; pathCleanup = onCleanup(@() path(oldPath)); %#ok<NASGU>
addpath(fullfile(projectRoot,'matlab'),'-begin');
addpath(fullfile(workRoot,'src'),'-begin');
addpath(fileparts(mfilename('fullpath')),'-begin');
assets = gpenmpcNative.loadCurrentAssets(workRoot);
contractPath = string(gpenmpc_external_path('public_hil_method_contract'));
verify(bound(contractPath,dir(contractPath).bytes, ...
    "2A948B129AFDCEF3121B675988C3C05AC48A7310D038CD513747295B23E78DB4"));
method = jsondecode(fileread(contractPath));
missionPath = string(method.authoritative_paths.mission_contract);
cfg = jsondecode(fileread(missionPath));
sourceFiles = [ ...
    bound(missionPath,3892,"E4B20DE53ACC4AA442ACD8262AE5639AEE1644505E12362C62520AE9F6CB6013"); ...
    bound(fullfile(projectRoot,'matlab','+gpenmpcHil','buildCambridgePhysicalClosedLoopTask.m'),11092,"D39CAB8AA191F75F84446BB4B6B0D5A2331CE0296502FE8B85D2956E1E613AF2"); ...
    bound(fullfile(projectRoot,'matlab','+gpenmpcHil','loadCambridgePhysicalMission.m'),7421,"6F17EC1C36E5FD6B0A83F3436C4BE7ADE3193CC131201A848FECC9ED18062B11"); ...
    bound(fullfile(projectRoot,'matlab','+gpenmpcHil','sampleCambridgePhysicalMission.m'),6134,"E01040495B4C25B1C8E850EEECF19DDF22705C23F4BDD619DAB57BB8D0DF7B8F"); ...
    bound(cfg.source_trace.path,cfg.source_trace.bytes,cfg.source_trace.sha256); ...
    bound(cfg.source_ledger.path,cfg.source_ledger.bytes,cfg.source_ledger.sha256); ...
    bound(cfg.mission_source.path,cfg.mission_source.bytes,cfg.mission_source.sha256)];
for i=1:numel(sourceFiles), verify(sourceFiles(i)); end
assert(strcmp(which('gpenmpcHil.buildCambridgePhysicalClosedLoopTask'), ...
    fullfile(projectRoot,'matlab','+gpenmpcHil','buildCambridgePhysicalClosedLoopTask.m')), ...
    'gpenmpcTask:Shadow','Wrong Cambridge builder selected on MATLAB path.');
ledger = jsondecode(fileread(cfg.source_ledger.path));
mission = jsondecode(fileread(cfg.mission_source.path));
for key = ["controller_map","route_pool"]
    b = ledger.multi_urban_identity.(key);
    sourceFiles(end+1) = bound(b.path,b.bytes,b.sha256); %#ok<AGROW>
    verify(sourceFiles(end));
end
map = jsondecode(fileread(ledger.multi_urban_identity.controller_map.path));
routePool = jsondecode(fileread(ledger.multi_urban_identity.route_pool.path));
assert(string(map.city_id)==string(mission.city_id) && ...
    string(routePool.city_id)==string(mission.city_id) && ...
    string(routePool.mission_id)==string(mission.mission_id), ...
    'gpenmpcTask:Map','Map/route pool and mission are not the same city/task.');
assert(string(assets.binding.source_manifest_sha256)==string(method.internal_identity.source_manifest_sha256) && ...
    string(assets.configurationBinding.effective_configuration_payload_sha256)==string(method.internal_identity.effective_configuration_payload_sha256), ...
    'gpenmpcTask:Method','Current runtime source/configuration does not match public method contract.');
verify(bound(assets.gpModelPath,dir(assets.gpModelPath).bytes,method.internal_identity.gp_model_sha256));
verify(bound(method.authoritative_paths.effective_configuration, ...
    dir(method.authoritative_paths.effective_configuration).bytes,method.internal_identity.effective_configuration_mat_sha256));
assert(string(method.internal_identity.architecture)=="A1_COORDINATED_PHYSICAL", ...
    'gpenmpcTask:Architecture','Not the selected A1 physical architecture.');
for key=reshape(string(fieldnames(method.internal_identity.timing)),1,[])
    assert(isequal(assets.enmpc.(key),method.internal_identity.timing.(key)), ...
        'gpenmpcTask:Timing','Actual timing differs from method contract: %s',key);
end
requirements=method.internal_identity.architecture_requirements;
for key=["coordinated_architecture_enabled","coordinated_physical_gp_application_enabled", ...
        "coordinated_gp_execution_feedforward_enabled", ...
        "gp_responsibility_gate_enabled","command_continuity_enabled"]
    assert(isequal(assets.enmpc.(key),requirements.(key)), ...
        'gpenmpcTask:ActualArchitecture','Runtime architecture differs: %s',key);
end
assert(string(assets.enmpc.coordinated_architecture_mode)==string(method.internal_identity.architecture), ...
    'gpenmpcTask:ActualArchitecture','Runtime is not A1 coordinated physical.');

% Use the MATLAB Cambridge implementation.
physicalTask = gpenmpcHil.buildCambridgePhysicalClosedLoopTask(projectRoot);
npzPath = fullfile(gpenmpc_external_path('gp_task_model_data'),'matlab','data');
addpath(npzPath,'-begin');
timeline = gpenmpcHil.loadCambridgePhysicalMission(projectRoot);
audit = validate_canonical_cambridge_binding(physicalTask,cfg,ledger,mission,method,timeline);

% The source reference ends at depot flight altitude and contains no final landing.
physicalTask.execution_method_binding = method.internal_identity;
physicalTask.execution_method_binding.public_method_name = method.public_method_name;
physicalTask.execution_requirements = struct( ...
    'live_admission_granted',false,'initial_takeoff_required',true, ...
    'final_native_land_required',true,'final_native_land_reference_included',false, ...
    'payload_update_requires_contact_landed_disarmed',true, ...
    'ground_dwell_s',cfg.physical_service_profile.ground_dwell_s, ...
    'parent_control_output_reused',false);
mkdir(outputRoot);
matName = string(cfg.mission_id)+"__CANONICAL_PHYSICAL_TASK.mat";
matPath = fullfile(outputRoot,matName);
save(matPath,'physicalTask','timeline','audit','-v7.3');
receipt = struct('schema','GPENMPC_EXACT_CAMBRIDGE_REFERENCE_PACKAGE_V1', ...
    'status','PASS_HOST_ONLY_REFERENCE_BINDING__LIVE_NOT_ADMITTED', ...
    'mission_id',string(physicalTask.mission_id),'planner_id',string(physicalTask.planner_id), ...
    'public_method_name',string(method.public_method_name), ...
    'internal_method_id',string(method.internal_identity.architecture), ...
    'reference_source_method',string(cfg.reference_source_method), ...
    'source_manifest_sha256',string(assets.binding.source_manifest_sha256), ...
    'effective_configuration_payload_sha256',string(assets.configurationBinding.effective_configuration_payload_sha256), ...
    'gp_model_sha256',string(method.internal_identity.gp_model_sha256), ...
    'method_contract',bound(contractPath,dir(contractPath).bytes,gpenmpcNative.fileSha256(contractPath)), ...
    'task',bound(matPath,dir(matPath).bytes,gpenmpcNative.fileSha256(matPath)), ...
    'source_files',sourceFiles,'audit',audit, ...
    'reference_sample_count',numel(physicalTask.reference.global_time_s), ...
    'source_transit_sample_count',numel(timeline.source_time_s), ...
    'source_duration_s',timeline.source_time_s(end), ...
    'physical_reference_duration_s',physicalTask.reference.global_time_s(end), ...
    'delivery_ground_dwell_s',cfg.physical_service_profile.ground_dwell_s, ...
    'final_reference_position_up_m',physicalTask.reference.position_m(end,:), ...
    'final_native_landing_reference_included',false, ...
    'limitation','REFERENCE_ONLY__FINAL_DEPOT_LANDING_AND_LIVE_METHOD_PLANT_INTERFACE_REQUIRE_SEPARATE_VALIDATION', ...
    'hardware_actions',0,'com_open',0,'board_access',0,'parameter_writes',0, ...
    'mapping_writes',0,'arm_requests',0,'mode_requests',0,'physical_output',0);
receiptPath = fullfile(outputRoot,string(cfg.mission_id)+"__"+ ...
    string(method.internal_identity.architecture)+"__TASK_RECEIPT.json");
fid = fopen(receiptPath,'w','n','UTF-8');
assert(fid>=0,'gpenmpcTask:Write','Cannot create task receipt.');
closeFile = onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(receipt,PrettyPrint=true));
fprintf('CANONICAL_CAMBRIDGE_REFERENCE_BOUND source_rows=%d output_rows=%d\n', ...
    receipt.source_transit_sample_count,receipt.reference_sample_count);
end

function b=bound(p,n,h)
b=struct('path',string(p),'bytes',double(n),'sha256',upper(string(h)));
end

function verify(b)
d=dir(b.path);
assert(numel(d)==1 && ~d.isdir && d.bytes==b.bytes && ...
    gpenmpcNative.fileSha256(b.path)==b.sha256, ...
    'gpenmpcTask:SourceIdentity','Source identity mismatch: %s',b.path);
end
