function [state,response,audit] = canonical_delivery_host_step_checked( ...
        state,request,deliveryConfig,relaunchConfig,outerConfig,timeline)
%CANONICAL_DELIVERY_HOST_STEP_CHECKED Safety wrapper around the immutable host adapter.
% It preserves the accepted Cambridge reference/controller path and closes
% two lifecycle timing gaps before any returned action can be executed.
arguments
    state (1,1) struct
    request (1,1) struct
    deliveryConfig (1,1) struct
    relaunchConfig (1,1) struct
    outerConfig (1,1) struct
    timeline (1,1) struct
end
verifyParents();
assert(deliveryConfig.service_dwell_s==8.0 && ...
    deliveryConfig.native_land_confirmation_timeout_s==30.0, ...
    'gpenmpcTask:LifecycleContract', ...
    'Canonical service dwell and native-land timeout must remain 8/30 s.');

audit=struct('schema','CANONICAL_DELIVERY_HOST_STEP_SAFETY_WRAPPER_V1', ...
    'parent_adapter_sha256','7314A3E98FEF02429AFD50D3002A5DA5B98A76BA840FDA2FC1B43F434C659D8C', ...
    'parent_lifecycle_sha256','4C3C6AB152C75584277E03AC866B57D6FD050668178C8ADB19661DD075F19CA8', ...
    'precondition_override',false,'reason','', ...
    'reference_or_method_mutated',false,'hardware_actions',0);

delivery=state.coordinator.delivery;
timeS=double(request.simulation_time_s);
[~,missionObservation]=gpenmpcHil.cambridgeMissionReference( ...
    state.mission_clock,timeline,timeS);
if string(delivery.name)=="SERVICE_GROUNDED_DISARMED" && ...
        isfinite(delivery.service_start_s) && ...
        string(missionObservation.service_phase)=="SERVICE_ASCENT" && ...
        timeS-delivery.service_start_s<deliveryConfig.service_dwell_s-1e-9
    [state,response]=reject(state,request, ...
        'SERVICE_ASCENT_BEFORE_EIGHT_SECOND_GROUND_DWELL');
    audit.precondition_override=true;
    audit.reason='SERVICE_ASCENT_BEFORE_EIGHT_SECOND_GROUND_DWELL';
    return
end

priorName=string(delivery.name);
priorEnter=double(delivery.state_enter_time_s);
[state,response]=gpenmpcHil.threeMethodHostAdapterStep( ...
    state,request,deliveryConfig,relaunchConfig,outerConfig,timeline);
if priorName=="FINAL_NATIVE_LAND" && isfinite(priorEnter) && ...
        timeS-priorEnter>=deliveryConfig.native_land_confirmation_timeout_s && ...
        ~response.task_complete
    [state,response]=reject(state,request,'FINAL_NATIVE_LAND_CONFIRMATION_TIMEOUT');
    audit.precondition_override=true;
    audit.reason='FINAL_NATIVE_LAND_CONFIRMATION_TIMEOUT';
end
end

function [state,response]=reject(state,request,code)
state.failed=true;
state.failure_code=string(code);
state.coordinator.failed=true;
state.coordinator.failure_code=string(code);
state.coordinator.delivery.name="FAIL_CLOSED";
state.coordinator.delivery.failure_code=string(code);
state.coordinator.delivery.task_complete=false;
command=struct('request_arm',false,'request_land',false, ...
    'request_disarm',false,'request_offboard',false, ...
    'allow_payload_update',false,'hold_reference',true, ...
    'advance_reference',false,'align_ground_dwell_start',false);
response=struct('schema','GPENMPC_THREE_METHOD_HOST_STEP_RESPONSE_V1', ...
    'source_sequence',uint64(request.sequence), ...
    'simulation_time_s',double(request.simulation_time_s), ...
    'method_id',state.identity.method_id, ...
    'board_ra_ctrl_mode',state.identity.board_ra_ctrl_mode, ...
    'board_reference',state.held_reference, ...
    'lifecycle_command',command,'lifecycle_event','FAIL_CLOSED', ...
    'lifecycle_diagnostic',struct('failed',true,'failure_code',string(code)), ...
    'mission_reference_diagnostic',struct('phase',state.mission_clock.phase, ...
        'task_time_s',state.mission_clock.task_time_s), ...
    'mission_clock_receipt',struct('phase',state.mission_clock.phase, ...
        'task_time_s',state.mission_clock.task_time_s,'advanced',false), ...
    'method_diagnostic',struct('updated',false,'source','FAIL_CLOSED'), ...
    'task_complete',false,'fail_closed',true,'failure_code',string(code), ...
    'physical_output_command_count',state.physical_output_command_count);
end

function verifyParents()
persistent checked
if ~isempty(checked),return;end
adapter=gpenmpc_external_path('delivery_host_adapter_source');
lifecycle=gpenmpc_external_path('delivery_lifecycle_source');
assert(strcmp(which('gpenmpcHil.threeMethodHostAdapterStep'),adapter) && ...
    strcmp(which('gpenmpcHil.deliveryLifecycleStep'),lifecycle), ...
    'gpenmpcTask:ParentShadow','Unexpected GPENMPC parent package on MATLAB path.');
assert(gpenmpcHil.sha256File(adapter)== ...
    "7314A3E98FEF02429AFD50D3002A5DA5B98A76BA840FDA2FC1B43F434C659D8C" && ...
    gpenmpcHil.sha256File(lifecycle)== ...
    "4C3C6AB152C75584277E03AC866B57D6FD050668178C8ADB19661DD075F19CA8", ...
    'gpenmpcTask:ParentIdentity','Immutable GPENMPC parent source changed.');
checked=true;
end
