function report=codegen_canonical_combined_numerics(outputRoot)
% Generate four numerical entry points in one library with per-owner spill storage.
% StackUsageMax is a Coder storage estimate.
arguments
    outputRoot (1,1) string
end
build=string(fileparts(fileparts(mfilename('fullpath'))));
oldPath=path;oldDir=pwd;cleanup=onCleanup(@()restore(oldPath,oldDir)); %#ok<NASGU>
assert(~isfolder(outputRoot),'Preserve previous generated libraries.');mkdir(outputRoot);
parent=string(gpenmpc_external_path('native_visual_host_runtime'));
addpath(fullfile(parent,'src'),'-begin');addpath(fullfile(build,'host_runtime'),'-begin');
gpenmpcNative.loadCanonicalAssets();
addpath(fullfile(build,'tools','codegen_compat'),'-begin');
innerRoot=fullfile(gpenmpc_external_path('canonical_local_inner_codegen'));
referenceRoot=fullfile(gpenmpc_external_path('canonical_reference_window_codegen'));
innerInput=fullfile(innerRoot,'FIXED_INPUTS.mat');original=load(innerInput,'n');
innerReport=jsondecode(fileread(fullfile(innerRoot,'RESULT.json')));
assert(strcmp(innerReport.status,'PASS_FIXED_ABI_MATLAB_AND_STANDALONE_C_GENERATION'));
for k=1:numel(innerReport.sources)
    assert(strcmpi(sha(innerReport.sources(k).path),innerReport.sources(k).sha256), ...
        'gpenmpcNative:CombinedSourceMismatch','Bound source mismatch: %s',innerReport.sources(k).path);
end
referenceInput=fullfile(gpenmpc_external_path('canonical_reference_window_transition'),'QUERY_CODEGEN_INPUTS.mat');
q=load(referenceInput,'window','state','request');
referenceReport=jsondecode(fileread(fullfile(referenceRoot,'RESULT_STATIC_SCHEMA.json')));
assert(referenceReport.pass&&strcmpi(sha(referenceReport.source),referenceReport.source_sha256) ...
    &&strcmpi(sha(referenceReport.transition_source),referenceReport.transition_source_sha256));
cfg=coder.config('lib');cfg.GenCodeOnly=true;cfg.TargetLang='C';cfg.GenerateReport=false;
cfg.EnableDynamicMemoryAllocation=false;cfg.InstructionSetExtensions='None';
cfg.EnableOpenMP=false;cfg.EnableAutoParallelization=false;
previousStackUsageMax=cfg.StackUsageMax;previousMultiInstanceCode=cfg.MultiInstanceCode;
cfg.StackUsageMax=2048;cfg.MultiInstanceCode=true;
report=struct('schema','CANONICAL_COMBINED_NUMERICS_CODEGEN_V1', ...
    'pass',false,'entries',{{'gpenmpcNative.canonicalLocalInnerFixedFirst', ...
    'gpenmpcNative.canonicalLocalInnerFixedStep','gpenmpcNative.queryCanonicalReferenceWindow', ...
    'gpenmpcNative.canonicalReferenceTransitionFromJet'}}, ...
    'original_stack_usage_max',previousStackUsageMax,'stack_usage_max',cfg.StackUsageMax, ...
    'original_multi_instance_code',previousMultiInstanceCode,'multi_instance_code',cfg.MultiInstanceCode, ...
    'storage_change','Coder-generated per-owner spill structure.', ...
    'instruction_set_extensions','None','openmp',false,'automatic_parallelization',false, ...
    'dynamic_memory_allocation',false,'inner_input',char(innerInput),'inner_input_sha256',sha(innerInput), ...
    'reference_input',char(referenceInput),'reference_input_sha256',sha(referenceInput), ...
    'inner_source_records',innerReport.sources,'reference_source_record',referenceReport, ...
    'official_memory_documentation','https://www.mathworks.com/help/coder/ug/control-stack-space-usage.html', ...
    'compiler_stack_is_not_coder_budget',true,'native_executed',false,'target_executed',false, ...
    'model_calls',0,'solver_calls',0,'hardware_actions',0,'error_identifier','','error_report','');
cd(outputRoot);
try
    codegen('-config',cfg,'gpenmpcNative.canonicalLocalInnerFixedFirst', ...
        '-args',{coder.Constant(original.n),zeros(36,1),zeros(2,1,'uint64')}, ...
        'gpenmpcNative.canonicalLocalInnerFixedStep', ...
        '-args',{coder.Constant(original.n),zeros(64,1),zeros(2,1,'uint64'),zeros(36,1), ...
            zeros(2,1,'uint64'),zeros(70,1),zeros(2,1,'uint64')}, ...
        'gpenmpcNative.queryCanonicalReferenceWindow','-args',{q.window,q.state,q.request}, ...
        'gpenmpcNative.canonicalReferenceTransitionFromJet', ...
        '-args',{zeros(3,4),1.0,0.0,0.0,zeros(3,1),zeros(3,1),.009,4.0}, ...
        '-d',char(fullfile(outputRoot,'generated')));
    report.pass=true;
catch err
    report.error_identifier=err.identifier;report.error_report=getReport(err,'extended','hyperlinks','off');
end
report.sources_unchanged=true;
for k=1:numel(innerReport.sources)
    report.sources_unchanged=report.sources_unchanged&&strcmpi(sha(innerReport.sources(k).path),innerReport.sources(k).sha256);
end
report.sources_unchanged=report.sources_unchanged&&strcmpi(sha(referenceReport.source),referenceReport.source_sha256) ...
    &&strcmpi(sha(referenceReport.transition_source),referenceReport.transition_source_sha256);
f=fopen(fullfile(outputRoot,'RESULT.json'),'w');assert(f>=0);c=onCleanup(@()fclose(f));
fprintf(f,'%s',jsonencode(report,PrettyPrint=true));clear c
fprintf('COMBINED_CODEGEN pass=%d unchanged=%d stack_budget=%g multi_instance=%d\n', ...
    report.pass,report.sources_unchanged,report.stack_usage_max,report.multi_instance_code);
end
function value=sha(path)
f=fopen(path,'rb');assert(f>=0);c=onCleanup(@()fclose(f));b=fread(f,Inf,'*uint8');clear c
d=java.security.MessageDigest.getInstance('SHA-256');d.update(typecast(b,'int8'));
value=string(upper(reshape(dec2hex(typecast(d.digest(),'uint8'),2).',1,[])));
end
function restore(p,d)
path(p);cd(d);
end
