function options=gpenmpc_demo_test_environment()
% Create isolated files for hidden display tests.
assert(isempty(findall(groot,'Type','figure','Tag','GPENMPCDemoConsole')), ...
 'gpenmpcTest:OpenPanel','Close this MATLAB process''s existing test panel first.');
root=tempname;mkdir(root);mkdir(fullfile(root,'logs'));
options=struct('LogRoot',fullfile(root,'logs'),'ReplayFile',fullfile(root,'display_fixture.mat'), ...
 'Visible','off','ViewerEnabled',false,'DisplayPort',0,'LockFile',fullfile(root,'session.lock'));
lock=System.IO.FileStream(options.LockFile,System.IO.FileMode.CreateNew, ...
 System.IO.FileAccess.ReadWrite,System.IO.FileShare.None);lock.Dispose();
t=(0:.1:20).';n=numel(t);
trace=struct('fixture',true,'mission_id','MU_CAMBRIDGE_MA_02', ...
 'planner_id','P_ENERGY_WIND_PAYLOAD','method_id','B2_ENMPC_GP_MEAN_TOTAL_TUBE', ...
 'command_continuity_enabled',true,'outer_period_s',.30, ...
 'prediction_step_s',.20,'prediction_horizon_s',1.60,'global_time_s',t, ...
 'position_error_norm_m',abs(sin(t)), 'velocity_mps',[sin(t) cos(t) t/20], ...
 'attitude_error_rad',[t/100 t/200 t/300], 'rotor_command_n',repmat(1:6,n,1)+t/20, ...
 'gp_physical_axis_authority_f',repmat([.2 .3 .4],n,1), ...
 'solver_last_elapsed_s',.01+zeros(n,1),'solver_elapsed_available',true(n,1));
save(options.ReplayFile,'trace');
end
