function report=inspect_rfly_native_raw_block(outputRoot,label)
% Compile the vendor byte-transport block with localhost test ports.
if nargin<2,label='ORIGINAL_ONE_D_DYNAMIC';end
assert(~isempty(regexp(label,'^[A-Z_]+$','once')));
out=fullfile(outputRoot,['RFLY_NATIVE_RAW_BLOCK_' label '.json']);assert(~isfile(out));
vendor=gpenmpc_install_path('rfly','RflySimAPIs\RflySimSDK\simulink');
originalPath=path;addpath(vendor);pathGuard=onCleanup(@()path(originalPath)); %#ok<NASGU>
name='gpenmpc_native_raw_compile_probe';assert(~bdIsLoaded(name));
cleanup=onCleanup(@()closeProbe(name)); %#ok<NASGU>
compiled=false;stage='create_probe';
try
    load_system('simulink');load_system(fullfile(vendor,'pixhawk_slib_swarm.slx'));
    new_system(name);
    set_param(name,'Solver','FixedStepDiscrete','FixedStep','0.001','StopTime','0');
    add_block('simulink/Sources/Clock',[name '/CompileTime']);
    add_block('simulink/User-Defined Functions/MATLAB Function',[name '/NoCommandBytes']);
    chart=find(sfroot,'-isa','Stateflow.EMChart','Path',[name '/NoCommandBytes']);
    assert(isscalar(chart));stage='configure_original_dynamic_vector_contract';
    chart.Script=sprintf(['function y=fcn(t)\n%%#codegen\n' ...
        'coder.varsize(''y'',[1100 1],[true false]);\n' ...
        'y=zeros(1,1,''uint8'');\n' ...
        'if t<0, y=[y;uint8(0)]; end\nend\n']);
    % Match the vendor chart's dynamic one-dimensional uint8 output shape.
    % Use nonempty lengths 1 and 2; these short zero buffers are not transmitted.
    chart.SupportVariableSizing=true;
    configuration=get_param([name '/NoCommandBytes'],'MATLABFunctionConfiguration');
    configuration.VectorOutputs1D=true;
    y=find(chart,'-isa','Stateflow.Data','Name','y');assert(isscalar(y));
    y.DataType='uint8';y.Props.Array.Size='1100';y.Props.Array.IsDynamic=true;
    add_block('pixhawk_slib_swarm/RflyUdpRaw',[name '/OfficialRaw'], ...
        'num','[1]','ip1','127.0.0.1','ip','127.0.0.1','isSame','on','port','62321','T','0.001');
    add_block('simulink/Sinks/Terminator',[name '/NoConsumer']);
    add_line(name,'CompileTime/1','NoCommandBytes/1');
    add_line(name,'NoCommandBytes/1','OfficialRaw/1');add_line(name,'OfficialRaw/1','NoConsumer/1');
    stage='compile';
    feval(name,[],[],[],'compile');compiled=true;
    stage='read_compiled_contract';
    p=get_param([name '/OfficialRaw'],'PortHandles');
    inDims=get_param(p.Inport,'CompiledPortDimensions');
    inMode=get_param(p.Inport,'CompiledPortDimensionsMode');
    inType=get_param(p.Inport,'CompiledPortDataType');
    assert(inDims(1)==1&&inMode==1&&strcmp(inType,'uint8'), ...
        'gpenmpcNative:VendorRawInputContract','Vendor input must compile as 1-D variable-size uint8.');
    report=struct('status','PASS_COMPILE_ONLY_VENDOR_RAW_BLOCK', ...
        'source',fullfile(vendor,'pixhawk_slib_swarm.slx'), ...
        's_function',which('RflyUdpRaw'),'sample_time_s',.001, ...
        'input_dimensions',inDims,'input_dimensions_mode',inMode, ...
        'output_dimensions',get_param(p.Outport,'CompiledPortDimensions'), ...
        'output_dimensions_mode',get_param(p.Outport,'CompiledPortDimensionsMode'), ...
        'input_type',inType, ...
        'output_type',get_param(p.Outport,'CompiledPortDataType'), ...
        'chart_vector_outputs_one_dimensional',configuration.VectorOutputs1D, ...
        'chart_output_declared_size',y.Props.Array.Size, ...
        'chart_output_declared_dynamic',y.Props.Array.IsDynamic, ...
        'original_contract_source', ...
        'ThreeUAVsRawMavExp.slx::simulink/stateflow/chart_23.xml::y=array1100,isDynamic1,uint8;eml.vectorOutputs1D1', ...
        'configuration',{get_param([name '/OfficialRaw'],'MaskValues')}, ...
        'simulation_ticks',0,'native_sfunction_initialization_may_open_localhost_udp',true, ...
        'COM',0,'board',0,'plant_runs',0,'controller_runs',0);
    stage='terminate';feval(name,[],[],[],'term');compiled=false;
catch ex
    termination=[];
    if bdIsLoaded(name)
        try,feval(name,[],[],[],'term');catch termEx,termination=exceptionTree(termEx);end
    end
    report=struct('status','HOST_ONLY_COMPILE_PROBE_FAILED','identifier',ex.identifier, ...
        'message',ex.message,'stack',ex.stack,'failure_stage',stage, ...
        'compiled_before_failure',compiled, ...
        'extended_report',getReport(ex,'extended','hyperlinks','off'), ...
        'exception',exceptionTree(ex),'termination_exception',termination,'simulation_ticks',0, ...
        'native_sfunction_initialization_may_open_localhost_udp',true,'COM',0,'board',0);
    fprintf(2,'%s\n',report.extended_report);
end
fid=fopen(out,'w');assert(fid>=0);fileGuard=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));disp(jsonencode(report));
end
function node=exceptionTree(ex)
causes=cell(size(ex.cause));
for k=1:numel(ex.cause),causes{k}=exceptionTree(ex.cause{k});end
node=struct('identifier',ex.identifier,'message',ex.message,'stack',ex.stack, ...
    'extended_report',getReport(ex,'extended','hyperlinks','off'),'causes',{causes});
end
function closeProbe(name)
if bdIsLoaded(name),bdclose(name);end
end
