function c=make_m600_board_local_short_config(plantIdentity,outerPreflightReceipt,assets)
% Configure a bounded BOARD_LOCAL_FULL_INNER trial from loaded assets.
% The outer owner supplies fresh preflight before live operation.
arguments
    plantIdentity
    outerPreflightReceipt
    assets (1,1) struct
end
assert(all(isfield(assets,{'enmpc','binding','configurationBinding','kernelParameters'})) ...
    &&strcmp(assets.binding.schema,'CANONICAL_E_PACKAGE_RUNTIME_SOURCE_BINDING_V1') ...
    &&assets.binding.verified_source_entries==160&&assets.binding.source_path_only_difference ...
    &&strcmpi(assets.binding.effective_configuration_payload_sha256, ...
        assets.configurationBinding.effective_configuration_payload_sha256), ...
    'gpenmpcShort:LoadedAssets','Pass the already loaded authoritative assets, not reconstructed method labels.');
assert(isfield(assets.enmpc,'method')&&strlength(string(assets.enmpc.method))>0 ...
    &&strcmp(assets.enmpc.coordinated_architecture_mode,'A1_COORDINATED_PHYSICAL') ...
    &&assets.enmpc.coordinated_physical_gp_application_enabled ...
    &&assets.enmpc.coordinated_gp_execution_feedforward_enabled ...
    &&assets.enmpc.command_continuity_enabled ...
    &&assets.enmpc.outer_period_s==0.30&&assets.enmpc.prediction_step_s==0.20 ...
    &&assets.enmpc.horizon_steps==8&&assets.enmpc.prediction_horizon_s==1.6 ...
    &&assets.enmpc.solver_deadline_s==0.28&&assets.kernelParameters.baseMass==9.5, ...
    'gpenmpcShort:CanonicalMethod','Use the loaded physical GP method, 0.30 s update, 0.20 s x 8 prediction, 0.28 s solve deadline and M600 mass.');
c=make_m600_native_hover_config(plantIdentity,outerPreflightReceipt);
build=fileparts(fileparts(mfilename('fullpath')));
evidence=fullfile(build,'evidence','task_interface');
c.local_mavlink_dialect=struct( ...
    'path',fullfile(build,'m600_coptersim','matlab_validation','+m600check','local_full_inner_dialect','px4_local_full_inner.xml'), ...
    'sha256','647FBB0BB47F0A55118D7FFB30370270648D0DB579D8CEF711C1C2336A8AC2BF', ...
    'common_sha256','7F1597B3EB4719ED7DFF6642064239799DB072CC3205E7A599C71AD568EC5D8F');

% Use the board session's engineering transport, input, outer and window bounds.
c.canonical_exchange=struct('runtime','BOARD_LOCAL_FULL_INNER', ...
    'assembly_limit_ns',uint64(50000000), ...
    'gp_reply_host_max_age_ns',uint64(200000000), ...
    'local_input_host_max_age_ns',uint64(80000000), ...
    'local_window_host_max_age_ns',uint64(1000000000), ...
    'completed_queue_capacity',8,'require_learning_audit',true);
% The GP send allowance is anchored to host reception and covers transport
% completion, not prediction validity. The board checks its own clock and
% retains the unavailable or late-result path.

% Bind the five-payload environment contract and selected plant policy.
c.delivery_environment_contract=struct('expected_session_token',26090501, ...
    'initial_payload_kg',2.21,'payload_by_generation_kg',[2.21;1.75;.98;.55;0], ...
    'mass_by_generation_kg',[11.71;11.25;10.48;10.05;9.5],'remote_port',30100);

% Retain ceil(400/20)+4 RLS entries to cover the 400 ms history at 20 ms
% publication spacing, including boundary entries.
sc=struct('source_max_age_ns',c.canonical_exchange.local_input_host_max_age_ns, ...
    'command_lifetime_ns',uint64(700000000),'pending_capacity',24,'component_initialization',false);
sc.gp_backend=struct('kind','CANONICAL_GP_WIRE_MEX', ...
    'path',fullfile(build,'runtime_assets','gp_wire','canonical_gp_wire_mex.mexw64'), ...
    'binary_sha256','A20AB9DAA20749EFB7E549DDBD26DE29AC7F34C2FA5C4A73FB5B4A348D1281D6', ...
    'receive_inline',true);
sc.input_codec_backend=struct('kind','CANONICAL_LOCAL_TASK_WIRE_MEX', ...
    'path',fullfile(evidence,'task_wire','canonical_local_task_wire_mex.mexw64'), ...
    'binary_sha256','150D341A3E0C5EB3F382FF494CBB69D07BC27231767CB48055052CA9AEA940EB', ...
    'adapter_path',fullfile(build,'tools','encode_canonical_local_task_mex.m'), ...
    'adapter_sha256','C2ACAEF7AFA34C6C2497928B562317A4C7F6F6D6194689AA14056BCEA35BD496');

c.local_short=struct('duration_s',40,'poll_period_s',.001, ...
    'runtime_state_only',true,'component_initialization',false, ...
    'heartbeat_period_s',.05,'preparation_timeout_s',c.preflight_deadline_s, ...
    'getter_capacity',4096,'environment_ledger_capacity',4096, ...
    'raw_capacity',c.maximum_raw_records,'service_cfg',sc, ...
    'method',char(assets.enmpc.method), ...
    'configuration_sha256',char(assets.binding.effective_configuration_payload_sha256), ...
    'gp_model_sha256',char(assets.binding.gp_model_sha256), ...
    'require_nonzero_gp_replies',false);
% Allow bounded estimator acquisition before arming.
% The ready predicate still requires valid state and an acceptable origin offset.
c.preflight_deadline_s=45;
c.bound_provenance.preflight_acquisition= ...
    'Engineering acquisition cap: 45 s for estimator convergence, with ground, finite-data, freshness, status-flag and 0.5 m origin checks.';
c.mavlink_transport=struct('source',struct('kind','GPENMPC_RFLY_UDP_TRANSPORT_MEX', ...
    'exact_path',fullfile(build,'tools','usb_rc_runtime','gpenmpc_rfly_udp_transport_mex.mexw64'), ...
    'sha256','6D207DE4797594C88AA9502C33C800503F7CC1C50806CC70C85D1C76E25AFFC0'), ...
    'scope','COPTERSIM_EXISTING_MAVLINK','allow_loopback',true, ...
    'local_host','127.0.0.1','remote_host','127.0.0.1', ...
    'local_port',c.local_mavlink_port,'remote_port',c.remote_mavlink_port, ...
    'local_system',uint8(255),'local_component',uint8(190), ...
    'remote_system',uint8(c.target_system),'remote_component',uint8(c.target_component), ...
    'maximum_poll_datagrams',64,'copter_serial_forwarding',true);

% Reuse native-hover clock and safety bounds for the canonical task lifecycle.
% The hover_* field names support lifecycle compatibility.
assert(c.evaluation_policy.limits.position_p95_m==.8);
c.bound_provenance.flight= ...
    'A 40 s control interval follows the first-leg reference after its 25-phase-second preparation; phase and source clocks govern progression.';
c.bound_provenance.scope= ...
    'BOARD_LOCAL_FULL_INNER short-duration HIL diagnostic.';
c.bound_provenance.local_transport= ...
    'HOST input-send allowance: 80 ms from first RLS reception, within the 100 ms board held-input limit. Estimator/control-gap freshness is 50 ms; transaction, GP numerical, assembly, outer and solver limits remain independently enforced.';
c.bound_provenance.local_host_work= ...
    'Requested pacing: 1 ms poll, 50 ms heartbeat and 30 s preparation wait. Getter and environment-association ledgers each hold 4096 entries; source binding requires a matching retained record.';
c.bound_provenance.local_performance= ...
    'P95 position-error screen: 0.8 m. Record every GP request, reply and commit; short trials may contain zero GP commits.';
c.bound_provenance.vertical_observer_hil= ...
    'Vertical observer interval limit: 20.0001 ms. Derivative and EWMA use the measured dt; longer intervals, wrong leg/payload or invalid data reset the observer.';
c.bound_provenance.outer_mailbox_age= ...
    'HOST source-to-result allowance: 600 ms, comprising 320 ms observation admission and 280 ms queue/solve/return time. Board source-anchored expiry remains 700 ms; solver, observation, generation and board-expiry checks apply independently.';
c.source_provenance.method=char(assets.enmpc.method);
c.source_provenance.configuration_sha256=char(assets.binding.effective_configuration_payload_sha256);
c.source_provenance.gp_model_sha256=char(assets.binding.gp_model_sha256);

% Px4ReadOnlyGuard requires RA_CTRL_MODE=0, COM_OBL_RC_ACT=4, and zero
% PWM_MAIN_FUNC1..8 and PWM_AUX_FUNC1..8 mappings.
% The canonical stream uses actuator_outputs_rfly; native LAND recovery uses
% actuator_outputs_sim and its separate allocator and tuning contracts.
% The outer owner supplies, reads back and restores those recovery parameters.
end
