function contract=make_m600_delivery_native_tuning_contract()
% Bind the selected native-recovery tuning values to the delivery model.
root=fileparts(fileparts(mfilename('fullpath')));
planPath=fullfile(gpenmpc_external_path('native_tuned_hover_preparation'),'PLAN.json');
parentPlan=jsondecode(fileread(planPath));old=parentPlan.native_hover_tuning;
derivative=fullfile(root,'matlab_validation','+m600check','derivativeSoftware.m');
model=fullfile(gpenmpc_external_path('environment_delivery_model'),'GPENMPC_M600_Canonical.slx');
generated=fullfile(gpenmpc_external_path('canonical_delivery_dll_build'), ...
    'GPENMPC_M600_Canonical_ert_rtw','GPENMPC_M600_Canonical.cpp');
dll=fullfile(gpenmpc_external_path('canonical_delivery_dll_build'),'compiled','GPENMPC_M600_Canonical.dll');
adapter=fullfile(root,'m600_coptersim','matlab_validation','+m600check','makeM600CopterSimIo.m');
oldDerivative=old.source_provenance(strcmpi({old.source_provenance.path},derivative));
assert(isscalar(oldDerivative),'m600delivery:OldDerivativeBinding');
contract=struct( ...
    'schema','TEMPORARY_M600_CANONICAL_DELIVERY_NATIVE_TUNING_V1', ...
    'entries',old.entries, ...
    'unchanged_guard_entries',old.unchanged_guard_entries, ...
    'output_guard_entries',old.output_guard_entries, ...
    'parent_plan',identity(planPath), ...
    'superseded_derivative_binding',oldDerivative, ...
    'current_derivative_binding',identity(derivative), ...
    'delivery_runtime_bindings',[identity(model);identity(generated);identity(dll);identity(adapter)], ...
    'change_reason','PASSIVE_GROUND_AND_PHYSICAL_DELIVERY_RUNTIME_SUPERSEDES_ONLY_THE_OLD_PLANT_DERIVATIVE_BYTES', ...
    'selected_values_changed',false, ...
    'controller_method_family_changes',0, ...
    'physical_output_actions',0, ...
    'maximum_apply_passes',1, ...
    'restore_policy','IDEMPOTENT_PER_OWNER_AFTER_DISARM_ZERO_OUTPUTS', ...
    'claim','CURRENT_SOURCE_PARAMETER_SERVICE_CONTRACT');
check=validate_m600_delivery_native_tuning_contract(contract);
assert(check.passed,'m600delivery:DeliveryTuningContract','%s',check.failure);
end

function item=identity(pathValue)
info=dir(pathValue);assert(isfile(pathValue)&&isscalar(info),'m600delivery:BindingMissing');
item=struct('path',char(pathValue),'bytes',info.bytes,'sha256',m600check.fileSha256(pathValue));
end
