function c=make_m600_canonical_delivery_config(plantIdentity,outerPreflightReceipt)
% Configure the Cambridge four-delivery MATLAB/PX4/M600 session.
buildRoot=fileparts(fileparts(mfilename('fullpath')));
parent=gpenmpc_external_path('delivery_method_project');
taskPath=fullfile(buildRoot,'task_packages','cambridge_canonical', ...
    'MU_CAMBRIDGE_MA_02__CANONICAL_PHYSICAL_TASK.mat');
c=make_m600_native_hover_config(plantIdentity,outerPreflightReceipt);
c.hover_altitude_m=1;             % retained compatibility field, unused by mission
c.hover_duration_s=763.6705;      % evaluator policy schema validation only
c.prestream_s=2.5;
c.preflight_deadline_s=30;
c.land_timeout_s=30;
c.disarm_timeout_s=8;
c.abort_truth_speed_mps=20;
c.abort_estimator_gap_m=50;
c.maximum_raw_records=1500000;
c.delivery_mission=struct( ...
    'schema','M600_CANONICAL_CAMBRIDGE_FOUR_GROUND_DELIVERY_V1', ...
    'task_path',taskPath, ...
    'task_sha256','B876546B468265F84BD028AC549B06EF8ADDCB25CBA09CF389A08F4B21290A5F', ...
    'gpenmpc_parent_matlab_root',fullfile(parent,'matlab'), ...
    'delivery_lifecycle_config',fullfile(parent,'config','DELIVERY_LIFECYCLE_V1.json'), ...
    'delivery_lifecycle_sha256','B1CCE6C7C11CC87B23D23B7FC683039BD442C8DB5598F45F75DDFC1295295B61', ...
    'relaunch_config',fullfile(parent,'config','RELAUNCH_STATE_MATCH_V1.json'), ...
    'relaunch_config_sha256','E14EEC4EC4E2A6D6A724465319BC7B85B31357156D20C05EF1F8A1DF9CA93944', ...
    'mission_timeout_s',980, ...
    'expected_delivery_count',4, ...
    'service_ids',{{'node5','node3','node2','node4'}}, ...
    'final_native_land_required',true, ...
    'controller','PX4_NATIVE_POSITION_ATTITUDE_RATE_ALLOCATOR', ...
    'task_clock_paused_during_native_land_and_rearm',true, ...
    'plant_truth_used_for_control',false);
c.delivery_environment_contract=struct( ...
    'expected_session_token',26090501, ...
    'initial_payload_kg',2.21, ...
    'payload_by_generation_kg',[2.21;1.75;.98;.55;0], ...
    'mass_by_generation_kg',[11.71;11.25;10.48;10.05;9.5], ...
    'remote_port',30100);
c.evaluation_policy.limits.position_rms_m=1.2;
c.evaluation_policy.limits.position_p95_m=2.0;
c.evaluation_policy.limits.position_max_m=5.0;
c.evaluation_policy.limits.estimator_gap_max_m=5.0;
c.evaluation_policy.limits.velocity_tracking_rms_mps=2.0;
c.evaluation_policy.limits.truth_speed_max_mps=20.0;
c.bound_provenance.delivery= ...
    'CANONICAL_TASK: four real native LAND + standard disarm + 8 s ground service + unload + rearm cycles, then final native LAND.';
c.bound_provenance.delivery_performance= ...
    'PROJECT_SCREENING_ONLY: RMS1.2/P952/max5m and estimator gap5m; a completed finite collision-free mission remains a valid result if a screen is missed.';
c.bound_provenance.delivery_abort= ...
    'Safety-interface abort at 50 m estimator/plant separation or 20 m/s truth speed.';
c.source_provenance.canonical_task=taskPath;
c.source_provenance.canonical_delivery_lifecycle=c.delivery_mission.delivery_lifecycle_config;
c.source_provenance.canonical_delivery_model= ...
    fullfile(gpenmpc_external_path('passive_ground_delivery_model'),'GPENMPC_M600_Canonical.slx');
end
