function c=make_m600_native_hover_config(plantIdentity,outerPreflightReceipt)
% Configure the native-controller hover check without device or file access.
% Parameter classifications are documented below.
c=struct('live_enabled',false,'outer_preflight_pass',false, ...
    'require_current_native_telemetry',true, ...
    'outer_preflight_receipt',outerPreflightReceipt,'plant_identity',plantIdentity, ...
    'write_artifacts',true,'hover_altitude_m',1,'hover_duration_s',20, ...
    'prestream_s',2.5,'preflight_deadline_s',30,'mode_timeout_s',8, ...
    'arm_timeout_s',12,'land_timeout_s',30,'disarm_timeout_s',8, ...
    'command_timeout_s',8,'poll_period_s',.05,'heartbeat_period_s',1, ...
    'heartbeat_max_age_s',3,'landed_max_age_s',2,'state_max_age_s',.25, ...
    'maximum_initial_origin_offset_m',.5,'abort_truth_speed_mps',5, ...
    'abort_estimator_gap_m',5,'local_mavlink_port',14550,'remote_mavlink_port',18570, ...
    'truth_port',30101,'coptersim_time_port',20005,'target_system',1,'target_component',1, ...
    'clock_max_rtt_s',.1,'clock_sync_samples',5,'clock_sync_period_s',.2, ...
    'clock_max_age_s',180,'clock_max_uncertainty_s',.051, ...
    'clock_max_utc_drift_s',.05,'clock_max_time_heartbeat_age_s',2, ...
    'clock_max_time_heartbeat_lag_s',.25,'maximum_truth_lag_s',.25, ...
    'maximum_raw_records',250000);
c.evaluation_policy=struct('minimum_anchor_samples',100,'required_valid_fraction',1, ...
    'maximum_anchor_gap_s',.25,'maximum_source_age_s',struct('reference',.25,'estimate',.25), ...
    'maximum_receive_lag_s',struct('reference',.001,'estimate',.25,'truth',.25), ...
    'maximum_alignment_skew_s',.25,'limits',struct('position_rms_m',.5, ...
    'position_p95_m',.8,'position_max_m',1.2,'estimator_gap_max_m',.5, ...
    'velocity_tracking_rms_mps',.75,'truth_speed_max_mps',1.5));
c.bound_provenance=struct( ...
    'flight','1 m hover, 20 s duration, 2.5 s prestream and 50 ms polling; tracking is evaluated from the three synchronized streams.', ...
    'lifecycle','8s Offboard, 12s arm, 30s LAND, 8s standard disarm reused from current physical-delivery lifecycle; no payload/task identity imported', ...
    'data_age','PROJECT_ENGINEERING_OBSERVABILITY_BOUND: 250ms = 12.5 periods of actual no-board 50Hz truth/diagnostic; gaps/raw rows remain disclosed', ...
    'heartbeats','Engineering liveness bounds: 3 s heartbeat and 2 s land/time data. Missing data yields UNKNOWN.', ...
    'clock','Engineering alignment bounds: TIMESYNC RTT <= 100 ms, midpoint half-RTT plus UTC pairing and 1 ms quantization <= 51 ms, and drift <= 50 ms.', ...
    'abort','PROJECT_ENGINEERING_INTERFACE_ABORT: 5m estimator/plant separation or 5m/s truth speed for a 1m neutral hover; not an airframe absolute limit or method-performance PASS', ...
    'performance','PROJECT_CHOSEN_HOVER_SCREENS: RMS0.5/P950.8/max1.2m, gap0.5m, velocityRMS0.75/max1.5mps. Screening misses retain completed result; no after-result lowering', ...
    'origin','Engineering prearm origin check: fixed translation <= 0.5 m in the verified flat LowGPU ground frame.', ...
    'raw_bound','HOST_MEMORY_CAP_ONLY: 250000 records; overflow invalidates evidence and triggers safe finalization', ...
    'current_estimator_status','Low-rate ESTIMATOR_STATUS uses the 3 s heartbeat bound; essential fields must be finite with source progress. Optional HAGL/TAS values may be NaN.', ...
    'scope','Neutral 2.21kg-payload same-M600 flat-plane native-PX4 interface experiment. Not representative Cambridge/A1, not source method replacement');
c.source_provenance=struct( ...
    'official_smoke','run_official_hex_hil_smoke.m', ...
    'lifecycle',gpenmpc_external_path('physical_delivery_lifecycle'), ...
    'neutral_ground_map','Official LowGPU map; exact map/DLL hashes required by outer before live');
end
