function context = make_sensor_aligned_hover_preparation()
% Bind the sensor-alignment observation files.
root=gpenmpc_external_path('sensor_aligned_observation_fixture');
plan=readJson(fullfile(root,'CONSUMED_INPUTS','CONSUMED_PLAN.json'));
obs=readJson(fullfile(root,'INITIALIZATION_MATLAB','RESULT.json'));
health=readJson(fullfile(root,'RAW_STREAM_ANALYSIS','INITIALIZATION_STREAM_HEALTH.json'));
outer=readJson(fullfile(root,'OUTER_RESULT.json'));
pre=readJson(fullfile(root,'SERIAL_PREFLIGHT.json'));
context=struct('schema','M600_SENSOR_ALIGNED_NATIVE_HOVER_PREPARATION_V1', ...
    'scope','BOUND_OFFLINE_PREPARATION_ONLY', ...
    'observation_run_root',root,'observation_execution_id','SENSOR_ALIGNED_REFERENCE_OBSERVATION', ...
    'required_fresh_preflight',true,'flight_admission',false, ...
    'staleness_policy','EXACT_RUN_AND_RUNTIME_BINDING_NOT_WALL_CLOCK_AGE', ...
    'calibration_contract',plan.virtual_sensor_mount_contract);
context.expected_identity=struct('uid',pre.uid,'board_version',pre.board_version, ...
    'commit',pre.commit,'flight_custom_version_hex',pre.flight_custom_version_hex);
context.observation=struct('window_completed',obs.window_completed, ...
    'duration_contract_s',obs.duration_contract_s,'elapsed_s',obs.elapsed_observation_s, ...
    'source_reset_count',double(obs.source_reset_performed), ...
    'source_reversal_count',health.snapshot_accounting.estimate_source_reversed_count+ ...
    health.snapshot_accounting.truth_source_reversed_count+health.snapshot_accounting.model_source_reversed_count+ ...
    health.snapshot_accounting.raw_model_source_reversed_count+health.snapshot_accounting.attitude_source_reversed_count, ...
    'fatal_present',~isempty(obs.first_fatal)||~isempty(obs.failure)||~isempty(health.transport_fatal), ...
    'safe_finally',outer.safe_to_stop_proved&&outer.final_serial_safety_passed&& ...
    outer.coptersim_stopped&&~outer.safety_recovery_remaining);
names={'outer_result','observer_result','stream_summary','attitude_summary','consumed_plan', ...
    'serial_preflight','serial_postflight','vendor_prefix','vendor_full_log','raw_observation','observation_rows','attitude_rows'};
paths={'OUTER_RESULT.json','INITIALIZATION_MATLAB\RESULT.json', ...
    'RAW_STREAM_ANALYSIS\INITIALIZATION_STREAM_HEALTH.json', ...
    'RAW_STREAM_ANALYSIS\ATTITUDE_VS_PLANT\SENSOR_FRAME_OBSERVATION_SUMMARY.json', ...
    'CONSUMED_INPUTS\CONSUMED_PLAN.json','SERIAL_PREFLIGHT.json','SERIAL_POSTFLIGHT.json', ...
    'VENDOR_INITIALIZATION_PREFIX.json','VENDOR_INITIALIZATION_FULL_LOG.json', ...
    'INITIALIZATION_MATLAB\RAW_INITIALIZATION_OBSERVATION.mat','INITIALIZATION_MATLAB\OBSERVATION_ROWS.csv', ...
    'RAW_STREAM_ANALYSIS\ATTITUDE_VS_PLANT\SENSOR_FRAME_OBSERVATION_ROWS.csv'};
refs=repmat(struct('label','','path','','bytes',0,'sha256',''),0,1);
for k=1:numel(names), refs(end+1)=fileRef(names{k},fullfile(root,paths{k})); end %#ok<AGROW>
runtimeLabels={'model_dll','source_model','core_parameters','sensor_frame_encoder','hil_profile','firmware', ...
    'sensor_mount_checker','sensor_mount_host_tests','sensor_calibration_readonly'};
context.runtime_binding=struct();
for k=1:numel(runtimeLabels)
    label=runtimeLabels{k}; idx=find(strcmp({plan.references.label},label));
    assert(numel(idx)==1,'m600check:PreparationSource','Missing/duplicate consumed runtime label.');
    r=plan.references(idx); refs(end+1)=r; %#ok<AGROW>
    context.runtime_binding.([label '_sha256'])=r.sha256;
end
context.references=refs;
end
function value=readJson(path)
value=jsondecode(fileread(path));
end
function r=fileRef(label,path)
d=dir(path); assert(isscalar(d)&&~d.isdir,'m600check:PreparationMissingFile','Missing exact file: %s',path);
r=struct('label',label,'path',path,'bytes',d.bytes,'sha256',hashFile(path));
end
function h=hashFile(path)
fid=fopen(path,'rb'); assert(fid>=0,'m600check:PreparationRead','Cannot read %s',path);
c=onCleanup(@()fclose(fid)); %#ok<NASGU>
md=java.security.MessageDigest.getInstance('SHA-256');
while true
    b=fread(fid,1048576,'*uint8'); if isempty(b), break; end
    md.update(b);
end
h=upper(reshape(dec2hex(typecast(md.digest(),'uint8'),2).',1,[]));
end
