function [cfg,meta]=native_position_control_explicit_fixture()
% Define host test parameters independently of measured board parameters.
cfg=struct('parameter_provenance','EXPLICIT_HOST_FIXTURE', ...
    'position_p',[1;1;1],'velocity_p',[2;2;2],'velocity_i',[.5;.5;.5], ...
    'velocity_d',[.1;.1;.1],'velocity_limits_mps',[5;3;2], ...
    'thrust_limits',[.1;.9],'horizontal_thrust_margin',.3, ...
    'tilt_limit_rad',.5,'hover_thrust',.5,'decouple_horizontal_vertical',true);
fields=fieldnames(cfg);rows=struct('field',{},'value',{},'provenance',{});
for k=1:numel(fields)
    rows(k)=struct('field',fields{k},'value',cfg.(fields{k}), ...
        'provenance','EXPLICIT_HOST_TEST_VALUE');
end
meta=struct('schema','NATIVE_POSITION_CONTROL_EXPLICIT_FIXTURE_V1', ...
    'parameter_rows',rows,'current_position_parameters_collected',false, ...
    'hover_note','Hover thrust 0.5 is the fixture value for gravity/thrust arithmetic.', ...
    'purpose','Small exact arithmetic/NaN/lifecycle functional tests; not performance tuning.', ...
    'units','NED meters/seconds, radians, normalized collective thrust; gains in the original PositionControl units.', ...
    'hardware_actions',0,'COM_UDP_actions',0,'flight_admission',false);
end
