function ledger=normalize_rfly_compiled_gp_ledger(core)
% Normalize post-run data for the native Raw auditor.
% Preserve source bytes, QPC timestamps, counters and failures in compiled_core.
assert(isstruct(core)&&isscalar(core)&&strcmp(core.scope, ...
    'COMPILED_RETAINED_C_QUERY_REPLAY_ONLY_NO_LIVE_AUTHORITY'), ...
    'gpenmpcNative:CompiledRawLedgerScope','Unexpected compiled evidence scope.');
u=double(core.updates);completed=double(core.queries_completed);calls=double(core.gp_calls);tx=double(core.tx_count);
assert(u>=0&&u<=10000&&completed>=0&&completed<=59&&calls>=completed&&calls<=59&&tx>=0&&tx<=178, ...
    'gpenmpcNative:CompiledRawLedgerCounts','Compiled ledger counters exceed fixed bounds.');
assert(isequal(size(core.raw_records),[u 3])&&isequal(size(core.raw_qpc),[u 2]) ...
    &&isa(core.raw_qpc,'uint64')&&isa(core.raw_bytes,'uint8') ...
    &&numel(core.raw_bytes)==double(core.raw_used) ...
    &&isequal(size(core.query_requests),[310 calls])&&isequal(size(core.query_replies),[286 calls]) ...
    &&isequal(size(core.query_result18),[calls 18])&&isequal(size(core.query_qpc),[calls 3]) ...
    &&isa(core.query_qpc,'uint64')&&isequal(size(core.query_times),[calls 1]) ...
    &&isequal(size(core.tx_frames),[300 tx])&&isequal(size(core.tx_metadata),[tx 5]), ...
    'gpenmpcNative:CompiledRawLedgerShape','Malformed compiled ledger arrays.');
assert(isa(core.qpc_frequency,'uint64')&&core.qpc_frequency>0&&isa(core.qpc_origin,'uint64'), ...
    'gpenmpcNative:CompiledRawLedgerClock','Exact QPC frequency/origin required.');
raw=cell(u,1);queries=cell(completed,1);outputs=cell(tx,1);
for k=1:u
    row=core.raw_records(k,:);first=row(1)+1;last=row(1)+row(2);
    assert(first>=1&&last<=numel(core.raw_bytes)&&row(2)>=1&&row(2)<=4999 ...
        &&row(1)==floor(row(1))&&row(2)==floor(row(2)), ...
        'gpenmpcNative:CompiledRawByteRange','Raw byte offsets must address retained memory exactly.');
    raw{k}=struct('bytes',core.raw_bytes(first:last),'simulation_s',row(3), ...
        'host_observed_qpc',core.raw_qpc(k,1),'processing_finished_qpc',core.raw_qpc(k,2), ...
        'clock_semantics','MONOTONIC_HOST_OBSERVATION_NOT_SOURCE_TIMESTAMP');
end
for k=1:tx
    row=core.tx_metadata(k,:);n=row(1);
    assert(n>=1&&n<=300&&n==floor(n)&&row(2)>=0&&row(2)<=59&&row(2)==floor(row(2)), ...
        'gpenmpcNative:CompiledRawTxRange','Output record dimensions/query number are invalid.');
    outputs{k}=struct('bytes',core.tx_frames(1:n,k),'query',row(2),'fragment',row(3), ...
        'queued_at_simulation_s',row(4),'output_at_simulation_s',row(5));
end
datagrams=cell(0,1);
if isfield(core,'tx_datagram_count')
    nd=double(core.tx_datagram_count);
    assert(nd>=0&&nd<=178&&nd==floor(nd)&&isequal(size(core.tx_datagram_bytes),[300 nd]) ...
        &&isequal(size(core.tx_datagram_metadata),[nd 8])&&isequal(size(core.tx_datagram_qpc),[nd 1]) ...
        &&isa(core.tx_datagram_qpc,'uint64')&&isa(core.tx_datagram_bytes,'uint8') ...
        &&strcmp(core.transport_scope,'HOST_ONLY_NO_COPTERSIM_UDP_COM_PROOF'), ...
        'gpenmpcNative:CompiledRawDatagramShape','Bounded actual datagram ledger required.');
    datagrams=cell(nd,1);nextFrame=0;
    for k=1:nd
        row=core.tx_datagram_metadata(k,:);n=row(1);count=row(2);first=row(3);
        assert(n>=6&&n<=300&&count>=1&&count<=2&&count==floor(count)&&first==nextFrame ...
            &&first+count<=tx&&core.tx_datagram_qpc(k)>0 ...
            &&(k==1||core.tx_datagram_qpc(k)>=core.tx_datagram_qpc(k-1)), ...
            'gpenmpcNative:CompiledRawDatagramRange','Datagram count/frame order/QPC invalid.');
        offsets=row([4 6]);lengths=row([5 7]);bytes=core.tx_datagram_bytes(1:n,k);offset=0;
        for j=1:count
            index=first+j;f=outputs{index};
            assert(offsets(j)==offset&&lengths(j)==numel(f.bytes)&&offset+lengths(j)<=n ...
                &&isequal(bytes(offset+1:offset+lengths(j)),f.bytes)&&row(8)==f.output_at_simulation_s, ...
                'gpenmpcNative:CompiledRawDatagramBytes','No dropped, padded, reordered or rewritten original frame bytes.');
            outputs{index}.datagram_index=k;outputs{index}.datagram_frame_index=j;
            outputs{index}.datagram_byte_offset=offset;
            outputs{index}.shared_datagram_exposure_qpc=core.tx_datagram_qpc(k);
            offset=offset+lengths(j);
        end
        assert(offset==n,'gpenmpcNative:CompiledRawDatagramTail','Every datagram byte must belong to an original frame.');
        datagrams{k}=struct('bytes',bytes,'frame_count',count,'first_frame_index',first+1, ...
            'frame_offsets',offsets(1:count),'frame_lengths',lengths(1:count), ...
            'output_at_simulation_s',row(8),'exposed_qpc',core.tx_datagram_qpc(k), ...
            'clock_semantics','ACTUAL_SHARED_HOST_OUTPUT_EXPOSURE_NOT_NETWORK_ARRIVAL_OR_SEND_CONFIRMATION');
        nextFrame=nextFrame+count;
    end
    assert(nextFrame==tx,'gpenmpcNative:CompiledRawDatagramCoverage','Every transmitted frame needs exactly one datagram mapping.');
end
for k=1:completed
    request=core.query_requests(:,k);q=gpenmpcNative.RflyLocalGpCodec.decodeRequest(request);
    reply=core.query_replies(:,k);r=gpenmpcNative.RflyLocalGpCodec.decodeReply(reply);
    assert(isequal(r.result18,core.query_result18(k,:).'), ...
        'gpenmpcNative:CompiledRawReplyNumerics','Reply bytes and retained result18 differ.');
    frames=cell(3,1);
    for j=1:tx
        if outputs{j}.query==k
            index=outputs{j}.fragment+1;
            assert(index>=1&&index<=3&&index==floor(index)&&isempty(frames{index}), ...
                'gpenmpcNative:CompiledRawDuplicateOutput','Duplicate or invalid output fragment.');
            frames{index}=outputs{j}.bytes;
        end
    end
    qt=core.query_qpc(k,:);
    assert(qt(3)>=qt(2)&&qt(2)>=qt(1), ...
        'gpenmpcNative:CompiledRawQueryClock','Observed receive and GP timestamps must be causal.');
    queries{k}=struct('index',k,'pending',struct('message',request,'decoded',q), ...
        'reply_bytes',reply,'result18',core.query_result18(k,:), ...
        'gp_call_index',k,'gp_mex_wall_s',double(qt(3)-qt(2))/double(core.qpc_frequency), ...
        'completion_at_simulation_s',core.query_times(k),'reply_frames',{frames}, ...
        'exact_query_qpc',qt,'normalization_source','POST_RUN_COMPILED_CORE_DATA_ONLY');
end
failure=struct();inflight=struct();
if core.error_code~=0
    failure=struct('code',core.error_code,'message',core.error_message,'update',core.error_update, ...
        'simulation_s',core.error_simulation_s,'qpc',core.error_qpc);
end
if calls>completed||core.pending_fragment_count>0
    inflight=struct('uncompleted_gp_calls',calls-completed,'pending_fragment_count',core.pending_fragment_count, ...
        'raw_is_preserved_in_compiled_core',true);
end
% Derive pending bytes from raw and query records.
% The auditor checks compiled send counters separately.
remaining=cell(double(core.remaining_queue_count),1);
ledger=struct('scope','COMPILED_RETAINED_C_QUERY_NATIVE_RAW_POSTRUN_NORMALIZED', ...
    'updates',u,'gp_calls',calls,'queries_completed',completed,'raw',{raw},'queries',{queries}, ...
    'system_output_frames',{outputs},'remaining_tx_queue',{remaining},'failure',failure, ...
    'in_flight_at_release',inflight,'compiled_core',core, ...
    'source_timestamps_and_publication_age_unchanged',true,'live_admission_proven',false, ...
    'controller_calls',0,'plant_runs',0,'sockets',0,'timers',0);
if isfield(core,'tx_datagram_count')
    ledger.system_output_datagrams=datagrams;ledger.reply_pair_datagrams=core.reply_pair_datagrams;
    ledger.transport_scope=core.transport_scope;
end
end
