function plan=prepare_m600_sensor_autocal_observation(outputPath,barrierTestPath)
% Prepare a rotation-only sensor observation with native autocalibration.
root=fileparts(fileparts(mfilename('fullpath')));mc=fullfile(root,'m600_coptersim');
project=gpenmpc_external_path('hil_configuration_archive');
phase=fullfile(project,'phases','02_m600_model_substitution');
mountTest=fullfile(gpenmpc_external_path('host_virtual_sensor_mount_contract'),'HOST_TEST_RESULT.json');
t=jsondecode(fileread(mountTest));
assert(t.passed&&t.legacy_case_count==34&&t.legacy_cases_passed==34&& ...
 t.v2_case_count>0&&t.v2_cases_passed==t.v2_case_count&&t.case_count==34+t.v2_case_count, ...
 'm600check:AutocalObservationTests','Complete old/new contract tests are required.');
contract=t.observation_contract;
assert(strcmp(contract.schema,'VIRTUAL_SENSOR_MOUNT_CONTRACT_V2_AUTOCAL_OBSERVED'));
options=struct('execution_kind','INITIALIZATION_OBSERVATION_ONLY', ...
 'runtime_path',fullfile(gpenmpc_external_path('sensor_aligned_runtime')), ...
 'dll_build',fullfile(gpenmpc_external_path('flat_terrain_model_dll'),'DLL_BUILD_RESULT.json'), ...
 'dll_probe',fullfile(gpenmpc_external_path('flat_terrain_dll_probe'),'PROBE_RESULT.json'), ...
 'dll_source_comparison',fullfile(gpenmpc_external_path('flat_terrain_dll_comparison'),'DLL_SOURCE_COMPARISON.json'), ...
 'actual_sensor_receipt',fullfile(gpenmpc_external_path('aligned_sensor_probe'),'SENSOR_FRAME_PAIR.json'), ...
 'actual_forwarding_receipt',fullfile(gpenmpc_external_path('sensor_aligned_forwarding'),'RESULT.json'), ...
 'terrain_map',fullfile(gpenmpc_external_path('sensor_aligned_runtime'),'external','map','LowGPU.txt'), ...
 'recovery_host_tests',fullfile(gpenmpc_external_path('sensor_aligned_host_regression'),'HOST_ONLY_RESULT.json'), ...
 'virtual_sensor_mount_contract',contract,'sensor_mount_host_tests',mountTest, ...
 'sensor_frame_model_receipt',fullfile(gpenmpc_external_path('flat_terrain_model'),'MODEL_BUILD_RESULT.json'), ...
 'sensor_calibration_readonly',fullfile(gpenmpc_external_path('m600_sensor_aligned_native_hover'), ...
    'SIM_CALIBRATION_READONLY','SIM_CALIBRATION.json'), ...
 'copter_init_observer_tests',fullfile(gpenmpc_external_path('copter_init_observer_host'),'RESULT.json'), ...
 'initialization_observer_tests',fullfile(gpenmpc_external_path('initialization_observer_host'),'RESULT.json'), ...
 'plant_identity','CURRENT_M600_19STATE_RK4_10MS__NEUTRAL_2_21KG__RAW_SENSOR_LEVEL_INVERSE__NATIVE_AUTOCAL_OBSERVED__NO_ARM_DIAGNOSTIC');
if nargin>=2,options.copter_barrier_tests=barrierTestPath;end
plan=prepare_m600_native_plan(outputPath,options);
end
