function p=prepare_m600_native_plan(outputPath,options)
% Bind the completed current MATLAB/Simulink evidence. File preparation only.
root=fileparts(fileparts(mfilename('fullpath')));mc=fullfile(root,'m600_coptersim');
project=gpenmpc_external_path('hil_configuration_archive');
runtime=fullfile(gpenmpc_external_path('native_model_runtime'));
input=struct('runtime_path',runtime, ...
    'dll_build',fullfile(gpenmpc_external_path('sensor_aligned_model_dll'),'DLL_BUILD_RESULT.json'), ...
    'dll_probe',fullfile(gpenmpc_external_path('sensor_aligned_dll_probe'),'PROBE_RESULT.json'), ...
    'dll_source_comparison',fullfile(gpenmpc_external_path('sensor_aligned_dll_comparison'),'DLL_SOURCE_COMPARISON.json'), ...
    'actual_sensor_receipt',fullfile(gpenmpc_external_path('level_sensor_probe'),'SENSOR_CHECK_RECOMPUTED.json'), ...
    'actual_forwarding_receipt',fullfile(gpenmpc_external_path('native_model_forwarding'),'RESULT.json'), ...
    'terrain_map',fullfile(runtime,'external','map','LowGPU.txt'), ...
    'firmware',gpenmpc_external_path('native_application_firmware'), ...
    'hil_profile',fullfile(gpenmpc_external_path('official_generic_hex_hil'),'FINAL_HIL_PROFILE.json'), ...
    'recovery_host_tests',fullfile(gpenmpc_external_path('native_model_host_regression'),'HOST_ONLY_RESULT.json'), ...
    'owned_job_host_tests',gpenmpc_external_path('owned_job_receipt'), ...
    'plant_identity','CURRENT_M600_19STATE_RK4_10MS__NEUTRAL_2_21KG__LOWGPU_FLAT__KINEMATIC_ACCB_SINGLE_GRAVITY__NOT_CAMBRIDGE_TASK', ...
    'live_enabled',true);
if nargin>=2
    names=fieldnames(options);
    for k=1:numel(names),input.(names{k})=options.(names{k});end
end
p=prepare_m600_canonical_plan(input,outputPath);
disp(struct('plan',outputPath,'references',numel(p.references),'preparation_COM_open',0));
end
