function plan=prepare_m600_sensor_aligned_hover(outputPath,hoverTestPath,recoveryTestPath,apiTestPath,outerTestPath,geometryHostTests,geometryApiTestPath,successorOptions)
% Prepare the next execution identity without modifying observation data.
root=fileparts(fileparts(mfilename('fullpath')));mc=fullfile(root,'m600_coptersim');
addpath(fullfile(root,'tools'),fullfile(mc,'matlab_validation'));
project=gpenmpc_external_path('hil_configuration_archive');
phase=fullfile(project,'phases','02_m600_model_substitution');
mountTest=fullfile(gpenmpc_external_path('host_virtual_sensor_mount_contract'),'HOST_TEST_RESULT.json');
t=jsondecode(fileread(mountTest));
assert(t.passed&&t.case_count==t.cases_passed,'m600check:MountHostTests');
context=make_sensor_aligned_hover_preparation();
contract=t.observation_contract;
check=m600check.verifySensorAlignedHoverPreparation(context,contract);
assert(check.passed,'m600check:HoverPreparationRejected','%s',check.failure);
options=struct('execution_kind','NATIVE_HOVER', ...
 'runtime_path',fullfile(gpenmpc_external_path('sensor_aligned_runtime')), ...
 'dll_build',fullfile(gpenmpc_external_path('flat_terrain_model_dll'),'DLL_BUILD_RESULT.json'), ...
 'dll_probe',fullfile(gpenmpc_external_path('flat_terrain_dll_probe'),'PROBE_RESULT.json'), ...
 'dll_source_comparison',fullfile(gpenmpc_external_path('flat_terrain_dll_comparison'),'DLL_SOURCE_COMPARISON.json'), ...
 'actual_sensor_receipt',fullfile(gpenmpc_external_path('aligned_sensor_probe'),'SENSOR_FRAME_PAIR.json'), ...
 'actual_forwarding_receipt',fullfile(gpenmpc_external_path('sensor_aligned_forwarding'),'RESULT.json'), ...
 'terrain_map',fullfile(gpenmpc_external_path('sensor_aligned_runtime'),'external','map','LowGPU.txt'), ...
 'recovery_host_tests',recoveryTestPath,'actual_api_receipt',apiTestPath, ...
 'virtual_sensor_mount_contract',contract,'sensor_mount_host_tests',mountTest, ...
 'sensor_frame_model_receipt',fullfile(gpenmpc_external_path('flat_terrain_model'),'MODEL_BUILD_RESULT.json'), ...
 'sensor_calibration_readonly',fullfile(gpenmpc_external_path('m600_sensor_aligned_native_hover'), ...
    'SIM_CALIBRATION_READONLY','SIM_CALIBRATION.json'), ...
 'native_hover_preparation',context,'hover_preparation_tests',hoverTestPath, ...
 'native_telemetry_tests',fullfile(gpenmpc_external_path('host_native_hover_telemetry'),'NATIVE_HOVER_TELEMETRY_TESTS.json'), ...
 'copter_barrier_tests',fullfile(gpenmpc_external_path('host_copter_initialization_barrier'),'RESULT.json'), ...
 'copter_barrier_outer_tests',outerTestPath, ...
 'plant_identity','CURRENT_M600_19STATE_RK4_10MS__NEUTRAL_2_21KG__RAW_SENSOR_LEVEL_INVERSE__NATIVE_AUTOCAL__NATIVE_HOVER_NOT_CAMBRIDGE_TASK');
if nargin>=6&&~isempty(geometryHostTests)
    options.temporary_allocator_geometry=m600check.buildTemporaryAllocatorGeometryContract( ...
        fullfile(gpenmpc_external_path('host_native_rotor_geometry'),'RESULT.json'));
    options.geometry_host_tests=geometryHostTests;
    assert(nargin>=7,'m600check:GeometryApiReceiptRequired','Supply the currently executed REAL32 API test receipt.');
    options.geometry_api_tests=geometryApiTestPath;
end
if nargin>=8
    % Require explicit successor inputs and their execution records.
    assert(isstruct(successorOptions)&&isscalar(successorOptions),'m600check:SuccessorOptions', ...
        'Successor options must be one struct.');
    allowed={'terrain_diagnostic_runtime_contract','terrain_runtime_host_tests', ...
        'runtime_path','actual_forwarding_receipt','dll_source_comparison', ...
        'native_hover_tuning','tuning_contract_tests','tuning_transfer_tests', ...
        'tuning_union_tests','tuning_api_tests','execution_kind', ...
        'copter_init_observer_tests','initialization_observer_tests'};
    assert(all(ismember(fieldnames(successorOptions),allowed)), ...
        'm600check:SuccessorOptionUnknown','Unknown successor input; legacy identities may not be overridden.');
    if isfield(successorOptions,'terrain_diagnostic_runtime_contract')
        needed={'terrain_runtime_host_tests','runtime_path','actual_forwarding_receipt','dll_source_comparison'};
        assert(all(isfield(successorOptions,needed)),'m600check:TerrainSuccessorEvidenceMissing', ...
            'Supply exact completed comparison, HOST tests, runtime and no-board forwarding paths.');
        tc=successorOptions.terrain_diagnostic_runtime_contract;
        tv=m600check.validateTerrainDiagnosticRuntimeContract(tc);
        assert(tv.passed,'m600check:TerrainSuccessorRejected','%s',tv.failure);
        options.dll_build=terrainPath(tc,'new_dll_build');
        options.dll_probe=terrainPath(tc,'legacy_probe');
        options.require_terrain_diagnostic_extension=true;
        options.terrain_map=fullfile(successorOptions.runtime_path,'external','map','LowGPU.txt');
        % Use the separate derivation record to bind sensor/model observations to the DLL.
    else
        forbidden={'terrain_runtime_host_tests','runtime_path','actual_forwarding_receipt','dll_source_comparison'};
        assert(~any(isfield(successorOptions,forbidden)),'m600check:TerrainContractRequired', ...
            'Runtime and terrain evidence overrides require the explicit terrain derivation contract.');
    end
    if isfield(successorOptions,'native_hover_tuning')
        assert(all(isfield(successorOptions,{'tuning_contract_tests','tuning_transfer_tests','tuning_union_tests','tuning_api_tests'})), ...
            'm600check:TuningSuccessorEvidenceMissing','Supply completed tuning contract, transfer, union and API test receipts.');
        assert(isfield(options,'temporary_allocator_geometry'),'m600check:TuningGeometryRequired', ...
            'Tuning3 requires the separately bound geometry12 contract.');
    else
        assert(~any(isfield(successorOptions,{'tuning_contract_tests','tuning_transfer_tests','tuning_union_tests','tuning_api_tests'})), ...
            'm600check:TuningContractRequired','Tuning test receipts require an explicit native-hover tuning contract.');
    end
    names=fieldnames(successorOptions);
    for k=1:numel(names),options.(names{k})=successorOptions.(names{k});end
end
plan=prepare_m600_native_plan(outputPath,options);
end
function file=terrainPath(contract,label)
r=contract.bindings(strcmp({contract.bindings.label},label));
assert(isscalar(r),'m600check:TerrainBindingMissing','%s',label);file=r.path;
end
