function report=prepare_canonical_delivery_model(outputDir,expectedSessionToken)
% PREPARE_CANONICAL_DELIVERY_MODEL Derive the delivery model.
arguments
    outputDir (1,1) string
    expectedSessionToken (1,1) double {mustBeInteger,mustBePositive}
end
assert(expectedSessionToken<=flintmax,'m600check:SessionToken','Token must be exact in double.');
outputDir=string(char(java.io.File(char(outputDir)).getCanonicalPath()));
assert(~isfolder(outputDir)&&~isfile(outputDir),'m600check:ExistingDeliveryModel', ...
    'Use a new model-output directory.');
build=string(fileparts(fileparts(mfilename('fullpath'))));
modelRoot=fullfile(build,'m600_coptersim');kernel=fullfile(build,'matlab_validation');
parent=fullfile(gpenmpc_external_path('diagnostic_terrain_model'),'GPENMPC_M600_Canonical.slx');
parameterParent=fullfile(fileparts(parent),'M600_CORE_PARAMETERS.mat');
parentSha='8A51BDA54AB552953AEC2D6ABF53634FEAB40DA4F2489A3EB09E56146254F03C';
parameterParentSha='969D347CE041715CAED49BE0B7897486E34FA4E0B22EB82E50E9752B8F4F19E4';
assert(strcmpi(fileSha(parent),parentSha),'m600check:DeliveryParentModelIdentity');
assert(strcmpi(fileSha(parameterParent),parameterParentSha),'m600check:DeliveryParentParameterIdentity');
required=[ ...
    fullfile(kernel,'+m600check','copterSimDeliveryCore.m'); ...
    fullfile(kernel,'+m600check','passiveGroundDissipation.m'); ...
    fullfile(kernel,'+m600check','encodeCopterSimDeliveryDiagnostics.m'); ...
    fullfile(kernel,'+m600check','derivativeSoftware.m'); ...
    fullfile(kernel,'+m600check','copterSimIoCore.m'); ...
    fullfile(kernel,'+gpenmpcTaskIo','initPlantEnvironmentV2.m'); ...
    fullfile(kernel,'+gpenmpcTaskIo','acceptPlantEnvironmentV2.m'); ...
    fullfile(kernel,'+gpenmpcTaskIo','commitPlantEnvironmentV2.m')];
assert(all(isfile(required)),'m600check:DeliveryHelpersMissing');
mkdir(outputDir);
modelFile=fullfile(outputDir,'GPENMPC_M600_Canonical.slx');
parameterFile=fullfile(outputDir,'M600_CORE_PARAMETERS.mat');
copyfile(parent,modelFile);copyfile(parameterParent,parameterFile);
[ok,~]=fileattrib(modelFile,'+w');assert(ok,'m600check:DeliveryModelWritable');
loaded=load(parameterFile,'parameters','environment');
parameters=loaded.parameters;environment=loaded.environment;
assert(environment.payload_kg==2.21&&isequal(environment.wind_xy_mps,zeros(2,1)) ...
    &&isequal(environment.reference_jet_ned,zeros(12,1)),'m600check:DeliveryInitialEnvironment');
parameters.ground_dissipation=struct('enabled',true, ...
    'coefficient_of_friction',0.4, ...
    'provenance','PROJECT_ENGINEERING_CANDIDATE__NOT_MEASURED_LANDING_GEAR');
% Host acceptance requires heartbeat age <=3.0 s and landed-state age <=2.0 s.
% The asynchronous plant also allows the 0.25 s environment transport budget,
% giving a 3.25 s plant-side bound while preserving the host gates.
deliveryPolicy=struct( ...
    'initial_payload_kg',2.21,'initial_wind_ned_xy_mps',zeros(2,1), ...
    'initial_reference_jet_ned',zeros(12,1), ...
    'expected_session_token',expectedSessionToken,'max_env_age_s',0.25, ...
    'max_board_age_s',3.25,'max_future_skew_s',0.05, ...
    'max_ground_sample_gap_s',0.05,'unload_dwell_s',8.0, ...
    'max_commit_delay_s',0.05, ...
    'base_mass_kg',parameters.profile.mass_properties.base_mass_kg, ...
    'mass_bias_kg',parameters.mission.plant_mismatch.mass_bias_kg, ...
    'mass_tolerance_kg',1e-12, ...
    'service_payload_targets_kg',[1.75;0.98;0.55;0.0]);
save(parameterFile,'parameters','environment','deliveryPolicy','-v7');
oldPath=path;pathGuard=onCleanup(@()path(oldPath)); %#ok<NASGU>
addpath(kernel,fullfile(modelRoot,'matlab_validation'),outputDir,'-begin');
% Resolve and verify dynamics and reference dependencies.
m600check.loadFixture();
mdl='GPENMPC_M600_Canonical';assert(~bdIsLoaded(mdl),'m600check:DeliveryModelAlreadyLoaded');
oldDir=pwd;cd(outputDir);cwdGuard=onCleanup(@()cd(oldDir)); %#ok<NASGU>
modelGuard=onCleanup(@()closeOwned(mdl)); %#ok<NASGU>
report=struct('schema','HOST_CANONICAL_DELIVERY_MODEL_PREPARATION_V1', ...
    'status','IN_PROGRESS','passed',false,'failure','', ...
    'parent_model',parent,'parent_model_sha256',parentSha, ...
    'parent_parameters',parameterParent,'parent_parameters_sha256',parameterParentSha, ...
    'model',modelFile,'model_sha256','','parameters',parameterFile,'parameters_sha256','', ...
    'expected_session_token',expectedSessionToken,'in_doub_ctrls_dimension',28, ...
    'delivery_payload_targets_kg',deliveryPolicy.service_payload_targets_kg, ...
    'ground_dissipation_mu',0.4,'ground_dissipation_not_measured_gear',true, ...
    'host_heartbeat_freshness_s',3.0,'host_extended_state_freshness_s',2.0, ...
    'environment_inflight_budget_s',0.25,'derived_board_evidence_bound_s',3.25, ...
    'source_paths',required,'source_sha256',strings(size(required)), ...
    'old_chart_sha256','','new_chart_sha256','', ...
    'parent_unchanged',false,'model_updated',false,'input_export_pending',true, ...
    'code_generation_completed',false,'DLL_generated',false, ...
    'COM_open',0,'UDP_open',0,'board_actions',0,'physical_output',0, ...
    'claim','Delivery model prepared.');
for k=1:numel(required),report.source_sha256(k)=fileSha(required(k));end
try
    evalin('base',"run('"+fullfile(modelRoot,'GPENMPC_M600_CopterSim_init.m')+"')");
    evalin('base','ModelInit_PosE=[0,0,0];ModelInit_AngEuler=[0,0,0];');
    load_system(modelFile);
    sf=sfroot;core=sf.find('-isa','Stateflow.EMChart','Path',[mdl '/CurrentM600_10ms']);
    assert(isscalar(core),'m600check:DeliveryCoreNotUnique');
    oldScript=char(core.Script);report.old_chart_sha256=textSha(oldScript);
    signature=['function [Ve,Xe,euler,DCM,Vb,wb,dwb,AccB,WindB,mass,gravity,' ...
        'animation,diagnostic] = fcn(u,pos0,ang0,terrain)'];
    newSignature=['function [Ve,Xe,euler,DCM,Vb,wb,dwb,AccB,WindB,mass,gravity,' ...
        'animation,diagnostic] = fcn(u,pos0,ang0,terrain,environmentFrame,ioTime)'];
    oldLoad="data=coder.load('M600_CORE_PARAMETERS.mat','parameters','environment');";
    newLoad="data=coder.load('M600_CORE_PARAMETERS.mat','parameters','environment','deliveryPolicy');";
    oldCall=['[y,d]=m600check.copterSimFlatTerrainCore(reshape(u,16,1),reset,' ...
        'reshape(pos0,3,1),reshape(ang0,3,1),data.environment,terrainSnapshot,data.parameters);'];
    newCall=sprintf(['[y,d,deliveryAck,environmentReceipt]=m600check.copterSimDeliveryCore( ...\n' ...
        '    reshape(u,16,1),reset,reshape(pos0,3,1),reshape(ang0,3,1),terrainSnapshot, ...\n' ...
        '    reshape(environmentFrame,28,1),ioTime,data.environment,data.parameters,data.deliveryPolicy);']);
    oldMass='mass=data.parameters.profile.mass_properties.base_mass_kg+data.environment.payload_kg; gravity=[0;0;9.80665];';
    newMass='mass=y.mass_kg; gravity=[0;0;9.80665];';
    oldDiagnostic=sprintf(['[diagnostic,terrainCapture]=m600check.encodeCopterSimTerrainDiagnostics( ...\n' ...
        '    diagnosticPrefix,terrainSnapshot,d.terrain_failure_reason,d.terrain_world_ned_z_m, ...\n' ...
        '    d.terrain_fault_latched,d.reset_applied,terrainCapture);']);
    newDiagnostic=sprintf(['[terrainDiagnostic,terrainCapture]=m600check.encodeCopterSimTerrainDiagnostics( ...\n' ...
        '    diagnosticPrefix,terrainSnapshot,d.terrain_failure_reason,d.terrain_world_ned_z_m, ...\n' ...
        '    d.terrain_fault_latched,d.reset_applied,terrainCapture);\n' ...
        'diagnostic=m600check.encodeCopterSimDeliveryDiagnostics( ...\n' ...
        '    terrainDiagnostic,deliveryAck,environmentReceipt.pending);']);
    changes={signature,newSignature;char(oldLoad),char(newLoad);oldCall,newCall;oldMass,newMass;oldDiagnostic,newDiagnostic};
    newScript=oldScript;
    for k=1:size(changes,1)
        assert(count(string(newScript),string(changes{k,1}))==1,'m600check:DeliveryPatchAnchor','Patch anchor %d.',k);
        newScript=strrep(newScript,changes{k,1},changes{k,2});
    end
    core.Script=newScript;report.new_chart_sha256=textSha(newScript);
    symbols=core.find('-isa','Stateflow.Data');
    for k=1:numel(symbols)
        switch symbols(k).Name
            case 'environmentFrame',symbols(k).DataType='double';symbols(k).Props.Array.Size='28';
            case 'ioTime',symbols(k).DataType='double';symbols(k).Props.Array.Size='1';
        end
    end
    add_block('simulink/Sources/In1',[mdl '/inDoubCtrls'], ...
        'Port','3','PortDimensions','28','SampleTime','0.001');
    add_block('simulink/Sources/Clock',[mdl '/DeliveryIoClock']);
    add_line(mdl,'inDoubCtrls/1','CurrentM600_10ms/5');
    add_line(mdl,'DeliveryIoClock/1','CurrentM600_10ms/6');
    set_param(mdl,'SimulationCommand','update');report.model_updated=true;
    assert(strcmp(core.Script,newScript),'m600check:DeliveryChartChangedOnUpdate');
    assert(strcmp(get_param([mdl '/inDoubCtrls'],'PortDimensions'),'28'),'m600check:DeliveryInputDimension');
    save_system(mdl,modelFile);
    assert(strcmpi(fileSha(parent),parentSha)&&strcmpi(fileSha(parameterParent),parameterParentSha), ...
        'm600check:DeliveryParentChanged');
    report.model_sha256=fileSha(modelFile);report.parameters_sha256=fileSha(parameterFile);
    report.parent_unchanged=true;report.status='PASS_HOST_MODEL_UPDATE_ONLY__CODEGEN_DLL_PROBE_PENDING';report.passed=true;
catch problem
    report.status='HOST_MODEL_PREPARATION_FAILED__NOT_HIL_RESULT';
    report.failure=getReport(problem,'extended','hyperlinks','off');
    report.parent_unchanged=strcmpi(fileSha(parent),parentSha)&&strcmpi(fileSha(parameterParent),parameterParentSha);
    if isfile(modelFile),report.model_sha256=fileSha(modelFile);end
    if isfile(parameterFile),report.parameters_sha256=fileSha(parameterFile);end
end
writeText(fullfile(outputDir,'MODEL_PREPARATION_RESULT.json'),jsonencode(report,PrettyPrint=true));
disp(struct('status',report.status,'model',report.model,'COM_open',0,'DLL_generated',false));
assert(report.passed,'m600check:DeliveryModelPreparationFailed','%s',report.failure);
end

function closeOwned(mdl),if bdIsLoaded(mdl),close_system(mdl,0);end,end
function h=fileSha(p)
f=fopen(p,'rb');assert(f>=0,'m600check:MissingFile','Missing %s',p);
c=onCleanup(@()fclose(f)); %#ok<NASGU>
md=java.security.MessageDigest.getInstance('SHA-256');md.update(uint8(fread(f,Inf,'*uint8')));
h=upper(reshape(dec2hex(typecast(md.digest(),'uint8'),2).',1,[]));
end
function h=textSha(t)
md=java.security.MessageDigest.getInstance('SHA-256');md.update(uint8(unicode2native(t,'UTF-8')));
h=upper(reshape(dec2hex(typecast(md.digest(),'uint8'),2).',1,[]));
end
function writeText(p,t)
f=fopen(p,'w','n','UTF-8');assert(f>=0);c=onCleanup(@()fclose(f)); %#ok<NASGU>
fprintf(f,'%s\n',t);
end
