function plan=prepare_native_tuned_hover_current(outputPlan)
% Assemble the native-hover configuration.
b=fileparts(fileparts(mfilename('fullpath')));mc=fullfile(b,'m600_coptersim');e=fullfile(b,'evidence');
addpath(fullfile(b,'tools'),fullfile(mc,'matlab_validation'));
[terrain,tv]=m600check.buildTerrainDiagnosticRuntimeContract();assert(tv.passed,'%s',tv.failure);
[tuning,nv]=m600check.buildNativeHoverTuningContract();assert(nv.passed,'%s',nv.failure);
options=struct('terrain_diagnostic_runtime_contract',terrain, ...
    'terrain_runtime_host_tests',fullfile(gpenmpc_external_path('host_terrain_runtime_contract'),'RESULT.json'), ...
    'runtime_path',gpenmpc_external_path('terrain_diagnostic_coptersim_runtime'), ...
    'actual_forwarding_receipt',fullfile(gpenmpc_external_path('canonical_no_board_forwarding'),'RESULT.json'), ...
    'dll_source_comparison',fullfile(gpenmpc_external_path('host_terrain_dll_source_compare'),'DLL_SOURCE_COMPARISON.json'), ...
    'native_hover_tuning',tuning, ...
    'tuning_contract_tests',fullfile(gpenmpc_external_path('host_native_hover_tuning_contract'),'HOST_RESULT.json'), ...
    'tuning_transfer_tests',fullfile(gpenmpc_external_path('host_native_hover_tuning_transfer'),'RESULT.json'), ...
    'tuning_union_tests',fullfile(gpenmpc_external_path('host_native_hover_parameter_union'),'RESULT.json'), ...
    'tuning_api_tests',fullfile(gpenmpc_external_path('host_native_hover_tuning_loopback'),'RESULT.json'));
plan=prepare_m600_sensor_aligned_hover(outputPlan, ...
    fullfile(gpenmpc_external_path('host_sensor_aligned_hover_preparation'),'RESULT.json'), ...
    fullfile(gpenmpc_external_path('host_geometry_integration'),'outer','HOST_ONLY_RESULT.json'), ...
    fullfile(gpenmpc_external_path('host_terrain_extension_real_api'),'HOST_API_RESULT.json'), ...
    fullfile(gpenmpc_external_path('host_copter_barrier_outer'),'RESULT.json'), ...
    fullfile(gpenmpc_external_path('host_geometry_integration'),'RESULT.json'), ...
    fullfile(gpenmpc_external_path('host_geometry_real_parameter_api'),'REAL_PARAMETER_API_RESULT.json'),options);
end
