function report=prepare_native_attitude_candidate(newOutputDir)
% Derive an attitude-P candidate from typed gains and MODEL009.
% Root and frequency calculations use base MATLAB.
arguments
    newOutputDir (1,1) string
end
assert(~isfolder(newOutputDir)&&~isfile(newOutputDir), ...
    'gpenmpc:CandidateOutputExists','Use a new output directory; preserve earlier evidence.');
build=string(fileparts(fileparts(mfilename('fullpath'))));
toolsDir=fullfile(build,'tools');
oldPath=path;pathCleanup=onCleanup(@()path(oldPath)); %#ok<NASGU>
addpath(toolsDir,'-begin');
mkdir(newOutputDir);
report=struct('schema','HOST_NATIVE_ATTITUDE_P_ROUTH_CANDIDATE_V1', ...
    'classification','HOST_ALGEBRAIC_PARAMETER_CANDIDATE', ...
    'passed',false,'failure','','created_utc',char(datetime('now','TimeZone','UTC', ...
    'Format','yyyy-MM-dd''T''HH:mm:ss.SSS''Z''')), ...
    'hardware_actions',0,'COM_UDP_actions',0,'parameter_writes',0, ...
    'model_or_production_source_changes',0,'live_admission',false, ...
    'terrain_source_cause_identified',false,'SIL_outcomes_read',false, ...
    'script_identity',identity([mfilename('fullpath') '.m']), ...
    'input_bindings',struct([]),'checks',struct('name',{},'passed',{}));
parameters=[];environment=[];originalCfg=[];candidateCfg=[];
try
    currentSource=fullfile(toolsDir,'native_lower_loop_current_config.m');
    fixtureSource=fullfile(toolsDir,'native_lower_loop_explicit_fixture.m');
    algebraSource=fullfile(toolsDir,'run_native_control_small_signal_audit.m');
    modelPath=fullfile(gpenmpc_external_path('flat_terrain_model'),'M600_CORE_PARAMETERS.mat');
    geometryPath=fullfile(gpenmpc_external_path('host_native_rotor_geometry'),'RESULT.json');
    sourceSpecs={currentSource,'E5B80D24F01A2ECE6D5E7D217C8B2F813AEF78FD0EFB13274DCD1E4B009309EF'; ...
        fixtureSource,'DCD003F67B30A04388EAE01D327874C65ADCD604A343D74ACA45EB32201193DC'; ...
        algebraSource,'344832CE31A977BFEC4F4153A4B95D2817BE9A353C507E990F6571A2ADC7A3F5'; ...
        modelPath,'969D347CE041715CAED49BE0B7897486E34FA4E0B22EB82E50E9752B8F4F19E4'; ...
        geometryPath,'4A399A8569FC3E0178AFF641A417586B86FC5589667439A82EE30D4EB2DEF511'};
    for k=1:size(sourceSpecs,1)
        id=identity(sourceSpecs{k,1});
        require(strcmp(id.sha256,sourceSpecs{k,2}),['Bound input changed: ' id.path]);
        appendBinding(id);
    end
    require(strcmpi(which('native_lower_loop_current_config'),currentSource) ...
        &&strcmpi(which('native_lower_loop_explicit_fixture'),fixtureSource),'Configuration function shadowing.');
    % Verify both receipts, all 105 typed rows, safety evidence and the 79 baseline rows.
    [originalCfg,metadata]=native_lower_loop_current_config();
    require(strcmp(originalCfg.parameter_provenance,'CURRENT_TYPED_ALL_REQUIRED') ...
        &&metadata.current105_typed_rows_verified==105 ...
        &&metadata.current_lower_kernel_parameter_count==34 ...
        &&metadata.original79_semantics_recomputed_match,'Incomplete current configuration.');
    for key={'original79','current105','current105_raw'}
        id=identity(metadata.(key{1}).path);
        require(isequal(id,metadata.(key{1})),'Configuration receipt identity mismatch.');
        appendBinding(id);
    end
    require(strcmp(metadata.current105.sha256, ...
        'EC504AEB12444D41B88DD0E5411DDAA3B59B513AB9410433736A5B59C47E1D9C'), ...
        'Current105 is not the prescribed read-only observation.');
    loaded=load(modelPath,'parameters','environment');
    require(isfield(loaded,'parameters')&&isfield(loaded,'environment'),'MODEL009 variables missing.');
    parameters=loaded.parameters;environment=loaded.environment;
    rotor=parameters.calibration.rotor_allocation;
    J=double(parameters.calibration.mass_inertia.inertia_nominal_kg_m2(:));
    tau=double(rotor.actuator_time_constant_nominal_s);
    Fmax=double(rotor.per_rotor_thrust_upper_n);
    arm=double(rotor.arm_radius_m);yawArm=double(rotor.yaw_moment_arm_nominal_m);
    angles=double(rotor.angles_deg(:));spin=double(rotor.spin_sign(:));
    require(numel(J)==3&&all(isfinite(J)&J>0)&&isscalar(tau)&&isfinite(tau)&&tau>0 ...
        &&isscalar(Fmax)&&isfinite(Fmax)&&Fmax>0&&isscalar(arm)&&isfinite(arm)&&arm>0 ...
        &&isscalar(yawArm)&&isfinite(yawArm)&&numel(angles)==6&&numel(spin)==6 ...
        &&all(isfinite(angles))&&all(ismember(spin,[-1;1])),'Invalid unchanged model constants.');
    require(isequal(parameters.mission.plant_mismatch.thrust_effectiveness_by_rotor(:),ones(6,1)) ...
        &&~parameters.mission.structured_residual.enabled, ...
        'The scalar neutral-rotor derivation does not cover changed thrust effectiveness/residuals.');
    proof=jsondecode(fileread(geometryPath));a=proof.audit;
    require(proof.passed&&a.passed&&a.candidate_geometry_aligned&&a.hardware_actions==0, ...
        'Corrected geometry proof failed.');
    order=double(a.canonical.rotor_order(:));
    require(isequal(sort(order),(1:6).')&&arm==a.canonical.arm_radius_m ...
        &&yawArm==a.canonical.yaw_arm_m&&Fmax==a.canonical.thrust_upper_n ...
        &&isequal(angles,a.canonical.angles_deg(:))&&isequal(spin,a.canonical.spin_sign(:)), ...
        'MODEL009 physical allocation is not the bound corrected-geometry model.');
    E=double(originalCfg.effectiveness);
    require(isequal(E,double(a.proposed_effectiveness_6x6)),'Configured allocator matrix differs.');
    [mix,normalization]=normalizedMix(E);
    physical=zeros(6,6);
    for ch=1:6
        rotorIndex=find(order==ch);x=arm*cosd(angles(rotorIndex));y=arm*sind(angles(rotorIndex));
        physical(:,ch)=Fmax*[-y;x;yawArm*spin(rotorIndex);0;0;-1];
    end
    K=physical(1:2,:)*mix(:,1:2);
    scale=max(1,max(abs(diag(K))));
    check('MODEL009_WRENCH_MATCHES_GEOMETRY_PROVENANCE', ...
        max(abs(physical-double(a.canonical_wrench_per_normalized_control)),[],'all')<1e-10);
    check('CORRECTED_ROLL_PITCH_DECOUPLED_TO_NUMERICAL_PRECISION', ...
        all(diag(K)>0)&&max(abs(K-diag(diag(K))),[],'all')<1e-10*scale);
    g=diag(K)./J(1:2);
    p=double(originalCfg.rate_k(1:2).*originalCfg.rate_p(1:2));
    i=double(originalCfg.rate_k(1:2).*originalCfg.rate_i(1:2));
    d=double(originalCfg.rate_k(1:2).*originalCfg.rate_d(1:2));
    originalA=double(originalCfg.attitude_p(1:2));
    require(all(isfinite([g;p;i;d;originalA]))&&all(g>0)&&all(p>0)&&all(i>0) ...
        &&all(d>=0)&&all(originalA>0)&&all(originalCfg.rate_ff(1:2)==0), ...
        'This I-enabled zero-FF derivation is not valid for the selected parameters.');
    check('CURRENT_ROLL_PITCH_ATTITUDE_P_REMAINS_6P5',isequal(originalA,[6.5;6.5]));
    report.current_configuration_metadata=metadata;
    report.original_configuration=originalCfg;
    report.model=struct('parameters_identity',identity(modelPath),'environment',environment, ...
        'J_kg_m2',J,'actuator_time_constant_s',tau,'per_rotor_full_scale_N',Fmax, ...
        'arm_radius_m',arm,'yaw_moment_arm_m',yawArm,'angles_deg',angles,'spin_sign',spin, ...
        'board_channel_to_canonical_rotor_order',order,'physical_wrench_per_normalized_command',physical, ...
        'corrected_effectiveness_6x6',E,'normalized_mix',mix,'normalization',normalization, ...
        'physical_roll_pitch_moment_gain',K,'angular_acceleration_gain_per_axis',g);
    report.equations=struct('assumptions','Near-level, airborne, unsaturated continuous dynamics with rate I enabled and zero rate feedforward.', ...
        'characteristic','tau*s^4+A*s^3+g*p*s^2+g*(p*a+i)*s+g*i*a=0; A=1+g*d', ...
        'routh_first_bound','a < A/tau-i/p', ...
        'routh_second_bound','a < (H+sqrt(H^2+4*tau*p^2*C))/(2*tau*p^2)', ...
        'H','A*p^2-2*tau*p*i-A^2*i/g','C','A*p*i-tau*i^2', ...
        'rate_closed_loop','H_rate(s)=g*(p*s+i)/(tau*s^3+A*s^2+g*p*s+g*i)', ...
        'outer_open_loop','L(s)=a*H_rate(s)/s', ...
        'selection','Common roll/pitch a = positive REAL32 floor of 0.5*min(both strict Routh bounds across both axes).');
    margin=0.5; % Engineering gain reserve.
    relativeProbe=1e-3; % Algebra-check perturbation.
    axisNames={'ROLL','PITCH'};axes=struct([]);bounds=zeros(2,1);
    for axisIndex=1:2
        ax=axisDerivation(axisNames{axisIndex},g(axisIndex),tau,p(axisIndex), ...
            i(axisIndex),d(axisIndex),originalA(axisIndex),relativeProbe);
        bounds(axisIndex)=min(ax.first_routh_upper_s_inverse,ax.second_routh_upper_s_inverse);
        if isempty(axes),axes=ax;else,axes(end+1)=ax;end %#ok<AGROW>
        check([axisNames{axisIndex} '_RATE_ONLY_I_ENABLED_STABLE'],ax.rate_only_roots.asymptotically_stable);
        check([axisNames{axisIndex} '_ORIGINAL_6P5_NEGATIVE_CONTROL'], ...
            ~ax.original.routh_stable&&~ax.original.roots.asymptotically_stable);
        check([axisNames{axisIndex} '_BELOW_CRITICAL_STABLE'], ...
            ax.below_critical.routh_stable&&ax.below_critical.roots.asymptotically_stable);
        check([axisNames{axisIndex} '_ABOVE_CRITICAL_UNSTABLE'], ...
            ~ax.above_critical.routh_stable&&~ax.above_critical.roots.asymptotically_stable);
        check([axisNames{axisIndex} '_CRITICAL_IMAGINARY_ROOT_RESIDUAL'], ...
            ax.critical_polynomial_relative_residual<1e-10);
    end
    unrounded=margin*min(bounds);
    candidate=singleFloorPositive(unrounded);
    candidateValue=double(candidate);candidateBits=upper(dec2hex(typecast(candidate,'uint32'),8));
    check('SINGLE_PRECISION_CANDIDATE_NOT_ROUNDED_ABOVE_RULE', ...
        candidateValue>0&&candidateValue<=unrounded);
    next=double(typecast(typecast(candidate,'uint32')+uint32(1),'single'));
    check('SINGLE_PRECISION_FLOOR_IS_GREATEST_NOT_ABOVE_RULE',next>unrounded);
    candidateCfg=originalCfg;candidateCfg.attitude_p(1:2)=candidateValue;
    verifyCfg=candidateCfg;verifyCfg.attitude_p(1:2)=originalCfg.attitude_p(1:2);
    check('ONLY_TWO_ATTITUDE_P_VALUES_CHANGE',isequaln(verifyCfg,originalCfg) ...
        &&all(candidateCfg.attitude_p(1:2)<originalCfg.attitude_p(1:2)));
    changes=struct('name',{},'mav_type',{},'original_value',{},'original_raw_bits_hex',{}, ...
        'candidate_value',{},'candidate_raw_bits_hex',{},'rollback_raw_bits_hex',{});
    selected=metadata.lower_kernel_current_parameter_rows;
    for axisIndex=1:2
        name=['MC_' axisNames{axisIndex} '_P'];row=selected(strcmp({selected.name},name));
        require(isscalar(row)&&row.mav_type==9&&row.value==originalA(axisIndex), ...
            'Original attitude parameter typed identity missing.');
        require(strcmp(row.raw_bits_hex,upper(dec2hex(typecast(single(row.value),'uint32'),8))), ...
            'Original attitude parameter raw bits mismatch.');
        changes(end+1)=struct('name',name,'mav_type',9,'original_value',row.value, ...
            'original_raw_bits_hex',row.raw_bits_hex,'candidate_value',candidateValue, ...
            'candidate_raw_bits_hex',candidateBits,'rollback_raw_bits_hex',row.raw_bits_hex); %#ok<AGROW>
        axes(axisIndex).candidate=caseAt(candidateValue,g(axisIndex),tau,p(axisIndex),i(axisIndex),d(axisIndex));
        axes(axisIndex).candidate_frequency=frequencyReport(candidateValue,g(axisIndex),tau,p(axisIndex),i(axisIndex),d(axisIndex));
        check([axisNames{axisIndex} '_FIXED_CANDIDATE_ROUTH_AND_ROOTS_STABLE'], ...
            axes(axisIndex).candidate.routh_stable&&axes(axisIndex).candidate.roots.asymptotically_stable);
        check([axisNames{axisIndex} '_FREQUENCY_POLYNOMIAL_RESIDUALS'], ...
            axes(axisIndex).candidate_frequency.unity_gain_residual<1e-8 ...
            &&axes(axisIndex).candidate_frequency.rate_minus3dB_residual<1e-8);
    end
    report.selection=struct('status','PROSPECTIVE_ONCE_ONLY_ALGEBRAIC_SELECTION_NOT_BASED_ON_SIL_OUTCOMES', ...
        'engineering_gain_factor',margin,'factor_provenance', ...
        'Engineering design margin: half the first ideal instability boundary, approximately 6.0206 dB nominal gain reserve.', ...
        'no_parameter_scan',true,'source_changed_policy','Reject bound-source mismatches. Recompute the gain formula when the binding is updated.', ...
        'per_axis_stability_upper_s_inverse',bounds,'common_unrounded_s_inverse',unrounded, ...
        'common_REAL32_value_s_inverse',candidateValue,'common_REAL32_bits',candidateBits, ...
        'nominal_min_gain_margin_dB',20*log10(min(bounds)/candidateValue), ...
        'algebra_negative_control_relative_gap',relativeProbe,'parameter_changes',changes);
    report.axes=axes;report.candidate_configuration=candidateCfg;
    report.coupled_candidate=coupledModel(K,J(1:2),tau,p,i,d,repmat(candidateValue,2,1));
    check('FULL_TWO_AXIS_IDEAL_MATRIX_CANDIDATE_STABLE',report.coupled_candidate.roots.asymptotically_stable);
    report.required_next_checks={ ...
        'Original 6.5 and this one candidate: same current typed native MEX, MODEL009 19-state plant, initial state and fixed small positive/negative roll and pitch perturbations.', ...
        'Keep airborne rate I enabled; landed/maybe-landed integral hold is tested as a separate branch.', ...
        'Record actual torque, rates, integral, attitude envelope, contact, all limiter/allocator activity and timestamps; retain full failed trajectories.', ...
        'Validate the actual sampled/held implementation and identifiable sensor/filter timing. Do not equate forwarded telemetry frequency with control-loop frequency.', ...
        'If the candidate fails, diagnose the omitted dynamics before revising the design.', ...
        'Validate the complete position, velocity and attitude chain together with takeoff, landing, contact and failsafe behavior.'};
    report.limitations={ ...
        'Continuous unsaturated small-signal analysis.', ...
        'The current lower-loop parameter set is typed, but IMU/EKF filter states, source sampling, work-queue timing, delay and Commander/land detection are not reconstructed.', ...
        'The 6 dB ideal gain reserve, phase margin and bandwidth are separate diagnostic quantities.', ...
        'Lower attitude P may worsen tilt tracking, position error, velocity-integrator accumulation, thrust demand and takeoff/landing transients; evaluate the full position loop.', ...
        'Corrected geometry is a bound HOST configuration.', ...
        'The analysis uses the bound rate PID, physical model, reference and screening parameters.', ...
        'The ideal instability model provides one contribution to the observed roll response.', ...
        'Allocation normalization uses MATLAB double arithmetic and the bound source formulas.', ...
        'Initial motor commands are explicit HOST initial conditions.'};
    report.passed=all([report.checks.passed]);
catch problem
    report.failure=getReport(problem,'extended','hyperlinks','off');
end
report.case_count=numel(report.checks);report.cases_passed=nnz([report.checks.passed]);
report.passed=report.passed&&isempty(report.failure);
% Retain numeric types and model inputs in MAT.
% Encode complex roots as real and imaginary columns in JSON.
save(fullfile(newOutputDir,'CANDIDATE.mat'),'report','parameters','environment', ...
    'originalCfg','candidateCfg','-v7');
fid=fopen(fullfile(newOutputDir,'CANDIDATE.json'),'w','n','UTF-8');
assert(fid>=0,'gpenmpc:CandidateOutputWrite','Cannot write candidate JSON.');
fileCleanup=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s',jsonencode(report,PrettyPrint=true));
fprintf('HOST attitude candidate: passed=%d, checks=%d/%d; board/COM/parameter writes=0\n', ...
    report.passed,report.cases_passed,report.case_count);
assert(report.passed,'gpenmpc:CandidatePreparationFailed','See preserved CANDIDATE.json.');
    function appendBinding(id)
        if isempty(report.input_bindings),report.input_bindings=id;else,report.input_bindings(end+1)=id;end
    end
    function check(name,ok)
        require(islogical(ok)&&isscalar(ok),'Non-scalar/nonlogical check result.');
        report.checks(end+1)=struct('name',name,'passed',ok);
        require(ok,['Algebra validation failed: ' name]);
    end
end

function ax=axisDerivation(name,g,tau,p,i,d,originalA,gap)
A=1+g*d;H=A*p^2-2*tau*p*i-A^2*i/g;C=A*p*i-tau*i^2;
require(C>0,'Rate-only I-enabled stability prerequisite C>0 failed.');
first=A/tau-i/p;second=(H+sqrt(H^2+4*tau*p^2*C))/(2*tau*p^2);
require(isfinite(first)&&isfinite(second)&&first>0&&second>0,'No positive strict Routh bound.');
critical=min(first,second);
% The second determinant is the limiting one for this bound current source.
require(second<first,'Different limiting Routh branch requires an explicit revised derivation.');
omega=sqrt(g*(p*critical+i)/A);coeff=characteristic(critical,g,tau,p,i,d);
relativeResidual=abs(polyval(coeff,1i*omega))/max(1,sum(abs(coeff).*omega.^(4:-1:0)));
ax=struct('axis',name,'g_s_inverse2',g,'tau_s',tau,'rate_P_effective',p, ...
    'rate_I_effective',i,'rate_D_effective',d,'A',A,'H',H,'C',C, ...
    'first_routh_upper_s_inverse',first,'second_routh_upper_s_inverse',second, ...
    'critical_gain_s_inverse',critical,'critical_angular_frequency_rad_s',omega, ...
    'critical_polynomial_relative_residual',relativeResidual, ...
    'rate_only_coefficients',[tau,A,g*p,g*i], ...
    'rate_only_roots',poleReport(roots([tau,A,g*p,g*i])), ...
    'original',caseAt(originalA,g,tau,p,i,d), ...
    'at_critical',caseAt(critical,g,tau,p,i,d), ...
    'below_critical',caseAt((1-gap)*critical,g,tau,p,i,d), ...
    'above_critical',caseAt((1+gap)*critical,g,tau,p,i,d));
end
function r=caseAt(a,g,tau,p,i,d)
c=characteristic(a,g,tau,p,i,d);
delta2=c(2)*c(3)-c(1)*c(4);
delta3=c(2)*c(3)*c(4)-c(1)*c(4)^2-c(2)^2*c(5);
b1=delta2/c(2);first=[c(1);c(2);b1;NaN;c(5)];
if b1~=0,first(4)=delta3/(c(2)*b1);end
r=struct('attitude_P_s_inverse',a,'coefficients',c,'routh_delta2',delta2, ...
    'routh_delta3',delta3,'routh_first_column',first,'routh_stable', ...
    all(c>0)&&delta2>0&&delta3>0,'roots',poleReport(roots(c)), ...
    'arithmetic_scope','Double-precision continuous-model analysis; marginal stability requires a strictly positive numerical margin.');
end
function c=characteristic(a,g,tau,p,i,d)
c=[tau,1+g*d,g*p,g*(p*a+i),g*i*a];
end
function r=frequencyReport(a,g,tau,p,i,d)
A=1+g*d;
% Solve squared-frequency polynomials and report every positive real root.
bwPoly=[tau^2,A^2-2*g*p*tau,-g^2*p^2-2*g*i*A,-g^2*i^2];
unityPoly=[tau^2,A^2-2*g*p*tau,g^2*p^2-2*g*i*A, ...
    g^2*i^2-a^2*g^2*p^2,-a^2*g^2*i^2];
bwRoots=positiveRealRoots(bwPoly);unityRoots=positiveRealRoots(unityPoly);
require(isscalar(bwRoots)&&isscalar(unityRoots),'Multiple frequency crossings need a revised interpretation.');
bw=sqrt(bwRoots);w=sqrt(unityRoots);
rate=@(frequency) g*(p*(1i*frequency)+i)./(tau*(1i*frequency).^3+A*(1i*frequency).^2+g*p*(1i*frequency)+g*i);
loop=a*rate(w)/(1i*w);
% Evaluate denominator phase explicitly for the continuous branch.
phaseMargin=pi/2+atan2(p*w,i)-atan2(g*p*w-tau*w^3,g*i-A*w^2);
r=struct('rate_minus3dB_rad_s',bw,'rate_minus3dB_Hz',bw/(2*pi), ...
    'outer_unity_rad_s',w,'outer_unity_Hz',w/(2*pi),'outer_to_inner_bandwidth_ratio',w/bw, ...
    'nominal_phase_margin_deg',phaseMargin*180/pi, ...
    'rate_minus3dB_residual',abs(abs(rate(bw))^2-0.5), ...
    'unity_gain_residual',abs(abs(loop)-1), ...
    'rate_bandwidth_polynomial_in_omega_squared',bwPoly, ...
    'outer_unity_polynomial_in_omega_squared',unityPoly, ...
    'positive_rate_bandwidth_roots_omega_squared',bwRoots, ...
    'positive_outer_unity_roots_omega_squared',unityRoots, ...
    'interpretation','Nominal small-signal diagnostics with zero filter and transport delay.');
end
function x=positiveRealRoots(coeff)
z=roots(coeff);tolerance=1e-9;
chosen=abs(imag(z))<=tolerance*max(1,abs(real(z)))&real(z)>0;
x=sort(real(z(chosen)));
require(~isempty(x)&&all(isfinite(x)),'No finite positive frequency root.');
end
function [mix,scale]=normalizedMix(A)
% Same native normalization formulas as bound small-signal source lines176+.
require(isequal(size(A),[6,6])&&all(isfinite(A),'all')&&rank(A)==4,'Invalid six-rotor effectiveness.');
mix=pinv(A);scale=ones(6,1);
nRoll=nnz(abs(mix(:,1))>1e-3);nPitch=nnz(abs(mix(:,2))>1e-3);
require(nRoll>0&&nPitch>0,'Missing roll/pitch allocator authority.');
roll=sqrt(sum(mix(:,1).^2)/(nRoll/2));pitch=sqrt(sum(mix(:,2).^2)/(nPitch/2));
scale(1:2)=max(roll,pitch);scale(3)=max(mix(:,3));
for axisIndex=6:-1:4
    count=nnz(abs(mix(:,axisIndex))>double(eps('single')));
    if count>0,scale(axisIndex)=sum(abs(mix(:,axisIndex)))/count;else,scale(axisIndex)=scale(6);end
end
require(all(scale>0)&&all(isfinite(scale)),'Degenerate native normalization.');
mix=mix./scale.';mix(abs(mix)<1e-3)=0;
end
function r=coupledModel(K,J,tau,p,i,d,a)
Ji=diag(1./J(:));P=diag(p);I=diag(i);D=diag(d);Ka=diag(a);
A=zeros(8);A(1:2,3:4)=eye(2);A(3:4,5:6)=Ji;
A(5:6,1:2)=-K*P*Ka/tau;A(5:6,3:4)=-K*P/tau;
A(5:6,5:6)=-(eye(2)+K*D*Ji)/tau;A(5:6,7:8)=K/tau;
A(7:8,1:2)=-I*Ka;A(7:8,3:4)=-I;
r=struct('state_matrix',A,'state_order','roll/pitch angle, body rate, physical moment, integral state', ...
    'integral_enabled',true,'roots',poleReport(eig(A)));
end
function r=poleReport(z)
z=z(:);[~,order]=sortrows([real(z),imag(z)],[1,2]);z=z(order);
r=struct('real_s_inverse',real(z),'imaginary_s_inverse',imag(z), ...
    'frequency_Hz',abs(imag(z))/(2*pi),'maximum_real_part_s_inverse',max(real(z)), ...
    'asymptotically_stable',all(real(z)<0));
end
function y=singleFloorPositive(x)
require(isscalar(x)&&isfinite(x)&&x>0&&x<double(realmax('single')),'Candidate outside finite REAL32 domain.');
y=single(x);
if double(y)>x,y=typecast(typecast(y,'uint32')-uint32(1),'single');end
require(isfinite(y)&&y>0&&double(y)<=x,'REAL32 downward conversion failed.');
end
function require(ok,message)
assert(isscalar(ok)&&ok,'gpenmpc:AttitudeCandidate','%s',message);
end
function r=identity(file)
file=char(file);fid=fopen(file,'rb');assert(fid>=0,'gpenmpc:CandidateMissingInput','Missing %s',file);
cleanup=onCleanup(@()fclose(fid));bytes=fread(fid,Inf,'*uint8');
md=java.security.MessageDigest.getInstance('SHA-256');md.update(bytes);
r=struct('path',file,'bytes',numel(bytes), ...
    'sha256',upper(reshape(dec2hex(typecast(md.digest(),'uint8'),2).',1,[])));clear cleanup
end
