function objects=prepare_m600_board_local_short_objects(cfg,resources,io)
% Construct session-independent objects before opening the getter, simulator or parameters.
% The optional IO argument is the instance later used by the runner.
% The outer worker starts an idle mailbox; session-bound services are created after registration.
arguments
    cfg (1,1) struct
    resources (1,1) struct
    io = []
end
assert(all(isfield(cfg,{'local_short','canonical_exchange','delivery_environment_contract'})) ...
    &&strcmp(cfg.canonical_exchange.runtime,'BOARD_LOCAL_FULL_INNER') ...
    &&all(isfield(resources,{'task_source','getter_source'})), ...
    'gpenmpcShort:PureObjectInputs','Original local configuration, task source and getter binding are required.');
c=cfg.local_short;task=resources.task_source;
assert(all(isfield(c,{'duration_s','poll_period_s','heartbeat_period_s','preparation_timeout_s', ...
    'getter_capacity','environment_ledger_capacity','raw_capacity','service_cfg'})) ...
    &&(ismember(c.duration_s,[20 40])||(ismember(c.duration_s,[0 120]) ...
       &&isfield(c,'component_initialization')&&c.component_initialization ...
       &&isfield(c.service_cfg,'operator_reference'))) ...
    &&c.poll_period_s>0&&c.heartbeat_period_s>0 ...
    &&c.poll_period_s<=c.heartbeat_period_s&&c.heartbeat_period_s<.1 ...
    &&c.preparation_timeout_s>0&&c.raw_capacity>=1&&c.raw_capacity==fix(c.raw_capacity), ...
    'gpenmpcShort:Bounds','Keep the original short-run bounds and independent full raw retention.');
assert(isscalar(c.environment_ledger_capacity)&&isfinite(c.environment_ledger_capacity) ...
    &&c.environment_ledger_capacity==fix(c.environment_ledger_capacity) ...
    &&c.environment_ledger_capacity>=4&&c.environment_ledger_capacity<=8192, ...
    'gpenmpcShort:EnvironmentLedgerCapacity','Environment association retention must use its own existing 4..8192 bound, not full raw capacity.');
assert(isa(c.service_cfg.source_max_age_ns,'uint64') ...
    &&isequal(c.service_cfg.source_max_age_ns,cfg.canonical_exchange.local_input_host_max_age_ns) ...
    &&isa(c.service_cfg.command_lifetime_ns,'uint64'), ...
    'gpenmpcShort:Lease','Original source and command limits must remain unchanged.');
source=resources.getter_source;p=string(source.exact_path);
assert(isfile(p)&&strcmpi(fileSha(p),source.sha256), ...
    'gpenmpcShort:GetterBinary','Actual original getter binary differs from its path/SHA binding.');
actual=string(which('rfly_original_getter_mex'));
assert(exist('rfly_original_getter_mex','file')==3&&strcmpi(actual,p), ...
    'gpenmpcShort:GetterShadow','Another getter binary shadows the bound implementation.');
dllSha='990850A2F40F3FCC2A6C47E63A4065B60FF49AA39CC4749FF443963B06F2EF7E';
if isfield(source,'model_sha256'),dllSha=source.model_sha256;end
getter=gpenmpcNative.RflyLocalOriginalGetterBuffer(c.getter_capacity,dllSha);
environment=gpenmpcNative.RflyLocalEnvironmentLedger( ...
    cfg.delivery_environment_contract,task.copter_id,c.environment_ledger_capacity);
taskIdentity=task;
if isfield(taskIdentity,'cached_asset'),taskIdentity=rmfield(taskIdentity,'cached_asset');end
if isfield(task,'cached_asset')
    asset=task.cached_asset;
    assert(isa(asset,'gpenmpcNative.RflyLocalTaskAsset'), ...
        'gpenmpcShort:TaskAsset','Borrow the actual original task asset.');
else
    asset=gpenmpcNative.RflyLocalTaskAsset(task);
end
asset.read(task); % Exact original path/configuration/content identity check.
if isfield(resources,'decoder_dialect')
    d=resources.decoder_dialect;
    assert(isa(d,'mavlinkdialect')&&isscalar(d), ...
        'gpenmpcShort:DecoderDialect','Pass the outer preloaded official dialect object.');
else
    build=fileparts(fileparts(mfilename('fullpath')));
    if isfield(cfg,'local_mavlink_dialect')
        d=mavlinkdialect(cfg.local_mavlink_dialect.path,2);
    else
        d=mavlinkdialect(fullfile(build,'m600_coptersim','matlab_validation','+m600check','px4_health_events.xml'),2);
    end
end
environmentService=[];
environmentConfig=struct('target_system',cfg.target_system,'target_component',cfg.target_component, ...
    'heartbeat_max_age_s',cfg.heartbeat_max_age_s,'landed_max_age_s',cfg.landed_max_age_s, ...
    'delivery_environment_contract',cfg.delivery_environment_contract);
if ~isempty(io)
    % Construct the environment service with the bound owner.
    environmentService=gpenmpcNative.RflyCanonicalEnvironmentService(io,cfg,task);
end
outer=[];
if isfield(resources,'prepared_outer')
    outer=resources.prepared_outer;
    assert(isa(outer,'gpenmpcNative.RflyLocalOuterService')&&isscalar(outer), ...
        'gpenmpcShort:PreparedOuter','Borrow only the actual preconstructed original outer owner.');
    outerState=outer.status();
    assert(outerState.preconstructed&&~outerState.session_bound&&~outerState.closed ...
        &&~outerState.failed&&outerState.worker.submitted==0, ...
        'gpenmpcShort:PreparedOuter','Preconstructed outer must still be unbound and have no solve submissions.');
elseif isfield(resources,'preconstruct_outer')
    assert(isequal(resources.preconstruct_outer,true)&&all(isfield(resources,{'assets','initial_trajectory'})), ...
        'gpenmpcShort:PreconstructOuter','Explicit original assets and trajectory are required.');
    outer=gpenmpcNative.RflyLocalOuterService(resources.assets,[],resources.initial_trajectory, ...
        c.service_cfg.source_max_age_ns,c.service_cfg.command_lifetime_ns,"PREPARE_UNBOUND");
end
if isfield(resources,'prepared_method_backends')
    methodBackends=resources.prepared_method_backends;
    assert(isstruct(methodBackends)&&isscalar(methodBackends) ...
        &&all(isfield(methodBackends,{'schema','input_codec','gp'})) ...
        &&strcmp(methodBackends.schema,'GPENMPC_PREPARED_LOCAL_METHOD_BACKENDS_V1'), ...
        'gpenmpcShort:PreparedMethodBackends','Borrow the exact pre-producer method backends only.');
else
    assert(isfield(resources,'assets')&&all(isfield(c.service_cfg,{'input_codec_backend','gp_backend'})), ...
        'gpenmpcShort:PreparedMethodBackends','Exact assets and both retained backend bindings are required.');
    methodBackends=struct('schema','GPENMPC_PREPARED_LOCAL_METHOD_BACKENDS_V1', ...
        'input_codec',gpenmpcNative.RflyLocalMethodService.prepareInputCodecBackend(c.service_cfg.input_codec_backend), ...
        'gp',gpenmpcNative.RflyLocalGpService.prepareBackend(resources.assets,c.service_cfg.gp_backend));
end
receipt=struct('schema','GPENMPC_LOCAL_SHORT_PURE_OBJECT_CONSTRUCTION_V1','passed',true, ...
    'getter_buffer_capacity',c.getter_capacity, ...
    'environment_ledger_capacity',c.environment_ledger_capacity,'full_raw_capacity',c.raw_capacity, ...
    'original_getter_mex_invocations',0,'socket_opens',0,'COM_opens',0,'plant_actions',0, ...
    'authority_granted',false,'session_dependent_construction_performed',false, ...
    'actual_io_environment_service_constructed',~isempty(environmentService), ...
    'scope','PURE_BUFFER_TASK_AND_OFFICIAL_DIALECT_CONSTRUCTION_ONLY');
receipt.outer_preconstructed=~isempty(outer);
receipt.method_backends_prepared_before_getter_producer=true;
receipt.method_backend_authority_granted=false;
receipt.method_backend_construction_calls=struct('input_codec',0, ...
    'numerical',methodBackends.gp.construction_gp_calls,'gp',methodBackends.gp.construction_gp_calls);
receipt.gp_preparation_scope='FIXED_PAIR_WORKER_REHEARSAL';
if ~isempty(outer)
    receipt.outer=outer.status();
    receipt.scope='PURE_OBJECTS_AND_ORIGINAL_IDLE_OUTER_WORKER_NO_SOLVE_OR_SESSION';
end
objects=struct('schema','GPENMPC_LOCAL_SHORT_PURE_OBJECTS_V1','local_short',c, ...
    'environment_contract',cfg.delivery_environment_contract,'task_identity',taskIdentity, ...
    'getter_source',source,'getter',getter,'environment',environment,'task_asset',asset, ...
    'dialect',d,'getter_mex',@rfly_original_getter_mex,'receipt',receipt, ...
    'environment_service',environmentService,'environment_io',io,'environment_service_config',environmentConfig, ...
    'outer',outer,'method_backends',methodBackends);
end
function h=fileSha(path)
f=fopen(path,'rb');assert(f>=0,'gpenmpcShort:GetterBinary','Cannot read the original getter binary.');
c=onCleanup(@()fclose(f));b=fread(f,Inf,'*uint8');clear c
m=java.security.MessageDigest.getInstance('SHA-256');m.update(typecast(b,'int8'));
h=upper(reshape(dec2hex(typecast(m.digest(),'uint8'),2).',1,[]));
end
