function report=probe_manual_ground_contact(outputDir)
% PROBE_MANUAL_GROUND_CONTACT Run three offline contact scenarios.
% Use the 19-state derivative and 10 ms RK4 step.
% These are constructed cases, not a reconstruction of an observed impact.
arguments
    outputDir (1,1) string
end
assert(strlength(outputDir)>0 &&~isfolder(outputDir)&&~isfile(outputDir), ...
    'manualContact:OutputExists','Use a new isolated output directory.');
build=string(fileparts(fileparts(mfilename('fullpath'))));
oldPath=path;cleanup=onCleanup(@()path(oldPath)); %#ok<NASGU>
addpath(fullfile(build,'matlab_validation'),fullfile(build,'m600_coptersim','matlab_validation'));
fixture=m600check.loadFixture(); % Checks the existing oracle source identities.
parameterPath=fullfile(build,'m600_coptersim','model', ...
    'generated','M600_CORE_PARAMETERS.mat');
assert(strcmpi(m600check.fileSha256(parameterPath), ...
    'D65290884733F07C19C54553BF8D83C703EB88AF5D0AAF110DE56C76FA767AA0'), ...
    'manualContact:ParametersChanged','M600 model parameter checksum mismatch.');
loaded=load(parameterPath,'parameters');p=loaded.parameters;
payload=2.21;g=9.80665;dt=.01;duration=1.0;
mass=p.profile.mass_properties.base_mass_kg+payload+p.mission.plant_mismatch.mass_bias_kg;
assert(abs(mass-11.71)<1e-12 &&p.contact.static_deflection_m==.035 ...
    &&p.contact.maximum_deflection_m==.060 &&p.contact.damping_ratio==.9, ...
    'manualContact:Identity','Current mass/contact identity differs.');
if isfield(p.contact,'surface_height_up_m')
    assert(p.contact.surface_height_up_m==0,'manualContact:Datum','Expected flat local ground at zero.');
end
assert(~p.mission.structured_residual.enabled, ...
    'manualContact:Residual','This isolated diagnostic requires the original neutral model parameters.');
upper=p.calibration.rotor_allocation.per_rotor_thrust_upper_n;
hover=mass*g/(6*upper);
assert(hover>0&&hover<1);
sourceNames=["m600check.loadFixture";"m600check.stepPx4Rk4"; ...
    "m600check.derivativeSoftware";"m600check.contactKernel"; ...
    "m600check.initialStepMemory";"m600check.passiveGroundDissipation"; ...
    "gpenmpcM600SixDofPlantDerivative";"gpenmpcM600Allocation"; ...
    "gpenmpcM600StructuredResidual";"gpenmpcQuaternionRotation"; ...
    "gpenmpcQuaternionDerivativeMatrix";"gpenmpcReferenceExtrapolation"];
sources=struct('path',{},'bytes',{},'sha256',{});
for k=1:numel(sourceNames)
    source=string(which(sourceNames(k)));
    assert(strlength(source)>0,'manualContact:Dependency','Missing dependency %s.',sourceNames(k));
    sources(end+1)=identity(source); %#ok<AGROW>
end
sources(end+1)=identity(string(mfilename('fullpath'))+".m");
specs=struct('name',{'HOVER_COMMAND_STEADY_THRUST','HALF_COMMAND_STEADY_THRUST', ...
    'HALF_COMMAND_FROM_HOVER_THRUST'}, ...
    'command_normalized',{hover,.5,.5},'initial_thrust_normalized',{hover,.5,hover});
common=struct('classification','CONTACT_COUNTERFACTUAL', ...
    'state_order','z-up position3, velocity3, quaternion_wxyz4, body_rate3, rotor_thrust_N6', ...
    'position_up_m',[0;0;p.contact.static_deflection_m], ...
    'velocity_up_mps',[0;0;-1.5],'quaternion_wxyz',[1;0;0;0], ...
    'angular_rate_radps',zeros(3,1),'payload_kg',payload,'mass_kg',mass, ...
    'wind_xy_mps',zeros(2,1),'surface_height_up_m',0, ...
    'dt_s',dt,'duration_s',duration,'maximum_steps',round(duration/dt), ...
    'horizon_role','One-second diagnostic observation horizon.', ...
    'contact_onset','z_up equals static_deflection; initial contact compression is zero', ...
    'reference','Constant downward 1.5 m/s jet, analytically extrapolated; no controller is run', ...
    'thrust_initialization','Each named case explicitly sets all six actuator states; third case excites the original thrust lag', ...
    'actuator_time_constant_s',p.calibration.rotor_allocation.actuator_time_constant_nominal_s, ...
    'fixed_inertia_kg_m2',p.calibration.mass_inertia.inertia_nominal_kg_m2, ...
    'px4_to_software_rotor_permutation',[5;1;4;6;2;3], ...
    'limitations',{{'Commanded vertical velocity and measured impact velocity are distinct quantities.', ...
    'Flat ground, level attitude and chosen actuator states are explicit synthetic initial conditions.', ...
    'No SE(3) controller, operator reference integration, estimator, terrain changes or live timing is replayed.', ...
    'Contact coefficients are the existing engineering proxy, not measured M600 landing-gear travel.', ...
    'Numerical ground-contact response.'}});
mkdir(outputDir);
writeJson(fullfile(outputDir,'PROSPECTIVE.json'),struct('common',common,'cases',specs, ...
    'parameter_identity',identity(parameterPath),'original_parameters',p, ...
    'sources',sources,'source_manifest_sha256',fixture.source_manifest_sha256, ...
    'hardware_actions',0,'COM_UDP_actions',0,'DLL_builds',0,'production_edits',0));
outcomes=struct([]);
for ci=1:numel(specs)
    a=runCase(specs(ci),common,p,upper);
    if isempty(outcomes),outcomes=a;else,outcomes(end+1)=a;end %#ok<AGROW>
end
report=struct('classification','HOST_CONTACT_COUNTERFACTUAL_COMPLETED', ...
    'executed_case_count',numel(outcomes),'common',common,'parameter_identity',identity(parameterPath), ...
    'original_parameters',p,'source_manifest_sha256',fixture.source_manifest_sha256, ...
    'sources',sources,'contact_stiffness_N_per_m',mass*g/p.contact.static_deflection_m, ...
    'contact_damping_Ns_per_m',2*p.contact.damping_ratio*sqrt(mass*g/p.contact.static_deflection_m*mass), ...
    'code3_interpretation','Integrated candidate deflection > maximum_deflection + 1e-12; rejected endpoint is not committed', ...
    'cases',outcomes,'hardware_actions',0,'COM_UDP_actions',0,'simulator_runs',0, ...
    'DLL_builds',0,'controller_runs',0,'production_edits',0);
writeJson(fullfile(outputDir,'RESULT.json'),report);
disp(jsonencode(struct('classification',report.classification, ...
    'cases',outcomes,'hardware_actions',0)));
end

function result=runCase(spec,common,p,upper)
x=zeros(19,1);x(1:3)=common.position_up_m;x(4:6)=common.velocity_up_mps;
x(7)=1;x(14:19)=spec.initial_thrust_normalized*upper;
initial=x;controls=zeros(16,1);controls(1:6)=spec.command_normalized;
memory=m600check.initialStepMemory();memory.ground_support_dwell_s=0;
memory.ground_confirmed=false;memory.airborne_observed=true;
memory.previous_contact_active=false;
t=0;accepted=0;maxAccepted=0;maxCandidate=0;maxForce=0;
firstFailure=struct('occurred',false,'code',0,'candidate_time_s',[], ...
    'last_accepted_time_s',[],'candidate_state_up',[],'candidate_deflection_m',[], ...
    'candidate_overtravel_m',[],'candidate_contact_force_N',[]);
for index=1:common.maximum_steps
    jet=zeros(12,1);jet(1:3)=common.position_up_m+common.velocity_up_mps*t;
    jet(4:6)=common.velocity_up_mps;
    [candidate,~,contact,mn,status]=m600check.stepPx4Rk4(x,controls,jet, ...
        common.payload_kg,common.wind_xy_mps,t,p,memory);
    maxCandidate=max(maxCandidate,contact.contact_deflection_m);
    maxForce=max(maxForce,contact.contact_force_n);
    if ~status.accepted
        firstFailure=struct('occurred',true,'code',double(status.failure_code), ...
            'candidate_time_s',t+common.dt_s,'last_accepted_time_s',t, ...
            'candidate_state_up',status.candidate_state, ...
            'candidate_deflection_m',contact.contact_deflection_m, ...
            'candidate_overtravel_m',contact.contact_overtravel_m, ...
            'candidate_contact_force_N',contact.contact_force_n);
        break
    end
    x=candidate;memory=mn;t=status.next_time_s;accepted=accepted+1;
    maxAccepted=max(maxAccepted,contact.contact_deflection_m);
end
result=struct('name',spec.name,'normalized_command',spec.command_normalized, ...
    'initial_normalized_thrust_state',spec.initial_thrust_normalized, ...
    'initial_state_up',initial,'command_controls16',controls,'accepted_steps',accepted, ...
    'accepted_duration_s',t,'full_diagnostic_horizon_completed',accepted==common.maximum_steps, ...
    'max_accepted_deflection_m',maxAccepted,'max_evaluated_endpoint_deflection_m',maxCandidate, ...
    'max_evaluated_endpoint_contact_force_N',maxForce,'first_failure',firstFailure, ...
    'first_code3_time_s',[],'last_accepted_state_up',x, ...
    'final_ground_confirmed',memory.ground_confirmed, ...
    'claim','Synthetic contact calculation with the full plant.');
if firstFailure.occurred&&firstFailure.code==3,result.first_code3_time_s=firstFailure.candidate_time_s;end
end

function a=identity(file)
d=dir(file);assert(isscalar(d)&&~d.isdir,'manualContact:SourceMissing','Missing source %s.',file);
a=struct('path',string(file),'bytes',d.bytes,'sha256',m600check.fileSha256(file));
end

function writeJson(file,value)
assert(~isfile(file),'manualContact:Overwrite','Refusing to overwrite evidence.');
text=jsonencode(value,'PrettyPrint',true,'ConvertInfAndNaN',false);
fid=fopen(file,'w','n','UTF-8');assert(fid>=0,'manualContact:Output','Cannot open new output.');
closer=onCleanup(@()fclose(fid)); %#ok<NASGU>
written=fprintf(fid,'%s\n',text);assert(written>=numel(text),'manualContact:ShortWrite','Short JSON write.');
end
