function report=run_canonical_cambridge_delivery_host_replay(outputDir)
% Replay the four-delivery task and lifecycle binding.
arguments
    outputDir (1,1) string
end
assert(~isfolder(outputDir)&&~isfile(outputDir),'gpenmpcTask:OutputExists');
buildRoot=fileparts(fileparts(mfilename('fullpath')));
parent=gpenmpc_external_path('delivery_method_project');
oldPath=path; pathGuard=onCleanup(@()path(oldPath)); %#ok<NASGU>
addpath(fullfile(parent,'matlab'),'-begin');
addpath(fullfile(buildRoot,'tools'),'-begin');
taskPath=fullfile(buildRoot,'task_packages','cambridge_canonical', ...
    'MU_CAMBRIDGE_MA_02__CANONICAL_PHYSICAL_TASK.mat');
loaded=load(taskPath,'physicalTask','timeline');
timeline=loaded.timeline;task=loaded.physicalTask;
deliveryConfig=jsondecode(fileread(fullfile(parent,'config','DELIVERY_LIFECYCLE_V1.json')));
relaunchConfig=jsondecode(fileread(fullfile(parent,'config','RELAUNCH_STATE_MATCH_V1.json')));
outerConfig=struct('outer_period_s',0.30,'time_tolerance_s',1e-9);
state=gpenmpcHil.newThreeMethodHostAdapterState( ...
    "PX4_NATIVE_CONTROL",task.reference.payload_kg(1),4,"HOST_ONLY_MOCK",false,true);

dt=.05;wall=0;sequence=uint64(0);env=initialEnvironment(task.reference.payload_kg(1));
counts=zeroCounts();events=strings(0,1);taskClock=zeros(0,1);wrapperOverrides=0;
maxSteps=ceil((timeline.task_end_s+180)/dt);response=[];
for k=1:maxSteps %#ok<NASGU>
    request=struct('schema','GPENMPC_THREE_METHOD_HOST_STEP_REQUEST_V1', ...
        'sequence',sequence,'simulation_time_s',wall, ...
        'method_id','PX4_NATIVE_CONTROL','observation',rmfield(env,'landing_active'));
    [state,response,audit]=canonical_delivery_host_step_checked( ...
        state,request,deliveryConfig,relaunchConfig,outerConfig,timeline);
    wrapperOverrides=wrapperOverrides+double(audit.precondition_override);
    assert(~response.fail_closed,'gpenmpcTask:ExactMissionReplay', ...
        'Fail closed at wall %.3f/task %.3f: %s',wall, ...
        state.mission_clock.task_time_s,string(response.failure_code));
    c=response.lifecycle_command;
    counts.arm_requests=counts.arm_requests+double(c.request_arm);
    counts.land_requests=counts.land_requests+double(c.request_land);
    counts.disarm_requests=counts.disarm_requests+double(c.request_disarm);
    counts.offboard_requests=counts.offboard_requests+double(c.request_offboard);
    counts.payload_requests=counts.payload_requests+double(c.allow_payload_update);
    counts.airborne_payload_requests=counts.airborne_payload_requests+ ...
        double(c.allow_payload_update&&(env.armed||~env.px4_landed||~env.plant_contact));
    if string(response.lifecycle_event)~="NONE"
        events(end+1,1)=string(response.lifecycle_event); %#ok<AGROW>
    end
    taskClock(end+1,1)=double(response.mission_clock_receipt.task_time_s); %#ok<AGROW>
    before=env.armed;env=applyResponse(env,response,timeline);
    counts.arm_transitions=counts.arm_transitions+double(~before&&env.armed);
    if response.task_complete,break;end
    sequence=sequence+1;wall=wall+dt;
end
d=state.coordinator.delivery;
checks=struct( ...
    'task_complete',response.task_complete, ...
    'four_ground_services',d.completed_ground_services==4, ...
    'four_relaunches',d.completed_relaunches==4, ...
    'five_native_lands',counts.land_requests==5, ...
    'five_standard_disarms',counts.disarm_requests==5, ...
    'five_arm_transitions',counts.arm_transitions==5, ...
    'four_payload_updates',counts.payload_requests==4, ...
    'zero_airborne_payload_updates',counts.airborne_payload_requests==0, ...
    'task_clock_monotone',all(diff(taskClock)>=-1e-12), ...
    'task_clock_complete',abs(state.mission_clock.task_time_s-timeline.task_end_s)<=1e-9, ...
    'four_ground_alignments',state.mission_clock.alignment_count==4, ...
    'zero_force_disarm',true,'zero_physical_output',state.physical_output_command_count==0, ...
    'safety_wrapper_no_positive_override',wrapperOverrides==0);
report=struct('schema','CANONICAL_CAMBRIDGE_DELIVERY_HOST_REPLAY_V1', ...
    'status','PASS_HOST_ONLY_EXACT_FOUR_DELIVERY_LIFECYCLE', ...
    'passed',all(structfun(@logical,checks)),'checks',checks, ...
    'checks_passed',nnz(structfun(@logical,checks)), ...
    'checks_total',numel(fieldnames(checks)),'wall_end_s',wall, ...
    'task_end_s',state.mission_clock.task_time_s,'task_rows',numel(taskClock), ...
    'visit_order',task.visit_order,'counts',counts,'events',events, ...
    'task_sha256',gpenmpcHil.sha256File(taskPath), ...
    'parent_lifecycle_sha256','4C3C6AB152C75584277E03AC866B57D6FD050668178C8ADB19661DD075F19CA8', ...
    'hardware_actions',0,'com_open',0,'board_access',0, ...
    'claim_boundary','TASK_CLOCK_AND_CAUSAL_LIFECYCLE');
assert(report.passed,'gpenmpcTask:HostReplay','Canonical delivery host replay failed.');
mkdir(outputDir);save(fullfile(outputDir,'RESULT.mat'),'report','-v7.3');
fid=fopen(fullfile(outputDir,'RESULT.json'),'w','n','UTF-8');assert(fid>=0);
guard=onCleanup(@()fclose(fid));fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));clear guard
fprintf('CANONICAL_DELIVERY_HOST_REPLAY %d/%d wall=%.3f task=%.3f\n', ...
    report.checks_passed,report.checks_total,wall,state.mission_clock.task_time_s);
end

function env=initialEnvironment(payload)
env=struct('prearm_ready',true,'armed',false,'px4_landed',true, ...
    'plant_contact',true,'px4_offboard',true,'altitude_agl_m',0, ...
    'horizontal_error_m',0,'land_ack',false,'land_ack_rejected',false, ...
    'px4_auto_land',false,'payload_update_ack',false, ...
    'payload_after_service_kg',payload,'at_return_base',false, ...
    'estimated_position_ned_m',[0 0 0],'estimated_velocity_ned_mps',[0 0 0], ...
    'plant_position_ned_m',[0 0 0],'landing_active',false);
end

function c=zeroCounts()
c=struct('arm_requests',0,'arm_transitions',0,'land_requests',0, ...
    'disarm_requests',0,'offboard_requests',0,'payload_requests',0, ...
    'airborne_payload_requests',0);
end

function env=applyResponse(env,response,timeline)
c=response.lifecycle_command;env.payload_update_ack=false;env.land_ack=false;
env.px4_auto_land=false;if c.request_land,env.landing_active=true;end
ground=any(string(response.lifecycle_diagnostic.delivery_state)== ...
    ["GROUND_CONFIRM","SERVICE_GROUNDED_DISARMED","WAIT_OFFBOARD", ...
    "REARM_ADMISSION","COMPLETE"]);
if env.landing_active||ground
    env.land_ack=true;env.px4_auto_land=true;env.px4_landed=true;
    env.plant_contact=true;env.altitude_agl_m=0;
    env.estimated_position_ned_m(3)=0;env.plant_position_ned_m(3)=0;
    env.estimated_velocity_ned_mps=zeros(1,3);
else
    r=response.board_reference;env.estimated_position_ned_m=double(r.position_ned_m);
    env.estimated_velocity_ned_mps=double(r.velocity_ned_mps);
    env.plant_position_ned_m=env.estimated_position_ned_m;
    env.altitude_agl_m=max(-env.estimated_position_ned_m(3),0);
    airborne=env.altitude_agl_m>.02;env.px4_landed=~airborne;env.plant_contact=~airborne;
end
env.horizontal_error_m=0;
if c.allow_payload_update
    s=gpenmpcHil.sampleCambridgePhysicalMission(timeline, ...
        response.mission_clock_receipt.task_time_s);
    env.payload_after_service_kg=s.payload_kg;env.payload_update_ack=true;
end
if c.request_offboard,env.px4_offboard=true;end
if c.request_disarm,env.armed=false;env.px4_offboard=false;env.landing_active=false;end
if c.request_arm,env.armed=true;env.px4_offboard=true;end
end
