function receipt=run_readonly_board_identity(outputPath)
% RUN_READONLY_BOARD_IDENTITY Read Pixhawk identity over COM3.
if nargin<1
    outputPath=fullfile(fileparts(fileparts(mfilename('fullpath'))), ...
        'evidence','CURRENT_BOARD_READONLY_IDENTITY.json');
end
root=fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(root,'host_runtime'),'-begin');
rehash path;
link=gpenmpcNative.MavlinkSerialLink;
cleanup=onCleanup(@()link.close()); %#ok<NASGU>
heartbeat=link.open("COM3",921600,15);
identity=link.collectIdentity(10);
version=identity.autopilot_version;
extended=identity.extended_sys_state;
pwmStatus=link.shellCommand("pwm_out status",3.0);
se3Status=link.shellCommand("gpenmpc_se3_control status",3.0);
receipt=struct( ...
    'schema','GPENMPC_CURRENT_BOARD_READONLY_IDENTITY_V1', ...
    'status','READ_ONLY_IDENTITY_OBSERVED', ...
    'uid',sprintf('%u',version.uid), ...
    'board_version',double(version.board_version), ...
    'vendor_id',double(version.vendor_id), ...
    'product_id',double(version.product_id), ...
    'commit',identity.parsed_commit, ...
    'hw_arch',identity.parsed_hw_arch, ...
    'armed',bitand(uint8(heartbeat.Payload.base_mode),uint8(128))~=0, ...
    'mode',gpenmpcNative.MavlinkSerialLink.modeName( ...
        heartbeat.Payload.custom_mode), ...
    'landed_state',double(extended.landed_state), ...
    'pwm_out_status',pwmStatus, ...
    'gpenmpc_se3_control_status',se3Status, ...
    'gpenmpc_se3_control_command_available', ...
        ~contains(lower(se3Status),'command not found'), ...
    'endpoint','COM3','baud',921600, ...
    'link_counters',link.counters(), ...
    'parameter_writes',0,'mapping_writes',0,'mode_requests',0, ...
    'arm_requests',0,'reboots',0,'flashes',0,'physical_outputs',0);
link.close();
folder=fileparts(outputPath);if ~isfolder(folder),mkdir(folder);end
temporary=outputPath+".tmp";
fid=fopen(temporary,'w','n','UTF-8');
assert(fid>=0,'gpenmpcNative:IdentityReceiptOpen','Cannot open identity receipt.');
fileCleanup=onCleanup(@()fclose(fid));
fprintf(fid,'%s\n',jsonencode(receipt,PrettyPrint=true));
clear fileCleanup
movefile(temporary,outputPath,'f');
disp(jsonencode(receipt,PrettyPrint=true));
end
