function report=run_m600_delivery_runner_host_tests(outputDir,scope)
% Test the delivery runner with injected in-memory IO.
arguments
    outputDir (1,1) string
    scope (1,1) string {mustBeMember(scope,["ALL","FINALIZER_ONLY"])} = "ALL"
end
assert(~isfolder(outputDir)&&~isfile(outputDir),'m600delivery:HostOutputExists');
root=fileparts(fileparts(mfilename('fullpath')));addpath(fullfile(root,'tools'), ...
    fullfile(root,'matlab_validation'),fullfile(root,'m600_coptersim','matlab_validation'));
cfg=make_m600_canonical_delivery_config(struct('identity','MEMORY_FIXTURE'),'MEMORY_FIXTURE');
parentPlan=jsondecode(fileread(fullfile(gpenmpc_external_path('native_tuned_hover_preparation'),'PLAN.json')));
cfg.temporary_allocator_geometry=parentPlan.temporary_allocator_geometry;
cfg.native_hover_tuning=make_m600_delivery_native_tuning_contract();
cfg.live_enabled=false;cfg.outer_preflight_pass=false;cfg.write_artifacts=false;
cfg.prestream_s=.1;cfg.preflight_deadline_s=.5;cfg.command_timeout_s=.2;
cfg.mode_timeout_s=.2;cfg.land_timeout_s=.5;cfg.disarm_timeout_s=.2;
cfg.poll_period_s=.02;cfg.heartbeat_period_s=.1;cfg.delivery_mission.mission_timeout_s=900;
result=[];ev=[];checks=struct();
if scope=="ALL"
    io=fixture(cfg);result=run_m600_matlab_delivery_hil('',cfg,io);ev=io.evidence();
    checks=struct( ...
    'task_completed',result.task_completed, ...
    'four_ground_services',result.delivery_state.completed_ground_services==4, ...
    'four_relaunches',result.delivery_state.completed_relaunches==4, ...
    'five_arm_transitions',result.counts.arm_transitions==5, ...
    'five_land_requests',result.counts.land_requests==5, ...
    'five_standard_disarms',result.counts.standard_disarm_requests==5, ...
    'four_payload_requests',result.counts.payload_update_requests==4, ...
    'four_payload_acks',result.counts.payload_update_acks==4, ...
    'six_mapping_apply_and_rollback',result.counts.mapping_apply_verified==6&& ...
        result.counts.mapping_rollback_verified==6, ...
    'geometry12_apply_restore',result.allocator_geometry_apply.passed&& ...
        result.allocator_geometry_restore.passed&&result.allocator_geometry_restored, ...
    'tuning3_apply_restore',result.native_hover_tuning_apply.passed&& ...
        result.native_hover_tuning_restore.passed&&result.native_hover_tuning_restored, ...
    'typed138_union_restored',result.native_original138_restored&& ...
        result.native_parameter_union_original.passed&& ...
        result.native_parameter_union_applied.passed&& ...
        result.native_parameter_union_restored.passed, ...
    'environment_begin_after_disarmed_setup',ev.environment_began_after_all_setup&& ...
        ev.first_environment_operation_index>ev.last_setup_apply_operation_index, ...
    'environment_board_time_monotonic_under_mapping_jitter', ...
        ev.environment_board_time_monotonic&& ...
        result.counts.environment_board_time_clamps>0&& ...
        result.counts.environment_board_time_max_raw_regression_s>0, ...
    'blocking_command_waits_pause_mission_clock', ...
        result.counts.paused_command_waits>=9&& ...
        result.counts.paused_command_clock_hold_updates>0&& ...
        result.counts.paused_command_max_wait_s>.1, ...
    'all_payload_releases_ground_disarmed',ev.payload_release_count==4&& ...
        ev.airborne_payload_release_count==0&&ev.minimum_ground_dwell_before_release_s>=8, ...
    'no_force_or_physical_output',result.counts.force_disarm_requests==0&& ...
        result.physical_output_actions==0, ...
    'safe_final',result.fresh_final_safe_state&&result.matlab_sockets_closed&& ...
        ev.closed&&ev.final_armed==0&&ev.final_landed_state==1&&ev.all_mappings_zero);
end
finalizerCases=struct('phase',{},'checks',{},'passed',{},'checks_passed',{}, ...
    'checks_total',{},'first_failure',{},'counts',{},'events',{}, ...
    'finalizer_mission_clock_unchanged',{},'safe_final',{});
for phaseCode=[1,2]
    % Actual lifecycle names are INITIAL_TAKEOFF and TRANSIT (tracking).
    % One recoverable host observation error occurs after arm in each phase;
    % subsequent board/model observations remain fresh, and ACKs retain the
    % existing 160 ms delay.  The original failure must remain a task failure.
    negativeIo=fixture(cfg,phaseCode);
    negative=run_m600_matlab_delivery_hil('',cfg,negativeIo);
    negativeEvidence=negativeIo.evidence();
    kinds=string({negative.events.kind});
    exceptionIndex=find(kinds=="EXCEPTION",1);
    afterFailure=negative.events(exceptionIndex:end);
    expectedPhase="INITIAL_TAKEOFF";if phaseCode==2,expectedPhase="TRANSIT";end
    negativeChecks=struct( ...
        'one_failure_in_requested_active_phase',negativeEvidence.injected_failures==1&& ...
            string(negative.first_failure.phase)==expectedPhase, ...
        'original_failure_preserved',strcmp(negative.first_failure.identifier, ...
            'm600delivery:NativeTelemetry')&&~negative.task_completed&&~negative.formal_completed, ...
        'land_request_and_delayed_ack_observed',sum(kinds=="FINALIZER_AUTO_LAND_REQUEST")==1&& ...
            sum(kinds=="FINALIZER_AUTO_LAND_ACK")==1&& ...
            negative.counts.safety_only_command_observations>2, ...
        'standard_disarm_request_and_ack_observed', ...
            sum(kinds=="FINALIZER_STANDARD_DISARM_REQUEST")==1&& ...
            sum(kinds=="FINALIZER_STANDARD_DISARM_ACK")==1, ...
        'no_secondary_termination_exception',~any(kinds=="FINALIZER_TERMINATION_ERROR"), ...
        'task_clock_and_failed_phase_preserved',negative.safety_finalizer_mission_clock_unchanged&& ...
            all([afterFailure.task_time_s]==afterFailure(1).task_time_s)&& ...
            string(negative.delivery_state.name)==expectedPhase, ...
        'mapping6_restored',negative.counts.mapping_apply_verified==6&& ...
            negative.counts.mapping_rollback_verified==6&&negativeEvidence.all_mappings_zero, ...
        'geometry12_tuning3_restored',negative.allocator_geometry_restored&& ...
            negative.native_hover_tuning_restored, ...
        'typed138_union_restored',negative.native_original138_restored, ...
        'safe_closed_no_force_no_payload_release',negative.fresh_final_safe_state&& ...
            negative.matlab_sockets_closed&&negativeEvidence.closed&& ...
            negativeEvidence.final_armed==0&&negativeEvidence.final_landed_state==1&& ...
            negative.counts.force_disarm_requests==0&&negative.counts.payload_update_requests==0&& ...
            negative.physical_output_actions==0, ...
        'host_only',negativeEvidence.hardware_actions==0&&negativeEvidence.com_open==0);
    names=fieldnames(negativeChecks);
    prefix=lower(char(expectedPhase));
    for n=1:numel(names)
        checks.([prefix '_' names{n}])=negativeChecks.(names{n});
    end
    finalizerCases(end+1)=struct('phase',char(expectedPhase), ...
        'checks',negativeChecks,'passed',all(structfun(@logical,negativeChecks)), ...
        'checks_passed',nnz(structfun(@logical,negativeChecks)), ...
        'checks_total',numel(names),'first_failure',negative.first_failure, ...
        'counts',negative.counts,'events',negative.events, ...
        'finalizer_mission_clock_unchanged',negative.safety_finalizer_mission_clock_unchanged, ...
        'safe_final',negative.fresh_final_safe_state); %#ok<AGROW>
end
report=struct('schema','HOST_ACTUAL_MATLAB_DELIVERY_RUNNER_INJECTED_IO_V1', ...
    'status','PASS_HOST_ONLY_ACTUAL_DELIVERY_RUNNER', ...
    'scope',char(scope),'normal_complete_run_executed',scope=="ALL", ...
    'passed',all(structfun(@logical,checks)),'checks',checks, ...
    'checks_passed',nnz(structfun(@logical,checks)), ...
    'checks_total',numel(fieldnames(checks)),'runner_result',result, ...
    'fixture_evidence',ev,'finalizer_regression',finalizerCases, ...
    'hardware_actions',0,'com_open',0,'udp_open',0, ...
    'claim_boundary','RUNNER_STATE_MACHINE_WITH_SYNTHETIC_DYNAMICS');
% Retain compact test results and assertions.
compact=report;
if scope=="ALL"
    compact.runner_result.three_stream_log=[];
    compact.runner_result.transport_evidence=[];
    compact.fixture_evidence.operation_log=compact.fixture_evidence.operation_log( ...
        1:min(64,numel(compact.fixture_evidence.operation_log)));
end
report=compact;
mkdir(outputDir);save(fullfile(outputDir,'RESULT.mat'),'report','-v7.3');
fid=fopen(fullfile(outputDir,'RESULT.json'),'w','n','UTF-8');assert(fid>=0);
guard=onCleanup(@()fclose(fid));fprintf(fid,'%s\n',jsonencode(compact,PrettyPrint=true));clear guard
fprintf('ACTUAL_DELIVERY_RUNNER_HOST %s %d/%d\n', ...
    scope,report.checks_passed,report.checks_total);
assert(report.passed,'m600delivery:HostRunnerTests','Actual delivery runner host test failed.');
end

function io=fixture(cfg,failurePhase)
if nargin<2,failurePhase=0;end
t=0;armed=0;landed=1;main=0;sub=0;position=zeros(1,3);velocity=zeros(1,3);
ack=[];closed=false;groundSince=0;continuity=1;previousGround=true;
params=containers.Map('KeyType','char','ValueType','any');
params('SYS_HITL')=typed('SYS_HITL',1);params('SYS_AUTOSTART')=typed('SYS_AUTOSTART',6001);
params('MAV_TYPE')=typed('MAV_TYPE',13);params('CA_ROTOR_COUNT')=typed('CA_ROTOR_COUNT',6);
params('RA_CTRL_MODE')=typed('RA_CTRL_MODE',0);
for k=1:16,params(sprintf('HIL_ACT_FUNC%d',k))=typed(sprintf('HIL_ACT_FUNC%d',k),0);end
for k=1:8,params(sprintf('PWM_MAIN_FUNC%d',k))=typed(sprintf('PWM_MAIN_FUNC%d',k),0);end
environment=[];payload=cfg.delivery_environment_contract.initial_payload_kg;
payloadGen=0;releaseCount=0;airborneRelease=0;minimumDwell=Inf;
commands=struct('time_s',{},'command',{},'params',{});setpointCount=0;environmentCount=0;
realActions=struct('time_s',{},'name',{},'expected_bits',{},'target_bits',{});
operationLog=strings(0,1);firstEnvironmentOperation=Inf;lastSetupApplyOperation=0;
snapshotCount=0;lastEnvironmentBoardTime=-Inf;environmentBoardTimeMonotonic=true;
injectedFailures=0;
seedContract(cfg.temporary_allocator_geometry.unchanged_guard_entries,'raw_bits_hex');
seedContract(cfg.temporary_allocator_geometry.entries,'original_raw_bits_hex');
seedContract(cfg.native_hover_tuning.unchanged_guard_entries,'raw_bits_hex');
seedContract(cfg.native_hover_tuning.entries,'original_raw_bits_hex');
seedContract(cfg.native_hover_tuning.output_guard_entries,'raw_bits_hex');
io=struct('now',@now,'sleep',@sleep,'snapshot',@snapshot, ...
    'sendHeartbeat',@noop,'sendSetpoint',@setpoint,'requestCommand',@command, ...
    'commandAck',@getAck,'readParameter',@readParameter, ...
    'setIntegerParameter',@setInteger,'setRealParameter',@setReal, ...
    'setNativeHoverTuningParameter',@setReal,'sendPlantEnvironment',@sendEnvironment, ...
    'close',@closeIo,'evidence',@evidence);
    function x=now(),x=t;end
    function sleep(dt),t=t+dt;updateGround();end
    function noop(),end
    function setpoint(r)
        setpointCount=setpointCount+1;
        if isstruct(r),target=double(r.position_ned_m);else,target=double(r);end
        if armed&&main==6
            old=position;position=target;velocity=(position-old)/max(cfg.poll_period_s,.02);
            if norm(velocity)>10,velocity=velocity/norm(velocity)*10;end
        else,velocity=zeros(1,3);end
        updateGround();
    end
    function updateGround()
        ground=armed==0&&landed==1;
        if ground~=previousGround
            continuity=continuity+1;previousGround=ground;if ground,groundSince=t;end
        end
    end
    function s=snapshot()
        snapshotCount=snapshotCount+1;
        updateGround();ground=landed==1&&abs(position(3))<1e-12;
        sample=struct('clock_id','MATLAB_MONOTONIC_MAPPED_SOURCE_TIME', ...
            'time_s',t,'received_at_s',t,'position_ned_m',position, ...
            'velocity_ned_mps',velocity);
        stream=struct('raw_source_time_s',t,'rx_s',t,'position_ned_m',position, ...
            'velocity_ned_mps',velocity,'sample',sample);
        model=struct('model_ready',true,'decoded',struct('sim_time_s',t, ...
            'ground_confirmed',ground),'fatal_reason','','status','FIXTURE');
        ext=struct('present',~isempty(environment),'mass_ack_valid',~isempty(environment), ...
            'decoded',struct('environment_extension',struct( ...
            'applied_payload_generation',payloadGen,'actual_payload_kg',payload, ...
            'actual_total_mass_kg',9.5+payload)));
        % Deliberately alternate a 40 ms receive-age perturbation. With the
        % 20 ms fixture step this makes the raw derived board time regress,
        % reproducing the live ENVIRONMENT_FAILURE_08 mechanism.
        receiveJitter=0.04*mod(snapshotCount,2);
        boardRx=max(0,t-receiveJitter);
        s=struct('now_s',t,'armed',armed,'landed_state',landed, ...
            'main_mode',main,'sub_mode',sub,'heartbeat_rx_s',t,'extended_rx_s',boardRx, ...
            'estimate',stream,'truth',stream,'clock_valid',true,'model_ready',true, ...
            'model_diagnostic',model,'native_hover_telemetry',struct('passed',true), ...
            'delivery_board_continuity_epoch',continuity,'delivery_environment',ext);
        if failurePhase>0&&injectedFailures==0&&armed==1&&~isempty(environment)&& ...
                environment.mission_phase==failurePhase
            % Inject one invalid native-stream sample while preserving later safety observations.
            s.native_hover_telemetry.passed=false;
            injectedFailures=1;
        end
    end
    function command(cmd,p)
        commands(end+1)=struct('time_s',t,'command',cmd,'params',p); %#ok<AGROW>
        if cmd==176&&p(2)==6,main=6;sub=0;
        elseif cmd==176&&p(2)==4,main=4;sub=6;position(3)=0;velocity=zeros(1,3);landed=1;
        elseif cmd==400&&p(1)==1,armed=1;landed=2;
        elseif cmd==400&&p(1)==0,armed=0;landed=1;main=0;sub=0;
        else,error('m600delivery:FixtureCommand','Unexpected command');end
        % Model 160 ms ACK latency as paused command-handshake time,
        % not an active reference step exceeding the 100 ms bound.
        updateGround();ack=struct('command',cmd,'result',0,'received_at_s',t+.16);
    end
    function a=getAck(cmd,sent)
        a=[];if ~isempty(ack)&&ack.command==cmd&&t>=ack.received_at_s&&ack.received_at_s>=sent,a=ack;end
    end
    function p=readParameter(name),p=params(char(name));end
    function p=setInteger(name,value)
        if startsWith(string(name),'HIL_ACT_FUNC')
            operationLog(end+1,1)="MAPPING_"+string(value); %#ok<AGROW>
            if value~=0,lastSetupApplyOperation=numel(operationLog);end
        end
        params(char(name))=typed(char(name),value);p=params(char(name));
    end
    function p=setReal(name,targetBits,expectedBits,beforeSendGuard)
        name=char(name);targetBits=upper(char(targetBits));expectedBits=upper(char(expectedBits));
        before=params(name);assert(before.mav_type==9&&strcmpi(before.raw_bits_hex,expectedBits), ...
            'm600delivery:FixtureRealExpectedBits');
        assert(beforeSendGuard(),'m600delivery:FixtureRealGuard');
        realActions(end+1)=struct('time_s',t,'name',name, ...
            'expected_bits',expectedBits,'target_bits',targetBits); %#ok<AGROW>
        operationLog(end+1,1)="REAL_"+string(name)+"_"+string(targetBits); %#ok<AGROW>
        if ~isfinite(firstEnvironmentOperation),lastSetupApplyOperation=numel(operationLog);end
        p=typedBits(name,9,targetBits);
        p.real_write_receipt=struct('attempted',true,'send_returned',true, ...
            'ack_verified',true,'readback_verified',true);
        params(name)=rmfield(p,'real_write_receipt');
    end
    function receipt=sendEnvironment(v)
        environmentCount=environmentCount+1;
        operationLog(end+1,1)="ENVIRONMENT"; %#ok<AGROW>
        if ~isfinite(firstEnvironmentOperation),firstEnvironmentOperation=numel(operationLog);end
        environmentBoardTimeMonotonic=environmentBoardTimeMonotonic&& ...
            v.board_min_rx_io_time_s>=lastEnvironmentBoardTime;
        lastEnvironmentBoardTime=v.board_min_rx_io_time_s;
        if v.payload_generation>payloadGen
            releaseCount=releaseCount+1;
            if armed||landed~=1,airborneRelease=airborneRelease+1;end
            minimumDwell=min(minimumDwell,t-groundSince);
            assert(v.payload_generation==payloadGen+1&&v.service_release_generation==v.payload_generation, ...
                'm600delivery:FixtureReleaseGeneration');
            assert(t-groundSince>=8-1e-9,'m600delivery:FixtureEarlyUnload');
            payloadGen=v.payload_generation;payload=v.payload_kg;
        end
        environment=v;
        receipt=struct('sent_s',t,'generation',v.generation, ...
            'payload_generation',v.payload_generation, ...
            'service_release_generation',v.service_release_generation,'bytes',232,'remote_port',30100);
    end
    function yes=closeIo(),closed=true;yes=true;end
    function e=evidence()
        zerosMap=true;for q=1:16,zerosMap=zerosMap&&params(sprintf('HIL_ACT_FUNC%d',q)).decoded==0;end
        e=struct('closed',closed,'final_time_s',t,'final_armed',armed, ...
            'final_landed_state',landed,'all_mappings_zero',zerosMap, ...
            'payload_release_count',releaseCount, ...
            'airborne_payload_release_count',airborneRelease, ...
            'minimum_ground_dwell_before_release_s',minimumDwell, ...
            'setpoint_count',setpointCount,'environment_count',environmentCount, ...
            'first_environment_operation_index',firstEnvironmentOperation, ...
            'last_setup_apply_operation_index',lastSetupApplyOperation, ...
            'environment_began_after_all_setup',isfinite(firstEnvironmentOperation)&& ...
                firstEnvironmentOperation>lastSetupApplyOperation, ...
            'environment_board_time_monotonic',environmentBoardTimeMonotonic, ...
            'last_environment_board_time_s',lastEnvironmentBoardTime, ...
            'operation_log',operationLog, ...
            'commands',commands,'real_parameter_actions',realActions, ...
            'injected_failures',injectedFailures,'injected_phase_code',failurePhase, ...
            'hardware_actions',0,'com_open',0);
    end
    function seedContract(rows,bitsField)
        for z=1:numel(rows)
            name=char(rows(z).name);candidate=typedBits(name,rows(z).mav_type,rows(z).(bitsField));
            if isKey(params,name)
                previous=params(name);
                assert(previous.mav_type==candidate.mav_type&& ...
                    strcmpi(previous.raw_bits_hex,candidate.raw_bits_hex), ...
                    'm600delivery:FixtureContractConflict');
            else
                params(name)=candidate;
            end
        end
    end
end

function p=typed(name,value)
p=struct('name',name,'mav_type',6,'decoded',double(value), ...
    'raw_bits_hex',upper(dec2hex(typecast(int32(value),'uint32'),8)));
end

function p=typedBits(name,mavType,bits)
bits=upper(char(bits));u=uint32(hex2dec(bits));
if mavType==9,value=double(typecast(u,'single'));
elseif mavType==6,value=double(typecast(u,'int32'));
else,error('m600delivery:FixtureType','Unsupported parameter type.');end
p=struct('name',char(name),'mav_type',double(mavType),'decoded',value,'raw_bits_hex',bits);
end
