function report=run_native_hover_tuning_integration_host_tests(outputDir)
% Test orchestration with an in-memory adapter and synthetic clock and plant.
arguments
    outputDir (1,1) string
end
deviceFixture=gpenmpc_test_device_config(); %#ok<NASGU>
assert(~isfolder(outputDir)&&~isfile(outputDir),'m600check:TuningIntegrationOutputExists','Use a new HOST result directory.');
root=fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(root,'tools'),fullfile(root,'matlab_validation'), ...
    fullfile(root,'m600_coptersim','matlab_validation'));
[tuning,tv]=m600check.buildNativeHoverTuningContract();assert(tv.passed,'%s',tv.failure);
[geometry,gv]=m600check.buildTemporaryAllocatorGeometryContract( ...
    fullfile(gpenmpc_external_path('host_native_rotor_geometry'),'RESULT.json'));
assert(gv.passed,'%s',gv.failure);
checks=struct('name',{},'passed',{});cases=struct('name',{},'kind',{},'result',{},'exception',{});
runnerNames={'success','original_mismatch','partial_tuning','geometry_restore_failure', ...
    'tuning_restore_failure','applied_union_drift','partial_mapping','legacy_geometry_only'};
for caseIndex=1:numel(runnerNames)
    scenario=runnerNames{caseIndex};cfg=config(tuning,geometry);
    if strcmp(scenario,'legacy_geometry_only'),cfg=rmfield(cfg,'native_hover_tuning');end
    io=fixture(scenario,'RUNNER',tuning,geometry);r=[];problem='';
    try,r=run_m600_matlab_hil('',cfg,io);catch e,problem=[e.identifier ': ' e.message];end
    cases(end+1)=struct('name',scenario,'kind','REAL_RUNNER_INJECTED_MEMORY_IO','result',r,'exception',problem); %#ok<AGROW>
    check(['runner_' scenario '_returned'],isempty(problem)&&isstruct(r));
    if ~isempty(problem),continue;end
    check(['runner_' scenario '_closed_no_forbidden'],r.matlab_sockets_closed&& ...
        r.counts.force_disarm_requests==0&&r.counts.physical_output_actions==0&&r.counts.com_open_count==0);
    switch scenario
        case 'success'
            check('runner_success_full_hover_and_original138',r.formal_completed&&r.fresh_final_safe_state&& ...
                strcmp(r.status,'PASS_CALLER_DEFINED_M600_NATIVE_HOVER')&&r.native_hover_original138_restored);
            check('runner_success_all_three_union_reads',fullUnion(r.native_hover_parameter_union_original)&& ...
                fullUnion(r.native_hover_parameter_union_applied)&&fullUnion(r.native_hover_parameter_union_restored));
            check('runner_success_separate_apply_restore_counts', ...
                r.allocator_geometry_apply.ack_and_readback_verified_count==12&& ...
                r.allocator_geometry_restore.ack_and_readback_verified_count==12&& ...
                r.counts.tuning_apply_setter_attempts==3&&r.counts.tuning_apply_ack_readback_verified==3&& ...
                r.counts.tuning_restore_setter_attempts==3&&r.counts.tuning_restore_ack_readback_verified==3&& ...
                r.counts.mapping_verified_writes==6&&r.counts.mapping_verified_rollbacks==6);
            order=r.transport_evidence.mutations;kinds={order.kind};
            check('runner_success_actual_mutation_order', ...
                last(kinds,'GEOMETRY_APPLY')<first(kinds,'TUNING_APPLY')&& ...
                last(kinds,'TUNING_APPLY')<first(kinds,'MAPPING_APPLY')&& ...
                last(kinds,'MAPPING_RESTORE')<first(kinds,'GEOMETRY_RESTORE')&& ...
                last(kinds,'MAPPING_RESTORE')<first(kinds,'TUNING_RESTORE'));
            check('runner_original138_read_before_first_mutation', ...
                all(ismember({r.native_hover_parameter_union_original.rows.name},r.transport_evidence.reads_before_first_mutation)));
        case 'original_mismatch'
            check('runner_original_mismatch_zero_authority',contains(r.failure,'NativeHoverOriginal138')&& ...
                numel(r.native_hover_parameter_union_original.rows)==138&& ...
                ~r.native_hover_parameter_union_original.passed&&isempty(r.transport_evidence.mutations)&& ...
                r.counts.mapping_write_attempts==0&&r.counts.offboard_requests==0&&r.counts.arm_requests==0);
            check('runner_original_mismatch_not_safe_PASS',~r.native_hover_original138_restored&&~r.fresh_final_safe_state);
        case 'partial_tuning'
            check('runner_partial_tuning_real_attempt_retained',r.counts.tuning_apply_setter_attempts==2&& ...
                r.counts.tuning_apply_setter_returns==1&&r.counts.tuning_apply_ack_readback_verified==1&& ...
                contains(r.failure,'NativeHoverTuningApply'));
            check('runner_partial_tuning_both_restore_before_any_arm',r.allocator_geometry_restored&& ...
                r.native_hover_tuning_restored&&r.native_hover_original138_restored&& ...
                r.counts.tuning_restore_setter_attempts==2&&r.counts.tuning_restore_no_op==1&& ...
                r.counts.mapping_write_attempts==0&&r.counts.offboard_requests==0&&r.counts.arm_requests==0);
            check('runner_partial_failure_not_erased_by_safe_finally',r.fresh_final_safe_state&& ...
                ~isempty(r.failure)&&~startsWith(r.status,'PASS'));
        case 'geometry_restore_failure'
            check('runner_geometry_failure_does_not_skip_tuning',~r.allocator_geometry_restored&& ...
                r.native_hover_tuning_restored&&r.counts.tuning_restore_ack_readback_verified==3&& ...
                ~r.native_hover_original138_restored&&~r.fresh_final_safe_state&&~startsWith(r.status,'PASS'));
        case 'tuning_restore_failure'
            check('runner_tuning_failure_does_not_undo_geometry_receipt',r.allocator_geometry_restored&& ...
                ~r.native_hover_tuning_restored&&r.counts.tuning_restore_setter_attempts==3&& ...
                r.counts.tuning_restore_ack_readback_verified==2&&~r.fresh_final_safe_state&&~startsWith(r.status,'PASS'));
        case 'applied_union_drift'
            check('runner_applied138_rejects_unchanged_drift_before_mapping', ...
                contains(r.failure,'NativeHoverApplied138')&&numel(r.native_hover_parameter_union_applied.rows)==138&& ...
                r.counts.mapping_write_attempts==0&&r.counts.offboard_requests==0&&r.counts.arm_requests==0);
            check('runner_drift_not_blindly_overwritten',r.allocator_geometry_restored&&r.native_hover_tuning_restored&& ...
                ~r.native_hover_original138_restored&&strcmp(r.transport_evidence.drift_field_bits,'00000000'));
        case 'partial_mapping'
            check('runner_partial_mapping_zero_then_both_restore',contains(r.failure,'InjectedMapping')&& ...
                r.counts.mapping_write_attempts==3&&r.counts.mapping_verified_rollbacks==3&& ...
                r.allocator_geometry_restored&&r.native_hover_tuning_restored&&r.native_hover_original138_restored&& ...
                r.counts.arm_requests==0&&r.counts.offboard_requests==0);
        case 'legacy_geometry_only'
            check('legacy_twelve_geometry_API_unchanged',r.formal_completed&&r.fresh_final_safe_state&& ...
                r.allocator_geometry_apply.ack_and_readback_verified_count==12&& ...
                r.allocator_geometry_restore.ack_and_readback_verified_count==12&& ...
                isempty(r.native_hover_tuning_apply)&&isempty(r.native_hover_parameter_union_original)&& ...
                r.counts.tuning_apply_setter_attempts==0&&r.counts.mapping_verified_writes==6);
    end
end
recoveryNames={'success','partial_apply','already_original','geometry_restore_failure', ...
    'tuning_restore_failure','unknown_tuning','previous_owner_present','earlier_mapping_failure','emergency_force'};
for caseIndex=1:numel(recoveryNames)
    scenario=recoveryNames{caseIndex};cfg=config(tuning,geometry);
    cfg.independent_recovery_previous_owner_released=~strcmp(scenario,'previous_owner_present');
    cfg.allow_emergency_logical_force_disarm=strcmp(scenario,'emergency_force');
    io=fixture(scenario,'RECOVERY',tuning,geometry);r=[];problem='';
    try,r=recover_m600_canonical_udp(cfg,io);catch e,problem=[e.identifier ': ' e.message];end
    cases(end+1)=struct('name',scenario,'kind','REAL_RECOVERY_INJECTED_MEMORY_IO','result',r,'exception',problem); %#ok<AGROW>
    check(['recovery_' scenario '_returned'],isempty(problem)&&isstruct(r));
    if ~isempty(problem),continue;end
    check(['recovery_' scenario '_closed_no_physical_other_writes'],r.udp_closed&& ...
        r.counts.arm_requests==0&&r.counts.physical_mapping_writes==0&&r.counts.parameter_other_writes==0&& ...
        ~r.inner_result_reclassified&&~r.CopterSim_started_or_stopped);
    switch scenario
        case 'success'
            check('recovery_success_exact15_and138',r.safe_bridge_shutdown_allowed&&r.normal_termination_pass&& ...
                r.counts.geometry_restore_ack_readback_verified==12&&r.counts.tuning_restore_ack_readback_verified==3&& ...
                fullUnion(r.native_hover_parameter_union_restored));
            check('recovery_actual_finalread_guard_send_order',isequal(r.evidence.setter_steps, ...
                repmat({'FINAL_TYPED_READ';'FRESH_GUARD';'MOCK_PARAM_SET'},15,1)));
            check('recovery_unhealthy_model_does_not_block_safe_parameters',~r.final_snapshot.model_ready&& ...
                ~r.final_snapshot.clock_valid&&r.safe_bridge_shutdown_allowed);
        case 'partial_apply'
            check('recovery_partial_known_values_only',r.safe_bridge_shutdown_allowed&& ...
                r.counts.geometry_restore_setter_attempts==3&&r.counts.geometry_restore_no_op==9&& ...
                r.counts.tuning_restore_setter_attempts==2&&r.counts.tuning_restore_no_op==1);
        case 'already_original'
            check('recovery_noop_still_full_original_readback',r.safe_bridge_shutdown_allowed&& ...
                r.counts.geometry_restore_setter_attempts==0&&r.counts.tuning_restore_setter_attempts==0&& ...
                r.counts.geometry_restore_no_op==12&&r.counts.tuning_restore_no_op==3&& ...
                fullUnion(r.native_hover_parameter_union_restored));
        case 'geometry_restore_failure'
            check('recovery_geometry_failure_still_restores_tuning3',~r.geometry_original_identity_verified&& ...
                r.tuning_original_identity_verified&&r.counts.tuning_restore_ack_readback_verified==3&& ...
                ~r.safe_bridge_shutdown_allowed&&~r.normal_termination_pass);
        case 'tuning_restore_failure'
            check('recovery_tuning_failure_retains_geometry12_and_rejects_shutdown',r.geometry_original_identity_verified&& ...
                ~r.tuning_original_identity_verified&&r.counts.tuning_restore_setter_attempts==3&& ...
                r.counts.tuning_restore_ack_readback_verified==2&&~r.safe_bridge_shutdown_allowed&&~r.normal_termination_pass);
        case 'unknown_tuning'
            check('recovery_unknown_not_overwritten_known_remainder_restored',~r.safe_bridge_shutdown_allowed&& ...
                r.counts.tuning_restore_setter_attempts==2&&~r.tuning_restore_receipt.actions(1).attempted&& ...
                strcmp(r.evidence.first_tuning_bits,'3F800000')&&~r.normal_termination_pass);
        case 'previous_owner_present'
            check('recovery_previous_owner_required_for_both_services',r.counts.geometry_restore_setter_attempts==0&& ...
                r.counts.tuning_restore_setter_attempts==0&&contains(r.geometry_restore_failure,'PreviousOwnerNotReleased')&& ...
                contains(r.tuning_restore_failure,'PreviousOwnerNotReleased')&&~r.safe_bridge_shutdown_allowed);
        case 'earlier_mapping_failure'
            check('recovery_safe_identity_does_not_erase_original_mapping_failure',r.safe_bridge_shutdown_allowed&& ...
                r.native_hover_original138_restored&&contains(r.failure,'InjectedMapping')&&~r.normal_termination_pass);
        case 'emergency_force'
            check('recovery_force_must_not_become_normal_PASS',r.safe_bridge_shutdown_allowed&& ...
                r.counts.force_disarm_requests==1&&r.emergency_force_used&&~r.normal_termination_pass&& ...
                r.geometry_original_identity_verified&&r.tuning_original_identity_verified);
    end
end
% Test recovery validation independently of the launcher.
for caseIndex=1:2
    cfg=config(tuning,geometry);cfg.independent_recovery_previous_owner_released=true;
    io=fixture('success','RECOVERY',tuning,geometry);problem='';
    if caseIndex==1,cfg.native_hover_tuning.entries(1).target_raw_bits_hex='3F000000';label='bad_tuning';
    else,cfg.temporary_allocator_geometry.entries(1).original_raw_bits_hex='3F000000';label='bad_geometry_with_tuning';end
    try,recover_m600_canonical_udp(cfg,io);catch e,problem=[e.identifier ': ' e.message];end
    if caseIndex==1,expectedError='m600check:RecoveryTuningContract';
    else,expectedError='m600check:RecoveryTuningGeometryContract';end
    ev=io.evidence();check(['direct_recovery_' label '_rejected_before_IO'], ...
        contains(problem,expectedError)&&isempty(ev.commands)&&isempty(ev.mutations));
    cases(end+1)=struct('name',label,'kind','DIRECT_RECOVERY_PREFLIGHT_NEGATIVE', ...
        'result',ev,'exception',problem); %#ok<AGROW>
end
paths={fullfile(root,'tools','run_m600_matlab_hil.m'),fullfile(root,'tools','recover_m600_canonical_udp.m'), ...
    fullfile(root,'tools','launch_m600_canonical_hil.m'),fullfile(root,'tools','m600_canonical_serial_preflight.m')};
static=struct('path',{},'sha256',{},'checkcode',{},'scope',{});
for sourceIndex=1:numel(paths)
    static(end+1)=struct('path',paths{sourceIndex},'sha256',m600check.fileSha256(paths{sourceIndex}), ...
        'checkcode',checkcode(paths{sourceIndex},'-id'), ...
        'scope','STATIC_CODE_ANALYSIS'); %#ok<AGROW>
end
report=struct('schema','HOST_NATIVE_HOVER_TUNING_INTEGRATION_V1','passed',all([checks.passed]), ...
    'checks_total',numel(checks),'checks_passed',nnz([checks.passed]),'checks',checks,'cases',cases, ...
    'static_sources',static,'hardware_actions',0,'COM_UDP_actions',0,'flight_admission',false, ...
    'scope','Actual runner/recovery/helper memory-IO behavior; serial/launcher static only.', ...
    'limitations','Synthetic state and clock fixtures exercise tuning integration.');
mkdir(outputDir);save(fullfile(outputDir,'RESULT.mat'),'report','-v7.3');
fid=fopen(fullfile(outputDir,'RESULT.json'),'w','n','UTF-8');assert(fid>=0);c=onCleanup(@()fclose(fid));
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));clear c
fprintf('Tuning integration HOST: %d/%d\n',report.checks_passed,report.checks_total);
assert(report.passed,'m600check:TuningIntegratedHostFailed','Failed: %s',strjoin({checks(~[checks.passed]).name},', '));
    function check(name,value)
        checks(end+1)=struct('name',name,'passed',islogical(value)&&isscalar(value)&&value);
    end
end

function yes=fullUnion(r)
yes=isstruct(r)&&r.passed&&r.read_attempts==138&&numel(r.rows)==138&&all([r.rows.passed]);
end
function i=first(kinds,name),i=find(strcmp(kinds,name),1,'first');if isempty(i),i=Inf;end,end
function i=last(kinds,name),i=find(strcmp(kinds,name),1,'last');if isempty(i),i=-Inf;end,end
function cfg=config(tuning,geometry)
policy=struct('clock_id','FIXTURE','clock_mapping_evidence','FIXTURE','window_s',[0,1], ...
    'minimum_anchor_samples',5,'required_valid_fraction',1,'maximum_anchor_gap_s',.05, ...
    'maximum_source_age_s',struct('reference',.05,'estimate',.05), ...
    'maximum_receive_lag_s',struct('reference',.05,'estimate',.05,'truth',.05), ...
    'maximum_alignment_skew_s',.05,'limits',struct('position_rms_m',.1,'position_p95_m',.1, ...
    'position_max_m',.1,'estimator_gap_max_m',.1,'velocity_tracking_rms_mps',.1,'truth_speed_max_mps',.1));
cfg=struct('live_enabled',false,'outer_preflight_pass',false,'outer_preflight_receipt','MEMORY_ONLY', ...
    'plant_identity','SYNTHETIC_STATE_MACHINE_NOT_PHYSICS','write_artifacts',false, ...
    'hover_altitude_m',1,'hover_duration_s',.4,'prestream_s',.1,'preflight_deadline_s',.3, ...
    'mode_timeout_s',.15,'arm_timeout_s',.15,'land_timeout_s',.2,'disarm_timeout_s',.15, ...
    'command_timeout_s',.15,'poll_period_s',.02,'heartbeat_period_s',.08, ...
    'heartbeat_max_age_s',.1,'landed_max_age_s',.1,'state_max_age_s',.1, ...
    'maximum_initial_origin_offset_m',.5,'abort_truth_speed_mps',2,'abort_estimator_gap_m',2, ...
    'evaluation_policy',policy,'native_hover_tuning',tuning,'temporary_allocator_geometry',geometry, ...
    'expected_uid','1234605616436508552','expected_board_version',56, ...
    'expected_flight_custom_version_hex','0102030405060708');
end

function io=fixture(scenario,kind,tuning,geometry)
params=containers.Map('KeyType','char','ValueType','any');
original=tuning.unchanged_guard_entries(:);
for seedIndex=1:3,e=tuning.entries(seedIndex);original(end+1)=struct('name',e.name,'mav_type',9,'raw_bits_hex',e.original_raw_bits_hex);end %#ok<AGROW>
for seedIndex=1:numel(original),e=original(seedIndex);params(e.name)=typed(e.name,e.mav_type,e.raw_bits_hex);end
for seedIndex=1:numel(tuning.output_guard_entries),e=tuning.output_guard_entries(seedIndex);params(e.name)=typed(e.name,e.mav_type,e.raw_bits_hex);end
allDelta=[geometry.entries(:);tuning.entries(:)];
if strcmp(kind,'RECOVERY')&&~strcmp(scenario,'already_original')
    for seedIndex=1:numel(allDelta)
        if strcmp(scenario,'partial_apply')&&~ismember(seedIndex,[1:3,13:14]),continue;end
        e=allDelta(seedIndex);params(e.name)=typed(e.name,9,e.target_raw_bits_hex);
    end
end
if any(strcmp(scenario,{'original_mismatch','applied_union_drift'}))
    assert(isKey(params,'FD_FAIL_R'));fdOriginal=params('FD_FAIL_R');assert(~strcmp(fdOriginal.raw_bits_hex,'00000000'));
end
if strcmp(scenario,'original_mismatch'),params('FD_FAIL_R')=typed('FD_FAIL_R',9,'00000000');end
if strcmp(scenario,'unknown_tuning'),e=tuning.entries(1);params(e.name)=typed(e.name,9,'3F800000');end
if strcmp(scenario,'earlier_mapping_failure'),params('HIL_ACT_FUNC1')=typed('HIL_ACT_FUNC1',6,'00000065');end
t=0;armed=0;landed=1;main=0;sub=0;pos=[0,0,-.25];target=pos;landAt=Inf;versionRx=-Inf;closed=false;
if strcmp(scenario,'emergency_force'),armed=1;landed=2;end
ack=[];reads={};beforeFirst={};steps=cell(0,1);commands=struct('command',{},'params',{},'time_s',{});
mutations=struct('kind',{},'name',{},'raw_bits_hex',{},'time_s',{});raw=struct('name',{}, ...
    'attempted',{},'send_returned',{},'ack_verified',{},'readback_verified',{});
version=struct('uid',uint64(3473490377)*uint64(1000000000)+uint64(90611257), ...
    'board_version',56,'flight_custom_version',uint8(1:8));
io=struct('now',@now,'sleep',@sleep,'snapshot',@snapshot,'sendHeartbeat',@noop, ...
    'sendSetpoint',@setpoint,'requestCommand',@command,'commandAck',@getAck,'readParameter',@readParam, ...
    'setIntegerParameter',@setInteger,'setRealParameter',@setGeometry, ...
    'setNativeHoverTuningParameter',@setTuning,'close',@closeIo,'evidence',@evidence);
    function x=now(),x=t;end
    function sleep(dt),t=t+dt;end
    function noop(),end
    function setpoint(p),target=p;if armed==1,pos=target;end,end
    function s=snapshot()
        if t>=landAt,pos=[0,0,-.25];landed=1;armed=0;end
        sample=struct('clock_id','MATLAB_MONOTONIC_MAPPED_SOURCE_TIME','time_s',t, ...
            'received_at_s',t,'position_ned_m',pos,'velocity_ned_mps',[0,0,0]);
        state=struct('raw_source_time_s',t,'rx_s',t,'position_ned_m',pos,'velocity_ned_mps',[0,0,0],'sample',sample);
        healthy=strcmp(kind,'RUNNER');d=struct('model_ready',healthy,'status','EXPLICIT_MEMORY_FIXTURE', ...
            'fatal_reason','','decoded',struct('ground_confirmed',landed==1));
        s=struct('now_s',t,'armed',armed,'landed_state',landed,'main_mode',main,'sub_mode',sub, ...
            'heartbeat_rx_s',t,'extended_rx_s',t,'estimate',state,'truth',state, ...
            'clock_valid',healthy,'model_ready',healthy,'model_diagnostic',d, ...
            'autopilot_version',version,'autopilot_version_rx_s',versionRx);
    end
    function command(cmd,p)
        t=t+.001;commands(end+1)=struct('command',cmd,'params',p,'time_s',t); %#ok<AGROW>
        if cmd==512,assert(p(1)==148);versionRx=t;
        elseif cmd==176&&p(2)==6,main=6;
        elseif cmd==176&&p(2)==4
            main=4;sub=6;if ~strcmp(scenario,'emergency_force'),landAt=t+.04;end
        elseif cmd==400&&p(1)==1,armed=1;landed=2;pos=target;
        elseif cmd==400&&p(1)==0,armed=0;if p(2)==21196,landed=1;end
        else,error('m600check:FixtureUnexpectedCommand','Unexpected fixture command.');end
        ack=struct('command',cmd,'result',0,'received_at_s',t);
    end
    function a=getAck(cmd,sent)
        a=[];if ~isempty(ack)&&ack.command==cmd&&ack.received_at_s>=sent,a=ack;end
    end
    function p=readParam(name)
        name=char(name);reads{end+1}=name;assert(isKey(params,name),'m600check:FixtureMissingTypedField','%s',name);p=params(name);
    end
    function p=setInteger(name,value)
        assert(startsWith(name,'HIL_ACT_FUNC')&&ismember(value,[0,101:106]));
        if isempty(mutations),beforeFirst=reads;end
        bits=upper(dec2hex(typecast(int32(value),'uint32'),8));
        if value==0,label='MAPPING_RESTORE';else,label='MAPPING_APPLY';end
        mutations(end+1)=struct('kind',label,'name',name,'raw_bits_hex',bits,'time_s',t); %#ok<AGROW>
        params(name)=typed(name,6,bits);
        if (strcmp(scenario,'partial_mapping')&&value==103)||strcmp(scenario,'earlier_mapping_failure')
            error('m600check:InjectedMapping','Mutation occurred before lost mapping ACK.');
        end
        p=readParam(name);
    end
    function p=setGeometry(name,bits,expectedBits,safeGuard)
        p=setReal(name,bits,expectedBits,safeGuard,'GEOMETRY',geometry.entries);
    end
    function p=setTuning(name,bits,expectedBits,safeGuard)
        p=setReal(name,bits,expectedBits,safeGuard,'TUNING',tuning.entries);
    end
    function p=setReal(name,bits,expectedBits,safeGuard,family,entries)
        e=entries(strcmp({entries.name},name));assert(isscalar(e));
        current=readParam(name);steps{end+1,1}='FINAL_TYPED_READ';
        assert(current.mav_type==9&&strcmpi(current.raw_bits_hex,expectedBits), ...
            'm600check:FixtureTOCTOUIdentity','Internal final read changed before send.');
        okay=safeGuard();steps{end+1,1}='FRESH_GUARD';
        assert(isequal(okay,true),'m600check:FixtureFreshGuard','Fresh state/output guard failed.');
        isApply=strcmpi(bits,e.target_raw_bits_hex);if isApply,suffix='APPLY';else,suffix='RESTORE';end
        % Send immediately after the final guard.
        steps{end+1,1}='MOCK_PARAM_SET';if isempty(mutations),beforeFirst=reads;end
        mutations(end+1)=struct('kind',[family '_' suffix],'name',name,'raw_bits_hex',bits,'time_s',t); %#ok<AGROW>
        raw(end+1)=struct('name',name,'attempted',true,'send_returned',false,'ack_verified',false,'readback_verified',false); %#ok<AGROW>
        blocked=(strcmp(scenario,'geometry_restore_failure')&&strcmp(family,'GEOMETRY')&&~isApply&&strcmp(name,geometry.entries(1).name))|| ...
            (strcmp(scenario,'tuning_restore_failure')&&strcmp(family,'TUNING')&&~isApply&&strcmp(name,tuning.entries(1).name));
        if blocked,error('m600check:InjectedRestore','Fixture restore send failed.');end
        params(name)=typed(name,9,bits);
        if strcmp(scenario,'partial_tuning')&&strcmp(family,'TUNING')&&isApply&&strcmp(name,tuning.entries(2).name)
            error('m600check:InjectedTuningACK','Mutation occurred but setter result was lost.');
        end
        if strcmp(scenario,'applied_union_drift')&&strcmp(family,'TUNING')&&isApply&&strcmp(name,tuning.entries(3).name)
            params('FD_FAIL_R')=typed('FD_FAIL_R',9,'00000000');
        end
        raw(end).send_returned=true;raw(end).ack_verified=true;raw(end).readback_verified=true;
        p=typed(name,9,bits);p.real_write_receipt=struct('attempted',true,'send_returned',true,'ack_verified',true,'readback_verified',true);
    end
    function yes=closeIo(),closed=true;yes=true;end
    function e=evidence()
        p=params(tuning.entries(1).name);d=params('FD_FAIL_R');
        e=struct('mock_only',true,'closed',closed,'commands',commands,'mutations',mutations, ...
            'real_parameter_actions',raw,'setter_steps',{steps},'reads_before_first_mutation',{beforeFirst}, ...
            'first_tuning_bits',p.raw_bits_hex,'drift_field_bits',d.raw_bits_hex);
    end
end
function p=typed(name,mavType,bits)
u=uint32(hex2dec(bits));if mavType==9,v=double(typecast(u,'single'));else,v=double(typecast(u,'int32'));end
p=struct('name',name,'mav_type',mavType,'decoded',v,'raw_bits_hex',upper(bits));
end
