function report=run_native_takeoff_cascade_sil(outputDir,positionMexDir,takeoffMexDir,actuatorFixture)
% Run the takeoff/hover diagnostic with numerical kernels and the M600 RK4 plant.
arguments
    outputDir (1,1) string
    positionMexDir (1,1) string = string(gpenmpc_external_path('native_takeoff_position_control_mex'))
    takeoffMexDir (1,1) string = string(gpenmpc_external_path('native_takeoff_mex'))
    actuatorFixture (1,1) string = "RAW_ALLOCATOR_100HZ"
end
assert(~isfolder(outputDir)&&~isfile(outputDir),'gpenmpc:ExistingOutput','No overwrite.');
assert(ismember(actuatorFixture,["RAW_ALLOCATOR_100HZ","SOURCE_PWMSIM_QUANTIZED_100HZ", ...
    "SOURCE_PWMSIM_QUANTIZED_50HZ_ZOH"]),'gpenmpc:UnknownActuatorFixture');
build=string(fileparts(fileparts(mfilename('fullpath'))));
runtime=string(gpenmpc_external_path('native_control_runtime_root'));
oldPath=path;handles={};
try
    addpath(fullfile(build,'tools'),fullfile(build,'matlab_validation'), ...
        fullfile(build,'m600_coptersim','matlab_validation'));
    dirs=[positionMexDir;fullfile(gpenmpc_external_path('host_native_lower_loop_mex')); ...
        fullfile(gpenmpc_external_path('host_native_sensor_filter_mex'));takeoffMexDir];
    names=["gpenmpc_px4_native_position_control_mex";"gpenmpc_px4_native_lower_loop_mex"; ...
        "gpenmpc_px4_sensor_filter_mex";"gpenmpc_px4_native_takeoff_mex"];
    expected=["11ADD5F95EC0481F124EFE53CE1D0C2AECA05B19C613E3C7DC1E30050AA24B89"; ...
        "62B8C112B32909269BA6FB7F7C31D980B0D6759BD556DFF5A7AB7454D81BDAE5"; ...
        "C4D4F05F491538967916A6769F62D92102E073645FE952B396829E56900BAD39"; ...
        "A9418125C5FF8DE54D79A4ADD044A68C79AA6DE6416D03872C70CCFDE6EB8565"];
    bindings=cell(4,1);
    for bindingIndex=1:4
        addpath(dirs(bindingIndex),'-begin');binary=fullfile(dirs(bindingIndex),names(bindingIndex)+".mexw64");
        assert(strcmpi(which(names(bindingIndex)),binary),'gpenmpc:UnexpectedMexResolution');
        bindings{bindingIndex}=verifyBuild(binary,fullfile(dirs(bindingIndex),'BUILD_RESULT.json'),expected(bindingIndex));
        handles{bindingIndex}=str2func(names(bindingIndex)); %#ok<AGROW>
    end
catch setupFailure
    finish(handles,oldPath);rethrow(setupFailure);
end
cleanup=onCleanup(@()finish(handles,oldPath)); %#ok<NASGU>
pos=handles{1};low=handles{2};sensor=handles{3};takeoff=handles{4};
m600check.loadFixture();
modelFile=fullfile(gpenmpc_external_path('flat_terrain_model'),'M600_CORE_PARAMETERS.mat');
assert(strcmpi(m600check.fileSha256(modelFile),'969D347CE041715CAED49BE0B7897486E34FA4E0B22EB82E50E9752B8F4F19E4'));
loaded=load(modelFile,'parameters');p=loaded.parameters;
[pc,module,positionMeta]=native_position_control_current_config();
[lc,lowerMeta]=native_lower_loop_current_config();[fc,sensorMeta]=native_sensor_filter_explicit_fixture(100);
[actuatorContract,actuatorSources]=actuatorFixtureContract(actuatorFixture,build,positionMeta);
assert(module.COM_SPOOLUP_TIME==1&&module.MPC_TKO_RAMP_T==3&&module.COM_THROW_EN==0, ...
    'gpenmpc:UnexpectedTakeoffProfile');
assert(module.MPC_VEL_LP==0&&module.MPC_VEL_NF_FRQ==0&&module.MPC_VELD_LP==5);
assert(pc.hover_thrust==.5&&all(lc.attitude_p(1:2)==6.5),'gpenmpc:UnexpectedCurrentHoverOrAttitude');
assert(positionMeta.module_phase_contract.explicit_new_instance_effective_vertical_I==0 ...
    &&positionMeta.module_phase_contract.no_route_motion_hover_target_I==0,'gpenmpc:UnexpectedNoRoutePhase');
candidateFile=fullfile(gpenmpc_external_path('host_native_attitude_candidate'),'CANDIDATE.json');
assert(strcmpi(m600check.fileSha256(candidateFile),'A6C93CC99FF39A6B84CD132E9DB0A4471E60D125781AE7BFD7677A260CD29C19'));
candidate=jsondecode(fileread(candidateFile));
assert(candidate.passed&&~candidate.SIL_outcomes_read&&~candidate.live_admission&&isequaln(candidate.original_configuration,lc));
unchanged=candidate.candidate_configuration;unchanged.attitude_p=lc.attitude_p;
assert(isequaln(unchanged,lc)&&strcmp(candidate.selection.common_REAL32_bits,'4026CCBE') ...
    &&all(candidate.candidate_configuration.attitude_p(1:2)==double(typecast(uint32(hex2dec('4026CCBE')),'single'))));

% Derive the third hover-thrust value from the model before running the MEX.
% Encode the parameter as its nearest REAL32 value.
payload=2.21;gravity=9.80665;
mass=p.profile.mass_properties.base_mass_kg+payload+p.mission.plant_mismatch.mass_bias_kg;
assert(abs(mass-11.71)<1e-12&&isfinite(mass)&&mass>0);
upper=p.calibration.rotor_allocation.per_rotor_thrust_upper_n;
assert(isfinite(upper)&&upper>0&&numel(p.calibration.rotor_allocation.angles_deg)==6);
assert(isequal(p.mission.plant_mismatch.thrust_effectiveness_by_rotor(:),ones(6,1)) ...
    &&~p.mission.structured_residual.enabled,'gpenmpc:ModelTrimRequiresNeutralRotorEffectiveness');
idealHover=mass*gravity/(6*upper);trim=double(single(idealHover));
assert(trim>=.05&&trim<=.9&&isfinite(trim),'gpenmpc:ModelTrimOutsideNativeHoverDomain');
selection=struct('rule','REAL32_NEAREST(model_total_mass_kg * 9.80665 / (6 * model_per_rotor_Fmax_N))', ...
    'provenance','VEHICLE_TRIM_ENGINEERING_CALIBRATION_FROM_MODEL__NOT_OUTCOME_TUNING', ...
    'mass_kg',mass,'payload_kg',payload,'gravity_mps2',gravity,'rotor_count',6,'per_rotor_Fmax_N',upper, ...
    'model_derived_hover_before_REAL32',idealHover,'selected_hover_REAL32',trim,'selected_hover_raw_bits',raw32(trim), ...
    'original_hover_REAL32',pc.hover_thrust,'original_hover_raw_bits',raw32(pc.hover_thrust), ...
    'REAL32_rounding_error',trim-idealHover,'position_vertical_I_gain_all_cases',0, ...
    'rate_I_unchanged',true,'model_parameters_changed',false,'protective_parameters_changed',false, ...
    'outcomes_read_for_selection',false,'live_parameter_apply_authorized_by_this_file',false);
specs=struct('name',{},'attitude_candidate',{},'hover_thrust',{});
specs(1)=struct('name','CURRENT_ATTITUDE_P__TYPED_HT_050','attitude_candidate',false,'hover_thrust',pc.hover_thrust);
specs(2)=struct('name','ANALYTIC_ATTITUDE_P__TYPED_HT_050','attitude_candidate',true,'hover_thrust',pc.hover_thrust);
specs(3)=struct('name','ANALYTIC_ATTITUDE_P__MODEL_TRIM_HT','attitude_candidate',true,'hover_thrust',trim);
fixture=struct('duration_s',20,'dt_s',.01,'source_clock_epoch_us',uint64(1000000), ...
    'position_sensor_rate_hz',100,'initial_height_m',0,'target_position_ned_m',[0;0;-1], ...
    'initial_north_offset_m',.02,'initial_roll_deg',.05,'initial_body_rates',zeros(3,1), ...
    'initial_motor_commands',zeros(6,1),'initial_rotor_thrust_N',zeros(6,1), ...
    'model009_ground_state','z_up=0 provides static ground support under the model contact equations.', ...
    'spoolup_time_s',module.COM_SPOOLUP_TIME,'ramp_time_s',module.MPC_TKO_RAMP_T, ...
    'tilt_slew_rate_rad_s',double(single(.2)),'tilt_slew_initial_rad',0, ...
    'vertical_I_phase','CURRENT_SOURCE_NO_ROUTE_HOVER_ZERO_GAIN__NOT_INTEGRAL_DISABLE_TUNING', ...
    'HTE_available',false,'HTE_updates',0,'native_MPC_USE_HTE_parameter',module.MPC_USE_HTE, ...
    'HTE_limit','Each case uses an explicit fixed hover-thrust value.', ...
    'payload_transition_or_route_topic_available',false,'native_land_detector_reconstructed',false, ...
    'ideal_detector_fixture','landed=ground_confirmed && contact_active; maybe_landed=contact_active; ground_contact=contact_active from original plant/memory', ...
    'ground_memory','initialStepMemory and stepPx4Rk4 ground-support dwell and confirmation.', ...
    'source_feedback','Same-clock model NED state and native-filtered gyro provide HOST feedback.', ...
    'arm_fixture','armed=true from t0 is a numerical input; no Commander/pre-arm/offboard contract is proved', ...
    'diagnostic_stop_attitude_deg',15,'diagnostic_stop_position_error_m',3, ...
    'stop_provenance','Bounded numerical takeoff experiment.', ...
    'control_input_during_preflight','Native empty p/v with acceleration [0,0,100], no hidden motor clamp or artificial launch', ...
    'comparison_scope','Three fixed takeoff/hover cases.');
fixture.actuator_output=actuatorContract;
sources=struct('path',{},'bytes',{},'sha256',{});
sourcePaths=[string(which('m600check.stepPx4Rk4'));string(which('m600check.derivativeSoftware')); ...
    string(which('m600check.contactKernel'));string(which('m600check.initialStepMemory')); ...
    string(which('m600check.copterSimOutputs'));string(which('gpenmpcM600SixDofPlantDerivative')); ...
    string(which('native_position_control_current_config'));string(which('native_lower_loop_current_config')); ...
    string(which('native_sensor_filter_explicit_fixture'));modelFile;candidateFile; ...
    string(gpenmpc_external_path('px4_position_controller_source')); ...
    string(gpenmpc_external_path('px4_slew_rate_source'))];
for sourceIndex=1:numel(sourcePaths),sources(end+1)=identity(sourcePaths(sourceIndex));end %#ok<AGROW>
sources=[sources,actuatorSources];
prospective=struct('schema','HOST_NATIVE_TAKEOFF_CASCADE_PROSPECTIVE_V1','selected_utc', ...
    char(datetime('now','TimeZone','UTC','Format',"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")), ...
    'selection',selection,'cases',specs,'fixture',fixture,'model',identity(modelFile), ...
    'attitude_candidate',identity(candidateFile),'position_configuration',pc,'lower_configuration',lc, ...
    'position_metadata',positionMeta,'lower_metadata',lowerMeta,'sensor_metadata',sensorMeta, ...
    'binary_bindings',{bindings},'numerical_sources',sources,'script',identity([mfilename('fullpath') '.m']), ...
    'outcomes_read',false,'MEX_calls_at_selection',0,'hardware_actions',0,'COM_UDP_actions',0,'live_admission',false);
mkdir(outputDir);writeJson(fullfile(outputDir,'PROSPECTIVE_SELECTION.json'),prospective);
prospectiveId=identity(fullfile(outputDir,'PROSPECTIVE_SELECTION.json'));

allData=cell(3,1);results=struct([]);
for caseIndex=1:3
    [caseResult,caseData]=runOne(specs(caseIndex),pc,lc,candidate.candidate_configuration,fc,module,p, ...
        mass,payload,upper,fixture,handles);
    allData{caseIndex}=caseData;
    if isempty(results),results=caseResult;else,results(end+1)=caseResult;end %#ok<AGROW>
    writetable(caseData.trace,fullfile(outputDir,string(specs(caseIndex).name)+'.csv'));
    fprintf('HOST takeoff case %d/3 %s: %s rows=%d final error=%.6f m\n', ...
        caseIndex,specs(caseIndex).name,caseResult.termination,caseResult.completed_rows,caseResult.final_position_error_m);
end
report=struct('schema','HOST_NATIVE_TAKEOFF_CASCADE_SIL_V1', ...
    'classification','HOST_TAKEOFF_HOVER_NUMERICAL_CASCADE_DIAGNOSTIC', ...
    'cases_planned',3,'cases_executed',numel(results),'all_cases_preserved',numel(results)==3, ...
    'infrastructure_valid_cases',nnz(cellfun(@isempty,{results.failure})), ...
    'cases',results,'prospective_selection',prospectiveId,'selection',selection,'fixture',fixture, ...
    'all_source_inputs_unchanged',checkSources(sources),'hardware_actions',0,'COM_UDP_actions',0, ...
    'live_admission',false,'limitations',{{ ...
        'The PositionControl kernel includes GPENMPC modifications.', ...
        'TakeoffHandling and Hysteresis are actual C++ kernels. Only caller-side documented module ordering is reproduced.', ...
        'The Takeoff gateway groups updateTakeoffState/updateRamp; the latter has no dependence on intervening hover/reset/tilt setters, so its returned state and limit retain the original numerical order.', ...
        'The HOST caller reproduces float tilt slew.', ...
        'Land, maybe-land and ground-contact flags are model-derived fixtures.', ...
        'Native landed/maybe-land inputs determine rate-integral updates.', ...
        'The no-route effective vertical I gain is zero in every case.', ...
        'HTE, sensor calibration history, EKF, transport, work queues, Commander/failsafe and disarm/landing are absent.', ...
        'HOST source timing is fixed at 100 Hz.', ...
        'RAW_ALLOCATOR_100HZ uses continuous raw allocator outputs: it is not an exact actuator_outputs_sim wire replay.', ...
        'Quantized fixtures reproduce the nonreversible motor FunctionMotors/interpolate/lroundf/PWMSim arithmetic only, with THR_MDL_FAC=0.', ...
        'Actuator publication samples even control ticks at 50 Hz; the controller and plant run at 100 Hz.', ...
        'Recorded animation input changes near 49.7 Hz motivate the 50 Hz sensitivity fixture.', ...
        'Stopped cases retain their actual duration, endpoint and invalid-input records.', ...
        'Each case uses the bound physical, control and screening parameters.'}});
save(fullfile(outputDir,'RAW_TAKEOFF_CASCADE_SIL.mat'),'allData','report','prospective','-v7.3');
writeJson(fullfile(outputDir,'RESULT.json'),report);
assert(report.all_source_inputs_unchanged,'gpenmpc:SourceChangedDuringHostDiagnostic');
end

function [result,data]=runOne(spec,pc,lc,analyticCfg,fc,module,p,mass,payload,upper,fixture,handles)
pos=handles{1};low=handles{2};sensor=handles{3};takeoff=handles{4};
dt=fixture.dt_s;n=round(fixture.duration_s/dt);
positionCfg=pc;positionCfg.hover_thrust=spec.hover_thrust;
lowerCfg=lc;if spec.attitude_candidate,lowerCfg=analyticCfg;end
lowerCfg.initial_motor_commands=zeros(6,1);
takeoffCfg=struct('spoolup_time_s',module.COM_SPOOLUP_TIME,'ramp_time_s',module.MPC_TKO_RAMP_T, ...
    'vertical_velocity_p',pc.velocity_p(3),'parameter_provenance','CURRENT_TYPED_WITH_EXPLICIT_MODULE_PHASE');
X=nan(n+1,19);R=nan(n,38);commands=cell(n,1);plantStatuses=cell(n,1);contacts=cell(n,1);
rawAllocator=nan(n,6);quantizedCommands=nan(n,6);appliedCommands=nan(n,6);
publicationUpdates=false(n,1);publicationSourceTimes=nan(n,1);publicationSampleAges=nan(n,1);
rows=0;attempts=0;failure='';firstException=struct();lastStage='INIT';
termination='FULL_PREDECLARED_TAKEOFF_HOVER_WINDOW';initReceipts=cell(4,1);
x=zeros(19,1);x(1)=fixture.initial_north_offset_m;x(7:10)=[cosd(fixture.initial_roll_deg/2);-sind(fixture.initial_roll_deg/2);0;0];
X(1,:)=x.';memory=m600check.initialStepMemory();controls=zeros(16,1);
heldActuator=zeros(6,1);lastPublicationSourceTime=NaN;
jet=zeros(12,1);jet(3)=1;target=fixture.target_position_ned_m;
previousVelocity=zeros(3,1,'single');accelFiltered=zeros(3,1,'single');tiltState=single(0);
df=single(dt);tau=single(1)/(single(2*pi)*single(module.MPC_VELD_LP));alpha=df/(tau+df);
try
    for clearIndex=1:4,handles{clearIndex}('clear');end
    initReceipts{1}=pos('init',positionCfg);initReceipts{2}=low('init',lowerCfg);
    initReceipts{3}=sensor('init',fc);initReceipts{4}=takeoff('init',takeoffCfg);
    assert(initReceipts{1}&&initReceipts{2}&&initReceipts{3}.initialized&&initReceipts{4});
    for stepIndex=1:n
        attempts=stepIndex;t=(stepIndex-1)*dt;lastStage='PRE_STEP_PLANT_OBSERVATION';
        commands{stepIndex}=struct('time_s',t,'stage',lastStage);
        rotor=controls([5;1;4;6;2;3])*upper;
        [dx,d,currentContact]=m600check.derivativeSoftware(x,rotor,jet,payload,[0;0],t,p);
        obs=m600check.copterSimOutputs(x,d.actual_acceleration_mps2,[0;0],dx(11:13),mass);
        % Use an ideal host land-detector fixture.
        groundContact=logical(currentContact.contact_active);
        landed=logical(memory.ground_confirmed&&groundContact);maybeLanded=groundContact;
        want=logical(target(3)<obs.position_ned_m(3));
        ts=struct('source_timestamp_us',uint64(1000000+round(t*1e6)),'initial_dt_s',dt, ...
            'armed',true,'landed',landed,'want_takeoff',want,'skip_takeoff',false, ...
            'takeoff_desired_velocity_up_mps',pc.velocity_limits_mps(2));
        commands{stepIndex}.takeoff_input=ts;lastStage='NATIVE_TAKEOFF';to=takeoff('step',ts);
        commands{stepIndex}.takeoff_output=to;assert(~to.authority_granted);
        noCorrection=logical(to.not_taken_off||(to.flying&&groundContact));
        psp=target;vsp=zeros(3,1);asp=zeros(3,1);yaw=0;yawSpeed=0;
        if to.state_after==4,asp(3)=NaN;end % Original rampup removes vertical FF.
        if noCorrection
            psp=nan(3,1);vsp=nan(3,1);asp=[0;0;100];yaw=NaN;yawSpeed=NaN;
        end
        if to.flying,tiltTarget=module.MPC_TILTMAX_AIR;minimum=pc.thrust_limits(1);
        else,tiltTarget=module.MPC_TILTMAX_LND;minimum=0;end
        % Original SlewRate<float>::update, initial value 0, slew .2f.
        targetRad=single(tiltTarget)*(single(pi)/single(180));deltaMax=single(.2)*single(to.dt_s);
        tiltState=tiltState+min(max(targetRad-tiltState,-deltaMax),deltaMax);
        action='KEEP';if ~to.flying,action='SET';end
        runtimeCfg=struct('velocity_limits_mps',[pc.velocity_limits_mps(1); ...
            min(to.upward_velocity_limit_mps,pc.velocity_limits_mps(2));max(pc.velocity_limits_mps(3),0)], ...
            'thrust_limits',[minimum;pc.thrust_limits(2)],'tilt_limit_rad',double(tiltState), ...
            'hover_action',action,'hover_thrust',spec.hover_thrust,'reset_integral',noCorrection, ...
            'reset_integral_xy',logical((~isfinite(vsp(1))||~isfinite(vsp(2)))&&(~isfinite(psp(1))||~isfinite(psp(2)))));
        commands{stepIndex}.runtime_configuration=runtimeCfg;lastStage='NATIVE_RUNTIME_CONFIGURATION';
        rc=pos('configure_runtime',runtimeCfg);commands{stepIndex}.runtime_receipt=rc;
        assert(rc.configured&&~rc.authority_granted&&~rc.instance_reinitialized&&rc.source_clock_unchanged);
        velocity=single(obs.velocity_ned_mps);derivative=(velocity-previousVelocity)/df;
        accelFiltered=accelFiltered+alpha*(derivative-accelFiltered);previousVelocity=velocity;
        ps=struct('timestamp_sample_s',t,'dt_s',dt,'state_position_ned',obs.position_ned_m, ...
            'state_velocity_ned',double(velocity),'state_acceleration_ned',double(accelFiltered),'state_yaw',obs.euler_rpy_rad(3), ...
            'trajectory_position_ned',psp,'trajectory_velocity_ned',vsp,'trajectory_acceleration_ned',asp, ...
            'trajectory_yaw',yaw,'trajectory_yawspeed',yawSpeed,'vertical_i_gain',0, ...
            'terminal_negative_integral_update_inhibit',false);
        commands{stepIndex}.position_input=ps;lastStage='NATIVE_POSITION_STEP';po=pos('step',ps);
        commands{stepIndex}.position_output=po;assert(po.update_valid&&po.outputs_usable_for_host_numerical_chain&&~po.authority_granted);
        fs=struct('raw_gyro',obs.body_rate_frd_rad_s,'timestamp_sample_us',ts.source_timestamp_us);
        commands{stepIndex}.gyro_input=fs;lastStage='NATIVE_GYRO_FILTER';fo=sensor('step',fs);
        commands{stepIndex}.gyro_output=fo;assert(~fo.must_stop&&fo.source_progressed);
        ls=struct('timestamp_sample_s',1+t,'initial_dt_s',dt,'q_est',obs.quaternion_wxyz_body_to_ned, ...
            'q_reference',po.q_d,'body_rate',fo.rate_body,'angular_acceleration',fo.derivative_body, ...
            'thrust_body_normalized',po.thrust_body,'yaw_rate_ff',po.yawspeed_setpoint,'battery_scale',1, ...
            'armed',true,'rotary_wing',true,'landed',landed,'maybe_landed',maybeLanded, ...
            'rates_enabled',true,'attitude_updated',true);
        commands{stepIndex}.lower_input=ls;lastStage='NATIVE_ATTITUDE_RATE_ALLOCATOR';lo=low('step',ls);
        commands{stepIndex}.lower_output=lo;
        lastStage='ACTUATOR_SOURCE_QUANTIZATION_AND_PUBLICATION';
        [wire,wireReceipt]=sourcePwmSim(lo.motor_commands);
        mode=string(fixture.actuator_output.mode);
        publish=mode~="SOURCE_PWMSIM_QUANTIZED_50HZ_ZOH"||mod(stepIndex-1,2)==0;
        if mode=="RAW_ALLOCATOR_100HZ"
            % Feed the legacy numerical values directly into the 10 ms RK4 plant.
            heldActuator=lo.motor_commands;lastPublicationSourceTime=t;
        elseif publish
            heldActuator=wire;lastPublicationSourceTime=t;
        end
        sampleAge=t-lastPublicationSourceTime;
        commands{stepIndex}.actuator_output=struct('mode',char(mode),'zero_based_control_tick',stepIndex-1, ...
            'allocator_raw',lo.motor_commands,'quantized_current_candidate',wire, ...
            'published_this_tick',publish,'applied_held',heldActuator, ...
            'publication_source_time_s',lastPublicationSourceTime,'publication_sample_age_s',sampleAge, ...
            'source_arithmetic',wireReceipt,'control_rate_hz',100, ...
            'actuator_publication_rate_hz',fixture.actuator_output.publication_rate_hz);
        rawAllocator(stepIndex,:)=lo.motor_commands.';quantizedCommands(stepIndex,:)=wire.';
        appliedCommands(stepIndex,:)=heldActuator.';publicationUpdates(stepIndex)=publish;
        publicationSourceTimes(stepIndex)=lastPublicationSourceTime;publicationSampleAges(stepIndex)=sampleAge;
        controls=zeros(16,1);controls(1:6)=heldActuator;
        commands{stepIndex}.plant_controls=controls;commands{stepIndex}.plant_reference_jet=jet;
        commands{stepIndex}.pre_state_up=x;commands{stepIndex}.pre_step_contact=currentContact;
        commands{stepIndex}.ideal_land_detector_fixture=struct('landed',landed,'maybe_landed',maybeLanded, ...
            'ground_contact',groundContact,'memory_ground_confirmed',memory.ground_confirmed,'not_native_land_detector',true);
        lastStage='EXACT_M600_RK4';[next,diagnostic,contact,nextMemory,status]= ...
            m600check.stepPx4Rk4(x,controls,jet,payload,[0;0],t,p,memory);
        plantStatuses{stepIndex}=status;contacts{stepIndex}=contact;
        commands{stepIndex}.plant_diagnostic=diagnostic;commands{stepIndex}.post_memory=nextMemory;
        after=m600check.copterSimOutputs(next,[0;0;0],[0;0],[0;0;0],mass);
        rows=stepIndex;X(rows+1,:)=next.';error=obs.position_ned_m-target;
        R(rows,:)=[t,obs.position_ned_m.',error.',rad2deg(obs.euler_rpy_rad).',po.vertical_integral_z_after, ...
            lo.motor_commands.',po.thrust_body(3),lo.motor_saturated,lo.rate_limit_reached,lo.integral_limit_reached, ...
            contact.contact_active,status.accepted,po.dt_clamped,lo.dt_clamped,fo.native_dt_clamped, ...
            to.state_after,to.upward_velocity_limit_mps,double(tiltState),minimum,landed,maybeLanded, ...
            groundContact,noCorrection,lo.integral_updates_enabled,to.dt_clamped,po.velocity_setpoint_ned(3),spec.hover_thrust];
        commands{stepIndex}.stage='STEP_COMPLETE';
        if ~status.accepted,termination=sprintf('PLANT_REJECT_%d',status.failure_code);break;end
        x=next;memory=nextMemory;
        if max(abs(rad2deg(after.euler_rpy_rad(1:2))))>=fixture.diagnostic_stop_attitude_deg
            termination='PREDECLARED_ATTITUDE_DIAGNOSTIC_DOMAIN_EXIT';break;
        end
        if norm(after.position_ned_m-target)>=fixture.diagnostic_stop_position_error_m
            termination='PREDECLARED_POSITION_DIAGNOSTIC_DOMAIN_EXIT';break;
        end
    end
catch problem
    failure=getReport(problem,'extended','hyperlinks','off');termination='HOST_IMPLEMENTATION_OR_KERNEL_INPUT_INVALID';
    firstException=struct('stage',lastStage,'attempt_index',attempts,'time_s',max(0,attempts-1)*dt, ...
        'identifier',problem.identifier,'message',problem.message);
    if attempts>0,commands{attempts}.stage=lastStage;commands{attempts}.exception=firstException;end
end
cleanupErrors={};
for clearIndex=1:4
    try,handles{clearIndex}('clear');catch problem,cleanupErrors{end+1}=getReport(problem,'basic','hyperlinks','off');end %#ok<AGROW>
end
columns={'time_s','north_m','east_m','down_m','error_north_m','error_east_m','error_down_m', ...
    'roll_deg','pitch_deg','yaw_deg','vertical_integral_z','motor1','motor2','motor3','motor4','motor5','motor6', ...
    'body_thrust_z','motor_saturated','rate_limited','integral_limited','contact_active','plant_accepted', ...
    'position_dt_clamped','lower_dt_clamped','sensor_dt_clamped','takeoff_state','up_limit_mps','tilt_limit_rad', ...
    'minimum_thrust','ideal_landed','ideal_maybe_landed','ideal_ground_contact','native_no_corrections', ...
    'rate_integral_updates_enabled','takeoff_dt_clamped','velocity_setpoint_down_mps','hover_thrust'};
trace=array2table(R(1:rows,:),'VariableNames',columns);
for motorIndex=1:6
    trace.(sprintf('allocator_raw_motor%d',motorIndex))=rawAllocator(1:rows,motorIndex);
    trace.(sprintf('quantized_current_motor%d',motorIndex))=quantizedCommands(1:rows,motorIndex);
    trace.(sprintf('applied_motor%d',motorIndex))=appliedCommands(1:rows,motorIndex);
end
trace.actuator_publication_update=publicationUpdates(1:rows);
trace.actuator_publication_source_time_s=publicationSourceTimes(1:rows);
trace.actuator_sample_age_s=publicationSampleAges(1:rows);
lastAccepted=X(1,:).';if rows>0,lastAccepted=X(rows+1,:).';end
last=m600check.copterSimOutputs(lastAccepted,[0;0;0],[0;0],[0;0;0],mass);
errorAll=[R(1:rows,5:7);(last.position_ned_m-target).'];
angleAll=[R(1:rows,8:10);rad2deg(last.euler_rpy_rad).'];
result=struct('specification',spec,'completed_rows',rows,'attempted_rows',attempts, ...
    'termination',termination,'full_20s_diagnostic_window',rows==n&&strcmp(termination,'FULL_PREDECLARED_TAKEOFF_HOVER_WINDOW'), ...
    'native_FLIGHT_phase_entered',any(R(1:rows,27)==5),'first_native_FLIGHT_time_s',firstTime(R,rows,27,5), ...
    'first_model_liftoff_time_s',firstStatusTime(plantStatuses,rows,'liftoff_this_step',dt), ...
    'max_position_error_m',max(vecnorm(errorAll,2,2)),'max_attitude_deg',max(abs(angleAll),[],1), ...
    'final_position_ned_m',last.position_ned_m,'final_position_error_ned_m',last.position_ned_m-target, ...
    'final_position_error_m',norm(last.position_ned_m-target),'final_attitude_deg',rad2deg(last.euler_rpy_rad), ...
    'motor_saturated_rows',nnz(R(1:rows,19)),'rate_limited_rows',nnz(R(1:rows,20)), ...
    'integral_limited_rows',nnz(R(1:rows,21)),'rate_I_update_rows',nnz(R(1:rows,35)), ...
    'all_recorded_vertical_I_gain_zero',true,'max_abs_vertical_integral_z',max([0;abs(R(1:rows,11))]), ...
    'plant_rejected_rows',nnz(R(1:rows,23)==0),'dt_clamped_rows',nnz(any(R(1:rows,[24:26,36]),2)), ...
    'accepted_states_finite',all(isfinite(X(1:rows+1,:)),'all'), ...
    'first_exception',firstException,'failure',failure,'kernel_cleanup_errors',{cleanupErrors}, ...
    'candidate_endpoint_preserved_in_plant_status',true,'live_admission',false,'landing_tested',false);
result.actuator_output=struct('mode',fixture.actuator_output.mode,'control_rate_hz',100, ...
    'publication_rate_hz',fixture.actuator_output.publication_rate_hz, ...
    'completed_publication_updates',nnz(publicationUpdates(1:rows)), ...
    'completed_hold_rows',nnz(~publicationUpdates(1:rows)), ...
    'max_sample_age_s',max([0;publicationSampleAges(1:rows)]), ...
    'max_current_quantization_delta',max([0;max(abs(rawAllocator(1:rows,:)-quantizedCommands(1:rows,:)),[],'all')]), ...
    'max_raw_to_applied_delta',max([0;max(abs(rawAllocator(1:rows,:)-appliedCommands(1:rows,:)),[],'all')]), ...
    'legacy_motor_columns_are_raw_allocator_not_applied',true);
data=struct('trace',trace,'states_up',X(1:rows+1,:),'commands',{commands(1:attempts)}, ...
    'plant_statuses',{plantStatuses(1:rows)},'contacts',{contacts(1:rows)},'result',result, ...
    'position_configuration',positionCfg,'lower_configuration',lowerCfg,'takeoff_configuration',takeoffCfg, ...
    'init_receipts',{initReceipts},'velocity_D_alpha_REAL32',alpha,'last_committed_plant_memory',memory, ...
    'raw_allocator_commands',rawAllocator(1:attempts,:), ...
    'quantized_current_commands',quantizedCommands(1:attempts,:), ...
    'applied_held_commands',appliedCommands(1:attempts,:), ...
    'publication_update',publicationUpdates(1:attempts), ...
    'publication_source_time_s',publicationSourceTimes(1:attempts), ...
    'publication_sample_age_s',publicationSampleAges(1:attempts));
end

function [c,sources]=actuatorFixtureContract(mode,build,positionMeta)
px4=string(gpenmpc_external_path('px4_source_root'));
relative=["src/lib/mixer_module/functions/FunctionMotors.hpp"; ...
    "src/lib/mixer_module/mixer_module.cpp";"src/lib/mathlib/math/Functions.hpp"; ...
    "src/modules/simulation/pwm_out_sim/PWMSim.cpp";"src/modules/simulation/pwm_out_sim/PWMSim.hpp"];
hashes=["BE4E6AAA363BC49A5B63CC5683E6CDB805494955431D250F3023EE70C9F8628A"; ...
    "D8140B57E6367EA35F7BBD24BA419DD766432F796177199A10BAFD2107929CBE"; ...
    "D45D4FA2CA6EF30615C32167A689B4B94C518802CD3C8F3B6E1CF252A13F5079"; ...
    "063581499B667055E31CE4B271EFF578F6D717D37BD4BF14E6930C3A543090B5"; ...
    "99BCF9C7F82D52625D386EE511618FF7A060A19CDFEBB0F260E0EF3D53FACB71"];
sources=struct('path',{},'bytes',{},'sha256',{});
for sourceIndex=1:numel(relative)
    current=identity(fullfile(px4,relative(sourceIndex)));
    assert(string(current.sha256)==hashes(sourceIndex),'gpenmpc:ActuatorArithmeticSourceChanged');
    sources(end+1)=current; %#ok<AGROW>
end
rawId=identity(positionMeta.current138_raw.path);assert(isequal(rawId,positionMeta.current138_raw));
raw=jsondecode(fileread(rawId.path));rows=raw.diagnostic_parameter_observations;
at=find(strcmp({rows.name},'THR_MDL_FAC'));assert(isscalar(at));q=rows(at);
assert(isempty(q.read_error)&&q.write_count==0&&strcmp(q.typed_value.name,'THR_MDL_FAC') ...
    &&q.typed_value.mav_type==9&&strcmpi(q.typed_value.raw_bits_hex,'00000000') ...
    &&q.typed_value.decoded==0,'gpenmpc:ActuatorThrustCurveMismatch');
observationFile=fullfile(gpenmpc_external_path('native_hover_oscillation_fixture'),'SUMMARY.json');
observationId=identity(observationFile);
assert(strcmp(observationId.sha256,'8463A29BF52ABCA7E6CE15C75DDE6DA004F364F9C23C52ECABA305E2D8A14E0B'));
observation=jsondecode(fileread(observationFile));
% Normalize the schema label at the retained observation boundary.
if strcmp(observation.schema,'HOST_NATIVE_HOVER_004_OSCILLATION_AND_RATE_SCOPE_V1')
    observation.schema='HOST_NATIVE_HOVER_OSCILLATION_AND_RATE_SCOPE_V1';
end
assert(strcmp(observation.schema,'HOST_NATIVE_HOVER_OSCILLATION_AND_RATE_SCOPE_V1'));
sources(end+1)=observationId;sources(end+1)=rawId;
publicationHz=100;if mode=="SOURCE_PWMSIM_QUANTIZED_50HZ_ZOH",publicationHz=50;end
c=struct('mode',char(mode),'control_rate_hz',100,'plant_rate_hz',100, ...
    'publication_rate_hz',publicationHz,'quantization_applied',mode~="RAW_ALLOCATOR_100HZ", ...
    'initial_applied_commands',zeros(6,1),'initial_publication_source_time','UNSET until t0 sample', ...
    'sample_schedule','Zero-based even control ticks t=0,0.02,... for50Hz; every tick for100Hz; held values drive next10ms RK4.', ...
    'arithmetic','float FunctionMotors u*2-1 -> float interpolate500*x+1500 -> lroundf -> uint16 -> float (PWM-1000)/1000', ...
    'THR_MDL_FAC_typed',q.typed_value,'source_bindings',sources(1:5), ...
    'nonreversible_motor_fixture',true,'output_limit_ON_fixture',true, ...
    'output_reverse_mask_fixture',0,'no_additional_idle_floor',true,'PWMSim_output_ramp_enabled',false, ...
    'finite_allocator_domain','Inputs must be finite and within 0..1; invalid values fail the case.', ...
    'not_reconstructed',{{'uORB/mixer scheduling','actuator_armed/lockdown state transitions','800Hz rate loop','actual sensor/transport delay'}}, ...
    'rate_choice_source',observationId,'observed_animation_changes',observation.observed_animation_input_changes, ...
    'observed_scope',observation.animation_scope, ...
    'rate_choice_interpretation','Recorded animation input changes near 49.7 Hz motivate the 50 Hz HOST sensitivity fixture.', ...
    'raw_mode_interpretation','Continuous allocator kernel output at100Hz, not exact actuator_outputs_sim wire.', ...
    'case_count_unchanged',3,'selection_or_threshold_changes',0,'hardware_actions',0);
end

function [wire,receipt]=sourcePwmSim(raw)
assert(isequal(size(raw),[6,1])&&all(isfinite(raw))&&all(raw>=0&raw<=1), ...
    'gpenmpc:BadAllocatorMotorValue');
% Match float rounding points in the THR_MDL_FAC=0 nonreversible branch.
u=single(raw);scaled=single(u.*single(2));motorFunction=single(scaled-single(1));
a=single(single(2000-1000)/single(1-(-1)));
b=single(single(1000)-single(a*single(-1)));
product=single(a.*motorFunction);interpolated=single(product+b);
interpolated(motorFunction<=single(-1))=single(1000);
interpolated(motorFunction>single(1))=single(2000);
% All values1000..2000 are positive. floor(double(float)+.5) is exactly
% C++ lroundf ties-away-from-zero on this declared domain, including .5.
rounded=floor(double(interpolated)+.5);pwm=uint16(min(max(rounded,0),65535));
scaledOutput=single(single(pwm)-single(1000));wireSingle=single(scaledOutput/single(1000));
wire=double(wireSingle);assert(all(wire>=0&wire<=1)&&all(isfinite(wire)));
receipt=struct('allocator_REAL32',u,'motor_function_minus1_to1_REAL32',motorFunction, ...
    'interpolated_pwm_REAL32',interpolated,'lroundf_integer',rounded,'pwm_uint16',pwm, ...
    'wire_REAL32',wireSingle,'thrust_factor',0,'motor_reversible',false,'idle_added',false);
end

function r=verifyBuild(binary,receiptPath,expected)
id=identity(binary);receipt=jsondecode(fileread(receiptPath));assert(isequal(id,receipt.binary));
if strlength(expected)>0,assert(string(id.sha256)==expected,'gpenmpc:UnexpectedKernelBinary');end
if isfield(receipt,'passed'),assert(receipt.passed);else,assert(startsWith(string(receipt.status),'PASS_'));end
assert(receipt.hardware_actions==0);
[~,binaryName]=fileparts(binary);
switch string(binaryName)
    case "gpenmpc_px4_native_lower_loop_mex"
        assert(receipt.com_open==0&&receipt.simulation_runs==0&&~receipt.closed_loop_performance_pass);
    case "gpenmpc_px4_sensor_filter_mex"
        assert(receipt.COM_actions==0);
    otherwise
        assert(receipt.COM_UDP_actions==0&&~receipt.flight_admission);
end
% Verify source and compatibility bindings before execution.
for bindingIndex=1:numel(receipt.bindings)
    assert(isequal(identity(receipt.bindings(bindingIndex).path),receipt.bindings(bindingIndex)), ...
        'gpenmpc:KernelBuildSourceChanged','%s',receipt.bindings(bindingIndex).path);
end
r=struct('binary',id,'build_receipt',identity(receiptPath),'bound_input_count',numel(receipt.bindings));
end
function ok=checkSources(s)
ok=true;for sourceIndex=1:numel(s),ok=ok&&isequal(identity(s(sourceIndex).path),s(sourceIndex));end
end
function t=firstTime(r,n,column,value)
at=find(r(1:n,column)==value,1);if isempty(at),t=NaN;else,t=r(at,1);end
end
function t=firstStatusTime(status,n,field,dt)
t=NaN;for statusIndex=1:n,if status{statusIndex}.(field),t=statusIndex*dt;return;end,end
end
function finish(handles,capturedPath)
for clearIndex=1:numel(handles),try,handles{clearIndex}('clear');catch,end,end
path(capturedPath);
end
function b=raw32(v),b=upper(dec2hex(typecast(single(v),'uint32'),8));end
function writeJson(file,value)
f=fopen(file,'w','n','UTF-8');assert(f>=0);g=onCleanup(@()fclose(f)); %#ok<NASGU>
fprintf(f,'%s\n',jsonencode(encodeNonfinite(value),PrettyPrint=true));
end
function value=encodeNonfinite(value)
if isnumeric(value)&&any(~isfinite(value(:)))
    value=struct('numeric_encoding','MATLAB_IEEE754_HEX_V1','matlab_class',class(value), ...
        'shape',size(value),'column_major_hex',{cellstr(num2hex(value(:)))});
elseif isstruct(value)
    fields=fieldnames(value);
    for itemIndex=1:numel(value),for fieldIndex=1:numel(fields),value(itemIndex).(fields{fieldIndex})=encodeNonfinite(value(itemIndex).(fields{fieldIndex}));end,end
elseif iscell(value)
    for itemIndex=1:numel(value),value{itemIndex}=encodeNonfinite(value{itemIndex});end
end
end
function id=identity(file)
f=fopen(file,'rb');assert(f>=0,'gpenmpc:MissingInput','%s',file);g=onCleanup(@()fclose(f)); %#ok<NASGU>
b=fread(f,Inf,'*uint8');h=java.security.MessageDigest.getInstance('SHA-256');h.update(b);
id=struct('path',char(file),'bytes',numel(b),'sha256',upper(reshape(dec2hex(typecast(h.digest(),'uint8'),2).',1,[])));
end
