function receipt = run_readonly_hil_profile(outputPath)
% RUN_READONLY_HIL_PROFILE Read HIL and physical-output guard parameters.

if nargin < 1
    outputPath = fullfile(fileparts(fileparts(mfilename('fullpath'))), ...
        'evidence', 'CURRENT_HIL_PROFILE_READONLY.json');
end

root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(root, 'host_runtime'), '-begin');
rehash path;

names = ["SYS_HITL", "SYS_AUTOSTART", "MAV_TYPE", "CA_ROTOR_COUNT", ...
    "RA_CTRL_MODE", compose("HIL_ACT_FUNC%d", 1:16), ...
    compose("PWM_MAIN_FUNC%d", 1:8)];

link = gpenmpcNative.MavlinkSerialLink;
linkCleanup = onCleanup(@()link.close()); %#ok<NASGU>
heartbeat = link.open("COM3", 921600, 15);
identity = link.collectIdentity(10);

parameters = repmat(struct('name', "", 'mav_type', NaN, ...
    'raw_float', NaN, 'raw_bits_hex', "", 'decoded', NaN), ...
    numel(names), 1);
for index = 1:numel(names)
    parameters(index) = link.requestParam(names(index), 3.0);
end

version = identity.autopilot_version;
extended = identity.extended_sys_state;
receipt = struct( ...
    'schema', 'GPENMPC_READONLY_HIL_PROFILE_V1', ...
    'uid', sprintf('%u', version.uid), ...
    'board_version', double(version.board_version), ...
    'commit', identity.parsed_commit, ...
    'hw_arch', identity.parsed_hw_arch, ...
    'armed', bitand(uint8(heartbeat.Payload.base_mode), uint8(128)) ~= 0, ...
    'landed_state', double(extended.landed_state), ...
    'parameters', parameters, ...
    'link_counters', link.counters(), ...
    'parameter_writes', 0, ...
    'mode_requests', 0, ...
    'arm_requests', 0, ...
    'physical_outputs', 0);

link.close();
folder = fileparts(outputPath);
if ~isfolder(folder), mkdir(folder); end
temporary = outputPath + ".tmp";
fid = fopen(temporary, 'w', 'n', 'UTF-8');
assert(fid >= 0, 'gpenmpcNative:HilProfileReceiptOpen', ...
    'Cannot open HIL profile receipt.');
fileCleanup = onCleanup(@()fclose(fid));
fprintf(fid, '%s\n', jsonencode(receipt, PrettyPrint=true));
clear fileCleanup
movefile(temporary, outputPath, 'f');
disp(jsonencode(receipt, PrettyPrint=true));
end
