function report=test_rfly_udp_clock_startup_placeholder()
% Test startup clock handling with three UDP inputs.
build=fileparts(fileparts(mfilename('fullpath')));
target=fullfile(build,'tools','UDP_CLOCK_STARTUP_PLACEHOLDER_HOST_ONLY.mat');
assert(~isfile(target),'gpenmpcHost:ExistingEvidence','Choose an unused output path.');
addpath(fullfile(build,'tools'),fullfile(build,'host_runtime'),fullfile(build,'matlab_validation'),fullfile(build,'m600_coptersim','matlab_validation'));
addpath(gpenmpc_external_path('native_visual_host_source'),'-end');
q=load(gpenmpc_external_path('udp_loopback_fixture'),'cfg');cfg=q.cfg;
assert(strcmp(cfg.mavlink_transport.scope,'HOST_ONLY_LOOPBACK')&& ...
    cfg.local_mavlink_port==62291&&cfg.remote_mavlink_port==62292&& ...
    cfg.coptersim_time_port==62294,'gpenmpcHost:Ports','Only the retained isolated HOST endpoints are allowed.');
addpath(fileparts(cfg.mavlink_transport.source.exact_path));
ioPath=which('m600check.makeM600CopterSimIo');classPath=which('gpenmpcNative.RflySoleMavlinkTransport');
sourceBefore={m600check.fileSha256(ioPath),m600check.fileSha256(classPath)};
io=[];peer=[];raw=struct();checks=struct();guard=onCleanup(@finish);
try
    io=m600check.makeM600CopterSimIo(cfg);
    peer=udpport('datagram','IPV4','LocalHost','127.0.0.1','LocalPort',62297);
    placeholder=packet(int64([-1 -1 0]));
    write(peer,placeholder,'uint8','127.0.0.1',62294);pause(.02);
    s=io.snapshot();e=io.evidence();n=gpenmpc_rfly_udp_transport_mex('status');
    raw.prestart=struct('snapshot',s,'io',e,'native',n,'sent_time_datagram',placeholder);
    checks.prestart_placeholder_is_not_clock_evidence=~s.clock_valid&&isempty(s.fatal)&& ...
        isnan(e.coptersim_start_utc_s)&&e.time_startup_uninitialized_count==1&& ...
        numel(e.raw_clock_datagrams)==1&& ...
        strcmp(e.raw_clock_datagrams{1}.classification,'PRESTART_UNINITIALIZED_TIME__NOT_CLOCK_EVIDENCE')&& ...
        isequal(uint8(e.raw_clock_datagrams{1}.bytes(:)),placeholder(:))&& ...
        n.sent_count==0&&~n.failed;
    assert(checks.prestart_placeholder_is_not_clock_evidence,'gpenmpcHost:PlaceholderInstalled', ...
        'Startup placeholder must be retained without an origin, fatal or automatic TX.');
    nowMs=int64(floor(posixtime(datetime('now','TimeZone','UTC'))*1000));
    valid=packet([nowMs nowMs int64(1)]);
    write(peer,valid,'uint8','127.0.0.1',62294);pause(.02);
    s=io.snapshot();e=io.evidence();n=gpenmpc_rfly_udp_transport_mex('status');
    raw.valid=struct('snapshot',s,'io',e,'native',n,'sent_time_datagram',valid,'epoch_ms',nowMs);
    checks.valid_epoch_installs_exact_origin_without_claiming_sync= ...
        e.coptersim_start_utc_s==double(nowMs)/1000&& ...
        s.clock_diagnostic.time_heartbeat_current_utc_s==double(nowMs)/1000&& ...
        s.clock_diagnostic.time_heartbeat_counter==1&& ...
        ~e.clock_origin_changed&&isempty(s.fatal)&&~s.clock_valid&& ...
        ~s.clock_diagnostic.sync_locked&&numel(e.raw_clock_datagrams)==2&& ...
        isequal(uint8(e.raw_clock_datagrams{2}.bytes(:)),valid(:))&&n.sent_count==0&&~n.failed;
    assert(checks.valid_epoch_installs_exact_origin_without_claiming_sync,'gpenmpcHost:ValidOrigin', ...
        'The valid epoch must be installed byte-faithfully; no TIMESYNC lock is supplied by this fixture.');
    write(peer,placeholder,'uint8','127.0.0.1',62294);pause(.02);
    s=io.snapshot();e=io.evidence();n=gpenmpc_rfly_udp_transport_mex('status');
    raw.after_origin=struct('snapshot',s,'io',e,'native',n,'sent_time_datagram',placeholder);
    checks.post_origin_placeholder_fatal_without_rebase= ...
        strcmp(s.fatal,'COPTERSIM_RUNNING_CLOCK_BECAME_UNINITIALIZED')&& ...
        ~s.clock_valid&&e.coptersim_start_utc_s==double(nowMs)/1000&& ...
        s.clock_diagnostic.time_heartbeat_current_utc_s==double(nowMs)/1000&& ...
        s.clock_diagnostic.time_heartbeat_counter==1&&~e.clock_origin_changed&& ...
        e.time_startup_uninitialized_count==1&&numel(e.raw_clock_datagrams)==3&& ...
        isequal(uint8(e.raw_clock_datagrams{3}.bytes(:)),placeholder(:))&&n.sent_count==0&&~n.failed;
    assert(checks.post_origin_placeholder_fatal_without_rebase,'gpenmpcHost:RuntimeReset', ...
        'The later placeholder must latch clock failure without replacing the established origin.');
    assert(isequal(sourceBefore,{m600check.fileSha256(ioPath),m600check.fileSha256(classPath)}), ...
        'gpenmpcHost:ConcurrentSourceChange','Production sources changed during this fixture.');
    report=struct('scope','HOST_ONLY_PRODUCTION_IO_THREE_TIME_UDP_INPUTS','pass',all(structfun(@logical,checks)), ...
        'checks',checks,'input_datagrams',3,'source_unchanged_during_test',true, ...
        'io_source_sha256',sourceBefore{1},'transport_class_sha256',sourceBefore{2}, ...
        'mex_sha256',cfg.mavlink_transport.source.sha256,'COM',0,'CopterSim',0,'board',0,'HIL',0,'control_commands',0);
    clear guard
    save(target,'raw','report','cfg');disp(jsonencode(report));
catch ex
    failure=struct('identifier',ex.identifier,'message',ex.message,'stack',ex.stack);
    if ~isempty(io),try,raw.failure_io=io.evidence();catch,end,end
    clear guard
    save(target,'raw','checks','cfg','failure');rethrow(ex)
end
    function bytes=packet(values)
        bytes=[typecast(int32([123456789 cfg.target_system]),'uint8'),typecast(int64(values),'uint8')];
        assert(numel(bytes)==32,'gpenmpcHost:TimePacketLength','Official time packet length must be 32 bytes.');
    end
    function finish()
        if ~isempty(io),try,io.close();catch,end;io=[];end
        if ~isempty(peer),delete(peer);peer=[];end
    end
end
