function result=test_make_plant_environment_frame_from_snapshot()
root=fileparts(fileparts(mfilename('fullpath')));addpath(fullfile(root,'matlab_validation'));
r=struct('position_ned_m',[1 2 -3],'velocity_ned_mps',[.1 .2 .3], ...
    'acceleration_ned_mps2',[.4 .5 .6],'jerk_ned_mps3',[.7 .8 .9], ...
    'estimated_wind_ned_mps',[2 -1 0]);
s=struct('now_s',12,'heartbeat_rx_s',11.9,'extended_rx_s',11.8, ...
    'armed',0,'landed_state',1,'clock_valid',true, ...
    'delivery_board_continuity_epoch',3, ...
    'model_diagnostic',struct('decoded',struct('sim_time_s',8)));
v=gpenmpcTaskIo.makePlantEnvironmentFrameFromSnapshot( ...
    s,r,1.75,1,1,22,12.5,true,"SERVICE_GROUNDED_DISARMED",26090501,true,true,true);
[bytes,f]=gpenmpcTaskIo.encodePlantEnvironmentV2(v,1,2.21);
checks=struct('bytes232',numel(bytes)==232,'phase5',f(8)==5, ...
    'jet_exact',isequal(f(9:20),[1;2;-3;.1;.2;.3;.4;.5;.6;.7;.8;.9]), ...
    'ground_flags15',f(25)==15,'board_time_mapped',abs(f(24)-7.8)<1e-12, ...
    'payload_release',f(5)==1.75&&f(21)==1&&f(28)==1, ...
    'continuity',f(27)==3);
s.armed=1;s.landed_state=2;
v2=gpenmpcTaskIo.makePlantEnvironmentFrameFromSnapshot( ...
    s,r,1.75,1,1,23,12.6,false,"TRANSIT",26090501,true,true,true);
[~,f2]=gpenmpcTaskIo.encodePlantEnvironmentV2(v2,1,2.21);
checks.flight_flags31=f2(25)==31&&f2(26)==2&&f2(8)==2;
v3=gpenmpcTaskIo.makePlantEnvironmentFrameFromSnapshot( ...
    s,r,1.75,1,1,24,12.7,false,"TRANSIT",26090501,true,false,true);
[~,f3]=gpenmpcTaskIo.encodePlantEnvironmentV2(v3,1,2.21);
checks.stale_heartbeat_not_reported_fresh=bitand(uint32(f3(25)),uint32(1))==0&& ...
    bitand(uint32(f3(25)),uint32(2))==uint32(2);
s.landed_state=4;
landing=gpenmpcTaskIo.makePlantEnvironmentFrameFromSnapshot( ...
    s,r,1.75,1,1,25,12.8,false,"NATIVE_LAND",26090501,true,true,true);
[~,fl]=gpenmpcTaskIo.encodePlantEnvironmentV2(landing,1,2.21);
checks.actual_landing_enum_preserved=landing.observed_mavlink_landed_state==4&&s.landed_state==4;
checks.landing_is_model_non_ground=fl(26)==2&&fl(8)==4&&fl(25)==31;
for invalid=[5,NaN]
    b=s;b.landed_state=invalid;rejected=false;
    try,gpenmpcTaskIo.makePlantEnvironmentFrameFromSnapshot( ...
        b,r,1.75,1,1,25,12.8,false,"NATIVE_LAND",26090501,true,true,true);
    catch ex,rejected=strcmp(ex.identifier,'gpenmpcTaskIo:BoardStateInvalid');end
    if isnan(invalid),checks.nan_landed_rejected=rejected;
    else,checks.unknown_landed_rejected=rejected;end
end
bad=s;bad.model_diagnostic.decoded=rmfield(bad.model_diagnostic.decoded,'sim_time_s');
failed=false;try,gpenmpcTaskIo.makePlantEnvironmentFrameFromSnapshot( ...
    bad,r,1.75,1,1,25,12.8,false,"TRANSIT",26090501,true,true,true);catch,failed=true;end
checks.missing_model_clock_fails_closed=failed;
result=struct('status','PASS_HOST_ONLY_PLANT_ENVIRONMENT_SNAPSHOT_BINDING', ...
    'passed',all(structfun(@logical,checks)),'checks',checks, ...
    'checks_passed',nnz(structfun(@logical,checks)), ...
    'checks_total',numel(fieldnames(checks)),'hardware_actions',0,'com_open',0);
assert(result.passed,'gpenmpcTaskIo:SnapshotFrameTest');
fprintf('PLANT_ENVIRONMENT_SNAPSHOT_BINDING %d/%d\n',result.checks_passed,result.checks_total);
end
