function report=test_canonical_outer_lifecycle(outputRoot)
% Test synchronous and asynchronous outer solvers with synthetic observations.
arguments
    outputRoot (1,1) string
end
build=string(fileparts(fileparts(mfilename('fullpath'))));
parent=string(gpenmpc_external_path('native_visual_host_runtime'));
old=path;pc=onCleanup(@()path(old)); %#ok<NASGU>
addpath(fullfile(parent,'src'),'-begin');addpath(fullfile(build,'host_runtime'),'-begin');
assert(~isfolder(outputRoot),'Keep prior evidence.');mkdir(outputRoot);
checks=struct('name',{},'pass',{});raw=struct();
e=struct('uid','1234605616436508552','system_id',1,'component_id',1, ...
    'boot_generation',7,'maximum_age_ns',1e8,'maximum_runtime_age_ns',1e8, ...
    'canonical_package_root',gpenmpcNative.canonicalAssetRoot(),'initial_payload_kg',2.27, ...
    'async_outer_required',true,'task_identity_sha256',repmat('C',1,64));
coeff=zeros(3,8);coeff(:,1)=[0;0;2];coeff(:,2)=[.1;0;0];
tr=struct('total_duration_s',10,'coefficients_ascending',coeff);
s=gpenmpcNative.BoardOuterService(build,e,tr);sc=onCleanup(@()s.close()); %#ok<NASGU>
t=2e9;rotor=ones(6,1)*20;
r=s.outerRuntime(10,t,rotor,ones(6,1),zeros(2,1),2.27);
raw.prepare=s.prepare(t,sample(e,10,t),r);
check('preparation_real_solver_no_publication',raw.prepare.status=="PASS_HOST_PREPARATION" ...
    &&~raw.prepare.command_committed&&~s.status().fresh_outer_for_current_leg);
previous=raw.prepare.input_boundary;
r=s.outerRuntime(11,t,rotor,ones(6,1),zeros(2,1),2.27);
r.wind=previous.wind_observation;
raw.first=s.update(uint64(1),t,sample(e,11,t),r);
check('production_outer_accepts_original_fresh_held_wind', ...
    raw.first.disposition=="FRESH_SOLVER_RESULT" ...
    &&isequaln(raw.first.input_boundary.wind_observation,previous.wind_observation));
check('held_wind_does_not_fabricate_new_generation_or_rx', ...
    raw.first.input_boundary.wind_generation==10 ...
    &&raw.first.input_boundary.wind_rx_ns==previous.wind_rx_ns);
check('actual_first_solver_has_current_r2_r3_evidence', ...
    raw.first.solver_audit.coordinated_single_supervisor ...
    &&isfield(raw.first,'continuity_event')&&s.status().fresh_outer_for_current_leg);
current=raw.first.input_boundary;
[yes,~,d]=gpenmpcNative.validateOuterObservationAdvance(previous,current);
check('held_wind_receipt_explicit',yes&&d.wind_held&&~d.source_stamps_rewritten);
bad=current;bad.wind_observation.rx_ns=bad.wind_rx_ns+1;bad.wind_rx_ns=bad.wind_rx_ns+1;
negative('held_wind_cannot_renew_rx',bad,'HELD_WIND_OBSERVATION_MUTATED');
bad=current;bad.wind_observation.estimate_xy_mps=[.1;0];
negative('held_wind_cannot_change_value',bad,'HELD_WIND_OBSERVATION_MUTATED');
bad=current;bad.wind_generation=9;bad.wind_observation.generation=9;
negative('wind_generation_reversal_rejected',bad,'REVERSED_WIND_OBSERVATION_GENERATION');
bad=current;bad.estimate_generations=previous.estimate_generations;
negative('estimate_cannot_be_reused_as_new',bad,'NONADVANCING_CAUSAL_INPUT_GENERATION');
bad=current;bad.virtual_actuator_generation=previous.virtual_actuator_generation;
negative('rotor_observation_cannot_be_reused_as_new',bad,'NONADVANCING_CAUSAL_INPUT_GENERATION');
bad=current;bad.outer_runtime_generation=previous.outer_runtime_generation;
negative('causal_runtime_cannot_be_reused_as_new',bad,'NONADVANCING_CAUSAL_INPUT_GENERATION');
bad=current;bad.estimate_rx_ns=previous.estimate_rx_ns-1;
negative('advancing_generation_cannot_hide_reversed_time',bad,'REVERSED_CAUSAL_INPUT_RECEIVE_TIME');

pr=physicalInput(e,12,t,rotor);
raw.begin=s.stepPhysicalReference(uint64(1),t,sample(e,12,t),pr,.01);
check('physical_fixture_opens_one_sample',raw.begin.accepted);
check('suspension_cannot_abandon_open_control_sample',rejects(@() ...
    s.suspendOuterForLifecycle('NATIVE_LAND',t),'gpenmpcNative:LifecycleOpenControlSample'));
raw.commit=s.commitV7PhysicalControl(uint64(1),t,moduleGuard(t),actuator(t));
check('fixture_control_closed_before_land_boundary',raw.commit.accepted);
r=s.outerRuntime(13,t+1e7,rotor,ones(6,1),zeros(2,1),2.27);
raw.submit=s.submitUpdate(uint64(2),t+1e7,sample(e,13,t+1e7),r);
check('second_actual_solver_inflight',raw.submit.status=="SUBMITTED"&&s.status().async_in_flight);
check('synchronous_solver_cannot_race_existing_worker',rejects(@() ...
    s.update(uint64(2),t+1e7,sample(e,13,t+1e7),r),'gpenmpcNative:BoardOuterAsyncBusy'));
check('external_expiry_cannot_double_account_inflight_generation',rejects(@() ...
    s.expire(uint64(2),'EXTERNAL_TIMEOUT'),'gpenmpcNative:BoardOuterAsyncBusy'));
before=s.status();raw.suspend=s.suspendOuterForLifecycle('NATIVE_LAND',t+1e7);
raw.repeat=s.suspendOuterForLifecycle('NATIVE_LAND',t+1e7);
check('land_suspension_freezes_phase_and_publication',s.status().outer_suspended ...
    &&~s.status().publication_allowed&&s.status().phase_s==before.phase_s);
check('suspension_idempotent_and_submitted_generation_accounted', ...
    raw.repeat.already_suspended&&s.status().lifecycle_suspend_count==1 ...
    &&s.status().last_generation==2);
check('no_new_solver_during_land',rejects(@()s.submitUpdate(uint64(3),t+1e7, ...
    sample(e,13,t+1e7),r),'gpenmpcNative:OuterLifecycleSuspended'));
check('no_physical_reference_during_land',rejects(@()s.stepPhysicalReference(uint64(2), ...
    t+1e7,sample(e,13,t+1e7),pr,.01),'gpenmpcNative:OuterLifecycleSuspended'));
timer=tic;raw.drain={};
while s.status().async_in_flight&&toc(timer)<5
    raw.drain{end+1}=s.pollUpdate(round(t+1e7+toc(timer)*1e9)); %#ok<AGROW>
    pause(.001);
end
check('same_worker_actual_result_drained_not_relaunched',~s.status().async_in_flight ...
    &&s.status().async_lifecycle_discarded==1&&s.status().async_submitted==1);
check('late_lifecycle_result_does_not_commit_or_change_warmstart_phase', ...
    s.status().accepted_solver_results==before.accepted_solver_results ...
    &&s.status().async_accepted==0&&s.status().phase_s==before.phase_s ...
    &&~s.status().publication_allowed&&~s.status().failed);
raw.leg=s.beginLeg(2,tr,1.5,true,false,t+2e7,sample(e,14,t+2e7));
check('ground_leg_transition_requires_new_outer_solution', ...
    s.status().leg_index==2&&~s.status().outer_suspended ...
    &&~s.status().fresh_outer_for_current_leg&&s.status().last_generation==2);
check('old_global_outer_count_cannot_admit_next_leg',rejects(@() ...
    s.stepPhysicalReference(uint64(2),t+2e7,sample(e,14,t+2e7),pr,.01), ...
    'gpenmpcNative:BoardPhysicalReferenceNotAdmitted'));
r=s.outerRuntime(14,t+2e7,rotor,ones(6,1),zeros(2,1),1.5);
raw.next=s.update(uint64(3),t+2e7,sample(e,14,t+2e7),r);
check('new_leg_actual_solver_can_reopen_only_current_leg', ...
    raw.next.disposition=="FRESH_SOLVER_RESULT"&&s.status().fresh_outer_for_current_leg ...
    &&raw.next.leg_index==2);
raw.final=s.status();
report=struct('status','PASS_HOST_ONLY_CANONICAL_OUTER_LIFECYCLE', ...
    'checks',checks,'test_count',numel(checks),'pass_count',sum([checks.pass]), ...
    'real_accepted_outer_results',raw.final.accepted_solver_results, ...
    'real_async_submitted',raw.final.async_submitted, ...
    'real_async_lifecycle_discarded',raw.final.async_lifecycle_discarded, ...
    'synthetic_feedback_commits',raw.final.physical_runtime.control_commit_count, ...
    'hardware_actions',0,'com_open',0,'sockets',0);
save(fullfile(outputRoot,'RAW.mat'),'raw','report','-v7.3');
fid=fopen(fullfile(outputRoot,'RESULT.json'),'w','n','UTF-8');assert(fid>=0);
fc=onCleanup(@()fclose(fid));fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));clear fc
clear sc;delete(s);clear s;clear pc
disp(jsonencode(report));
    function negative(name,b,reason)
        [ok,why]=gpenmpcNative.validateOuterObservationAdvance(previous,b);
        check(name,~ok&&why==string(reason));
    end
    function check(name,yes)
        checks(end+1)=struct('name',name,'pass',logical(yes)); %#ok<AGROW>
        if ~yes,save(fullfile(outputRoot,'FAILURE_RAW.mat'),'raw','checks');end
        assert(yes,'gpenmpcNative:OuterLifecycleTest','%s',name);
    end
end
function yes=rejects(f,id)
yes=false;try,f();catch ex,yes=strcmp(ex.identifier,id);end
end
function p=sample(e,g,t)
p=struct('source','PX4_EKF2_MAVLINK_ODOMETRY_331','atomic_estimate',true, ...
    'plant_truth_used',false,'uid',e.uid,'system_id',1,'component_id',1, ...
    'boot_generation',7,'sample_timestamp_ns',t,'odometry_reset_counter',2, ...
    'odometry_frame_id',1,'odometry_child_frame_id',1,'odometry_estimator_type',8, ...
    'position_ned_m',[0;0;-2],'velocity_ned_mps',zeros(3,1), ...
    'quaternion_wxyz_body_to_ned',[1;0;0;0],'omega_frd_rad_s',zeros(3,1), ...
    'position_rx_ns',t-1e5,'attitude_rx_ns',t-1e5,'rates_rx_ns',t-1e5, ...
    'position_generation',g,'attitude_generation',g,'rates_generation',g, ...
    'position_valid',true,'attitude_valid',true,'rates_valid',true);
end
function r=physicalInput(e,g,t,rotor)
stamp=@(src)struct('source',src,'rx_ns',t-1e5,'generation',g,'valid',true);
v=stamp('HOST_M600_VIRTUAL_ACTUATOR_INTERFACE');v.ordering='SOFTWARE_M600_ORDER';v.rotor_thrust_state_n=rotor;
w=stamp('FROZEN_TASK_WIND_ESTIMATOR');w.estimate_xy_mps=zeros(2,1);
r=struct('schema','GPENMPC_PHYSICAL_CAUSAL_RUNTIME_INPUT_V1', ...
    'task_identity_sha256',e.task_identity_sha256,'plant_truth_used',false, ...
    'virtual_actuator',v,'wind',w,'task',struct('source','FROZEN_GPENMPC_TASK_STATE', ...
    'payload_kg',2.27,'leg_index',1));
end
function g=moduleGuard(t)
g=struct('source','PX4_UORB_GPENMPC_SE3_CONTROL_STATUS','valid',true, ...
    'plant_truth_used',false,'rx_ns',t-1e5,'control_mode',1,'failure_reason',0, ...
    'active',true,'state_valid',true,'reference_fresh',true,'segment_fresh',true, ...
    'native_position_controller_disabled',true,'native_attitude_rate_allocator_enabled',true, ...
    'single_publisher_contract_pass',true);
end
function a=actuator(t)
a=struct('mavpackettype','HIL_ACTUATOR_CONTROLS','time_usec',t/1000, ...
    'controls',[ones(6,1)*.5;nan(10,1)],'src_system',1,'src_component',1, ...
    'rx_ns',t,'generation',1);
end
