function report=test_canonical_local_inner_precontrol(outputRoot)
% Replay 60 samples through precontrol numerics.
arguments
    outputRoot (1,1) string
end
build=string(fileparts(fileparts(mfilename('fullpath'))));
parent=string(gpenmpc_external_path('native_visual_host_runtime'));
old=path;pathGuard=onCleanup(@()path(old)); %#ok<NASGU>
addpath(fullfile(parent,'src'),'-begin');addpath(fullfile(build,'host_runtime'),'-begin');
assert(~isfolder(outputRoot),'Preserve prior evidence.');mkdir(outputRoot);
archivePath=fullfile(gpenmpc_external_path('canonical_full_inner_runtime'),'RAW.mat');
archive=load(archivePath,'raw','report');assert(numel(archive.raw.samples)==60);
a=gpenmpcNative.loadCanonicalAssets();
names={'robust','enmpc','calibration','profile','attitudeContinuity', ...
    'kernelParameters','prediction_context'};
n=struct();for j=1:numel(names),n.(names{j})=a.(names{j});end
assert(~isfield(n,'gp_model'));
expected=struct('uid','HOST_ONLY_SYNTHETIC_SAMPLE','system_id',1,'component_id',1, ...
    'boot_generation',7,'maximum_age_ns',1e8,'maximum_runtime_age_ns',1e8, ...
    'initial_payload_kg',2.27,'canonical_package_root',gpenmpcNative.canonicalAssetRoot(), ...
    'inner_control_contract','CANONICAL_FULL_SE3', ...
    'full_inner_evidence_scope','HOST_ONLY_KERNEL_EXECUTION');
task=repmat('C',1,64);
runtime=gpenmpcNative.CurrentPhysicalCausalRuntime(build,expected,task,a);
checks=struct('name',{},'pass',{});raw=cell(60,1);state=[];pending=struct();
max61=0;maxState=0;maxAug=0;maxPending=0;bit61=0;exactStates=0;
gpCalls=0;exactGpSplits=0;availableClosed=0;activePhysical=0;
% Test-only value inspection compares every original private numerical field;
% it does not modify the runtime, expose an API, or copy its IO/identity state.
oldWarn=warning('off','MATLAB:structOnObject');wg=onCleanup(@()warning(oldWarn)); %#ok<NASGU>
for k=1:60
    recorded=archive.raw.samples{k};cmd=recorded.begin.full_inner_command;
    % These lag values are the ORIGINAL explicit synthetic fixture values
    % from test_canonical_full_inner_runtime.observations, not plant truth.
    lag=ones(6,1)*20;
    input=struct('x13',cmd.state_up(1:13),'rotor_thrust_state_n',lag, ...
        'reference_up',cmd.reference_up,'payload_kg',cmd.payload_kg, ...
        'wind_estimate_xy_mps',cmd.wind_estimate_xy_mps,'dt_s',cmd.dt_s, ...
        'source_timestamp_ns',cmd.estimate_sample_timestamp_ns, ...
        'source_generation',cmd.generation,'leg_index',1,'new_leg',k==1);
    before=state;[candidate,out]=gpenmpcNative.canonicalLocalInnerPreControl(state,input,pending,n);
    assert(isequaln(before,state),'Pure precontrol mutated the committed value.');
    original61=[recorded.feedback.wrench_n_nm;recorded.feedback.rotor_command_n;recorded.feedback.diagnostic51];
    error61=max(abs(out.kernel_output61-original61));max61=max(max61,error61);
    bit61=bit61+double(isequal(typecast(out.kernel_output61,'uint64'),typecast(original61,'uint64')));
    augError=max(abs(out.augmentation_up_mps2-recorded.begin.physical_output.compensation_up_mps2));
    maxAug=max(maxAug,augError);
    check("archive_source_"+k,error61<=1e-10&&augError<=1e-12 ...
        &&maxDiff(out.closed_gp_evidence,recorded.begin.closed_gp_evidence)<=1e-12 ...
        &&maxDiff(out.attitude_command,cmd.attitude_command)<=1e-12 ...
        &&maxDiff(out.vertical_observer,recorded.begin.vertical_observer)<=1e-12);

    now=uint64(1e9+k*1e7);[px4,rt]=observations(k,now,lag);
    b=runtime.beginSample(uint64(k),now,px4,rt,cmd.reference_up,.01);
    assert(b.accepted,'%s',b.reason);original=struct(runtime);
    beginStateError=max(maxDiff(candidate.robust_state,original.PhysicalAdapterState.robust_state), ...
        maxDiff(candidate.attitude_continuity_state,original.AttitudeContinuityState));
    f=gpenmpcNative.executeCanonicalFullInnerKernelHost(b.full_inner_command,a,now+uint64(1e6));
    commit=runtime.commitControl(uint64(k),now+uint64(2e6),f);assert(commit.accepted);
    candidateBefore=candidate;
    [state,pendingScaffold,gpRequest,post]=gpenmpcNative.canonicalLocalInnerPostControl(candidate,out,n,~isempty(a.gp_model));
    assert(isequaln(candidate,candidateBefore),'Pure postcontrol mutated its candidate.');
    assert(~isfield(pendingScaffold,'prediction'));
    prediction=struct();
    if gpRequest.prediction_required
        prediction=gpenmpcSparseGpPredict(a.gp_model,gpRequest.features_f17);
        gpCalls=gpCalls+1;
    end
    split=gpenmpcNative.completeCanonicalCurrentGpPrediction(gpRequest,prediction);
    direct=gpenmpcPredictCurrentGpEvidence(input.x13(4:6),input.reference_up, ...
        input.wind_estimate_xy_mps,input.payload_kg,out.kernel_control_candidate.desired_force_projected_up_n, ...
        candidate.previous_rotor_command_n,candidate.residual_history_f_mps2, ...
        a.prediction_context,a.gp_model,logical(candidate.causal_valid),a.enmpc);
    exactGpSplits=exactGpSplits+double(isequaln(split,direct));
    pending=pendingScaffold;pending.prediction=split;
    original=struct(runtime);
    stateError=max([beginStateError,maxDiff(state.robust_state,original.PhysicalAdapterState.robust_state), ...
        maxDiff(state.residual_history_f_mps2,original.ResidualHistoryF), ...
        maxDiff(state.gp_agreement_weight_f,original.AgreementF), ...
        maxDiff(state.attitude_continuity_state,original.AttitudeContinuityState), ...
        maxDiff(state.previous_rotor_command_n,original.PreviousRotorCommandN), ...
        maxDiff(state.previous_desired_force_projected_up_n,original.PreviousDesiredForceProjectedN)]);
    pendingError=maxDiff(pending,original.Pending);
    maxState=max(maxState,stateError);maxPending=max(maxPending,pendingError);
    exactStates=exactStates+double(stateError==0&&pendingError==0);
    check("current_runtime_state_and_post_"+k,stateError<=1e-12&&pendingError<=1e-12 ...
        &&isequaln(split,direct)&&isequal(post.previous_rotor_command_n_for_prediction, ...
        candidate.previous_rotor_command_n)&&~split.prediction_sample_closed ...
        &&~split.observed_innovation_available);
    availableClosed=availableClosed+double(out.closed_gp_evidence.available);
    activePhysical=activePhysical+double(~out.physical_diagnostic.exact_b1_fallback);
    raw{k}=struct('input',input,'candidate',candidate,'precontrol',out, ...
        'postcontrol_state',state,'postcontrol_receipt',post,'pending',pending, ...
        'gp_request',gpRequest,'kernel61_error',error61,'state_error',stateError, ...
        'pending_error',pendingError);
end
check('no_model_in_local_numerics',~isfield(n,'gp_model')&&gpCalls==59&&exactGpSplits==60);
check('candidate_only_no_publication_or_early_innovation',all(cellfun(@(x) ...
    x.precontrol.candidate_only&&~x.precontrol.board_publication_authority ...
    &&~x.precontrol.current_gp_prediction_performed ...
    &&~x.postcontrol_receipt.board_consumption_proven ...
    &&x.postcontrol_receipt.publication_count==0&&x.postcontrol_receipt.hardware_actions==0,raw)));
% Source identity cannot be manufactured by changing an internal ordinal.
next=input;next.source_timestamp_ns=next.source_timestamp_ns+uint64(1e7);
next.source_generation=next.source_generation+uint64(1);next.new_leg=false;
[~,normal]=gpenmpcNative.canonicalLocalInnerPreControl(state,next,pending,n);
gap=next;gap.source_generation=gap.source_generation+uint64(17);
[gapState,gapOut]=gpenmpcNative.canonicalLocalInnerPreControl(state,gap,pending,n);
check('source_gap_not_relabelled_or_used_as_dt',isequal(normal.kernel_output61,gapOut.kernel_output61) ...
    &&gapState.source_generation==gap.source_generation&&gapOut.source_timestamp_ns==next.source_timestamp_ns);
bad=next;bad.source_timestamp_ns=state.last_sample_timestamp_ns;
check('nonadvancing_original_time_rejected',rejects(@()gpenmpcNative.canonicalLocalInnerPreControl(state,bad,pending,n)));
bad=next;bad.dt_s=.005;
check('source_dt_mismatch_rejected',rejects(@()gpenmpcNative.canonicalLocalInnerPreControl(state,bad,pending,n)));
bad=next;bad.x13(1)=NaN;
check('nonfinite_source_rejected',rejects(@()gpenmpcNative.canonicalLocalInnerPreControl(state,bad,pending,n)));
bad=next;bad.new_leg=true;
check('same_leg_reset_cannot_hide_discontinuity',rejects(@()gpenmpcNative.canonicalLocalInnerPreControl(state,bad,pending,n)));
badPending=pending;badPending.generation=badPending.generation-uint64(1);
check('wrong_pending_generation_rejected',rejects(@()gpenmpcNative.canonicalLocalInnerPreControl(state,next,badPending,n)));
badPending=pending;badPending.timestamp_ns=badPending.timestamp_ns-uint64(1);
check('wrong_pending_original_timestamp_rejected',rejects(@()gpenmpcNative.canonicalLocalInnerPreControl(state,next,badPending,n)));
badPending=pending;badPending.prediction.prediction_sample_closed=true;
check('already_closed_prediction_rejected',rejects(@()gpenmpcNative.canonicalLocalInnerPreControl(state,next,badPending,n)));
check('incomplete_host_prediction_scaffold_rejected',rejects(@() ...
    gpenmpcNative.canonicalLocalInnerPreControl(state,next,rmfield(pending,'prediction'),n)));
before=state;gpenmpcNative.canonicalLocalInnerPreControl(state,next,pending,n);
check('discarded_candidate_does_not_commit_memory',isequaln(before,state));
report=struct('status','PASS_HOST_ONLY_LOCAL_PRE_POST_GP_NUMERICAL_CLOSURE', ...
    'checks',checks,'test_count',numel(checks),'pass_count',sum([checks.pass]), ...
    'archived_continuous_samples',60,'archive',archivePath, ...
    'archive_sha256',gpenmpcNative.fileSha256(archivePath), ...
    'source_inputs','ORIGINAL_SYNTHETIC_FIXTURE_NOT_LIVE', ...
    'archive_kernel61_bit_equal_samples',bit61,'fully_exact_current_runtime_states',exactStates, ...
    'maximum_kernel61_error',max61,'maximum_augmentation_error',maxAug, ...
    'maximum_state_error',maxState,'maximum_pending_error',maxPending, ...
    'local_chain_host_gp_prediction_calls',gpCalls, ...
    'independent_direct_oracle_gp_prediction_calls',gpCalls, ...
    'independent_original_runtime_gp_prediction_calls',gpCalls, ...
    'total_gp_prediction_calls_in_60_sample_comparison',3*gpCalls, ...
    'exact_gp_split_samples',exactGpSplits, ...
    'available_closed_evidence_samples',availableClosed,'physical_gp_active_samples',activePhysical, ...
    'outer_solver_calls',0,'plant_runs',0,'io_calls',0,'hardware_actions',0, ...
    'board_local_loop_installed',false,'real_time_deadline_proven',false);
files={'canonicalLocalInnerPreControl','canonicalLocalInnerPostControl', ...
    'prepareCanonicalCurrentGpPrediction','completeCanonicalCurrentGpPrediction','CurrentPhysicalCausalRuntime'};
for j=1:numel(files),report.source_sha256.(files{j})=gpenmpcNative.fileSha256(which("gpenmpcNative."+files{j}));end
save(fullfile(outputRoot,'RAW.mat'),'raw','report','-v7.3');
fid=fopen(fullfile(outputRoot,'RESULT.json'),'w','n','UTF-8');assert(fid>=0);
fg=onCleanup(@()fclose(fid));fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));clear fg
disp(jsonencode(report));
    function check(name,ok)
        checks(end+1)=struct('name',name,'pass',logical(ok)); %#ok<AGROW>
        if ~ok,save(fullfile(outputRoot,'FAILURE_RAW.mat'),'raw','checks','max61','maxState','maxPending');end
        assert(ok,'gpenmpcNative:LocalPreControlTest','%s',name);
    end
    function [p,rt]=observations(g,now,lag)
        % Verbatim numerical observations of the archived original 60-row test.
        p=struct('source','PX4_EKF2_MAVLINK_ODOMETRY_331','atomic_estimate',true, ...
            'plant_truth_used',false,'uid',expected.uid,'system_id',1,'component_id',1, ...
            'boot_generation',7,'sample_timestamp_ns',uint64(g)*uint64(1e7), ...
            'odometry_reset_counter',2,'odometry_frame_id',1, ...
            'odometry_child_frame_id',1,'odometry_estimator_type',8, ...
            'position_ned_m',[0;0;-2],'velocity_ned_mps',zeros(3,1), ...
            'quaternion_wxyz_body_to_ned',[1;0;0;0],'omega_frd_rad_s',zeros(3,1), ...
            'position_rx_ns',double(now)-1e5,'attitude_rx_ns',double(now)-1e5, ...
            'rates_rx_ns',double(now)-1e5,'position_generation',g, ...
            'attitude_generation',g,'rates_generation',g, ...
            'position_valid',true,'attitude_valid',true,'rates_valid',true);
        v=struct('source','HOST_M600_VIRTUAL_ACTUATOR_INTERFACE','valid',true, ...
            'generation',g,'rx_ns',double(now)-1e5,'ordering','SOFTWARE_M600_ORDER','rotor_thrust_state_n',lag);
        w=struct('source','FROZEN_TASK_WIND_ESTIMATOR','valid',true, ...
            'generation',g,'rx_ns',double(now)-1e5,'estimate_xy_mps',zeros(2,1));
        rt=struct('schema','GPENMPC_PHYSICAL_CAUSAL_RUNTIME_INPUT_V1', ...
            'task_identity_sha256',task,'plant_truth_used',false,'virtual_actuator',v,'wind',w, ...
            'task',struct('source','FROZEN_GPENMPC_TASK_STATE','payload_kg',2.27,'leg_index',1));
    end
end
function yes=rejects(f)
yes=false;try,f();catch,yes=true;end
end
function difference=maxDiff(a,b)
if isstruct(a)&&isstruct(b)
    if ~isequal(sort(fieldnames(a)),sort(fieldnames(b))),difference=Inf;return,end
    difference=0;names=fieldnames(a);
    for j=1:numel(names),difference=max(difference,maxDiff(a.(names{j}),b.(names{j})));end
elseif isnumeric(a)&&isnumeric(b)
    if ~isequal(size(a),size(b))||~isequal(isnan(a),isnan(b))||~isequal(isinf(a),isinf(b))
        difference=Inf;return
    end
    values=abs(double(a(isfinite(a)))-double(b(isfinite(b))));
    if isempty(values),difference=0;else,difference=max(values,[],'all');end
else
    difference=double(~isequaln(a,b))*Inf;
    if isequaln(a,b),difference=0;end
end
end
