function report=test_measured_source_coordinator(outputRoot)
% Test coordinator and worker clock wiring with checksum-valid synthetic RSP inputs.
arguments
    outputRoot (1,1) string
end
build=string(fileparts(fileparts(mfilename('fullpath'))));
parent=string(gpenmpc_external_path('native_visual_host_runtime'));
addpath(fullfile(parent,'src'),'-begin');addpath(fullfile(build,'host_runtime'),'-begin');
assert(~isfolder(outputRoot));mkdir(outputRoot);
fixture=fullfile(gpenmpc_external_path('board_commit_exchange_fixture'),'SOURCE_1.bin');
base=readBytes(fixture);raw=struct();checks=struct('name',{},'pass',{});c=[];
original=gpenmpcNative.RflySnapshotDecoder(base,gpenmpcNative.rflyOriginalHostMonotonicNs());
e=struct('uid',string(original.observed_uid),'system_id',1,'component_id',1, ...
    'boot_generation',original.observed_boot_generation,'maximum_age_ns',1e8, ...
    'maximum_runtime_age_ns',1e8,'canonical_package_root',gpenmpcNative.canonicalAssetRoot(), ...
    'initial_payload_kg',2.27,'async_outer_required',true, ...
    'task_identity_sha256',repmat('C',1,64),'inner_control_contract','CANONICAL_FULL_SE3', ...
    'full_inner_evidence_scope','BOARD_COMMIT_RFC1', ...
    'configuration_payload_sha256',hex(original.configuration_sha256));
e.rfly_board_commit=struct('execution_session_sha256',repmat('D',1,64), ...
    'identity_semantics','BoardRegisteredExecutionSessionGenerationV1', ...
    'link_lifecycle_generation',uint64(1),'board_registration_hrt_us',uint64(1), ...
    'reference_max_age_us',uint64(400000),'outer_max_age_us',uint64(400000), ...
    'generated_arm_source_sha256','A47F1C255BDAC1DAE712494BE8D9D66FC4F83138DBA9B0C2E3A31E114D4ABD0F', ...
    'wrapper_matlab_source_sha256','9117D3CDF8E924A253F4C444CDD467E4850D6F11CBF5744B26375B950E2A95B5');
now=gpenmpcNative.rflyOriginalHostMonotonicNs();[p,v,w]=obs(1,uint64(1000000),uint64(10000),now);
[x,ok]=gpenmpcNative.px4EstimateState(p,e,now);assert(ok);
coef=zeros(3,8);coef(:,1)=x(1:3);coef(:,2)=[.1;0;0];
tr=struct('total_duration_s',10,'coefficients_ascending',coef);
c=gpenmpcNative.CanonicalOuterCoordinator(build,e,tr);
cleanup=onCleanup(@()closeCoordinator(c)); %#ok<NASGU>
bad=p;bad.sample_timestamp_ns=double(bad.sample_timestamp_ns);
check('private_clock_requires_original_uint64_before_preparation', ...
    rejects(@()c.prepare(now,bad,v,w),'gpenmpcNative:CoordinatorMeasuredSource') ...
    &&c.status().service.preparation_calls==0&&~c.status().failed);
bad=p;bad.source='PX4_EKF2_MAVLINK_ODOMETRY_331';
check('private_scope_cannot_mix_a_different_source_label', ...
    rejects(@()c.prepare(now,bad,v,w),'gpenmpcNative:CoordinatorMeasuredSource'));
bad=p;bad.original_sample_hrt_us=bad.original_sample_hrt_us+uint64(1);
bad.sample_timestamp_ns=bad.original_sample_hrt_us*uint64(1000);
check('caller_consistent_clock_rewrite_still_differs_from_original_bytes', ...
    rejects(@()c.prepare(now,bad,v,w),'gpenmpcNative:CoordinatorMeasuredSource'));
bad=p;bad.actual_source_delta_us=uint64(9000);
check('measured_delta_cannot_be_rewritten_after_decode', ...
    rejects(@()c.prepare(now,bad,v,w),'gpenmpcNative:CoordinatorMeasuredSource') ...
    &&c.status().service.preparation_calls==0&&~c.status().failed);
raw.prepare=c.prepare(now,p,v,w);
check('production_owner_selected_measured_clock', ...
    raw.prepare.status=="PASS_HOST_PREPARATION" ...
    &&c.status().source_clock.schema=="GPENMPC_MEASURED_SOURCE_OUTER_CLOCK_V1");
now=gpenmpcNative.rflyOriginalHostMonotonicNs();[p,~,~]=obs(2,uint64(1009000),uint64(9000),now);
raw.drain=c.observeDisarmedSample(now,p,false);
check('nine_ms_not_forced_onto_ten_ms_grid',raw.drain.clock.accepted ...
    &&raw.drain.clock.observed_source_interval_ns==uint64(9000000) ...
    &&raw.drain.source_clock.total_flight_time_ns==0&&raw.drain.actual_solver_submissions==0);
now=gpenmpcNative.rflyOriginalHostMonotonicNs();[p,v,w]=obs(3,uint64(1018000),uint64(9000),now);
raw.first=c.flightSample(now,p,v,w);
check('first_real_worker_submission_uses_zero_flight_time', ...
    raw.first.clock.dispatch_solver&&raw.first.clock.leg_flight_time_ns==0 ...
    &&raw.first.submit.status=="SUBMITTED"&&raw.first.actual_solver_submissions==1);
raw.polls=drain();
check('worker_poll_cannot_advance_source_clock',all(cellfun( ...
    @(r)r.source_clock_unchanged,raw.polls))&&c.status().source_clock.leg_flight_time_ns==0);
now=gpenmpcNative.rflyOriginalHostMonotonicNs();[p,v,w]=obs(4,uint64(1027000),uint64(9000),now);
raw.nine=c.flightSample(now,p,v,w);
check('actual_flight_interval_retained_not_rounded',raw.nine.clock.accepted ...
    &&raw.nine.clock.effective_flight_dt_ns==uint64(9000000) ...
    &&raw.nine.clock.leg_flight_time_ns==uint64(9000000)&&~raw.nine.clock.dispatch_solver);
now=gpenmpcNative.rflyOriginalHostMonotonicNs();[p,v,w]=obs(5,uint64(1316000),uint64(9000),now);
raw.beforeDue=c.flightSample(now,p,v,w);
check('export_gap_not_fabricated_inner_steps',raw.beforeDue.clock.host_export_gap ...
    &&raw.beforeDue.clock.observed_source_interval_ns==uint64(289000000) ...
    &&raw.beforeDue.clock.leg_flight_time_ns==uint64(298000000) ...
    &&~raw.beforeDue.clock.dispatch_solver);
now=gpenmpcNative.rflyOriginalHostMonotonicNs();[p,v,w]=obs(6,uint64(1325000),uint64(9000),now);
raw.due=c.flightSample(now,p,v,w);
check('point30_dispatch_at_first_observed_sample_with_explicit_delay', ...
    raw.due.clock.dispatch_solver ...
    &&raw.due.clock.dispatch_due_leg_time_ns==uint64(300000000) ...
    &&raw.due.clock.dispatch_actual_leg_time_ns==uint64(307000000) ...
    &&raw.due.clock.dispatch_delay_ns==uint64(7000000) ...
    &&raw.due.actual_solver_submissions==2);
raw.land=c.enterNativeLand(gpenmpcNative.rflyOriginalHostMonotonicNs(),p);
check('same_source_land_pauses_without_invented_interval', ...
    raw.land.clock.effective_flight_dt_ns==0 ...
    &&raw.land.clock.leg_flight_time_ns==uint64(307000000) ...
    &&raw.land.service.outer_suspended&&~raw.land.land_command_sent);
raw.retired=drain();
now=gpenmpcNative.rflyOriginalHostMonotonicNs();[p,~,~]=obs(7,uint64(1334000),uint64(9000),now);
raw.ground=c.groundSample(now,p,true,false);
now=gpenmpcNative.rflyOriginalHostMonotonicNs();[p,~,~]=obs(8,uint64(9343000),uint64(9000),now);
raw.dwell=c.groundSample(now,p,true,false);
check('long_ground_dwell_excluded_from_flight_and_solver_time', ...
    raw.dwell.clock.effective_flight_dt_ns==0 ...
    &&raw.dwell.source_clock.total_flight_time_ns==uint64(307000000) ...
    &&raw.dwell.actual_solver_submissions==2&&~raw.dwell.clock.dispatch_solver);
now=gpenmpcNative.rflyOriginalHostMonotonicNs();[p,~,~]=obs(9,uint64(9352000),uint64(9000),now);
before=c.status();
check('clock_test_cannot_claim_unexecuted_inner_leg_complete', ...
    rejects(@()c.beginNextLeg(now,p,tr,1.5,true,false),'gpenmpcNative:PhysicalLegTransition') ...
    &&isequaln(c.status().source_clock,before.source_clock) ...
    &&~c.status().failed&&c.status().service.leg_index==1);
now=gpenmpcNative.rflyOriginalHostMonotonicNs();[p,~,~]=obs(10,uint64(9362001),uint64(10001),now);
check('existing_actual_delta_limit_not_weakened', ...
    rejects(@()c.groundSample(now,p,true,false),'gpenmpcNative:CoordinatorFailClosed') ...
    &&c.status().failed&&contains(c.status().failure_code,'ACTUAL_SOURCE_DELTA_EXCEEDED'));
raw.final=c.status();
check('no_inner_or_io_or_arm_claim',raw.final.service.physical_runtime.begin_count==0 ...
    &&raw.final.service.physical_runtime.control_commit_count==0 ...
    &&raw.final.owned_io_endpoints==0&&raw.final.owned_plants==0 ...
    &&~raw.final.final_hil_admission&&~raw.final.logical_arm_authority);
report=struct('status','PASS_HOST_ONLY_MEASURED_SOURCE_COORDINATOR_WIRING', ...
    'checks',checks,'test_count',numel(checks),'pass_count',sum([checks.pass]), ...
    'actual_solver_submissions',raw.final.actual_solver_submissions, ...
    'actual_solver_accepted',raw.final.service.async_accepted, ...
    'source_inputs','EXPLICIT_SYNTHETIC_CHECKSUM_CORRECT_RSP_FIXTURES_NOT_BOARD_OR_TRANSPORT', ...
    'source_timestamps_are_test_inputs_not_observed_wall_time',true, ...
    'production_service_and_worker',true,'hardware_actions',0,'com_open',0, ...
    'actual_inner_steps',0,'transport_authentication_proven',false, ...
    'coordinator_sha256',gpenmpcNative.fileSha256(which('gpenmpcNative.CanonicalOuterCoordinator')), ...
    'clock_sha256',gpenmpcNative.fileSha256(which('gpenmpcNative.canonicalMeasuredSourceOuterClock')), ...
    'base_fixture_sha256',gpenmpcNative.fileSha256(fixture));
save(fullfile(outputRoot,'RAW.mat'),'raw','report','-v7.3');
f=fopen(fullfile(outputRoot,'RESULT.json'),'w','n','UTF-8');assert(f>=0);
fc=onCleanup(@()fclose(f));fprintf(f,'%s\n',jsonencode(report,PrettyPrint=true));clear fc
disp(jsonencode(report));
    function list=drain()
        list={};t=tic;
        while c.status().service.async_in_flight&&toc(t)<5
            pause(.001);list{end+1}=c.poll(gpenmpcNative.rflyOriginalHostMonotonicNs()); %#ok<AGROW>
        end
        assert(~c.status().service.async_in_flight);
    end
    function [p,v,w]=obs(g,sourceUs,deltaUs,hostNs)
        % Only a HOST test fixture generator. No decoder/production source rewrite.
        b=base;b(59:62)=be(uint32(g));b(63:70)=be(sourceUs);
        b(71:78)=be(sourceUs+uint64(100));b(79:86)=be(sourceUs+uint64(200));
        b(167:174)=be(uint64(1));b(175:182)=be(deltaUs);
        md=java.security.MessageDigest.getInstance('SHA-256');md.update(typecast(b(1:214),'int8'));
        b(215:246)=reshape(typecast(md.digest(),'uint8'),[],1);
        p=gpenmpcNative.RflySnapshotSample(b,hostNs,e);
        v=struct('source','HOST_M600_VIRTUAL_ACTUATOR_INTERFACE','valid',true, ...
            'generation',g,'rx_ns',double(hostNs),'ordering','SOFTWARE_M600_ORDER', ...
            'rotor_thrust_state_n',ones(6,1)*20,'thrust_effectiveness',ones(6,1), ...
            'state_source','SAME_M600_ACCEPTED_STEP_ROTOR_LAG_STATE','plant_session_id',1);
        w=struct('source','FROZEN_TASK_WIND_ESTIMATOR','valid',true, ...
            'generation',g,'rx_ns',double(hostNs),'estimate_xy_mps',zeros(2,1));
    end
    function check(name,ok)
        checks(end+1)=struct('name',name,'pass',logical(ok)); %#ok<AGROW>
        if ~ok,save(fullfile(outputRoot,'FAILURE.mat'),'raw','checks');end
        assert(ok,'gpenmpcNative:MeasuredCoordinatorTest','%s',name);
    end
end
function closeCoordinator(c)
if ~isempty(c)&&isvalid(c),c.close();delete(c);end
end
function b=readBytes(p)
f=fopen(p,'rb');assert(f>=0);c=onCleanup(@()fclose(f));b=fread(f,Inf,'*uint8'); %#ok<NASGU>
end
function b=be(v)
[~,~,e]=computer;if e=='L',v=swapbytes(v);end;b=reshape(typecast(v,'uint8'),[],1);
end
function h=hex(b),h=upper(reshape(dec2hex(b,2).',1,[]));end
function ok=rejects(f,id),ok=false;try,f();catch ex,ok=strcmp(ex.identifier,id);end;end
