function report=test_canonical_outer_coordinator(outputRoot,fullInner)
% Test scheduler/service coupling with one worker and synthetic observations.
arguments
    outputRoot (1,1) string
    fullInner (1,1) logical = false
end
build=string(fileparts(fileparts(mfilename('fullpath'))));
parent=string(gpenmpc_external_path('native_visual_host_runtime'));
old=path;c=[];pc=onCleanup(@cleanupTest); %#ok<NASGU>
addpath(fullfile(parent,'src'),'-begin');addpath(fullfile(build,'host_runtime'),'-begin');
assert(~isfolder(outputRoot),'Prior evidence must remain unchanged.');mkdir(outputRoot);
checks=struct('name',{},'pass',{});raw=struct();
e=struct('uid','1234605616436508552','system_id',1,'component_id',1, ...
    'boot_generation',7,'maximum_age_ns',1e8,'maximum_runtime_age_ns',1e8, ...
    'canonical_package_root',gpenmpcNative.canonicalAssetRoot(),'initial_payload_kg',2.27, ...
    'async_outer_required',true,'task_identity_sha256',repmat('C',1,64));
if fullInner
    e.inner_control_contract='CANONICAL_FULL_SE3';
    e.full_inner_evidence_scope='HOST_ONLY_KERNEL_EXECUTION';
    fullAssets=gpenmpcNative.loadCanonicalAssets();
end
coef=zeros(3,8);coef(:,1)=[0;0;2];coef(:,2)=[.1;0;0];
tr=struct('total_duration_s',10,'coefficients_ascending',coef);
c=gpenmpcNative.CanonicalOuterCoordinator(build,e,tr);
now=gpenmpcNative.monotonicNs();[p,v,w]=obs(10,2,now);
bad=rmfield(p,'sample_timestamp_ns');
check('source_clock_checked_before_real_solver_preparation',rejects(@() ...
    c.prepare(now,bad,v,w),'gpenmpcNative:CoordinatorSourceClock'));
check('invalid_preparation_has_no_partial_service_commit', ...
    ~c.status().initialized&&~c.status().service.prepared ...
    &&c.status().service.preparation_calls==0&&~c.status().failed);
raw.prepare=c.prepare(now,p,v,w);
check('real_canonical_preparation_no_admission',raw.prepare.status=="PASS_HOST_PREPARATION" ...
    &&~raw.prepare.final_hil_admission&&c.status().service.preparation_calls==1);
check('exactly_same_service_handle_is_reused',c.controlService()==c.controlService());
now=gpenmpcNative.monotonicNs();[p,v,w]=obs(11,2,now);
raw.first=c.flightSample(now,p,v,w);
check('t0_launches_actual_async_solver_once',raw.first.clock.dispatch_solver ...
    &&raw.first.submit.status=="SUBMITTED"&&c.status().actual_solver_submissions==1);
raw.polls={};timer=tic;
while c.status().service.async_in_flight&&toc(timer)<3
    pause(.001);raw.polls{end+1}=c.poll(gpenmpcNative.monotonicNs()); %#ok<AGROW>
end
s=c.status();
check('actual_solver_result_committed_with_r2_r3',s.service.async_accepted==1 ...
    &&s.service.fresh_outer_for_current_leg ...
    &&any(cellfun(@(x)isfield(x.poll,'solver_audit') ...
        &&x.poll.solver_audit.coordinated_single_supervisor,raw.polls)));
check('polling_does_not_advance_source_clock',all(cellfun( ...
    @(x)x.source_clock_unchanged,raw.polls))&&s.source_clock.total_flight_ticks==0);
% Test the shared service's two-phase lifecycle with a synthetic V7 fixture.
now=gpenmpcNative.monotonicNs();[p,v,w]=obs(12,2,now);
physical=struct('schema','GPENMPC_PHYSICAL_CAUSAL_RUNTIME_INPUT_V1', ...
    'task_identity_sha256',e.task_identity_sha256,'plant_truth_used',false, ...
    'virtual_actuator',v,'wind',w,'task',struct('source','FROZEN_GPENMPC_TASK_STATE', ...
    'payload_kg',2.27,'leg_index',1));
raw.syntheticControlBegin=c.controlService().stepPhysicalReference( ...
    uint64(1),now,p,physical,.01);
commitNs=gpenmpcNative.monotonicNs();
guard=struct('source','PX4_UORB_GPENMPC_SE3_CONTROL_STATUS','valid',true, ...
    'plant_truth_used',false,'rx_ns',double(commitNs)-1e5,'control_mode',1, ...
    'failure_reason',0,'active',true,'state_valid',true,'reference_fresh',true, ...
    'segment_fresh',true,'native_position_controller_disabled',true, ...
    'native_attitude_rate_allocator_enabled',true,'single_publisher_contract_pass',true);
act=struct('mavpackettype','HIL_ACTUATOR_CONTROLS','time_usec',floor(double(commitNs)/1000), ...
    'controls',[ones(6,1)*.5;nan(10,1)],'src_system',1,'src_component',1, ...
    'rx_ns',double(commitNs),'generation',1);
if fullInner
    command=raw.syntheticControlBegin.full_inner_command;
    raw.fullInnerFeedback=gpenmpcNative.executeCanonicalFullInnerKernelHost( ...
        command,fullAssets,commitNs);
    raw.syntheticControlCommit=c.controlService().commitPhysicalControl( ...
        uint64(1),commitNs,raw.fullInnerFeedback);
else
    raw.syntheticControlCommit=c.controlService().commitV7PhysicalControl( ...
        uint64(1),commitNs,guard,act);
end
check('same_service_closes_explicit_host_control_execution', ...
    raw.syntheticControlBegin.accepted&&raw.syntheticControlCommit.accepted ...
    &&c.status().service.physical_runtime.control_commit_count==1);
now=gpenmpcNative.monotonicNs();[p,v,w]=obs(12,2.01,now);
raw.notDue=c.flightSample(now,p,v,w);
check('ordinary_inner_tick_does_not_launch_extra_solve', ...
    ~raw.notDue.clock.dispatch_solver&&raw.notDue.submit.status=="NOT_DUE" ...
    &&c.status().actual_solver_submissions==1);
now=gpenmpcNative.monotonicNs();[p,v,w]=obs(13,2.30,now);
raw.second=c.flightSample(now,p,v,w);
check('point30_source_clock_dispatch_not_reference_phase', ...
    raw.second.clock.dispatch_solver&&raw.second.clock.dispatch_leg_time_s==.30 ...
    &&c.status().service.phase_s<.02&&c.status().actual_solver_submissions==2);
check('skipped_source_ticks_accounted_not_fabricated', ...
    raw.second.clock.skipped_inner_ticks==28 ...
    &&raw.second.clock.outer_slots_accounted==1);
now=gpenmpcNative.monotonicNs();[p,~,~]=obs(14,2.31,now);
raw.land=c.enterNativeLand(now,p);
check('native_land_retires_same_worker_without_land_command', ...
    raw.land.suspension.inflight_retired&&~raw.land.land_command_sent ...
    &&c.status().service.outer_suspended);
now=gpenmpcNative.monotonicNs();[p,v,w]=obs(15,2.32,now);
check('flight_reentry_during_land_rejected',rejects(@()c.flightSample(now,p,v,w), ...
    'gpenmpcNative:CoordinatorFlightLifecycle'));
timer=tic;raw.drain={};
while c.status().service.async_in_flight&&toc(timer)<3
    pause(.001);raw.drain{end+1}=c.poll(gpenmpcNative.monotonicNs()); %#ok<AGROW>
end
check('land_drain_discards_without_new_worker_or_solver_commit', ...
    c.status().service.async_lifecycle_discarded==1 ...
    &&c.status().service.async_accepted==1&&c.status().actual_solver_submissions==2);
now=gpenmpcNative.monotonicNs();[p,~,~]=obs(16,2.32,now);
raw.ground=c.groundSample(now,p,true,false);before=c.status();
now=gpenmpcNative.monotonicNs();[p,~,~]=obs(17,2.82,now);
raw.dwell=c.groundSample(now,p,true,false);
check('ground_dwell_never_advances_flight_clock', ...
    c.status().source_clock.total_flight_ticks==before.source_clock.total_flight_ticks ...
    &&raw.dwell.clock.effective_flight_dt_s==0&&~raw.dwell.payload_write_sent);
now=gpenmpcNative.monotonicNs();[p,~,~]=obs(18,2.83,now);
check('ground_armed_cannot_start_new_leg',rejects(@() ...
    c.beginNextLeg(now,p,tr,1.5,true,true),'gpenmpcNative:BoardLegTransitionAuthority'));
beforeBad=c.status();
causalBefore=c.controlService().outerRuntime(90,now,ones(6,1)*20,ones(6,1),zeros(2,1),2.27);
badtr=tr;badtr.total_duration_s=-1;
check('invalid_next_trajectory_rejected_before_causal_reset',rejects(@() ...
    c.beginNextLeg(now,p,badtr,1.5,true,false),'gpenmpcNative:BoardReferenceTrajectory'));
causalAfter=c.controlService().outerRuntime(90,now,ones(6,1)*20,ones(6,1),zeros(2,1),2.27);
check('invalid_next_trajectory_preserves_clock_leg_force_and_causal_state', ...
    isequaln(beforeBad.service,c.status().service) ...
    &&isequaln(beforeBad.source_clock,c.status().source_clock) ...
    &&isequaln(causalBefore,causalAfter)&&~c.status().failed);
raw.next=c.beginNextLeg(gpenmpcNative.monotonicNs(),p,tr,1.5,true,false);
check('next_leg_resets_once_and_requires_own_fresh_result', ...
    raw.next.clock.reset_phase&&c.status().service.leg_index==2 ...
    &&~c.status().service.fresh_outer_for_current_leg);
now=gpenmpcNative.monotonicNs();[p,v,w]=obs(19,2.83,now);
raw.nextFlight=c.flightSample(now,p,v,w);
check('next_leg_t0_is_new_actual_submission',raw.nextFlight.clock.dispatch_solver ...
    &&c.status().actual_solver_submissions==3);
timer=tic;raw.nextPolls={};
while c.status().service.async_in_flight&&toc(timer)<3
    pause(.001);raw.nextPolls{end+1}=c.poll(gpenmpcNative.monotonicNs()); %#ok<AGROW>
end
check('next_leg_actual_canonical_solution',c.status().service.async_accepted==2 ...
    &&c.status().service.fresh_outer_for_current_leg);
% An invalid external observation at the next due slot must latch both
% owners, preserve the first cause and account rejection without a launch.
now=gpenmpcNative.monotonicNs();[p,v,w]=obs(20,3.13,now);v.valid=false;
check('mutation_region_exception_preserves_primary_identifier',rejects(@() ...
    c.flightSample(now,p,v,w),'gpenmpcNative:ObservedOuterRuntime'));
raw.final=c.status();
check('coordinator_and_service_latch_consistently_after_invalid_observation', ...
    raw.final.failed&&raw.final.service.failed&&raw.final.rejected_dispatches==1 ...
    &&raw.final.failure_code=="IMPLEMENTATION__gpenmpcNative:ObservedOuterRuntime");
check('source_denominator_and_actual_submissions_separate', ...
    raw.final.source_clock.outer_slots_accounted==4 ...
    &&raw.final.source_clock.dispatch_permissions==4 ...
    &&raw.final.submit_attempts==4&&raw.final.actual_solver_submissions==3 ...
    &&raw.final.submit_attempts==raw.final.actual_solver_submissions+raw.final.rejected_dispatches);
check('no_plant_io_or_final_hil_authority',raw.final.owned_plants==0 ...
    &&raw.final.owned_io_endpoints==0&&~raw.final.final_hil_admission ...
    &&~raw.final.logical_arm_authority&&~raw.final.control_publication_authority);
report=struct('status','PASS_HOST_ONLY_SINGLE_OWNER_CANONICAL_OUTER_COORDINATOR', ...
    'checks',checks,'test_count',numel(checks),'pass_count',sum([checks.pass]), ...
    'actual_solver_submissions',raw.final.actual_solver_submissions, ...
    'actual_async_results_accepted',raw.final.service.async_accepted, ...
    'actual_lifecycle_results_discarded',raw.final.service.async_lifecycle_discarded, ...
    'synthetic_observations',true,'dynamics_plant_count',0, ...
    'synthetic_v7_control_fixture_count',double(~fullInner), ...
    'actual_host_full_inner_executions',double(fullInner), ...
    'inner_controller_deployment_tested',false,'hardware_actions',0,'com_open',0);
report.source_sha256=struct('coordinator',gpenmpcNative.fileSha256(which( ...
    'gpenmpcNative.CanonicalOuterCoordinator')),'service',gpenmpcNative.fileSha256( ...
    which('gpenmpcNative.BoardOuterService')),'clock',gpenmpcNative.fileSha256( ...
    which('gpenmpcNative.canonicalOuterClock')));
save(fullfile(outputRoot,'RAW.mat'),'report','raw','-v7.3');
fid=fopen(fullfile(outputRoot,'RESULT.json'),'w','n','UTF-8');assert(fid>=0);
fc=onCleanup(@()fclose(fid));fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));clear fc
disp(jsonencode(report));clear pc
    function cleanupTest()
        % Release the worker/handles before restoring away their class path.
        if ~isempty(c)&&isvalid(c),c.close();delete(c);end
        path(old);
    end
    function check(name,ok)
        checks(end+1)=struct('name',name,'pass',logical(ok)); %#ok<AGROW>
        if ~ok,save(fullfile(outputRoot,'FAILURE_RAW.mat'),'raw','checks');end
        assert(ok,'gpenmpcNative:CoordinatorTest','%s',name);
    end
    function [p,v,w]=obs(g,sourceS,hostNs)
        p=struct('source','PX4_EKF2_MAVLINK_ODOMETRY_331','atomic_estimate',true, ...
            'plant_truth_used',false,'uid',e.uid,'system_id',1,'component_id',1, ...
            'boot_generation',7,'sample_timestamp_ns',round(sourceS*1e9), ...
            'odometry_reset_counter',2,'odometry_frame_id',1,'odometry_child_frame_id',1, ...
            'odometry_estimator_type',8,'position_ned_m',[0;0;-2], ...
            'velocity_ned_mps',zeros(3,1),'quaternion_wxyz_body_to_ned',[1;0;0;0], ...
            'omega_frd_rad_s',zeros(3,1),'position_rx_ns',double(hostNs)-1e5, ...
            'attitude_rx_ns',double(hostNs)-1e5,'rates_rx_ns',double(hostNs)-1e5, ...
            'position_generation',g,'attitude_generation',g,'rates_generation',g, ...
            'position_valid',true,'attitude_valid',true,'rates_valid',true);
        v=struct('source','HOST_M600_VIRTUAL_ACTUATOR_INTERFACE', ...
            'rx_ns',double(hostNs)-1e5,'generation',g,'valid',true, ...
            'ordering','SOFTWARE_M600_ORDER','rotor_thrust_state_n',ones(6,1)*20, ...
            'thrust_effectiveness',ones(6,1), ...
            'state_source','SAME_M600_ACCEPTED_STEP_ROTOR_LAG_STATE','plant_session_id',26090501);
        w=struct('source','FROZEN_TASK_WIND_ESTIMATOR','rx_ns',double(hostNs)-1e5, ...
            'generation',g,'valid',true,'estimate_xy_mps',zeros(2,1));
    end
end
function ok=rejects(f,id)
ok=false;try,f();catch ex,ok=strcmp(ex.identifier,id);end
end
