function report=test_canonical_rotor_execution_interface(outputRoot)
% Test the rotor execution interface with fixed data.
arguments
    outputRoot (1,1) string
end
build=string(fileparts(fileparts(mfilename('fullpath'))));
assert(startsWith(lower(string(java.io.File(char(outputRoot)).getCanonicalPath())), ...
    lower(string(java.io.File(char(fullfile(build,'evidence'))).getCanonicalPath())+filesep)));
assert(~isfolder(outputRoot),'Never overwrite prior evidence.');mkdir(outputRoot);
old=path;guard=onCleanup(@()path(old));
parent=string(gpenmpc_external_path('native_visual_host_runtime'));
addpath(fullfile(parent,'src'),'-end');addpath(fullfile(build,'host_runtime'),'-begin');
a=gpenmpcNative.loadCanonicalAssets(gpenmpcNative.canonicalAssetRoot());
px4=string(gpenmpc_external_path('px4_source_root'));
sources={ ...
    'src/lib/mixer_module/functions/FunctionMotors.hpp','BE4E6AAA363BC49A5B63CC5683E6CDB805494955431D250F3023EE70C9F8628A'; ...
    'src/lib/mixer_module/mixer_module.cpp','D8140B57E6367EA35F7BBD24BA419DD766432F796177199A10BAFD2107929CBE'; ...
    'src/lib/mathlib/math/Functions.hpp','D45D4FA2CA6EF30615C32167A689B4B94C518802CD3C8F3B6E1CF252A13F5079'; ...
    'src/modules/simulation/pwm_out_sim/PWMSim.cpp','063581499B667055E31CE4B271EFF578F6D717D37BD4BF14E6930C3A543090B5'; ...
    'src/modules/simulation/pwm_out_sim/PWMSim.hpp','99BCF9C7F82D52625D386EE511618FF7A060A19CDFEBB0F260E0EF3D53FACB71'; ...
    'src/modules/mavlink/streams/HIL_ACTUATOR_CONTROLS.hpp','1AC5017C301C73801D1E8329024FB5F54183FBE58292E56EF29B2BC6B6B903B7'; ...
    'src/modules/control_allocator/ControlAllocator.cpp','56482F1E2D384CF3151E438065D0EB00555A01F060C8439F6115525B6EED938F'; ...
    'src/lib/control_allocation/control_allocation/ControlAllocationPseudoInverse.cpp','3200E76A8A150C0DD514C8E4008D7392729BCA53BF42E71151A74D364C803499'; ...
    'src/lib/control_allocation/control_allocation/ControlAllocationSequentialDesaturation.cpp','07E60BC11A9948D41C99950FD99FFF06368BB6203F05B79D64386A0A04351D7C'; ...
    'msg/versioned/ActuatorMotors.msg','A5CF96CE35AA90526ED4ACCE9BCFC221CB696E6910985561CF205060AA88DF8B'};
for k=1:size(sources,1)
    assert(strcmpi(gpenmpcNative.fileSha256(fullfile(px4,sources{k,1})),sources{k,2}), ...
        'Audited source changed: %s',sources{k,1});
end
allocation=gpenmpcM600Allocation(a.calibration);upper=allocation.per_rotor_upper_n;
interface=struct('schema','CANONICAL_M600_ROTOR_EXECUTION_INTERFACE_V1', ...
    'input_units','NEWTON','input_order','CANONICAL_M600_ORDER', ...
    'allocation_matrix',allocation.matrix,'per_rotor_upper_n',upper, ...
    'software_from_px4_one_based',[5;1;4;6;2;3], ...
    'hil_output_functions',[(101:106)';zeros(10,1)],'thr_mdl_fac',0, ...
    'reversible_flags',0,'output_reverse_mask',0, ...
    'pwm_sim_min',1000,'pwm_sim_max',2000,'output_limit_state','ON');
fixture=fullfile(build,'evidence','canonical_full_se3_kernel_rebinding_20260906_074245','RAW_REBINDING.mat');
assert(strcmpi(gpenmpcNative.fileSha256(fixture), ...
    '3896CDC2B329E751F8E524EDD8FF7FADCCAF63B764A17CC79261FABDBC89A9DD'));
loaded=load(fixture,'raw');commands=loaded.raw.oracle61(:,5:10);
checks=struct('name',{},'pass',{});raw=struct();maxError=0;nonzeroDistortion=0;
predicted=zeros(size(commands));pwm=zeros(size(commands),'uint16');
try
    for k=1:size(commands,1)
        [r,ok,reason]=gpenmpcNative.canonicalRotorToActuatorMotors(commands(k,:).',a.calibration,interface);
        assert(ok,'gpenmpc:Conversion','%s',reason);
        predicted(k,:)=r.expected_linear_host_decoded_rotor_newton.';
        pwm(k,:)=r.expected_pwm_sim_u16_on.';
        maxError=max(maxError,r.maximum_absolute_error_newton);
        nonzeroDistortion=nonzeroDistortion+double(r.maximum_absolute_error_newton>1e-12);
        assert(~r.publication_allowed&&~r.exact_arbitrary_real_output_equivalence);
    end
    check('all_2123_current_kernel_outputs_converted',size(commands,1)==2123);
    check('source_derived_quantization_error_bound',maxError<= ...
        r.ideal_half_step_error_bound_newton+r.float32_arithmetic_guard_newton);
    check('quantization_not_misrepresented_as_exact_equivalence',nonzeroDistortion>0);
    check('no_helper_clipping_or_reallocation',~r.helper_clipping_performed&&~r.controller_or_allocator_recomputed);
    for rotor=1:6
        n=zeros(6,1);n(rotor)=upper;
        [q,ok]=gpenmpcNative.canonicalRotorToActuatorMotors(n,a.calibration,interface);
        expected=zeros(6,1);expected(interface.software_from_px4_one_based(rotor))=1;
        check("single_rotor_order_"+rotor,ok&&isequal(double(q.actuator_motors_control(1:6)),expected) ...
            &&isequal(q.expected_linear_host_decoded_rotor_newton,n));
        check("inactive_motor_stop_nan_"+rotor,all(isnan(q.actuator_motors_control(7:12))));
    end
    [q,ok]=gpenmpcNative.canonicalRotorToActuatorMotors(zeros(6,1),a.calibration,interface);
    check('zero_not_disarmed_state_claim',ok&&all(q.expected_hil_controls_1_to_6_on==0)&&~q.publication_allowed);
    % Narrow fixtures around one PWM rounding boundary.
    offsets=[-1e-4,1e-4];raw.rounding_boundaries=cell(1,2);
    for j=1:2
        n=ones(6,1)*upper*(.1235+offsets(j));
        [q,ok]=gpenmpcNative.canonicalRotorToActuatorMotors(n,a.calibration,interface);
        check("pwm_rounding_side_"+j,ok&&all(q.expected_pwm_sim_u16_on==uint16(1122+j)));
        raw.rounding_boundaries{j}=q;
    end
    n=ones(6,1)*upper/2;
    cases={ 'normalized_mislabel','input_units','NORMALIZED'; ...
        'wrong_order','input_order','PX4_MOTOR_ORDER'; ...
        'permutation_identity','software_from_px4_one_based',(1:6)'; ...
        'function_order','hil_output_functions',[(102:106)';101;zeros(10,1)]; ...
        'wrong_upper','per_rotor_upper_n',upper+1; ...
        'thrust_curve','thr_mdl_fac',.5; ...
        'reverse_rotors','reversible_flags',1; ...
        'reverse_output','output_reverse_mask',1; ...
        'pwm_range','pwm_sim_max',4000; ...
        'off_state','output_limit_state','OFF'; ...
        'ramp_state','output_limit_state','RAMP'; ...
        'failsafe_state','output_limit_state','FAILSAFE'};
    for j=1:size(cases,1)
        bad=interface;bad.(cases{j,2})=cases{j,3};rejected(cases{j,1},n,a.calibration,bad);
    end
    bad=interface;bad.allocation_matrix(2,1)=1;rejected('wrong_geometry_matrix',n,a.calibration,bad);
    badCal=a.calibration;badCal.rotor_allocation.spin_sign(1)=-1;rejected('wrong_spin_geometry',n,badCal,interface);
    bad=n;bad(1)=NaN;rejected('nan_input',bad,a.calibration,interface);
    bad=n;bad(1)=Inf;rejected('infinite_input',bad,a.calibration,interface);
    bad=n;bad(1)=-eps;rejected('negative_not_silently_clipped',bad,a.calibration,interface);
    bad=n;bad(1)=upper+eps(upper);rejected('above_limit_not_silently_clipped',bad,a.calibration,interface);
    rejected('five_channels',n(1:5),a.calibration,interface);
    raw.input_rotor_newton=commands;raw.predicted_rotor_newton=predicted;raw.pwm_sim_u16=pwm;
    report=struct('status','PASS_HOST_ONLY_ROTOR_UNIT_ORDER_AND_QUANTIZATION_INTERFACE', ...
        'case_count',size(commands,1),'checks',checks,'check_count',numel(checks), ...
        'maximum_quantization_error_per_rotor_newton',maxError, ...
        'ideal_half_step_bound_newton',upper/2000,'nonzero_quantization_rows',nonzeroDistortion, ...
        'interface',interface,'hardware_actions',0,'matlab_model_runs',0, ...
        'exact_arbitrary_real_output_equivalence',false,'live_publication_authority',false, ...
        'full_px4_allocator_equivalence',false,'fixture_path',fixture, ...
        'audited_px4_source_root',px4,'audited_px4_source_paths_and_sha256',{sources}, ...
        'helper_sha256',gpenmpcNative.fileSha256(which('gpenmpcNative.canonicalRotorToActuatorMotors')), ...
        'test_sha256',gpenmpcNative.fileSha256(mfilename('fullpath')+".m"));
    save(fullfile(outputRoot,'RAW.mat'),'report','raw','-v7');
    fid=fopen(fullfile(outputRoot,'RESULT.json'),'w','n','UTF-8');assert(fid>=0);
    outGuard=onCleanup(@()fclose(fid));fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));clear outGuard
    disp(jsonencode(report));
catch err
    raw.failure=getReport(err,'extended','hyperlinks','off');
    save(fullfile(outputRoot,'FAILURE_RAW.mat'),'raw','checks','-v7');rethrow(err)
end
    function check(name,ok)
        checks(end+1)=struct('name',string(name),'pass',logical(ok));
        assert(ok,'gpenmpc:RotorInterfaceTest','%s',name);
    end
    function rejected(name,n,c,contract)
        [v,ok,~]=gpenmpcNative.canonicalRotorToActuatorMotors(n,c,contract);
        check("reject_"+name,~ok&&~v.publication_allowed&&v.hardware_actions==0 ...
            &&~isfield(v,'actuator_motors_control'));
    end
end
