function report=test_canonical_board_outer_service(outputRoot,useAsync)
% Test the canonical solver and service with synthetic board inputs.
arguments
    outputRoot (1,1) string
    useAsync (1,1) logical = false
end
build=string(fileparts(fileparts(mfilename('fullpath'))));
parent=string(gpenmpc_external_path('native_visual_host_runtime'));
oldPath=path;pathGuard=onCleanup(@()path(oldPath)); %#ok<NASGU>
addpath(fullfile(parent,'src'),'-begin');
addpath(fullfile(build,'host_runtime'),'-begin');
a=gpenmpcNative.loadCanonicalAssets(gpenmpcNative.canonicalAssetRoot());
assert(startsWith(string(which('gpenmpcCoordinatedOuterStep')),string(a.sourceRoot)));
assert(~isfolder(outputRoot),'Test output already exists; preserve prior evidence.');
mkdir(outputRoot);
checks=struct('name',{},'pass',{});raw=struct();
expected=struct('uid','1234605616436508552','system_id',1,'component_id',1, ...
    'boot_generation',7,'maximum_age_ns',100e6,'maximum_runtime_age_ns',100e6, ...
    'canonical_package_root',gpenmpcNative.canonicalAssetRoot(), ...
    'initial_payload_kg',2.27, ...
    'async_outer_required',useAsync, ...
    'task_identity_sha256',repmat('C',1,64)); % Explicit synthetic unit task.
coeff=zeros(3,8);coeff(:,1)=[0;0;2];coeff(:,2)=[.1;0;0];
trajectory=struct('total_duration_s',10,'coefficients_ascending',coeff);
service=gpenmpcNative.BoardOuterService(build,expected,trajectory);
serviceGuard=onCleanup(@()service.close()); %#ok<NASGU>
mass=double(a.profile.mass_properties.base_mass_kg)+2.27;
rotor=repmat(mass*9.80665/6,6,1);
t=2e9;
r=service.outerRuntime(10,t,rotor,ones(6,1),zeros(2,1),2.27);
p=sample(expected,10,t);
raw.preparation=service.prepare(t,p,r);
check('real_preparation_calls_canonical_solver_no_command', ...
    raw.preparation.status=="PASS_HOST_PREPARATION" ...
    &&~raw.preparation.command_committed ...
    &&raw.preparation.preparation_audit.coordinated_single_supervisor);
r=service.outerRuntime(11,t,rotor,ones(6,1),zeros(2,1),2.27);
p=sample(expected,11,t);
if useAsync
    timer=tic;
    raw.async_submit=service.submitUpdate(uint64(1),t,p,r);
    check('async_submit_real_solver_once',raw.async_submit.status=="SUBMITTED");
    check('async_second_inflight_submit_rejected',rejects(@() ...
        service.submitUpdate(uint64(1),t,p,r),'gpenmpcNative:BoardOuterAsyncBusy'));
    raw.async_polls={};
    while toc(timer)<2
        polled=service.pollUpdate(round(t+toc(timer)*1e9));
        raw.async_polls{end+1}=polled; %#ok<AGROW>
        if polled.status=="FRESH_RESULT_COMMITTED" ...
                ||polled.status=="DEADLINE_FALLBACK_COMMITTED" ...
                ||polled.status=="FAIL_CLOSED_WORKER_ERROR"
            raw.first=polled;break
        end
        pause(.001);
    end
    check('async_result_arrived_and_committed',isfield(raw,'first') ...
        &&raw.first.status=="FRESH_RESULT_COMMITTED");
else
    raw.first=service.update(uint64(1),t,p,r);
end
check('real_solver_result_retains_full_decision_and_r3_evidence', ...
    isfield(raw.first,'solver_decision')&&isfield(raw.first,'solver_audit') ...
    &&isfield(raw.first,'continuity_event')&&raw.first.generation==1);
check('initial_no_causal_gp_evidence_uses_exact_b1', ...
    raw.first.selected_method==string(a.enmpc.b1_fallback_method) ...
    &&raw.first.solver_audit.coordinated_responsibility.exact_b1_required);
check('real_solver_completed_within_unchanged_deadline', ...
    any(raw.first.disposition==["FRESH_SOLVER_RESULT","FRESH_ASYNC_SOLVER_RESULT"]) ...
    &&raw.first.solver_wall_s<=.28&&raw.first.solver_deadline_s==.28);

for k=1:2
    now=t+(k-1)*1e7;
    px=sample(expected,11+k,now);
    if k==2,px.velocity_ned_mps=[0;0;-.001];end
    raw.physical{k}=service.stepPhysicalReference(uint64(k),now, ...
        px,physicalRuntime(expected,11+k,now,rotor,1,2.27),.01);
    check("physical_begin_"+k,raw.physical{k}.accepted);
    raw.commits{k}=service.commitV7PhysicalControl(uint64(k),now, ...
        moduleGuard(now),actuator(k,now));
    check("actual_feedback_adapter_commit_fixture_"+k,raw.commits{k}.accepted);
end
after=service.outerRuntime(14,t+2e7,rotor,ones(6,1),zeros(2,1),2.27);
check('outer_desired_force_is_committed_mirror_not_rotor_product', ...
    after.outer.desired_force_generation==2 ...
    &&after.outer.desired_force_source=="COMMITTED_NOMINAL_CONTROLLER_MIRROR" ...
    &&isequal(after.outer.previous_desired_force_projected_n, ...
        raw.commits{2}.v7_desired_force_projected_up_n));
check('outer_prior_rotor_command_not_lagged_rotor_state', ...
    isequal(after.virtual_actuator.rotor_command_n,raw.commits{2}.current_rotor_command_n) ...
    &&after.virtual_actuator.command_source=="PREVIOUS_COMMITTED_HIL_ACTUATOR_COMMAND" ...
    &&after.virtual_actuator.command_generation==2);
check('nonzero_observer_fixture_exercised_before_leg_reset', ...
    any(after.outer.runtime_vertical_observer_shadow_i_mps2~=0));
before=service.status();
raw.dwell=service.stepGroundReference(.01,true,false);
check('ground_dwell_does_not_advance_flight_phase', ...
    service.status().phase_s==before.phase_s ...
    &&raw.dwell.board_reference_publication_count==0);
raw.expiry1=service.expire(uint64(2),'TEST_DEADLINE_INJECTION');
raw.expiry2=service.expire(uint64(3),'TEST_DEADLINE_INJECTION');
check('first_deadline_preserves_canonical_one_period_hold', ...
    raw.expiry1.applied_command_source=="ONE_PERIOD_LAST_FEASIBLE_HOLD");
check('second_deadline_preserves_canonical_safe_neutral', ...
    raw.expiry2.applied_command_source=="SAFE_NEUTRAL_COMMAND");
check('leg_reset_while_armed_rejected',rejects(@() ...
    service.beginLeg(2,trajectory,1.5,true,true), ...
    'gpenmpcNative:BoardLegTransitionAuthority'));
raw.leg=service.beginLeg(2,trajectory,1.5,true,false,t+3e7,sample(expected,15,t+3e7));
s=service.status();
check('new_leg_resets_phase_and_warm_start_without_resetting_denominator', ...
    s.phase_s==0&&s.phase_rate==1&&s.last_generation==3 ...
    &&s.leg_index==2&&~s.publication_allowed&&raw.leg.warm_start_reset);
r=service.outerRuntime(15,t+3e7,rotor,ones(6,1),zeros(2,1),1.5);
check('new_leg_force_uses_new_payload_canonical_initialization', ...
    r.outer.desired_force_generation==0 ...
    &&r.outer.desired_force_source=="CANONICAL_LEG_INITIAL_FORCE" ...
    &&isequal(r.outer.previous_desired_force_projected_n, ...
      (double(a.profile.mass_properties.base_mass_kg)+1.5)*[0;0;9.80665]) ...
    &&~r.outer.causal_valid&&r.task.leg_index==2);
check('new_leg_resets_observer_and_gp_before_first_outer_solve', ...
    all(r.outer.runtime_vertical_observer_shadow_i_mps2==0) ...
    &&r.outer.runtime_gp_responsibility_blend==0 ...
    &&all(r.outer.runtime_gp_filtered_mean_f_mps2==0) ...
    &&all(r.outer.residual_history_f_mps2==0));
raw.second_leg_outer=service.update(uint64(4),t+3e7,sample(expected,15,t+3e7),r);
check('new_leg_solves_with_fresh_phase_and_real_supervisor', ...
    raw.second_leg_outer.disposition=="FRESH_SOLVER_RESULT" ...
    &&raw.second_leg_outer.solver_audit.coordinated_single_supervisor);

% Compare service snapshot to the direct canonical entry and actually run
% the GP branch with explicitly synthetic closed-evidence inputs.
ee=expected;ee.outer_snapshot_leg_index=2;
ee.outer_snapshot_first_in_leg=true;ee.last_committed_inner_generation=0;
phase=struct('progress_s',0,'progress_rate',1, ...
    'previous_phase_acceleration_s_inv',0);
[snap,ok,why]=gpenmpcNative.makeBoardOuterSnapshot(build,sample(expected,15,t+3e7), ...
    ee,t+3e7,r,trajectory,phase,zeros(1,a.enmpc.decision_dimension),a);
check('canonical_snapshot_input_accepted',ok);
assert(ok,'%s',why);
snap.causal.valid=true;snap.causal.runtime_gp_axis_weight_f=ones(3,1);
snap.causal.runtime_gp_responsibility_blend=1;
snap.causal.runtime_gp_filtered_mean_f_mps2=[.01;0;0];
snap.gp_evidence=struct('available',true,'prediction_sample_closed',true, ...
    'observed_innovation_available',true,'hard_invalid',false,'trust',1);
raw.gp=gpenmpcNative.solveCurrentOuter(snap);
check('real_gp_branch_selected_by_causal_evidence_not_method_label', ...
    ~raw.gp.audit.coordinated_responsibility.exact_b1_required ...
    &&raw.gp.audit.coordinated_selected_method==string(a.enmpc.method));
raw.final=service.status();
bad=physicalRuntime(expected,16,t+4e7,rotor,3,1.0);
check('implicit_new_leg_cannot_bypass_service_ground_transition', ...
    rejects(@()service.stepPhysicalReference(uint64(3),t+4e7, ...
        sample(expected,16,t+4e7),bad,.01),'gpenmpcNative:BoardRuntimeTaskBinding') ...
    &&service.status().failed);
check('host_service_owns_no_hardware_endpoint', ...
    raw.final.hardware_actions==0&&raw.final.com_open==0&&raw.final.board_access==0);
report=struct('status','PASS_HOST_ONLY_REAL_CANONICAL_SOLVER_SERVICE', ...
    'checks',checks,'test_count',numel(checks),'pass_count',sum([checks.pass]), ...
    'source_manifest_sha256',a.binding.source_manifest_sha256, ...
    'configuration_payload_sha256',a.configurationBinding.effective_configuration_payload_sha256, ...
    'gp_model_sha256',a.binding.gp_model_sha256, ...
    'real_service_updates',raw.final.accepted_solver_results, ...
    'async_enabled',useAsync, ...
    'async_submitted',raw.final.async_submitted, ...
    'async_accepted',raw.final.async_accepted, ...
    'injected_deadlines',2,'synthetic_gp_branch_calls',1, ...
    'physical_control_commits',raw.final.physical_runtime.control_commit_count, ...
    'hardware_actions',0,'com_open',0,'live_admitted',false, ...
    'claim','Canonical solver tests with synthetic inputs.');
save(fullfile(outputRoot,'RAW.mat'),'raw','report','-v7.3');
fid=fopen(fullfile(outputRoot,'RESULT.json'),'w','n','UTF-8');assert(fid>=0);
guard=onCleanup(@()fclose(fid));fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
clear guard
% Release service and worker before removing their package from the MATLAB path.
clear serviceGuard
delete(service);
clear service
clear pathGuard
disp(jsonencode(report));
    function check(name,pass)
        checks(end+1)=struct('name',char(name),'pass',logical(pass)); %#ok<AGROW>
        if ~pass
            save(fullfile(outputRoot,'FAILURE_RAW.mat'),'raw','checks');
            error('gpenmpcNative:CanonicalServiceTest','Failed: %s',name);
        end
    end
end

function yes=rejects(f,id)
yes=false;try,f();catch ex,yes=strcmp(ex.identifier,id);end
end
function p=sample(e,g,t)
p=struct('source','PX4_EKF2_MAVLINK_ODOMETRY_331','atomic_estimate',true, ...
    'plant_truth_used',false,'uid',e.uid,'system_id',1,'component_id',1, ...
    'boot_generation',7,'sample_timestamp_ns',t,'odometry_reset_counter',2, ...
    'odometry_frame_id',1,'odometry_child_frame_id',1,'odometry_estimator_type',8, ...
    'position_ned_m',[0;0;-2],'velocity_ned_mps',zeros(3,1), ...
    'quaternion_wxyz_body_to_ned',[1;0;0;0],'omega_frd_rad_s',zeros(3,1), ...
    'position_rx_ns',t-1e5,'attitude_rx_ns',t-1e5,'rates_rx_ns',t-1e5, ...
    'position_generation',g,'attitude_generation',g,'rates_generation',g, ...
    'position_valid',true,'attitude_valid',true,'rates_valid',true);
end
function r=physicalRuntime(e,g,t,rotor,leg,payload)
stamp=@(src)struct('source',src,'rx_ns',t-1e5,'generation',g,'valid',true);
v=stamp('HOST_M600_VIRTUAL_ACTUATOR_INTERFACE');
v.ordering='SOFTWARE_M600_ORDER';v.rotor_thrust_state_n=rotor;
w=stamp('FROZEN_TASK_WIND_ESTIMATOR');w.estimate_xy_mps=zeros(2,1);
r=struct('schema','GPENMPC_PHYSICAL_CAUSAL_RUNTIME_INPUT_V1', ...
    'task_identity_sha256',e.task_identity_sha256,'plant_truth_used',false, ...
    'virtual_actuator',v,'wind',w,'task',struct('source','FROZEN_GPENMPC_TASK_STATE', ...
    'payload_kg',payload,'leg_index',leg));
end
function g=moduleGuard(t)
g=struct('source','PX4_UORB_GPENMPC_SE3_CONTROL_STATUS','valid',true, ...
    'plant_truth_used',false,'rx_ns',t-1e5,'control_mode',1,'failure_reason',0, ...
    'active',true,'state_valid',true,'reference_fresh',true,'segment_fresh',true, ...
    'native_position_controller_disabled',true, ...
    'native_attitude_rate_allocator_enabled',true,'single_publisher_contract_pass',true);
end
function a=actuator(g,t)
c=repmat(.5,16,1);c(7:16)=NaN;
a=struct('mavpackettype','HIL_ACTUATOR_CONTROLS','time_usec',t/1000, ...
    'controls',c,'src_system',1,'src_component',1,'rx_ns',t,'generation',g);
end
