function report=test_load_canonical_runtime_assets(outputDir)
% Actual loader calls, including isolated MATLAB read-boundary fault injection.
arguments
    outputDir (1,1) string
end
root=fileparts(fileparts(mfilename('fullpath')));
evidenceRoot=string(fullfile(root,'evidence'));
configuredOutputRoot=string(getenv('GPENMPC_TEST_OUTPUT_ROOT'));
if strlength(configuredOutputRoot)>0,evidenceRoot=configuredOutputRoot;end
outputDir=canonicalPath(outputDir);
assert(startsWith(lower(outputDir),lower(canonicalPath(evidenceRoot)+filesep)), ...
    'Fixtures must remain under the configured test-output root.');
assert(~isfolder(outputDir)&&~isfile(outputDir),'Refuse to overwrite prior evidence.');
mkdir(outputDir);oldPath=path;oldDirectory=pwd;
guard=onCleanup(@()restoreTestEnvironment(oldDirectory,oldPath)); %#ok<NASGU>
addpath(fullfile(root,'host_runtime'),'-begin');
packageRoot=canonicalPath(fullfile(root,'..','..','assets','canonical'));
checks=struct('name',{},'passed',{},'observed',{});
a=gpenmpcNative.loadCanonicalAssets(packageRoot);
required={'sourceRoot','enmpc','configurationBinding','gpModelPath','gp_model', ...
    'aero','robust','calibration','profile','prediction_context','attitudeContinuity', ...
    'kernelParameters','binding','binding_path'};
check('legacy_consumer_fields_available',all(isfield(a,required)),strjoin(required,','));
check('binding_path_uses_canonical_passport',strcmp(a.binding_path,char(fullfile(packageRoot, ...
    'binding','execution.json')))&& ...
    strcmp(a.binding.binding_path,a.binding_path),a.binding_path);
check('canonical_source160',a.binding.verified_source_entries==160&& ...
    numel(a.binding.entries)==160,'160 verified source entries');
check('all_paths_canonical',all(startsWith(lower(string({a.binding.entries.path})), ...
    lower(packageRoot+filesep))),'No copied legacy runtime fallback');
check('three_real_configuration_calls',numel(a.binding.configuration_chain)==3&& ...
    a.enmpc.coordinated_architecture_enabled&&a.enmpc.command_continuity_enabled, ...
    strjoin(string(a.binding.configuration_chain),' -> '));
check('coordinated_physical_not_ordinary',strcmp(a.enmpc.coordinated_architecture_mode, ...
    'A1_COORDINATED_PHYSICAL')&&a.enmpc.coordinated_physical_gp_application_enabled&& ...
    a.enmpc.coordinated_gp_execution_feedforward_enabled&&a.enmpc.gp_responsibility_gate_enabled, ...
    'A1_COORDINATED_PHYSICAL');
check('timing_030_020_8_160_028',isequal([a.enmpc.outer_period_s,a.enmpc.prediction_step_s, ...
    a.enmpc.horizon_steps,a.enmpc.prediction_horizon_s,a.enmpc.solver_deadline_s], ...
    [.30,.20,8,1.60,.28]),'Outer/prediction/horizon/deadline inspected');
check('normalized_payload_exact',strcmp(a.binding.effective_configuration_payload_sha256, ...
    'A859433D0AA774013341444A4B9AE971A34F12B4FB89C0A004B2CB3E013FCEBA'), ...
    a.binding.effective_configuration_payload_sha256);
check('only_source_path_portability',all(string(a.binding.configuration_difference_fields)=="source_path"), ...
    strjoin(string(a.binding.configuration_difference_fields),','));
check('gp_sha_exact',strcmp(a.binding.gp_model_sha256, ...
    '4A09E9A3D4818B5555CD3439A6D2133026EEA0FDC2774A1FB17F9E05486E5BB2'),a.gpModelPath);
check('kernel_and_prediction_context_ready',numel(a.kernelParameters.rotorUpper)==1&& ...
    all(isfinite(a.kernelParameters.inertia(:)))&& ...
    isa(a.prediction_context.phase_power_fcn,'function_handle'),'No solver/model tick executed');
reject('wrong_root',@()gpenmpcNative.loadCanonicalAssets(outputDir),'gpenmpcNative:CanonicalRoot');
reject('guard_directory_not_package_root',@()gpenmpcNative.loadCanonicalAssets( ...
    fullfile(packageRoot,'binding')),'gpenmpcNative:CanonicalRoot');

% Shadowing is tested in a new current directory because MATLAB current-
% directory functions outrank even addpath(...,''-begin''). The source-root
% checks must reject it before executing the false architecture function.
shadow=fullfile(outputDir,'shadow');mkdir(shadow);
writeText(fullfile(shadow,'gpenmpcApplyArchitectureConfiguration.m'),sprintf([ ...
    'function varargout=gpenmpcApplyArchitectureConfiguration(varargin)\n' ...
    'error(''fixture:ShadowExecuted'',''Legacy shadow must never execute.'');\nend\n']));
cd(shadow);clear gpenmpcApplyArchitectureConfiguration;rehash path;
beforeRejectedPath=path;
reject('old_shadow_path_rejected',@()gpenmpcNative.loadCanonicalAssets(packageRoot), ...
    'gpenmpcNative:CanonicalSourceShadow');
check('shadow_failure_restores_path',strcmp(path,beforeRejectedPath),'Path restored after rejected loader');
cd(oldDirectory);clear gpenmpcApplyArchitectureConfiguration;rehash path;

% Inject corruption into in-memory copies and verify semantic payload checks.
configFixture=fullfile(outputDir,'bad_configuration');mkdir(configFixture);
writeText(fullfile(configFixture,'load.m'),sprintf([ ...
    'function result=load(varargin)\nresult=builtin(''load'',varargin{:});\n' ...
    'if isfield(result,''effectiveRuntimeConfiguration'')\n' ...
    'result.effectiveRuntimeConfiguration.outer_period_s=0.20;\nend\nend\n']));
cd(configFixture);clear load;rehash path;
beforeRejectedPath=path;
reject('wrong_effective_configuration_value_rejected', ...
    @()gpenmpcNative.loadCanonicalAssets(packageRoot),'gpenmpcNative:CanonicalConfigurationValues');
check('configuration_failure_restores_path',strcmp(path,beforeRejectedPath),'Path restored after rejected loader');
cd(oldDirectory);clear load;rehash path;

hashFixture=fullfile(outputDir,'bad_binding_hash');mkdir(hashFixture);
writeText(fullfile(hashFixture,'jsondecode.m'),sprintf([ ...
    'function value=jsondecode(varargin)\nvalue=builtin(''jsondecode'',varargin{:});\n' ...
    'if isstruct(value)&&isfield(value,''schema'')&&strcmp(value.schema,' ...
    '''GPENMPC_RUNTIME_CONFIGURATION_BINDING_V1'')\n' ...
    'value.effective_configuration_payload_sha256=repmat(''0'',1,64);\nend\nend\n']));
cd(hashFixture);clear jsondecode;rehash path;
beforeRejectedPath=path;
reject('wrong_effective_binding_hash_rejected', ...
    @()gpenmpcNative.loadCanonicalAssets(packageRoot),'gpenmpcNative:CanonicalEffectiveBinding');
check('binding_failure_preserves_path',strcmp(path,beforeRejectedPath),'Identity rejection does not mutate path');
cd(oldDirectory);clear jsondecode;rehash path;
b=gpenmpcNative.loadCanonicalAssets(packageRoot);
check('clean_reload_after_fault_injection',strcmp(b.binding.effective_configuration_payload_sha256, ...
    a.binding.effective_configuration_payload_sha256)&&isequaln(a.enmpc,b.enmpc), ...
    'Canonical files and clean loader behavior preserved');
check('no_execution_or_device_actions',a.binding.hardware_actions==0&& ...
    a.binding.scientific_ticks==0&&a.binding.outer_solve_calls==0, ...
    'COM/UDP/model/solver/scientific ticks all zero');
report=struct('schema','CANONICAL_ASSET_LOADER_HOST_TEST_V1','passed',all([checks.passed]), ...
    'checks_passed',nnz([checks.passed]),'checks_total',numel(checks),'checks',checks, ...
    'source_root',a.sourceRoot,'source_count',160, ...
    'source_manifest_sha256',a.binding.source_manifest_sha256, ...
    'normalized_configuration_sha256',a.binding.effective_configuration_payload_sha256, ...
    'gp_model_sha256',a.binding.gp_model_sha256,'hardware_actions',0,'COM_open',0,'UDP_open',0, ...
    'scientific_ticks',0,'outer_solve_calls',0,'claim','Host asset-loading tests.');
writeText(fullfile(outputDir,'RESULT.json'),jsonencode(report,PrettyPrint=true));
fprintf('CANONICAL_ASSET_LOADER %d/%d pass=%d\n',report.checks_passed,report.checks_total,report.passed);
assert(report.passed,'Canonical loader host tests failed.');
    function check(name,passed,observed)
        checks(end+1)=struct('name',name,'passed',logical(passed),'observed',char(string(observed))); %#ok<AGROW>
    end
    function reject(name,f,expected)
        caught='NO_ERROR';try,f();catch problem,caught=problem.identifier;end
        check(name,strcmp(caught,expected),caught);
    end
end
function restoreTestEnvironment(oldDirectory,oldPath)
cd(oldDirectory);path(oldPath);clear load jsondecode gpenmpcApplyArchitectureConfiguration;
end
function value=canonicalPath(value)
value=string(char(java.io.File(char(value)).getCanonicalPath()));
end
function writeText(p,text)
assert(~isfile(p),'Refuse fixture overwrite.');
fid=fopen(p,'w','n','UTF-8');assert(fid>=0);g=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',text);
end
