function report=test_local_outer_preconstruction(outputRoot)
% Test idle-mailbox construction with retained registration data.
arguments,outputRoot (1,1) string,end
build=string(fileparts(fileparts(mfilename('fullpath'))));
addpath(fullfile(build,'tools'),fullfile(build,'host_runtime'), ...
    fullfile(build,'m600_coptersim','matlab_validation'));
addpath(gpenmpc_external_path('native_visual_host_source'),'-end');
assert(~isfolder(outputRoot),'gpenmpcOuterTest:NoOverwrite','Use one new evidence child.');mkdir(outputRoot);
a=gpenmpcNative.loadCanonicalAssets();
taskPath=fullfile(build,'task_packages','cambridge_canonical','MU_CAMBRIDGE_MA_02__CANONICAL_PHYSICAL_TASK.mat');
taskSha='B876546B468265F84BD028AC549B06EF8ADDCB25CBA09CF389A08F4B21290A5F';
bundle=gpenmpcNative.loadRflyCanonicalDeliveryTask(taskPath,taskSha);
[trajectory,~]=gpenmpcNative.bindRflyCanonicalInitialTakeoffTrajectory(bundle.legs{1},zeros(3,1));
cfg=make_m600_board_local_short_config('M600_CANONICAL_DIAGNOSTIC_SAME_6DOF_MODEL', ...
    fullfile(outputRoot,'NO_BOARD_RECEIPT_REQUESTED.json'),a);
task=struct('path',taskPath,'sha256',taskSha,'configuration_sha256',char(a.binding.effective_configuration_payload_sha256), ...
    'environment_policy',rmfield(cfg.delivery_environment_contract,{'initial_payload_kg','remote_port'}),'copter_id',1);
getterPath=fullfile(gpenmpc_external_path('local_original_getter_mex'),'rfly_original_getter_mex.mexw64');
addpath(fileparts(getterPath),'-begin');
resources=struct('task_source',task,'getter_source',struct('exact_path',char(getterPath), ...
    'sha256','FD876F30B4337CC3AAD10B1D2531CF5388020401963EA39422328E9C430D3433'), ...
    'assets',a,'initial_trajectory',trajectory,'preconstruct_outer',true);
timer=tic;objects=prepare_m600_board_local_short_objects(cfg,resources);coldS=toc(timer);
owner=objects.outer;cleanup=onCleanup(@()owner.close()); %#ok<NASGU>
initial=owner.status();
% Reusing the same prepared objects must not create another original worker.
resources=rmfield(resources,'preconstruct_outer');resources.prepared_outer=owner;
resources.decoder_dialect=objects.dialect;
borrowed=prepare_m600_board_local_short_objects(cfg,resources);
sameOwner=isequal(borrowed.outer,owner);
unboundRejected=rejects(@()owner.poll(uint64(1)),'gpenmpcNative:LocalOuterUnbound');
fixture=fullfile(gpenmpc_external_path('local_task_input'),'MATCHED_RLS_RLI.bin');
f=fopen(fixture,'rb');assert(f>=0);fileCleanup=onCleanup(@()fclose(f));
b=reshape(fread(f,Inf,'*uint8'),1029,[]);clear fileCleanup
u=gpenmpcNative.RflyLocalTaskCodec.decode(b(383:end,1));
registered=struct('local_full_inner',true,'identity',u.source.identity,'leg_index',u.leg_index, ...
    'execution_session_sha256',hex(u.execution_session_sha256),'task_sha256',hex(u.task_sha256), ...
    'reference_asset_sha256',hex(u.reference_asset_sha256), ...
    'configuration_sha256',char(a.binding.effective_configuration_payload_sha256));
bad=a;bad.binding.passport_sha256=repmat('0',1,64);
wrongSourceRejected=rejects(@()owner.bindPreparedSession(bad,registered,trajectory, ...
    cfg.local_short.service_cfg.source_max_age_ns,cfg.local_short.service_cfg.command_lifetime_ns), ...
    'gpenmpcNative:LocalOuterPreparedBinding');
timer=tic;owner.bindPreparedSession(a,registered,trajectory,cfg.local_short.service_cfg.source_max_age_ns, ...
    cfg.local_short.service_cfg.command_lifetime_ns);attachS=toc(timer);
bound=owner.status();
duplicateRejected=rejects(@()owner.bindPreparedSession(a,registered,trajectory, ...
    cfg.local_short.service_cfg.source_max_age_ns,cfg.local_short.service_cfg.command_lifetime_ns), ...
    'gpenmpcNative:LocalOuterPreparedOwner');
% An outer caller failure before any MethodService exists still closes this
% same owner. No SOLVE is used to warm the worker or to test cancellation.
try,callerFailure(owner);catch ex,assert(strcmp(ex.identifier,'gpenmpcOuterTest:CallerFailure'));end
closed=owner.status();owner.close();again=owner.status();
checks=struct('name',{},'pass',{});
checks(end+1)=check('one_same_original_owner_before_session',sameOwner&&initial.preconstructed ...
    &&~initial.session_bound&&initial.session_bindings==0&&initial.worker_construction.worker_constructions==1);
checks(end+1)=check('unbound_source_processing_rejected',unboundRejected);
checks(end+1)=check('exact_source_and_once_only_session_binding',wrongSourceRejected&&duplicateRejected ...
    &&bound.session_bound&&bound.session_bindings==1&&isequal(initial.worker_construction,bound.worker_construction));
checks(end+1)=check('no_solve_or_clock_or_command_prepared',initial.worker.submitted==0&&bound.worker.submitted==0 ...
    &&bound.preparation_calls==0&&bound.outer_submissions==0&&isempty(bound.clock)&&isempty(bound.last_command) ...
    &&objects.receipt.original_getter_mex_invocations==0&&objects.receipt.socket_opens==0);
checks(end+1)=check('caller_failure_closes_same_worker_idempotently',closed.closed&&closed.worker_close.clean_stop ...
    &&closed.worker_close.submitted==0&&isequal(closed,again));
checks(end+1)=check('original_source_and_deadline_retained',strcmpi(initial.worker_construction.source_binding_sha256,a.binding.passport_sha256) ...
    &&strcmpi(initial.worker_construction.configuration_payload_sha256,a.binding.effective_configuration_payload_sha256) ...
    &&initial.worker_construction.solver_deadline_s==.28);
paths={which('gpenmpcNative.OuterMailboxWorker'),which('gpenmpcNative.outerMailboxLoop'), ...
    which('gpenmpcNative.RflyLocalOuterService'),which('gpenmpcNative.RflyLocalMethodService'), ...
    which('prepare_m600_board_local_short_objects'),which('execute_m600_board_local_short'),mfilename('fullpath')+".m"};
sources=struct('path',{},'sha256',{});
for k=1:numel(paths),sources(end+1)=struct('path',char(paths{k}),'sha256',m600check.fileSha256(paths{k}));end %#ok<AGROW>
report=struct('schema','GPENMPC_ORIGINAL_OUTER_PRECONSTRUCTION_HOST_V1', ...
    'scope','HOST_ONLY_RETAINED_REGISTRATION_NO_AUTHORITY_NO_SOLVE', ...
    'passed',all([checks.pass]),'checks',checks,'total',numel(checks),'pass_count',sum([checks.pass]), ...
    'timing',struct('pure_objects_including_cold_original_worker_s',coldS, ...
    'original_constant_and_worker_constructor_s',initial.worker_construction.elapsed_s, ...
    'same_owner_session_attach_s',attachS,'diagnostic_not_WCET',true), ...
    'initial',initial,'bound',bound,'closed',closed,'sources',sources, ...
    'solver_calls',0,'getter_calls',0,'socket_opens',0,'COM_opens',0,'NoUI_starts',0,'board_actions',0);
save(fullfile(outputRoot,'RAW.mat'),'initial','bound','closed','report');
f=fopen(fullfile(outputRoot,'RESULT.json'),'w');assert(f>=0);fileCleanup=onCleanup(@()fclose(f));
fprintf(f,'%s\n',jsonencode(report,PrettyPrint=true));clear fileCleanup
disp(jsonencode(report));assert(report.passed,'gpenmpcOuterTest:Checks','Original idle-worker ownership checks failed.');
end
function callerFailure(owner)
cleanup=onCleanup(@()owner.close()); %#ok<NASGU>
error('gpenmpcOuterTest:CallerFailure','Injected caller failure.');
end
function value=rejects(call,identifier)
value=false;try,call();catch ex,assert(strcmp(ex.identifier,identifier),'gpenmpcOuterTest:Unexpected','%s',getReport(ex));value=true;end
end
function r=check(name,pass),r=struct('name',name,'pass',logical(pass));end
function s=hex(b),s=upper(reshape(dec2hex(uint8(b),2).',1,[]));end
