function report=test_canonical_full_inner_runtime(outputRoot)
% Test the stateful full kernel with synthetic observations.
arguments
    outputRoot (1,1) string
end
build=string(fileparts(fileparts(mfilename('fullpath'))));
parent=string(gpenmpc_external_path('native_visual_host_runtime'));
old=path;guard=onCleanup(@()path(old)); %#ok<NASGU>
addpath(fullfile(parent,'src'),'-begin');addpath(fullfile(build,'host_runtime'),'-begin');
assert(~isfolder(outputRoot),'Choose an unused output path.');mkdir(outputRoot);
a=gpenmpcNative.loadCanonicalAssets();
e=struct('uid','HOST_ONLY_SYNTHETIC_SAMPLE','system_id',1,'component_id',1, ...
    'boot_generation',7,'maximum_age_ns',1e8,'maximum_runtime_age_ns',1e8, ...
    'initial_payload_kg',2.27,'canonical_package_root',gpenmpcNative.canonicalAssetRoot(), ...
    'inner_control_contract','CANONICAL_FULL_SE3', ...
    'full_inner_evidence_scope','HOST_ONLY_KERNEL_EXECUTION');
task=repmat('C',1,64);checks=struct('name',{},'pass',{});raw=struct();
r=gpenmpcNative.CurrentPhysicalCausalRuntime(build,e,task,a);
reference=struct('position_m',[0;0;2],'velocity_mps',zeros(3,1), ...
    'acceleration_mps2',zeros(3,1),'jerk_mps3',zeros(3,1));
oracleState=gpenmpcInitializeDesiredAttitudeContinuityState();
max61=0;maxContinuity=0;nonzeroOmega=0;nonzeroOmegaDot=0;
raw.samples=cell(60,1);
for k=1:60
    now=uint64(1e9+k*1e7);[p,rt]=observations(k,now,1,2.27);
    reference.acceleration_mps2=[.2*sin(k*.05);.1*cos(k*.04);0];
    b=r.beginSample(uint64(k),now,p,rt,reference,.01);
    assert(b.accepted,'Begin failed: %s',b.reason);
    cmd=b.full_inner_command;feedback=gpenmpcNative.executeCanonicalFullInnerKernelHost(cmd,a,now+1e6);
    x=cmd.state_up;
    direct=gpenmpcDesiredSe3Command(x,reference,2.27,[0;0], ...
        b.physical_output.compensation_up_mps2,a.calibration,a.profile);
    [expectedAttitude,oracleState]=gpenmpcUpdateDesiredAttitudeContinuity( ...
        oracleState,direct.desired_rotation,.01,k==1,a.attitudeContinuity);
    maxContinuity=max(maxContinuity,norm(expectedAttitude.desired_rotation- ...
        cmd.attitude_command.desired_rotation,'fro'));
    nonzeroOmega=nonzeroOmega+double(norm(cmd.attitude_command.desired_angular_velocity_body_rad_s)>1e-8);
    nonzeroOmegaDot=nonzeroOmegaDot+double(norm(cmd.attitude_command.desired_angular_acceleration_body_rad_s2)>1e-8);
    [ok,reason,~]=gpenmpcNative.validateCanonicalFullInnerFeedback( ...
        feedback,cmd,a,double(now+2e6),double(now),1e8);
    assert(ok,'%s',reason);
    c=r.commitControl(uint64(k),now+2e6,feedback);assert(c.accepted,'Control commit rejected.');
    [oracleRotor,oracle]=gpenmpcRobustSe3Control(x,reference,2.27,[0;0], ...
        b.physical_output.compensation_up_mps2,a.calibration,a.profile,expectedAttitude);
    max61=max(max61,max(abs([oracle.desired_thrust_n;oracle.desired_moment_nm;oracleRotor] ...
        -[feedback.wrench_n_nm;feedback.rotor_command_n])));
    raw.samples{k}=struct('begin',b,'feedback',feedback,'commit',c);
end
s=r.status();
check('sixty_actual_full_kernel_control_commits',s.full_inner_commit_count==60&&~s.failed);
check('same_stateful_gp_closes_prior_interval',s.closed_evidence_count==59&&s.has_pending_prediction);
check('canonical_continuity_not_zero_substituted',nonzeroOmega>0&&nonzeroOmegaDot>0&&maxContinuity<1e-12);
check('canonical_wrench_and_rotor_source_equivalence',max61<1e-10);
check('exactly_one_augmentation_application',all(cellfun(@(x) ...
    x.begin.full_inner_command.augmentation_applications==1 ...
    &&isequal(x.begin.full_inner_command.reference_up,x.begin.reference_up) ...
    &&isequal(x.begin.full_inner_command.augmentation_up_mps2, ...
        x.begin.physical_output.compensation_up_mps2),raw.samples)));
check('committed_force_and_rotor_drive_next_prediction', ...
    s.desired_force_source=="COMMITTED_CANONICAL_FULL_SE3_KERNEL_HOST_ONLY" ...
    &&isequal(r.outerRuntimeState().previous_committed_rotor_command_n, ...
    raw.samples{60}.feedback.rotor_command_n));
check('new_path_does_not_publish_legacy_ned_reference',all(cellfun(@(x) ...
    ~x.begin.publication_allowed&&x.begin.host_kernel_execution_allowed ...
    &&~x.begin.reference_ned_publication_allowed&&~x.begin.board_publication_authority ...
    &&~x.commit.board_consumption_proven,raw.samples)));
% Check malformed returns against an independent source oracle and sample tuple.
cmd=raw.samples{60}.begin.full_inner_command;f=raw.samples{60}.feedback;
variants={f,f,f,f,f,f,f,f,f};
variants{1}.generation=uint64(59);variants{2}.estimate_sample_timestamp_ns=uint64(1);
variants{3}.kernel_source_sha256=repmat('0',1,64);variants{4}.wrench_n_nm(2)=NaN;
variants{5}.rotor_command_n(1)=variants{5}.rotor_command_n(1)+.01;
variants{6}.diagnostic51(1)=variants{6}.diagnostic51(1)+1;
variants{7}.board_consumption_proven=true;variants{8}.evidence_scope='LIVE_BOARD';
variants{9}.rx_ns=double(1e9);
for k=1:numel(variants)
    [ok,~,~]=gpenmpcNative.validateCanonicalFullInnerFeedback(variants{k},cmd,a,1.603e9,1.60e9,1e8);
    check("negative_return_"+k,~ok);
end
now=uint64(1.62e9);[p,rt]=observations(61,now,2,1.5);
r.prepareLegTransition(2,1.5,now,p);
b=r.beginSample(uint64(61),now,p,rt,reference,.01);
check('new_leg_resets_actual_attitude_state',b.accepted ...
    &&b.full_inner_command.attitude_command.reset_active ...
    &&all(b.full_inner_command.attitude_command.desired_angular_velocity_body_rad_s==0));
f=gpenmpcNative.executeCanonicalFullInnerKernelHost(b.full_inner_command,a,now+1e6);
c=r.commitControl(uint64(61),now+2e6,f);
check('new_payload_full_control_and_causal_commit',c.accepted&&r.status().leg_reset_count==2);
% Check saturation-aware authority memory and bounded actuator output.
rs=gpenmpcNative.CurrentPhysicalCausalRuntime(build,e,task,a);
now=uint64(2e9);[p,rt]=observations(1,now,1,2.27);p.omega_frd_rad_s=[20;0;0];
large=reference;large.acceleration_mps2=[0;0;100];
b=rs.beginSample(uint64(1),now,p,rt,large,.01);assert(b.accepted,'%s',b.reason);
f=gpenmpcNative.executeCanonicalFullInnerKernelHost(b.full_inner_command,a,now+1e6);
check('projection_and_rotor_clipping_actually_exercised',f.diagnostic51(49)>1e-6&&logical(f.diagnostic51(51)));
c=rs.commitControl(uint64(1),now+2e6,f);
check('canonical_fail_soft_authority_not_replaced_by_legacy_domain',c.accepted ...
    &&rs.status().robust_authority_scale<1&&all(f.rotor_command_n>=0) ...
    &&all(f.rotor_command_n<=a.kernelParameters.rotorUpper));
% Generation gap and legacy mixed-controller return both latch, no reset.
rr=gpenmpcNative.CurrentPhysicalCausalRuntime(build,e,task,a);
[p,rt]=observations(1,now,1,2.27);b=rr.beginSample(uint64(1),now,p,rt,reference,.01);
c=rr.commitV7NominalControl(uint64(1),now+1e6,struct(),struct());
check('legacy_v7_return_cannot_enter_full_method',~c.accepted&&rr.status().failed);
b=rr.beginSample(uint64(2),now+1e7,p,rt,reference,.01);
check('fault_latch_not_cleaned_by_next_sample',~b.accepted);
bad=e;bad.full_inner_evidence_scope='LIVE_BOARD';
check('unimplemented_live_path_rejected_not_simulated',rejects(@() ...
    gpenmpcNative.CurrentPhysicalCausalRuntime(build,bad,task,a), ...
    'gpenmpcNative:FullInnerDeploymentNotBound'));
check('all_host_only_no_hardware_or_plant',r.status().hardware_actions==0 ...
    &&~r.status().final_hil_admission);
% A fresh board-session owner after ground service retains the GLOBAL task
% leg number while resetting exactly the same numerical per-leg state.
e3=e;e3.initial_leg_index=3;e3.initial_payload_kg=1.5;
third=gpenmpcNative.CurrentPhysicalCausalRuntime(build,e3,task,a);
e1=e;e1.initial_payload_kg=1.5;
first=gpenmpcNative.CurrentPhysicalCausalRuntime(build,e1,task,a);
now3=uint64(3e9);[p3,rt3]=observations(1,now3,3,1.5);
b3=third.beginSample(uint64(1),now3,p3,rt3,reference,.01);
[p1,rt1]=observations(1,now3,1,1.5);
b1=first.beginSample(uint64(1),now3,p1,rt1,reference,.01);
check('new_session_global_leg_three_not_relabelled_one',b3.accepted&&b1.accepted ...
    &&b3.full_inner_command.attitude_command.reset_active&&third.status().leg_reset_count==1);
f3=gpenmpcNative.executeCanonicalFullInnerKernelHost(b3.full_inner_command,a,now3+1e6);
f1=gpenmpcNative.executeCanonicalFullInnerKernelHost(b1.full_inner_command,a,now3+1e6);
check('global_leg_ordinal_does_not_change_kernel_or_initial_observer', ...
    isequal(f3.wrench_n_nm,f1.wrench_n_nm)&&isequal(f3.rotor_command_n,f1.rotor_command_n) ...
    &&isequal(f3.diagnostic51,f1.diagnostic51)&&third.status().control_commit_count==0);
c3=third.commitControl(uint64(1),now3+2e6,f3);
check('new_session_third_leg_actual_full_commit',c3.accepted&&third.status().full_inner_commit_count==1);
for invalid={0,-1,1.5,NaN,Inf,[1,2]}
    bad=e;bad.initial_leg_index=invalid{1};
    check("bad_initial_global_leg_"+numel(checks),rejects(@() ...
        gpenmpcNative.CurrentPhysicalCausalRuntime(build,bad,task,a),'gpenmpcNative:CanonicalInitialLeg'));
end
report=struct('status','PASS_HOST_ONLY_STATEFUL_FULL_CANONICAL_INNER_RUNTIME', ...
    'checks',checks,'test_count',numel(checks),'pass_count',sum([checks.pass]), ...
    'actual_full_kernel_samples',64,'synthetic_estimate_inputs',true, ...
    'outer_solver_calls',0,'dynamics_plant_count',0,'hardware_actions',0, ...
    'live_board_consumption_proven',false,'maximum_control_error',max61, ...
    'maximum_continuity_error',maxContinuity,'nonzero_omega',nonzeroOmega, ...
    'nonzero_omega_dot',nonzeroOmegaDot,'final_runtime',r.status());
report.source_sha256=struct('runtime',gpenmpcNative.fileSha256(which('gpenmpcNative.CurrentPhysicalCausalRuntime')), ...
    'builder',gpenmpcNative.fileSha256(which('gpenmpcNative.prepareCanonicalFullInnerCommand')), ...
    'consumer',gpenmpcNative.fileSha256(which('gpenmpcNative.validateCanonicalFullInnerFeedback')));
save(fullfile(outputRoot,'RAW.mat'),'raw','report','-v7.3');
fid=fopen(fullfile(outputRoot,'RESULT.json'),'w','n','UTF-8');assert(fid>=0);
fg=onCleanup(@()fclose(fid));fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));clear fg
disp(jsonencode(report));
    function check(name,ok)
        checks(end+1)=struct('name',name,'pass',logical(ok)); %#ok<AGROW>
        if ~ok,save(fullfile(outputRoot,'FAILURE_RAW.mat'),'raw','checks');end
        assert(ok,'gpenmpcNative:FullInnerRuntimeTest','%s',name);
    end
    function [p,rt]=observations(g,now,leg,payload)
        p=struct('source','PX4_EKF2_MAVLINK_ODOMETRY_331','atomic_estimate',true, ...
            'plant_truth_used',false,'uid',e.uid,'system_id',1,'component_id',1, ...
            'boot_generation',7,'sample_timestamp_ns',uint64(g)*uint64(1e7), ...
            'odometry_reset_counter',2,'odometry_frame_id',1, ...
            'odometry_child_frame_id',1,'odometry_estimator_type',8, ...
            'position_ned_m',[0;0;-2], ...
            'velocity_ned_mps',zeros(3,1),'quaternion_wxyz_body_to_ned',[1;0;0;0], ...
            'omega_frd_rad_s',zeros(3,1),'position_rx_ns',double(now)-1e5, ...
            'attitude_rx_ns',double(now)-1e5,'rates_rx_ns',double(now)-1e5, ...
            'position_generation',g,'attitude_generation',g,'rates_generation',g, ...
            'position_valid',true,'attitude_valid',true,'rates_valid',true);
        v=struct('source','HOST_M600_VIRTUAL_ACTUATOR_INTERFACE','valid',true, ...
            'generation',g,'rx_ns',double(now)-1e5,'ordering','SOFTWARE_M600_ORDER', ...
            'rotor_thrust_state_n',ones(6,1)*20);
        w=struct('source','FROZEN_TASK_WIND_ESTIMATOR','valid',true, ...
            'generation',g,'rx_ns',double(now)-1e5,'estimate_xy_mps',zeros(2,1));
        rt=struct('schema','GPENMPC_PHYSICAL_CAUSAL_RUNTIME_INPUT_V1', ...
            'task_identity_sha256',task,'plant_truth_used',false, ...
            'virtual_actuator',v,'wind',w,'task',struct('source','FROZEN_GPENMPC_TASK_STATE', ...
            'payload_kg',payload,'leg_index',leg));
    end
end
function ok=rejects(f,id)
ok=false;try,f();catch ex,ok=strcmp(ex.identifier,id);end
end
