function report=test_local_outer_observation(outputRoot)
% Decode retained C input/output fixtures into the MATLAB outer-observation schema.
arguments,outputRoot (1,1) string,end
build=string(fileparts(fileparts(mfilename('fullpath'))));addpath(fullfile(build,'host_runtime'),'-begin');
old=gpenmpc_external_path('native_visual_host_source');addpath(old,'-end');
a=gpenmpcNative.loadCanonicalAssets();
b=gpenmpcNative.loadRflyCanonicalDeliveryTask(fullfile(build,'task_packages','cambridge_canonical','MU_CAMBRIDGE_MA_02__CANONICAL_PHYSICAL_TASK.mat'), ...
    'B876546B468265F84BD028AC549B06EF8ADDCB25CBA09CF389A08F4B21290A5F');
[trajectory,~]=gpenmpcNative.bindRflyCanonicalInitialTakeoffTrajectory(b.legs{1},zeros(3,1));
assert(~isfolder(outputRoot));mkdir(outputRoot);
inputPath=fullfile(gpenmpc_external_path('local_task_input'),'MATCHED_RLS_RLI.bin');
commitPath=fullfile(gpenmpc_external_path('committed_state_reference'),'COMMITTED_RLC1.bin');
pairs=reshape(read(inputPath),1029,[]);commits=reshape(read(commitPath),1398,[]);
checks=struct('name',{},'pass',{});snapshots=cell(3,1);receipts=cell(3,1);
for k=1:3
    source=struct('message',pairs(1:382,k),'original_host_receive_ns',uint64(1000000000+k*10000000));
    input=pairs(383:end,k);u=gpenmpcNative.RflyLocalTaskCodec.decode(input);
    registered=struct('identity',u.source.identity,'leg_index',u.leg_index, ...
        'execution_session_sha256',hex(u.execution_session_sha256),'task_sha256',hex(u.task_sha256), ...
        'reference_asset_sha256',hex(u.reference_asset_sha256),'configuration_sha256',hex(u.configuration_sha256));
    committed=struct('message',commits(:,k),'original_host_receive_ns',source.original_host_receive_ns+uint64(1));
    [s,r]=gpenmpcNative.makeLocalCommittedOuterSnapshot(a,trajectory,zeros(1,a.enmpc.decision_dimension),source,committed,input,registered, ...
        source.original_host_receive_ns+uint64(2),uint64(1000000));
    c=gpenmpcNative.RflyLocalCommittedDecoder(committed.message,committed.original_host_receive_ns);
    check(sprintf('actual_C_closed_fields_%d',k),isequal(s.gp_evidence,c.closed_gp_evidence) ...
        &&isequal(s.observation.previous_desired_force_n,c.state64(61:63)) ...
        &&isequal(s.observation.previous_rotor_command_n,c.state64(55:60)) ...
        &&isequal(s.causal.runtime_gp_axis_weight_f,c.state64(51:53)));
    check(sprintf('actual_board_phase_not_host_step_%d',k),s.phase.progress_s==c.installed_phase2(1) ...
        &&s.phase.progress_rate==c.installed_phase2(2)&&s.phase.previous_phase_acceleration_s_inv==c.reference6(3));
    check(sprintf('source_age_not_renewed_%d',k),s.snapshot_timestamp_ns==double(source.original_host_receive_ns) ...
        &&~r.host_inner_or_plant_step&&~r.next_open_GP_used&&~s.plant_truth_used);
    snapshots{k}=s;receipts{k}=r;
    held=struct('held_input_bytes',input,'original_input_source',source);
    [hs,hr]=gpenmpcNative.makeLocalCommittedOuterSnapshot(a,trajectory,zeros(1,a.enmpc.decision_dimension),source,committed,held,registered, ...
        source.original_host_receive_ns+uint64(2),uint64(1000000));
    check(sprintf('original_slow_input_actual_fast_state_%d',k),isequaln(hs,s)&&hr.valid_held_slow_input ...
        &&hr.slow_input_source_generation==u.source.source_generation);
    parsedSource=source;parsedSource.decoded=gpenmpcNative.RflyLocalSnapshotDecoder(source.message,source.original_host_receive_ns);
    parsedCommit=committed;parsedCommit.decoded=c;
    parsedHeld=held;parsedHeld.original_input_source=parsedSource;parsedHeld.held_input_decoded=u;
    [reuse,reuseReceipt]=gpenmpcNative.makeLocalCommittedOuterSnapshot(a,trajectory,zeros(1,a.enmpc.decision_dimension), ...
        parsedSource,parsedCommit,parsedHeld,registered,source.original_host_receive_ns+uint64(2),uint64(1000000));
    check(sprintf('same_IO_decodes_reuse_identical_outer_numerics_%d',k),isequaln(reuse,hs)&&isequaln(reuseReceipt,hr));
    [dynamic,dynamicReceipt]=gpenmpcNative.makeLocalCommittedOuterSnapshot(a,trajectory,zeros(1,a.enmpc.decision_dimension), ...
        parsedSource,parsedCommit,parsedHeld,registered,source.original_host_receive_ns+uint64(2),uint64(1000000),true);
    fixedFields={'source_root','config','context','gp_model','trajectory'};
    check(sprintf('dynamic_only_preserves_all_original_numerics_and_time_%d',k), ...
        isequaln(dynamic,rmfield(reuse,fixedFields))&&isequaln(dynamicReceipt,reuseReceipt));
end
bad=parsedSource;bad.message(132)=bitxor(bad.message(132),uint8(1));
reject('retained_source_must_match_all_original_bytes',@()gpenmpcNative.makeLocalCommittedOuterSnapshot(a,trajectory,[], ...
    bad,parsedCommit,parsedHeld,registered,source.original_host_receive_ns+uint64(2),uint64(1000000)));
bad=parsedCommit;bad.original_host_receive_ns=bad.original_host_receive_ns+uint64(1);
reject('retained_commit_cannot_refresh_original_receive_time',@()gpenmpcNative.makeLocalCommittedOuterSnapshot(a,trajectory,[], ...
    parsedSource,bad,parsedHeld,registered,source.original_host_receive_ns+uint64(2),uint64(1000000)));
bad=parsedHeld;bad.held_input_bytes(584)=bitxor(bad.held_input_bytes(584),uint8(1));
reject('retained_input_must_match_successful_send_bytes',@()gpenmpcNative.makeLocalCommittedOuterSnapshot(a,trajectory,[], ...
    parsedSource,parsedCommit,bad,registered,source.original_host_receive_ns+uint64(2),uint64(1000000)));
reject('retained_parse_still_rejects_expired_source',@()gpenmpcNative.makeLocalCommittedOuterSnapshot(a,trajectory,[], ...
    parsedSource,parsedCommit,parsedHeld,registered,source.original_host_receive_ns+uint64(1000001),uint64(1000000)));
badHeld=held;badHeld.original_input_source.message=pairs(1:382,1);
% Test the .120 s outer budget separately from the .050 s inner-input budget.
% Reject a one-nanosecond excess while preserving source and commit fields.
outerBudget=uint64(round((.4-.28)*1e9));
[lateOuter,lateReceipt]=gpenmpcNative.makeLocalCommittedOuterSnapshot(a,trajectory,zeros(1,a.enmpc.decision_dimension), ...
    source,committed,held,registered,source.original_host_receive_ns+outerBudget,outerBudget);
check('slow_outer_120ms_keeps_original_source_and_math',isequaln(lateOuter,s) ...
    &&lateReceipt.no_retimestamp&&lateOuter.snapshot_timestamp_ns==double(source.original_host_receive_ns));
reject('slow_outer_120ms_plus_1ns_rejected',@()gpenmpcNative.makeLocalCommittedOuterSnapshot(a,trajectory,[], ...
    source,committed,held,registered,source.original_host_receive_ns+outerBudget+uint64(1),outerBudget));
reject('held_input_source_cannot_be_fabricated',@()gpenmpcNative.makeLocalCommittedOuterSnapshot(a,trajectory,[],source,committed,badHeld,registered, ...
    source.original_host_receive_ns+uint64(2),uint64(1000000)));
reject('source_too_old',@()gpenmpcNative.makeLocalCommittedOuterSnapshot(a,trajectory,[],source,committed,input,registered, ...
    source.original_host_receive_ns+uint64(1000001),uint64(1000000)));
bad=registered;bad.leg_index=uint32(2);reject('wrong_leg',@()gpenmpcNative.makeLocalCommittedOuterSnapshot(a,trajectory,[],source,committed,input,bad, ...
    source.original_host_receive_ns+uint64(2),uint64(1000000)));
bad=committed;bad.message=commits(:,1);reject('different_committed_source',@()gpenmpcNative.makeLocalCommittedOuterSnapshot(a,trajectory,[],source,bad,input,registered, ...
    source.original_host_receive_ns+uint64(2),uint64(1000000)));
[initial,r]=gpenmpcNative.makeLocalCommittedOuterSnapshot(a,trajectory,zeros(1,a.enmpc.decision_dimension),source,[],input,registered, ...
    source.original_host_receive_ns+uint64(2),uint64(1000000));
check('explicit_initializer_no_closed_evidence_invention',~initial.gp_evidence.available&&~initial.causal.valid ...
    &&initial.phase.progress_s==0&&r.first_explicit_leg_initializer);
% A real first outer solve cannot depend on its own not-yet-existing command.
% Same retained numerical fields, without an invented zero-command RLI frame.
bound=struct('schema','RFLY_LOCAL_ORIGINAL_INPUT_BINDING_V1','source',u.source,'rotor',u.rotor, ...
    'payload',u.payload,'wind',u.wind,'leg_index',u.leg_index,'numerical_inputs_complete',true,'control_authority',false);
[uncommanded,uncommandedReceipt]=gpenmpcNative.makeLocalCommittedOuterSnapshot(a,trajectory,zeros(1,a.enmpc.decision_dimension), ...
    source,[],bound,registered,source.original_host_receive_ns+uint64(2),uint64(1000000));
check('bootstrap_original_measurements_without_fake_outer_command',isequaln(uncommanded,initial)&&isequaln(uncommandedReceipt,r));
observation=gpenmpcNative.RflyLocalTaskCodec.originalNumericalObservation(bound,source.message,source.original_host_receive_ns,registered);
check('bootstrap_has_no_command_or_authority',isempty(observation.outer)&&~observation.outer_command_fabricated&&~observation.control_authority);
badBound=bound;badBound.numerical_inputs_complete=false;
reject('incomplete_uncommanded_observation_rejected',@()gpenmpcNative.makeLocalCommittedOuterSnapshot(a,trajectory,[],source,[],badBound,registered, ...
    source.original_host_receive_ns+uint64(2),uint64(1000000)));
badBound=bound;badBound.source.source_generation=badBound.source.source_generation+uint64(1);
reject('wrong_source_uncommanded_observation_rejected',@()gpenmpcNative.makeLocalCommittedOuterSnapshot(a,trajectory,[],source,[],badBound,registered, ...
    source.original_host_receive_ns+uint64(2),uint64(1000000)));
report=struct('passed',all([checks.pass]),'test_count',numel(checks),'checks',checks, ...
    'input_fixture',inputPath,'committed_fixture',commitPath, ...
    'boundary','Compatible HOST C fixtures test outer-observation encoding.', ...
    'hardware_actions',0,'outer_solve_calls',0,'host_inner_steps',0);
save(fullfile(outputRoot,'RAW.mat'),'snapshots','receipts','initial','report');
f=fopen(fullfile(outputRoot,'RESULT.json'),'wt');g=onCleanup(@()fclose(f));fprintf(f,'%s\n',jsonencode(report,PrettyPrint=true));clear g
disp(jsonencode(report));
    function check(n,ok),checks(end+1)=struct('name',n,'pass',logical(ok));assert(ok,'%s',n);end
    function reject(n,fn),ok=false;try,fn();catch ex,ok=startsWith(string(ex.identifier),'gpenmpcNative:');if ~ok,rethrow(ex);end,end;check(n,ok);end
end
function b=read(p),f=fopen(p,'rb');assert(f>=0);g=onCleanup(@()fclose(f));b=fread(f,Inf,'*uint8');end
function s=hex(b),s=upper(reshape(dec2hex(b,2).',1,[]));end
