function report=test_rfly_async_preparation(outputRoot,initialLeg)
% Test asynchronous generation-zero preparation with one worker and C++ fixtures.
arguments
    outputRoot (1,1) string
    initialLeg (1,1) double = 1
end
build=string(fileparts(fileparts(mfilename('fullpath'))));
parent=string(gpenmpc_external_path('native_visual_host_runtime'));
old=path; %#ok<NASGU> Caller batch owns process path; retain class definitions through destructor.
addpath(fullfile(parent,'src'),'-begin');addpath(fullfile(build,'host_runtime'),'-begin');
assert(~isfolder(outputRoot));mkdir(outputRoot);checks=struct('name',{},'pass',{});raw=struct();
probe=fullfile(gpenmpc_external_path('rfly_board_commit_consumer'),'actual_exchange_probe');
kernel=fullfile(gpenmpc_external_path('full_inner_px4_float_mapping'),'MATLAB_ARGUMENTS_AND_EXPECTED.bin');
states=fullfile(gpenmpc_external_path('full_inner_px4_float_mapping'),'MATLAB_NED_AND_MAPPED_STATE.bin');
args=javaArray('java.lang.String',9);
values={'wsl.exe','-d','Ubuntu-24.04','--',linux(probe),linux(kernel),linux(states),linux(outputRoot),'serve'};
for k=1:9,args(k)=java.lang.String(values{k});end
builder=java.lang.ProcessBuilder(args);builder.redirectErrorStream(true);process=builder.start();
processCleanup=onCleanup(@()process.destroy()); %#ok<NASGU>
reader=java.io.BufferedReader(java.io.InputStreamReader(process.getInputStream()));
writer=java.io.PrintWriter(process.getOutputStream(),true);
raw.cpp_export=string(reader.readLine());echoBytes=readBytes(fullfile(outputRoot,'ACTUAL_FIXTURE_ECHO119.bin'));
check('actual_cpp_register_confirm_echo119',numel(echoBytes)==119&&raw.cpp_export=="READY_ACTUAL_FIXTURE_SESSION_AND_SOURCES");
a=gpenmpcNative.loadCanonicalAssets();
echo=struct('identity_semantics','BoardRegisteredExecutionSessionGenerationV1', ...
    'host_challenge',decode(echoBytes(6:21),'uint64'),'uid',decode(echoBytes(22:29),'uint64'), ...
    'system',echoBytes(30),'component',echoBytes(31),'board_registration_hrt_us',decode(echoBytes(32:39),'uint64'), ...
    'process_session_generation',decode(echoBytes(40:47),'uint64'), ...
    'link_lifecycle_generation',decode(echoBytes(48:55),'uint64'), ...
    'configuration_payload_sha256',hex(echoBytes(56:87)));
sessionSha=hex(echoBytes(88:119));now=gpenmpcNative.rflyOriginalHostMonotonicNs();
assoc=struct('schema','GPENMPC_RFLY_REGISTERED_SESSION_ASSOCIATION_V1', ...
    'registration_result','Registered','echo_confirmation_result','Confirmed','echo',echo, ...
    'original_host_challenge',echo.host_challenge,'original_host_receive_ns',now, ...
    'execution_session_sha256',sessionSha,'provenance','ACTUAL_EXISTING_SESSION_BOUND_GUARD_HOST_FIXTURE');
e=struct('uid',string(echo.uid),'system_id',1,'component_id',1,'boot_generation',echo.process_session_generation, ...
    'maximum_age_ns',1e8,'maximum_runtime_age_ns',1e8,'canonical_package_root',gpenmpcNative.canonicalAssetRoot(), ...
    'configuration_payload_sha256',echo.configuration_payload_sha256,'initial_payload_kg',2.27, ...
    'async_outer_required',true,'task_identity_sha256',repmat('C',1,64), ...
    'inner_control_contract','CANONICAL_FULL_SE3','full_inner_evidence_scope','BOARD_COMMIT_RFC1');
e.rfly_board_commit=struct('execution_session_sha256',sessionSha,'identity_semantics',echo.identity_semantics, ...
    'link_lifecycle_generation',echo.link_lifecycle_generation,'board_registration_hrt_us',echo.board_registration_hrt_us, ...
    'reference_max_age_us',uint64(400000),'outer_max_age_us',uint64(400000), ...
    'generated_arm_source_sha256','A47F1C255BDAC1DAE712494BE8D9D66FC4F83138DBA9B0C2E3A31E114D4ABD0F', ...
    'wrapper_matlab_source_sha256','9117D3CDF8E924A253F4C444CDD467E4850D6F11CBF5744B26375B950E2A95B5');
e.initial_leg_index=initialLeg;
origin=struct('link_lifecycle_generation',echo.link_lifecycle_generation,'execution_session_sha256',sessionSha, ...
    'source_system',uint8(1),'source_component',uint8(1));
sbytes=cell(1,3);for k=1:3,sbytes{k}=readBytes(fullfile(outputRoot,"SOURCE_"+k+".bin"));end
s=gpenmpcNative.RflySnapshotSample(sbytes{1},now,e);[state,ok]=gpenmpcNative.px4EstimateState(s,e,now);assert(ok);
coef=zeros(3,8);coef(:,1)=state(1:3);coef(:,2)=[.1;0;0];tr=struct('total_duration_s',10,'coefficients_ascending',coef);
dialect=mavlinkdialect('common.xml',2);
serializer=mavlinkio(dialect,SystemID=42,ComponentID=191,ComponentType='MAV_TYPE_GCS',AutopilotType='MAV_AUTOPILOT_INVALID');
bad=assoc;bad.echo.process_session_generation=echo.process_session_generation+uint64(1);
check('altered_registered_generation_rejected',rejects(@()gpenmpcNative.RflyHostExchangeService(build,e,tr,bad,serializer,dialect,8)));
bad=assoc;bad.original_host_challenge(1)=bad.original_host_challenge(1)+uint64(1);
check('challenge_echo_mismatch_rejected',rejects(@()gpenmpcNative.RflyHostExchangeService(build,e,tr,bad,serializer,dialect,8)));
x=gpenmpcNative.RflyHostExchangeService(build,e,tr,assoc,serializer,dialect,8);
xcleanup=onCleanup(@()x.close()); %#ok<NASGU>
now=gpenmpcNative.rflyOriginalHostMonotonicNs();[v,w]=observed(63,now);
raw.prepare_begin=x.beginPrepare(sbytes{1},now,now,v,w,origin);
check('begin_preparation_returns_before_result_or_state_commit', ...
    raw.prepare_begin.status=="PREPARATION_SUBMITTED"&&isempty(raw.prepare_begin.packets) ...
    &&~x.status().coordinator.initialized&&x.status().coordinator.state=="PREPARING" ...
    &&x.status().coordinator.service.preparation_in_flight ...
    &&x.status().coordinator.service.phase_s==0&&x.status().coordinator.actual_solver_submissions==0);
% Explicit delayed-poll negative control uses actual elapsed HOST time. The
% same gen-0 diagnostic may complete, but cannot be labelled fresh control.
pause(.30);raw.prepare_polls={};timer=tic;
while ~x.status().coordinator.initialized&&toc(timer)<60
    raw.prepare=x.pollPreparation(gpenmpcNative.rflyOriginalHostMonotonicNs());
    raw.prepare_polls{end+1}=raw.prepare; %#ok<AGROW>
    if raw.prepare.status=="PREPARATION_PENDING",pause(.001);end
end
check('real_expired_gen0_is_only_cold_diagnostic',raw.prepare.status=="PASS_HOST_PREPARATION" ...
    &&raw.prepare.preparation_expired&&raw.prepare.worker_expired_count==1 ...
    &&raw.prepare.preparation_result_timing=="COLD_REHEARSAL_COMPLETED_EXPIRED" ...
    &&~raw.prepare.result_fresh_for_control&&~raw.prepare.generation_consumed ...
    &&~raw.prepare.command_committed&&raw.prepare.generation==0 ...
    &&raw.prepare.numerical_state_unchanged&&raw.prepare.worker_submitted_count==1);
check('prepare_polls_preserve_original_time_boundary_and_no_clock_progress', ...
    all(cellfun(@(p)p.original_submit_ns==raw.prepare_begin.original_submit_ns ...
        &&p.original_snapshot_ns==raw.prepare_begin.original_snapshot_ns ...
        &&p.source_clock_unchanged,raw.prepare_polls)) ...
    &&isequaln(raw.prepare.input_boundary,raw.prepare_begin.input_boundary) ...
    &&x.status().coordinator.service.physical_runtime.begin_count==0 ...
    &&x.status().coordinator.service.physical_runtime.control_commit_count==0 ...
    &&~x.status().coordinator.service.fresh_outer_for_current_leg);
check('real_existing_preparation_and_single_worker',raw.prepare.status=="PASS_HOST_PREPARATION" ...
    &&x.status().coordinator.owned_outer_services==1&&x.status().owned_io_endpoints==0);
now=gpenmpcNative.rflyOriginalHostMonotonicNs();[v,w]=observed(64,now);
raw.startup_rx_ns=now;
raw.source2=x.disarmedStartupSnapshot(sbytes{2},now,now,v,w,origin,false);
check('disarmed_actual_async_submit_no_inner_payload',raw.source2.status=="DISARMED_STARTUP_OUTER_SUBMITTED_NO_INNER_COMMAND" ...
    &&isempty(raw.source2.packets)&&x.status().coordinator.actual_solver_submissions==1);
raw.paused=x.status();
check('global_task_leg_preserved_clock_is_session_local', ...
    raw.paused.coordinator.global_task_leg_index==initialLeg ...
    &&raw.paused.coordinator.clock_global_task_leg_offset==initialLeg-1 ...
    &&raw.paused.coordinator.source_clock.leg_id==1 ...
    &&isnan(raw.paused.coordinator.service.physical_runtime.current_leg));
check('startup_does_not_advance_phase_flight_observer_or_inner', ...
    raw.paused.coordinator.state=="PREPARED_PAUSED"&&raw.paused.coordinator.source_clock.total_flight_time_ns==uint64(0) ...
    &&raw.paused.coordinator.service.phase_s==0&&raw.paused.coordinator.service.phase_rate==1 ...
    &&raw.paused.coordinator.service.physical_runtime.begin_count==0 ...
    &&raw.paused.coordinator.service.physical_runtime.control_commit_count==0 ...
    &&raw.paused.coordinator.service.physical_runtime.physical_accepted_sample_count==0 ...
    &&~raw.paused.pending_command&&~raw.paused.startup.ready);
raw.polls={};timer=tic;
while x.status().context.outer_commits==0&&toc(timer)<3
    pause(.001);raw.polls{end+1}=x.poll(gpenmpcNative.rflyOriginalHostMonotonicNs()); %#ok<AGROW>
end
check('actual_async_response_bound_to_original_ticket',x.status().context.outer_commits==1 ...
    &&x.status().coordinator.service.fresh_outer_for_current_leg);
raw.ready=x.status();
check('startup_readiness_reports_both_original_deadlines_no_arm',raw.ready.startup.ready ...
    &&raw.ready.startup.original_outer_expiry_host_ns==raw.startup_rx_ns+uint64(400000000) ...
    &&raw.ready.startup.original_outer_expiry_board_us==uint64(1410000) ...
    &&~raw.ready.startup.arm_admission&&~raw.ready.startup.HOST_HRT_mapping ...
    &&raw.ready.coordinator.service.phase_s==0&&raw.ready.coordinator.service.physical_runtime.begin_count==0);
now=gpenmpcNative.rflyOriginalHostMonotonicNs();[v,w]=observed(65,now);
raw.source3=x.source(sbytes{3},now,now,v,w,origin);
check('held_outer_current_reference_and_actual_source_tags',raw.source3.status=="PREPARED_CONTEXT_AND_COMMAND_BYTES_NO_SEND" ...
    &&numel(raw.source3.packets)==7&&raw.source3.binding.command_generation==65 ...
    &&raw.source3.binding.reference_generation==1&&raw.source3.binding.outer_generation==1 ...
    &&~isequal(raw.source3.context.outer_source_ticket,raw.source3.context.reference_source_ticket));
check('RSP1_not_relabelled_as_MAVLink331',raw.source3.original_source.source=="PX4_PRIVATE_VEHICLE_ODOMETRY_RSP1" ...
    &&raw.source3.prepared.full_inner_command.evidence_scope=="BOARD_COMMIT_RFC1");
writeBytes(fullfile(outputRoot,'CONTEXT316.bin'),raw.source3.context_bytes);
writeBytes(fullfile(outputRoot,'COMMAND381.bin'),raw.source3.command_bytes);
raw.original_submit_ns=gpenmpcNative.rflyOriginalHostMonotonicNs();
try,raw.submitted=x.submitted(uint64(65),raw.original_submit_ns);
catch ex,save(fullfile(outputRoot,'SUBMISSION_FAILURE.mat'),'raw','checks');rethrow(ex);end
writer.println('execute');line=string(reader.readLine());disp(line);raw.cpp_execute=jsondecode(line);
msg=readBytes(fullfile(outputRoot,'FEEDBACK1112.bin'));rx=gpenmpcNative.rflyOriginalHostMonotonicNs();
raw.decoded=gpenmpcNative.RflyCommittedFeedbackDecoder(msg,rx);
try,raw.feedback=x.feedback(msg,rx,rx,origin);
catch ex,raw.failure_status=x.status();save(fullfile(outputRoot,'FEEDBACK_FAILURE.mat'),'raw','checks');rethrow(ex);end
check('first_flight_reuses_real_startup_slot_without_second_solver', ...
    raw.source3.scheduler.submit.status=="STARTUP_OUTER_ALREADY_COMMITTED" ...
    &&raw.source3.scheduler.clock.dispatch_solver&&raw.source3.scheduler.clock.dispatch_slot_index==0 ...
    &&raw.source3.scheduler.clock.effective_flight_dt_s==0 ...
    &&raw.source3.scheduler.clock.next_outer_leg_time_s==.30 ...
    &&x.status().coordinator.actual_solver_submissions==1 ...
    &&x.status().coordinator.service.physical_runtime.begin_count==1 ...
    &&x.status().coordinator.service.physical_runtime.current_leg==initialLeg ...
    &&x.status().coordinator.service.phase_s>0&&x.status().coordinator.service.phase_s<.0101);
clock=x.status().coordinator.source_clock;
clockEvent=struct('sample_timestamp_ns',clock.last_sample_timestamp_ns+uint64(300000000), ...
    'actual_source_delta_us',uint64(10000),'leg_id',1,'flight_active',true, ...
    'reset_leg',false,'solver_in_flight',false,'phase_rate',1);
[~,clockReceipt]=gpenmpcNative.canonicalMeasuredSourceOuterClock(clock,clockEvent);
check('measured_source_clock_next_permission_is_point30',clockReceipt.accepted ...
    &&clockReceipt.dispatch_solver&&clockReceipt.dispatch_due_leg_time_ns==uint64(300000000));
for k=1:7
    [m,status]=deserializemsg(dialect,raw.source3.packets{k},OutputAllMessage=true);
    check("actual_MATLAB_MAVLink_frame_"+k,numel(m)==1&&status==0&&m.Payload.payload_type==42002);
end
check('actual_C_RFC1_updates_same_owned_service',raw.feedback.accepted ...
    &&x.status().coordinator.service.physical_runtime.control_commit_count==1 ...
    &&raw.cpp_execute.actual_generated_c_steps==1&&raw.cpp_execute.failed==0);
check('held_outer_deadline_not_renewed_by_new_reference',raw.decoded.token.outer_valid_until_us==uint64(1410000) ...
    &&raw.decoded.token.reference_valid_until_us==uint64(1420000));
check('registered_fixture_generation_not_host_constant42',raw.decoded.token.identity.boot_generation==echo.process_session_generation ...
    &&echo.process_session_generation==1&&raw.decoded.token.sample_generation==65);
check('single_original_scheduler_no_extra_solver_from_reference_poll',x.status().coordinator.actual_solver_submissions==1 ...
    &&all(cellfun(@(p)p.source_clock_unchanged,raw.polls)));
check('no_production_bootstrap_physical_or_transport_claim',~x.status().live_registration_proven ...
    &&~x.status().transport_source_authenticated&&~x.status().publication_authority);
check('repeat_feedback_rejected_and_exchange_closes',rejects(@()x.feedback(msg,rx,rx,origin))&&x.status().closed);
raw.legacy_outer_snapshot=test_canonical_outer_snapshot(a);
% Independent real-worker negative controls. Altered times below are marked
% rejected input fixtures, not fresh board observations or emitted commands.
c=gpenmpcNative.CanonicalOuterCoordinator(build,e,tr);ccleanup=onCleanup(@()c.close()); %#ok<NASGU>
now=gpenmpcNative.rflyOriginalHostMonotonicNs();p=gpenmpcNative.RflySnapshotSample(sbytes{1},now,e);[v,w]=observed(63,now);
raw.negative_prepare=c.prepare(now,p,v,w);
now=gpenmpcNative.rflyOriginalHostMonotonicNs();p2=gpenmpcNative.RflySnapshotSample(sbytes{2},now,e);[v,w]=observed(64,now);
check('observed_armed_or_unknown_not_startup',rejectsId(@()c.disarmedStartupSample(now,p2,v,w,true),'gpenmpcNative:CoordinatorStartupState') ...
    &&rejectsId(@()c.disarmedStartupSample(now,p2,v,w,[]),'gpenmpcNative:CoordinatorStartupState'));
check('preparation_source_not_reused_for_startup',rejectsId(@()c.disarmedStartupSample(now,p,v,w,false),'gpenmpcNative:CoordinatorStartupSource'));
raw.negative_startup=c.disarmedStartupSample(now,p2,v,w,false);
check('duplicate_startup_does_not_resubmit_solver',rejectsId(@()c.disarmedStartupSample(now,p2,v,w,false),'gpenmpcNative:CoordinatorStartupState') ...
    &&c.status().actual_solver_submissions==1);
% A startup source must not become a flight source when the worker completes.
check('startup_ticket_cannot_be_first_flight_ticket',rejectsId(@()c.flightSample(now,p2,v,w),'gpenmpcNative:CoordinatorStartupNotFresh') ...
    &&c.status().service.physical_runtime.begin_count==0);
timer=tic;while c.status().service.async_in_flight&&toc(timer)<3
    pause(.001);c.poll(gpenmpcNative.rflyOriginalHostMonotonicNs());
end
raw.negative_ready=c.status();check('negative_controls_still_have_one_real_startup_result',raw.negative_ready.startup.ready ...
    &&raw.negative_ready.service.phase_s==0&&raw.negative_ready.service.physical_runtime.control_commit_count==0);
now=gpenmpcNative.rflyOriginalHostMonotonicNs();p3=gpenmpcNative.RflySnapshotSample(sbytes{3},now,e);[v,w]=observed(65,now);
bad=p3;bad.original_sample_hrt_us=p2.original_sample_hrt_us+uint64(400001);
bad.sample_timestamp_ns=bad.original_sample_hrt_us*uint64(1000);
check('original_board_outer_expiry_rejected_before_flight_or_inner',rejectsId(@()c.flightSample(now,bad,v,w), ...
    'gpenmpcNative:CoordinatorStartupNotFresh')&&c.status().state=="PREPARED_PAUSED" ...
    &&c.status().service.physical_runtime.begin_count==0);
expiry=c.status().startup.original_outer_expiry_host_ns;
while gpenmpcNative.rflyOriginalHostMonotonicNs()<=expiry,pause(.001);end
raw.expired=c.poll(gpenmpcNative.rflyOriginalHostMonotonicNs());
check('poll_cannot_renew_original_host_expiry',~raw.expired.startup.ready ...
    &&raw.expired.startup.original_outer_expiry_host_ns==expiry ...
    &&raw.expired.startup.original_outer_expiry_board_us==uint64(1410000));
now=gpenmpcNative.rflyOriginalHostMonotonicNs();p3=gpenmpcNative.RflySnapshotSample(sbytes{3},now,e);[v,w]=observed(65,now);
check('late_first_flight_rejected_even_with_new_host_receipt',rejectsId(@()c.flightSample(now,p3,v,w), ...
    'gpenmpcNative:CoordinatorStartupNotFresh')&&c.status().service.physical_runtime.begin_count==0 ...
    &&c.status().source_clock.total_flight_time_ns==uint64(0)&&c.status().actual_solver_submissions==1);
raw.negative_final=c.status();
% Drain a distinct archived sample while the worker prepares the first sample.
d=gpenmpcNative.RflyHostExchangeService(build,e,tr,assoc,serializer,dialect,8);
dcleanup=onCleanup(@()d.close()); %#ok<NASGU>
now=gpenmpcNative.rflyOriginalHostMonotonicNs();[v,w]=observed(63,now);
raw.drain_prepare_begin=d.beginPrepare(sbytes{1},now,now,v,w,origin);
now=gpenmpcNative.rflyOriginalHostMonotonicNs();
raw.drained=d.observeDisarmedSnapshot(sbytes{2},now,now,origin,false);
check('actual_disarmed_drain_does_not_overwrite_prepare_or_advance_science', ...
    raw.drained.original_source.position_generation==64&&isempty(raw.drained.packets) ...
    &&~raw.drained.scientific_sample_consumed&&raw.drained.operational_observation_only ...
    &&d.status().context.sources_recorded==2&&d.status().context.retained_sources==0 ...
    &&d.status().coordinator.service.phase_s==0 ...
    &&d.status().coordinator.service.physical_runtime.begin_count==0 ...
    &&d.status().coordinator.actual_solver_submissions==0);
timer=tic;while ~d.status().coordinator.initialized&&toc(timer)<60
    raw.drain_prepare=d.pollPreparation(gpenmpcNative.rflyOriginalHostMonotonicNs());pause(.001);
end
check('drain_did_not_replace_original_preparation_association',raw.drain_prepare.status=="PASS_HOST_PREPARATION" ...
    &&isequaln(raw.drain_prepare.input_boundary,raw.drain_prepare_begin.input_boundary) ...
    &&all(d.status().coordinator.service.last_input_generations==63) ...
    &&raw.drain_prepare.numerical_state_unchanged);
now=gpenmpcNative.rflyOriginalHostMonotonicNs();[v,w]=observed(65,now);
raw.drain_startup=d.disarmedStartupSnapshot(sbytes{3},now,now,v,w,origin,false);
timer=tic;while d.status().context.outer_commits==0&&toc(timer)<3
    d.poll(gpenmpcNative.rflyOriginalHostMonotonicNs());pause(.001);
end
check('next_actual_source_after_drain_is_formal_startup_not_gen0_result', ...
    d.status().context.outer_commits==1&&d.status().coordinator.service.async_accepted==1 ...
    &&d.status().coordinator.service.last_generation==1 ...
    &&raw.drain_startup.original_source.position_generation==65 ...
    &&~isequal(raw.drain_startup.original_source.source_ticket,raw.drain_prepare_begin.original_source.source_ticket));
now=gpenmpcNative.rflyOriginalHostMonotonicNs();
check('retired_drained_source_replay_still_rejected',rejects(@() ...
    d.observeDisarmedSnapshot(sbytes{2},now,now,origin,false))&&d.status().failed);
% Reject a synthetic future event beyond the preparation time cap.
l=gpenmpcNative.CanonicalOuterCoordinator(build,e,tr);lcleanup=onCleanup(@()l.close()); %#ok<NASGU>
now=gpenmpcNative.rflyOriginalHostMonotonicNs();p=gpenmpcNative.RflySnapshotSample(sbytes{1},now,e);[v,w]=observed(63,now);
raw.limit_begin=l.beginPrepare(now,p,v,w);
check('cold_engineering_60s_cap_cannot_become_prepared',rejectsId(@() ...
    l.pollPreparation(now+uint64(60000000000)),'gpenmpcNative:CoordinatorFailClosed') ...
    &&l.status().failed&&~l.status().service.prepared ...
    &&l.status().service.failure_code=="PREPARATION_COLD_LIMIT_EXPIRED" ...
    &&l.status().service.preparation_expired&&l.status().service.last_generation==0);
raw.limit_rejected=l.status();
report=struct('status','PASS_ASYNC_PREPARATION_SAME_WORKER_WITH_ORIGINAL_EXPIRY', ...
    'checks',checks,'test_count',numel(checks),'pass_count',sum([checks.pass]), ...
    'actual_async_submissions',3,'actual_generated_c_steps',1,'actual_cpp_registration_fixture',true, ...
    'original_registered_association',assoc,'live_registration_proven',false,'physical_authorization',false, ...
    'publication_authority',false,'hardware_actions',0,'plant_steps',0,'owned_coordinators',1, ...
    'final_status',x.status());
report.source_sha256=struct('coordinator',gpenmpcNative.fileSha256(which('gpenmpcNative.CanonicalOuterCoordinator')), ...
    'exchange',gpenmpcNative.fileSha256(which('gpenmpcNative.RflyHostExchangeService')), ...
    'measured_source_clock',gpenmpcNative.fileSha256(which('gpenmpcNative.canonicalMeasuredSourceOuterClock')), ...
    'unchanged_clock',gpenmpcNative.fileSha256(which('gpenmpcNative.canonicalOuterClock')));
report.startup_scope='FIRST_LEG_OF_SESSION_ACTUAL_ASYNC_ARCHIVED_SOURCE_AND_SESSION_FIXTURES_NO_ARM_ADMISSION';
report.initial_global_task_leg=initialLeg;
report.new_api_async_preparation_submissions=3;
report.synthetic_future_time_only_in_rejected_60s_cap_fixture=true;
report.source_sha256.service=gpenmpcNative.fileSha256(which('gpenmpcNative.BoardOuterService'));
save(fullfile(outputRoot,'RAW.mat'),'raw','report','-v7.3');
f=fopen(fullfile(outputRoot,'RESULT.json'),'w','n','UTF-8');g=onCleanup(@()fclose(f));fprintf(f,'%s\n',jsonencode(report,PrettyPrint=true));clear g
disp(jsonencode(report));
    function check(n,ok)
        checks(end+1)=struct('name',n,'pass',logical(ok)); %#ok<AGROW>
        if ~ok,save(fullfile(outputRoot,'FAILURE.mat'),'raw','checks');end
        assert(ok,'gpenmpcNative:ExchangeTest','%s',n);
    end
    function [v,w]=observed(g,now)
        v=struct('source','HOST_M600_VIRTUAL_ACTUATOR_INTERFACE','valid',true,'generation',g,'rx_ns',double(now), ...
            'ordering','SOFTWARE_M600_ORDER','rotor_thrust_state_n',ones(6,1)*20,'thrust_effectiveness',ones(6,1), ...
            'state_source','SAME_M600_ACCEPTED_STEP_ROTOR_LAG_STATE','plant_session_id',1);
        w=struct('source','FROZEN_TASK_WIND_ESTIMATOR','valid',true,'generation',g,'rx_ns',double(now),'estimate_xy_mps',zeros(2,1));
    end
end
function s=linux(p),p=char(p);s=['/mnt/' lower(p(1)) strrep(p(3:end),'\','/')];end
function b=readBytes(p),f=fopen(p,'rb');assert(f>=0);g=onCleanup(@()fclose(f));b=fread(f,Inf,'*uint8');end %#ok<NASGU>
function writeBytes(p,b),f=fopen(p,'wb');assert(f>=0);g=onCleanup(@()fclose(f));fwrite(f,b,'uint8');end %#ok<NASGU>
function v=decode(b,kind),v=typecast(b,kind);[~,~,e]=computer;if e=='L',v=swapbytes(v);end;v=v(:);end
function h=hex(b),h=upper(reshape(dec2hex(b,2).',1,[]));end
function yes=rejects(f),yes=false;try,f();catch,yes=true;end;end


function yes=rejectsId(f,id),yes=false;try,f();catch ex,yes=strcmp(ex.identifier,id);end;end
