function report=test_rfly_udp_environment_queue_drain()
% Test one accumulated UDP burst using retained NoUI bytes on loopback.
build=fileparts(fileparts(mfilename('fullpath')));
target=fullfile(build,'tools','UDP_ENVIRONMENT_QUEUE_BURST_HOST_ONLY.mat');
assert(~isfile(target),'gpenmpcHost:ExistingEvidence','Choose an unused output path.');
addpath(fullfile(build,'tools'),fullfile(build,'host_runtime'),fullfile(build,'matlab_validation'),fullfile(build,'m600_coptersim','matlab_validation'));
addpath(gpenmpc_external_path('native_visual_host_source'),'-end');
q=load(gpenmpc_external_path('udp_loopback_fixture'),'cfg');cfg=q.cfg;
assert(isequal(cfg.local_short.environment_ledger_capacity,4096), ...
    'gpenmpcHost:ExistingCapacity','Use the existing 4096-row environment consumer capacity without a new override.');
assert(strcmp(cfg.mavlink_transport.scope,'HOST_ONLY_LOOPBACK')&&cfg.truth_port==62293&& ...
    cfg.local_mavlink_port==62291&&cfg.remote_mavlink_port==62292&&cfg.delivery_environment_contract.remote_port==62296);
addpath(fileparts(cfg.mavlink_transport.source.exact_path));
source=fullfile(gpenmpc_external_path('startup_observation'),'STARTUP_COMPATIBILITY_CHECK','STARTUP_OBSERVATION_RAW.mat');
retained=load(source,'rawIo');rows=retained.rawIo.raw_truth_datagrams;
index=find(cellfun(@(x)numel(x.bytes)==264,rows),1,'first');
assert(~isempty(index),'gpenmpcHost:MissingActualDiagnostic','Retained actual startup must contain a 264-byte diagnostic.');
wire=uint8(rows{index}.bytes(:));
ioPath=which('m600check.makeM600CopterSimIo');classPath=which('gpenmpcNative.RflySoleMavlinkTransport');
hashes={m600check.fileSha256(ioPath),m600check.fileSha256(classPath)};
oldReceipt=gpenmpc_external_path('udp_queue_drain_receipt');
oldReceiptHash=m600check.fileSha256(oldReceipt);
oldVariables=whos('-file',oldReceipt);
beforeRoot=fullfile(build,'tools','udp_queue_drain_reference');
beforeSources={fullfile(beforeRoot,'makeM600CopterSimIo.m'),fullfile(beforeRoot,'test_rfly_udp_environment_queue_drain.m')};
beforeHashes=cellfun(@m600check.fileSha256,beforeSources,'UniformOutput',false);
testPath=mfilename('fullpath');testPath=[testPath '.m'];testHash=m600check.fileSha256(testPath);
inputCount=514;sentCount=0;snapshotCalls=0;takeCalls=0;
io=[];peer=[];raw=struct();drained={};snapshot=[];checks=struct();guard=onCleanup(@finish);
try
    io=m600check.makeM600CopterSimIo(cfg);
    peer=udpport('datagram','IPV4','LocalHost','127.0.0.1','LocalPort',62297);
    before=io.evidence();
    assert(isempty(before.raw_truth_datagrams)&&before.canonical_environment_queue_count==0, ...
        'gpenmpcHost:NonemptyFixture','The isolated receiver must start with no truth/environment records.');
    % No snapshot, take, callback or manual receiver drain inside this loop.
    for k=1:inputCount
        write(peer,wire,'uint8','127.0.0.1',62293);
        sentCount=sentCount+1;
    end
    pause(.05); % Allow delivery before draining the IO queue.
    beforeSnapshot=io.evidence();
    snapshotCalls=snapshotCalls+1;snapshot=io.snapshot();
    afterSnapshot=io.evidence();
    rawDelta=numel(afterSnapshot.raw_truth_datagrams)-numel(beforeSnapshot.raw_truth_datagrams);
    raw=struct('before',before,'before_snapshot',beforeSnapshot,'after_snapshot',afterSnapshot, ...
        'input_bytes',wire,'sent_count',sentCount,'snapshot_calls',snapshotCalls,'take_calls',takeCalls);
    assert(rawDelta==inputCount&&afterSnapshot.canonical_environment_queue_count==inputCount, ...
        'gpenmpcHost:BurstNotAccumulated','Snapshot retained %d/%d raw datagrams and queued %d. ', ...
        rawDelta,inputCount,afterSnapshot.canonical_environment_queue_count);
    takeCalls=takeCalls+1;drained=io.takeCanonicalEnvironmentRecords();
    evidence=io.evidence();native=gpenmpc_rfly_udp_transport_mex('status');
    checks.one_accumulated_burst_before_one_snapshot_and_one_take=sentCount==inputCount&& ...
        snapshotCalls==1&&takeCalls==1&&isempty(beforeSnapshot.raw_truth_datagrams)&& ...
        beforeSnapshot.canonical_environment_queue_count==0&&rawDelta==inputCount&&rawDelta>256&& ...
        afterSnapshot.canonical_environment_queue_count==inputCount;
    checks.all_actual_datagrams_byte_exact=numel(evidence.raw_truth_datagrams)==inputCount&& ...
        all(cellfun(@(r)isequal(uint8(r.bytes(:)),wire),evidence.raw_truth_datagrams))&& ...
        numel(drained)==inputCount&&all(cellfun(@(r)strcmp(r.kind,'DIAGNOSTIC_RX')&&isequal(uint8(r.bytes(:)),wire),drained));
    checks.original_uint64_receive_times_unchanged=numel(drained)==inputCount;
    for k=1:numel(drained)
        rx=drained{k}.original_host_receive_ns;
        checks.original_uint64_receive_times_unchanged=checks.original_uint64_receive_times_unchanged&& ...
            isa(rx,'uint64')&&isscalar(rx)&&rx>0&& ...
            isequal(rx,evidence.raw_truth_datagrams{k}.original_host_receive_ns);
        if k>1,checks.original_uint64_receive_times_unchanged=checks.original_uint64_receive_times_unchanged&& ...
                rx>=drained{k-1}.original_host_receive_ns;end
    end
    checks.shared_capacity_and_overflow_latch=afterSnapshot.canonical_environment_queue_capacity==4096&& ...
        ~afterSnapshot.canonical_environment_queue_overflow&&~evidence.canonical_environment_queue_overflow&& ...
        evidence.canonical_environment_queue_count==0&&numel(evidence.raw_truth_datagrams)==rawDelta&& ...
        isempty(evidence.fatal)&&all(structfun(@(v)v==0,evidence.raw_record_overflow_drops));
    checks.snapshot_not_fatal=isempty(snapshot.fatal);
    checks.no_environment_tx_or_source_binding=isempty(evidence.raw_environment_transmit_datagrams)&& ...
        isempty(evidence.raw_transmit_messages)&&~evidence.canonical_exchange_bind_attempted&& ...
        isempty(evidence.canonical_exchange_association)&&~evidence.delivery_diagnostic_observer.session_bound&& ...
        native.sent_count==0&&~native.failed;
    assert(all(structfun(@logical,checks)),'gpenmpcHost:Checks','Queue/raw/no-authority check failed.');
    assert(isequal(hashes,{m600check.fileSha256(ioPath),m600check.fileSha256(classPath)}), ...
        'gpenmpcHost:SourceChanged','Production source changed during fixture.');
    assert(strcmp(oldReceiptHash,m600check.fileSha256(oldReceipt))&&strcmp(testHash,m600check.fileSha256(testPath)), ...
        'gpenmpcHost:EvidenceChanged','Historical evidence and the current test must remain unchanged.');
    raw.drained=drained;raw.snapshot=snapshot;raw.io=evidence;raw.native=native;raw.take_calls=takeCalls;
    report=struct('scope','HOST_ONLY_ACTUAL_DIAGNOSTIC514_ACCUMULATED_SINGLE_SNAPSHOT_BURST','pass',true,'checks',checks, ...
        'retained_source',source,'retained_source_sha256',m600check.fileSha256(source),'retained_raw_index',index, ...
        'input_count',inputCount,'send_calls_returned',sentCount,'actual_raw_delta',rawDelta, ...
        'snapshot_calls',snapshotCalls,'take_calls',takeCalls,'raw_count',numel(evidence.raw_truth_datagrams), ...
        'queue_capacity_before',256,'queue_capacity_after',cfg.local_short.environment_ledger_capacity, ...
        'capacity_provenance','EXISTING_LOCAL_SHORT_ENVIRONMENT_LEDGER_ENGINEERING_STORAGE_BOUND_NOT_NATIVE_GETTER_RING_OR_TIME_GATE', ...
        'queue_overflow',false,'queue_overflow_evidence','ALL_514_QUEUED_BY_ONE_SNAPSHOT_BEFORE_ONE_SUCCESSFUL_TAKE_AND_FINAL_COUNT_ZERO', ...
        'old_receipt',oldReceipt,'old_receipt_sha256',oldReceiptHash,'old_receipt_variables',{ {oldVariables.name} }, ...
        'comparison_test_pattern','SEPARATE_SEND_AND_DRAIN', ...
        'source_before',{beforeSources},'source_before_sha256',{beforeHashes},'test_source_sha256',testHash, ...
        'source_unchanged',true,'io_source_sha256',hashes{1},'transport_class_sha256',hashes{2}, ...
        'COM',0,'CopterSim',0,'board',0,'HIL',0,'environment_tx',0,'control_commands',0);
    clear guard
    save(target,'raw','report','cfg');disp(jsonencode(report));
catch ex
    failure=struct('identifier',ex.identifier,'message',ex.message,'stack',ex.stack);
    if ~isempty(io),try,raw.failure_io=io.evidence();catch,end,end
    clear guard
    save(target,'raw','drained','snapshot','snapshotCalls','takeCalls','sentCount','checks','cfg','failure');rethrow(ex)
end
    function finish()
        if ~isempty(io),try,io.close();catch,end;io=[];end
        if ~isempty(peer),delete(peer);peer=[];end
    end
end
