function report=test_rfly_session_association(outputRoot)
% Test session association from C++-generated SERIAL_CONTROL fixtures.
arguments,outputRoot (1,1) string,end
build=string(fileparts(fileparts(mfilename('fullpath'))));
addpath(fullfile(build,'host_runtime'),'-begin');assert(~isfolder(outputRoot));mkdir(outputRoot);
originalPwd=pwd;cd(outputRoot);restore=onCleanup(@()cd(originalPwd)); %#ok<NASGU>
root=fullfile(gpenmpc_external_path('rfly_board_commit_consumer'));
packer=fullfile(root,'pack_session_serial_control.exe');
echoBytes=readBytes(fullfile(gpenmpc_external_path('board_commit_exchange_fixture'),'ACTUAL_FIXTURE_ECHO119.bin'));
request=struct('original_host_challenge',decode(echoBytes(6:21)), ...
    'uid',decode(echoBytes(22:29)),'system',echoBytes(30),'component',echoBytes(31), ...
    'host_system',uint8(42),'host_component',uint8(191), ...
    'configuration_payload_sha256',hex(echoBytes(56:87)), ...
    'approved_parameter_sha256','CBF017C734B59715B563A61BCB64D8B142A740007C8D610BB6D4BE54808356A8', ...
    'original_prepare_submit_ns',bitshift(uint64(1),54), ...
    'original_confirm_submit_ns',bitshift(uint64(1),54)+uint64(1000));
authorization=struct('source','OperatorUsbIsolationDeclaration', ...
    'physical_setup_record_sha256',repmat('A',1,64), ...
    'original_record',struct('provenance','HOST_FIXTURE_ONLY_NOT_LIVE_USER_CONFIRMATION', ...
    'statement','USB-only fixture with props removed, actuator power disconnected and fixed wiring.'));
sessionSha=hex(echoBytes(88:119));challenge=hex(echoBytes(6:21));
request.original_confirm_session_sha256=sessionSha;
request.confirmed_physical_setup_record_sha256=authorization.physical_setup_record_sha256;
base=sprintf(['RFLY_SESSION state=1 challenge=%s uid=%u system=%u component=%u registration_hrt_us=%u ' ...
    'session_generation=%u link_generation=%u semantics=1 config_sha=%s session_sha=%s parameter_sha=%s ' ...
    'registered=1 echo_confirmed=0 declared_isolation=0 declaration_is_sensor_proof=0 session_fault=0 start_requests=0 stop_requests=0\r\n'], ...
    challenge,request.uid,request.system,request.component,decode(echoBytes(32:39)), ...
    decode(echoBytes(40:47)),decode(echoBytes(48:55)),request.configuration_payload_sha256,sessionSha,request.approved_parameter_sha256);
confirmed=strrep(strrep(strrep(base,'state=1','state=2'),'echo_confirmed=0','echo_confirmed=1'),'declared_isolation=0','declared_isolation=1');
prepareText=sprintf('nsh> gpenmpc_rfly_session prepare ORIGINAL_ARGUMENTS\r\n%sRFLY_PROFILE original_profile_fixture=1\r\nnsh> ',base);
confirmText=sprintf('nsh> gpenmpc_rfly_session confirm ORIGINAL_ARGUMENTS\r\n%snsh> ',confirmed);
checks=struct('name',{},'pass',{});cases=0;dialect=mavlinkdialect('common.xml',2);
pre=pack(prepareText,request.original_prepare_submit_ns+uint64(10));
con=pack(confirmText,request.original_confirm_submit_ns+uint64(10));
a=gpenmpcNative.RflySessionAssociationDecoder(pre,con,request,authorization,dialect);
prepareRequest=rmfield(request,{'original_confirm_submit_ns','original_confirm_session_sha256','confirmed_physical_setup_record_sha256'});
pending=gpenmpcNative.RflySessionAssociationDecoder(pre,[],prepareRequest,[],dialect);
check('prepare_can_supply_actual_digest_before_confirm_sent',isequal(pending.echo,a.echo) ...
    &&strcmp(pending.execution_session_sha256,sessionSha)&&isequal(pending.prepare_receipt.original_frames,pre));
check('prepare_only_never_registered_association_or_authority', ...
    strcmp(pending.schema,'GPENMPC_RFLY_PREPARED_SESSION_RECEIPT_V1') ...
    &&strcmp(pending.echo_confirmation_result,'NOT_CONFIRMED')&&~pending.publication_authority ...
    &&~pending.physical_authorization&&~pending.live_registration_proven);
check('actual_v116_generated_81_byte_payloads_crc_decode',all(arrayfun(@(f)f.raw_frame(2)==81,pre)) ...
    &&all(a.prepare_receipt.serial_control_target_extensions(:,1)==42) ...
    &&all(a.confirm_receipt.serial_control_target_extensions(:,2)==191));
check('unchanged_registered_association_schema',strcmp(a.schema,'GPENMPC_RFLY_REGISTERED_SESSION_ASSOCIATION_V1') ...
    &&strcmp(a.registration_result,'Registered')&&strcmp(a.echo_confirmation_result,'Confirmed') ...
    &&strcmp(a.execution_session_sha256,sessionSha));
check('exact_uint64_uid_and_challenge_above_flintmax',a.echo.uid==request.uid&&a.echo.uid>uint64(flintmax) ...
    &&isequal(a.echo.host_challenge,request.original_host_challenge));
check('original_shell_bytes_frames_and_host_times_preserved',isequal(a.prepare_receipt.original_frames,pre) ...
    &&isequal(a.confirm_receipt.original_frames,con) ...
    &&isequal(a.prepare_receipt.original_shell_bytes,uint8(prepareText).') ...
    &&isequal(a.confirm_receipt.original_shell_bytes,uint8(confirmText).') ...
    &&a.original_host_receive_ns==con(end).original_host_receive_ns);
check('original_registration_hrt_not_confirmation_renewal',a.echo.board_registration_hrt_us==decode(echoBytes(32:39)) ...
    &&~a.board_confirm_timestamp_present&&~a.cross_boot_unique_identity_claim);
check('human_record_separate_from_board_observation',isequal(a.physical_declaration,authorization) ...
    &&strcmp(a.physical_setup_record_sha256,authorization.physical_setup_record_sha256) ...
    &&a.board_reported_human_declaration_bound&&~a.declaration_is_sensor_proof ...
    &&~a.physical_authorization&&~a.publication_authority&&~a.live_registration_proven ...
    &&~a.transport_source_authenticated&&~a.board_echoes_user_record_sha256 ...
    &&a.original_confirm_command_record_bound);
check('multiple_original_fragments_concatenated_before_parse',numel(pre)>2&&numel(con)>2);
callbackPre=callbackRecords(pre);callbackCon=callbackRecords(con);
ca=gpenmpcNative.RflySessionAssociationDecoder(callbackPre,callbackCon,request,authorization,dialect);
check('actual_callback_schema_same_exact_session',isequal(ca.echo,a.echo) ...
    &&strcmp(ca.execution_session_sha256,a.execution_session_sha256));
check('callback_original_payload_and_origin_preserved_no_reencoding', ...
    isequal(ca.prepare_receipt.original_frames,callbackPre) ...
    &&isequal(ca.confirm_receipt.original_frames,callbackCon) ...
    &&isequal(ca.prepare_receipt.original_shell_bytes,a.prepare_receipt.original_shell_bytes) ...
    &&~any(ca.prepare_receipt.raw_frame_available)&&~ca.prepare_receipt.mavlink_crc_checked ...
    &&all(ca.prepare_receipt.original_mavlinkio_decoded_callback) ...
    &&~any(ca.prepare_receipt.serial_control_target_extensions_known));
bad=callbackCon;bad(1).decoded_message.SystemID=uint8(2);
check('callback_wrong_original_source',rejects(callbackPre,bad,request,authorization));
bad=callbackCon;bad(1).decoded_message=rmfield(bad(1).decoded_message,'ComponentID');
check('callback_missing_original_header',rejects(callbackPre,bad,request,authorization));
bad=callbackCon;bad(1).raw_frame_available=true;
check('callback_cannot_claim_unavailable_rawframe',rejects(callbackPre,bad,request,authorization));
bad=callbackCon;bad(1).decoded_source='RESERIALIZED_HOST_MESSAGE';
check('reserialized_message_not_original_callback',rejects(callbackPre,bad,request,authorization));
bad=callbackCon;bad(1).decoded_message.Payload.count=uint8(71);
check('callback_count_exceeds_original_capacity',rejects(callbackPre,bad,request,authorization));
tokens=regexp(strtrim(base),' ','split');
for k=2:numel(tokens)
    missing=strrep(base,[' ' tokens{k}],'');
    bad=pack(missing,request.original_prepare_submit_ns+uint64(10));
    check("missing_field_"+extractBefore(string(tokens{k}),"="),rejects(bad,con,request,authorization));
end
variants={ ...
    'truncated_final_line',confirmed(1:end-2); ...
    'duplicate_session_line',[confirmed confirmed]; ...
    'duplicate_field',strrep(confirmed,' uid=',' state=2 uid='); ...
    'bad_session_digest',strrep(confirmed,sessionSha,repmat('F',1,64)); ...
    'changed_registration_hrt',strrep(confirmed,'registration_hrt_us=900000','registration_hrt_us=900001'); ...
    'same_address_new_link_generation',strrep(confirmed,'link_generation=1','link_generation=2'); ...
    'wrong_identity',strrep(confirmed,sprintf('uid=%u',request.uid),sprintf('uid=%u',request.uid+uint64(1))); ...
    'uid_overflow',regexprep(confirmed,'uid=[0-9]+','uid=18446744073709551616'); ...
    'negative_integer',strrep(confirmed,'state=2','state=-2'); ...
    'nondecimal_integer',strrep(confirmed,'state=2','state=A'); ...
    'retired_state',strrep(confirmed,'state=2','state=4'); ...
    'already_installed_state',strrep(confirmed,'state=2','state=3'); ...
    'unconfirmed',strrep(confirmed,'echo_confirmed=1','echo_confirmed=0'); ...
    'missing_human_declaration',strrep(confirmed,'declared_isolation=1','declared_isolation=0'); ...
    'sensor_proof_mislabel',strrep(confirmed,'declaration_is_sensor_proof=0','declaration_is_sensor_proof=1'); ...
    'faulted_session',strrep(confirmed,'session_fault=0','session_fault=1'); ...
    'start_already_requested',strrep(confirmed,'start_requests=0','start_requests=1'); ...
    'stop_already_requested',strrep(confirmed,'stop_requests=0','stop_requests=1')};
for k=1:size(variants,1)
    bad=pack(variants{k,2},request.original_confirm_submit_ns+uint64(10));
    check(variants{k,1},rejects(pre,bad,request,authorization));
end
badRequest=request;badRequest.original_host_challenge(1)=badRequest.original_host_challenge(1)+uint64(1);
check('old_challenge_receipts_cannot_satisfy_fresh_request',rejects(pre,con,badRequest,authorization));
badRequest=request;badRequest.approved_parameter_sha256=repmat('E',1,64);
check('wrong_frozen_parameter_sha',rejects(pre,con,badRequest,authorization));
badRequest=request;badRequest.host_component=uint8(190);
check('wrong_actual_serial_control_target',rejects(pre,con,badRequest,authorization));
badRequest=request;badRequest.original_confirm_session_sha256=repmat('B',1,64);
check('original_confirm_command_named_other_session',rejects(pre,con,badRequest,authorization));
badRequest=request;badRequest.confirmed_physical_setup_record_sha256=repmat('B',1,64);
check('original_confirm_command_named_other_user_record',rejects(pre,con,badRequest,authorization));
bothPre=pack(strrep(prepareText,sessionSha,repmat('D',1,64)),request.original_prepare_submit_ns+uint64(10));
bothCon=pack(strrep(confirmText,sessionSha,repmat('D',1,64)),request.original_confirm_submit_ns+uint64(10));
badRequest=request;badRequest.original_confirm_session_sha256=repmat('D',1,64);
check('both_receipts_and_command_cannot_forge_RSE1_digest',rejects(bothPre,bothCon,badRequest,authorization));
bad=con;bad(1).original_host_receive_ns=request.original_confirm_submit_ns-uint64(1);
check('receipt_predates_original_confirm_submit',rejects(pre,bad,request,authorization));
bad=con;bad(2).original_host_receive_ns=bad(1).original_host_receive_ns-uint64(1);
check('original_host_time_reverse',rejects(pre,bad,request,authorization));
bad=pre;bad(1).original_host_receive_ns=double(bad(1).original_host_receive_ns);
check('double_receive_timestamp_not_accepted',rejects(bad,con,request,authorization));
bad=con;bad(1).raw_frame(20)=bitxor(bad(1).raw_frame(20),uint8(1));
check('actual_crc_corruption',rejects(pre,bad,request,authorization));
bad=con;bad(1).raw_frame=bad(1).raw_frame(1:end-1);
check('truncated_actual_mavlink_frame',rejects(pre,bad,request,authorization));
bad=con;bad(1).raw_frame(6)=uint8(2);
check('wrong_actual_mavlink_source',rejects(pre,bad,request,authorization));
badAuthorization=authorization;badAuthorization=rmfield(badAuthorization,'original_record');
check('raw_boolean_without_existing_record_not_authorization',rejects(pre,con,request,badAuthorization));
badAuthorization=authorization;badAuthorization.source='BOARD_SENSOR_PROOF';
check('sensor_claim_does_not_replace_human_record',rejects(pre,con,request,badAuthorization));
report=struct('status','PASS_HOST_ORIGINAL_SERIAL_CONTROL_SESSION_ASSOCIATION', ...
    'checks',checks,'test_count',numel(checks),'pass_count',sum([checks.pass]), ...
    'actual_generated_mavlink_packer',true,'fixture_print_format_from_actual_entry',true, ...
    'retained_actual_cpp_echo_source',fullfile(gpenmpc_external_path('board_commit_exchange_fixture'),'ACTUAL_FIXTURE_ECHO119.bin'), ...
    'hardware_actions',0,'COM_opened',false,'live_registration_proven',false,'physical_authorization',false);
save(fullfile(outputRoot,'RAW.mat'),'a','ca','pending','pre','con','callbackPre','callbackCon','request','authorization','prepareText','confirmText','report');
f=fopen(fullfile(outputRoot,'RESULT.json'),'w','n','UTF-8');g=onCleanup(@()fclose(f));fprintf(f,'%s\n',jsonencode(report,PrettyPrint=true));clear g
disp(jsonencode(report));
    function frames=pack(txt,start)
        cases=cases+1;input=sprintf('shell_%03d.txt',cases);output=sprintf('frames_%03d.bin',cases);
        f=fopen(input,'wb');assert(f>=0);fwrite(f,uint8(txt),'uint8');fclose(f);
        [rc,log]=system(sprintf('"%s" "%s" "%s"',packer,input,output));assert(rc==0,'%s',log);
        bytes=readBytes(output);at=1;frames=struct('raw_frame',{},'original_host_receive_ns',{});
        while at<=numel(bytes)
            n=double(bytes(at))*256+double(bytes(at+1));at=at+2;
            frames(end+1)=struct('raw_frame',bytes(at:at+n-1).', ...
                'original_host_receive_ns',start+uint64(numel(frames))); %#ok<AGROW>
            at=at+n;
        end
        assert(at==numel(bytes)+1);
    end
    function yes=rejects(p,c,r,u)
        yes=false;
        try,gpenmpcNative.RflySessionAssociationDecoder(p,c,r,u,dialect);
        catch ex,yes=startsWith(string(ex.identifier),"gpenmpcNative:Session");if ~yes,rethrow(ex);end,end
    end
    function records=callbackRecords(frames)
        records=struct('decoded_message',{},'original_host_receive_ns',{},'decoded_source',{},'raw_frame_available',{});
        for j=1:numel(frames)
            frame=frames(j).raw_frame;[message,status]=deserializemsg(dialect,frame,OutputAllMessage=true);assert(status==0);
            % Exact installed Subscriber callback shape, fed here by original
            % generated fixture bytes. This is NOT a live callback receipt.
            m=struct('MsgID',message.MsgID,'SystemID',frame(6),'ComponentID',frame(7),'Seq',frame(5),'Payload',message.Payload);
            records(end+1)=struct('decoded_message',m,'original_host_receive_ns',frames(j).original_host_receive_ns, ...
                'decoded_source','ORIGINAL_MAVLINKIO_SERIAL_CONTROL_CALLBACK','raw_frame_available',false); %#ok<AGROW>
        end
    end
    function check(name,yes)
        checks(end+1)=struct('name',name,'pass',logical(yes)); %#ok<AGROW>
        assert(yes,'gpenmpcNative:SessionTest','%s',name);
    end
end
function v=decode(b)
v=typecast(b(:),'uint64');[~,~,endian]=computer;if endian=='L',v=swapbytes(v);end;v=v(:);
end
function s=hex(b),s=upper(reshape(dec2hex(b,2).',1,[]));end
function b=readBytes(p)
f=fopen(p,'rb');assert(f>=0);g=onCleanup(@()fclose(f));b=fread(f,Inf,'*uint8'); %#ok<NASGU>
end
