function audit=validate_canonical_cambridge_binding(task,cfg,ledger,mission,method,timeline)
% Validate task identity and reference data in memory.
checks=struct('name',{},'pass',{});
check('mission',string(task.mission_id)==string(cfg.mission_id) && ...
    string(task.mission_id)==string(mission.mission_id) && ...
    string(task.mission_id)==string(method.planning_identity.mission_id) && ...
    string(task.mission_id)==string(ledger.mission_config.mission_id));
check('planner',string(task.planner_id)==string(cfg.planner_id) && ...
    string(task.planner_id)==string(ledger.multi_urban_identity.planning_method) && ...
    string(task.planner_id)==string(method.planning_identity.planner_id));
check('mission_payload',string(task.mission_payload_sha256)==string(cfg.mission_payload_sha256) && ...
    string(task.mission_payload_sha256)==string(method.planning_identity.mission_payload_sha256));
check('plan_payload',string(task.plan_payload_sha256)==string(cfg.plan_payload_sha256) && ...
    string(task.plan_payload_sha256)==string(ledger.plans(1).plan_payload_sha256) && ...
    string(task.plan_payload_sha256)==string(method.planning_identity.plan_payload_sha256));
check('reference_source_method',string(ledger.method)==string(cfg.reference_source_method));
check('method',string(method.internal_identity.architecture)=="A1_COORDINATED_PHYSICAL" && ...
    ~method.internal_identity.architecture_requirements.ordinary_b2);
check('environment_exact',isequaln(task.mission_config,ledger.mission_config));
check('visit_order',isequal(double(task.visit_order(:)),double(cfg.visit_order(:))) && ...
    isequal(double(task.visit_order(:)),double(ledger.plans(1).visit_order_roster_indices(:))));
check('route_candidates',isequal(string(task.route_candidate_ids(:)),string(cfg.route_candidate_ids(:))) && ...
    isequal(string(task.route_candidate_ids(:)),string({ledger.plans(1).legs.route_candidate_id}).'));
check('depot_and_return',max(abs(task.reference.position_m(1,:)-double(mission.depot.xyz_m(:).')))<1e-8 && ...
    max(abs(task.reference.position_m(end,:)-double(mission.depot.xyz_m(:).')))<1e-8);
check('initial_payload',abs(task.reference.payload_kg(1)-mission.initial_payload_kg)<1e-12);
ref=task.reference; source=timeline.arrays;
check('sample_period',task.mission_config.simulation.sample_period_s==0.01);
check('time',all(isfinite(ref.global_time_s)) && all(diff(ref.global_time_s)>0) && ...
    abs(ref.global_time_s(end)-timeline.task_end_s)<1e-9);
transit=ref.service_ordinal==0;
check('transit_row_count',nnz(transit)==numel(timeline.source_time_s));
fields={'position_m','velocity_mps','acceleration_mps2','jerk_mps3', ...
    'actual_wind_xy_mps','wind_estimate_xy_mps','payload_kg','leg_index','phase_code'};
sourceNames={'reference_position_m','reference_velocity_mps','reference_acceleration_mps2', ...
    'reference_jerk_mps3','actual_wind_xy_mps','wind_estimate_xy_mps','payload_kg','leg_index','phase_code'};
for i=1:numel(fields)
    a=double(ref.(fields{i})(transit,:)); b=double(source.(sourceNames{i}));
    check(['transit_exact_' fields{i}],isequal(a,b));
end
check('time_retiming_only',isequal(double(ref.global_time_s(transit)),double(timeline.time_s)));
check('payload_change_count',nnz(diff(ref.payload_kg)~=0)==cfg.delivery_count);
change=find(diff(ref.payload_kg)~=0)+1;
check('payload_at_ascent_start',all(ref.phase_code(change)==12) && ...
    all(abs(ref.position_m(change,3)-cfg.physical_service_profile.contact_plane_up_m)<1e-8));
check('ground_service_no_teleport',task.physical_service.service_teleport_count==0 && ...
    task.physical_service.payload_change_only_on_ground && ...
    task.physical_service.ground_dwell_s==cfg.physical_service_profile.ground_dwell_s);
for ordinal=1:cfg.delivery_count
    ix=find(ref.service_ordinal==ordinal & ref.phase_code==11);
    rec=timeline.service_records(ordinal); node=task.visit_order(ordinal);
    points=mission.service_points; point=points([points.roster_index]==node);
    check(sprintf('service_%d_unique_node',ordinal),numel(point)==1);
    check(sprintf('service_%d_ground_point',ordinal),~isempty(ix) && ...
        max(abs(ref.position_m(ix,1:2)-reshape(double(point.xyz_m(1:2)),1,2)),[],'all')<1e-8 && ...
        all(ref.position_m(ix,3)==cfg.physical_service_profile.contact_plane_up_m));
    dt=task.mission_config.simulation.sample_period_s;
    dwell=ref.global_time_s(ix(end))-ref.global_time_s(ix(1))+dt;
    check(sprintf('service_%d_duration',ordinal),abs(dwell-point.service_duration_s)<=dt+1e-8 && ...
        rec.ground_dwell_s==point.service_duration_s);
    check(sprintf('service_%d_payload',ordinal),abs(ref.payload_kg(change(ordinal)-1)- ...
        ref.payload_kg(change(ordinal))-point.package_mass_kg)<1e-10);
end
check('return_payload_zero',abs(ref.payload_kg(end))<1e-12);
check('no_parent_control_or_state',task.parent_control_injection_prohibited && ...
    task.parent_state_injection_prohibited && ~timeline.parent_control_output_reused);
audit=struct('checks',checks,'checks_total',numel(checks),'checks_passed',sum([checks.pass]), ...
    'source_rows',nnz(transit),'delivery_count',cfg.delivery_count,'visit_order',task.visit_order, ...
    'map_city',string(ledger.multi_urban_identity.city_id),'hardware_actions',0);
    function check(name,condition)
        ok=isscalar(condition) && logical(condition);
        checks(end+1)=struct('name',string(name),'pass',ok); %#ok<AGROW>
        assert(ok,'gpenmpcTask:CanonicalMismatch','Canonical task mismatch: %s',name);
    end
end
